/**
 * `blog` starter templates — seven ways to publish and be read: a personal journal,
 * a photo-led travel diary, a recipe index, an engineering notebook, a personal-finance
 * letter, a parenting mailbag, and an independent product-review desk.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const blogTemplates: Template[] = [
  // ── 1. Personal journal ────────────────────────────────────────────────────
  tpl({
    id: 'blog-journal',
    vertical: 'blog',
    label: 'Personal journal — Editorial',
    description: 'A quiet, type-led writing journal that opens with the newest essay in full and keeps the archive underneath.',
    tags: ['journal', 'long-form', 'newsletter', 'light', 'personal'],
    layout: 'editorial',
    preset: 'mono',
    meta: { title: 'Marginalia — Esme Whitlock', description: 'A slow journal about attention, walking, and the things worth writing down. New essay most Sundays.', lang: 'en', favicon: '✒️' },
    blocks: [
      b('nav', 'nav', { brand: 'Marginalia', sticky: false, links: [{ label: 'Latest', href: '#essay' }, { label: 'Archive', href: '#archive' }, { label: 'About', href: '#about' }], cta: { label: 'Subscribe', href: '#subscribe' } }),
      b('hero', 'hero', { eyebrow: 'Essay 214 · Sunday, 12 October', headline: 'Notes from the long way round', subhead: 'One essay most Sundays about paying attention: walking the same three miles, reading slowly, and writing things down before they blur.', align: 'left', minHeight: 'md', overlay: 'none', cta: { label: 'Read this week’s essay', href: '#essay' } }),
      b('essay', 'blog-post', {
        title: 'The three miles I have walked four hundred times',
        date: '12 October 2025',
        author: 'Esme Whitlock',
        cover: img('marginalia-canal-path'),
        coverAlt: 'A towpath in low autumn light, bare trees on the far bank',
        body: [
          { kind: 'paragraph', text: 'There is a loop from my front door in Sheffield out along the canal, up through Norfolk Heritage Park and back down Duke Street. It takes fifty-two minutes at my usual pace and I have walked it, at a conservative estimate, four hundred times.' },
          { kind: 'paragraph', text: 'The first hundred were for exercise. The next hundred were for thinking, which is a polite way of saying I was worrying with better scenery. Somewhere after that it stopped being for anything, and that is when it got interesting.' },
          { kind: 'heading', text: 'What repetition gives you' },
          { kind: 'paragraph', text: 'A route you know by heart stops competing for your attention. You are not navigating, so you notice: the heron that stands on the same lock gate every October, the graffiti under the bridge that gets painted over each spring and returns by June, the exact week the hawthorn turns.' },
          { kind: 'quote', text: 'Novelty is loud. The same three miles, four hundred times, is how you learn to hear anything quieter than novelty.' },
          { kind: 'paragraph', text: 'I keep a pocket notebook for it now — not a journal, nothing so grand. Just a line a walk. Half of them are useless. The other half became the last two years of this newsletter.' },
          { kind: 'heading', text: 'Three lines from this month' },
          { kind: 'bullet', text: '3 Oct — The lock keeper’s cottage has a new door, painted the exact green of the old one. Someone cared about that.' },
          { kind: 'bullet', text: '7 Oct — Frost on the recreation ground before it was cold enough to notice on my hands.' },
          { kind: 'bullet', text: '11 Oct — Two people arguing about a bus timetable with genuine, sustained warmth. Married, I think, decades.' },
          { kind: 'paragraph', text: 'Next week: why I stopped reading three books at once, and what happened to how much I remembered.' },
        ],
      }),
      b('break', 'divider', { style: 'dots' }),
      b('archive', 'blog-list', {
        title: 'The archive',
        columns: 2,
        posts: [
          { title: 'On finishing things badly', excerpt: 'A defence of the mediocre completed draft over the immaculate abandoned one, written after clearing out a drawer of them.', href: '#essay', date: '5 October 2025', tag: 'Writing' },
          { title: 'The reading year I kept a ledger for', excerpt: 'I logged every book for twelve months — page counts, where I read it, whether I finished. The numbers were less interesting than the excuses.', href: '#essay', date: '28 September 2025', tag: 'Reading' },
          { title: 'Letters I did not send', excerpt: 'Writing to someone specific fixes almost every problem with a first draft. You do not have to post it afterwards.', href: '#essay', date: '21 September 2025', tag: 'Writing' },
          { title: 'A week without a single recommendation', excerpt: 'No algorithm chose anything for me for seven days. Here is what I read, watched and listened to instead, and how I found it.', href: '#essay', date: '14 September 2025', tag: 'Attention' },
          { title: 'The house my grandmother described', excerpt: 'She could walk me through every room of a house demolished in 1971. I tried to write it down before it went with her.', href: '#essay', date: '7 September 2025', tag: 'Memory' },
          { title: 'In praise of the second coffee', excerpt: 'The first one is chemistry. The second one, taken sitting down with nothing else happening, is the whole point.', href: '#essay', date: '31 August 2025', tag: 'Attention' },
        ],
      }),
      b('about', 'about', {
        eyebrow: 'Who is writing',
        title: 'Esme Whitlock',
        body: 'I write Marginalia from a first-floor flat in Sheffield, mostly on Sunday mornings before anyone else in the building is awake. For nine years I edited other people’s non-fiction for a living, which cured me of any belief that good writing arrives fully formed. This is where I do the arriving in public. There are no sponsors, no affiliate links and no plans for either. About four thousand people read it, which is the exact size I want it to be: small enough that I still reply to every message, large enough that it feels like sending post somewhere rather than talking to myself.',
        image: img('marginalia-desk-morning'),
        imageAlt: 'A writing desk with a notebook, fountain pen and half-drunk coffee',
        imageSide: 'left',
      }),
      b('subscribe', 'newsletter', { title: 'One essay, most Sundays', intro: 'Free, roughly 1,200 words, and never more than once a week. Unsubscribe from the bottom of any issue — I will not chase you.', placeholder: 'you@example.com', submitLabel: 'Send me Marginalia', successMessage: 'You’re on the list — the next essay lands Sunday morning.' }),
      b('elsewhere', 'social-links', { title: 'Elsewhere', layout: 'row', variant: 'labeled', align: 'start', links: [
        { platform: 'rss', href: '#', label: 'RSS feed' },
        { platform: 'mastodon', href: '#', label: 'Mastodon' },
        { platform: 'email', href: '#', label: 'Reply by email' },
      ] }),
      b('footer', 'footer', { brand: 'Marginalia', tagline: 'Written in Sheffield. Sent on Sundays.', links: [{ label: 'Archive', href: '#archive' }, { label: 'About', href: '#about' }, { label: 'Subscribe', href: '#subscribe' }], copyright: '© Esme Whitlock' }),
    ],
  }),

  // ── 2. Travel diary ────────────────────────────────────────────────────────
  tpl({
    id: 'blog-travel',
    vertical: 'blog',
    label: 'Travel diary — Showcase',
    description: 'A photo-first travel journal where the pictures carry the story, with a where-I-am-now log and a route map.',
    tags: ['travel', 'gallery', 'photography', 'newsletter', 'social'],
    layout: 'showcase',
    preset: 'ocean',
    meta: { title: 'Twelve Time Zones — Rafa Okonkwo', description: 'Slow overland travel, photographed. Currently working east from Lisbon by train, ferry and whatever else shows up.', lang: 'en', favicon: '🧭' },
    blocks: [
      b('nav', 'nav', { brand: 'Twelve Time Zones', sticky: true, links: [{ label: 'Photos', href: '#photos' }, { label: 'Dispatches', href: '#dispatches' }, { label: 'Where I am', href: '#now' }, { label: 'Route', href: '#route' }], cta: { label: 'Get the dispatch', href: '#subscribe' } }),
      b('hero', 'hero', { eyebrow: 'Day 291 · Batumi, Georgia', headline: 'Overland, slowly, with a camera', subhead: 'No flights since March. Eleven countries, forty-one trains, three ferries and one very regrettable overnight bus.', align: 'center', minHeight: 'full', image: img('twelve-zones-black-sea-dawn'), overlay: 'dark', cta: { label: 'See the last frames', href: '#photos' } }),
      b('photos', 'gallery', { layout: 'masonry', columns: 3, gap: 'lg', lightbox: true, items: [
        { src: img('twelve-zones-sleeper-window'), alt: 'View from a sleeper train window at dawn', caption: 'Bucharest–Sofia, 05:40. The dining car had run out of everything but tea.' },
        { src: img('twelve-zones-tbilisi-balcony'), alt: 'Carved wooden balconies on a leaning old-town house', caption: 'Sololaki, Tbilisi. Every one of these balconies is held up by faith and paint.' },
        { src: img('twelve-zones-ferry-deck'), alt: 'Passengers asleep on a ferry deck under blankets', caption: 'Deck class, Black Sea. Nine hours, no cabins left, no regrets.' },
        { src: img('twelve-zones-market-plums'), alt: 'Crates of plums and peaches at a roadside market', caption: 'Roadside stall near Kutaisi. Two lari for more plums than I could carry.' },
        { src: img('twelve-zones-mountain-road'), alt: 'A gravel road switchbacking up a green mountainside', caption: 'The road to Ushguli, which is a road only in the loosest sense.' },
        { src: img('twelve-zones-night-platform'), alt: 'An empty station platform lit by orange lamps at night', caption: 'Waiting for the 23:15 that turned out to be the 01:50.' },
      ] }),
      b('dispatches', 'blog-list', {
        title: 'Dispatches',
        columns: 3,
        posts: [
          { title: 'How to sleep on a train that does not want you to', excerpt: 'Nine months of couchettes and seat-61 improvisation, distilled into six things I would tell my March self.', href: '#dispatches', image: img('twelve-zones-couchette'), date: '9 October 2025', tag: 'Practical' },
          { title: 'The Batumi bus station rule', excerpt: 'Whatever the timetable says, the marshrutka leaves when it is full. Once you accept this, Georgia becomes a much calmer country.', href: '#dispatches', image: img('twelve-zones-marshrutka'), date: '2 October 2025', tag: 'Georgia' },
          { title: 'What 291 days overland actually costs', excerpt: 'Full spreadsheet: €11,400 so far, of which transport is less than a third and laundry is embarrassingly more than I expected.', href: '#dispatches', image: img('twelve-zones-notebook-budget'), date: '24 September 2025', tag: 'Money' },
          { title: 'Three days in a Svaneti guesthouse with no plan', excerpt: 'I meant to stay one night. The family had other ideas, most of them involving cheese bread and a very persuasive grandmother.', href: '#dispatches', image: img('twelve-zones-svaneti-house'), date: '15 September 2025', tag: 'Georgia' },
          { title: 'Carrying one camera and one lens for a year', excerpt: 'A 35mm prime and no second body. What I have missed, what I stopped missing, and the frames I got because I stopped choosing.', href: '#dispatches', image: img('twelve-zones-camera-bag'), date: '6 September 2025', tag: 'Photography' },
          { title: 'The ferry that does not appear on any website', excerpt: 'It leaves twice a week, sells tickets from a portacabin, and is the only sensible way east. Here is how to actually board it.', href: '#dispatches', image: img('twelve-zones-port-office'), date: '29 August 2025', tag: 'Practical' },
        ],
      }),
      b('now', 'feed', {
        title: 'Where I am, roughly',
        layout: 'list',
        items: [
          { title: 'Batumi, Georgia', subtitle: 'Now · until 18 October', text: 'Sea-facing room above a bakery, catching up on eleven weeks of unedited film scans.', badge: 'Here' },
          { title: 'Kutaisi → Tbilisi', subtitle: 'Late October', text: 'Slow train, then two weeks static to renew a visa and finally fix the tripod.', badge: 'Next' },
          { title: 'Yerevan, Armenia', subtitle: 'November', text: 'Overnight from Tbilisi if the sleeper is running, marshrutka if it is not.', badge: 'Planned' },
          { title: 'Somewhere with a winter', subtitle: 'December–February', text: 'Open to suggestions. The only rule is that I get there without flying.', badge: 'Undecided' },
        ],
      }),
      b('route', 'map', { query: 'Batumi, Georgia', zoom: 6, height: 420, label: 'Currently: Batumi, on the Black Sea coast' }),
      b('subscribe', 'newsletter', { title: 'The dispatch', intro: 'One long letter a fortnight with the photos that did not make the site, the costs, and the parts I got wrong. About 3,000 readers.', placeholder: 'you@example.com', submitLabel: 'Send me the dispatch', successMessage: 'Welcome aboard — the next dispatch goes out from wherever I am on Sunday.' }),
      b('social', 'social-links', { title: 'Follow along between dispatches', layout: 'row', variant: 'icon', align: 'center', links: [
        { platform: 'instagram', href: '#', label: 'Instagram' },
        { platform: 'youtube', href: '#', label: 'YouTube' },
        { platform: 'rss', href: '#', label: 'RSS' },
        { platform: 'email', href: '#', label: 'Email' },
      ] }),
      b('footer', 'footer', { brand: 'Twelve Time Zones', tagline: 'Overland since March. No flights, no sponsors.', links: [{ label: 'Dispatches', href: '#dispatches' }, { label: 'Photos', href: '#photos' }, { label: 'Subscribe', href: '#subscribe' }], copyright: '© Rafa Okonkwo · All photographs my own' }),
    ],
  }),

  // ── 3. Food & recipe blog ──────────────────────────────────────────────────
  tpl({
    id: 'blog-recipes',
    vertical: 'blog',
    label: 'Food & recipe blog — Catalogue',
    description: 'A searchable recipe index that puts the whole catalogue up front, with one full recipe written out in the body.',
    tags: ['food', 'recipes', 'catalogue', 'newsletter', 'family'],
    layout: 'catalogue',
    preset: 'sand',
    meta: { title: 'Salt & Sunday — weeknight cooking from Portland', description: 'Tested recipes for actual weeknights: short ingredient lists, one pan where possible, and honest timings.', lang: 'en', favicon: '🥘' },
    blocks: [
      b('notice', 'announcement-bar', { text: 'New this week: the winter braise index — 22 recipes, all tested twice.', linkLabel: 'Browse recipes', href: '#recipes', tone: 'promo', dismissible: true }),
      b('nav', 'nav', { brand: 'Salt & Sunday', sticky: true, links: [{ label: 'Recipes', href: '#recipes' }, { label: 'This week', href: '#feature' }, { label: 'Pantry', href: '#pantry' }, { label: 'About', href: '#about' }], cta: { label: 'Get Fridays', href: '#subscribe' } }),
      b('find', 'search', { layout: 'bar', placeholder: 'Search 380 recipes — “sheet pan”, “no oven”, “under 30 min”…', label: 'Search the recipe index', buttonLabel: 'Search', name: 'q', align: 'center' }),
      b('recipes', 'blog-list', {
        title: 'The index',
        columns: 3,
        posts: [
          { title: 'Sheet-pan gochujang chicken with cabbage', excerpt: 'One pan, 40 minutes, and the cabbage is the part people ask about. Uses a whole jar of gochujang eventually, I promise.', href: '#feature', image: img('salt-sunday-gochujang-tray'), date: 'January 17', tag: 'Weeknight' },
          { title: 'White beans, a lot of olive oil, and greens', excerpt: 'The recipe I cook when I do not want to cook. Ten minutes if the beans are canned, and they should be.', href: '#feature', image: img('salt-sunday-white-beans'), date: 'January 10', tag: '15 minutes' },
          { title: 'Sunday ragù that forgives you', excerpt: 'Four hours, but only twelve minutes of them are yours. Freezes in flat bags; feeds four people twice.', href: '#feature', image: img('salt-sunday-ragu-pot'), date: 'January 3', tag: 'Batch' },
          { title: 'Cold-oven potatoes', excerpt: 'Start them in an oven you have not turned on yet. Crisper skins, no parboiling, no arguments in the comments please.', href: '#feature', image: img('salt-sunday-potatoes'), date: 'December 20', tag: 'Sides' },
          { title: 'The lentil soup I make every January', excerpt: 'Brown lentils, a parmesan rind, more lemon than seems reasonable. Costs about $6 for a pot that lasts three days.', href: '#feature', image: img('salt-sunday-lentil-soup'), date: 'December 12', tag: 'Budget' },
          { title: 'Buttermilk cornbread in a cast-iron pan', excerpt: 'Not sweet. Preheat the fat until it smokes a little — that edge is the entire reason to make it in iron.', href: '#feature', image: img('salt-sunday-cornbread'), date: 'December 5', tag: 'Baking' },
        ],
      }),
      b('feature', 'blog-post', {
        title: 'Sheet-pan gochujang chicken with charred cabbage',
        date: 'January 17, 2026',
        author: 'June Halloran',
        cover: img('salt-sunday-feature-tray'),
        coverAlt: 'A sheet pan of glazed chicken thighs and browned cabbage wedges',
        body: [
          { kind: 'paragraph', text: 'This has been on the site since 2021 and it is still the recipe I get the most email about. I retested it in November with a shorter marinade and a hotter oven, and the version below is the one to use.' },
          { kind: 'paragraph', text: 'Serves 4 · Active 15 minutes · Total 45 minutes · One sheet pan' },
          { kind: 'heading', text: 'Ingredients' },
          { kind: 'bullet', text: '8 bone-in, skin-on chicken thighs (about 2½ lb / 1.1 kg)' },
          { kind: 'bullet', text: '3 tbsp gochujang, 2 tbsp soy sauce, 1 tbsp honey, 1 tbsp rice vinegar, 2 grated garlic cloves' },
          { kind: 'bullet', text: '1 small green cabbage, cut into 6 wedges through the core' },
          { kind: 'bullet', text: '2 tbsp neutral oil, plus scallions and toasted sesame to finish' },
          { kind: 'heading', text: 'Method' },
          { kind: 'paragraph', text: '1. Heat the oven to 425°F / 220°C with a rack in the upper third. Whisk the gochujang, soy, honey, vinegar and garlic in a large bowl, add the thighs, and turn to coat. Fifteen minutes on the counter is enough; overnight in the fridge is better but not required.' },
          { kind: 'paragraph', text: '2. Toss the cabbage wedges with the oil and a good pinch of salt and lay them cut-side down on one half of a large sheet pan. Nestle the chicken skin-side up on the other half and scrape any remaining marinade over the thighs only — it burns on the cabbage.' },
          { kind: 'paragraph', text: '3. Roast 30–35 minutes, until the skin is lacquered and a thigh reads 175°F / 79°C at the bone. If the glaze is not dark at the edges, give it 3 minutes under the broiler and stand there watching it.' },
          { kind: 'quote', text: 'If your cabbage is pale, your pan was too crowded. Use two pans before you use a smaller cabbage.' },
          { kind: 'heading', text: 'Notes from four years of emails' },
          { kind: 'bullet', text: 'Boneless thighs work at 400°F for 22 minutes, but you lose the skin, which is most of the joy.' },
          { kind: 'bullet', text: 'Gochujang brands vary wildly in heat. Start at 2 tbsp if yours is new to you.' },
          { kind: 'bullet', text: 'Leftovers shredded into rice with a fried egg is arguably the better meal.' },
        ],
      }),
      b('subscribe', 'newsletter', { title: 'Friday dinner plan', intro: 'Every Friday: three recipes, one shopping list, and what I actually cooked that week including the failures.', placeholder: 'you@example.com', submitLabel: 'Send me Fridays', successMessage: 'Done — your first dinner plan arrives this Friday morning.' }),
      b('pantry', 'accordion', {
        title: 'Pantry questions I get every week',
        items: [
          { heading: 'What do you keep in the fridge door at all times?', body: 'Gochujang, doubanjiang, a tube of tomato paste, fish sauce, Dijon, and whatever citrus is cheap. Between those six things and an onion there is dinner in almost any week.' },
          { heading: 'Do I need a scale?', body: 'For baking, yes, and a $15 one is fine. For everything else on this site the volume measures are tested and honest — I do not hide behind grams to avoid retesting.' },
          { heading: 'Why are your timings longer than other sites?', body: 'Because I time them with a phone on the counter while actually cooking, including the chopping. A recipe that says "10 minutes" and means "10 minutes if everything is already prepped" is lying to you.' },
          { heading: 'Can I halve the batch recipes?', body: 'The braises and soups, yes, straight down the middle. The ragù, no — halving it changes the reduction time in ways that are not worth the math. Freeze the other half instead.' },
        ],
      }),
      b('about', 'about', {
        eyebrow: 'The kitchen',
        title: 'Cooked and photographed in Portland, Oregon',
        body: 'Salt & Sunday started in 2019 as a shared note between me and two friends who kept asking what I was making. It is now about 380 recipes, all of them cooked at least twice in a normal home kitchen with a normal oven that runs 15 degrees hot. I develop everything on a weeknight schedule: if a recipe cannot survive being made at 6:40pm by a tired person, it does not go up. Nothing here is sponsored, and the ingredient lists are short because groceries in this city are not cheap.',
        image: img('salt-sunday-kitchen'),
        imageAlt: 'A home kitchen counter with a wooden board, knives and a bowl of citrus',
        imageSide: 'right',
      }),
      b('social', 'social-links', { title: 'Cooking along?', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'instagram', href: '#', label: 'Instagram' },
        { platform: 'tiktok', href: '#', label: 'TikTok' },
        { platform: 'rss', href: '#', label: 'RSS' },
      ] }),
      b('footer', 'footer', { brand: 'Salt & Sunday', tagline: 'Weeknight recipes, tested twice, Portland OR.', links: [{ label: 'Recipe index', href: '#recipes' }, { label: 'Pantry', href: '#pantry' }, { label: 'About', href: '#about' }], copyright: '© June Halloran' }),
    ],
  }),

  // ── 4. Tech / engineering blog ─────────────────────────────────────────────
  tpl({
    id: 'blog-engineering',
    vertical: 'blog',
    label: 'Engineering notebook — Minimal',
    description: 'A stripped-back engineering blog: one long write-up, a searchable index, and nothing else competing for attention.',
    tags: ['engineering', 'long-form', 'dark', 'newsletter', 'remote'],
    layout: 'minimal',
    preset: 'midnight',
    meta: { title: 'Tail Latency — Devika Rao', description: 'Write-ups on distributed systems, database internals and the incidents that taught me something. Roughly monthly.', lang: 'en', favicon: '📉' },
    blocks: [
      b('nav', 'nav', { brand: 'tail-latency', sticky: false, links: [{ label: 'Posts', href: '#posts' }, { label: 'Latest', href: '#post' }], cta: { label: 'RSS', href: '#' } }),
      b('hero', 'hero', { eyebrow: 'Devika Rao · Bengaluru', headline: 'Tail Latency', subhead: 'Notes on distributed systems, storage engines, and the incidents that taught me more than the design docs did. Roughly one post a month, always with the numbers.', align: 'left', minHeight: 'sm', overlay: 'none' }),
      b('post', 'blog-post', {
        title: 'A p99 that only got worse when we added capacity',
        date: '4 March 2026',
        author: 'Devika Rao',
        body: [
          { kind: 'paragraph', text: 'We doubled the fleet and the p99 went up by 40ms. That sentence sat in our incident channel for two days before anyone could explain it, and the explanation turned out to be a good one, so here it is written down.' },
          { kind: 'heading', text: 'The setup' },
          { kind: 'paragraph', text: 'A read path: stateless API pods, a connection pool per pod, and a Postgres primary with two replicas. Reads go to replicas through a pooler. Median 4ms, p99 around 60ms at 12k reads/sec, which we were happy with.' },
          { kind: 'paragraph', text: 'Traffic forecasts said 20k/sec by April, so we went from 40 pods to 80. Median stayed flat. p99 went from 60ms to 101ms within an hour of the rollout, and stayed there.' },
          { kind: 'heading', text: 'What we checked first, and why it was all wrong' },
          { kind: 'bullet', text: 'Replica CPU: 31%, flat before and after. Not saturation.' },
          { kind: 'bullet', text: 'Query plans: identical, verified with auto_explain on the slow samples.' },
          { kind: 'bullet', text: 'Network: no retransmits, no change in RTT between availability zones.' },
          { kind: 'bullet', text: 'GC pauses in the API tier: unchanged, and too small to account for 40ms anyway.' },
          { kind: 'paragraph', text: 'Every dashboard we owned said nothing had changed. The thing that had changed was not on a dashboard: the number of connections.' },
          { kind: 'heading', text: 'The actual cause' },
          { kind: 'paragraph', text: 'Each pod opened a pool of 20 connections at startup and kept them warm. At 40 pods that is 800 connections into the pooler; at 80 pods it is 1,600, against a pooler configured for 900 server-side slots. Past that ceiling the pooler queues, and its queue is FIFO with no fairness across clients.' },
          { kind: 'paragraph', text: 'So the median request still found a free slot immediately — plenty were free most of the time. But the unlucky tail now waited behind a queue that had not existed at all a week earlier. More capacity in the stateless tier had made the stateful tier’s contention worse. Obvious in hindsight, invisible in the metrics we had.' },
          { kind: 'quote', text: 'Adding stateless capacity is only free until it multiplies your connection count against something that is not stateless.' },
          { kind: 'heading', text: 'The fix, in order of how much it helped' },
          { kind: 'bullet', text: 'Dropped the per-pod pool from 20 to 6, sized from measured concurrency rather than a number someone typed in 2021. p99 back to 58ms immediately.' },
          { kind: 'bullet', text: 'Added pool-wait time as a first-class client-side metric — this is the graph that would have found it in ten minutes.' },
          { kind: 'bullet', text: 'Set the pooler’s queue timeout to 250ms so we fail fast and shed load instead of holding requests the caller has already given up on.' },
          { kind: 'bullet', text: 'Wrote a capacity check into the deploy pipeline: pods × pool size must stay under 70% of pooler slots, or the deploy warns.' },
          { kind: 'paragraph', text: 'Three months on, p99 at 19k reads/sec is 54ms on 80 pods. The number that mattered was never CPU. It was a multiplication we were not doing.' },
        ],
      }),
      b('find', 'search', { layout: 'bar', placeholder: 'Search posts — postgres, raft, incident, io_uring…', label: 'Search', buttonLabel: 'Go', name: 'q', align: 'start' }),
      b('posts', 'blog-list', {
        title: 'Everything else',
        columns: 2,
        posts: [
          { title: 'Reading the Postgres WAL for fun and change data capture', excerpt: 'What logical decoding actually emits, where the replication slot bites you, and why our first CDC pipeline pinned a disk for six days.', href: '#post', date: 'January 2026', tag: 'Postgres' },
          { title: 'Raft is simple until you have to snapshot', excerpt: 'Log compaction is where the paper stops holding your hand. Notes from implementing it twice and getting it wrong once.', href: '#post', date: 'November 2025', tag: 'Consensus' },
          { title: 'Benchmarks that survive contact with production', excerpt: 'Why our synthetic numbers were 6× optimistic, and the four changes to the harness that closed the gap to 15%.', href: '#post', date: 'September 2025', tag: 'Performance' },
          { title: 'io_uring in a boring service', excerpt: 'We rewrote one hot path and measured everything. The win was real, smaller than the blog posts promised, and cost us a week of debugging.', href: '#post', date: 'July 2025', tag: 'Linux' },
          { title: 'Idempotency keys are a product decision', excerpt: 'Where to put the key, how long to keep it, and what to do when the client retries with the same key and a different body.', href: '#post', date: 'May 2025', tag: 'APIs' },
          { title: 'The on-call handbook I wish I had in year one', excerpt: 'Fifteen habits, no heroics. Mostly about writing things down while the adrenaline is still making you fast.', href: '#post', date: 'March 2025', tag: 'On-call' },
        ],
      }),
      b('subscribe', 'newsletter', { title: 'New posts by email', intro: 'One email per post, roughly monthly. No digests, no course upsell, no “hey quick question” follow-ups.', placeholder: 'you@example.com', submitLabel: 'Subscribe', successMessage: 'Subscribed — you’ll get the next post the day it goes up.' }),
      b('links', 'social-links', { layout: 'row', variant: 'labeled', align: 'start', links: [
        { platform: 'github', href: '#', label: 'GitHub' },
        { platform: 'mastodon', href: '#', label: 'Mastodon' },
        { platform: 'rss', href: '#', label: 'RSS' },
        { platform: 'email', href: '#', label: 'Email' },
      ] }),
      b('rights', 'copyright', { holder: 'Devika Rao', text: 'Posts are CC BY 4.0. Opinions are mine and are frequently revised.', showSymbol: true, align: 'start' }),
    ],
  }),

  // ── 5. Personal finance blog ───────────────────────────────────────────────
  tpl({
    id: 'blog-finance',
    vertical: 'blog',
    label: 'Personal finance — Classic',
    description: 'A no-hype money letter with public numbers, an explainer archive and the disclosures a finance site actually needs.',
    tags: ['finance', 'newsletter', 'faq', 'b2c', 'budget'],
    layout: 'classic',
    preset: 'forest',
    meta: { title: 'Slow Money Weekly — plain-English personal finance', description: 'One letter a week about index funds, tax-advantaged accounts and not panicking. No stock picks, no affiliate links.', lang: 'en', favicon: '🌱' },
    blocks: [
      b('nav', 'nav', { brand: 'Slow Money Weekly', sticky: true, links: [{ label: 'Start here', href: '#start' }, { label: 'Archive', href: '#archive' }, { label: 'The numbers', href: '#numbers' }, { label: 'FAQ', href: '#faq' }], cta: { label: 'Read free', href: '#subscribe' } }),
      b('hero', 'hero', { eyebrow: 'Week 187 · Austin, Texas', headline: 'Boring money advice, written out in full', subhead: 'One letter a week on index funds, 401(k)s, HSAs and the small decisions that compound. No stock picks. No affiliate links. No course.', align: 'left', minHeight: 'md', image: img('slow-money-porch-morning'), overlay: 'scrim', cta: { label: 'Start with the basics', href: '#start' } }),
      b('numbers', 'stats', {
        title: 'Published in the open since 2021',
        columns: 4,
        items: [
          { value: '187', label: 'Weekly letters, none skipped' },
          { value: '41', label: 'Readers', suffix: 'k' },
          { value: '0', label: 'Affiliate links, ever' },
          { value: '4', label: 'Public portfolio updates a year' },
        ],
      }),
      b('start', 'steps', {
        title: 'If you are starting from zero, do these five things in this order',
        subtitle: 'It takes about a weekend. Nothing here needs an advisor, and none of it is clever.',
        items: [
          { title: 'Write down what you actually owe', text: 'Every balance, every rate, on one page. Not an app — a page. Most people are wrong about at least one number and it is usually the rate.' },
          { title: 'Bank one month of expenses', text: 'A plain savings account, separate bank, no card attached. This is the buffer that stops a flat tire becoming credit card debt at 24% APR.' },
          { title: 'Take the whole employer match', text: 'If your 401(k) matches 4% and you contribute 2%, you are declining a raise. This is the highest guaranteed return you will ever be offered.' },
          { title: 'Kill anything above 8% interest', text: 'Avalanche order, highest rate first. Below 8%, the math stops being obvious and investing instead becomes a reasonable choice.' },
          { title: 'Automate one broad index fund', text: 'A total-market or target-date fund inside a Roth IRA, funded on payday before you can think about it. Then stop looking at it for a year.' },
        ],
      }),
      b('archive', 'blog-list', {
        title: 'Recent letters',
        columns: 2,
        posts: [
          { title: 'The HSA is the best account nobody explains to you', excerpt: 'Triple tax advantage, portable, and it becomes a second IRA at 65. The catch is the receipts, and the catch is manageable.', href: '#archive', date: 'February 14, 2026', tag: 'Accounts' },
          { title: 'What our household spent in 2025, line by line', excerpt: 'All $71,340 of it, including the $2,100 of restaurant meals I said I would cut last January and did not.', href: '#archive', date: 'February 7, 2026', tag: 'Public numbers' },
          { title: 'Target-date funds are fine, actually', excerpt: 'The 0.08% expense ratio argument against them costs a typical saver less than one bad panic-sell. Simplicity is a real return.', href: '#archive', date: 'January 31, 2026', tag: 'Investing' },
          { title: 'Reading a 401(k) fee disclosure without crying', excerpt: 'Where the numbers hide, which three lines matter, and the email template that got a reader’s plan fees cut by half.', href: '#archive', date: 'January 24, 2026', tag: 'Accounts' },
          { title: 'Emergency funds when your income is lumpy', excerpt: 'Six months of expenses is the wrong frame for freelancers. Here is the version that works when March pays for June.', href: '#archive', date: 'January 17, 2026', tag: 'Self-employed' },
          { title: 'I got the 2022 bond market completely wrong', excerpt: 'What I wrote at the time, what actually happened, and the two things it changed about how I write about duration.', href: '#archive', date: 'January 10, 2026', tag: 'Corrections' },
        ],
      }),
      b('about', 'about', {
        eyebrow: 'Who writes this',
        title: 'Marcus Adeyemi, and no one else',
        body: 'I am not a financial advisor and I do not want to be one. I spent eleven years as a compliance analyst at a mid-size bank, which is where I learned how much of retail finance is designed to be slightly too boring to read. Slow Money Weekly is my attempt at the opposite: the same information in plain English, with my own numbers attached so you can see what I actually do rather than what I recommend. The letter is free and always will be. It is funded by a reader membership of $6 a month that about 3% of readers pay and 97% happily ignore.',
        image: img('slow-money-marcus-desk'),
        imageAlt: 'A desk with a laptop, printed spreadsheets and a cup of coffee',
        imageSide: 'left',
      }),
      b('faq', 'faq', {
        title: 'Reasonable questions',
        items: [
          { question: 'Will you tell me which stocks to buy?', answer: 'No. I have never picked an individual stock in this letter and I do not intend to. If that is what you are after, there are four hundred newsletters that will happily oblige and I would read none of them.' },
          { question: 'Is this US-specific?', answer: 'Mostly, yes — 401(k), Roth IRA and HSA are US accounts. The behavioral parts travel fine, and about a fifth of readers are outside the US, but I will not pretend to know your country’s tax code.' },
          { question: 'How do you make money?', answer: 'A $6/month voluntary membership, and nothing else. No affiliate links, no sponsored issues, no referral bonuses for brokerages. If I ever take sponsorship it will be disclosed at the top of the letter in bold before you read a word.' },
          { question: 'Can I ask you about my specific situation?', answer: 'I read every reply and answer what I can generally, in the letter, anonymized. I cannot give you personal advice — that is both a legal line and a genuinely good idea, because I do not know your full picture.' },
        ],
      }),
      b('subscribe', 'newsletter', { title: 'One letter, every Saturday morning', intro: 'Free. About 1,500 words. Unsubscribe in one click and I will never email you again — no win-back sequence.', placeholder: 'you@example.com', submitLabel: 'Send me Saturdays', successMessage: 'You’re in. The next letter goes out Saturday at 8am Central.' }),
      b('disclosures', 'legal', {
        title: 'The small print, which is short on purpose',
        align: 'center',
        separator: '·',
        documents: [
          { label: 'Not financial advice', title: 'Editorial disclaimer', content: '**Slow Money Weekly is written for general education and is not personalized financial advice.**\n\nMarcus Adeyemi is not a registered investment adviser, broker-dealer, tax preparer or attorney. Nothing published here accounts for your income, debts, tax residence, dependents, risk tolerance or timeline.\n\nInvestments can lose value, including the entire amount invested. Past performance says nothing reliable about future returns. Before acting on anything you read here, consider speaking to a fee-only fiduciary adviser or a licensed tax professional in your jurisdiction.' },
          { label: 'Funding & conflicts', title: 'How this letter is funded', content: '**Reader-funded, single source.**\n\n- Voluntary memberships at $6/month are the only revenue.\n- No affiliate links, referral bonuses, sponsored issues or paid placements have ever run in this letter.\n- Personal holdings are published in full each quarter and are limited to broad-market index funds, a target-date fund and cash.\n- If any of the above changes, it will be disclosed at the top of the next issue before any other content.' },
          { label: 'Privacy', title: 'What happens to your email address', content: '**Your address is used to send you this letter. That is the whole list.**\n\n- Stored with our email provider under a data processing agreement; never sold, rented or shared.\n- Open and click tracking is off. Subscriber counts come from list size, not from pixels.\n- One-click unsubscribe removes you within the hour and deletes your record within 30 days.\n- Requests to see or delete your data: reply to any issue and it will be handled within seven days.' },
        ],
      }),
      b('social', 'social-links', { layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'rss', href: '#', label: 'RSS' },
        { platform: 'linkedin', href: '#', label: 'LinkedIn' },
        { platform: 'email', href: '#', label: 'Reply to any issue' },
      ] }),
      b('footer', 'footer', { brand: 'Slow Money Weekly', tagline: 'Reader-funded since 2021. Austin, Texas.', links: [{ label: 'Start here', href: '#start' }, { label: 'Archive', href: '#archive' }, { label: 'FAQ', href: '#faq' }], copyright: '© Marcus Adeyemi · Educational content only' }),
    ],
  }),

  // ── 6. Parenting blog ──────────────────────────────────────────────────────
  tpl({
    id: 'blog-parenting',
    vertical: 'blog',
    label: 'Parenting blog — Mailbag',
    description: 'A warm parenting blog built around the reader mailbag, with the week’s questions answered as a readable thread.',
    tags: ['parenting', 'family', 'newsletter', 'social', 'light'],
    layout: 'conversational',
    preset: 'candy',
    meta: { title: 'Three Under Five — a parenting mailbag', description: 'Honest, non-judgemental parenting notes from Melbourne. Reader questions answered every Wednesday, no perfect households involved.', lang: 'en', favicon: '🧸' },
    blocks: [
      b('nav', 'nav', { brand: 'Three Under Five', sticky: true, links: [{ label: 'Mailbag', href: '#mailbag' }, { label: 'This week', href: '#latest' }, { label: 'Archive', href: '#archive' }, { label: 'About', href: '#about' }], cta: { label: 'Ask a question', href: '#subscribe' } }),
      b('hero', 'hero', { eyebrow: 'Wednesday mailbag · Issue 96', headline: 'You are not doing it wrong. It is just genuinely hard.', subhead: 'Reader questions about sleep, tantrums, screens and the guilt, answered honestly by someone whose house is also loud at 6am.', align: 'center', minHeight: 'md', overlay: 'none', cta: { label: 'Read this week’s mailbag', href: '#mailbag' } }),
      b('latest', 'feed', {
        title: 'This week',
        layout: 'cards',
        items: [
          { title: 'The 4pm meltdown hour, explained', subtitle: 'Wednesday · 6 min read', text: 'Why the worst hour of the day is almost always the same hour, and four things that genuinely take the edge off it.', href: '#mailbag', image: img('three-under-five-afternoon-kitchen'), badge: 'New' },
          { title: 'What I stopped buying after the third child', subtitle: 'Monday · 4 min read', text: 'A short, unsentimental list. The wipes warmer did not make it. Neither did most of the sleep gadgets.', href: '#archive', image: img('three-under-five-toy-basket'), badge: 'Popular' },
          { title: 'Daycare drop-off without the guilt spiral', subtitle: 'Last week · 7 min read', text: 'The two-minute goodbye routine an early-childhood teacher taught me, and why looking back is fine actually.', href: '#archive', image: img('three-under-five-daycare-door'), badge: 'Reader favourite' },
        ],
      }),
      b('mailbag', 'chat-thread', {
        title: 'The Wednesday mailbag',
        subtitle: 'Three questions from readers, answered as I would answer a friend. Names changed, permission given.',
        participants: [
          { id: 'reader', name: 'Reader', role: 'user' },
          { id: 'priya', name: 'Priya', role: 'agent', avatar: img('three-under-five-priya') },
        ],
        messages: [
          { from: 'reader', time: '09:02', body: [{ kind: 'text', text: 'My 3-year-old has started refusing to nap but is a disaster by 5pm. Do I fight for the nap or drop it?' }] },
          { from: 'priya', time: '09:14', body: [
            { kind: 'text', text: 'Neither, in my experience — you split the difference for about six weeks. Around three, most kids need rest but not sleep, and the fight is usually about the bed, not the tiredness.' },
            { kind: 'list', ordered: true, items: [
              { label: 'Rename it: "quiet time", same room, door open, no requirement to sleep.' },
              { label: 'Books and one quiet toy allowed. 45 minutes, timer they can see.' },
              { label: 'If they fall asleep, cap it at an hour so bedtime survives.' },
              { label: 'Move dinner 20 minutes earlier for those six weeks — the 5pm disaster is often hunger wearing a costume.' },
            ] },
            { kind: 'text', text: 'Ours dropped naps properly at 3 years 4 months and quiet time stayed until school. It is the single best thing we did for the afternoons.' },
          ] },
          { from: 'reader', time: '09:31', body: [{ kind: 'text', text: 'How much screen time is too much? I feel awful every time I hand over the tablet and I hand it over most days.' }] },
          { from: 'priya', time: '09:47', body: [
            { kind: 'text', text: 'Honestly? The number matters less than what it displaces. An hour while you cook dinner is not the same hour as one that replaces the only outdoor time in the day.' },
            { kind: 'text', text: 'What helped me more than any limit was making it predictable — same slot, announced in advance, ends with a timer rather than with me. The screaming was never about the screen, it was about the surprise.' },
            { kind: 'text', text: 'If you are the only person in your house feeling guilty about it, the problem is probably the guilt and not the tablet.' },
          ] },
          { from: 'reader', time: '10:05', body: [{ kind: 'text', text: 'Second baby due in March and I already feel like I am betraying the first one. Does that go away?' }] },
          { from: 'priya', time: '10:20', body: [
            { kind: 'text', text: 'It goes quiet, then it comes back on the first properly hard day, then it fades for good somewhere around the point where they start playing together without you.' },
            { kind: 'text', text: 'The thing nobody told me: you do not divide your attention, but you do divide your time, and those are not the same loss. Ten focused minutes at bedtime with the older one bought me more peace than any amount of guilt-driven daytime hovering.' },
            { kind: 'buttons', items: [{ label: 'Read: the first six weeks with two', href: '#archive' }, { label: 'Ask your own question', href: '#subscribe' }] },
          ] },
        ],
      }),
      b('subscribe', 'newsletter', { title: 'Get the mailbag on Wednesdays', intro: 'One email a week with the questions and answers, plus the reply link if you want to ask something. Free, and never sold to anyone.', placeholder: 'you@example.com', submitLabel: 'Join 12,000 parents', successMessage: 'Welcome — Wednesday’s mailbag is on its way, and you can reply to it with anything.' }),
      b('archive', 'blog-list', {
        title: 'From the archive',
        columns: 3,
        posts: [
          { title: 'Sleep regressions that were not regressions', excerpt: 'Three times I lost a fortnight to a "regression" that turned out to be a tooth, a growth spurt, and once, memorably, a new streetlight.', href: '#archive', image: img('three-under-five-cot-night'), date: '18 February', tag: 'Sleep' },
          { title: 'The lunchbox that finally came home empty', excerpt: 'Four terms of trial and error at a Melbourne kinder, and the five things that survive a hot bag until midday.', href: '#archive', image: img('three-under-five-lunchbox'), date: '4 February', tag: 'Food' },
          { title: 'Saying no without a forty-minute negotiation', excerpt: 'Short scripts that work on a determined toddler, none of which involve counting to three or raising your voice.', href: '#archive', image: img('three-under-five-park-swing'), date: '21 January', tag: 'Behaviour' },
          { title: 'What a $0 weekend looks like with three kids', excerpt: 'Library, creek, cardboard, and the local pool on a free-entry Sunday. Nobody noticed it was a budget decision.', href: '#archive', image: img('three-under-five-creek-walk'), date: '14 January', tag: 'Budget' },
          { title: 'Splitting the mental load, on paper', excerpt: 'The shared list that finally stopped the "just tell me what to do" conversation in our house. Includes the template.', href: '#archive', image: img('three-under-five-fridge-list'), date: '7 January', tag: 'Partnership' },
          { title: 'Flying to Perth with three under five', excerpt: 'Four hours, one aisle seat, zero screens confiscated. Mostly luck, partly the snack strategy in the middle section.', href: '#archive', image: img('three-under-five-airport'), date: '20 December', tag: 'Travel' },
        ],
      }),
      b('about', 'about', {
        eyebrow: 'Who is answering',
        title: 'Priya Raman, three kids, one very loud kitchen',
        body: 'I am not a paediatrician, a sleep consultant or a parenting expert. I am a former primary school teacher in Melbourne with three children aged five, three and one, writing down what worked, what did not, and what I would tell a friend at the school gate. Everything here is opinion and experience, not medical advice — for anything about feeding, development or health, please talk to your GP or maternal and child health nurse. What I can offer is the honest version: the mornings that went badly, the things I bought and regretted, and the reassurance that most of this is normal and most of it passes.',
        image: img('three-under-five-family-kitchen'),
        imageAlt: 'A busy family kitchen with breakfast things on the table',
        imageSide: 'right',
      }),
      b('social', 'social-links', { title: 'Come say hello', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'instagram', href: '#', label: 'Instagram' },
        { platform: 'facebook', href: '#', label: 'Facebook group' },
        { platform: 'email', href: '#', label: 'Email Priya' },
      ] }),
      b('footer', 'footer', { brand: 'Three Under Five', tagline: 'Written in Melbourne, usually after bedtime.', links: [{ label: 'Mailbag', href: '#mailbag' }, { label: 'Archive', href: '#archive' }, { label: 'About', href: '#about' }], copyright: '© Priya Raman · Opinion, not medical advice' }),
    ],
  }),

  // ── 7. Product review blog ─────────────────────────────────────────────────
  tpl({
    id: 'blog-reviews',
    vertical: 'blog',
    label: 'Product reviews — Bold',
    description: 'An independent review desk that leads with the current picks, then shows exactly how everything was tested.',
    tags: ['reviews', 'gear', 'testing', 'newsletter', 'b2c'],
    layout: 'bold',
    preset: 'mono',
    meta: { title: 'Bench Tested — independent gear reviews', description: 'We buy everything we test, at retail, and publish the measurements. Kitchen, tools and home gear, reviewed properly.', lang: 'en', favicon: '🔧' },
    blocks: [
      b('nav', 'nav', { brand: 'BENCH TESTED', sticky: true, links: [{ label: 'Top picks', href: '#picks' }, { label: 'Reviews', href: '#reviews' }, { label: 'How we test', href: '#method' }], cta: { label: 'Search', href: '#find' } }),
      b('hero', 'hero', { eyebrow: 'Independent · Reader-funded · No review units', headline: 'We buy it. We break it. We tell you.', subhead: 'Every product on this site was bought at retail with our own money, tested to a written protocol, and kept for at least ninety days before we published a word.', align: 'center', minHeight: 'full', image: img('bench-tested-workshop-hero'), overlay: 'dark', cta: { label: 'This month’s picks', href: '#picks' } }),
      b('picks', 'product', {
        title: 'Current picks — updated 2 March',
        subtitle: 'The thing we would buy today, at today’s price, with our own money. Prices are UK RRP and change constantly.',
        columns: 3,
        items: [
          { name: 'Ridgeline C3 cordless drill', description: 'Best overall. 118 driven screws per charge, and the only drill under £150 whose chuck stayed true after the drop test.', price: '£139', was: '£159', image: img('bench-tested-drill'), badge: 'Best overall', ctaLabel: 'Read the review', ctaHref: '#reviews' },
          { name: 'Hearthstone 24cm carbon steel pan', description: 'Beat two pans costing three times as much on heat retention. Seasoned in 40 minutes, still non-stick after 90 days of eggs.', price: '£48', image: img('bench-tested-pan'), badge: 'Best value', ctaLabel: 'Read the review', ctaHref: '#reviews' },
          { name: 'Nordfell 60L rolling duffel', description: 'Survived 14 airport handling cycles with no seam failure. Wheels are the weak point — expect to replace them around year four.', price: '£185', image: img('bench-tested-duffel'), badge: 'Travel pick', ctaLabel: 'Read the review', ctaHref: '#reviews' },
          { name: 'Marlow XT robot vacuum', description: 'Cleared 94% of test debris on carpet, the highest we have measured. Loud, and the app is genuinely unpleasant to use.', price: '£429', was: '£499', image: img('bench-tested-vacuum'), badge: 'Best on carpet', ctaLabel: 'Read the review', ctaHref: '#reviews' },
          { name: 'Kessel 8-cup pour-over kettle', description: 'Temperature held within 1.2°C over a four-minute pour. The cheapest gooseneck we would actually recommend.', price: '£72', image: img('bench-tested-kettle'), badge: 'Coffee pick', ctaLabel: 'Read the review', ctaHref: '#reviews' },
          { name: 'Bramble 3-in-1 baby monitor', description: 'Do not buy. Failed our network isolation test and streamed to a third-party host we could not identify. Full write-up inside.', price: '£129', image: img('bench-tested-monitor'), badge: 'Avoid', ctaLabel: 'Why we say no', ctaHref: '#reviews' },
        ],
      }),
      b('find', 'search', { layout: 'bar', placeholder: 'Search 412 tested products…', label: 'Find a review', buttonLabel: 'Search', name: 'q', align: 'center' }),
      b('reviews', 'blog-list', {
        title: 'Latest write-ups',
        columns: 2,
        posts: [
          { title: 'Six cordless drills, 4,000 screws, one clear winner', excerpt: 'We drove screws until every battery died, then dropped each drill onto concrete from bench height. Two chucks never recovered.', href: '#reviews', image: img('bench-tested-drill-lineup'), date: '2 March 2026', tag: 'Tools' },
          { title: 'The carbon steel pan test that embarrassed our cast iron', excerpt: 'Nine pans, one thermal camera, 300 eggs. The £48 pan out-performed the £150 one on every measure except weight.', href: '#reviews', image: img('bench-tested-pan-lineup'), date: '24 February 2026', tag: 'Kitchen' },
          { title: 'We put four baby monitors on an isolated network', excerpt: 'Three behaved. One phoned home to an unidentified host every 40 seconds, including when the camera was covered.', href: '#reviews', image: img('bench-tested-monitor-lab'), date: '17 February 2026', tag: 'Home' },
          { title: 'Robot vacuums: the carpet numbers manufacturers will not print', excerpt: 'Standardised debris, weighed before and after, across three pile depths. The gap between best and worst was 38 percentage points.', href: '#reviews', image: img('bench-tested-vacuum-test'), date: '9 February 2026', tag: 'Home' },
        ],
      }),
      b('method', 'rich-text', {
        blocks: [
          { kind: 'heading', text: 'How we test, in full' },
          { kind: 'paragraph', text: 'Every claim on this site should be checkable by someone with the same equipment and a free weekend. That means we publish the protocol before the results, and we publish the results even when they contradict what we said last year.' },
          { kind: 'subheading', text: 'What we buy' },
          { kind: 'paragraph', text: 'Everything is bought anonymously at retail, from ordinary shops, using reader-membership money. We do not accept review units, loans, embargoed access or briefings. If a manufacturer contacts us about a product under test, that email is quoted in the review.' },
          { kind: 'subheading', text: 'How long we keep it' },
          { kind: 'paragraph', text: 'Minimum ninety days of ordinary use before publication, and we re-check every pick at six and eighteen months. About one in seven picks changes at the six-month re-check, usually because a manufacturer quietly revised a component.' },
          { kind: 'subheading', text: 'The measurements' },
          { kind: 'bullet', text: 'Every number is the median of at least five runs, with the raw runs published in the appendix of each review.' },
          { kind: 'bullet', text: 'Destructive tests happen last, on the same unit, after the ninety days — never on a second sample.' },
          { kind: 'bullet', text: 'Prices shown are the price we paid, in GBP, with the date. We do not update them silently.' },
          { kind: 'bullet', text: 'Corrections are appended to the top of the review with a date, never edited into the body.' },
          { kind: 'quote', text: 'If we cannot measure it, we say it is an opinion and label it as one. Most gear writing goes wrong at exactly that line.' },
          { kind: 'subheading', text: 'How this is paid for' },
          { kind: 'paragraph', text: 'Reader memberships at £5 a month, and nothing else. No affiliate links, no advertising, no sponsored posts, no data sales. Tested products are donated to a local repair café or the Bristol tool library once the write-up is published.' },
        ],
      }),
      b('verdict', 'cta', { headline: 'Buy the right one once.', subhead: 'Six current picks, every one bought at retail, measured against a written protocol and lived with for ninety days before we said a word about it.', background: 'accent', button: { label: 'See the current picks', href: '#picks' } }),
      b('subscribe', 'newsletter', { title: 'New reviews, no spam', intro: 'One email when a review publishes and one summary at the end of each month. About 26,000 readers, all of whom can unsubscribe in one click.', placeholder: 'you@example.com', submitLabel: 'Get the reviews', successMessage: 'Subscribed — the next review lands in your inbox the moment it publishes.' }),
      b('social', 'social-links', { layout: 'row', variant: 'icon', align: 'center', links: [
        { platform: 'youtube', href: '#', label: 'YouTube' },
        { platform: 'x', href: '#', label: 'X' },
        { platform: 'rss', href: '#', label: 'RSS' },
        { platform: 'email', href: '#', label: 'Email the desk' },
      ] }),
      b('footer', 'footer', { brand: 'Bench Tested', tagline: 'Bought at retail. Tested to a protocol. Bristol, UK.', links: [{ label: 'Top picks', href: '#picks' }, { label: 'How we test', href: '#method' }, { label: 'Reviews', href: '#reviews' }], copyright: '© Bench Tested Ltd · No affiliate links, ever' }),
    ],
  }),
];
