/**
 * `care` starter templates — childcare, pet care and care-at-home: eight pages whose
 * real job is proving that a stranger can be trusted with a child, a dog, or a parent.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const careTemplates: Template[] = [
  tpl({
    id: 'care-babysitter',
    vertical: 'care',
    label: 'Childminder — Classic',
    description: 'A registered home childminder leading with checks, daily rhythm and term-time rates.',
    tags: ['childcare', 'family', 'booking', 'local', 'reviews'],
    layout: 'classic',
    preset: 'candy',
    meta: { title: 'Rowan Tree Childminding — Chapel Allerton, Leeds', description: 'Ofsted-registered home childminding for under-fives in Chapel Allerton, Leeds. Two spaces from September.', lang: 'en', favicon: '🧸' },
    blocks: [
      b('nav', 'nav', { brand: 'Rowan Tree', sticky: true, links: [{ label: 'About', href: '#about' }, { label: 'Checks', href: '#checks' }, { label: 'Rates', href: '#rates' }, { label: 'A day here', href: '#day' }, { label: 'Questions', href: '#faq' }], cta: { label: 'Arrange a visit', href: '#visit' } }),
      b('hero', 'hero', { eyebrow: 'Ofsted URN 2611940 · Good', headline: 'A small setting, three children at a time', subhead: 'Home childminding for under-fives in Chapel Allerton — muddy mornings, real lunches, and a proper handover at the door.', align: 'left', minHeight: 'lg', image: img('care-childminder-playroom-morning'), overlay: 'scrim', cta: { label: 'Arrange a visit', href: '#visit' } }),
      b('about', 'about', { eyebrow: 'Since 2017', title: 'Hello — I’m Marta', body: 'I’ve been childminding from our terraced house on Sholebroke Avenue for nine years, after seven years as a nursery room leader in Harehills. The setting is the ground floor: playroom at the front, kitchen where the children help with lunch, and a long back garden with a mud kitchen and a very patient apple tree. I take three under-fives at a time and one after-schooler, which is the whole point — the children know each other, and I know exactly where everyone is.', image: img('care-childminder-garden-mudkitchen'), imageAlt: 'Garden mud kitchen with pans and a water tray', imageSide: 'right' }),
      b('checks', 'features', { title: 'The paperwork, up front', subtitle: 'All of this is in a folder by the front door — ask to see the originals at your visit.', columns: 3, items: [
        { icon: '🛡️', title: 'Enhanced DBS', text: 'Enhanced DBS on the Update Service for me and for everyone over 16 living here. Checked annually.' },
        { icon: '🩹', title: 'Paediatric first aid', text: '12-hour Ofsted-approved paediatric first aid, renewed March 2026. Certificate on the wall.' },
        { icon: '📋', title: 'Ofsted registered', text: 'URN 2611940, rated Good at the last inspection in November 2024. Full report on request.' },
        { icon: '☂️', title: 'Public liability', text: 'Insured to £5m through Morton Michel, including car seats for outings.' },
        { icon: '📞', title: 'Three references', text: 'Two current parents and one former nursery manager, all happy to take a call.' },
        { icon: '🍲', title: 'Food hygiene L2', text: 'Level 2 food hygiene, and a kitchen rated 5 by Leeds City Council.' },
      ] }),
      b('day', 'steps', { title: 'What a Tuesday looks like', subtitle: 'Loose, not rigid — but the shape is the same every day, which small children like.', items: [
        { title: '7:45 — Arrivals', text: 'Coats on hooks, a quick word at the door about sleep, food and mood. Breakfast if you need it.' },
        { title: '9:00 — Out', text: 'Potternewton Park, the library rhyme time on Wednesdays, or the allotment if it isn’t hammering down.' },
        { title: '11:30 — Lunch', text: 'Cooked here, eaten together at the low table. The children lay it and clear it.' },
        { title: '12:30 — Rest', text: 'Naps in the back room for those who still nap, books and quiet play for those who don’t.' },
        { title: '15:15 — School run', text: 'Walk to Chapel Allerton Primary, then home for snack and the garden until pick-up.' },
        { title: '17:30 — Handover', text: 'A two-minute rundown at the door plus photos and a food, nappy and sleep log in the app.' },
      ] }),
      b('rates', 'services-catalogue', { title: 'Rates from September 2026', subtitle: 'Invoiced monthly in advance. I accept Tax-Free Childcare and the 15- and 30-hour funded entitlements for 3- and 4-year-olds.', items: [
        { name: 'Full day, 7:45–17:45', description: 'Includes breakfast, cooked lunch, tea and all trips. Nappies and wipes provided.', price: '£62' },
        { name: 'Half day', description: 'Morning 7:45–13:00 or afternoon 13:00–17:45, meals included.', price: '£36' },
        { name: 'After-school, 15:00–17:45', description: 'Monday to Thursday. Collection from Chapel Allerton Primary, snack, garden, homework if they’ll sit still.', price: '£22' },
        { name: 'Ad-hoc hour', description: 'Subject to space on the day — usually possible on Wednesdays and Fridays.', price: '£8.50/hr' },
        { name: 'Settling-in sessions', description: 'Two one-hour visits with you, then one without. Nobody starts cold.', price: 'Free' },
      ] }),
      b('hours', 'hours', { title: 'Opening hours', timezone: 'Europe/London', note: 'Closed for four weeks a year plus bank holidays — dates confirmed each January.', days: [
        { day: 'mon', open: '07:45', close: '17:45' },
        { day: 'tue', open: '07:45', close: '17:45' },
        { day: 'wed', open: '07:45', close: '17:45' },
        { day: 'thu', open: '07:45', close: '17:45' },
        { day: 'fri', open: '07:45', close: '15:30' },
        { day: 'sat', closed: true },
        { day: 'sun', closed: true },
      ] }),
      b('reviews', 'reviews', { title: 'What parents say', subtitle: 'Left on childcare.co.uk and Google over the last three years.', average: '5.0', count: '38', source: 'Google', items: [
        { rating: 5, quote: 'Our daughter went from clinging to my leg to running through the door in about three weeks. The settling sessions did that.', author: 'Hannah B.', date: 'April 2026', source: 'google' },
        { rating: 5, quote: 'She rang me the day our son had a temperature, not a text — and had already logged what he’d eaten and when. That is the standard.', author: 'Idris K.', date: 'January 2026', source: 'google' },
        { rating: 5, quote: 'Three years with Marta and he can name every bird in Potternewton Park. Small setting, huge world.', author: 'Ruth and Sam', date: 'September 2025', source: 'facebook' },
      ] }),
      b('faq', 'faq', { title: 'The things parents ask at the visit', items: [
        { question: 'Do you have spaces?', answer: 'Two full-day spaces from September 2026 (Monday to Thursday), and one after-school space now. I keep a short waiting list and I will always tell you honestly where you sit on it.' },
        { question: 'What about allergies?', answer: 'Yes — we are a nut-free house as standard. I hold care plans for allergies, asthma and eczema, and I will do the training if your child needs something I haven’t handled before.' },
        { question: 'Do you drive?', answer: 'I do, with business insurance and correctly fitted stage-appropriate seats. Most days we walk, but the farm trip and the dentist run happen by car with your written consent.' },
        { question: 'How do you handle illness?', answer: 'A temperature over 38°C, sickness or diarrhoea means 48 hours at home. It is not fun for anyone, but it is the only thing that stops a bug going round a setting this small.' },
        { question: 'Can I see the policies?', answer: 'All of them — safeguarding, behaviour, complaints, EYFS planning, accident records. They live in the blue folder in the hall and I would rather you read them than not.' },
      ] }),
      b('visit', 'contact-details', { title: 'Come and see it', address: '31 Sholebroke Avenue, Chapel Allerton, Leeds LS7 3HB', phone: '+44 113 496 0021', email: 'marta@rowantreechildminding.co.uk', hours: 'Visits Tue–Thu at 18:30, or Saturday mornings' }),
      b('book', 'cta', { headline: 'Bring your child, not just yourself', subhead: 'Visits are half an hour, in the playroom, while the children are still here. That tells you far more than an empty room would.', background: 'primary', button: { label: 'Arrange a visit', href: '#visit' } }),
      b('footer', 'footer', { brand: 'Rowan Tree Childminding', tagline: 'Ofsted URN 2611940 · Chapel Allerton, Leeds', links: [{ label: 'Checks', href: '#checks' }, { label: 'Rates', href: '#rates' }, { label: 'Questions', href: '#faq' }], copyright: '© Rowan Tree Childminding' }),
    ],
  }),

  tpl({
    id: 'care-live-in-nanny',
    vertical: 'care',
    label: 'Live-in Nanny — Profile',
    description: 'One nanny’s hiring page: certifications, family history, languages and a screening-friendly enquiry form.',
    tags: ['childcare', 'profile', 'family', 'portfolio', 'b2c'],
    layout: 'profile',
    preset: 'sand',
    meta: { title: 'Devon Achebe — Live-in Nanny, Greater Boston', description: 'Career live-in nanny, eleven years, infant and twin experience. Newborn Care Specialist, CPR and Red Cross certified.', lang: 'en', favicon: '🍼' },
    blocks: [
      b('nav', 'nav', { brand: 'Devon Achebe', sticky: true, links: [{ label: 'Background', href: '#history' }, { label: 'Credentials', href: '#credentials' }, { label: 'Skills', href: '#skills' }, { label: 'References', href: '#references' }], cta: { label: 'Start a conversation', href: '#enquire' } }),
      b('who', 'profile-header', {
        name: 'Devon Achebe',
        headline: 'Career live-in nanny · newborns, twins and multiples · Greater Boston',
        location: 'Brookline, MA — will relocate within New England',
        avatar: img('care-nanny-devon-portrait'),
        summary: 'Eleven years and three families, the shortest placement two years. I work live-in, Monday through Friday, and I am at my best in the first eighteen months — sleep shaping, feeding routines, and keeping a household calm while two exhausted adults find their feet. INA-credentialed, non-smoker, clean license, and comfortable in a house with dogs.',
        contacts: [
          { type: 'email', value: 'devon@achebenanny.com', label: 'Email' },
          { type: 'phone', value: '+1 617 555 0148', label: 'Text first, please' },
          { type: 'location', value: 'Brookline, Massachusetts' },
        ],
        showDownload: true,
        downloadLabel: 'Download my CV (PDF)',
        showShare: true,
        shareLabel: 'Share with your partner',
      }),
      b('intro', 'rich-text', { blocks: [
        { kind: 'heading', text: 'What I actually do all day' },
        { kind: 'paragraph', text: 'A live-in nanny is not a babysitter who sleeps over. I run the children’s half of a household: their laundry, their food, their appointments, their nap schedule, and the hundred small decisions that otherwise land on a parent at 6pm. Everything else in the house is somebody else’s job, and I am firm about that line because it is what makes a placement last.' },
        { kind: 'quote', text: 'The best compliment I have had: “We stopped having the same argument every evening.”' },
        { kind: 'subheading', text: 'What I ask for' },
        { kind: 'bullet', text: 'A private room and bathroom, and a door that closes on my time off.' },
        { kind: 'bullet', text: 'A written work agreement — hours, guaranteed pay, overtime, vacation, sick days, and how we end it if it isn’t working.' },
        { kind: 'bullet', text: 'Payroll on the books, with taxes withheld. I have never worked any other way.' },
        { kind: 'bullet', text: 'A two-week paid trial before either of us commits to a year.' },
      ] }),
      b('history', 'experience', { title: 'Placements', items: [
        { role: 'Live-in nanny — twins from 6 weeks', org: 'Private family, Wellesley, MA', period: '2021 – 2026', location: 'Wellesley, Massachusetts', summary: 'Two parents working hospital shifts, boy/girl twins, and a golden retriever who thinks he is a third child.', bullets: [
          'Ran the night shift for the first fourteen weeks, then handed both babies to a 7pm bedtime that held.',
          'Built the feeding and pumping schedule with a lactation consultant and kept the log both parents lived by.',
          'Took both twins through their first year of preschool drop-offs, swim lessons and a dairy allergy diagnosis.',
        ] },
        { role: 'Live-in nanny — infant, then two under three', org: 'Private family, Cambridge, MA', period: '2017 – 2021', location: 'Cambridge, Massachusetts', summary: 'Started at eleven weeks with a first baby; stayed through the arrival of a second.', bullets: [
          'Managed the transition from one child to two, including the sibling regression nobody warns you about.',
          'Travelled with the family to Lisbon and Montréal, solo-parenting on flights so both adults could work.',
        ] },
        { role: 'Nanny, live-out — after school, ages 4 and 7', org: 'Private family, Somerville, MA', period: '2015 – 2017', location: 'Somerville, Massachusetts', bullets: [
          'School pick-ups, homework, three activities a week and dinner on the table by 6:15.',
        ] },
        { role: 'Toddler room lead', org: 'Beacon Street Early Learning Center', period: '2014 – 2015', location: 'Boston, Massachusetts', summary: 'Twelve toddlers, two assistants, and where I learned to plan a day properly.' },
      ] }),
      b('credentials', 'experience', { title: 'Certifications and checks', items: [
        { role: 'Newborn Care Specialist', org: 'Newborn Care Solutions', period: 'Certified 2020', summary: 'Sleep shaping, reflux and colic, multiples, and supporting a feeding plan without overriding it.' },
        { role: 'Infant & child CPR and First Aid', org: 'American Red Cross', period: 'Renewed February 2026', summary: 'Renewed every two years without a lapse since 2014.' },
        { role: 'INA Credentialed Nanny Exam', org: 'International Nanny Association', period: 'Passed 2019' },
        { role: 'Background screening', org: 'Sterling Volunteers — national criminal, registry and SSN trace', period: 'Run annually, last March 2026', summary: 'Report shared directly with you by the screening company so it does not come from me.' },
        { role: 'Driving record', org: 'Massachusetts RMV', period: 'Clean, checked March 2026', summary: 'Licensed since 2011, no points, comfortable driving your car or mine.' },
      ] }),
      b('skills', 'skills', { title: 'What I bring', display: 'bars', groups: [
        { name: 'Ages', items: [
          { label: 'Newborn (0–3 months)', level: 5 },
          { label: 'Infant (3–12 months)', level: 5 },
          { label: 'Toddler', level: 5 },
          { label: 'School age', level: 4 },
        ] },
        { name: 'Specialisms', items: [
          { label: 'Twins & multiples', level: 5 },
          { label: 'Sleep shaping', level: 5 },
          { label: 'Food allergies', level: 4 },
          { label: 'Travel & jet lag', level: 4 },
        ] },
        { name: 'Languages', items: [
          { label: 'English (native)', level: 5 },
          { label: 'Igbo (native)', level: 5 },
          { label: 'French (conversational)', level: 3 },
        ] },
      ] }),
      b('references', 'testimonials', { title: 'From the families', items: [
        { quote: 'Devon arrived on day nine with twins and a household in freefall, and within a month there was a schedule taped to the fridge that actually worked. Five years later our kids still ask when Devon is coming back.', author: 'The Vasquez-Lindt family', role: 'Wellesley, MA · 2021–2026' },
        { quote: 'Honest about what was and wasn’t their job, which sounds like a small thing until you have employed someone who wasn’t.', author: 'Priya N.', role: 'Cambridge, MA · 2017–2021' },
        { quote: 'We wrote the work agreement together and never once had to look at it again.', author: 'Michael O.', role: 'Somerville, MA · 2015–2017' },
      ] }),
      b('terms', 'pricing', { title: 'Terms I work on', subtitle: 'Greater Boston, 2026. Gross, on payroll, with taxes withheld — never cash.', plans: [
        { name: 'Live-in, Mon–Fri', price: '$1,450', period: 'per week and up', features: ['50 guaranteed hours, paid whether used or not', 'Private room and private bathroom', 'Overtime at 1.5× beyond 50 hours', 'Use of a household car, or mileage on mine', 'Two weeks of my choosing, one of yours, ten holidays'], ctaLabel: 'Talk it through', ctaHref: '#enquire', featured: true },
        { name: 'Newborn night cover', price: '+$450', period: 'per week', features: ['First 12 weeks, three nights a week', 'Awake with the baby, feeds and settling', 'Reverts to the standard rate after week 12', 'Not combined with a full weekday schedule'], ctaLabel: 'Ask about nights', ctaHref: '#enquire' },
        { name: 'Travel with the family', price: '$280', period: 'per day, on top', features: ['Domestic or international, own room', 'Per-diem for days off away from home', 'Solo-parenting on flights if that helps', 'Passport current to 2032'], ctaLabel: 'Ask about travel', ctaHref: '#enquire' },
      ] }),
      b('enquire', 'contact-form', {
        title: 'If it sounds like a fit',
        intro: 'Tell me about your household. I answer every message within two days, even when the answer is no — and I will tell you straight away if I am already in another final round.',
        submitLabel: 'Send to Devon',
        successMessage: 'Thank you — I will reply within two days.',
        fields: [
          { name: 'family', label: 'Your name', type: 'text', placeholder: 'Who am I writing back to?', required: true },
          { name: 'email', label: 'Email', type: 'email', placeholder: 'you@example.com', required: true },
          { name: 'phone', label: 'Phone', type: 'tel', placeholder: '+1 617 555 0000' },
          { name: 'town', label: 'Where is the role based?', type: 'text', placeholder: 'Town or neighborhood', required: true },
          { name: 'children', label: 'Children and ages', type: 'text', placeholder: 'e.g. twins, 4 months', required: true },
          { name: 'arrangement', label: 'Arrangement', type: 'select', options: ['Live-in, Mon–Fri', 'Live-in, full week', 'Live-out with occasional overnights', 'Not sure yet'], required: true },
          { name: 'start', label: 'Ideal start', type: 'text', placeholder: 'e.g. late August 2026' },
          { name: 'notes', label: 'Anything else I should know?', type: 'textarea', placeholder: 'Pets, allergies, shift patterns, grandparents nearby…' },
          { name: 'payroll', label: 'We can offer on-the-books payroll', type: 'checkbox', required: true },
        ],
      }),
      b('footer', 'footer', { brand: 'Devon Achebe', tagline: 'Live-in nanny · Greater Boston · references available on request', links: [{ label: 'Credentials', href: '#credentials' }, { label: 'References', href: '#references' }, { label: 'Enquire', href: '#enquire' }], copyright: '© Devon Achebe' }),
    ],
  }),

  tpl({
    id: 'care-dog-walker',
    vertical: 'care',
    label: 'Dog Walker — App',
    description: 'A group-walk dog walking round run like a product: live walk feed, install prompt and per-week plans.',
    tags: ['pets', 'dog-walking', 'mobile-first', 'pricing', 'booking'],
    layout: 'app',
    preset: 'forest',
    meta: { title: 'Pack Lane — Dog Walking, Inner West Sydney', description: 'Small-group and solo dog walks across Marrickville, Dulwich Hill and Petersham. GPS tracked, photo report after every walk.', lang: 'en', favicon: '🐕' },
    blocks: [
      b('shell', 'app-shell', { brand: 'Pack Lane', tabs: [
        { label: 'Today', href: '#walks', icon: '🐾' },
        { label: 'Plans', href: '#plans', icon: '💳' },
        { label: 'Safety', href: '#safety', icon: '🛡️' },
        { label: 'Reviews', href: '#reviews', icon: '⭐' },
        { label: 'Book', href: '#book', icon: '📅' },
      ] }),
      b('hero', 'hero-app', {
        headline: 'Every walk, on your phone, before your dog is even dry',
        subhead: 'Four dogs to a walker, GPS-tracked routes, and a photo report with distance, duration and mood in the app by the time you finish your meeting.',
        installLabel: 'Add Pack Lane to your phone',
        installHref: '#book',
        screenshots: [
          { src: img('care-packlane-app-route'), alt: 'Map screen showing a tracked walk through Marrickville' },
          { src: img('care-packlane-app-report'), alt: 'Walk report card with distance, duration and three photos' },
          { src: img('care-packlane-app-schedule'), alt: 'Weekly schedule screen with recurring walk slots' },
        ],
      }),
      b('install', 'install-prompt', { title: 'Keep Pack Lane one tap away', body: 'Add it to your home screen and your dog’s walk report lands like a message, not an email.', actionLabel: 'Show me how', position: 'bottom-right', tone: 'promo', delayMs: 6000, dismissible: true, rememberDismiss: true, platforms: ['ios-safari', 'android', 'desktop-chrome'] }),
      b('walks', 'feed', { title: 'Today’s rounds', layout: 'cards', items: [
        { title: 'Marrickville morning pack', subtitle: '9:00 · Jack, Nala, Biscuit, Otto', text: 'Off-lead loop at Enmore Park, then the back lanes home. Two spaces on Thursdays.', badge: 'Space Thu', image: img('care-packlane-enmore-park'), href: '#book' },
        { title: 'Dulwich Hill sniffari', subtitle: '11:30 · slow, solo walks', text: 'Twenty-five minutes at the dog’s pace for seniors, recoverers and dogs who find other dogs a lot.', badge: 'Solo only', image: img('care-packlane-senior-sniff'), href: '#book' },
        { title: 'Petersham lunchtime', subtitle: '12:45 · Maple, Kimchi, Dune', text: 'Fenced run at Petersham Park, water break, towel-dry at the door. Full until August.', badge: 'Waitlist', image: img('care-packlane-petersham-run'), href: '#book' },
        { title: 'Puppy socials', subtitle: 'Sat 8:00 · under 9 months', text: 'Six puppies, two handlers, thirty minutes of very supervised chaos in a fenced yard.', badge: 'Saturdays', image: img('care-packlane-puppy-social'), href: '#book' },
      ] }),
      b('plans', 'pricing', { title: 'Plans', subtitle: 'Billed fortnightly. Pause any week with 48 hours’ notice — holidays shouldn’t cost you.', plans: [
        { name: 'Casual', price: 'A$38', period: 'per walk', features: ['45-minute group walk', 'GPS route and photo report', 'Towel-dry and fresh water', 'Book up to 24h ahead, if there’s room'], ctaLabel: 'Book a walk', ctaHref: '#book' },
        { name: 'Three a week', price: 'A$99', period: 'per week', features: ['Three 45-minute group walks', 'Same walker, same days', 'Priority on holiday cover', 'Free meet-and-greet and key handover', 'Pause up to four weeks a year'], ctaLabel: 'Start Mon–Wed–Fri', ctaHref: '#book', featured: true },
        { name: 'Solo & senior', price: 'A$46', period: 'per walk', features: ['One-to-one, 25–30 minutes', 'Pace set by the dog', 'Medication given if you leave a plan', 'Reactive and recovering dogs welcome'], ctaLabel: 'Ask about solo', ctaHref: '#book' },
        { name: 'Daycare day', price: 'A$85', period: 'per day', features: ['7:30–17:00 at the Marrickville yard', 'Two walks plus a rest block', 'Max six dogs, two handlers', 'Trial day required first'], ctaLabel: 'Book a trial day', ctaHref: '#book' },
      ] }),
      b('safety', 'features', { title: 'The boring, important part', subtitle: 'Ask any walker in Sydney for these. If they hesitate, keep looking.', columns: 2, items: [
        { icon: '📄', title: 'Insured to A$20m', text: 'Public liability and care-custody-and-control cover, protecting your dog, your keys and your front door.' },
        { icon: '🚑', title: 'Canine first aid', text: 'Every walker holds a current canine first aid certificate and carries a kit, a tick remover and a slip lead.' },
        { icon: '🔑', title: 'Key handling', text: 'Keys are coded, never labelled with your address, and stored in a bolted lockbox at the yard.' },
        { icon: '🚐', title: 'Crated transport', text: 'Individually crated in a ventilated, air-conditioned van. No dog rides loose, ever.' },
        { icon: '🌡️', title: 'Heat policy', text: 'Over 28°C we swap to early shade walks or yard enrichment, and tell you before we do it.' },
        { icon: '📍', title: 'Council registered', text: 'Registered commercial dog walker with Inner West Council, four dogs per handler as the by-law requires.' },
      ] }),
      b('reviews', 'reviews', { title: 'From the group chat', average: '4.9', count: '204', source: 'Google', items: [
        { rating: 5, quote: 'Otto is a nervous rescue and they spent three weeks just doing pavement sits with him before he joined a pack. Nobody asked them to do that.', author: 'Ellie T.', date: 'May 2026', source: 'google' },
        { rating: 5, quote: 'The photo report is genuinely the best part of my working day. Also they once texted me that Biscuit had a limp, before I noticed it that evening.', author: 'Raj S.', date: 'March 2026', source: 'google' },
        { rating: 5, quote: 'Pausing for the school holidays without being charged is the reason we stayed.', author: 'Fiona M.', date: 'February 2026', source: 'facebook' },
      ] }),
      b('book', 'booking', {
        title: 'Book a meet-and-greet',
        intro: 'Free, twenty minutes, at your place. We meet the dog, you meet the walker, and nobody signs anything on the day.',
        submitLabel: 'Request a time',
        successMessage: 'Got it — we’ll confirm by text within a few hours.',
        serviceLabel: 'What are you after?',
        services: [
          { name: 'Meet-and-greet', duration: '20 min', price: 'Free' },
          { name: 'Group walk', duration: '45 min', price: 'A$38' },
          { name: 'Solo or senior walk', duration: '25–30 min', price: 'A$46' },
          { name: 'Daycare trial day', duration: '7:30–17:00', price: 'A$85' },
          { name: 'Puppy social', duration: '30 min', price: 'A$25' },
        ],
        askDate: true,
        askTime: true,
        askParty: false,
        askPhone: true,
        askNotes: true,
        notesLabel: 'Breed, age, and anything your dog finds hard',
      }),
      b('footer', 'footer', { brand: 'Pack Lane', tagline: 'Marrickville · Dulwich Hill · Petersham · Stanmore', links: [{ label: 'Plans', href: '#plans' }, { label: 'Safety', href: '#safety' }, { label: 'Book', href: '#book' }], copyright: '© Pack Lane Dog Walking' }),
    ],
  }),

  tpl({
    id: 'care-pet-boarding',
    vertical: 'care',
    label: 'Pet Sitting & Boarding — Showcase',
    description: 'A home boarding and pet-sitting service that sells the rooms, the garden and the daily video updates.',
    tags: ['pets', 'boarding', 'gallery', 'video', 'showcase'],
    layout: 'showcase',
    preset: 'ocean',
    meta: { title: 'Fellnest — Home Boarding & Pet Sitting, Berlin', description: 'Cage-free home boarding for dogs and in-home cat sitting across Neukölln and Kreuzberg. Six guests, one house, daily video.', lang: 'en', favicon: '🐾' },
    blocks: [
      b('nav', 'nav', { brand: 'Fellnest', sticky: true, links: [{ label: 'The house', href: '#tour' }, { label: 'Rooms', href: '#rooms' }, { label: 'A day', href: '#films' }, { label: 'Rates', href: '#rates' }, { label: 'Sitters', href: '#sitters' }], cta: { label: 'Reserve dates', href: '#book' } }),
      b('hero', 'hero', { eyebrow: 'Neukölln, Berlin · since 2018', headline: 'Six guests. One house. No cages, ever.', subhead: 'Home boarding for dogs who would rather be on a sofa than in a kennel, and in-home sitting for cats who would rather you left entirely.', align: 'center', minHeight: 'full', image: img('care-fellnest-house-evening'), overlay: 'dark', cta: { label: 'See the house', href: '#tour' } }),
      b('tour', 'carousel', { title: 'Walk through it', autoplay: true, items: [
        { src: img('care-fellnest-livingroom-dogs'), alt: 'Three dogs asleep on a large sofa in a bright living room', caption: 'The living room, 15:00, peak activity' },
        { src: img('care-fellnest-garden-fence'), alt: 'Fenced back garden with raised beds and a paddling pool', caption: '180m² garden, 1.9m fence, double-gated' },
        { src: img('care-fellnest-sleep-nooks'), alt: 'Row of open sleeping nooks with washable beds', caption: 'Open nooks — a door only if your dog asks for one' },
        { src: img('care-fellnest-cat-window'), alt: 'Tabby cat on a window ledge in a client apartment', caption: 'Cat visits happen in your flat, not ours' },
        { src: img('care-fellnest-kitchen-feeding'), alt: 'Feeding station with labelled containers for each guest', caption: 'Your food, your portions, your schedule' },
      ] }),
      b('rooms', 'gallery', { layout: 'masonry', columns: 3, gap: 'lg', lightbox: true, items: [
        { src: img('care-fellnest-room-quiet'), alt: 'Small quiet room with a covered crate and a blanket', caption: 'The quiet room, for nervous first-timers' },
        { src: img('care-fellnest-tempelhof-walk'), alt: 'Dogs walking across the open field at Tempelhof', caption: 'Tempelhofer Feld, twice daily' },
        { src: img('care-fellnest-canal-morning'), alt: 'Morning walk along the Landwehrkanal', caption: 'Landwehrkanal, the 7am round' },
        { src: img('care-fellnest-towel-station'), alt: 'Towel and paw-washing station by the back door', caption: 'Nobody comes in muddy' },
        { src: img('care-fellnest-senior-dog-rug'), alt: 'Senior dog resting on an orthopaedic bed by a radiator', caption: 'Orthopaedic beds for the old boys' },
        { src: img('care-fellnest-medication-board'), alt: 'Whiteboard listing each guest’s medication and times', caption: 'Meds board, checked off twice a day' },
      ] }),
      b('films', 'video-gallery', { title: 'What you get sent, every day', layout: 'grid', columns: 3, items: [
        { provider: 'youtube', src: 'hV2rQ8mLp4T', title: 'Morning at Tempelhofer Feld — 90 seconds', poster: img('care-fellnest-film-morning') },
        { provider: 'youtube', src: 'xB6nD3wKs9F', title: 'Garden hour, and who shares a paddling pool', poster: img('care-fellnest-film-garden') },
        { provider: 'vimeo', src: '904712358', title: 'Settling in: a nervous dog’s first 48 hours', poster: img('care-fellnest-film-settling') },
      ] }),
      b('rates', 'services-catalogue', { title: 'Rates 2026', subtitle: 'Per animal, per day, VAT included. Christmas and Easter are +25% and book out by March.', items: [
        { name: 'Dog home boarding', description: 'Overnight in the house, two walks, garden access, daily video and photo update.', price: '€42/day', ctaLabel: 'Reserve', ctaHref: '#book' },
        { name: 'Second dog, same household', description: 'Same room, same bed if they insist. Fed separately regardless.', price: '€30/day', ctaLabel: 'Reserve', ctaHref: '#book' },
        { name: 'Cat sitting, in your home', description: 'Two visits a day: food, water, litter, play, plants and post. Photo after each visit.', price: '€26/day', ctaLabel: 'Reserve', ctaHref: '#book' },
        { name: 'Small animals', description: 'Rabbits, guinea pigs, birds — one visit a day, cleaning included.', price: '€18/day', ctaLabel: 'Reserve', ctaHref: '#book' },
        { name: 'Trial night', description: 'Required before a first boarding. Drop-off at 17:00, pick-up after breakfast.', price: '€25', ctaLabel: 'Book a trial', ctaHref: '#book' },
        { name: 'Vet run', description: 'Transport and attendance at your practice if something happens while you are away.', price: '€35 + fare', ctaLabel: 'Reserve', ctaHref: '#book' },
      ] }),
      b('sitters', 'team', { title: 'Who is actually in the house', subtitle: 'Two of us live here. Nobody boards without a police clearance and a first-aid certificate.', columns: 3, members: [
        { name: 'Jonas Rieck', role: 'Owner · lives on site', photo: img('care-fellnest-jonas'), bio: 'Twelve years with dogs, six of them at a Kreuzberg shelter. Certified in canine first aid, erweitertes Führungszeugnis on file, and the one who does the 6:40 walk.' },
        { name: 'Amaia Etxeberria', role: 'Boarding lead', photo: img('care-fellnest-amaia'), bio: 'Veterinary nurse by training, which is why the medication board exists. Handles seniors, post-op guests and anything requiring an injection.' },
        { name: 'Tobi Lange', role: 'Cat sitter, Kreuzberg round', photo: img('care-fellnest-tobi'), bio: 'Does the in-home cat visits on foot and by bike. Insured, key-bonded, and has never once forgotten to water a plant.' },
      ] }),
      b('reviews', 'reviews', { title: 'Reviews', subtitle: 'From Google and from the Berlin dog owners’ forum.', average: '4.9', count: '167', source: 'Google', items: [
        { rating: 5, quote: 'Our anxious Podenco has stayed eleven times. He walks in and goes straight to his nook. That is the whole review.', author: 'Kathrin W.', date: 'June 2026', source: 'google' },
        { rating: 5, quote: 'Amaia noticed our cat wasn’t drinking on day two, called our vet, and sent us the invoice with an apology. We would have come home to a much worse situation.', author: 'Léa D.', date: 'April 2026', source: 'google' },
        { rating: 5, quote: 'The daily video is not a marketing gimmick, it is ninety seconds of your dog being fine, which is exactly what you want at an airport.', author: 'Marcus H.', date: 'February 2026', source: 'trustpilot' },
      ] }),
      b('book', 'booking', {
        title: 'Reserve your dates',
        intro: 'Tell us the dates and the animal. We hold the space for 48 hours while we arrange the trial night.',
        submitLabel: 'Request dates',
        successMessage: 'Danke — we will confirm within 24 hours.',
        serviceLabel: 'Service',
        services: [
          { name: 'Dog home boarding', duration: 'per night', price: '€42' },
          { name: 'Cat sitting, in your home', duration: '2 visits/day', price: '€26' },
          { name: 'Small animals', duration: '1 visit/day', price: '€18' },
          { name: 'Trial night', duration: '17:00 – 09:00', price: '€25' },
        ],
        askDate: true,
        askTime: false,
        askParty: true,
        askPhone: true,
        askNotes: true,
        notesLabel: 'Breed, age, medication, and how they are with other animals',
      }),
      b('find', 'map', { query: 'Weichselstraße 52, 12045 Berlin, Germany', zoom: 15, height: 340, label: 'Drop-off at the courtyard gate — ring Fellnest, not the main bell' }),
      b('footer', 'footer', { brand: 'Fellnest', tagline: 'Home boarding & pet sitting · Neukölln, Berlin · licensed under §11 TierSchG', links: [{ label: 'Rates', href: '#rates' }, { label: 'Sitters', href: '#sitters' }, { label: 'Reserve', href: '#book' }], copyright: '© Fellnest Tierbetreuung' }),
    ],
  }),

  tpl({
    id: 'care-elderly-companion',
    vertical: 'care',
    label: 'Companion Care — Editorial',
    description: 'A long-form page for elder companionship visits, written for the adult child making the decision.',
    tags: ['elder-care', 'long-form', 'family', 'faq', 'local'],
    layout: 'editorial',
    preset: 'mono',
    meta: { title: 'Saanjh — Companion Care for Elders, Pune', description: 'Unhurried companionship visits for older adults in Pune: conversation, walks, appointments and a weekly note home to family.', lang: 'en', favicon: '🫖' },
    blocks: [
      b('nav', 'nav', { brand: 'Saanjh', sticky: false, links: [{ label: 'Why we exist', href: '#opening' }, { label: 'A visit', href: '#visit' }, { label: 'Our people', href: '#people' }, { label: 'History', href: '#history' }, { label: 'Questions', href: '#questions' }] }),
      b('opening', 'rich-text', { blocks: [
        { kind: 'heading', text: 'Your parent is not ill. They are alone.' },
        { kind: 'paragraph', text: 'Most of the calls we get do not start with a medical problem. They start with someone in Bengaluru or Toronto noticing that the phone calls home have got shorter, that the fridge has the same vegetables in it as last week, and that nobody has visited since Diwali.' },
        { kind: 'paragraph', text: 'Saanjh does not do nursing. We do not give injections, we do not lift anyone out of a bed, and we will tell you plainly when what your parent needs is a nurse and not us. What we do is turn up, three afternoons a week, and stay for three hours — because loneliness is a health condition and it responds to being treated like one.' },
        { kind: 'quote', text: 'The first month, my father barely spoke to Kavita. The fourth month, he was annoyed if she was five minutes late.' },
        { kind: 'subheading', text: 'What the three hours are actually spent on' },
        { kind: 'bullet', text: 'Talking. Usually about the same things, which is fine, and which is most of it.' },
        { kind: 'bullet', text: 'A walk, if the knees allow — around the society compound, or as far as the Kalyani Nagar promenade.' },
        { kind: 'bullet', text: 'Tea, and often cooking together, because a kitchen gives a conversation somewhere to go.' },
        { kind: 'bullet', text: 'The small admin that quietly stops happening: bill payments, the pharmacy run, the electrician who never came.' },
        { kind: 'bullet', text: 'Medication reminders, and a written note if something looks different from last week.' },
      ] }),
      b('visit', 'split', { rows: [
        { title: 'The same person, the same days', text: 'Every client has one named companion and one named backup, and you meet both before we start. Rotating strangers through an 82-year-old’s living room is worse than sending nobody: it costs your parent the effort of an introduction every single week and gives them nothing in return. Our companions stay with a family for an average of two years and three months.', image: img('care-saanjh-companion-tea'), imageAlt: 'Two people sitting with tea in a sunlit living room' },
        { title: 'A note home, every Sunday', text: 'On Sunday evening you get a short written note — not a form, not a dashboard. What was talked about, what was eaten, how the walk went, and anything that seemed different. Families abroad tell us this is the part they did not know they needed, because it replaces the guesswork between phone calls with something specific enough to act on.', image: img('care-saanjh-weekly-note'), imageAlt: 'Handwritten weekly note on a desk beside a phone' },
        { title: 'Appointments, attended properly', text: 'A companion goes to the cardiologist with your parent, writes down what is actually said, asks the question your father was too polite to ask, and sends you the notes the same evening. We do not make medical decisions. We make sure the people who do have heard the whole story, including the bit about the dizziness three Tuesdays ago.', image: img('care-saanjh-clinic-waiting'), imageAlt: 'Companion and older adult waiting together at a clinic' },
        { title: 'Where we stop', text: 'We are not a nursing service. No wound care, no catheters, no transfers, no injections, and no overnight cover. If your parent needs those, we will say so at the first assessment and put you in touch with two agencies in Pune who do it well. We would rather lose the client than take a fee for the wrong thing.', image: img('care-saanjh-garden-walk'), imageAlt: 'Older adult walking with a companion through a garden path' },
      ] }),
      b('people', 'about', { eyebrow: 'Who we hire', title: 'Fourteen companions, all trained here', body: 'Every companion completes a four-week induction before their first visit: dementia communication, safeguarding and abuse recognition, basic first aid and CPR, elder mobility, and a full day on the one skill nobody teaches — how to sit with somebody in silence without filling it. We police-verify every companion, hold two verified references, and re-check annually. Nine of the fourteen have been with us for more than three years, which in this sector is unusual and is entirely a function of paying properly.', image: img('care-saanjh-team-training'), imageAlt: 'Small group in a training session around a table', imageSide: 'left' }),
      b('rates', 'services-catalogue', { title: 'What it costs', subtitle: 'Monthly, billed in advance. No joining fee, no notice period beyond two weeks.', items: [
        { name: 'Three afternoons a week', description: 'Three hours a visit, same companion, Sunday note home. Our most common arrangement.', price: '₹18,000/month' },
        { name: 'Daily companionship', description: 'Six days a week, three hours, with a named backup companion for leave.', price: '₹34,000/month' },
        { name: 'Single visit', description: 'For families testing the idea, or covering a fortnight away. Works out dearer per visit than a monthly plan, which is the honest way round.', price: '₹1,600/visit' },
        { name: 'Appointment escort', description: 'Pick-up, waiting, consultation notes, drop-home. Cab fare at actuals.', price: '₹1,200/visit' },
        { name: 'First assessment', description: 'Ninety minutes at home with you and your parent. Always free, never a sales call.', price: 'Free' },
      ] }),
      b('history', 'timeline', { title: 'How Saanjh got here', items: [
        { date: '2019', title: 'One flat in Aundh', text: 'Started after our founder spent a year visiting a neighbour nobody else visited.' },
        { date: '2021', title: 'The Sunday note', text: 'Written for one family in Dubai during the pandemic, then adopted for everyone.' },
        { date: '2023', title: 'Fourteen companions', text: 'Induction training formalised into four weeks, with an outside safeguarding trainer.' },
        { date: '2025', title: 'Dementia specialism', text: 'Six companions complete advanced dementia communication training with a Pune neurologist.' },
        { date: '2026', title: '190 families', text: 'Across Aundh, Kalyani Nagar, Kothrud and Viman Nagar. Still no nursing, deliberately.' },
      ] }),
      b('words', 'testimonials', { title: 'From the families', items: [
        { quote: 'I live in Toronto. For four years I had no idea how my mother actually was. Now I get a paragraph every Sunday and I sleep.', author: 'Anjali R.', role: 'Daughter · Kalyani Nagar' },
        { quote: 'They told us at the assessment that we needed a nurse, not a companion, and gave us two numbers. They earned us as clients eighteen months later by being honest that day.', author: 'Suresh and Padma K.', role: 'Kothrud' },
        { quote: 'Kavita has now been coming for three years. My father calls her his youngest and worst-behaved child.', author: 'Nikhil D.', role: 'Son · Aundh' },
      ] }),
      b('questions', 'accordion', { title: 'What families ask us first', items: [
        { heading: 'My parent says they do not want anybody. What then?', body: 'That is the normal starting position and we plan for it. The first four visits are short — an hour, framed as help with a specific task rather than company. Almost everyone converts, and the ones who genuinely do not, we stop billing for. Nobody benefits from an unwanted visitor.' },
        { heading: 'Are companions police-verified?', body: 'Yes. Police verification through the local station, two independently contacted references, Aadhaar and address verification, and an annual re-check. The file for your companion is shared with you before the first visit.' },
        { heading: 'What happens in an emergency?', body: 'Companions carry a card with your parent’s conditions, medications, blood group and your numbers. They call an ambulance first, you second, us third, and stay at the hospital until family or our supervisor arrives. Every companion holds current first aid and CPR.' },
        { heading: 'Can we change companion?', body: 'Yes, without explanation and without awkwardness. Ring the office and we will introduce someone else that week. Personality fit is the entire product; pretending otherwise would be silly.' },
        { heading: 'Do you work with dementia?', body: 'Companionship, yes — six of our companions hold advanced dementia communication training and we are used to repetition, sundowning and shifting recognition. Personal and nursing care, no. We will be clear with you about where that line sits for your parent specifically.' },
      ] }),
      b('reach', 'contact-details', { title: 'Talk to us', address: 'Saanjh Care, 4th Floor, Amar Neptune, Baner Road, Pune 411045, Maharashtra', phone: '+91 20 4800 1122', email: 'families@saanjh.care', hours: 'Office Mon–Sat 9:30–18:30 · assessments in the evenings' }),
      b('footer', 'footer', { brand: 'Saanjh', tagline: 'Companion care for elders · Pune · not a nursing service, on purpose', links: [{ label: 'A visit', href: '#visit' }, { label: 'Rates', href: '#rates' }, { label: 'Questions', href: '#questions' }], copyright: '© Saanjh Care LLP' }),
    ],
  }),

  tpl({
    id: 'care-home-care-agency',
    vertical: 'care',
    label: 'Home Care Agency — Catalogue',
    description: 'A regulated domiciliary care agency putting its full package list, funding routes and inspection record first.',
    tags: ['home-care', 'b2b', 'pricing', 'faq', 'long-form'],
    layout: 'catalogue',
    preset: 'ocean',
    meta: { title: 'Northgate Home Care — Manchester & Trafford', description: 'CQC-registered domiciliary care across Manchester and Trafford: personal care, dementia support, live-in and respite.', lang: 'en', favicon: '🏠' },
    blocks: [
      b('notice', 'announcement-bar', { text: 'Recruiting care workers across Trafford — £13.85/hr, paid travel time, guaranteed hours.', linkLabel: 'See what we offer', href: '#jobs', tone: 'info', dismissible: true }),
      b('nav', 'nav', { brand: 'Northgate Home Care', sticky: true, links: [{ label: 'Packages', href: '#packages' }, { label: 'Hourly rates', href: '#rates' }, { label: 'Funding', href: '#funding' }, { label: 'Our team', href: '#team' }, { label: 'Questions', href: '#faq' }], cta: { label: 'Request an assessment', href: '#enquire' } }),
      b('packages', 'services-catalogue', {
        title: 'Care packages',
        subtitle: 'Every package starts with a free needs assessment at home, carried out by a registered nurse. CQC-registered, provider ID 1-1097442833, rated Good with Outstanding for Caring (March 2025).',
        items: [
          { name: 'Personal care visits', description: 'Washing, dressing, continence support, medication prompting and administration. From 30 minutes, up to four visits a day.', price: 'from £19.50/visit', ctaLabel: 'Enquire', ctaHref: '#enquire' },
          { name: 'Dementia support', description: 'Consistent named workers trained to Level 3 in dementia care, with life-story planning and family coaching.', price: 'from £32.00/hr', ctaLabel: 'Enquire', ctaHref: '#enquire' },
          { name: 'Live-in care', description: 'One worker living in the home, with a two-week rotation and a second worker for cover. Cheaper than most residential placements.', price: 'from £1,395/wk', ctaLabel: 'Enquire', ctaHref: '#enquire' },
          { name: 'Night care — sleeping', description: 'A worker sleeps in and is available for up to two calls a night. Beyond that it becomes waking cover.', price: '£165/night', ctaLabel: 'Enquire', ctaHref: '#enquire' },
          { name: 'Night care — waking', description: 'Awake and on duty for ten hours, for repositioning, catheter care and high falls risk.', price: '£265/night', ctaLabel: 'Enquire', ctaHref: '#enquire' },
          { name: 'Respite & holiday cover', description: 'Short-term cover so a family carer can take a break. Minimum three days, book two weeks ahead.', price: 'from £31.00/hr', ctaLabel: 'Enquire', ctaHref: '#enquire' },
          { name: 'Reablement after hospital', description: 'Six-week intensive support after a discharge, tapering as independence returns. Referrals accepted directly from ward teams.', price: 'Block-costed', ctaLabel: 'Enquire', ctaHref: '#enquire' },
          { name: 'Companionship & errands', description: 'Non-personal-care hours: shopping, appointments, company. Often used alongside a personal care package.', price: '£26.00/hr', ctaLabel: 'Enquire', ctaHref: '#enquire' },
          { name: 'End of life care', description: 'Delivered with the district nursing team and hospice at home. Available at short notice, including same-day.', price: 'On assessment', ctaLabel: 'Enquire', ctaHref: '#enquire' },
        ],
      }),
      b('rates', 'pricing', { title: 'What it costs by the hour', subtitle: 'Weekday daytime rates. Weekends +12%, bank holidays +50%. No joining fee and no contractual notice period beyond seven days.', plans: [
        { name: '30-minute call', price: '£19.50', period: 'per visit', features: ['Medication, prompting, a check-in', 'Two workers if the care plan requires', 'Electronic call monitoring, timed in and out', 'Minimum two calls a day'], ctaLabel: 'Ask about calls', ctaHref: '#enquire' },
        { name: 'Hourly care', price: '£29.50', period: 'per hour', features: ['Full personal care', 'Named worker plus named backup', 'Care plan reviewed every 8 weeks', 'App access for the whole family', 'Same rate for 1 hour or 6'], ctaLabel: 'Request assessment', ctaHref: '#enquire', featured: true },
        { name: 'Live-in care', price: '£1,395', period: 'per week', features: ['One worker in the home', 'Two-week on and off rotation', 'Two hours off each day covered by us', 'Includes night availability', 'Couples: +£240/wk, not double'], ctaLabel: 'Compare with residential', ctaHref: '#enquire' },
      ] }),
      b('numbers', 'stats', { title: 'Northgate in numbers', columns: 4, items: [
        { value: '1,140', label: 'Visits a week' },
        { value: '96', label: 'Care workers employed' },
        { value: '4.2', label: 'Average worker tenure', suffix: ' yrs' },
        { value: '98.4', label: 'Calls on time, last quarter', suffix: '%' },
      ] }),
      b('funding', 'tabs', { items: [
        { label: 'Paying privately', text: 'Most of our clients fund their own care. You are invoiced monthly in arrears against a timesheet you can see in the app, and you can increase, reduce or stop the package with seven days’ notice. There is no minimum contract, no assessment fee, and no charge for a care plan review. If your circumstances change — a hospital admission, a family member moving in — we will happily reduce a package rather than quietly keep billing it.' },
        { label: 'Local authority funded', text: 'We hold framework contracts with Manchester City Council and Trafford Council. If your assessed needs qualify, the council commissions the hours directly and you may contribute based on a financial assessment. Ask your social worker for Northgate by name — you are entitled to express a preference, and if we have capacity in your postcode we will take the referral. We can also take direct payments if you would rather commission us yourself with council money.' },
        { label: 'NHS Continuing Healthcare', text: 'If your needs are primarily health rather than social, CHC funding may cover the full cost of care at home, including live-in. It is a difficult assessment to navigate. Our registered manager sits in on CHC checklists and full assessments with families at no charge, whether or not you end up commissioning us, because far too many people are told they do not qualify when nobody has read the framework properly.' },
        { label: 'Direct payments', text: 'Holding a direct payment gives you the most control and usually the most hours per pound. We can be commissioned in whole or in part — some families use us for the personal care calls and employ their own personal assistant for companionship hours. We will help you cost that split honestly, even where it means fewer hours for us.' },
      ] }),
      b('team', 'team', { title: 'Who runs it', subtitle: 'The registered manager is named on our CQC registration and answers the phone.', columns: 3, members: [
        { name: 'Grace Okonjo', role: 'Registered Manager', photo: img('care-northgate-grace'), bio: 'Registered nurse, 22 years, nine of them as a district nursing sister in Wythenshawe. Registered with CQC as manager since 2019 and personally signs off every care plan.' },
        { name: 'Dan Whitaker', role: 'Head of Care Quality', photo: img('care-northgate-dan'), bio: 'Runs supervision, spot checks and the complaints log. Was a care worker here for six years before this and still covers rounds at Christmas.' },
        { name: 'Salma Iqbal', role: 'Training Lead', photo: img('care-northgate-salma'), bio: 'Delivers the Care Certificate in-house plus Level 3 dementia, moving-and-handling and medication competency. Nobody works unsupervised until she signs them off.' },
      ] }),
      b('checks', 'features', { title: 'What every worker has before their first shift', columns: 3, items: [
        { icon: '🛡️', title: 'Enhanced DBS', text: 'Enhanced DBS with adult barred list check, on the Update Service, re-checked every three years.' },
        { icon: '📚', title: 'Care Certificate', text: 'All 15 standards completed in-house, plus four shadowed shifts before working alone.' },
        { icon: '💊', title: 'Medication competency', text: 'Assessed and re-assessed annually against NICE guidance for medicines in the community.' },
        { icon: '🤝', title: 'Two references', text: 'Both verified by phone, including the most recent employer. Gaps in employment are always asked about.' },
        { icon: '🏋️', title: 'Moving & handling', text: 'Practical assessment with hoists and slide sheets, refreshed every twelve months.' },
        { icon: '🚗', title: 'Business insurance', text: 'Checked at induction and annually. Travel time between calls is paid, so nobody rushes your visit.' },
      ] }),
      b('partners', 'logos', { title: 'We work alongside', items: [
        { src: img('care-northgate-logo-cqc'), alt: 'Care Quality Commission — registered provider' },
        { src: img('care-northgate-logo-mcc'), alt: 'Manchester City Council — framework provider' },
        { src: img('care-northgate-logo-trafford'), alt: 'Trafford Council — approved provider' },
        { src: img('care-northgate-logo-hospice'), alt: 'Local hospice — hospice at home partner' },
        { src: img('care-northgate-logo-skills'), alt: 'Skills for Care — endorsed learning provider' },
      ] }),
      b('faq', 'faq', { title: 'Questions families ask', items: [
        { question: 'How quickly can care start?', answer: 'Usually within 72 hours of the assessment, and same-day for hospital discharges and end-of-life referrals. If we cannot staff your postcode safely we will tell you on the phone rather than take a deposit and hope.' },
        { question: 'Will it be the same carer every time?', answer: 'You get a named worker and a named backup, and they cover the large majority of calls. We will not promise one person and only one person — that promise breaks the first time somebody is ill, and the way agencies hide that is by sending strangers unannounced.' },
        { question: 'What if we are not happy?', answer: 'Ring Grace directly on the number below. Complaints are logged, acknowledged in two working days and answered in ten, and the log goes to CQC. You can also change worker with no explanation required.' },
        { question: 'Do you charge for travel time?', answer: 'Not to you. We pay our workers for travel between calls out of the hourly rate, which is why our rate is a pound or two above the cheapest agency in Manchester and why our calls run on time.' },
        { question: 'Is live-in really cheaper than a care home?', answer: 'For one person it is roughly line-ball, and we will not pretend otherwise — the average Greater Manchester residential fee with nursing is now above £1,300 a week, against our £1,395. What the same money buys is one worker for one person rather than one worker for six, in their own house. For a couple it is genuinely cheaper, because live-in charges a £240 supplement rather than a second full fee.' },
      ] }),
      b('jobs', 'cta', { headline: 'We are hiring care workers across Trafford', subhead: '£13.85 an hour, paid travel time, guaranteed-hours contracts, and the Care Certificate paid for. Experience welcome, not required.', background: 'accent', button: { label: 'See open roles', href: '#' } }),
      b('enquire', 'contact-form', {
        title: 'Request a free assessment',
        intro: 'A registered nurse visits, spends about ninety minutes, and writes you a plan whether or not you use us. No obligation and no cost.',
        submitLabel: 'Request an assessment',
        successMessage: 'Thank you — we will call you within one working day.',
        fields: [
          { name: 'name', label: 'Your name', type: 'text', required: true },
          { name: 'relationship', label: 'Who is the care for?', type: 'select', options: ['Myself', 'My parent', 'My partner', 'Another relative', 'A patient (professional referral)'], required: true },
          { name: 'phone', label: 'Best number', type: 'tel', placeholder: '0161 000 0000', required: true },
          { name: 'email', label: 'Email', type: 'email', placeholder: 'you@example.com' },
          { name: 'postcode', label: 'Postcode', type: 'text', placeholder: 'M20 …', required: true },
          { name: 'package', label: 'What are you looking for?', type: 'select', options: ['Personal care visits', 'Dementia support', 'Live-in care', 'Night care', 'Respite', 'Hospital discharge', 'Not sure yet'], required: true },
          { name: 'urgency', label: 'When do you need it?', type: 'select', options: ['Immediately', 'Within a week', 'Within a month', 'Planning ahead'] },
          { name: 'notes', label: 'Anything we should know?', type: 'textarea', placeholder: 'Conditions, mobility, medication, who else is involved…' },
        ],
      }),
      b('office', 'contact-details', { title: 'The office', address: 'Northgate Home Care, Unit 4, Longford Works, Chester Road, Stretford, Manchester M32 0RS', phone: '+44 161 850 4400', email: 'care@northgatehomecare.co.uk', hours: 'Office Mon–Fri 8:30–17:30 · on-call 24/7 for existing clients' }),
      b('policies', 'legal', { title: 'Our policies', align: 'center', separator: '·', documents: [
        { label: 'Complaints procedure', title: 'Complaints procedure', content: 'We would always rather hear from you early.\n\nStage one — ring the office and ask for the registered manager. We aim to resolve most concerns on the call, and we acknowledge every complaint in writing within two working days.\n\nStage two — if you are not satisfied, we investigate formally and respond in full within ten working days, including what we are changing as a result.\n\nStage three — you may escalate to the Local Government and Social Care Ombudsman, or, if your care is council-funded, to your commissioning authority. Concerns about safety can be raised with the Care Quality Commission at any point, including instead of contacting us first.' },
        { label: 'Safeguarding statement', title: 'Safeguarding adults', content: 'Every member of staff completes safeguarding training at induction and annually, and has a duty to report any concern about abuse or neglect the same day, whether or not it involves Northgate.\n\nConcerns go to the registered manager and, where the threshold is met, to the local authority safeguarding team and to the Care Quality Commission. We do not require certainty before reporting — a suspicion is enough, and no member of staff has ever been penalised for raising one.\n\nWhistleblowing is protected. Staff may report directly to the regulator without going through us.' },
        { label: 'Privacy notice', title: 'How we handle your data', content: 'We process personal and health data in order to plan and deliver your care, on the lawful bases of contract and, for health information, the provision of health and social care under UK GDPR Article 9(2)(h).\n\nCare records are held electronically for eight years after care ends, as required by records-management guidance, and are then securely destroyed. Access is limited to the workers involved in your care, the office team and the registered manager.\n\nYou may request a copy of everything we hold about you at any time, free of charge, and we will provide it within one calendar month.' },
      ] }),
      b('footer', 'footer', { brand: 'Northgate Home Care', tagline: 'CQC provider ID 1-1097442833 · Manchester & Trafford', links: [{ label: 'Packages', href: '#packages' }, { label: 'Funding', href: '#funding' }, { label: 'Careers', href: '#jobs' }, { label: 'Policies', href: '#policies' }], copyright: '© Northgate Home Care Ltd' }),
    ],
  }),

  tpl({
    id: 'care-house-sitter',
    vertical: 'care',
    label: 'House Sitter — Minimal',
    description: 'A stripped-back page for a professional house sitter: what they cover, what it costs, one form.',
    tags: ['house-sitting', 'one-pager', 'dark', 'local', 'pets'],
    layout: 'minimal',
    preset: 'midnight',
    meta: { title: 'Adobe & Key — House Sitting, Santa Fe', description: 'Professional, insured house sitting in Santa Fe and Eldorado. Occupied homes, watered plants, fed animals, nothing left to chance.', lang: 'en', favicon: '🔑' },
    blocks: [
      b('nav', 'nav', { brand: 'Adobe & Key', sticky: false, links: [{ label: 'What I cover', href: '#covers' }, { label: 'Rates', href: '#rates' }, { label: 'Clients', href: '#clients' }], cta: { label: 'Check my dates', href: '#enquire' } }),
      b('hero', 'hero', { eyebrow: 'Santa Fe · Eldorado · Tesuque', headline: 'Your house, lived in while you’re gone', subhead: 'One sitter, one house at a time, never more. Lights on, mail in, pipes checked, animals fed, and a text every evening.', align: 'left', minHeight: 'md', overlay: 'none', cta: { label: 'Check my dates', href: '#enquire' } }),
      b('covers', 'features', { title: 'What house sitting actually means here', subtitle: 'I stay in the house. I do not drop by twice a day and call it sitting.', columns: 2, items: [
        { icon: '🌙', title: 'Every night, in residence', text: 'I sleep at the house for the full engagement. An occupied home does not get broken into, and a frozen pipe gets caught in an hour rather than a week.' },
        { icon: '🐈', title: 'Animals in their own home', text: 'Cats, dogs, chickens, an elderly horse once. Fed on your schedule, medicated if needed, and never boarded away from the place they know.' },
        { icon: '🪴', title: 'Plants and drip lines', text: 'Interior watering by your notes, and I will run and check the drip system — Santa Fe summers punish an unattended garden in about nine days.' },
        { icon: '❄️', title: 'Winter watch', text: 'Thermostats monitored, faucets dripped below 20°F, roof and vigas checked after snow, and a shoveled walk so the house does not look empty.' },
        { icon: '📦', title: 'Mail, deliveries, contractors', text: 'Mail and packages in daily. I will let in a scheduled contractor and stay with them, and I will refuse an unscheduled one.' },
        { icon: '📱', title: 'A nightly text', text: 'Short, same time each evening, with a photo of whichever animal is being least cooperative. Silence from a sitter is the thing you should never accept.' },
      ] }),
      b('rates', 'services-catalogue', { title: 'Rates', subtitle: 'Flat nightly rate for Santa Fe County. Half rate for the arrival day, no charge for departure morning.', items: [
        { name: 'Standard night', description: 'House, mail, plants, and up to two animals.', price: '$95/night' },
        { name: 'Additional animals', description: 'Beyond two, per animal, per night. Livestock quoted separately.', price: '$12/night' },
        { name: 'Long stay, 21+ nights', description: 'Snowbird and sabbatical rate, billed monthly.', price: '$78/night' },
        { name: 'Meet and walkthrough', description: 'An hour at the house before you book. Free, and I bring a checklist you keep.', price: 'Free' },
      ] }),
      b('clients', 'testimonials', { title: 'Clients', items: [
        { quote: 'We came back from six weeks in Portugal to a house that smelled like a house, not like a closed-up house. Also the cat did not punish us, which was new.', author: 'Bill & Teresa H.', role: 'Eldorado · 2025 and 2026' },
        { quote: 'A pipe let go in the guest bath on a Tuesday night. They had the water off in four minutes and a plumber there by nine the next morning. I found out afterward.', author: 'Renata C.', role: 'Casa Solana' },
        { quote: 'Licensed, bonded, insured, and turned up with a printed checklist at the walkthrough. That was the whole decision.', author: 'Doug M.', role: 'Tesuque' },
      ] }),
      b('enquire', 'contact-form', {
        title: 'Check my dates',
        intro: 'Insured to $2M through Pet Sitters Associates, bonded, background-checked every January, and happy to hand you three local references before you tell me anything about your house.',
        submitLabel: 'Send',
        successMessage: 'Thanks — I answer every enquiry within a day.',
        fields: [
          { name: 'name', label: 'Name', type: 'text', required: true },
          { name: 'email', label: 'Email', type: 'email', placeholder: 'you@example.com', required: true },
          { name: 'dates', label: 'Dates you need covered', type: 'text', placeholder: 'e.g. Nov 3 – Nov 24', required: true },
          { name: 'area', label: 'Where is the house?', type: 'select', options: ['Santa Fe city', 'Eldorado', 'Tesuque', 'La Cienega', 'Elsewhere in Santa Fe County'], required: true },
          { name: 'animals', label: 'Animals', type: 'text', placeholder: 'e.g. two cats, one senior dog on meds' },
          { name: 'notes', label: 'Anything else', type: 'textarea', placeholder: 'Drip system, gate codes, the neighbor who has a key…' },
        ],
      }),
      b('footer', 'footer', { brand: 'Adobe & Key', tagline: 'House sitting · Santa Fe, New Mexico · licensed, bonded, insured', links: [{ label: 'What I cover', href: '#covers' }, { label: 'Rates', href: '#rates' }], copyright: '© Adobe & Key House Sitting' }),
    ],
  }),

  tpl({
    id: 'care-doula-postnatal',
    vertical: 'care',
    label: 'Doula & Postnatal — Conversational',
    description: 'A doula practice that answers the awkward first questions in a real transcript before selling anything.',
    tags: ['doula', 'postnatal', 'family', 'faq', 'booking'],
    layout: 'conversational',
    preset: 'candy',
    meta: { title: 'Nest & Nourish — Birth & Postnatal Doula, Adelaide', description: 'Birth support and postnatal doula care across Adelaide: continuity, night support, and no agenda about how you feed or birth.', lang: 'en', favicon: '🪺' },
    blocks: [
      b('nav', 'nav', { brand: 'Nest & Nourish', sticky: true, links: [{ label: 'Ask me anything', href: '#thread' }, { label: 'Packages', href: '#packages' }, { label: 'How it works', href: '#how' }, { label: 'Families', href: '#families' }], cta: { label: 'Book a free chat', href: '#book' } }),
      b('hero', 'hero', { eyebrow: 'Adelaide & the inner south', headline: 'Someone in your corner who has done this 200 times', subhead: 'Birth support and postnatal doula care — practical, unshockable, and completely without an opinion about how you should be doing it.', align: 'center', minHeight: 'sm', overlay: 'none', cta: { label: 'Read a real first chat', href: '#thread' } }),
      b('thread', 'chat-thread', {
        title: 'A first conversation, shared with permission',
        subtitle: 'A real message thread from a client at 31 weeks. Names changed, nothing else.',
        participants: [
          { id: 'parent', name: 'Steph', role: 'user' },
          { id: 'doula', name: 'Meg — Nest & Nourish', role: 'agent', avatar: img('care-doula-meg-avatar') },
        ],
        messages: [
          { from: 'parent', time: '9:12 pm', body: [
            { kind: 'text', text: 'Hi — I got your number from the Unley parents group. I honestly don’t know if I need a doula. I have a midwife and a partner. Is this a silly question?' },
          ] },
          { from: 'doula', time: '9:20 pm', body: [
            { kind: 'text', text: 'Not silly at all, it’s the question I get most. Short version: your midwife is responsible for clinical safety and may change at shift handover. Your partner will be brilliant and will also be having their own enormous day. I’m the only person in the room whose entire job is you, and who’ll still be there at 4am.' },
          ] },
          { from: 'parent', time: '9:23 pm', body: [
            { kind: 'text', text: 'Okay. What do you actually DO though. Like physically.' },
          ] },
          { from: 'doula', time: '9:31 pm', body: [
            { kind: 'text', text: 'Genuinely, mostly this:' },
            { kind: 'list', ordered: false, items: [
              { label: 'Counter-pressure on your hips and lower back, for hours if that’s what helps' },
              { label: 'Keeping the room how you want it — lights, noise, who is and isn’t in it' },
              { label: 'Reminding you of the question to ask when someone offers you a decision at 3am' },
              { label: 'Feeding your partner, so they can keep going too' },
              { label: 'Nothing clinical. No exams, no monitoring, no advice that overrides your midwife' },
            ] },
          ] },
          { from: 'parent', time: '9:35 pm', body: [
            { kind: 'text', text: 'I want an epidural. Like, I have wanted one since before I was pregnant. Do you still work with people like me or is that a thing' },
          ] },
          { from: 'doula', time: '9:38 pm', body: [
            { kind: 'text', text: 'It is absolutely not a thing. Roughly half my clients plan an epidural and I have never once talked anyone out of one. I’ll help you time it well, get you comfortable afterwards, and keep you moving in bed so the labour keeps progressing. My job is your plan, not mine.' },
          ] },
          { from: 'parent', time: '9:41 pm', body: [
            { kind: 'text', text: 'What about after. Everyone keeps saying the first six weeks are the hard bit and nobody will say why' },
          ] },
          { from: 'doula', time: '9:52 pm', body: [
            { kind: 'text', text: 'Because it’s unglamorous and it doesn’t photograph well. Postnatal work is where I’m most useful, honestly. A typical four-hour visit:' },
            { kind: 'list', ordered: true, items: [
              { label: 'You shower and sleep while I hold the baby. That is not a joke, it is the main event.' },
              { label: 'Feeding support — bottle, breast, both, whatever you’re actually doing rather than what a poster said.' },
              { label: 'One load of washing, one meal in the fridge, one bench wiped.' },
              { label: 'A real conversation about how you are, with someone who won’t report back to your family.' },
            ] },
            { kind: 'image', src: img('care-doula-postnatal-kitchen'), alt: 'Prepared meals in containers on a kitchen bench beside a kettle' },
          ] },
          { from: 'parent', time: '9:55 pm', body: [
            { kind: 'text', text: 'That last one might be the bit I need most and I feel weird about that' },
          ] },
          { from: 'doula', time: '10:01 pm', body: [
            { kind: 'text', text: 'It’s the bit almost everyone needs most and almost nobody books for. Have a look at the postnatal package rather than the birth one — and come to a free chat first, at yours or over video. No deposit, no pressure, and I’ll tell you if I think you don’t need me.' },
            { kind: 'buttons', items: [
              { label: 'See the packages', href: '#packages' },
              { label: 'Book a free chat', href: '#book' },
            ] },
          ] },
        ],
      }),
      b('how', 'steps', { title: 'How working together goes', items: [
        { title: 'Free chat', text: 'An hour, at your place or on video. You ask everything. I check we actually like each other, because you are about to be very unguarded around me.' },
        { title: 'Two prenatal visits', text: 'Around 32 and 37 weeks. We write your preferences down properly, talk through what happens if things change, and practise positions with your partner.' },
        { title: 'On call from 38 weeks', text: 'Phone on, bag packed, two hours from anywhere in metro Adelaide. I have a named backup doula you will have already met.' },
        { title: 'The birth', text: 'I join when you want me, at home or at the hospital, and stay until two hours after the baby arrives — usually until the first feed is done.' },
        { title: 'Postnatal visits', text: 'A visit in the first 72 hours, then as many as your package covers. Days, nights, or both.' },
        { title: 'A debrief at six weeks', text: 'We go back through the birth so the story you carry is accurate rather than the one your adrenaline wrote.' },
      ] }),
      b('packages', 'services-catalogue', { title: 'Packages', subtitle: 'Payment plans from 20 weeks, no interest. Some private health extras rebate postnatal support — ask and I will check your fund.', items: [
        { name: 'Birth support', description: 'Two prenatal visits, on call from 38 weeks, continuous support at the birth, one postnatal visit and a six-week debrief.', price: 'A$2,400', ctaLabel: 'Enquire', ctaHref: '#book' },
        { name: 'Postnatal — daytime', description: 'Six four-hour visits in the first eight weeks. Sleep, feeding support, meals, washing, and someone to talk to.', price: 'A$1,320', ctaLabel: 'Enquire', ctaHref: '#book' },
        { name: 'Postnatal — overnight', description: '10pm to 6am, awake with the baby so you get one unbroken block of sleep. Booked in threes.', price: 'A$460/night', ctaLabel: 'Enquire', ctaHref: '#book' },
        { name: 'The whole thing', description: 'Birth support plus eight daytime postnatal visits and two nights. What most second-time families book.', price: 'A$3,900', ctaLabel: 'Enquire', ctaHref: '#book' },
        { name: 'Single postnatal visit', description: 'Four hours, whenever the wheels come off. Available up to twelve months.', price: 'A$240', ctaLabel: 'Enquire', ctaHref: '#book' },
      ] }),
      b('creds', 'features', { title: 'Credentials, briefly', columns: 3, items: [
        { icon: '🎓', title: 'Certified doula', text: 'Certified through Doula Training Australia in 2016, and a current member of Australian Doulas.' },
        { icon: '🩹', title: 'First aid & CPR', text: 'HLTAID012 including infant CPR, renewed annually. Last renewed February 2026.' },
        { icon: '🛡️', title: 'Working with Children', text: 'Current WWCC and a national police check, both renewed every three years.' },
        { icon: '☂️', title: 'Insured', text: 'Professional indemnity and public liability to A$10m, certificate on request.' },
        { icon: '🍼', title: 'Feeding trained', text: 'Breastfeeding counsellor training with the Australian Breastfeeding Association, and unbothered by a bottle.' },
        { icon: '🫂', title: 'Perinatal mental health', text: 'Trained to recognise and refer, with standing links to two Adelaide perinatal psychologists.' },
      ] }),
      b('families', 'reviews', { title: 'Families', average: '5.0', count: '61', source: 'Google', items: [
        { rating: 5, quote: 'I had a caesarean after 26 hours, which was nothing like the plan. Meg was in recovery with me holding the baby while my husband slept in a chair, and she never once said anything about the plan.', author: 'Harriet M.', date: 'May 2026', source: 'google' },
        { rating: 5, quote: 'The overnight visits saved our marriage. Three nights of actual sleep in week two and we became people again.', author: 'Jules & Ani', date: 'March 2026', source: 'google' },
        { rating: 5, quote: 'She told me at the free chat that she didn’t think I needed a birth doula and to just book postnatal. Who does that? I booked both.', author: 'Nadia F.', date: 'November 2025', source: 'facebook' },
      ] }),
      b('faq', 'faq', { title: 'Still wondering', items: [
        { question: 'Are you allowed in the hospital?', answer: 'Yes. Doulas are support people at every Adelaide hospital and birth centre, and I have worked at four of them many times over. I introduce myself to your midwife, stay out of clinical space, and I have never had a problem.' },
        { question: 'What if you are at another birth?', answer: 'I take a maximum of three clients a month with a five-day gap between guess dates. If two of you overlap, my named backup — who you will have met at 34 weeks — comes instead, at no extra cost.' },
        { question: 'Is this instead of a midwife?', answer: 'Never. I do nothing clinical: no exams, no monitoring, no assessments, no advice that contradicts your care team. If you are choosing between a private midwife and a doula, get the midwife.' },
        { question: 'Do you work with same-sex and single parents?', answer: 'Yes, and with surrogates, adoptive parents and people whose families are not involved. I use whatever words for yourself and your body that you use.' },
        { question: 'What if we lose the baby?', answer: 'I stay. Bereavement support is part of what I do, at no charge beyond what you have already paid, for as long as you want me there.' },
      ] }),
      b('book', 'booking', {
        title: 'Book a free chat',
        intro: 'An hour, no cost, no obligation, at your place or over video. Bring your partner if you have one and every awkward question you have.',
        submitLabel: 'Request a chat',
        successMessage: 'Lovely — I will reply within a day to confirm.',
        serviceLabel: 'What are you thinking about?',
        services: [
          { name: 'Free introductory chat', duration: '60 min', price: 'Free' },
          { name: 'Birth support', duration: 'Full package', price: 'A$2,400' },
          { name: 'Postnatal — daytime', duration: '6 × 4 hours', price: 'A$1,320' },
          { name: 'Postnatal — overnight', duration: '10pm – 6am', price: 'A$460/night' },
          { name: 'Single postnatal visit', duration: '4 hours', price: 'A$240' },
        ],
        askDate: true,
        askTime: true,
        askParty: false,
        askPhone: true,
        askNotes: true,
        notesLabel: 'Due date, where you are birthing, and anything on your mind',
      }),
      b('socials', 'social-links', { title: 'Elsewhere', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'instagram', href: '#', label: '@nestandnourish.adl' },
        { platform: 'whatsapp', href: '#', label: 'Message Meg' },
        { platform: 'email', href: '#', label: 'meg@nestandnourish.com.au' },
      ] }),
      b('footer', 'footer', { brand: 'Nest & Nourish', tagline: 'Birth & postnatal doula · Adelaide, South Australia · Kaurna Country', links: [{ label: 'Packages', href: '#packages' }, { label: 'How it works', href: '#how' }, { label: 'Book', href: '#book' }], copyright: '© Nest & Nourish Doula Care' }),
    ],
  }),
];
