/**
 * `creator` starter templates — the social surface *is* the product: a makeup
 * influencer, a coach selling programmes, a travel writer, a recipe-reels cook,
 * a game streamer, a podcaster, a long-form YouTuber, a paid newsletter, and a
 * one-screen link-in-bio, across nine different page shapes.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const creatorTemplates: Template[] = [
  // ── beauty & makeup influencer ─────────────────────────────────────────────
  tpl({
    id: 'creator-beauty',
    vertical: 'creator',
    label: 'Beauty Creator — Showcase',
    description: 'A photo-led page for a makeup creator whose looks, tutorials and brand deals do the selling.',
    tags: ['beauty', 'gallery', 'video', 'social', 'b2c'],
    layout: 'showcase',
    preset: 'candy',
    meta: { title: 'Priya Solanki — Beauty', description: 'Everyday makeup for brown skin, filmed in real bathroom light. Looks, tutorials and the kit I actually use.', lang: 'en', favicon: '💄' },
    blocks: [
      b('promo', 'announcement-bar', { text: 'The Everyday Glow palette restocks Thursday, 9am GMT — 400 units.', linkLabel: 'See the kit', href: '#kit', tone: 'promo', dismissible: true }),
      b('nav', 'nav', { brand: 'PRIYA SOLANKI', sticky: true, links: [{ label: 'Looks', href: '#looks' }, { label: 'Tutorials', href: '#tutorials' }, { label: 'The kit', href: '#kit' }, { label: 'Work with me', href: '#partners' }], cta: { label: 'Get the Sunday edit', href: '#edit' } }),
      b('hero', 'hero', { eyebrow: 'London · filmed on a phone in bathroom light', headline: 'Makeup that survives a Tuesday.', subhead: 'Fourteen years of doing my own face badly, then eight doing it properly. Everything here is shot in the light you will actually get ready in — no ring light, no filter, no free-gifting nonsense.', align: 'left', minHeight: 'lg', image: img('creator-beauty-hero'), overlay: 'scrim', cta: { label: 'Watch a tutorial', href: '#tutorials' } }),
      b('looks', 'gallery', { layout: 'masonry', columns: 3, gap: 'md', lightbox: true, items: [
        { src: img('creator-beauty-look-glow'), alt: 'Close-up of a dewy skin-first base with a bare lip', caption: 'The 6-minute base — cream everything, no powder' },
        { src: img('creator-beauty-look-liner'), alt: 'A soft smudged brown liner on a hooded eye', caption: 'Smudged liner for hooded eyes (the version that stays put)' },
        { src: img('creator-beauty-look-wedding'), alt: 'A gold-toned festive eye with a deep berry lip', caption: 'Cousin-wedding face — built to last twelve hours and a dance floor' },
        { src: img('creator-beauty-look-blush'), alt: 'A high draped blush across the cheekbones and temples', caption: 'Draped blush, kept off the nose' },
        { src: img('creator-beauty-look-nomakeup'), alt: 'A bare face with groomed brows and lip balm only', caption: 'The four-product school-run face' },
        { src: img('creator-beauty-look-editorial'), alt: 'A graphic teal liner shot against a plain wall', caption: 'Playing with colour — teal on deeper skin tones' },
      ] }),
      b('tutorials', 'video-gallery', { title: 'Tutorials', layout: 'grid', columns: 3, items: [
        { provider: 'youtube', src: 'kR7mLcJq2vY', title: 'The 6-minute base I do most mornings', poster: img('creator-beauty-vid-base') },
        { provider: 'youtube', src: 'wQ3pT8nZ0uA', title: 'Foundation matching for medium-to-deep skin, honestly', poster: img('creator-beauty-vid-match') },
        { provider: 'youtube', src: 'bH9dV1sXe4M', title: 'Hooded eyes: five liner shapes, ranked' },
        { provider: 'youtube', src: 'Yq2fN6rTk8P', title: 'Twelve-hour wedding makeup, start to finish' },
        { provider: 'youtube', src: 'zC4jU7mDp1L', title: 'What I actually keep after a PR unboxing' },
        { provider: 'youtube', src: 'aM5xW0gRt6N', title: 'Brows for people who over-plucked in 2009' },
      ] }),
      b('kit', 'product', { title: 'The kit', subtitle: 'Only things still in my drawer after a year. Affiliate links are marked — they cost you nothing extra.', columns: 3, items: [
        { name: 'Everyday Glow palette', description: 'Four creams, one balm. The whole 6-minute base in one tin.', price: '£34', badge: 'Mine', image: img('creator-beauty-kit-palette'), ctaLabel: 'Buy', ctaHref: '#' },
        { name: 'Skin Tint 06 — Amber', description: 'The one I re-buy. Sheer, non-oxidising, no flashback.', price: '£29', was: '£36', image: img('creator-beauty-kit-tint'), ctaLabel: 'Shop (affiliate)', ctaHref: '#' },
        { name: 'Smudge brush no. 12', description: 'Short, stiff, cheap. Does 90% of the liner work on this page.', price: '£9', image: img('creator-beauty-kit-brush'), ctaLabel: 'Shop (affiliate)', ctaHref: '#' },
        { name: 'Setting mist — unscented', description: 'For the base, not the drama. Fragrance-free, so it plays nicely with retinol nights.', price: '£18', image: img('creator-beauty-kit-mist'), ctaLabel: 'Shop (affiliate)', ctaHref: '#' },
        { name: 'Brow soap and spoolie', description: 'Six pounds, and it replaced three brow gels.', price: '£6', badge: 'Cheap', image: img('creator-beauty-kit-brow'), ctaLabel: 'Shop (affiliate)', ctaHref: '#' },
        { name: 'The Glow Guide (PDF)', description: 'Forty pages: shade-matching, undertones, and my full drawer with prices.', price: '£12', image: img('creator-beauty-kit-guide'), ctaLabel: 'Download', ctaHref: '#' },
      ] }),
      b('partners', 'logos', { title: 'Brands I have worked with', items: [
        { src: img('creator-beauty-brand-lumen'), alt: 'Lumen Beauty', href: '#' },
        { src: img('creator-beauty-brand-saffron'), alt: 'Saffron & Co.', href: '#' },
        { src: img('creator-beauty-brand-northlight'), alt: 'Northlight Cosmetics', href: '#' },
        { src: img('creator-beauty-brand-halva'), alt: 'Halva Skin', href: '#' },
        { src: img('creator-beauty-brand-orchid'), alt: 'Orchid Street', href: '#' },
        { src: img('creator-beauty-brand-bellweather'), alt: 'Bellweather Media', href: '#' },
      ] }),
      b('words', 'reviews', { title: 'From the comments', subtitle: 'Pulled straight off the videos, typos included.', average: '4.9', count: '2,100+ comments', source: 'YouTube', items: [
        { rating: 5, quote: 'I am 52 and have brown skin and have never once seen a foundation video that was about my face. thank you for saying the flashback thing out loud.', author: 'renu_k', date: 'May 2026', source: 'other' },
        { rating: 5, quote: 'the six minute base is the only routine i have kept for longer than a fortnight in my adult life', author: 'tomasz.p', date: 'April 2026', source: 'other' },
        { rating: 4, quote: 'love the tutorials, please stop filming with the tap running though', author: 'aoife_makes', date: 'March 2026', source: 'other' },
      ] }),
      b('edit', 'newsletter', { title: 'The Sunday Edit', intro: 'One email a week: what I used, what I sent back, and what is worth the money. No affiliate codes buried in the body text.', placeholder: 'you@email.com', submitLabel: 'Send me the edit', successMessage: 'You are in — the first edit lands Sunday morning.' }),
      b('socials', 'social-links', { title: 'Elsewhere', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'instagram', href: '#', label: '@priyasolanki' },
        { platform: 'tiktok', href: '#', label: '@priyadoesfaces' },
        { platform: 'youtube', href: '#', label: 'Priya Solanki' },
        { platform: 'email', href: '#', label: 'Press & partnerships' },
      ] }),
      b('footer', 'footer', { brand: 'Priya Solanki', tagline: 'Everyday makeup, filmed in real light.', links: [{ label: 'Tutorials', href: '#tutorials' }, { label: 'The kit', href: '#kit' }, { label: 'Partnerships', href: '#partners' }], copyright: '© Priya Solanki. Affiliate links marked; nothing here is a paid review.' }),
    ],
  }),

  // ── fitness influencer with programmes ─────────────────────────────────────
  tpl({
    id: 'creator-fitness-programmes',
    vertical: 'creator',
    label: 'Fitness Creator — Programme Catalogue',
    description: 'A programme-first page for an online coach whose written training plans are the whole business.',
    tags: ['fitness', 'pricing', 'video', 'social', 'remote'],
    layout: 'catalogue',
    preset: 'midnight',
    meta: { title: 'Dani Okafor — Training Programmes', description: 'Eight- and twelve-week strength programmes you run yourself, plus small-group online coaching. Sydney-based, coaching worldwide.', lang: 'en', favicon: '🏋️' },
    blocks: [
      b('nav', 'nav', { brand: 'DANI OKAFOR', sticky: true, links: [{ label: 'Programmes', href: '#programmes' }, { label: 'Coaching', href: '#coaching' }, { label: 'Form library', href: '#library' }, { label: 'Results', href: '#results' }, { label: 'FAQ', href: '#faq' }], cta: { label: 'Find my programme', href: '#programmes' } }),
      b('hero', 'hero', { eyebrow: 'Sydney · coaching online since 2019', headline: 'Pick the plan. Run it for eight weeks. Send me the numbers.', subhead: 'No app subscription, no daily check-in guilt. You buy the programme once, you get the spreadsheet and the form videos, and you own it.', align: 'center', minHeight: 'md', image: img('creator-fitness-hero'), overlay: 'dark', cta: { label: 'See all programmes', href: '#programmes' } }),
      b('programmes', 'services-catalogue', { title: 'The programmes', subtitle: 'One-off purchase. Lifetime access, including every future revision.', items: [
        { name: 'Foundations — 8 weeks', description: 'Three days a week, full body. For anyone who has never followed a written programme, or is coming back after a long gap.', price: 'A$59', ctaLabel: 'Get Foundations', ctaHref: '#' },
        { name: 'Strong Twelve — 12 weeks', description: 'Four days, upper/lower split. Squat, bench, deadlift, overhead press, with the accessory work that keeps your shoulders happy.', price: 'A$89', ctaLabel: 'Get Strong Twelve', ctaHref: '#' },
        { name: 'Home & Hotel — 6 weeks', description: 'Dumbbells and a bench, nothing else. Written for people who travel for work and are sick of skipping.', price: 'A$45', ctaLabel: 'Get Home & Hotel', ctaHref: '#' },
        { name: 'Postnatal Return — 10 weeks', description: 'A slow rebuild through core and pelvic floor before any loaded work. Written with a pelvic-health physio; get clearance from your own clinician first.', price: 'A$69', ctaLabel: 'Get Postnatal Return', ctaHref: '#' },
        { name: 'Pull-Up Project — 8 weeks', description: 'One goal, one plan. Band-assisted to a strict rep, run alongside whatever else you are doing.', price: 'A$35', ctaLabel: 'Get the Pull-Up Project', ctaHref: '#' },
        { name: 'Deload & Diagnose', description: 'A one-week reset plus a written review of your last training block. For when the numbers stall and you cannot see why.', price: 'A$25', ctaLabel: 'Book a review', ctaHref: '#coaching' },
      ] }),
      b('coaching', 'pricing', { title: 'If you want me involved', subtitle: 'Small groups only. I cap it at forty people so the video feedback is actually written by me.', plans: [
        { name: 'Programme only', price: 'A$59+', period: 'one-off', features: ['Any programme above', 'Spreadsheet and form-video library', 'Lifetime revisions', 'Email support for setup'], ctaLabel: 'Browse programmes', ctaHref: '#programmes' },
        { name: 'Group coaching', price: 'A$119', period: '/mo', features: ['Programme tailored each block', 'Weekly video form review', 'Group call every second Sunday', 'Cancel any month'], ctaLabel: 'Join the group', ctaHref: '#', featured: true },
        { name: '1:1', price: 'A$310', period: '/mo', features: ['Everything in group coaching', 'Fortnightly 1:1 call', 'Direct messaging, replies within a day', 'Waitlisted — usually 4–6 weeks'], ctaLabel: 'Join the waitlist', ctaHref: '#' },
      ] }),
      b('numbers', 'stats', { title: 'Where things stand', columns: 4, items: [
        { value: '6,400', label: 'Programmes sold', suffix: '+' },
        { value: '40', label: 'Coaching spots, capped' },
        { value: '7', label: 'Years coaching online' },
        { value: '92', label: 'Finish their first block', suffix: '%' },
      ] }),
      b('library', 'video-gallery', { title: 'Form library — free, no signup', layout: 'carousel', columns: 3, items: [
        { provider: 'youtube', src: 'nT8kQ2vLx5R', title: 'Low-bar squat: bar position and the shoulder complaint' },
        { provider: 'youtube', src: 'pW4hR9bZm3D', title: 'Conventional deadlift setup in four cues' },
        { provider: 'youtube', src: 'eL6yG1nCq7T', title: 'Bench: how to actually find your arch, and why it is not cheating' },
        { provider: 'youtube', src: 'uK3sP7dFv0J', title: 'Band-assisted pull-up progressions, easiest to hardest' },
        { provider: 'youtube', src: 'iN9tB5wHx2Q', title: 'Dumbbell-only leg day in a hotel room' },
      ] }),
      b('results', 'testimonials', { title: 'From people who finished a block', items: [
        { quote: 'I have bought four training apps and quit all of them by week three. A spreadsheet and a video per lift is somehow the thing that stuck. Deadlift went 70kg to 112.5kg over two blocks.', author: 'Freya M.', role: 'Strong Twelve, twice' },
        { quote: 'The postnatal plan was the first thing that neither babied me nor threw me straight back into burpees. My physio read it and said keep going.', author: 'Ruth A.', role: 'Postnatal Return' },
        { quote: 'I travel three weeks a month. Home & Hotel is the only reason I still train at all.', author: 'Sam O.', role: 'Home & Hotel' },
      ] }),
      b('faq', 'faq', { title: 'Before you buy', items: [
        { question: 'Do I need a gym?', answer: 'For Foundations and Strong Twelve, yes — a barbell, a rack and a bench. Home & Hotel and the Pull-Up Project need a pair of adjustable dumbbells and a bar or band.' },
        { question: 'Is there an app?', answer: 'No. You get a spreadsheet you copy to your own drive, a PDF, and a private video library. It works offline, it works forever, and there is nothing to cancel.' },
        { question: 'What if it is too hard, or too easy?', answer: 'Every session has a scale-down and a scale-up column. If you are still in the wrong place after two weeks, email me the numbers and I will rewrite the block for you at no charge.' },
        { question: 'Refunds?', answer: 'Fourteen days, no questions, even if you have downloaded everything. Roughly one in a hundred people asks, which seems about right.' },
        { question: 'Do you do nutrition?', answer: 'No. I am not a dietitian and I will not sell you a meal plan. If you want one I will point you at two people I trust.' },
      ] }),
      b('list', 'newsletter', { title: 'Training notes, fortnightly', intro: 'One programming idea, one thing I got wrong, and whatever the group is arguing about. Sent every second Wednesday.', placeholder: 'you@email.com', submitLabel: 'Subscribe', successMessage: 'Done — the next one goes out Wednesday.' }),
      b('socials', 'social-links', { title: 'Find me', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'instagram', href: '#', label: '@danilifts' },
        { platform: 'youtube', href: '#', label: 'Dani Okafor' },
        { platform: 'tiktok', href: '#', label: '@danilifts' },
        { platform: 'email', href: '#', label: 'dani@daniokafor.com.au' },
      ] }),
      b('footer', 'footer', { brand: 'Dani Okafor Training', tagline: 'Written programmes, run by you.', links: [{ label: 'Programmes', href: '#programmes' }, { label: 'Coaching', href: '#coaching' }, { label: 'FAQ', href: '#faq' }], copyright: '© Dani Okafor Training, Sydney NSW. General fitness information, not medical advice.' }),
    ],
  }),

  // ── travel creator ─────────────────────────────────────────────────────────
  tpl({
    id: 'creator-travel',
    vertical: 'creator',
    label: 'Travel Creator — Editorial',
    description: 'A long-form travel writer and photographer whose dispatches and paid letter carry the audience.',
    tags: ['travel', 'long-form', 'newsletter', 'gallery', 'social'],
    layout: 'editorial',
    preset: 'ocean',
    meta: { title: 'Slow Latitudes — Marco Ferreira', description: 'Overland travel writing and photography from a Lisbon base. Long dispatches, few flights, no listicles.', lang: 'en', favicon: '🧭' },
    blocks: [
      b('nav', 'nav', { brand: 'Slow Latitudes', sticky: false, links: [{ label: 'Dispatches', href: '#dispatches' }, { label: 'Photographs', href: '#photographs' }, { label: 'The route', href: '#route' }, { label: 'Commissions', href: '#partners' }], cta: { label: 'Subscribe', href: '#letter' } }),
      b('hero', 'hero', { eyebrow: 'Dispatch 84 · Trabzon to Tbilisi, by bus', headline: 'Nine countries, no flights, and a laundry problem.', subhead: 'I have been travelling overland since 2021 and writing about it about half as fast as I move. Long pieces, real prices, and the parts that did not work.', align: 'left', minHeight: 'md', image: img('creator-travel-hero'), overlay: 'scrim', cta: { label: 'Start with dispatch 84', href: '#dispatches' } }),
      b('about', 'about', { eyebrow: 'Who is writing', title: 'A shipping analyst who got off at the wrong stop', body: 'I spent eleven years pricing container routes out of Lisbon, which is a very unromantic way to learn how the world is actually stitched together. In 2021 I took six months off to follow one of those routes at ground level and never went back to the desk. Since then it has been ferries, night buses and one memorable freight train, funded by the letter, a photography licence or two, and occasional work for tourism boards that agree in writing that I keep final say on the text. I travel slowly because it is cheaper, and because a place stops performing for you around day nine.', image: img('creator-travel-about'), imageAlt: 'A writer at a ferry terminal cafe with a notebook', imageSide: 'right' }),
      b('essay', 'rich-text', { blocks: [
        { kind: 'heading', text: 'How the money works, since nobody ever says' },
        { kind: 'paragraph', text: 'Roughly sixty per cent of what I earn comes from paid subscribers to the letter, about a quarter from licensing photographs to magazines and one very persistent hotel group, and the rest from commissioned pieces. I have turned down four sponsored trips this year, mostly because the brief included the phrase "hidden gem".' },
        { kind: 'quote', text: 'A place stops performing for you around day nine. That is when the writing starts.' },
        { kind: 'subheading', text: 'What a dispatch costs to make' },
        { kind: 'bullet', text: 'Two to three weeks in one place, at €35–€60 a night in a room with a desk.' },
        { kind: 'bullet', text: 'Ground transport only — trains and buses, ferries where the map insists.' },
        { kind: 'bullet', text: 'A fixer or translator on about a third of them, paid at local professional rates and credited by name.' },
        { kind: 'numbered', text: 'Reporting, usually eight to twelve days.' },
        { kind: 'numbered', text: 'A first draft written badly and fast, on the next bus.' },
        { kind: 'numbered', text: 'Two weeks of rewriting somewhere with reliable wifi, then it goes out.' },
      ] }),
      b('photographs', 'carousel', { title: 'Photographs', autoplay: false, items: [
        { src: img('creator-travel-photo-ferry'), alt: 'Passengers asleep on the deck of an overnight ferry', caption: 'Overnight ferry, Bari to Durrës — deck class, €29' },
        { src: img('creator-travel-photo-market'), alt: 'A covered market at dawn with crates of citrus', caption: 'Dawn at the Trabzon market, before the tea arrives' },
        { src: img('creator-travel-photo-pass'), alt: 'A mountain road switchbacking above a treeline', caption: 'The road over the pass into Svaneti, closed six months a year' },
        { src: img('creator-travel-photo-train'), alt: 'An empty night-train corridor lit by a single lamp', caption: 'Night train out of Belgrade — the last carriage, as always' },
        { src: img('creator-travel-photo-laundry'), alt: 'Laundry strung between two balconies over a narrow street', caption: 'Alfama, Lisbon. Home for eight weeks a year' },
      ] }),
      b('dispatches', 'blog-list', { title: 'Recent dispatches', columns: 2, posts: [
        { title: 'Trabzon to Tbilisi, by bus, in the wrong month', excerpt: 'Four buses, one closed border crossing, and the mathematics of a mountain pass that shuts without announcing it. Costs at the bottom, as always.', href: '#', image: img('creator-travel-post-tbilisi'), date: '2 June 2026', tag: 'Dispatch 84' },
        { title: 'The last freight ferry out of Bari', excerpt: 'Deck class on a working ship is the cheapest bed in the Adriatic and the worst night of sleep in Europe. I have now done it eleven times.', href: '#', image: img('creator-travel-post-bari'), date: '8 May 2026', tag: 'Dispatch 83' },
        { title: 'What a fixer actually does', excerpt: 'On the invisible labour behind travel writing, why so few pieces name it, and what I now pay per day in six countries.', href: '#', image: img('creator-travel-post-fixer'), date: '19 April 2026', tag: 'Craft' },
        { title: 'Eight weeks in Alfama without writing a word about Alfama', excerpt: 'A note on going home, the tourist-flat problem, and why the place you live is the hardest place to see.', href: '#', image: img('creator-travel-post-alfama'), date: '30 March 2026', tag: 'Dispatch 82' },
      ] }),
      b('route', 'timeline', { title: 'The route so far', items: [
        { date: '2021', title: 'Lisbon to Istanbul', text: 'Six months that were meant to be six months. Trains as far as Sofia, then buses. The letter started here, with forty readers, all of them relatives.' },
        { date: '2022', title: 'Anatolia and the Black Sea coast', text: 'A year mostly in one country. Learned enough Turkish to be rude by accident and to order breakfast correctly.' },
        { date: '2023–24', title: 'The Caucasus', text: 'Georgia, Armenia, and four attempts at a land border that was open on the map and shut in life. First paid commissions.' },
        { date: '2025', title: 'Central Asia by rail', text: 'Aktau to Almaty, largely horizontal. The photographs from this stretch pay the rent on the Lisbon flat.' },
        { date: '2026', title: 'Back west, slowly', text: 'Currently working north through the Balkans. Dispatch 85 will be from a town of nine hundred people with two competing bakeries.' },
      ] }),
      b('partners', 'logos', { title: 'Commissions and licensing', items: [
        { src: img('creator-travel-client-meridian'), alt: 'Meridian Quarterly', href: '#' },
        { src: img('creator-travel-client-passage'), alt: 'Passage Magazine', href: '#' },
        { src: img('creator-travel-client-atlas'), alt: 'Atlas Rail Europe', href: '#' },
        { src: img('creator-travel-client-caravela'), alt: 'Caravela Hotels', href: '#' },
        { src: img('creator-travel-client-ganso'), alt: 'Ganso Outdoor', href: '#' },
      ] }),
      b('letter', 'newsletter', { title: 'The letter', intro: 'A dispatch every three or four weeks, whenever one is finished. Free readers get the whole piece; paid readers get the costs breakdown, the outtakes and the route notes, for €6 a month.', placeholder: 'you@email.com', submitLabel: 'Subscribe free', successMessage: 'Welcome aboard — the next dispatch is half-written on a bus.' }),
      b('socials', 'social-links', { title: 'Elsewhere', layout: 'row', variant: 'icon', align: 'start', links: [
        { platform: 'instagram', href: '#', label: '@slowlatitudes' },
        { platform: 'mastodon', href: '#', label: 'Mastodon' },
        { platform: 'rss', href: '#', label: 'RSS' },
        { platform: 'email', href: '#', label: 'marco@slowlatitudes.com' },
      ] }),
      b('footer', 'footer', { brand: 'Slow Latitudes', tagline: 'Overland travel writing from a Lisbon base.', links: [{ label: 'Dispatches', href: '#dispatches' }, { label: 'Licensing', href: '#partners' }, { label: 'The letter', href: '#letter' }], copyright: '© Marco Ferreira, Lisbon. Photographs licensed individually.' }),
    ],
  }),

  // ── food creator / recipe reels ────────────────────────────────────────────
  tpl({
    id: 'creator-food-reels',
    vertical: 'creator',
    label: 'Food Creator — Reel Feed',
    description: 'A feed-shaped page for a short-form recipe creator, with the week of reels sitting above everything else.',
    tags: ['food', 'recipes', 'video', 'social', 'mobile-first'],
    layout: 'conversational',
    preset: 'sand',
    meta: { title: 'Bite Sized — Ayesha Rahman', description: 'Sixty-second recipes that work in a real kitchen. Toronto. The written recipe is always free and always below the video.', lang: 'en', favicon: '🍳' },
    blocks: [
      b('nav', 'nav', { brand: 'Bite Sized', sticky: true, links: [{ label: 'This week', href: '#week' }, { label: 'Watch', href: '#watch' }, { label: 'Recipe index', href: '#index' }, { label: 'Ask me', href: '#asks' }], cta: { label: 'Get Sunday Prep', href: '#prep' } }),
      b('who', 'profile-header', { name: 'Ayesha Rahman', headline: 'Sixty-second recipes that survive a real kitchen', location: 'Toronto, ON', avatar: img('creator-food-avatar'), summary: 'Line cook for six years, recipe developer for four, and now the person your phone shows you at 11pm. Everything I post is cooked on a domestic four-burner with one decent pan, and the written recipe is always underneath the video for free — nobody should have to scrub a reel to find out how much salt.', contacts: [
        { type: 'email', value: 'hello@bitesized.kitchen', label: 'Recipes and press' },
        { type: 'location', value: 'Toronto, Canada' },
        { type: 'website', value: 'bitesized.kitchen' },
      ], showShare: true, shareLabel: 'Share this page' }),
      b('week', 'feed', { title: 'This week', layout: 'cards', items: [
        { title: 'Nine-minute chilli crisp noodles', subtitle: 'Monday · 1.2M views', text: 'The one everyone asks about. Dried noodles, chilli crisp, a splash of the cooking water, and a scrambled egg folded through at the end.', badge: 'Reel', image: img('creator-food-reel-noodles'), href: '#' },
        { title: 'Sheet-pan chicken with the potatoes underneath', subtitle: 'Tuesday · 640k views', text: 'The potatoes go in first for twenty minutes on their own. That is the entire trick and it took me a year to work out.', badge: 'Reel', image: img('creator-food-reel-sheetpan'), href: '#' },
        { title: 'Dal for people who think they do not like dal', subtitle: 'Thursday · 980k views', text: 'Masoor, not chana. Fifteen minutes. The tarka goes on at the table so people can hear it.', badge: 'Reel', image: img('creator-food-reel-dal'), href: '#' },
        { title: 'Testing five supermarket puff pastries', subtitle: 'Friday · 410k views', text: 'All-butter won, obviously, but the cheapest one came second and that is the useful bit.', badge: 'Test', image: img('creator-food-reel-pastry'), href: '#' },
        { title: 'Reader fix: why your rice keeps catching', subtitle: 'Saturday · 220k views', text: 'Ninety per cent of the time it is the pan, not the heat. Sent in by Marisol in Winnipeg.', badge: 'Reply', image: img('creator-food-reel-rice'), href: '#' },
      ] }),
      b('watch', 'video-gallery', { title: 'Longer cooks', layout: 'grid', columns: 2, items: [
        { provider: 'youtube', src: 'gJ7fQ2xNv4B', title: 'Sunday prep in 90 minutes: five components, twelve dinners', poster: img('creator-food-vid-prep') },
        { provider: 'youtube', src: 'hD5mZ8cTr1W', title: 'Biryani properly, the way my nani actually does it' },
        { provider: 'youtube', src: 'qS3vK6bJl9E', title: 'Knife skills for people cooking on a 40cm counter' },
        { provider: 'youtube', src: 'rF8nX1yPd2C', title: 'A month of dinners on C$70 a week, receipts shown' },
      ] }),
      b('index', 'menu', { title: 'Recipe index', subtitle: 'Every written recipe, free, no login. Tags: V vegetarian, VG vegan, GF gluten-free.', sections: [
        { name: 'Under 15 minutes', note: 'Weeknight, one pan, nothing to defrost.', items: [
          { name: 'Chilli crisp noodles', description: 'Egg folded through, spring onion on top.', tags: ['V'], spice: 2 },
          { name: 'Masoor dal with a table tarka', description: 'Red lentils, cumin, dried chilli, ghee or oil.', tags: ['V', 'VG', 'GF'], spice: 1 },
          { name: 'Tuna and white bean smash', description: 'Lemon, olive oil, far too much black pepper.', tags: ['GF'] },
        ] },
        { name: 'Weekend cooking', note: 'Longer, but mostly the oven doing the work.', items: [
          { name: 'Chicken biryani', description: 'Layered, sealed, rested twenty minutes off the heat.', spice: 2 },
          { name: 'Sheet-pan chicken and potatoes', description: 'Potatoes twenty minutes ahead. Do not skip that.', tags: ['GF'] },
          { name: 'Slow-roast tomato sauce', description: 'Three hours at 140°C. Freezes in portions.', tags: ['V', 'VG', 'GF'] },
        ] },
        { name: 'Baking', note: 'Weights only. Cups are a conspiracy.', items: [
          { name: 'One-bowl olive oil cake', description: 'Orange zest, no mixer, keeps four days.', tags: ['V'] },
          { name: 'Rough puff, honestly assessed', description: 'Worth doing once. Buy the all-butter block the rest of the time.', tags: ['V'] },
        ] },
      ] }),
      b('asks', 'chat-thread', { title: 'Ask me', subtitle: 'The DM questions that come in most often, answered once here so I can stop typing them out at midnight.', participants: [
        { id: 'reader', name: 'Readers', role: 'user' },
        { id: 'ayesha', name: 'Ayesha', role: 'agent', avatar: img('creator-food-chat-avatar') },
      ], messages: [
        { from: 'reader', time: 'Mon 23:14', body: [{ kind: 'text', text: 'Can I use the chilli crisp noodles recipe without the egg? Cooking for someone who does not eat eggs.' }] },
        { from: 'ayesha', time: 'Tue 08:02', body: [
          { kind: 'text', text: 'Yes. Skip it and add half a block of firm tofu, torn not cubed, fried hard in the same pan first. You want something that holds the sauce the way the egg does.' },
        ] },
        { from: 'reader', time: 'Wed 19:40', body: [{ kind: 'text', text: 'Why is the written recipe free when everyone else gates it? Genuine question, not a dig.' }] },
        { from: 'ayesha', time: 'Wed 20:11', body: [
          { kind: 'text', text: 'Because I lost an argument with myself about it in 2023. The video earns from views and brand work; the recipe is the part someone needs at 6pm with a hot pan. Gating that felt like charging for the salt.' },
          { kind: 'list', ordered: true, items: [
            { label: 'Recipes: free, forever, no login', href: '#index' },
            { label: 'Sunday Prep shopping list: free', href: '#prep' },
            { label: 'Brand work: disclosed in the first five seconds of the video' },
          ] },
        ] },
        { from: 'reader', time: 'Fri 12:05', body: [{ kind: 'text', text: 'My rice keeps catching even on low. Pan is a thin steel one from a starter set.' }] },
        { from: 'ayesha', time: 'Fri 12:29', body: [
          { kind: 'text', text: 'That is the pan, not you. Thin steel has hot spots the size of a coin. Either move to absorption in a heavy lidded pot, or boil it like pasta and drain — the second one is unfashionable and it works.' },
          { kind: 'image', src: img('creator-food-chat-rice'), alt: 'A heavy lidded pot of rice resting off the heat with the lid on' },
        ] },
      ] }),
      b('prep', 'newsletter', { title: 'Sunday Prep', intro: 'One email on Saturday morning: the week’s five recipes as a single shopping list, sized for one, two or four. Free.', placeholder: 'you@email.com', submitLabel: 'Send me the list', successMessage: 'Nice — Saturday’s list is on its way.' }),
      b('socials', 'social-links', { title: 'Where the reels live', layout: 'grid', variant: 'labeled', align: 'center', links: [
        { platform: 'tiktok', href: '#', label: '@bitesized' },
        { platform: 'instagram', href: '#', label: '@bitesized.kitchen' },
        { platform: 'youtube', href: '#', label: 'Bite Sized' },
        { platform: 'whatsapp', href: '#', label: 'Recipe broadcast' },
        { platform: 'email', href: '#', label: 'hello@bitesized.kitchen' },
      ] }),
      b('footer', 'footer', { brand: 'Bite Sized', tagline: 'The written recipe is always free, always underneath.', links: [{ label: 'Recipe index', href: '#index' }, { label: 'Sunday Prep', href: '#prep' }, { label: 'Ask me', href: '#asks' }], copyright: '© Ayesha Rahman, Toronto. Paid partnerships are disclosed in the video, not the caption.' }),
    ],
  }),

  // ── game streamer ──────────────────────────────────────────────────────────
  tpl({
    id: 'creator-streamer',
    vertical: 'creator',
    label: 'Game Streamer — App Shell',
    description: 'An app-shaped hub for a live streamer: tab bar, schedule, clips and sub tiers, installable to a phone.',
    tags: ['streaming', 'gaming', 'video', 'social', 'dark'],
    layout: 'app',
    preset: 'mono',
    meta: { title: 'KESTREL — live', description: 'Slow games, long runs, nobody shouting. Live four nights a week from Berlin. Schedule, clips and Discord.', lang: 'en', favicon: '🎮' },
    blocks: [
      b('shell', 'app-shell', { brand: 'KESTREL', tabs: [
        { label: 'Live', href: '#live', icon: '🔴' },
        { label: 'Schedule', href: '#schedule', icon: '🗓' },
        { label: 'Clips', href: '#clips', icon: '✂️' },
        { label: 'Perks', href: '#tiers', icon: '⭐' },
      ] }),
      b('top', 'hero-app', { headline: 'Slow games. Long runs. Nobody shouting.', subhead: 'Live Tuesday to Friday, 20:00 CET, from a flat in Neukölln. Mostly strategy and survival-craft, occasionally a nine-hour attempt at something I am bad at.', installLabel: 'Add to home screen', installHref: '#install', screenshots: [
        { src: img('creator-stream-shot-overlay'), alt: 'Stream overlay showing a base-building game beside a chat column' },
        { src: img('creator-stream-shot-schedule'), alt: 'The weekly schedule view on a phone' },
        { src: img('creator-stream-shot-clips'), alt: 'A grid of clip thumbnails' },
        { src: img('creator-stream-shot-discord'), alt: 'The community Discord channel list' },
      ] }),
      b('install', 'install-prompt', { title: 'Keep the schedule on your phone', body: 'Add this page to your home screen and the schedule works offline, in your own timezone.', actionLabel: 'Show me how', position: 'bottom', tone: 'info', delayMs: 6000, dismissible: true, rememberDismiss: true, platforms: ['ios-safari', 'android', 'desktop-chrome'] }),
      b('live', 'video', { provider: 'youtube', src: 'vQ6dR3nHt7K', title: 'Latest full VOD — the nine-hour island run', poster: img('creator-stream-vod-poster'), caption: 'When the stream is offline this slot shows the most recent full VOD, uncut, chat included.' }),
      b('schedule', 'feed', { title: 'This week', layout: 'list', items: [
        { title: 'Tuesday — factory game, week 6', subtitle: '20:00–23:00 CET', text: 'Still trying to fix the train network I built while sleep-deprived in week three.', badge: 'Weekly' },
        { title: 'Wednesday — community night', subtitle: '20:00–00:00 CET', text: 'Open lobby. Server details go in Discord an hour before. Bring nothing, know nothing, it is fine.', badge: 'Open' },
        { title: 'Thursday — blind first playthrough', subtitle: '20:00–23:00 CET', text: 'No wikis, no backseating. Spoiler timeouts are instant and I will not feel bad about it.', badge: 'Blind' },
        { title: 'Friday — long run', subtitle: '19:00 CET until it is done', text: 'One attempt, one sitting. Last month this ran to 02:40 and I regret nothing.', badge: 'Marathon' },
        { title: 'Saturday 14 June — charity stream', subtitle: '12:00–20:00 CET', text: 'Eight hours for the Berlin food bank network. Last year the channel raised €11,400.', badge: 'Special' },
      ] }),
      b('clips', 'video-gallery', { title: 'Clips people keep sending back', layout: 'grid', columns: 3, items: [
        { provider: 'youtube', src: 'aW2eT9kMz5X', title: 'The train network incident (46 seconds, no words)' },
        { provider: 'youtube', src: 'bY7uI4pLd8N', title: 'Hour eight of the island run, immediately before the flood' },
        { provider: 'youtube', src: 'cU1oP6rSv3M', title: 'Chat solves a puzzle I had been stuck on for two streams' },
        { provider: 'youtube', src: 'dI9aS2fGh6V', title: 'A very calm reaction to losing forty hours of progress' },
        { provider: 'youtube', src: 'eO4jK8lZc0B', title: 'Charity stream 2025: the final total' },
        { provider: 'youtube', src: 'fP5qN3xWb7T', title: 'Explaining supply chains to a viewer who is nine' },
      ] }),
      b('numbers', 'stats', { title: 'The channel', columns: 4, items: [
        { value: '48k', label: 'Followers' },
        { value: '1,900', label: 'Average concurrent' },
        { value: '11,400', label: 'Raised for charity in 2025', prefix: '€' },
        { value: '4', label: 'Nights a week since 2020' },
      ] }),
      b('tiers', 'pricing', { title: 'Subs and perks', subtitle: 'None of this is required. The stream is free and always will be.', plans: [
        { name: 'Free', price: '€0', period: 'forever', features: ['Every stream, live and VOD', 'Read-only Discord', 'Schedule in your timezone'], ctaLabel: 'Just watch', ctaHref: '#live' },
        { name: 'Tier 1', price: '€4', period: '/mo', features: ['Emotes and chat colour', 'Full Discord access', 'Community-night priority', 'Subscriber-only Sunday chat'], ctaLabel: 'Subscribe', ctaHref: '#', featured: true },
        { name: 'Tier 2', price: '€9', period: '/mo', features: ['Everything in Tier 1', 'Monthly co-op session, eight seats', 'Name in the end card', 'Early VODs, ad-free'], ctaLabel: 'Subscribe', ctaHref: '#' },
      ] }),
      b('socials', 'social-links', { title: 'Channels', layout: 'grid', variant: 'labeled', align: 'center', links: [
        { platform: 'youtube', href: '#', label: 'VODs and clips' },
        { platform: 'discord', href: '#', label: 'Kestrel Discord' },
        { platform: 'x', href: '#', label: '@kestrelplays' },
        { platform: 'telegram', href: '#', label: 'Go-live alerts' },
        { platform: 'email', href: '#', label: 'business@kestrel.tv' },
      ] }),
      b('footer', 'footer', { brand: 'KESTREL', tagline: 'Live Tue–Fri, 20:00 CET, Berlin.', links: [{ label: 'Schedule', href: '#schedule' }, { label: 'Clips', href: '#clips' }, { label: 'Perks', href: '#tiers' }], copyright: '© Kestrel. Sponsorship enquiries by email only — no DMs.' }),
    ],
  }),

  // ── podcaster ──────────────────────────────────────────────────────────────
  tpl({
    id: 'creator-podcast',
    vertical: 'creator',
    label: 'Podcast — Classic',
    description: 'An interview podcast with an episode feed, a sponsor strip and a guest-pitch form.',
    tags: ['podcast', 'audio', 'newsletter', 'social', 'long-form'],
    layout: 'classic',
    preset: 'forest',
    meta: { title: 'Second Draft — a podcast about how things get made', description: 'Long interviews with people who make things, about the version that did not work. New episodes every other Tuesday, from Dublin.', lang: 'en', favicon: '🎙️' },
    blocks: [
      b('nav', 'nav', { brand: 'Second Draft', sticky: true, links: [{ label: 'Episodes', href: '#episodes' }, { label: 'About', href: '#about' }, { label: 'On video', href: '#video' }, { label: 'Pitch a guest', href: '#pitch' }], cta: { label: 'Listen now', href: '#episodes' } }),
      b('hero', 'hero', { eyebrow: 'Episode 112 · every other Tuesday · Dublin', headline: 'The interview about the version that did not work.', subhead: 'Ninety minutes with architects, showrunners, brewers, bridge engineers and one competitive whistler — always about the draft they threw away, never about the launch.', align: 'center', minHeight: 'md', image: img('creator-podcast-hero'), overlay: 'dark', cta: { label: 'Start with episode 112', href: '#episodes' } }),
      b('about', 'about', { eyebrow: 'The premise', title: 'Nobody tells you about the second draft', body: 'Every craft interview you have ever heard follows the same arc: the idea, the struggle, the triumph, the plug. This show cuts the first and the last. Guests bring one thing they made that failed, or nearly did, and we spend an hour and a half on it — the meeting where it went wrong, the thing they defended for too long, what it cost. It is recorded in one take with no pre-interview, which means the awkward pauses stay in. Since 2021 we have made 112 of these, and the most-downloaded one is still a structural engineer describing a footbridge that was fine and felt wrong.', image: img('creator-podcast-about'), imageAlt: 'Two microphones on a table in a small carpeted studio', imageSide: 'left' }),
      b('episodes', 'feed', { title: 'Recent episodes', layout: 'list', items: [
        { title: '112 — The footbridge that was fine and felt wrong', subtitle: 'Priya Nandakumar, structural engineer · 1h 38m', text: 'On the difference between a structure passing every calculation and a structure people trust with their feet, and the eighteen months spent proving it.', badge: 'New', href: '#' },
        { title: '111 — Cutting the film we spent a year on', subtitle: 'Colm Beirne, documentary editor · 1h 21m', text: 'It had a subject, a grant and 190 hours of footage. It did not have a spine. What happened next.', href: '#' },
        { title: '110 — A brewery that scaled too fast on purpose', subtitle: 'Nadia Haddad, brewer · 1h 44m', text: 'Doubling capacity before the demand existed. Why they would do it again, and the two years in between.', href: '#' },
        { title: '109 — The show that got a season two nobody wanted', subtitle: 'Anonymous showrunner · 1h 09m', text: 'A rare anonymous episode, with the employer named only in the parts they cleared.', badge: 'Anon', href: '#' },
        { title: '108 — Rebuilding a typeface from a photograph', subtitle: 'Wesley Okonkwo, type designer · 1h 33m', text: 'Four years, one blurry 1954 shopfront, and the argument about how much invention is allowed.', href: '#' },
      ] }),
      b('sponsors', 'logos', { title: 'Supported this season by', items: [
        { src: img('creator-podcast-sponsor-quarry'), alt: 'Quarry Notebooks', href: '#' },
        { src: img('creator-podcast-sponsor-inkwell'), alt: 'Inkwell Type Foundry', href: '#' },
        { src: img('creator-podcast-sponsor-fieldhouse'), alt: 'Fieldhouse Audio', href: '#' },
        { src: img('creator-podcast-sponsor-tidemark'), alt: 'Tidemark Coffee', href: '#' },
      ] }),
      b('video', 'video-gallery', { title: 'Episodes on video', layout: 'grid', columns: 2, items: [
        { provider: 'youtube', src: 'gT4mV8sQx2Y', title: '112 — Priya Nandakumar on the footbridge', poster: img('creator-podcast-vid-bridge') },
        { provider: 'youtube', src: 'hR9bN5wJc7Z', title: '110 — Nadia Haddad on scaling a brewery too fast' },
        { provider: 'youtube', src: 'jK2xL7dPm4A', title: '108 — Wesley Okonkwo rebuilds a lost typeface' },
        { provider: 'youtube', src: 'kM6yC1fRt9U', title: 'Live at the Project Arts Centre — three guests, one draft each' },
      ] }),
      b('listeners', 'testimonials', { title: 'What listeners say', items: [
        { quote: 'It is the only interview show where the host will sit in a fifteen-second silence and let the guest finish thinking. I have started doing that in meetings.', author: 'Iona F.', role: 'Listener since ep. 12' },
        { quote: 'I run a two-person studio and episode 110 talked me out of a decision that would have ended us. That is a strange thing to say about a podcast.', author: 'Dermot A.', role: 'Studio owner, Cork' },
        { quote: 'Ninety minutes is too long and I listen to every one of them.', author: 'Sasha V.', role: 'Listener' },
      ] }),
      b('pitch', 'contact-form', { title: 'Pitch a guest', intro: 'Including yourself. The only rule is that there is a specific thing that did not work and you are willing to talk about it in detail. Publicists welcome; press releases ignored.', submitLabel: 'Send the pitch', successMessage: 'Got it. Every pitch gets read, and answered within a fortnight either way.', fields: [
        { name: 'name', label: 'Your name', type: 'text', required: true, placeholder: 'First and last' },
        { name: 'email', label: 'Email', type: 'email', required: true, placeholder: 'you@email.com' },
        { name: 'guest', label: 'Who is the guest', type: 'text', required: true, placeholder: 'Name and what they make' },
        { name: 'relationship', label: 'Your relationship to them', type: 'select', options: ['It is me', 'I represent them', 'I work with them', 'I am a listener with an idea'] },
        { name: 'draft', label: 'What is the second draft?', type: 'textarea', required: true, placeholder: 'The thing that did not work, in a paragraph.' },
        { name: 'travel', label: 'They can record in person in Dublin', type: 'checkbox' },
      ] }),
      b('list', 'newsletter', { title: 'Show notes by email', intro: 'Every other Tuesday: the episode, the transcript link, and the two things the guest said off-mic that they were happy for us to print.', placeholder: 'you@email.com', submitLabel: 'Get show notes', successMessage: 'Subscribed — the next notes go out with episode 113.' }),
      b('socials', 'social-links', { title: 'Follow the show', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'rss', href: '#', label: 'RSS feed' },
        { platform: 'youtube', href: '#', label: 'Full episodes on video' },
        { platform: 'mastodon', href: '#', label: '@seconddraft' },
        { platform: 'linkedin', href: '#', label: 'Second Draft' },
        { platform: 'email', href: '#', label: 'post@seconddraft.fm' },
      ] }),
      b('footer', 'footer', { brand: 'Second Draft', tagline: 'A podcast about the version that did not work.', links: [{ label: 'Episodes', href: '#episodes' }, { label: 'Sponsor the show', href: '#sponsors' }, { label: 'Pitch a guest', href: '#pitch' }], copyright: '© Second Draft Media, Dublin. Transcripts for every episode, always.' }),
    ],
  }),

  // ── YouTuber / long-form video creator ─────────────────────────────────────
  tpl({
    id: 'creator-youtube',
    vertical: 'creator',
    label: 'YouTuber — Bold',
    description: 'A high-contrast page for a long-form documentary channel selling scale, sponsors and the back catalogue.',
    tags: ['video', 'youtube', 'documentary', 'social', 'dark'],
    layout: 'bold',
    preset: 'midnight',
    meta: { title: 'HARLAN REEVE', description: 'Hour-long documentary films about infrastructure, money and the things that hold cities up. Four films a year, on YouTube, free.', lang: 'en', favicon: '🎬' },
    blocks: [
      b('nav', 'nav', { brand: 'HARLAN REEVE', sticky: true, links: [{ label: 'Films', href: '#films' }, { label: 'How they get made', href: '#process' }, { label: 'The money', href: '#money' }, { label: 'Sponsorship', href: '#sponsors' }], cta: { label: 'Watch the latest', href: '#films' } }),
      b('hero', 'hero', { eyebrow: 'Four films a year · Chicago', headline: 'One hour. One subject. Eleven months of reporting.', subhead: 'Documentary films about infrastructure, money, and the systems nobody notices until they stop. Free on YouTube, no mid-rolls, no second channel.', align: 'center', minHeight: 'full', image: img('creator-youtube-hero'), overlay: 'dark', cta: { label: 'Watch “The Grid Holds”', href: '#films' } }),
      b('numbers', 'stats', { title: 'The channel, plainly', columns: 4, items: [
        { value: '3.1M', label: 'Subscribers' },
        { value: '19', label: 'Films since 2018' },
        { value: '11', label: 'Months, average per film' },
        { value: '6', label: 'People on the team' },
      ] }),
      b('films', 'video-gallery', { title: 'The films', layout: 'grid', columns: 2, items: [
        { provider: 'youtube', src: 'nB3kW7tQz1F', title: 'The Grid Holds — a year inside the people who keep the lights on', poster: img('creator-youtube-film-grid') },
        { provider: 'youtube', src: 'pC8dL2mYs5H', title: 'Six Inches of Concrete — how a bridge inspection actually works', poster: img('creator-youtube-film-bridge') },
        { provider: 'youtube', src: 'qE1fN9rVb6J', title: 'The Last Mile — what happens to a parcel after you stop watching' },
        { provider: 'youtube', src: 'rG5hP4xZc8K', title: 'Water Rights — one river, four states, sixty years of arithmetic' },
        { provider: 'youtube', src: 'sJ7jT6yWd0L', title: 'Nobody Owns the Sidewalk — the strange law under your feet' },
        { provider: 'youtube', src: 'tK9lU3zXe2M', title: 'Signal Failure — a rail network running on 1970s hardware' },
      ] }),
      b('process', 'split', { rows: [
        { title: 'Eleven months, and most of it is not filming', text: 'A film starts as a question I cannot answer in an afternoon. Then four to six months of reading, records requests and phone calls that go nowhere, before a camera comes out of the bag. If the question turns out to have a boring answer the project dies — three have, and that is a feature.', image: img('creator-youtube-process-research'), imageAlt: 'A desk covered in printed public records and a laptop' },
        { title: 'We shoot with four people and no permission we did not earn', text: 'Every location in the last six films was arranged directly with the people who work there, not through a communications team. It takes longer. It is the reason the interviews sound like people rather than statements.', image: img('creator-youtube-process-shoot'), imageAlt: 'A small crew filming inside a substation control room' },
        { title: 'The edit is where films die', text: 'First assemblies run three hours. Everything that survives to the final hour has to answer the original question or it goes, however expensive it was to get. There is a folder called “beautiful and irrelevant” and it is the largest folder on the drive.', image: img('creator-youtube-process-edit'), imageAlt: 'An editing timeline across two monitors in a dark room' },
      ] }),
      b('sponsors', 'logos', { title: 'Films funded by', items: [
        { src: img('creator-youtube-sponsor-lantern'), alt: 'Lantern Foundation', href: '#' },
        { src: img('creator-youtube-sponsor-crosscut'), alt: 'Crosscut Drives', href: '#' },
        { src: img('creator-youtube-sponsor-meridianfilm'), alt: 'Meridian Film Fund', href: '#' },
        { src: img('creator-youtube-sponsor-halcyon'), alt: 'Halcyon Lenses', href: '#' },
        { src: img('creator-youtube-sponsor-northpine'), alt: 'North Pine Audio', href: '#' },
      ] }),
      b('press', 'reviews', { title: 'What people said', average: '4.9', count: '19 films', source: 'Press and viewers', items: [
        { rating: 5, quote: 'Reeve has quietly built the most serious infrastructure journalism operation in the country, and it lives on a video platform.', author: 'The Chicago Review', date: 'February 2026', source: 'other' },
        { rating: 5, quote: 'I work in transmission planning. This is the first time anyone has explained my job on camera without getting a single thing wrong.', author: 'Devon R.', date: 'January 2026', source: 'other' },
        { rating: 5, quote: 'Watched an hour about sidewalk law. Voluntarily. Twice.', author: 'mkhalid_', date: 'April 2026', source: 'other' },
      ] }),
      b('support', 'cta', { headline: 'The films are free. Keeping them free is the hard part.', subhead: 'No paywall, no mid-rolls, no sponsor reading dropped into the middle of an interview. Members cover about a third of the budget and get the raw interviews.', background: 'accent', button: { label: 'Become a member — $6/mo', href: '#' } }),
      b('money', 'accordion', { title: 'The money, in detail', items: [
        { heading: 'What does a film cost to make?', body: 'Between $140,000 and $210,000, most of it salary for six people over eleven months. Travel and archive licensing are the next two lines. The camera package has not been upgraded since 2022 and nobody has noticed.' },
        { heading: 'Where does that come from?', body: 'Roughly a third from members at $6 a month, a third from three foundations that have no editorial input and sign a document saying so, and a third from YouTube revenue on the back catalogue. No single source can pull more than a third, which is deliberate.' },
        { heading: 'Do sponsors see the film first?', body: 'No. Sponsors are named in the end card and in the description, they read the film at the same time as everyone else, and they have never once asked to change anything — partly because the contract says the answer is no.' },
        { heading: 'Why no mid-rolls?', body: 'An hour-long film about a bridge inspection has maybe four moments where attention is fragile, and an ad break lands in one of them. The membership exists so I never have to weigh that trade.' },
        { heading: 'Can I use a clip in a class?', body: 'Yes, for any non-commercial teaching, no permission needed. The sources list published with each film is there for exactly that. For anything commercial, email and ask.' },
      ] }),
      b('socials', 'social-links', { title: 'Elsewhere', layout: 'row', variant: 'icon', align: 'center', links: [
        { platform: 'youtube', href: '#', label: 'Harlan Reeve' },
        { platform: 'x', href: '#', label: '@harlanreeve' },
        { platform: 'linkedin', href: '#', label: 'Harlan Reeve' },
        { platform: 'email', href: '#', label: 'sponsorship@harlanreeve.com' },
      ] }),
      b('footer', 'footer', { brand: 'HARLAN REEVE', tagline: 'Documentary films about the things that hold cities up.', links: [{ label: 'Films', href: '#films' }, { label: 'Sponsorship', href: '#sponsors' }, { label: 'Membership', href: '#support' }], copyright: '© Reeve Pictures LLC, Chicago. Sources published with every film.' }),
    ],
  }),

  // ── paid newsletter writer ─────────────────────────────────────────────────
  tpl({
    id: 'creator-newsletter',
    vertical: 'creator',
    label: 'Paid Newsletter — Landing',
    description: 'A single-purpose subscribe page for a paid weekly letter, with a full sample issue on the page.',
    tags: ['newsletter', 'pricing', 'faq', 'long-form', 'b2b'],
    layout: 'landing',
    preset: 'sand',
    meta: { title: 'Margin Notes — the business of small publishing', description: 'Every Thursday: one reported piece on how small publishers, bookshops and independent media actually make money. Free and paid tiers.', lang: 'en', favicon: '✉️' },
    blocks: [
      b('promo', 'announcement-bar', { text: 'Issue 208 is out: what a bookshop actually earns on a £9.99 paperback.', linkLabel: 'Read it below', href: '#sample', tone: 'info', dismissible: true }),
      b('hero', 'hero', { eyebrow: 'Thursdays · issue 208 · 24,000 readers', headline: 'How small publishing actually makes money.', subhead: 'One reported piece a week on the economics of bookshops, small presses, zines and independent media — with the real numbers, from people who agreed to show them.', align: 'center', minHeight: 'md', cta: { label: 'Subscribe free', href: '#subscribe' } }),
      b('subscribe', 'newsletter', { title: 'Start with the free tier', intro: 'Every Thursday, the full reported piece, with no paywall on the reporting itself. Paid readers also get the spreadsheets, the interview transcripts and the Tuesday open thread.', placeholder: 'you@email.com', submitLabel: 'Subscribe free', successMessage: 'Welcome — issue 209 lands Thursday at 7am UK time.' }),
      b('sample', 'blog-post', { title: 'What a bookshop actually earns on a £9.99 paperback', date: '12 June 2026', author: 'Devi Menon', cover: img('creator-newsletter-sample-cover'), coverAlt: 'A bookshop counter with a stack of paperbacks and a card reader', body: [
        { kind: 'paragraph', text: 'A customer hands over £9.99. By the time the shop closes, somewhere between £1.10 and £2.40 of that is still in the till as profit, and the rent has not been paid yet. Three independent shops — in Hebden Bridge, Margate and Glasgow — opened their books for this issue on the condition that I publish the ranges rather than their individual figures.' },
        { kind: 'heading', text: 'Where the £9.99 goes' },
        { kind: 'bullet', text: '£4.50–£5.50 to the wholesaler or publisher, depending on the discount the shop can negotiate. Volume is everything, and small shops have none.' },
        { kind: 'bullet', text: 'Nothing in VAT — books are zero-rated in the UK. It reappears the moment the shop sells a tote bag, which is one reason every shop sells tote bags.' },
        { kind: 'bullet', text: '£0.22–£0.31 in card fees, higher than any of the three owners expected when I asked them to guess.' },
        { kind: 'bullet', text: 'The remainder, £4.20–£5.30, covers rent, staff, heat, insurance and the owner. In two of the three shops the owner is the last one paid.' },
        { kind: 'quote', text: '“I stopped thinking of it as selling books about four years ago. I sell about ninety minutes of somebody’s Saturday, and a book is what they take home from it.” — bookshop owner, Margate' },
        { kind: 'heading', text: 'The number nobody volunteers' },
        { kind: 'paragraph', text: 'All three shops make more per square metre from events, coffee and stationery than from books. None of them lead with that publicly, and two were visibly uncomfortable saying it out loud, which tells you something about how the trade sees itself. The full profit-and-loss breakdown, with the events maths, is in the paid version of this issue.' },
        { kind: 'paragraph', text: 'Next week: what a small press pays a translator, and why the rate has not moved since 2016.' },
      ] }),
      b('issues', 'blog-list', { title: 'Recent issues', columns: 3, posts: [
        { title: 'The 3am shift at a print-on-demand warehouse', excerpt: 'Two nights with the machines that make one copy at a time, and what that does to a small press’s margins.', href: '#', image: img('creator-newsletter-issue-print'), date: '5 June 2026', tag: 'Reported' },
        { title: 'Nobody knows what a zine costs', excerpt: 'Eleven makers, eleven pricing methods, one shared refusal to count their own labour.', href: '#', image: img('creator-newsletter-issue-zine'), date: '29 May 2026', tag: 'Reported' },
        { title: 'The subscription cliff at month fourteen', excerpt: 'Why paid newsletters lose people at almost exactly the same point, with churn data from nine writers.', href: '#', image: img('creator-newsletter-issue-churn'), date: '22 May 2026', tag: 'Data' },
        { title: 'What a literary festival pays', excerpt: 'Fee ranges for eleven UK and Irish festivals, published with permission, plus the four that declined.', href: '#', image: img('creator-newsletter-issue-festival'), date: '15 May 2026', tag: 'Rates' },
        { title: 'The distributor problem, explained slowly', excerpt: 'If you have ever wondered why a small press cannot simply sell to shops directly, start with this one.', href: '#', image: img('creator-newsletter-issue-distro'), date: '8 May 2026', tag: 'Explainer' },
        { title: 'A year of Margin Notes, audited', excerpt: 'My own revenue, costs and churn, in full, because it would be absurd to write this letter and not.', href: '#', image: img('creator-newsletter-issue-audit'), date: '1 May 2026', tag: 'Open books' },
      ] }),
      b('tiers', 'pricing', { title: 'Two tiers, one letter', subtitle: 'The reporting is never paywalled. The working — spreadsheets, transcripts, sources — is what you pay for.', plans: [
        { name: 'Free', price: '£0', period: 'forever', features: ['The full reported piece, weekly', 'Complete archive of 208 issues', 'No ads, ever'], ctaLabel: 'Subscribe free', ctaHref: '#subscribe' },
        { name: 'Paid', price: '£7', period: '/mo', features: ['Everything free readers get', 'The spreadsheets behind each issue', 'Interview transcripts, lightly redacted', 'Tuesday open thread', 'Quarterly rates survey'], ctaLabel: 'Go paid', ctaHref: '#', featured: true },
        { name: 'Founding', price: '£180', period: '/yr', features: ['Everything in Paid', 'Your name in the annual open-books issue', 'Two 30-minute calls a year', 'Funds one commissioned piece a quarter'], ctaLabel: 'Become founding', ctaHref: '#' },
      ] }),
      b('readers', 'testimonials', { title: 'Who reads it', items: [
        { quote: 'I have run a small press for nine years and Margin Notes is the only place I have seen my own P&L described accurately by someone who does not work here.', author: 'Órla D.', role: 'Publisher, Galway' },
        { quote: 'We use the quarterly rates survey to set our freelance budget. It is worth roughly a hundred times what it costs.', author: 'Tom A.', role: 'Editor, London' },
        { quote: 'The churn issue made me redesign our onboarding in a weekend. Month fourteen is real and I had never named it.', author: 'Bea S.', role: 'Newsletter writer' },
      ] }),
      b('faq', 'faq', { title: 'Reasonable questions', items: [
        { question: 'How long is it?', answer: 'Between 1,200 and 2,000 words, once a week, on Thursday morning UK time. It is deliberately one email and never a digest of five.' },
        { question: 'Is the archive paywalled?', answer: 'No. All 208 issues are readable by anyone, including the reporting in the paid ones. Only the working files sit behind the paid tier.' },
        { question: 'Do you take sponsorship?', answer: 'No, and that is the whole point of the paid tier. If it ever changes it will be announced at the top of an issue, not in a footer.' },
        { question: 'Can I expense it?', answer: 'Yes — a VAT receipt is emailed automatically, and there is a group rate for teams of four or more. Reply to any issue and ask.' },
        { question: 'What if I cannot afford it?', answer: 'Reply and say so and I will comp you for a year. About thirty people a year do this and nobody is asked why.' },
      ] }),
      b('closing', 'cta', { headline: 'Thursday, 7am, one email.', subhead: 'Start on the free tier. Upgrade when an issue is worth £7 to you, and not before.', background: 'primary', button: { label: 'Subscribe free', href: '#subscribe' } }),
      b('socials', 'social-links', { title: 'Devi Menon elsewhere', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'linkedin', href: '#', label: 'Devi Menon' },
        { platform: 'mastodon', href: '#', label: '@devi' },
        { platform: 'rss', href: '#', label: 'RSS' },
        { platform: 'email', href: '#', label: 'devi@marginnotes.co.uk' },
      ] }),
      b('footer', 'footer', { brand: 'Margin Notes', tagline: 'The business of small publishing, weekly.', links: [{ label: 'Archive', href: '#issues' }, { label: 'Pricing', href: '#tiers' }, { label: 'FAQ', href: '#faq' }], copyright: '© Devi Menon. Reader-funded: no sponsorship, no affiliate links.' }),
    ],
  }),

  // ── minimal link-in-bio ────────────────────────────────────────────────────
  tpl({
    id: 'creator-link-in-bio',
    vertical: 'creator',
    label: 'Link in Bio — Minimal',
    description: 'One screen, one avatar, one column of links — the page a profile bio actually points at.',
    tags: ['link-in-bio', 'one-pager', 'mobile-first', 'social'],
    layout: 'minimal',
    preset: 'candy',
    meta: { title: 'Jules Amara — links', description: 'Illustrator and occasional DJ in Melbourne. Shop, commissions, mixes and the mailing list, all in one place.', lang: 'en', favicon: '🔗' },
    blocks: [
      b('me', 'profile-header', { name: 'Jules Amara', headline: 'Illustrator · occasional DJ · Melbourne', location: 'Naarm / Melbourne, Australia', avatar: img('creator-linkbio-avatar'), summary: 'Risograph illustration for books and record sleeves. The commission list opens twice a year. I also play records on a community station on Thursday nights, which is unrelated, but people keep asking.', contacts: [
        { type: 'email', value: 'hi@julesamara.com', label: 'Commissions' },
        { type: 'website', value: 'julesamara.com' },
        { type: 'location', value: 'Naarm / Melbourne' },
      ], showShare: true, shareLabel: 'Share' }),
      b('links', 'feed', { layout: 'list', items: [
        { title: 'Shop — prints and zines', subtitle: 'Restocked 3 June', text: 'Riso prints from A4 up, plus the two zines. Ships worldwide from Melbourne.', badge: 'New stock', href: '#' },
        { title: 'Commission list — opens 1 September', subtitle: 'Six slots, twice a year', text: 'Join the waitlist and you get first refusal before it goes public.', badge: 'Waitlist', href: '#' },
        { title: 'Thursday night mixes', subtitle: 'Skylark FM · 21:00 AEST', text: 'Two hours of records, archived the next morning. Currently on show 61.', href: '#' },
        { title: 'The portfolio, properly', subtitle: 'Book covers, sleeves, editorial', text: 'Full case studies, with the rejected roughs included.', href: '#' },
        { title: 'Rates and how I work', subtitle: 'Plain language, no “price on application”', text: 'What things cost, what a licence covers, and what I will not take on.', href: '#' },
      ] }),
      b('socials', 'social-links', { layout: 'grid', variant: 'icon', align: 'center', links: [
        { platform: 'instagram', href: '#', label: '@julesamara' },
        { platform: 'tiktok', href: '#', label: '@julesamara' },
        { platform: 'youtube', href: '#', label: 'Mix archive' },
        { platform: 'email', href: '#', label: 'hi@julesamara.com' },
        { platform: 'website', href: '#', label: 'julesamara.com' },
      ] }),
      b('list', 'newsletter', { title: 'Two emails a year', intro: 'One when the shop restocks, one when commissions open. That is genuinely the whole schedule.', placeholder: 'you@email.com', submitLabel: 'Notify me', successMessage: 'Saved. You will hear from me in September.' }),
      b('rights', 'copyright', { holder: 'Jules Amara', text: 'All illustration © the artist. Please ask before reposting.', showSymbol: true, align: 'center' }),
    ],
  }),
];
