/**
 * `ecommerce` starter templates — seven ways to sell online: a running-gear shop,
 * an editorial skincare brand, a coffee subscription, a print-on-demand art store,
 * a streetwear drop, a handmade-crafts maker, and a digital downloads library.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const ecommerceTemplates: Template[] = [
  tpl({
    id: 'ecommerce-shop',
    vertical: 'ecommerce',
    label: 'Shop — Product',
    description: 'A single-product apparel shop leading with photography, kit bundles and buyer reviews.',
    tags: ['b2c', 'pricing', 'gallery', 'reviews', 'dark'],
    layout: 'classic',
    preset: 'midnight',
    meta: { title: 'Pace Athletics — Run Gear', description: 'Engineered running gear, tested on real roads.', lang: 'en', favicon: '👟' },
    blocks: [
      b('nav', 'nav', { brand: 'Pace', sticky: true, links: [{ label: 'Shop', href: '#shop' }, { label: 'Bundles', href: '#bundles' }, { label: 'Reviews', href: '#reviews' }], cta: { label: 'Shop now', href: '#shop' } }),
      b('hero', 'hero', { eyebrow: 'Free shipping over £50', headline: 'Gear that keeps up with you', subhead: 'Lightweight, breathable, and built to last mile after mile.', align: 'center', minHeight: 'lg', image: img('run-hero'), overlay: 'dark', cta: { label: 'Shop the range', href: '#shop' } }),
      b('shop', 'gallery', { layout: 'grid', columns: 4, gap: 'md', lightbox: true, items: [{ src: img('run-1'), alt: 'Tempo tee' }, { src: img('run-2'), alt: 'Split shorts' }, { src: img('run-3'), alt: 'Trail jacket' }, { src: img('run-4'), alt: 'Compression socks' }] }),
      b('why', 'features', { title: 'Why Pace', columns: 3, items: [
        { icon: '🪶', title: 'Feather-light', text: 'Under 90g for the tempo tee.' },
        { icon: '💨', title: 'Stays dry', text: 'Wicking fabric, flatlock seams.' },
        { icon: '♻️', title: 'Made to last', text: 'Recycled fibres, 2-year guarantee.' },
      ] }),
      b('bundles', 'pricing', { title: 'Kit bundles', subtitle: 'Save when you gear up together.', plans: [
        { name: 'Starter', price: '£65', features: ['Tempo tee', 'Split shorts'], ctaLabel: 'Add to bag', ctaHref: '#' },
        { name: 'Race day', price: '£120', features: ['Tempo tee', 'Split shorts', 'Compression socks', 'Cap'], ctaLabel: 'Add to bag', ctaHref: '#', featured: true },
        { name: 'All-weather', price: '£180', features: ['Everything in Race day', 'Trail jacket', 'Gloves'], ctaLabel: 'Add to bag', ctaHref: '#' },
      ] }),
      b('reviews', 'testimonials', { title: '4.8 from 2,000+ runners', items: [
        { quote: 'The shorts are the best I’ve owned. No chafe on a marathon.', author: 'Chris', role: 'Verified buyer' },
        { quote: 'Light, dries fast, and still looks new after a season.', author: 'Mei', role: 'Verified buyer' },
      ] }),
      b('faq', 'faq', { title: 'Shipping & returns', items: [
        { question: 'How fast is delivery?', answer: 'Next-day in the UK on orders before 3pm.' },
        { question: 'What’s your returns policy?', answer: '60-day free returns, no questions asked.' },
      ] }),
      b('cta', 'cta', { headline: 'Ready to run?', subhead: 'Free shipping over £50 and a 60-day return window.', background: 'primary', button: { label: 'Shop now', href: '#shop' } }),
      b('footer', 'footer', { brand: 'Pace Athletics', tagline: 'Engineered run gear.', links: [{ label: 'Shop', href: '#shop' }, { label: 'Returns', href: '#faq' }], copyright: '© Pace Athletics' }),
    ],
  }),

  tpl({
    id: 'ecommerce-skincare',
    vertical: 'ecommerce',
    label: 'Skincare — Editorial',
    description: 'A small-batch skincare brand that sells through ingredient transparency and long-form writing.',
    tags: ['skincare', 'beauty', 'long-form', 'newsletter', 'b2c'],
    layout: 'editorial',
    preset: 'sand',
    meta: { title: 'Anjali & Co. — Small-batch skincare', description: 'Six products, forty ingredients, and a full list of what is in each one. Made in Bengaluru.', lang: 'en', favicon: '🌿' },
    blocks: [
      b('promo', 'announcement-bar', { text: 'Free delivery across India on orders over ₹1,500 — dispatched within 24 hours.', linkLabel: 'Shop the six', href: '#range', tone: 'promo', dismissible: true }),
      b('nav', 'nav', { brand: 'Anjali & Co.', sticky: false, links: [{ label: 'The range', href: '#range' }, { label: 'Ingredients', href: '#ingredients' }, { label: 'Our story', href: '#story' }, { label: 'Reviews', href: '#reviews' }], cta: { label: 'Join the letter', href: '#letter' } }),
      b('hero', 'hero', { eyebrow: 'Made in Bengaluru · batch no. 41', headline: 'Six products. Nothing you cannot pronounce.', subhead: 'We publish the full formula for every bottle, down to fractions of a percent, because you should not need a chemistry degree to buy a moisturiser.', align: 'left', minHeight: 'md', overlay: 'none', cta: { label: 'Read the ingredient list', href: '#ingredients' } }),
      b('story', 'rich-text', { blocks: [
        { kind: 'heading', text: 'We started because a label lied to us' },
        { kind: 'paragraph', text: 'In 2019 our founder bought a ₹3,200 serum marketed as "98% natural" and spent an evening working out that the remaining 2% was doing all of the work, and that the 98% was mostly water. That is not a scandal — water is a perfectly good ingredient — but the label was written to stop you noticing.' },
        { kind: 'paragraph', text: 'So we built the opposite. Every Anjali & Co. product ships with its complete formula printed on the carton, in descending order, with percentages. Six products is not a soft launch; it is the whole plan. We would rather make six things properly than forty things quickly.' },
        { kind: 'quote', text: 'If we cannot explain why an ingredient is in the bottle, it does not go in the bottle.' },
        { kind: 'subheading', text: 'How we make it' },
        { kind: 'numbered', text: 'Batches of 400 units, blended in our Indiranagar workshop' },
        { kind: 'numbered', text: 'Third-party stability and microbial testing on every batch' },
        { kind: 'numbered', text: 'Amber glass, aluminium caps, refill pouches from batch 30 onward' },
        { kind: 'paragraph', text: 'Shelf life is twelve months unopened and six once you break the seal. We print both dates. If a batch is close to date we discount it and say so — you will find those under "last of the batch" rather than buried in a sale.' },
      ] }),
      b('range', 'product', { title: 'The six', subtitle: 'Everything we make. Prices include GST. The five bottled products also come as refill pouches, from ₹560.', columns: 3, items: [
        { name: 'Morning Milk Cleanser', description: 'Oat, glycerin, and a very small amount of coco-glucoside. Does not strip.', price: '₹890', image: img('ec-skin-cleanser'), ctaLabel: 'Add to bag', ctaHref: '#' },
        { name: 'Niacinamide 4% Serum', description: 'Four percent, not ten. Ten made most of our testers flush.', price: '₹1,240', image: img('ec-skin-serum'), badge: 'Best seller', ctaLabel: 'Add to bag', ctaHref: '#' },
        { name: 'Squalane + Ceramide Cream', description: 'Olive-derived squalane, three ceramides, no fragrance at all.', price: '₹1,480', image: img('ec-skin-cream'), ctaLabel: 'Add to bag', ctaHref: '#' },
        { name: 'Mineral Sunscreen SPF 40', description: 'Zinc oxide, tinted very slightly warm so it does not go grey.', price: '₹1,150', image: img('ec-skin-spf'), ctaLabel: 'Add to bag', ctaHref: '#' },
        { name: 'Rice Water Toner', description: 'Fermented rice water and panthenol. The simplest thing we sell.', price: '₹720', was: '₹840', image: img('ec-skin-toner'), badge: 'Last of batch 39', ctaLabel: 'Add to bag', ctaHref: '#' },
        { name: 'Beeswax Lip Balm', description: 'Coorg beeswax, castor oil and shea butter. Three ingredients, no flavouring.', price: '₹390', image: img('ec-skin-balm'), ctaLabel: 'Add to bag', ctaHref: '#' },
      ] }),
      b('ingredients', 'accordion', { title: 'What is actually in it', items: [
        { heading: 'Niacinamide 4% Serum — full formula', body: 'Aqua 88.2%, Niacinamide 4%, Glycerin 3.5%, Pentylene Glycol 2%, Panthenol 1%, Zinc PCA 0.8%, Xanthan Gum 0.3%, Sodium Phytate 0.1%, Phenoxyethanol + Ethylhexylglycerin 0.1%. pH 5.6.' },
        { heading: 'Why 4% and not 10%', body: 'In our own 60-person patch test, 10% niacinamide caused visible flushing in 19 people and stinging in 11. At 4% that dropped to two and one. The published evidence for barrier and pigmentation benefit is solid from about 2% upward, so the extra 6% was buying us irritation and not much else.' },
        { heading: 'Fragrance, essential oils and dyes', body: 'None, anywhere, in any product. This was the single most common cause of irritation we saw in testing, and skincare does not need to smell of anything.' },
        { heading: 'Preservatives', body: 'Yes, we use them. Anything with water in it needs a preservative or it grows mould within weeks. Ours is phenoxyethanol at 0.1% — well under the 1% regulatory cap and one of the best-studied options available.' },
        { heading: 'Animal testing and sourcing', body: 'No animal testing at any stage, by us or our suppliers. Squalane is olive-derived, never shark. Our only animal-derived ingredient is beeswax in the lip balm, from a co-operative in Coorg.' },
      ] }),
      b('press', 'logos', { title: 'Written about in', items: [
        { src: img('ec-skin-press-1'), alt: 'Vogue India', href: '#' },
        { src: img('ec-skin-press-2'), alt: 'Mint Lounge', href: '#' },
        { src: img('ec-skin-press-3'), alt: 'The Hindu Weekend', href: '#' },
        { src: img('ec-skin-press-4'), alt: 'Grazia India', href: '#' },
      ] }),
      b('reviews', 'reviews', { title: 'What people write back', average: '4.7', count: '1,384', source: 'Verified orders', items: [
        { rating: 5, quote: 'I have rosacea and almost nothing is boring enough for my face. This is beautifully boring. The cream especially.', author: 'Sreelakshmi P.', date: 'March 2026', source: 'other' },
        { rating: 4, quote: 'The sunscreen is the only mineral one I have found that does not turn me ashy, though it does take a minute to rub in. Worth it.', author: 'Danish R.', date: 'February 2026', source: 'other' },
        { rating: 5, quote: 'Emailed to ask about the preservative and got a two-paragraph answer from an actual formulator within a day. That is why I keep buying.', author: 'Meera J.', date: 'January 2026', source: 'other' },
      ] }),
      b('letter', 'newsletter', { title: 'Batch notes', intro: 'One email when a batch goes out: what changed, what we learned, and what is running low. Roughly monthly, never a countdown timer.', placeholder: 'you@example.com', submitLabel: 'Send me batch notes', successMessage: 'You are on the list — the next batch note goes out with batch 42.' }),
      b('footer', 'footer', { brand: 'Anjali & Co.', tagline: 'Small-batch skincare, fully disclosed.', links: [{ label: 'The range', href: '#range' }, { label: 'Ingredients', href: '#ingredients' }, { label: 'Instagram', href: '#' }], copyright: '© Anjali & Co., Bengaluru' }),
    ],
  }),

  tpl({
    id: 'ecommerce-coffee-subscription',
    vertical: 'ecommerce',
    label: 'Coffee — Subscription',
    description: 'A roaster selling a recurring coffee plan as one conversion page: proof, plans, objections, one CTA.',
    tags: ['coffee', 'subscription', 'pricing', 'faq', 'b2c'],
    layout: 'landing',
    preset: 'forest',
    meta: { title: 'Third Rail Coffee — Subscriptions', description: 'Roasted Monday, shipped Tuesday, on your counter Thursday. Austin, TX.', lang: 'en', favicon: '☕' },
    blocks: [
      b('nav', 'nav', { brand: 'Third Rail', sticky: true, links: [{ label: 'How it works', href: '#how' }, { label: 'Plans', href: '#plans' }, { label: 'Questions', href: '#faq' }], cta: { label: 'Start a plan', href: '#plans' } }),
      b('hero', 'hero', { eyebrow: 'Austin, TX · roasting since 2016', headline: 'Coffee that was green beans on Monday', subhead: 'We roast on Monday, ship on Tuesday, and it lands on your counter Thursday. Pick a grind, pick a rhythm, and skip any week you are travelling.', align: 'center', minHeight: 'lg', image: img('ec-coffee-hero'), overlay: 'scrim', cta: { label: 'See the plans', href: '#plans' } }),
      b('numbers', 'stats', { title: 'Where we are at', columns: 4, items: [
        { value: '3', label: 'Roast to your counter', suffix: ' days' },
        { value: '6,200', label: 'Active subscribers' },
        { value: '11', label: 'Producer relationships' },
        { value: '94', label: 'Renew past month six', suffix: '%' },
      ] }),
      b('how', 'steps', { title: 'How it works', subtitle: 'Four things, and only the first one takes any thought.', items: [
        { title: 'Tell us how you brew', text: 'Espresso, filter, moka pot or French press. We grind to match, or send whole bean if you have a grinder.' },
        { title: 'Pick a rhythm', text: 'Every week, every two weeks, or monthly. Change it whenever — the setting is on the front of your account page, not buried three clicks down.' },
        { title: 'We roast Monday', text: 'Your bag is roasted the Monday before it ships, with the roast date stamped on the side. No warehouse, no six-week-old stock.' },
        { title: 'Skip, pause, or cancel', text: 'One click each, no phone call, no retention offer. If you cancel we will not email you about it again for six months.' },
      ] }),
      b('plans', 'pricing', { title: 'Three plans', subtitle: 'Prices per delivery. Shipping is free in the lower 48 on every plan.', plans: [
        { name: 'Solo', price: '$17', period: 'per 12oz bag', features: ['One 12oz bag', 'Single origin, rotating', 'Free shipping', 'Skip or pause any time'], ctaLabel: 'Start solo', ctaHref: '#' },
        { name: 'Household', price: '$31', period: 'per delivery', features: ['Two 12oz bags', 'One single origin + one blend', 'Free shipping', 'Skip or pause any time', 'First delivery ships next business day'], ctaLabel: 'Start household', ctaHref: '#', featured: true },
        { name: 'Office', price: '$96', period: 'per delivery', features: ['Five 2lb bags', 'Blend of your choice, fixed', 'Free shipping', 'Net-30 invoicing available', 'Free filter-brewing session on video'], ctaLabel: 'Talk to us', ctaHref: '#faq' },
      ] }),
      b('roasts', 'tabs', { items: [
        { label: 'This week: Huila, Colombia', text: 'Washed caturra from Finca La Esperanza at 1,750m, bought at $3.40/lb FOB against a C-market of $1.85. Tastes like red apple, brown sugar and a little black tea. Roasted for filter; works fine as espresso if you pull it long.' },
        { label: 'The house blend', text: 'Sixty percent Brazil Cerrado, forty percent Guatemala Huehuetenango. Built for milk — it holds up in a 10oz latte instead of disappearing. This is what goes out on every Office plan unless you ask for something else.' },
        { label: 'Decaf', text: 'Sugarcane-process decaf from Cauca, Colombia. Genuinely good rather than merely acceptable, which took us four years and eleven rejected samples to find. Swap it onto any plan at no extra cost.' },
        { label: 'What we do not do', text: 'Flavoured coffee, dark roast that tastes only of roast, and "mystery" bags with no origin on the label. If you want any of those we will happily point you at someone in town who does them well.' },
      ] }),
      b('proof', 'testimonials', { title: 'From subscribers', items: [
        { quote: 'I switched from a big subscription because their bags never had a roast date. Third Rail prints it on the side. Six months in and not one stale bag.', author: 'Dana Whitfield', role: 'Household plan, 14 months' },
        { quote: 'Our studio runs on the Office plan. Net-30 invoicing sorted our accounts person out, and the coffee genuinely made people come into the building on Fridays.', author: 'Ibrahim Sowe', role: 'Studio manager, East Austin' },
        { quote: 'I paused for three months while I was overseas and nobody sent me a single guilt-trip email. Resumed the day I landed.', author: 'Priya Ramanathan', role: 'Solo plan, 2 years' },
      ] }),
      b('faq', 'faq', { title: 'Before you start', items: [
        { question: 'Can I change grind after I have started?', answer: 'Yes, on your account page, and it applies to the next delivery — including one already in the roasting queue if you change it before Sunday night.' },
        { question: 'What if I do not like a coffee?', answer: 'Tell us within two weeks and we will send a replacement bag of something different, free. We do not ask you to ship the first one back; postage would cost more than the coffee.' },
        { question: 'Do you ship outside the US?', answer: 'Canada only, at $12 flat, usually five business days. Customs is on you, but it is generally under $6.' },
        { question: 'Is there a minimum commitment?', answer: 'No. You can cancel after one delivery. About one in nine people do, which is fine — coffee subscriptions are not for everybody.' },
        { question: 'Can I gift a plan?', answer: 'Yes: three, six or twelve deliveries, prepaid, with a note card. It does not auto-renew into a paid subscription when it ends, because that trick is horrible.' },
      ] }),
      b('start', 'cta', { headline: 'First bag ships Tuesday', subhead: 'Order by Sunday night and you are in this week’s roast. Skip, pause or cancel in one click, forever.', background: 'primary', button: { label: 'Start a plan', href: '#plans' } }),
      b('footer', 'footer', { brand: 'Third Rail Coffee', tagline: 'Roasted Monday. Austin, TX.', links: [{ label: 'Plans', href: '#plans' }, { label: 'How it works', href: '#how' }, { label: 'Wholesale', href: '#' }], copyright: '© Third Rail Coffee Co.' }),
    ],
  }),

  tpl({
    id: 'ecommerce-art-prints',
    vertical: 'ecommerce',
    label: 'Art prints — Showcase',
    description: 'A print-on-demand art store where the work carries the page, with sizing and framing detail underneath.',
    tags: ['art', 'prints', 'gallery', 'portfolio', 'light'],
    layout: 'showcase',
    preset: 'mono',
    meta: { title: 'Editionen — Archival art prints', description: 'Open and limited-edition giclée prints from independent artists. Printed and shipped from Berlin.', lang: 'en', favicon: '🖼️' },
    blocks: [
      b('nav', 'nav', { brand: 'Editionen', sticky: true, links: [{ label: 'New work', href: '#featured' }, { label: 'The wall', href: '#wall' }, { label: 'Sizes', href: '#sizes' }, { label: 'Artists', href: '#artists' }], cta: { label: 'Browse prints', href: '#wall' } }),
      b('featured', 'carousel', { title: 'New this month', autoplay: true, items: [
        { src: img('ec-art-feat-1'), alt: 'Abstract cyanotype in deep blue', caption: 'Hafen II — Lina Brandt · limited edition of 50 · from €95' },
        { src: img('ec-art-feat-2'), alt: 'Minimal continuous-line drawing of a seated figure', caption: 'Sitzend — Tomás Rey · open edition · from €48' },
        { src: img('ec-art-feat-3'), alt: 'Two-colour riso-style landscape', caption: 'Havel, August — Nour El-Amin · limited edition of 30 · from €120' },
        { src: img('ec-art-feat-4'), alt: 'Botanical fern study on cream paper', caption: 'Farn — Ida Marchetti · open edition · from €48' },
      ] }),
      b('wall', 'gallery', { layout: 'masonry', columns: 3, gap: 'lg', lightbox: true, items: [
        { src: img('ec-art-wall-1'), alt: 'Long-exposure seascape at dawn', caption: 'Nordsee, 04:40 — €95' },
        { src: img('ec-art-wall-2'), alt: 'Geometric colour-field composition', caption: 'Block Study 7 — €48' },
        { src: img('ec-art-wall-3'), alt: 'Soft-focus portrait against a window', caption: 'Anna, Kreuzberg — €120' },
        { src: img('ec-art-wall-4'), alt: 'Ink drawing of city rooftops', caption: 'Dächer — €48' },
        { src: img('ec-art-wall-5'), alt: 'Pale desert horizon', caption: 'Almería — €95' },
        { src: img('ec-art-wall-6'), alt: 'Overlapping translucent shapes', caption: 'Interference — €72' },
        { src: img('ec-art-wall-7'), alt: 'Close crop of peeling painted wall', caption: 'Wandfarbe — €48' },
        { src: img('ec-art-wall-8'), alt: 'Night street with wet reflections', caption: 'Regen, Neukölln — €120' },
        { src: img('ec-art-wall-9'), alt: 'Still life with glass and long shadow', caption: 'Glas I — €72' },
      ] }),
      b('sizes', 'product', { title: 'Sizes and framing', subtitle: 'Every print is giclée on 310gsm Hahnemühle cotton rag, with a 20mm unprinted border for framing.', columns: 4, items: [
        { name: 'A4 — 21 × 29.7cm', description: 'Unframed, rolled in a rigid tube.', price: '€48', image: img('ec-art-size-a4'), ctaLabel: 'Choose a print', ctaHref: '#wall' },
        { name: 'A3 — 29.7 × 42cm', description: 'Unframed, rolled. The size most people pick.', price: '€72', image: img('ec-art-size-a3'), badge: 'Most ordered', ctaLabel: 'Choose a print', ctaHref: '#wall' },
        { name: 'A2 — 42 × 59.4cm', description: 'Unframed, rolled. Needs a wall with a bit of room.', price: '€95', image: img('ec-art-size-a2'), ctaLabel: 'Choose a print', ctaHref: '#wall' },
        { name: 'Framed A3', description: 'Solid oak or black ash, 30mm profile, museum acrylic.', price: '€148', was: '€165', image: img('ec-art-size-framed'), ctaLabel: 'Choose a print', ctaHref: '#wall' },
      ] }),
      b('craft', 'split', { rows: [
        { title: 'Printed twelve minutes from our office', text: 'We print in Wedding on a twelve-colour Canon PRO-4100 that we own and calibrate ourselves every Monday morning. Nothing is drop-shipped through a third party, which is why a print ordered on Tuesday leaves the building on Wednesday rather than in ten to fourteen business days.', image: img('ec-art-studio'), imageAlt: 'Large-format printer in a Berlin studio' },
        { title: 'Paper you can read from across the room', text: 'Hahnemühle Photo Rag, 310gsm, 100% cotton, acid-free and rated for over a century of lightfastness under glass. It has a very slight texture that kills reflections and makes flat colour look like an object rather than a screenshot.', image: img('ec-art-paper'), imageAlt: 'Close crop of cotton rag paper texture' },
        { title: 'Artists are paid 40% of every sale', text: 'Not 10%, and not "exposure". Forty percent of the sale price, paid monthly, with a dashboard showing exactly what sold and where it went. Limited editions are numbered, signed by the artist, and retired permanently once the run is gone.', image: img('ec-art-artist'), imageAlt: 'Artist signing the margin of a print' },
      ] }),
      b('artists', 'team', { title: 'Currently on the wall', subtitle: 'Fourteen artists, six countries, all paid the same rate.', columns: 4, members: [
        { name: 'Lina Brandt', role: 'Cyanotype & alt-process', photo: img('ec-art-p-lina'), bio: 'Works in cyanotype from a converted garage in Leipzig. Everything is exposed in real sunlight, so summer editions run larger.', socials: [{ label: 'Instagram', href: '#' }] },
        { name: 'Tomás Rey', role: 'Line drawing', photo: img('ec-art-p-tomas'), bio: 'One continuous line, no lifting the pen, usually finished in under four minutes. Based in Valencia.', socials: [{ label: 'Instagram', href: '#' }] },
        { name: 'Nour El-Amin', role: 'Two-colour landscape', photo: img('ec-art-p-nour'), bio: 'Riso-inspired reductions of places within a bike ride of Berlin. Editions of 30, never reprinted.', socials: [{ label: 'Website', href: '#' }] },
        { name: 'Ida Marchetti', role: 'Botanical study', photo: img('ec-art-p-ida'), bio: 'Paints from the herbarium collection in Bologna. Mostly ferns, occasionally something with a flower on it.', socials: [{ label: 'Instagram', href: '#' }] },
      ] }),
      b('faq', 'faq', { title: 'Practical things', items: [
        { question: 'How is it packed?', answer: 'Rolled prints go in a 100mm rigid tube with end caps and a sheet of glassine. Framed prints go in a double-walled box with corner blocks. We have had four transit damages in 9,000 orders.' },
        { question: 'Delivery times', answer: 'Germany one to two working days, rest of the EU three to five, UK five to seven with duty prepaid, US and Canada seven to ten. Everything is tracked.' },
        { question: 'Do the colours match my screen?', answer: 'Closely, but not exactly — your screen emits light and paper reflects it. If a print looks materially different from the listing, send us a photo and we will reprint it or refund you.' },
        { question: 'Can I return a print?', answer: 'Fourteen days on open editions, unframed and unused. Limited editions are returnable too, but the number goes back into the run rather than being destroyed.' },
      ] }),
      b('letter', 'newsletter', { title: 'New editions, first', intro: 'Limited runs sell out in a few days. Subscribers see them 48 hours early — one email a month, nothing else.', placeholder: 'you@example.com', submitLabel: 'Get early access', successMessage: 'Done. The next drop reaches you two days before the site.' }),
      b('footer', 'footer', { brand: 'Editionen', tagline: 'Archival prints, printed in Berlin.', links: [{ label: 'The wall', href: '#wall' }, { label: 'Sizes', href: '#sizes' }, { label: 'Artists', href: '#artists' }], copyright: '© Editionen GmbH, Berlin' }),
    ],
  }),

  tpl({
    id: 'ecommerce-sneaker-drop',
    vertical: 'ecommerce',
    label: 'Streetwear — Drop',
    description: 'A limited streetwear release page built around a drop calendar, a raffle entry form and the rules.',
    tags: ['streetwear', 'sneakers', 'video', 'social', 'dark'],
    layout: 'bold',
    preset: 'candy',
    meta: { title: 'BLOK 22 — Drop 014', description: 'Drop 014: the Terrace Low in Chalk. 400 pairs, raffle entry closes Thursday 9pm AEST.', lang: 'en', favicon: '🔥' },
    blocks: [
      b('alert', 'announcement-bar', { text: 'Raffle for Drop 014 closes Thursday 9:00pm AEST — winners notified by 11pm.', linkLabel: 'Enter the raffle', href: '#raffle', tone: 'warning', dismissible: false }),
      b('nav', 'nav', { brand: 'BLOK 22', sticky: true, links: [{ label: 'Drop 014', href: '#drop' }, { label: 'Calendar', href: '#calendar' }, { label: 'Raffle', href: '#raffle' }, { label: 'Archive', href: '#archive' }], cta: { label: 'Enter', href: '#raffle' } }),
      b('hero', 'hero', { eyebrow: 'Drop 014 · 400 pairs · Melbourne', headline: 'TERRACE LOW / CHALK', subhead: 'Suede upper, gum sole, dyed in a single 400-pair run. No restock, no second colourway, no "back by popular demand".', align: 'center', minHeight: 'full', image: img('ec-drop-hero'), overlay: 'dark', cta: { label: 'Enter the raffle', href: '#raffle' } }),
      b('stock', 'progress', { title: 'What is left', subtitle: 'Live against the raffle allocation. Open stock is not capped and is not shown here.', display: 'segments', layout: 'inline', size: 'md', showValue: true, items: [
        { label: 'Terrace Low — Chalk', value: 61, max: 400, suffix: ' left', state: 'danger', caption: 'Raffle closes Thursday 23:59 AEST.' },
        { label: 'Terrace Hoodie — Chalk', value: 138, max: 250, suffix: ' left', state: 'warning' },
        { label: 'Drop 014 Tee', value: 900, max: 900, suffix: ' available', state: 'success', caption: 'Open stock — buys straight through, no raffle.' },
      ] }),
      b('drop', 'product', { title: 'Drop 014', subtitle: 'Sizes AU 5–14, including half sizes to AU 12.', columns: 3, items: [
        { name: 'Terrace Low — Chalk', description: 'Pig suede upper, gum outsole, hand-numbered inside the tongue.', price: 'A$249', image: img('ec-drop-shoe'), badge: '400 pairs', ctaLabel: 'Enter raffle', ctaHref: '#raffle' },
        { name: 'Terrace Hoodie — Chalk', description: '480gsm loopback cotton, milled in Portugal. 250 units.', price: 'A$189', image: img('ec-drop-hoodie'), badge: '250 units', ctaLabel: 'Enter raffle', ctaHref: '#raffle' },
        { name: 'Drop 014 Tee', description: 'Open stock — no raffle, buys straight through on Friday.', price: 'A$69', image: img('ec-drop-tee'), badge: 'Open stock', ctaLabel: 'Add to bag', ctaHref: '#' },
      ] }),
      b('film', 'video', { provider: 'youtube', src: 'https://www.youtube.com/watch?v=aqz-KE-bpKQ', title: 'Making Drop 014 — three months in Collingwood', poster: img('ec-drop-film-poster'), caption: 'Six minutes on how the Chalk dye came out wrong twice before it came out right.' }),
      b('calendar', 'timeline', { title: 'Drop calendar', items: [
        { date: 'Mon 3 Aug', title: 'Lookbook goes live', text: 'Full shot list on the site and on Instagram. The sizing guide is published at the same time — the Terrace runs a half size large.' },
        { date: 'Tue 4 Aug, 9am', title: 'Raffle opens', text: 'One entry per person, per size. Your card is authorised, not charged. Entering twice from two accounts voids both entries.' },
        { date: 'Thu 6 Aug, 9pm', title: 'Raffle closes', text: 'Hard stop. Anything submitted after 9:00:00pm AEST is not in the draw, including if you had the page open before then.' },
        { date: 'Thu 6 Aug, 11pm', title: 'Winners drawn', text: 'Random draw, results emailed to everyone — winners and not. Unsuccessful authorisations release within 48 hours.' },
        { date: 'Fri 7 Aug, 10am', title: 'Winners have 24 hours', text: 'Pay within the window or the pair rolls to the next name. Tees and open stock go on general sale at the same time.' },
        { date: 'Mon 10 Aug', title: 'Everything ships', text: 'Express within Australia, DHL everywhere else. Tracking numbers go out the same day.' },
      ] }),
      b('raffle', 'contact-form', { title: 'Enter the raffle — Drop 014', intro: 'Free to enter. One entry per person. Your card is authorised for the item price and released automatically if you are not drawn.', submitLabel: 'Enter the draw', successMessage: 'You are in. Watch your inbox Thursday at 11pm AEST — we email everyone, win or lose.', fields: [
        { name: 'name', label: 'Full name', type: 'text', placeholder: 'As it appears on your ID', required: true },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'you@example.com', required: true },
        { name: 'phone', label: 'Mobile', type: 'tel', placeholder: '04XX XXX XXX', required: true },
        { name: 'item', label: 'Which item', type: 'select', required: true, options: ['Terrace Low — Chalk', 'Terrace Hoodie — Chalk', 'Both (separate draws)'] },
        { name: 'size', label: 'Size', type: 'select', required: true, options: ['AU 5', 'AU 6', 'AU 7', 'AU 8', 'AU 9', 'AU 10', 'AU 11', 'AU 12', 'AU 13', 'AU 14', 'Hoodie S', 'Hoodie M', 'Hoodie L', 'Hoodie XL'] },
        { name: 'city', label: 'Delivery city', type: 'text', placeholder: 'Melbourne', required: true },
        { name: 'terms', label: 'I have read the raffle rules and understand entries are one per person', type: 'checkbox', required: true },
      ] }),
      b('archive', 'feed', { title: 'The archive', layout: 'cards', items: [
        { title: 'Drop 013 — Court Mid / Oxblood', subtitle: 'April 2026 · 300 pairs', text: 'Sold out in the raffle at 4.1 entries per pair. Resale is sitting around A$390, which we are not thrilled about and cannot do much about.', image: img('ec-drop-a13'), badge: 'Sold out', href: '#' },
        { title: 'Drop 012 — Utility Vest / Slate', subtitle: 'February 2026 · 180 units', text: 'Our first cut-and-sew piece. Ten units held back for the archive and the rest gone in eleven minutes of general sale.', image: img('ec-drop-a12'), badge: 'Sold out', href: '#' },
        { title: 'Drop 011 — Terrace Low / Ink', subtitle: 'December 2025 · 400 pairs', text: 'The first Terrace. Same last, darker suede, and the pair that taught us to publish a sizing note before the raffle rather than after it.', image: img('ec-drop-a11'), badge: 'Sold out', href: '#' },
      ] }),
      b('faq', 'faq', { title: 'Raffle rules, plainly', items: [
        { question: 'Can I enter more than once?', answer: 'No. One entry per person across all payment methods and addresses. We deduplicate on card fingerprint, address and phone, and duplicate entries are all voided rather than just the extras.' },
        { question: 'Do bots help?', answer: 'They do not. The draw is random rather than first-come, so refreshing at 9:00:00 gains you nothing. Automated entries are removed when we spot them.' },
        { question: 'Will there be a restock?', answer: 'Never. 400 pairs is 400 pairs. Drop 011 sold out in 2025, has not been reissued, and will not be.' },
        { question: 'Can I change size after winning?', answer: 'Only into a size still unclaimed after the 24-hour window closes. Email us and we will tell you what is left.' },
        { question: 'Can I enter from overseas?', answer: 'Yes — we ship worldwide by DHL, calculated at checkout. Duties are not prepaid outside Australia and New Zealand.' },
      ] }),
      b('socials', 'social-links', { title: 'Drop alerts', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'instagram', href: '#', label: '@blok22' },
        { platform: 'tiktok', href: '#', label: '@blok22' },
        { platform: 'discord', href: '#', label: 'BLOK 22 server' },
        { platform: 'youtube', href: '#', label: 'BLOK 22 films' },
      ] }),
      b('footer', 'footer', { brand: 'BLOK 22', tagline: 'Limited runs. Collingwood, Melbourne.', links: [{ label: 'Calendar', href: '#calendar' }, { label: 'Raffle rules', href: '#faq' }, { label: 'Archive', href: '#archive' }], copyright: '© BLOK 22 Pty Ltd' }),
    ],
  }),

  tpl({
    id: 'ecommerce-handmade',
    vertical: 'ecommerce',
    label: 'Handmade — Maker catalogue',
    description: 'A one-person ceramics and textiles maker whose stock list, commission rates and market dates are the page.',
    tags: ['handmade', 'crafts', 'local', 'one-pager', 'light'],
    layout: 'catalogue',
    preset: 'ocean',
    meta: { title: 'Wren & Thistle — Handmade ceramics', description: 'Wheel-thrown stoneware and plant-dyed linen from a workshop in Hebden Bridge, West Yorkshire.', lang: 'en', favicon: '🏺' },
    blocks: [
      b('nav', 'nav', { brand: 'Wren & Thistle', sticky: true, links: [{ label: 'In stock', href: '#stock' }, { label: 'Commissions', href: '#commissions' }, { label: 'Markets', href: '#markets' }, { label: 'Workshop', href: '#find' }], cta: { label: 'Commission a piece', href: '#enquire' } }),
      b('hero', 'hero', { eyebrow: 'Hebden Bridge, West Yorkshire', headline: 'Everything here was made by one pair of hands', subhead: 'Wheel-thrown stoneware and plant-dyed linen. Stock is genuinely limited — when a piece is gone the listing comes down rather than turning into a pre-order.', align: 'left', minHeight: 'sm', overlay: 'none', cta: { label: 'See what is in stock', href: '#stock' } }),
      b('stock', 'product', { title: 'In stock today', subtitle: 'Updated every Friday once the kiln comes down. Nine pieces left from the July firing.', columns: 3, items: [
        { name: 'Speckled dinner plate — 26cm', description: 'Toasted stoneware, matte oatmeal glaze. Dishwasher and oven safe. Four left.', price: '£38', image: img('ec-craft-plate'), ctaLabel: 'Add to basket', ctaHref: '#' },
        { name: 'Tall mug — 350ml', description: 'Deep sea-green glaze that pools darker at the foot. Two left.', price: '£26', image: img('ec-craft-mug'), badge: 'Two left', ctaLabel: 'Add to basket', ctaHref: '#' },
        { name: 'Serving bowl — 30cm', description: 'A one-off. Slightly oval because it moved in the kiln and I liked it better.', price: '£92', image: img('ec-craft-bowl'), badge: 'One-off', ctaLabel: 'Add to basket', ctaHref: '#' },
        { name: 'Woad-dyed linen napkins — set of 4', description: 'Dyed with woad grown on the allotment behind the workshop. Fades beautifully.', price: '£44', image: img('ec-craft-napkins'), ctaLabel: 'Add to basket', ctaHref: '#' },
        { name: 'Seconds box', description: 'Glaze pinholes, warped rims, wrong colours. Perfectly usable, sold blind, three pieces.', price: '£30', was: '£75', image: img('ec-craft-seconds'), badge: 'Seconds', ctaLabel: 'Add to basket', ctaHref: '#' },
        { name: 'Gift voucher', description: 'Any amount, no expiry date, sent as a printed card rather than a code.', price: 'from £20', image: img('ec-craft-voucher'), ctaLabel: 'Choose an amount', ctaHref: '#' },
      ] }),
      b('commissions', 'services-catalogue', { title: 'Commissions', subtitle: 'I take on roughly one commission a month. Lead time is currently ten to twelve weeks.', items: [
        { name: 'Dinner set for four', description: 'Sixteen pieces: plates, side plates, bowls, mugs. Your glaze from six options. 40% deposit to start.', price: 'from £480', ctaLabel: 'Enquire', ctaHref: '#enquire' },
        { name: 'Single statement piece', description: 'A vase, platter or lidded jar up to 45cm. We sketch it together on a call first.', price: 'from £180', ctaLabel: 'Enquire', ctaHref: '#enquire' },
        { name: 'Wedding favours', description: 'Small dishes or bud vases, 30 units minimum, twelve weeks’ notice. Names impressed into the base if you want.', price: '£14 per unit', ctaLabel: 'Enquire', ctaHref: '#enquire' },
        { name: 'Restaurant service', description: 'Trade pricing on runs over 60 pieces, with replacements at the same rate for three years.', price: 'on request', ctaLabel: 'Enquire', ctaHref: '#enquire' },
      ] }),
      b('story', 'about', { eyebrow: 'The workshop', title: 'A former weaving shed, two wheels, one kiln', body: 'I trained as a textile conservator and came to clay sideways, in an evening class in Halifax in 2014, which I attended largely to get out of the house. Eleven years later the wheel has taken over the whole ground floor and the loom has been pushed into the corner, though it still earns its keep for the linen. Everything is thrown, trimmed, bisque-fired, glazed and fired again here — no outsourcing and no white-labelled blanks. The kiln holds about eighty pieces, takes fourteen hours to fire and two days to cool, which is why stock arrives in lumps on a Friday rather than trickling in. If something is listed, it exists and is sitting on the shelf behind me.', image: img('ec-craft-workshop'), imageAlt: 'Potter’s wheel and shelves of unglazed stoneware in a stone workshop', imageSide: 'right' }),
      b('markets', 'timeline', { title: 'Where to find me in person', items: [
        { date: 'Sat 1 Aug', title: 'Hebden Bridge Handmade Market', text: 'St George’s Square, 9am–4pm. Full stock plus seconds, and the only place I sell the very large platters, because posting them is a nightmare.' },
        { date: 'Sun 16 Aug', title: 'Saltaire Makers Fair', text: 'Victoria Hall, 10am–5pm. Card and cash. I usually sell out of mugs by lunchtime, so come early if that is what you are after.' },
        { date: '12–13 Sep', title: 'Yorkshire Craft Weekender, Leeds', text: 'Corn Exchange, both days 10am–6pm. Throwing demonstration at 2pm on the Saturday.' },
        { date: '27–29 Nov', title: 'Winter Open Studio', text: 'The workshop itself, 11am–5pm. Mulled wine, everything out on the tables, and the seconds bin at its most generous.' },
      ] }),
      b('words', 'testimonials', { title: 'From customers', items: [
        { quote: 'We commissioned a dinner set for our wedding and two years on it is what we eat off every single day. Two chips, both my fault, both replaced at cost.', author: 'Ruth and Femi', role: 'Commission, 2024' },
        { quote: 'I bought a seconds box for someone who is very hard to buy for. They now message me photographs of their breakfast.', author: 'Aidan McCarrick', role: 'Saltaire Makers Fair' },
        { quote: 'The napkins have been washed maybe forty times and the woad has faded into something better than it started as. Exactly as promised.', author: 'Helen T.', role: 'Online order' },
      ] }),
      b('find', 'hours', { title: 'Workshop opening', timezone: 'Europe/London', note: 'The workshop is up a steep cobbled lane with no parking outside — the Old Gate car park is a four-minute walk. Firing days are marked closed because I cannot hear the door over the extractor.', days: [
        { day: 'mon', closed: true },
        { day: 'tue', open: '10:00', close: '16:00' },
        { day: 'wed', open: '10:00', close: '16:00' },
        { day: 'thu', closed: true },
        { day: 'fri', open: '10:00', close: '17:00' },
        { day: 'sat', open: '10:00', close: '17:00' },
        { day: 'sun', closed: true },
      ] }),
      b('map', 'map', { query: 'Hebden Bridge, West Yorkshire HX7', zoom: 15, height: 340, label: 'Wren & Thistle workshop, Hebden Bridge' }),
      b('enquire', 'contact-form', { title: 'Commission enquiry', intro: 'Tell me roughly what you have in mind and I will come back within three working days with a price, a lead time, and an honest answer about whether I am the right maker for it.', submitLabel: 'Send enquiry', successMessage: 'Thank you — I read every one of these myself and will reply within three working days.', fields: [
        { name: 'name', label: 'Your name', type: 'text', required: true },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'you@example.com', required: true },
        { name: 'kind', label: 'What sort of commission', type: 'select', required: true, options: ['Dinner set', 'Single statement piece', 'Wedding favours', 'Restaurant service', 'Something else'] },
        { name: 'when', label: 'When do you need it by', type: 'text', placeholder: 'e.g. before Christmas, or no rush' },
        { name: 'detail', label: 'Tell me about it', type: 'textarea', placeholder: 'Colours, sizes, how it will be used, anything you have seen that you liked', required: true },
      ] }),
      b('footer', 'footer', { brand: 'Wren & Thistle', tagline: 'Wheel-thrown stoneware, Hebden Bridge.', links: [{ label: 'In stock', href: '#stock' }, { label: 'Commissions', href: '#commissions' }, { label: 'Markets', href: '#markets' }], copyright: '© Wren & Thistle' }),
    ],
  }),

  tpl({
    id: 'ecommerce-digital-downloads',
    vertical: 'ecommerce',
    label: 'Digital downloads — Library',
    description: 'A downloads store shaped like an app: tab-bar chrome, a signed-in library, licences and instant delivery.',
    tags: ['digital', 'downloads', 'mobile-first', 'dark', 'b2b'],
    layout: 'app',
    preset: 'midnight',
    meta: { title: 'Kitwork — Templates & assets', description: 'Fonts, Figma kits, LUTs and Notion templates. Buy once, download forever, commercial licence included.', lang: 'en', favicon: '📦' },
    blocks: [
      b('shell', 'app-shell', { brand: 'Kitwork', tabs: [
        { label: 'Store', href: '#catalogue', icon: '🛒' },
        { label: 'Library', href: '#library', icon: '📚' },
        { label: 'Licence', href: '#licence', icon: '📄' },
        { label: 'Account', href: '#account', icon: '👤' },
      ] }),
      b('hero', 'hero-app', { headline: 'Buy once. Download forever.', subhead: 'Every purchase lands in your library in under ten seconds, re-downloadable on any device, with updates free for life. No subscription, no seat counting, no asset that expires.', installLabel: 'Browse the store', installHref: '#catalogue', screenshots: [
        { src: img('ec-dl-shot-library'), alt: 'Library screen showing purchased asset packs' },
        { src: img('ec-dl-shot-detail'), alt: 'Product detail screen with file list and licence' },
        { src: img('ec-dl-shot-updates'), alt: 'Update notifications for previously purchased files' },
      ] }),
      b('find', 'search', { layout: 'bar', label: 'Search 1,240 files', placeholder: 'Try “brutalist poster”, “Figma dashboard”, “VHS LUT”', buttonLabel: 'Search', name: 'q', align: 'center' }),
      b('catalogue', 'product', { title: 'This week in the store', subtitle: 'Prices in USD. Every file includes the extended commercial licence at no extra cost.', columns: 3, items: [
        { name: 'Grotesk Variable — 8 weights', description: 'Variable OTF and WOFF2, 890 glyphs, Latin Extended and Cyrillic. Desktop, web and app licence.', price: '$79', image: img('ec-dl-font'), badge: 'New', ctaLabel: 'Buy and download', ctaHref: '#' },
        { name: 'Dashboard Kit for Figma', description: '128 components, 42 screens, full variable-based theming with light and dark already wired.', price: '$59', was: '$89', image: img('ec-dl-figma'), badge: 'Updated v4.2', ctaLabel: 'Buy and download', ctaHref: '#' },
        { name: 'Halide 12 — cinematic LUT pack', description: 'Twelve .cube LUTs at 33 and 65 point, plus Rec.709 and Log conversion notes.', price: '$34', image: img('ec-dl-luts'), ctaLabel: 'Buy and download', ctaHref: '#' },
        { name: 'Notion Studio OS', description: 'Client, project and invoicing databases with the relations already built. A duplicate link, not a PDF.', price: '$29', image: img('ec-dl-notion'), badge: 'Best seller', ctaLabel: 'Buy and download', ctaHref: '#' },
        { name: 'Riso Texture Library', description: '240 scanned paper and ink textures at 4000px, PNG with transparency plus layered PSD.', price: '$45', image: img('ec-dl-textures'), ctaLabel: 'Buy and download', ctaHref: '#' },
        { name: 'Everything bundle', description: 'All 41 current products plus everything released in the next twelve months.', price: '$399', was: '$1,240', image: img('ec-dl-bundle'), badge: 'Save 68%', ctaLabel: 'Get the bundle', ctaHref: '#' },
      ] }),
      b('library', 'feed', { title: 'Your library', layout: 'list', items: [
        { title: 'Dashboard Kit for Figma', subtitle: 'Purchased 4 March 2026 · v4.2 available', text: 'Version 4.2 adds 14 chart components and rebuilds the tables on auto-layout. Free update — your original licence key still applies.', badge: 'Update ready', href: '#account' },
        { title: 'Halide 12 — cinematic LUT pack', subtitle: 'Purchased 19 January 2026 · v1.0', text: 'Downloaded three times. Files stay available indefinitely; there is no download cap and no expiring link.', badge: 'Up to date', href: '#account' },
        { title: 'Notion Studio OS', subtitle: 'Purchased 2 November 2025 · v3.1', text: 'Duplicate link re-issued on 8 February after you changed workspace. Ask any time and we will re-issue again.', badge: 'Up to date', href: '#account' },
      ] }),
      b('account', 'auth', { mode: 'signin', title: 'Sign in to your library', providers: [{ label: 'Continue with Google', provider: 'google' }, { label: 'Continue with GitHub', provider: 'github' }], showEmail: true }),
      b('why', 'features', { title: 'Why buying here is different', columns: 4, items: [
        { icon: '⚡', title: 'Instant delivery', text: 'Files are in your library before the payment email arrives.' },
        { icon: '🔁', title: 'Free updates for life', text: 'v4 of something you bought at v1 costs nothing.' },
        { icon: '📄', title: 'One extended licence', text: 'Client work, products you sell, unlimited end users. No upgrade tier.' },
        { icon: '💸', title: 'Refunds without a fight', text: 'Fourteen days, asked once why, refunded either way.' },
      ] }),
      b('licence', 'legal', { title: 'Licence and policies', align: 'start', separator: '·', documents: [
        { label: 'Licence', title: 'Kitwork Extended Commercial Licence', content: 'One purchase covers you and anyone working for you, on unlimited personal and commercial projects, including work you deliver to clients and products you sell to end users. You may modify the files freely and you do not need to credit us. You may not resell, redistribute or sublicense the files themselves — the assets as assets — or include them in a competing template or asset marketplace. Fonts may be embedded in apps, websites, PDFs and video. There is no page-view cap, no seat count and no annual renewal. The licence does not expire, including if you stop being a customer or if this store closes.' },
        { label: 'Refunds', title: 'Refund policy', content: 'Digital files are refundable within fourteen days of purchase. Email support with your order number and we will process it within two working days, back to the original payment method. We ask once what went wrong, because it is usually something we can fix, but the refund does not depend on your answer. Bundles are refundable in full within the same window; we do not pro-rate by how many files you downloaded.' },
        { label: 'Privacy', title: 'What we store', content: 'Your email address, your purchase history and your download log. Payments are processed by Stripe and we never see your card details. We do not sell or share customer data, and we run no third-party advertising or analytics trackers on this site. Ask us to delete your account and we do it within seven days, keeping only the invoice records tax law requires us to keep.' },
      ] }),
      b('faq', 'faq', { title: 'Common questions', items: [
        { question: 'Can I use these for client work?', answer: 'Yes. The extended licence covers unlimited client projects, including projects where the client is a large company. You do not need a second copy per client.' },
        { question: 'What if I lose the files?', answer: 'Sign in and download again. There is no cap on downloads, no expiring link and no re-purchase. Files from 2019 are still there.' },
        { question: 'Do you do team pricing?', answer: 'The licence already covers everyone at your company, so a team of forty buys one copy. If procurement needs an invoice and a signed licence rather than a card payment, email us and we will send both.' },
        { question: 'Are updates really free?', answer: 'Really. The Figma kit has shipped four major versions since 2023, and everyone who bought v1 has v4.2 sitting in their library.' },
      ] }),
      b('install', 'install-prompt', { title: 'Add Kitwork to your home screen', body: 'Your library works offline once installed, so downloaded files stay reachable on a plane.', actionLabel: 'Install', position: 'bottom-right', tone: 'info', delayMs: 8000, dismissible: true, rememberDismiss: true, platforms: ['ios-safari', 'android', 'desktop-chrome'] }),
      b('footer', 'footer', { brand: 'Kitwork', tagline: 'Buy once, download forever.', links: [{ label: 'Store', href: '#catalogue' }, { label: 'Licence', href: '#licence' }, { label: 'Support', href: '#faq' }], copyright: '© Kitwork Digital LLC' }),
    ],
  }),
];
