/**
 * `education` starter templates — tutoring, instruments, languages, driving, code,
 * coaching and early years, from a one-person studio to a 16-week bootcamp.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const educationTemplates: Template[] = [
  tpl({
    id: 'education-academy',
    vertical: 'education',
    label: 'Tutoring Academy — Classic',
    description: 'A one-to-one tutoring service selling confidence as much as grades, with per-lesson pricing.',
    tags: ['tutoring', 'pricing', 'family', 'faq', 'local'],
    layout: 'classic',
    preset: 'ocean',
    meta: { title: 'Bright Minds — Tutoring & Coaching', description: 'One-to-one tutoring that builds confidence, not just grades.', lang: 'en', favicon: '🎓' },
    blocks: [
      b('nav', 'nav', { brand: 'Bright Minds', sticky: true, links: [{ label: 'Subjects', href: '#subjects' }, { label: 'How it works', href: '#how' }, { label: 'Pricing', href: '#pricing' }], cta: { label: 'Book a free trial', href: '#contact' } }),
      b('hero', 'hero', { eyebrow: 'Ages 8–18', headline: 'Confidence that shows up on results day', subhead: 'Personal tutoring in maths, English, and science — online or in person.', align: 'left', minHeight: 'md', image: img('edu-hero'), overlay: 'light', cta: { label: 'Book a free trial lesson', href: '#contact' } }),
      b('subjects', 'features', { title: 'What we teach', columns: 3, items: [
        { icon: '➗', title: 'Maths', text: 'KS2 to A-level, exam boards covered.' },
        { icon: '📖', title: 'English', text: 'Reading, writing, and comprehension.' },
        { icon: '🔬', title: 'Science', text: 'Biology, chemistry, and physics.' },
      ] }),
      b('how', 'steps', { title: 'How it works', items: [
        { title: 'Free trial lesson', text: 'We assess, listen, and set a plan together.' },
        { title: 'Weekly sessions', text: 'A matched tutor, same time each week.' },
        { title: 'Progress reports', text: 'Short written updates after every block.' },
      ] }),
      b('pricing', 'pricing', { title: 'Simple pricing', subtitle: 'Pay per lesson. No contracts.', plans: [
        { name: 'Primary', price: '£28', period: '/lesson', features: ['KS1–KS2', '55 minutes', 'Online or in person'], ctaLabel: 'Enquire', ctaHref: '#contact' },
        { name: 'Secondary', price: '£34', period: '/lesson', features: ['KS3–GCSE', '55 minutes', 'Exam-board aligned'], ctaLabel: 'Enquire', ctaHref: '#contact', featured: true },
        { name: 'A-level', price: '£42', period: '/lesson', features: ['Specialist tutors', '60 minutes', 'Past-paper focus'], ctaLabel: 'Enquire', ctaHref: '#contact' },
      ] }),
      b('faq', 'faq', { title: 'Questions, answered', items: [
        { question: 'Online or in person?', answer: 'Both — most families mix the two week to week.' },
        { question: 'Do you follow our exam board?', answer: 'Yes. Tell us the board and we align to its spec.' },
      ] }),
      b('reviews', 'testimonials', { title: 'Parents & students', items: [
        { quote: 'Went from a 4 to a 7 in maths, but the confidence was the real win.', author: 'The Osei family', role: 'GCSE' },
        { quote: 'My tutor made me actually enjoy English. Never thought I’d say that.', author: 'Ruby', role: 'Student' },
      ] }),
      b('cta', 'cta', { headline: 'The first lesson is free', subhead: 'See if it’s a fit — no cost, no commitment.', background: 'primary', button: { label: 'Book a free trial', href: '#contact' } }),
      b('contact', 'contact-details', { title: 'Get in touch', address: 'Online & across Manchester', phone: '+44 161 000 0000', email: 'hello@brightminds.tutoring', hours: 'Mon–Fri 9:00–19:00' }),
      b('footer', 'footer', { brand: 'Bright Minds', tagline: 'Tutoring & coaching.', links: [{ label: 'Subjects', href: '#subjects' }, { label: 'Pricing', href: '#pricing' }], copyright: '© Bright Minds' }),
    ],
  }),

  tpl({
    id: 'education-music-studio',
    vertical: 'education',
    label: 'Music Teacher — Studio Profile',
    description: 'A single piano and theory teacher presented as a person: training, repertoire, rates and a booking form.',
    tags: ['music', 'one-pager', 'booking', 'portfolio', 'video'],
    layout: 'profile',
    preset: 'midnight',
    meta: { title: 'Ines Bellweather — Piano & Theory Studio', description: 'Piano, theory and audition prep in Southeast Portland — beginners through conservatory applicants.', lang: 'en', favicon: '🎹' },
    blocks: [
      b('profile', 'profile-header', {
        name: 'Ines Bellweather',
        headline: 'Piano & music theory — beginners to conservatory prep',
        location: 'Southeast Portland, OR',
        avatar: img('edu-piano-portrait'),
        summary: 'Fifteen years of teaching out of a converted garage studio on SE Clinton. Two students a year go on to a music degree; the rest just keep playing, which I count as the bigger win.',
        contacts: [
          { type: 'email', value: 'ines@bellweatherpiano.com', label: 'Email' },
          { type: 'phone', value: '+1 (503) 555 0147', label: 'Studio line' },
          { type: 'location', value: 'SE Clinton St, Portland, OR 97202' },
        ],
        showShare: true,
        shareLabel: 'Share this studio',
      }),
      b('lessons', 'services-catalogue', {
        title: 'Lessons & rates',
        subtitle: 'Billed monthly, four lessons to a month. Sheet music is included.',
        items: [
          { name: 'First 30 minutes', description: 'A trial lesson at the piano. No obligation, and I will say so if I am not the right teacher for you.', price: 'Free', ctaLabel: 'Book it', ctaHref: '#book' },
          { name: 'Weekly 30-minute lesson', description: 'Ages 6–11, or absolute beginners of any age.', price: '$140 / month' },
          { name: 'Weekly 45-minute lesson', description: 'Intermediate players working through graded repertoire.', price: '$195 / month' },
          { name: 'Weekly 60-minute lesson', description: 'Advanced repertoire, accompaniment work, or theory alongside playing.', price: '$255 / month' },
          { name: 'Audition & jury prep', description: 'Six-week intensive for college applications, including a recorded mock jury.', price: '$480 block' },
          { name: 'Adult return-to-piano', description: 'For anyone who quit at eleven and has regretted it since. Evenings available.', price: '$50 / lesson' },
        ],
      }),
      b('teaching', 'experience', {
        title: 'Training & teaching',
        items: [
          { role: 'Independent piano teacher', org: 'Bellweather Piano Studio', period: '2011 — present', location: 'Portland, OR', summary: 'A roster of 24 students, capped deliberately so nobody gets a rushed lesson.', bullets: ['Annual spring recital at Alberta Abbey', 'Prepared 31 students for MTNA evaluations', 'Certified Teacher of Music, MTNA'] },
          { role: 'Staff accompanist', org: 'Rose City Youth Chorus', period: '2009 — 2016', location: 'Portland, OR', bullets: ['Rehearsal and concert accompaniment for three ensembles'] },
          { role: 'BMus, Piano Performance', org: 'University of Oregon', period: '2005 — 2009', location: 'Eugene, OR' },
        ],
      }),
      b('what', 'skills', {
        title: 'What we work on',
        display: 'bars',
        groups: [
          { name: 'At the keyboard', items: [{ label: 'Classical repertoire', level: 5 }, { label: 'Sight-reading', level: 5 }, { label: 'Jazz voicings', level: 3 }, { label: 'Accompaniment', level: 4 }] },
          { name: 'Away from it', items: [{ label: 'Theory & harmony', level: 5 }, { label: 'Ear training', level: 4 }, { label: 'Composition basics', level: 3 }] },
        ],
      }),
      b('recital', 'video', {
        provider: 'youtube',
        src: 'kQ7tR2vLm9A',
        title: 'Spring recital 2026 — student performances',
        poster: img('edu-piano-recital'),
        caption: 'Eleven students, one slightly out-of-tune upright at Alberta Abbey, zero disasters.',
      }),
      b('praise', 'testimonials', {
        title: 'From students and parents',
        items: [
          { quote: 'Our daughter practises without being asked now. I genuinely did not think that was a thing that happened.', author: 'Marisol Ocampo', role: 'Parent, third year' },
          { quote: 'I came back to piano at 41 after twenty years away. Ines started me on Debussy in month four and never once made me feel behind.', author: 'Wes T.', role: 'Adult student' },
          { quote: 'The mock jury was harder than the real one. That was the point.', author: 'Devon Aluko', role: 'Now studying at Oberlin' },
        ],
      }),
      b('book', 'booking', {
        title: 'Book a lesson slot',
        intro: 'Studio hours are Tuesday to Saturday afternoons. I reply the same evening, or the next morning if it is a teaching night.',
        serviceLabel: 'What are you after?',
        services: [
          { name: 'Free 30-minute trial', duration: '30 min', price: 'Free' },
          { name: 'Weekly 30-minute lesson', duration: '30 min', price: '$140 / month' },
          { name: 'Weekly 45-minute lesson', duration: '45 min', price: '$195 / month' },
          { name: 'Weekly 60-minute lesson', duration: '60 min', price: '$255 / month' },
          { name: 'Audition & jury prep', duration: '6 weeks', price: '$480' },
        ],
        askPhone: true,
        askNotes: true,
        notesLabel: 'Who is the lesson for, and where are they up to?',
        submitLabel: 'Request a slot',
        successMessage: 'Got it — I will confirm a time within a day.',
      }),
      b('social', 'social-links', {
        title: 'Elsewhere',
        layout: 'row',
        variant: 'labeled',
        align: 'center',
        links: [
          { platform: 'youtube', href: '#', label: 'Recital archive' },
          { platform: 'instagram', href: '#', label: '@bellweatherpiano' },
          { platform: 'email', href: 'mailto:ines@bellweatherpiano.com', label: 'Email the studio' },
        ],
      }),
      b('footer', 'footer', { brand: 'Bellweather Piano Studio', tagline: 'Piano & theory, Southeast Portland.', links: [{ label: 'Rates', href: '#lessons' }, { label: 'Book', href: '#book' }], copyright: '© Ines Bellweather' }),
    ],
  }),

  tpl({
    id: 'education-language-school',
    vertical: 'education',
    label: 'Language School — Course Catalogue',
    description: 'A city language school where the course list is the whole page, split by level with an enquiry form.',
    tags: ['languages', 'courses', 'catalogue', 'reviews', 'b2c'],
    layout: 'catalogue',
    preset: 'forest',
    meta: { title: 'Aula Ronda — Spanish & Catalan in Barcelona', description: 'Small-group Spanish and Catalan courses in the Eixample, from A1 to exam preparation.', lang: 'en', favicon: '🗣️' },
    blocks: [
      b('nav', 'nav', { brand: 'Aula Ronda', sticky: true, links: [{ label: 'Courses', href: '#courses' }, { label: 'Levels', href: '#levels' }, { label: 'Reviews', href: '#reviews' }, { label: 'FAQ', href: '#faq' }], cta: { label: 'Enquire', href: '#enquire' } }),
      b('hero', 'hero', { eyebrow: 'Carrer de Mallorca, Eixample', headline: 'Eight students to a class. Never nine.', subhead: 'Spanish and Catalan courses that start every month, taught by people who live here and teach the language people actually speak.', align: 'left', minHeight: 'sm', overlay: 'none', cta: { label: 'See the course list', href: '#courses' } }),
      b('courses', 'services-catalogue', {
        title: 'Courses starting this term',
        subtitle: 'All prices include materials and the end-of-course certificate. Enrolment closes a week before each start date.',
        items: [
          { name: 'Spanish A1 — Intensive', description: '20 hours a week for four weeks. Mornings, 9:30–13:30. Next start: 6 October.', price: '€680', ctaLabel: 'Enquire', ctaHref: '#enquire' },
          { name: 'Spanish A2–B1 — Evening', description: 'Two evenings a week for ten weeks, 19:00–21:00. For people with jobs and no spare daylight.', price: '€395', ctaLabel: 'Enquire', ctaHref: '#enquire' },
          { name: 'Spanish B2 — Conversation lab', description: 'One session a week, entirely spoken. Debate, negotiation, and arguing about football.', price: '€210', ctaLabel: 'Enquire', ctaHref: '#enquire' },
          { name: 'Catalan for residents', description: 'Ten weeks of practical Catalan for paperwork, neighbours and school runs. Subsidised places available.', price: '€260', ctaLabel: 'Enquire', ctaHref: '#enquire' },
          { name: 'DELE exam preparation', description: 'Eight weeks aimed squarely at the B2 or C1 paper, with two full mock exams.', price: '€430', ctaLabel: 'Enquire', ctaHref: '#enquire' },
          { name: 'Business Spanish', description: 'In-company or in-school, six weeks. Meetings, email register, and the phone call nobody enjoys.', price: 'From €1,150 per group', ctaLabel: 'Enquire', ctaHref: '#enquire' },
        ],
      }),
      b('levels', 'tabs', {
        items: [
          { label: 'A1–A2', text: 'You start from nothing, or nearly. By the end of A2 you can order lunch, open a bank account, and follow a conversation aimed at you. Roughly 160 classroom hours across the two levels, and we do not do the subjunctive scare-mongering — it simply is not needed yet.' },
          { label: 'B1–B2', text: 'The plateau level, and the one people give up on. We break it with heavy speaking loads: at B1 you narrate and explain, at B2 you argue and hedge. B2 is also the level most residency and university applications ask for, so this is where the DELE preparation course pairs in.' },
          { label: 'C1', text: 'Register, irony, regional variation, and writing that does not read like a translation. Small groups only — usually four to six — and taught by Núria, who marks essays with a brutality students later thank her for.' },
          { label: 'Catalan', text: 'A separate track, not an afterthought. Taught for people who live here and would like to stop apologising in shops. A2 Catalan is achievable in a single term if you already have Spanish above B1.' },
        ],
      }),
      b('numbers', 'stats', {
        title: 'The school in numbers',
        columns: 4,
        items: [
          { value: '8', label: 'Students per class, maximum' },
          { value: '11', label: 'Teachers, all resident in Barcelona' },
          { value: '94', label: 'DELE pass rate', suffix: '%' },
          { value: '2009', label: 'Teaching since' },
        ],
      }),
      b('reviews', 'reviews', {
        title: 'What students say',
        average: '4.8',
        count: '312 reviews',
        source: 'Google',
        items: [
          { rating: 5, quote: 'I did four weeks of the A1 intensive and could hold a real conversation with my flatmate’s grandmother by the end of it. Slowly, but really.', author: 'Tomas Lindqvist', date: 'May 2026', source: 'google' },
          { rating: 5, quote: 'Núria’s C1 class ruined me for other language schools. She corrects everything and explains why, which nobody else had bothered to do.', author: 'Amara Diallo', date: 'March 2026', source: 'google' },
          { rating: 4, quote: 'Excellent teaching, cramped classrooms in the August heat. Bring a fan and take the evening slot.', author: 'Reuben O’Farrell', date: 'August 2025', source: 'google' },
        ],
      }),
      b('faq', 'faq', {
        title: 'Before you enrol',
        items: [
          { question: 'How do I know my level?', answer: 'Take the free 20-minute placement test at the school, or online if you are not in the city yet. We place from the spoken part, not the grammar score.' },
          { question: 'Can you help with a student visa?', answer: 'For courses of 20 hours a week or more we issue the enrolment letter the consulate asks for. We cannot promise you an appointment date — nobody can.' },
          { question: 'What if I miss classes?', answer: 'You can sit in on the same session in another group that week, space permitting. Beyond four missed sessions we would rather move you to the next intake than have you struggle.' },
          { question: 'Do you teach online?', answer: 'Only the conversation lab and private tuition. The group courses lose too much online, so we stopped pretending otherwise.' },
        ],
      }),
      b('enquire', 'contact-form', {
        title: 'Enquire about a course',
        intro: 'Tell us roughly where you are and what you need the language for. We answer within one working day, in English, Spanish or Catalan.',
        submitLabel: 'Send enquiry',
        successMessage: 'Thanks — we will reply within one working day.',
        fields: [
          { name: 'name', label: 'Your name', type: 'text', required: true, placeholder: 'First and last name' },
          { name: 'email', label: 'Email', type: 'email', required: true, placeholder: 'you@example.com' },
          { name: 'course', label: 'Which course?', type: 'select', required: true, options: ['Spanish A1 — Intensive', 'Spanish A2–B1 — Evening', 'Spanish B2 — Conversation lab', 'Catalan for residents', 'DELE exam preparation', 'Business Spanish', 'Not sure yet'] },
          { name: 'level', label: 'Current level, honestly', type: 'select', options: ['None at all', 'A little (A1)', 'Can get by (A2–B1)', 'Comfortable (B2+)'] },
          { name: 'message', label: 'What do you need the language for?', type: 'textarea', placeholder: 'Work, residency, family, curiosity…' },
        ],
      }),
      b('visit', 'contact-details', { title: 'The school', address: 'Carrer de Mallorca 214, 3r, 08008 Barcelona', phone: '+34 93 000 00 00', email: 'hola@aularonda.es', hours: 'Mon–Thu 9:00–21:00 · Fri 9:00–15:00' }),
      b('footer', 'footer', { brand: 'Aula Ronda', tagline: 'Spanish & Catalan, Eixample, Barcelona.', links: [{ label: 'Courses', href: '#courses' }, { label: 'Levels', href: '#levels' }, { label: 'Enquire', href: '#enquire' }], copyright: '© Aula Ronda SL' }),
    ],
  }),

  tpl({
    id: 'education-driving-school',
    vertical: 'education',
    label: 'Driving Instructor — Minimal',
    description: 'A solo driving instructor with a short page: packages, honest answers, and a phone number.',
    tags: ['driving', 'pricing', 'local', 'mobile-first', 'faq'],
    layout: 'minimal',
    preset: 'sand',
    meta: { title: 'Northside Driving — Dale Mokoena', description: 'Patient, unhurried driving lessons across Melbourne’s northern suburbs. Automatic and manual.', lang: 'en', favicon: '🚗' },
    blocks: [
      b('nav', 'nav', { brand: 'Northside Driving', sticky: false, links: [{ label: 'Packages', href: '#packages' }, { label: 'Questions', href: '#faq' }], cta: { label: 'Call 0491 570 156', href: '#contact' } }),
      b('hero', 'hero', {
        eyebrow: 'Northern suburbs · Automatic & manual',
        headline: 'Nobody has ever been shouted at in this car',
        subhead: 'Dale Mokoena, accredited driving instructor since 2013. Lessons from Coburg to Epping, with pick-up from home, school or work.',
        align: 'left',
        minHeight: 'md',
        image: img('edu-driving-lesson'),
        overlay: 'scrim',
        cta: { label: 'See lesson packages', href: '#packages' },
      }),
      b('packages', 'pricing', {
        title: 'Lesson packages',
        subtitle: 'All prices in AUD and include pick-up and drop-off within 10 km. Test-day car hire is priced separately.',
        plans: [
          { name: 'Single lesson', price: '$75', period: '/ 60 min', features: ['One hour, one-on-one', 'Automatic or manual', 'Pick-up from home or school', 'Logbook hours signed off'], ctaLabel: 'Book by phone', ctaHref: '#contact' },
          { name: 'Ten-lesson pack', price: '$680', period: '/ 10 hours', features: ['Save $70 against singles', 'Book weekly or fortnightly', 'Free 30-minute test-route session', 'Transferable to a sibling'], ctaLabel: 'Book by phone', ctaHref: '#contact', featured: true },
          { name: 'Test day', price: '$260', period: '/ package', features: ['90-minute warm-up lesson', 'Use of my car for the test', 'VicRoads booking checked in advance', 'A debrief either way'], ctaLabel: 'Book by phone', ctaHref: '#contact' },
        ],
      }),
      b('faq', 'faq', {
        title: 'The things people ring up and ask',
        items: [
          { question: 'How many lessons will I need?', answer: 'Most learners who also practise with a parent take between fifteen and twenty-five hours with me. Learners doing all their driving in lessons need closer to forty. I will give you a straight estimate after the second lesson and revise it as we go.' },
          { question: 'Automatic or manual?', answer: 'If you have no particular reason to learn manual, learn automatic — it is faster and cheaper, and converting later is only a few lessons. If you want to drive a ute for work or a hire car overseas, learn manual now.' },
          { question: 'Will you tell me if I am not ready for the test?', answer: 'Yes, plainly, and more than once if needed. I would rather lose a test-day booking than watch you fail on a hook turn.' },
          { question: 'Do you teach nervous or older learners?', answer: 'About a third of my learners are over thirty, and roughly as many are anxious drivers returning after a break. Quiet industrial streets on a Sunday morning are a perfectly respectable place to start.' },
        ],
      }),
      b('cta', 'cta', { headline: 'Ring, text, or leave a voicemail', subhead: 'I answer between lessons and always by the evening.', background: 'primary', button: { label: 'Get in touch', href: '#contact' } }),
      b('contact', 'contact-details', { title: 'Northside Driving', address: 'Coburg, Preston, Reservoir, Epping & surrounds, Melbourne VIC', phone: '0491 570 156', email: 'dale@northsidedriving.com.au', hours: 'Mon–Sat 7:00–19:00 · Sun by arrangement' }),
      b('footer', 'footer', { brand: 'Northside Driving', tagline: 'Accredited driving instructor, Melbourne north.', links: [{ label: 'Packages', href: '#packages' }, { label: 'Questions', href: '#faq' }], copyright: '© Dale Mokoena · VicRoads ADI 41827' }),
    ],
  }),

  tpl({
    id: 'education-bootcamp',
    vertical: 'education',
    label: 'Coding Bootcamp — Bold',
    description: 'A 16-week full-stack bootcamp built around outcomes: cohort dates, curriculum timeline and hiring proof.',
    tags: ['bootcamp', 'long-form', 'pricing', 'dark', 'reviews'],
    layout: 'bold',
    preset: 'midnight',
    meta: { title: 'Kernel Labs — 16-week Full-Stack Bootcamp, Bengaluru', description: 'A full-time, in-person engineering bootcamp with an income-share option and a published placement report.', lang: 'en', favicon: '⌨️' },
    blocks: [
      b('notice', 'announcement-bar', { text: 'Cohort 19 starts 14 September. Twelve of thirty seats left.', linkLabel: 'Apply now', href: '#apply', tone: 'promo', dismissible: true }),
      b('nav', 'nav', { brand: 'Kernel Labs', sticky: true, links: [{ label: 'Curriculum', href: '#curriculum' }, { label: 'Inside a week', href: '#inside' }, { label: 'Tuition', href: '#tuition' }, { label: 'Outcomes', href: '#numbers' }], cta: { label: 'Apply', href: '#apply' } }),
      b('hero', 'hero', {
        eyebrow: 'Cohort 19 · Indiranagar, Bengaluru',
        headline: 'Sixteen weeks. Forty-five hours a week. One portfolio you would actually show someone.',
        subhead: 'Full-time, in-person, and deliberately hard. We publish every placement number, including the ones we are not proud of.',
        align: 'center',
        minHeight: 'lg',
        image: img('edu-bootcamp-floor'),
        overlay: 'dark',
        cta: { label: 'Apply for cohort 19', href: '#apply' },
      }),
      b('numbers', 'stats', {
        title: 'Cohorts 14–18, audited and published',
        columns: 4,
        items: [
          { value: '81', label: 'Placed within 6 months', suffix: '%' },
          { value: '9.4', label: 'Median first salary', prefix: '₹', suffix: 'L' },
          { value: '142', label: 'Graduates to date' },
          { value: '11', label: 'Withdrew mid-course' },
        ],
      }),
      b('curriculum', 'timeline', {
        title: 'The sixteen weeks',
        items: [
          { date: 'Weeks 1–3', title: 'Foundations that usually get skipped', text: 'The command line, git as a mental model rather than four memorised commands, HTTP end to end, and enough data structures to reason about cost.' },
          { date: 'Weeks 4–6', title: 'JavaScript and TypeScript, properly', text: 'Closures, the event loop, async failure modes, and types as design tools. You write a small promise library, because reading about promises is not the same thing.' },
          { date: 'Weeks 7–9', title: 'Back end and data', text: 'Node and Postgres. Schema design, indexes, transactions, and the afternoon where everyone discovers N+1 queries the hard way.' },
          { date: 'Weeks 10–12', title: 'Front end at production scale', text: 'React with real state problems, accessibility from the first commit, and performance budgets you have to defend in review.' },
          { date: 'Weeks 13–15', title: 'Capstone in a team of four', text: 'A brief from a partner company, a real deadline, and code review from a working senior engineer twice a week.' },
          { date: 'Week 16', title: 'Interviews, not "career support"', text: 'System-design practice, salary negotiation, and eight mock interviews with engineers who do not work here.' },
        ],
      }),
      b('inside', 'split', {
        rows: [
          { title: 'A day starts at 9:15 with a code review', text: 'Not a stand-up. Someone puts a pull request on the projector and the room reviews it, including the instructor’s. It is uncomfortable in week one and the single most useful habit you leave with.', image: img('edu-bootcamp-review'), imageAlt: 'A group reviewing code on a large screen' },
          { title: 'Afternoons are pairing, not lecture', text: 'Two people, one keyboard, rotating every forty minutes. Instructors circulate rather than present. Total lecture time across sixteen weeks is under thirty hours.', image: img('edu-bootcamp-pairing'), imageAlt: 'Two people pair programming at one desk' },
          { title: 'Fridays are demo and repair', text: 'Ship whatever the week produced to a room of thirty, then spend the afternoon fixing what the demo exposed. Nobody has ever demoed something that worked perfectly.', image: img('edu-bootcamp-demo'), imageAlt: 'A student demoing a project to a room' },
        ],
      }),
      b('hiring', 'logos', {
        title: 'Graduates now working at',
        items: [
          { src: img('edu-partner-sarvapay'), alt: 'Sarvapay' },
          { src: img('edu-partner-loadstar'), alt: 'Loadstar Freight' },
          { src: img('edu-partner-medhalabs'), alt: 'Medha Health' },
          { src: img('edu-partner-tiffinly'), alt: 'Tiffinly' },
          { src: img('edu-partner-quiltdev'), alt: 'Quilt Developer Tools' },
        ],
      }),
      b('tuition', 'pricing', {
        title: 'Tuition',
        subtitle: 'Three ways to pay. The income share is capped and expires — read the agreement before you sign anything, here or anywhere.',
        plans: [
          { name: 'Upfront', price: '₹3,20,000', period: 'one payment', features: ['₹40,000 saving', 'Refundable in full to end of week 2', 'Laptop loan included', 'Alumni code review for 2 years'], ctaLabel: 'Apply', ctaHref: '#apply' },
          { name: 'Instalments', price: '₹3,60,000', period: '6 payments', features: ['₹60,000 a month for six months', 'No interest, no credit check', 'Refundable pro-rata to week 4', 'Laptop loan included'], ctaLabel: 'Apply', ctaHref: '#apply', featured: true },
          { name: 'Income share', price: '12%', period: 'of salary, 24 months', features: ['Pay nothing until you earn ₹6L', 'Total capped at ₹4,50,000', 'Expires after 4 years regardless', 'Full agreement published on request'], ctaLabel: 'Apply', ctaHref: '#apply' },
        ],
      }),
      b('grads', 'reviews', {
        title: 'Graduates, one year on',
        average: '4.6',
        count: '88 reviews',
        source: 'Course Report',
        items: [
          { rating: 5, quote: 'I had a commerce degree and a support-desk job. Fourteen months later I am on the platform team at a payments company. The capstone got me the interview; the code reviews got me through it.', author: 'Sneha Ravikumar', date: 'Cohort 15', source: 'other' },
          { rating: 4, quote: 'Genuinely brutal pace and I nearly quit in week nine. What I will say is that no employer has ever caught me out on fundamentals since.', author: 'Arjun Pillai', date: 'Cohort 16', source: 'other' },
          { rating: 5, quote: 'They talked me out of the income-share plan and into instalments because it was cheaper for my situation. That is the moment I decided to trust them.', author: 'Fatima Sheikh', date: 'Cohort 17', source: 'other' },
        ],
      }),
      b('faq', 'faq', {
        title: 'Honest answers',
        items: [
          { question: 'Can I keep my job during the course?', answer: 'No. It is forty-five contact hours a week plus homework, in person. People who have tried have failed the course and kept the debt, which is the worst of both.' },
          { question: 'Do I need to know how to code already?', answer: 'You need to have finished a free introductory course and be able to explain a loop and a function in the interview. Complete beginners are welcome; complete beginners who have not tried are not.' },
          { question: 'What happens if I do not get a job?', answer: 'On the income share you simply pay nothing. On upfront or instalments there is no refund after week four — we would rather say that here than in the small print.' },
          { question: 'Is there a remote option?', answer: 'No. Pairing and live code review are the whole method and both degrade badly online. If you cannot be in Indiranagar five days a week, this is not the right course.' },
        ],
      }),
      b('apply', 'cta', { headline: 'Applications for cohort 19 close 29 August', subhead: 'A short written task, then a 45-minute conversation. No whiteboard puzzles.', background: 'accent', button: { label: 'Start an application', href: '#' } }),
      b('footer', 'footer', { brand: 'Kernel Labs', tagline: '16-week full-stack bootcamp · Indiranagar, Bengaluru.', links: [{ label: 'Curriculum', href: '#curriculum' }, { label: 'Tuition', href: '#tuition' }, { label: 'Outcomes', href: '#numbers' }], copyright: '© Kernel Labs Education Pvt Ltd' }),
    ],
  }),

  tpl({
    id: 'education-coach',
    vertical: 'education',
    label: 'Business Coach — Conversational',
    description: 'A business and leadership coach whose page opens with a real discovery-call transcript instead of a pitch.',
    tags: ['coaching', 'b2b', 'remote', 'newsletter', 'one-pager'],
    layout: 'conversational',
    preset: 'mono',
    meta: { title: 'Halloway Coaching — Leadership & business coaching', description: 'Coaching for founders and first-time managers who have outgrown advice from friends.', lang: 'en', favicon: '🧭' },
    blocks: [
      b('nav', 'nav', { brand: 'Halloway Coaching', sticky: true, links: [{ label: 'A real call', href: '#call' }, { label: 'Packages', href: '#packages' }, { label: 'Clients', href: '#clients' }], cta: { label: 'Book a call', href: '#contact' } }),
      b('hero', 'hero', {
        eyebrow: 'Leadership & business coaching · London and online',
        headline: 'Most coaching pages explain what coaching is. Here is a transcript instead.',
        subhead: 'Jo Halloway coaches founders and newly promoted managers. Below is a lightly edited discovery call, shared with the client’s permission.',
        align: 'left',
        minHeight: 'sm',
        overlay: 'none',
        cta: { label: 'Read the call', href: '#call' },
      }),
      b('call', 'chat-thread', {
        title: 'Discovery call, thirty minutes, condensed',
        subtitle: 'A technical co-founder who had just taken over a team of nine. Shared with permission; name changed.',
        participants: [
          { id: 'jo', name: 'Jo Halloway', role: 'agent', avatar: img('edu-coach-portrait') },
          { id: 'client', name: 'Priya', role: 'user' },
        ],
        messages: [
          { from: 'client', time: '10:02', body: [{ kind: 'text', text: 'I think my problem is time management. I am working eleven-hour days and still nothing is finished.' }] },
          { from: 'jo', time: '10:03', body: [{ kind: 'text', text: 'Possibly. Tell me what you did yesterday between nine and one, in order, without editing it to sound reasonable.' }] },
          { from: 'client', time: '10:06', body: [{ kind: 'list', ordered: true, items: [{ label: 'Rewrote a junior engineer’s pull request myself' }, { label: 'Two interviews I had not prepared for' }, { label: 'Answered forty-one Slack messages' }, { label: 'Ten minutes on the roadmap I have owed the board for three weeks' }] }] },
          { from: 'jo', time: '10:07', body: [{ kind: 'text', text: 'Nothing in that list is a time-management problem. Three of the four are things you have not delegated, and the fourth is the only one nobody else in the company can do.' }] },
          { from: 'client', time: '10:09', body: [{ kind: 'text', text: 'I do not think they would do it as well as me. Which I realise is a terrible sentence to say out loud.' }] },
          { from: 'jo', time: '10:11', body: [{ kind: 'text', text: 'It is a very common sentence, and it is usually true for about six weeks. What would it have cost you if that pull request had shipped at eighty per cent of your standard?' }] },
          { from: 'client', time: '10:12', body: [{ kind: 'text', text: 'Honestly? Nothing. It was internal tooling.' }] },
          { from: 'jo', time: '10:14', body: [{ kind: 'text', text: 'Then that is where we start. Not a calendar system — a list of what only you can do, and a plan for handing over everything else, with the mistakes budgeted for in advance.' }, { kind: 'buttons', items: [{ label: 'Book a discovery call', href: '#contact' }, { label: 'See packages', href: '#packages' }] }] },
        ],
      }),
      b('packages', 'pricing', {
        title: 'How the work is structured',
        subtitle: 'Sessions are 60 minutes, online or in person in central London. The first call is free and has no pitch at the end of it.',
        plans: [
          { name: 'Fortnightly', price: '£320', period: '/ session', features: ['Twelve sessions over six months', 'Email support between sessions', 'Written summary after each call', 'Cancel with two weeks’ notice'], ctaLabel: 'Enquire', ctaHref: '#contact' },
          { name: 'Intensive', price: '£2,400', period: '/ 6 weeks', features: ['Weekly sessions for six weeks', 'For a specific transition or crunch', 'Stakeholder interviews included', 'Follow-up session at three months'], ctaLabel: 'Enquire', ctaHref: '#contact', featured: true },
          { name: 'Leadership team', price: '£5,800', period: '/ quarter', features: ['Four founders or managers', 'Individual plus group sessions', 'Anonymous 360 feedback round', 'Quarterly written report'], ctaLabel: 'Enquire', ctaHref: '#contact' },
        ],
      }),
      b('clients', 'testimonials', {
        title: 'Clients',
        items: [
          { quote: 'Jo spent the first three sessions dismantling the problem I thought I had. Annoying at the time, correct in hindsight.', author: 'Priya N.', role: 'Co-founder, logistics software' },
          { quote: 'I was promoted over people who had trained me and I handled it badly for four months. Six weeks of the intensive fixed what I had been avoiding since February.', author: 'Callum Reid', role: 'Engineering manager' },
          { quote: 'No frameworks, no worksheets, no talk of my personal brand. Just very good questions and someone who remembers what I said last time.', author: 'Deborah Achebe', role: 'Managing director, design studio' },
        ],
      }),
      b('letter', 'newsletter', {
        title: 'A short letter, every other Thursday',
        intro: 'One idea about managing people, usually under four hundred words, occasionally an admission that I got something wrong. About 2,600 readers.',
        placeholder: 'you@company.com',
        submitLabel: 'Subscribe',
        successMessage: 'You are on the list — the next one goes out Thursday.',
      }),
      b('contact', 'contact-details', { title: 'Book a discovery call', address: 'Online, or a quiet room near Clerkenwell Green, London EC1', phone: '+44 20 7946 0958', email: 'jo@hallowaycoaching.co.uk', hours: 'Calls Tue–Thu 8:00–18:00' }),
      b('footer', 'footer', { brand: 'Halloway Coaching', tagline: 'Leadership and business coaching, London.', links: [{ label: 'Packages', href: '#packages' }, { label: 'The call', href: '#call' }, { label: 'Contact', href: '#contact' }], copyright: '© Jo Halloway' }),
    ],
  }),

  tpl({
    id: 'education-nursery',
    vertical: 'education',
    label: 'Nursery & Preschool — Showcase',
    description: 'A nursery and preschool that persuades with photographs of the rooms, the garden and the shape of the day.',
    tags: ['nursery', 'family', 'gallery', 'local', 'booking'],
    layout: 'showcase',
    preset: 'candy',
    meta: { title: 'Little Acorns — Nursery & Preschool, Sandymount', description: 'A 46-place nursery and preschool in Sandymount, Dublin 4, with a garden, a kitchen, and ECCE places.', lang: 'en', favicon: '🌱' },
    blocks: [
      b('nav', 'nav', { brand: 'Little Acorns', sticky: true, links: [{ label: 'Our rooms', href: '#rooms' }, { label: 'The day', href: '#day' }, { label: 'Team', href: '#team' }, { label: 'Fees', href: '#policies' }], cta: { label: 'Book a visit', href: '#visit' } }),
      b('hero', 'hero', {
        eyebrow: 'Sandymount, Dublin 4 · Ages 1–5',
        headline: 'A garden, a real kitchen, and forty-six children who own the place',
        subhead: 'Little Acorns has been on the Green since 2004. We take ECCE places, we cook everything on site, and you are welcome to look around any Wednesday morning.',
        align: 'center',
        minHeight: 'lg',
        image: img('edu-nursery-garden'),
        overlay: 'scrim',
        cta: { label: 'Book a look around', href: '#visit' },
      }),
      b('day', 'carousel', {
        title: 'A Tuesday, more or less',
        autoplay: false,
        items: [
          { src: img('edu-nursery-arrival'), alt: 'Children hanging up coats in a bright hallway', caption: '8:00 — Arrivals, coats, and the porridge that somehow tastes better here' },
          { src: img('edu-nursery-messy'), alt: 'Toddlers painting at a low table', caption: '9:30 — Messy play. Send them in clothes you have made peace with' },
          { src: img('edu-nursery-outdoor'), alt: 'Children digging in a garden bed', caption: '11:00 — Garden, in all weather bar actual thunder' },
          { src: img('edu-nursery-lunch'), alt: 'Children eating lunch together at a table', caption: '12:15 — Lunch, cooked in our kitchen, eaten at proper tables' },
          { src: img('edu-nursery-story'), alt: 'An adult reading a picture book to a group of children', caption: '14:30 — Story corner, and the quietest ten minutes of the day' },
        ],
      }),
      b('rooms', 'gallery', {
        layout: 'masonry',
        columns: 3,
        gap: 'md',
        lightbox: true,
        items: [
          { src: img('edu-nursery-babies'), alt: 'Baby room with soft mats and low shelving', caption: 'Acorn room · 1–2 years · ratio 1:3' },
          { src: img('edu-nursery-toddlers'), alt: 'Toddler room with construction toys', caption: 'Sapling room · 2–3 years · ratio 1:5' },
          { src: img('edu-nursery-preschool'), alt: 'Preschool room with a writing table', caption: 'Oak room · 3–5 years · ratio 1:8' },
          { src: img('edu-nursery-kitchen'), alt: 'A nursery kitchen with fresh vegetables on the counter' },
          { src: img('edu-nursery-yard'), alt: 'A covered outdoor play area with tricycles' },
          { src: img('edu-nursery-library'), alt: 'A low bookshelf and cushions in a reading nook' },
        ],
      }),
      b('story', 'about', {
        eyebrow: 'Since 2004',
        title: 'Small, and staying small',
        body: 'Little Acorns was started by two early-years teachers who wanted a nursery where children could be outdoors every day and eat food someone had actually cooked. Twenty-two years on we have three rooms, forty-six places, and a waiting list we manage honestly — if we cannot offer you a place, we say so rather than leave you hoping. We follow Aistear and Síolta, we are Tusla-registered, and we take ECCE places for both preschool years. Nine of our thirteen staff have been here longer than five years, which probably tells you more than any policy document could.',
        image: img('edu-nursery-founders'),
        imageAlt: 'Two early-years teachers in a nursery room',
        imageSide: 'left',
      }),
      b('care', 'features', {
        title: 'What is included',
        columns: 4,
        items: [
          { icon: '🥕', title: 'All meals', text: 'Breakfast, hot lunch and two snacks, cooked on site. Allergy plans agreed in writing.' },
          { icon: '🌦️', title: 'Outdoors daily', text: 'Garden and covered yard. We supply the waterproofs and the wellies.' },
          { icon: '📓', title: 'Daily notes', text: 'A short written note each day and a proper developmental review each term.' },
          { icon: '🧷', title: 'Nappies & wipes', text: 'Included in the fee, so there is nothing to remember at eight in the morning.' },
        ],
      }),
      b('team', 'team', {
        title: 'Who looks after your child',
        subtitle: 'Every room lead holds a Level 6 qualification or above. All staff are Garda-vetted and first-aid trained.',
        columns: 3,
        members: [
          { name: 'Aoife Brennan', role: 'Manager & co-founder', photo: img('edu-nursery-staff-one'), bio: 'BA Early Childhood Education. Here since the first day in 2004, and still runs the Wednesday tours personally.' },
          { name: 'Tomás Ó Riain', role: 'Oak room lead (preschool)', photo: img('edu-nursery-staff-two'), bio: 'Level 8 in Early Years Practice. Runs the garden beds and the wildly popular worm project.' },
          { name: 'Grace Adeyemi', role: 'Sapling room lead', photo: img('edu-nursery-staff-three'), bio: 'Level 7, seven years with us. Specialist training in speech and language support.' },
          { name: 'Marta Kowalczyk', role: 'Acorn room lead (babies)', photo: img('edu-nursery-staff-four'), bio: 'Level 6 and an infant-massage qualification. Settles new babies better than anyone we have met.' },
          { name: 'Declan Fitzgerald', role: 'Cook', photo: img('edu-nursery-staff-five'), bio: 'Twelve years in restaurant kitchens, now cooking for forty-six much harder critics.' },
          { name: 'Priya Menon', role: 'Inclusion & AIM coordinator', photo: img('edu-nursery-staff-six'), bio: 'Coordinates Access and Inclusion Model supports and liaises with visiting therapists.' },
        ],
      }),
      b('hours', 'hours', {
        title: 'Opening hours',
        timezone: 'Europe/Dublin',
        note: 'Closed for two weeks at Christmas and on public holidays. Sessional ECCE places run 9:00–12:00.',
        days: [
          { day: 'mon', open: '07:45', close: '18:15' },
          { day: 'tue', open: '07:45', close: '18:15' },
          { day: 'wed', open: '07:45', close: '18:15' },
          { day: 'thu', open: '07:45', close: '18:15' },
          { day: 'fri', open: '07:45', close: '17:30' },
          { day: 'sat', closed: true },
          { day: 'sun', closed: true },
        ],
      }),
      b('where', 'map', { query: 'Sandymount Green, Dublin 4, Ireland', zoom: 16, height: 380, label: 'Little Acorns, 14 Sandymount Green' }),
      b('policies', 'accordion', {
        title: 'Fees, policies and the practical bits',
        items: [
          { heading: 'Fees for 2026', body: 'Full day (7:45–18:15) €1,180 per month. School day (8:30–14:30) €890. Sessional ECCE (9:00–12:00) is free for eligible children during term. The National Childcare Scheme subsidy is applied directly to your invoice — bring your NCS code to the enrolment meeting and we handle the rest.' },
          { heading: 'Settling in', body: 'Three short visits across a week before the first full day, at no charge. A parent or carer stays for the first, stays nearby for the second, and leaves for the third. Some children need six visits instead of three, and that is entirely normal.' },
          { heading: 'Illness', body: 'We ask that children stay home for 48 hours after a temperature above 38°C or any vomiting. We ring you if a child becomes unwell during the day and ask for collection within the hour. Prescribed medication is administered with a signed form.' },
          { heading: 'Waiting list', body: 'We take names up to twelve months ahead with a refundable €100 deposit. Siblings of current children come first, then date order. If we cannot realistically offer you a place we will tell you within a fortnight rather than leave you waiting.' },
        ],
      }),
      b('visit', 'contact-form', {
        title: 'Book a look around',
        intro: 'Tours run Wednesdays at 10:00 and Thursdays at 15:30, twenty minutes, no appointment pressure. Tell us your child’s age and roughly when you would need a place.',
        submitLabel: 'Request a visit',
        successMessage: 'Thanks — Aoife will call you back within two working days.',
        fields: [
          { name: 'name', label: 'Your name', type: 'text', required: true },
          { name: 'email', label: 'Email', type: 'email', required: true, placeholder: 'you@example.com' },
          { name: 'phone', label: 'Phone', type: 'tel', placeholder: '+353 ' },
          { name: 'age', label: 'Child’s age at start', type: 'select', required: true, options: ['Under 1', '1–2 years', '2–3 years', '3–5 years (ECCE)'] },
          { name: 'start', label: 'When would you need a place?', type: 'text', placeholder: 'e.g. September 2026' },
          { name: 'notes', label: 'Anything you would like us to know?', type: 'textarea' },
        ],
      }),
      b('footer', 'footer', { brand: 'Little Acorns', tagline: 'Nursery & preschool · 14 Sandymount Green, Dublin 4.', links: [{ label: 'Rooms', href: '#rooms' }, { label: 'Fees', href: '#policies' }, { label: 'Book a visit', href: '#visit' }], copyright: '© Little Acorns Childcare · Tusla reg. TU-04417' }),
    ],
  }),
];
