/**
 * `healthcare` starter templates — clinics and practitioners, from a high-street
 * dental practice to a patient-app GP centre, a catalogue-first physio, a
 * conversational counselling practice, a showcase optician, a bold veterinary
 * hospital, a single-offer chiropractic landing page, and a solo dietitian profile.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const healthcareTemplates: Template[] = [
  tpl({
    id: 'healthcare-clinic',
    vertical: 'healthcare',
    label: 'Clinic — Appointments',
    description: 'A high-street dental practice leading with treatment prices, the team, and same-week booking.',
    tags: ['dentist', 'booking', 'family', 'faq', 'local'],
    layout: 'classic',
    preset: 'ocean',
    meta: { title: 'Maple Dental — Gentle, modern dentistry', description: 'Family and cosmetic dentistry with same-week appointments.', lang: 'en', favicon: '🦷' },
    blocks: [
      b('nav', 'nav', { brand: 'Maple Dental', sticky: true, links: [{ label: 'Treatments', href: '#treatments' }, { label: 'Team', href: '#team' }, { label: 'FAQ', href: '#faq' }], cta: { label: 'Book appointment', href: '#book' } }),
      b('hero', 'hero', { eyebrow: 'Accepting new patients', headline: 'Dentistry that actually feels calm', subhead: 'Same-week appointments, transparent pricing, and a team that explains everything.', align: 'left', minHeight: 'md', image: img('clinic-hero'), overlay: 'light', cta: { label: 'Book an appointment', href: '#book' } }),
      b('treatments', 'services-catalogue', { title: 'Treatments', subtitle: 'Clear pricing, no surprises.', items: [
        { name: 'Check-up & clean', description: 'Exam, scale & polish.', price: 'from £59' },
        { name: 'Teeth whitening', description: 'Take-home or in-chair.', price: 'from £249' },
        { name: 'Invisible aligners', description: 'Full treatment plan.', price: 'from £1,800' },
        { name: 'Emergency visit', description: 'Same-day where possible.', price: 'from £75' },
      ] }),
      b('team', 'team', { title: 'Meet the team', columns: 3, members: [
        { name: 'Dr. Aisha Khan', role: 'Principal Dentist', photo: img('doc-1'), bio: 'BDS · 12 years · cosmetic & restorative.' },
        { name: 'Dr. Leo Marsh', role: 'Dentist', photo: img('doc-2'), bio: 'Aligners and family dentistry.' },
        { name: 'Sam Rivera', role: 'Hygienist', photo: img('doc-3'), bio: 'Preventive care and nervous patients.' },
      ] }),
      b('faq', 'faq', { title: 'Questions, answered', items: [
        { question: 'Do you take new patients?', answer: 'Yes — both private and plan patients, usually within the week.' },
        { question: 'Nervous about the dentist?', answer: 'Tell us when you book. We build in extra time and go at your pace.' },
      ] }),
      b('book', 'cta', { headline: 'Ready when you are', subhead: 'Book online in under a minute, or call us.', background: 'primary', button: { label: 'Book an appointment', href: '#' } }),
      b('visit', 'contact-details', { title: 'Find us', address: '4 Elm Court, Leeds LS1 4DL', phone: '+44 113 000 0000', email: 'hello@mapledental.co.uk', hours: 'Mon–Fri 8:30–17:30 · Sat 9:00–13:00' }),
      b('footer', 'footer', { brand: 'Maple Dental', tagline: 'Gentle, modern dentistry.', links: [{ label: 'Treatments', href: '#treatments' }, { label: 'Book', href: '#book' }], copyright: '© Maple Dental' }),
    ],
  }),

  tpl({
    id: 'healthcare-family-practice',
    vertical: 'healthcare',
    label: 'Family Health Centre — Patient App',
    description: 'A general practice run like a product: tab-bar chrome, in-app booking, and an add-to-home-screen prompt.',
    tags: ['booking', 'family', 'mobile-first', 'dark', 'faq'],
    layout: 'app',
    preset: 'midnight',
    meta: { title: 'Sanjivani Family Health Centre — Pune', description: 'Everyday family medicine in Kothrud: same-day GP slots, vaccinations, and lab reports on your phone.', lang: 'en', favicon: '🩺' },
    blocks: [
      b('notice', 'announcement-bar', { text: 'Monsoon flu shots are in — walk-in clinic every Saturday morning.', linkLabel: 'Reserve a slot', href: '#book', tone: 'info', dismissible: true }),
      b('shell', 'app-shell', { brand: 'Sanjivani', tabs: [
        { label: 'Home', href: '#home', icon: '🏠' },
        { label: 'Care', href: '#care', icon: '🩺' },
        { label: 'Clinics', href: '#clinics', icon: '📅' },
        { label: 'Book', href: '#book', icon: '➕' },
        { label: 'Help', href: '#help', icon: '💬' },
      ] }),
      b('home', 'hero-app', {
        headline: 'Your family doctor, one tap away',
        subhead: 'Book a same-day slot, see your lab reports, and repeat a prescription without queueing at reception.',
        installLabel: 'Add Sanjivani to your phone',
        installHref: '#install',
        screenshots: [
          { src: img('hc-sanjivani-app-slots'), alt: 'Appointment slots for today' },
          { src: img('hc-sanjivani-app-report'), alt: 'A blood test report on a phone screen' },
          { src: img('hc-sanjivani-app-repeat'), alt: 'Repeat prescription request screen' },
        ],
      }),
      b('care', 'features', { title: 'What we look after', subtitle: 'Six doctors, one practice, no referral maze for the everyday things.', columns: 3, items: [
        { icon: '🤒', title: 'Same-day illness', text: 'Fever, throat, stomach — slots held back until 9am each day.' },
        { icon: '💉', title: 'Vaccinations', text: 'Full childhood schedule plus travel and flu shots.' },
        { icon: '🩸', title: 'Labs on site', text: 'Bloods drawn before 10am are reported the same evening.' },
        { icon: '🫀', title: 'Long-term care', text: 'Diabetes, thyroid and blood pressure reviews every quarter.' },
        { icon: '👶', title: 'Child health', text: 'Growth checks, feeding advice, and a paediatrician on Thursdays.' },
        { icon: '📄', title: 'Records that travel', text: 'Every note and report downloadable as a PDF, any time.' },
      ] }),
      b('clinics', 'feed', { title: 'This week at the centre', layout: 'list', items: [
        { title: 'Diabetes review clinic', subtitle: 'Tue & Thu, 4:00–7:00 pm', text: 'HbA1c, foot check and a 20-minute review with Dr. Kulkarni.', badge: '₹600', href: '#book' },
        { title: 'Child immunisation', subtitle: 'Wed, 10:00 am–1:00 pm', text: 'Government schedule free of charge; optional vaccines at cost.', badge: 'Free', href: '#book' },
        { title: 'Antenatal drop-in', subtitle: 'Fri, 11:00 am–2:00 pm', text: 'Weight, BP and scan review — no appointment needed.', badge: 'Walk-in', href: '#book' },
        { title: 'Saturday flu clinic', subtitle: 'Sat, 8:00–11:00 am', text: 'Quadrivalent flu shot for anyone over six months.', badge: '₹1,100', href: '#book' },
      ] }),
      b('book', 'booking', {
        title: 'Book a slot',
        intro: 'Requests are confirmed by SMS within the hour during opening times.',
        submitLabel: 'Request this slot',
        successMessage: 'Thanks — reception will text you a confirmation shortly.',
        serviceLabel: 'What do you need?',
        services: [
          { name: 'GP consultation', duration: '15 min', price: '₹700' },
          { name: 'Same-day illness slot', duration: '10 min', price: '₹700' },
          { name: 'Diabetes / BP review', duration: '20 min', price: '₹600' },
          { name: 'Vaccination', duration: '10 min', price: 'Free–₹1,100' },
          { name: 'Blood test only', duration: '5 min', price: 'from ₹350' },
        ],
        askDate: true, askTime: true, askPhone: true, askNotes: true,
        notesLabel: 'Anything the doctor should know first?',
      }),
      b('help', 'faq', { title: 'Before you come in', items: [
        { question: 'Do I need an appointment?', answer: 'For the doctor, yes — but we hold twelve slots back each morning for illness that cannot wait. Walk in before 9:30 am and ask for one.' },
        { question: 'Where do my reports go?', answer: 'Into the app, and by email if you prefer. Nothing is posted, and nothing is charged for a copy.' },
        { question: 'Can I see the same doctor each time?', answer: 'Pick their name when you book. If they are away, whoever sees you will have read the whole record.' },
        { question: 'Do you take insurance?', answer: 'We are a cash practice, but every bill is itemised and coded so reimbursement claims go through cleanly.' },
      ] }),
      b('install', 'install-prompt', {
        title: 'Keep the centre on your home screen',
        body: 'Appointments, reports and repeat prescriptions without hunting for a link.',
        actionLabel: 'Show me how',
        position: 'bottom',
        tone: 'info',
        delayMs: 6000,
        dismissible: true,
        rememberDismiss: true,
        platforms: ['ios-safari', 'android', 'desktop-chrome'],
      }),
      b('visit', 'contact-details', { title: 'The centre', address: '2nd Floor, Sunrise Plaza, Karve Road, Kothrud, Pune 411038', phone: '+91 20 4890 2200', email: 'reception@sanjivanihealth.in', hours: 'Mon–Sat 8:00–20:00 · Sun 9:00–13:00' }),
      b('footer', 'footer', { brand: 'Sanjivani Family Health Centre', tagline: 'Everyday medicine for Kothrud families.', links: [{ label: 'Care', href: '#care' }, { label: 'Clinics', href: '#clinics' }, { label: 'Book', href: '#book' }], copyright: '© Sanjivani Family Health Centre' }),
    ],
  }),

  tpl({
    id: 'healthcare-physio',
    vertical: 'healthcare',
    label: 'Physiotherapy — Catalogue',
    description: 'A physio clinic where the treatment list and the session prices are the first thing on the page.',
    tags: ['physiotherapy', 'pricing', 'booking', 'reviews', 'local'],
    layout: 'catalogue',
    preset: 'forest',
    meta: { title: 'Southbank Physio & Movement — Melbourne', description: 'Hands-on physiotherapy, clinical Pilates and return-to-sport rehab in Southbank.', lang: 'en', favicon: '🦵' },
    blocks: [
      b('nav', 'nav', { brand: 'Southbank Physio', sticky: true, links: [{ label: 'Treatments', href: '#services' }, { label: 'Fees', href: '#pricing' }, { label: 'Reviews', href: '#reviews' }, { label: 'Find us', href: '#map' }], cta: { label: 'Book online', href: '#book' } }),
      b('services', 'services-catalogue', {
        title: 'Everything we treat',
        subtitle: 'No referral needed. Most people are assessed and started on the same visit.',
        items: [
          { name: 'Initial assessment', description: '45 minutes: history, movement screen, hands-on treatment and a written plan.', price: 'A$135', ctaLabel: 'Book', ctaHref: '#book' },
          { name: 'Standard follow-up', description: '30 minutes of manual therapy and loaded exercise progression.', price: 'A$105', ctaLabel: 'Book', ctaHref: '#book' },
          { name: 'Return-to-run rehab', description: 'Treadmill gait analysis and a graded 12-week running plan.', price: 'A$180', ctaLabel: 'Book', ctaHref: '#book' },
          { name: 'Clinical Pilates (1:1)', description: 'Reformer work built around your injury, not a class timetable.', price: 'A$110', ctaLabel: 'Book', ctaHref: '#book' },
          { name: 'Dry needling add-on', description: 'Added to any follow-up where it will actually help.', price: 'A$25', ctaLabel: 'Book', ctaHref: '#book' },
          { name: 'Post-surgical rehab', description: 'ACL, shoulder and hip protocols, in step with your surgeon.', price: 'A$135', ctaLabel: 'Book', ctaHref: '#book' },
        ],
      }),
      b('pricing', 'pricing', {
        title: 'Multi-session packs',
        subtitle: 'Rehab works when it is finished, so packs cost less than paying visit by visit. Valid twelve months, refundable on the unused balance.',
        plans: [
          { name: 'Starter', price: 'A$215', period: '2 sessions', features: ['Initial assessment', 'One follow-up', 'Home program in the app'], ctaLabel: 'Buy the pack', ctaHref: '#book' },
          { name: 'Recovery', price: 'A$560', period: '6 sessions', features: ['Initial assessment', 'Five follow-ups', 'Home program in the app', 'Progress re-test at session four', 'Direct HICAPS claiming'], ctaLabel: 'Buy the pack', ctaHref: '#book', featured: true },
          { name: 'Return to sport', price: 'A$980', period: '10 sessions', features: ['Everything in Recovery', 'Gait or throwing analysis', 'Strength testing at week six', 'A letter for your coach or club'], ctaLabel: 'Buy the pack', ctaHref: '#book' },
        ],
      }),
      b('process', 'timeline', {
        title: 'A typical shoulder or low-back rehab, week by week',
        items: [
          { date: 'Day 1', title: 'Assessed and measured', text: 'Range, strength and load tolerance written down, so week six has something to be compared against. You go home with two exercises filmed on your own phone.' },
          { date: 'Week 2', title: 'Pain settles before strength arrives', text: 'Most people are sleeping through the night by now. This is the point where the exercises feel pointless and stopping them is the mistake.' },
          { date: 'Week 6', title: 'Re-test day', text: 'The same measurements, repeated. If the numbers have not moved we change the plan or send you for imaging — we do not simply book more sessions.' },
          { date: 'Week 12', title: 'Back to the thing you stopped doing', text: 'Netball, the 10k, lifting the toddler. We taper appointments out rather than discharging you the week you feel fine.' },
          { date: 'Month 6', title: 'One check-in, no charge', text: 'A short review to make sure the strength held once we stopped watching. Roughly one person in five needs a top-up block; the rest we wave off.' },
        ],
      }),
      b('reviews', 'reviews', {
        title: 'What people say afterwards',
        average: '4.9',
        count: '312',
        source: 'Google',
        items: [
          { rating: 5, quote: 'Six months of shoulder pain and three physios before this one. Marlee measured everything on day one and I was back overhead in nine weeks.', author: 'Tomas B.', date: 'March 2026', source: 'google' },
          { rating: 5, quote: 'They talked me out of a scan I did not need and gave me the exercises instead. Ran the half marathon in October.', author: 'Priya N.', date: 'November 2025', source: 'google' },
          { rating: 4, quote: 'Parking in Southbank is a nightmare, the physio is excellent. Post-ACL rehab was structured to the week.', author: 'Jordan A.', date: 'January 2026', source: 'google' },
        ],
      }),
      b('book', 'booking', {
        title: 'Book a treatment',
        intro: 'Online bookings close two hours before the slot — call the clinic for anything sooner.',
        submitLabel: 'Request booking',
        successMessage: 'Booked in. You will get a confirmation email with parking directions.',
        serviceLabel: 'Treatment',
        services: [
          { name: 'Initial assessment', duration: '45 min', price: 'A$135' },
          { name: 'Standard follow-up', duration: '30 min', price: 'A$105' },
          { name: 'Return-to-run rehab', duration: '60 min', price: 'A$180' },
          { name: 'Clinical Pilates (1:1)', duration: '45 min', price: 'A$110' },
        ],
        askDate: true, askTime: true, askPhone: true, askNotes: true,
        notesLabel: 'Where does it hurt, and since when?',
      }),
      b('map', 'map', { query: '3 Kavanagh Street, Southbank VIC 3006, Australia', zoom: 16, height: 380, label: 'Southbank Physio & Movement' }),
      b('visit', 'contact-details', { title: 'Practical details', address: 'Ground floor, 3 Kavanagh Street, Southbank VIC 3006', phone: '+61 3 9682 4410', email: 'front.desk@southbankphysio.com.au', hours: 'Mon–Thu 7:00–19:00 · Fri 7:00–16:00 · Sat 8:00–12:00' }),
      b('footer', 'footer', { brand: 'Southbank Physio & Movement', tagline: 'Measured rehab, not mystery treatment.', links: [{ label: 'Treatments', href: '#services' }, { label: 'Fees', href: '#pricing' }, { label: 'Book', href: '#book' }], copyright: '© Southbank Physio & Movement Pty Ltd' }),
    ],
  }),

  tpl({
    id: 'healthcare-therapy',
    vertical: 'healthcare',
    label: 'Counselling Practice — Conversational',
    description: 'A therapy practice that answers the awkward questions in the visitor’s own words before asking for anything.',
    tags: ['therapy', 'remote', 'faq', 'pricing', 'newsletter'],
    layout: 'conversational',
    preset: 'sand',
    meta: { title: 'Northlight Counselling — Portland, OR', description: 'Individual and couples therapy in Portland and online across Oregon.', lang: 'en', favicon: '🌾' },
    blocks: [
      b('nav', 'nav', { brand: 'Northlight Counselling', sticky: false, links: [{ label: 'How it works', href: '#how' }, { label: 'Fees', href: '#fees' }, { label: 'Questions', href: '#faq' }], cta: { label: 'Ask a question', href: '#contact' } }),
      b('hero', 'hero', {
        eyebrow: 'Portland, OR · and online across Oregon',
        headline: 'Most people put this off for about two years',
        subhead: 'You do not have to know what to say, or what is wrong, or whether it is bad enough. Start with a message and we will work it out from there.',
        align: 'center',
        minHeight: 'sm',
        overlay: 'none',
        cta: { label: 'Send a first message', href: '#contact' },
      }),
      b('approach', 'rich-text', { blocks: [
        { kind: 'heading', text: 'How we work' },
        { kind: 'paragraph', text: 'Northlight is three therapists sharing an office above a bakery on SE Division. We practise relationally, which mostly means we are interested in what happens between people — including what happens between you and us in the room.' },
        { kind: 'paragraph', text: 'Between us we are trained in EMDR, emotionally focused therapy for couples, and internal family systems. Those are tools, not identities. Which one gets used depends entirely on what you bring.' },
        { kind: 'quote', text: 'The first job is not insight. It is that your nervous system decides this room is safe enough to be honest in.' },
        { kind: 'subheading', text: 'What we are not' },
        { kind: 'bullet', text: 'We do not prescribe. If medication would help, we will say so and refer.' },
        { kind: 'bullet', text: 'We are not a crisis service. If you are in danger tonight, call or text 988.' },
        { kind: 'bullet', text: 'We do not do court-ordered evaluations or custody assessments.' },
      ] }),
      b('reach-out', 'chat-thread', {
        title: 'What reaching out actually looks like',
        subtitle: 'A first exchange, shared with permission and with the details changed.',
        participants: [
          { id: 'v', name: 'New enquiry', role: 'user' },
          { id: 'n', name: 'Rowan, Northlight', role: 'agent' },
        ],
        messages: [
          { from: 'v', time: 'Tue 21:14', body: [{ kind: 'text', text: 'I do not really know how to write this. Nothing terrible has happened, I am just tired all the time and snapping at my partner. Is that even a therapy thing?' }] },
          { from: 'n', time: 'Wed 08:40', body: [
            { kind: 'text', text: 'It is, and honestly that is how most people describe it when they first write. Nothing dramatic, just running on empty and taking it out on the person closest to you.' },
            { kind: 'text', text: 'Two ways in from here — no wrong answer:' },
            { kind: 'list', ordered: false, items: [
              { label: 'A free 20-minute call this week, no notes taken' },
              { label: 'Straight into a first full session, $150' },
            ] },
            { kind: 'buttons', items: [{ label: 'Book the free call', href: '#contact' }, { label: 'See fees first', href: '#fees' }] },
          ] },
          { from: 'v', time: 'Wed 09:02', body: [{ kind: 'text', text: 'The call, I think. Do I have to talk about my childhood?' }] },
          { from: 'n', time: 'Wed 09:15', body: [
            { kind: 'text', text: 'Only if and when it seems useful to you. Plenty of good therapy stays firmly in the present tense.' },
            { kind: 'text', text: 'Thursday 6pm or Friday 12:30 — which suits?' },
            { kind: 'buttons', items: [{ label: 'Thursday 6pm' }, { label: 'Friday 12:30' }] },
          ] },
        ],
      }),
      b('how', 'accordion', {
        title: 'The practical shape of it',
        items: [
          { heading: 'How long does therapy take?', body: 'Focused work on one issue — a phobia, a specific trauma, a decision — often lands between eight and sixteen sessions. Longer-standing patterns take longer, and we will review together at session six rather than letting it drift indefinitely.' },
          { heading: 'Weekly, or can I come fortnightly?', body: 'Weekly for the first six sessions if you can manage it; momentum matters early. After that, plenty of people move to fortnightly, and some to monthly maintenance.' },
          { heading: 'Do you see couples?', body: 'Yes, with Rowan and with Dani. Couples sessions run 75 minutes, because 50 is not enough for two people. We do not take couples where there is ongoing intimate partner violence — we will refer you somewhere better suited.' },
          { heading: 'Is online as good as in person?', body: 'For most talking therapy the research says it is comparable. EMDR online works but needs a stable connection and a private room. We are licensed in Oregon, so you need to be physically in Oregon during the session.' },
        ],
      }),
      b('fees', 'pricing', {
        title: 'Fees, plainly',
        subtitle: 'We hold four reduced-fee places at any time. Ask — there is no means test and nobody checks your bank statements.',
        plans: [
          { name: 'Individual', price: '$150', period: '50 minutes', features: ['Weekly or fortnightly', 'In person or online', 'Superbill for out-of-network reimbursement'], ctaLabel: 'Ask about a slot', ctaHref: '#contact' },
          { name: 'Couples', price: '$210', period: '75 minutes', features: ['Both partners, one therapist', 'Evening slots on Tue and Thu', 'Superbill provided'], ctaLabel: 'Ask about a slot', ctaHref: '#contact', featured: true },
          { name: 'Reduced fee', price: '$70', period: '50 minutes', features: ['Four places held open', 'Students, carers, between jobs', 'No paperwork required'], ctaLabel: 'Ask if one is free', ctaHref: '#contact' },
        ],
      }),
      b('faq', 'faq', {
        title: 'The questions people email at 1am',
        items: [
          { question: 'What if I cry, or say nothing at all?', answer: 'Both are extremely normal and neither is a problem. Some first sessions are mostly silence. That is still work.' },
          { question: 'Will you tell my partner or my employer anything?', answer: 'No. What you say stays in the room, with the legal exceptions we go through in session one — risk to your life, risk to a child or vulnerable adult, or a court order.' },
          { question: 'Do you take insurance?', answer: 'We are out-of-network. You pay us directly and we issue a superbill each month; most PPO plans reimburse 50–80%. We will help you check before you commit.' },
          { question: 'What if we are not a fit?', answer: 'Say so, at any point, including after session one. We keep a referral list of therapists we would send our own families to.' },
        ],
      }),
      b('contact', 'contact-form', {
        title: 'Send a first message',
        intro: 'Two or three sentences is plenty. Replies come from a real person, usually within one working day.',
        submitLabel: 'Send it',
        successMessage: 'Got it. You will hear back within one working day — check your spam folder just in case.',
        fields: [
          { name: 'name', label: 'What should we call you?', type: 'text', placeholder: 'First name is fine', required: true },
          { name: 'email', label: 'Email', type: 'email', placeholder: 'you@example.com', required: true },
          { name: 'phone', label: 'Phone (optional)', type: 'tel', placeholder: '(503) 555-0142' },
          { name: 'kind', label: 'What are you looking for?', type: 'select', required: true, options: ['Individual therapy', 'Couples therapy', 'Not sure yet', 'A reduced-fee place'] },
          { name: 'message', label: 'In your own words', type: 'textarea', placeholder: 'It does not have to be tidy.', required: true },
          { name: 'consent', label: 'I am happy to be contacted by email', type: 'checkbox', required: true },
        ],
      }),
      b('letters', 'newsletter', {
        title: 'A letter, once a month',
        intro: 'One short piece on something we keep seeing in the room — burnout, repair after an argument, the January slump. No promotions, unsubscribe in one click.',
        placeholder: 'you@example.com',
        submitLabel: 'Send it to me',
        successMessage: 'You are on the list. The first letter arrives on the first Tuesday of the month.',
      }),
      b('policies', 'legal', {
        title: 'Policies',
        align: 'center',
        separator: '·',
        documents: [
          { label: 'Confidentiality', title: 'Confidentiality and its limits', content: 'What you say in session stays between you and your therapist. The exceptions, which we go through verbally in your first session, are: a serious and imminent risk to your own life; suspected abuse or neglect of a child, elder or dependent adult; and a valid court order. Notes are kept encrypted and retained for seven years, as Oregon law requires.' },
          { label: 'Cancellation', title: 'Cancellation policy', content: 'Sessions cancelled with more than 24 hours notice are not charged. Inside 24 hours the full fee applies, because the hour cannot be filled. We waive this for genuine emergencies and illness — just tell us.' },
          { label: 'Privacy', title: 'Website privacy', content: 'The enquiry form emails us your message and nothing else. We do not run advertising trackers on this site. Newsletter addresses are stored with our email provider and deleted on unsubscribe.' },
        ],
      }),
      b('footer', 'footer', { brand: 'Northlight Counselling', tagline: 'Relational therapy on SE Division.', links: [{ label: 'Fees', href: '#fees' }, { label: 'Questions', href: '#faq' }, { label: 'Get in touch', href: '#contact' }], copyright: '© Northlight Counselling LLC · In a crisis, call or text 988' }),
    ],
  }),

  tpl({
    id: 'healthcare-optician',
    vertical: 'healthcare',
    label: 'Optician — Showcase',
    description: 'An independent optician where the frames and the room do the selling before any copy does.',
    tags: ['optician', 'gallery', 'booking', 'luxury', 'local'],
    layout: 'showcase',
    preset: 'mono',
    meta: { title: 'Lens & Loupe Optiek — Amsterdam', description: 'Independent eyewear and unhurried eye examinations on the Elandsgracht.', lang: 'en', favicon: '👓' },
    blocks: [
      b('nav', 'nav', { brand: 'Lens & Loupe', sticky: true, links: [{ label: 'Lookbook', href: '#lookbook' }, { label: 'Frames', href: '#frames' }, { label: 'The shop', href: '#inside' }, { label: 'Visit', href: '#visit' }], cta: { label: 'Book an eye test', href: '#eye-test' } }),
      b('hero', 'hero', {
        eyebrow: 'Jordaan · since 2011',
        headline: 'Glasses you keep for a decade',
        subhead: 'Four hundred frames, chosen one at a time from twenty-two independent makers. Nothing here is in a chain window.',
        align: 'center',
        minHeight: 'full',
        image: img('hc-loupe-shopfront'),
        overlay: 'dark',
        cta: { label: 'See the lookbook', href: '#lookbook' },
      }),
      b('lookbook', 'gallery', {
        layout: 'masonry',
        columns: 3,
        gap: 'lg',
        lightbox: true,
        items: [
          { src: img('hc-loupe-acetate-amber'), alt: 'Amber acetate frame on a linen tray', caption: 'Handmade acetate, Cadore — €340' },
          { src: img('hc-loupe-titanium-rim'), alt: 'Thin titanium rimless frame', caption: 'Beta-titanium rimless, 11 g — €410' },
          { src: img('hc-loupe-round-gold'), alt: 'Round gold-toned metal frame', caption: 'Hand-soldered rounds, Sabae — €520' },
          { src: img('hc-loupe-tortoise-cat'), alt: 'Tortoiseshell cat-eye frame on marble' },
          { src: img('hc-loupe-fitting-bench'), alt: 'Frames being adjusted at the fitting bench' },
          { src: img('hc-loupe-lens-edger'), alt: 'A lens on the edging machine in the back workshop' },
          { src: img('hc-loupe-sun-clip'), alt: 'Magnetic sun clip on a horn frame' },
          { src: img('hc-loupe-childrens-wall'), alt: 'Wall of children’s frames in bright colours' },
        ],
      }),
      b('frames', 'product', {
        title: 'A few we are wearing this season',
        subtitle: 'Prices are for the frame. Lenses are quoted after your test, because the right lens depends entirely on your eyes.',
        columns: 3,
        items: [
          { name: 'Cadore 04', description: 'Italian block acetate, milled and polished over six weeks. Keyhole bridge.', price: '€340', image: img('hc-loupe-prod-cadore'), badge: 'Best seller', ctaLabel: 'Try it on', ctaHref: '#eye-test' },
          { name: 'Nord Rimless', description: 'Beta-titanium, eleven grams, no screws to work loose.', price: '€410', was: '€460', image: img('hc-loupe-prod-nord'), badge: 'Ex-display', ctaLabel: 'Try it on', ctaHref: '#eye-test' },
          { name: 'Sasaki Round', description: 'Hand-soldered in Sabae, gold-plated over titanium.', price: '€520', image: img('hc-loupe-prod-sasaki'), ctaLabel: 'Try it on', ctaHref: '#eye-test' },
          { name: 'Buffalo Horn 1', description: 'Genuine horn, warms to the face, every pair a different grain.', price: '€680', image: img('hc-loupe-prod-horn'), badge: 'One of a kind', ctaLabel: 'Try it on', ctaHref: '#eye-test' },
          { name: 'Kite Kids', description: 'Flexible, springy, and survives a school bag. Free replacement if broken in year one.', price: '€145', image: img('hc-loupe-prod-kite'), ctaLabel: 'Try it on', ctaHref: '#eye-test' },
          { name: 'Duo Sun Clip', description: 'Magnetic polarised clip, cut to fit any frame in the shop.', price: '€95', image: img('hc-loupe-prod-clip'), ctaLabel: 'Ask in store', ctaHref: '#visit' },
        ],
      }),
      b('inside', 'carousel', {
        title: 'Inside the shop',
        autoplay: false,
        items: [
          { src: img('hc-loupe-inside-counter'), alt: 'The oak counter and frame wall', caption: 'Four hundred frames, all of them tryable, none of them locked away.' },
          { src: img('hc-loupe-inside-testroom'), alt: 'The consulting room with a phoropter', caption: 'Forty-five minutes for a test. Nobody is hurried out.' },
          { src: img('hc-loupe-inside-workshop'), alt: 'Bench with lens edging equipment', caption: 'Single-vision lenses cut in the back — often ready the next morning.' },
          { src: img('hc-loupe-inside-canal'), alt: 'The canal outside the shop at dusk', caption: 'Elandsgracht, two minutes from the Wednesday market.' },
        ],
      }),
      b('care', 'features', {
        title: 'What a €95 eye test buys you',
        columns: 4,
        items: [
          { icon: '⏱️', title: 'Forty-five minutes', text: 'Not fifteen. Time to actually ask questions.' },
          { icon: '📷', title: 'Retinal photography', text: 'Imaged every visit and compared year to year.' },
          { icon: '🧾', title: 'Fee refunded', text: 'Deducted in full from any complete pair over €250.' },
          { icon: '🔧', title: 'Adjustments forever', text: 'Bring them in whenever they slip. No charge, no appointment.' },
        ],
      }),
      b('eye-test', 'booking', {
        title: 'Book an eye examination',
        intro: 'Two optometrists, three rooms, and rarely more than a week’s wait. Bring your current glasses.',
        submitLabel: 'Request this time',
        successMessage: 'Bedankt — we will email to confirm, usually within a few hours.',
        serviceLabel: 'Type of appointment',
        services: [
          { name: 'Full eye examination', duration: '45 min', price: '€95' },
          { name: 'Contact lens fitting', duration: '60 min', price: '€120' },
          { name: 'Children’s eye test (under 16)', duration: '30 min', price: '€55' },
          { name: 'Frame styling only', duration: '30 min', price: 'Free' },
        ],
        askDate: true, askTime: true, askPhone: true, askNotes: false,
      }),
      b('words', 'testimonials', {
        title: 'From the guest book by the door',
        items: [
          { quote: 'They spent an hour talking me out of the pair I walked in for and into one that suits my face. Three years on I still get compliments.', author: 'Marijke', role: 'Jordaan' },
          { quote: 'Picked up an astigmatism two other opticians had shrugged at. The retinal photos convinced me — you can see the change year on year.', author: 'Daan', role: 'Customer since 2018' },
          { quote: 'My kid has broken theirs twice. Both times replaced without a sigh or an invoice.', author: 'Hanneke', role: 'Amsterdam-West' },
        ],
      }),
      b('visit', 'directions', {
        title: 'Finding us',
        place: 'Lens & Loupe Optiek',
        address: 'Elandsgracht 88-H, 1016 TZ Amsterdam',
        lat: '52.3701',
        lng: '4.8792',
        directionsLabel: 'Open in maps',
        appleMaps: true,
      }),
      b('footer', 'footer', { brand: 'Lens & Loupe Optiek', tagline: 'Independent eyewear on the Elandsgracht.', links: [{ label: 'Frames', href: '#frames' }, { label: 'Eye test', href: '#eye-test' }, { label: 'Visit', href: '#visit' }], copyright: '© Lens & Loupe Optiek · KvK 51224098 · Tue–Sat 10:00–18:00' }),
    ],
  }),

  tpl({
    id: 'healthcare-vet',
    vertical: 'healthcare',
    label: 'Veterinary Hospital — Bold',
    description: 'A full-service animal hospital with an emergency strip, a big warm hero, and the whole team on the page.',
    tags: ['pets', 'emergency', 'family', 'video', 'reviews'],
    layout: 'bold',
    preset: 'candy',
    meta: { title: 'Barton Creek Animal Hospital — Austin, TX', description: 'Primary care, dentistry and urgent medicine for dogs, cats and the occasional rabbit.', lang: 'en', favicon: '🐾' },
    blocks: [
      b('urgent', 'announcement-bar', { text: 'Emergency? We are open until midnight, seven days — call before you drive.', linkLabel: 'See today’s hours', href: '#hours', tone: 'warning', dismissible: false }),
      b('nav', 'nav', { brand: 'Barton Creek Animal Hospital', sticky: true, links: [{ label: 'Services', href: '#services' }, { label: 'Our team', href: '#team' }, { label: 'Tour', href: '#tour' }, { label: 'Hours', href: '#hours' }], cta: { label: 'Book a visit', href: '#book' } }),
      b('hero', 'hero', {
        eyebrow: 'Fear-Free certified · AAHA accredited',
        headline: 'Nobody here is going to rush your dog',
        subhead: 'Twenty-minute appointments, non-slip floors, treats before needles, and a separate cat entrance that never smells of dog.',
        align: 'left',
        minHeight: 'full',
        image: img('hc-barton-hero-dog'),
        overlay: 'scrim',
        cta: { label: 'Book a visit', href: '#book' },
      }),
      b('stats', 'stats', {
        title: 'Eighteen years on Bee Cave Road',
        columns: 4,
        items: [
          { value: '18', label: 'Years in the neighborhood' },
          { value: '11', label: 'Veterinarians on staff' },
          { value: '9,400', label: 'Patients on our books', prefix: '~' },
          { value: '24', label: 'Diagnostics turned around in', suffix: ' hrs' },
        ],
      }),
      b('services', 'services-catalogue', {
        title: 'What we do here',
        subtitle: 'Everything except orthopedic surgery, which we refer to a specialist twelve minutes away.',
        items: [
          { name: 'Wellness exam', description: 'Twenty minutes, nose to tail, with a written plan for the year.', price: '$78' },
          { name: 'Vaccination visit', description: 'Core and lifestyle vaccines, tailored to where your pet actually goes.', price: 'from $32' },
          { name: 'Dental with radiographs', description: 'Full-mouth X-rays, scale and polish under monitored anesthesia.', price: 'from $620' },
          { name: 'Radiology & ultrasound', description: 'In-house, read the same day by a boarded radiologist.', price: 'from $210' },
          { name: 'Urgent care', description: 'Walk-in triage until 11:30 pm, seven days a week.', price: 'from $135' },
          { name: 'Senior blood panel', description: 'Kidney, liver, thyroid and blood pressure for pets over eight.', price: '$189' },
          { name: 'Behavior consult', description: 'Ninety minutes with Dr. Okafor for anxiety, reactivity and litter-box wars.', price: '$240' },
          { name: 'End-of-life care', description: 'At the clinic or at home, unhurried, in a room with a door that closes.', price: 'from $290' },
        ],
      }),
      b('team', 'team', {
        title: 'The people who will actually see you',
        subtitle: 'You can request any of them by name, and most clients do.',
        columns: 4,
        members: [
          { name: 'Dr. Renata Okafor', role: 'Medical Director · Behavior', photo: img('hc-barton-vet-okafor'), bio: 'DVM, Texas A&M. Fear-Free certified. Will sit on the floor for as long as it takes.' },
          { name: 'Dr. Sam Whitfield', role: 'Dentistry & Surgery', photo: img('hc-barton-vet-whitfield'), bio: 'Two hundred dentals a year and a genuine enthusiasm for feline resorptive lesions.' },
          { name: 'Dr. Meera Patel', role: 'Internal Medicine', photo: img('hc-barton-vet-patel'), bio: 'Runs the diabetic and kidney clinics. Answers emails at unreasonable hours.' },
          { name: 'Kelsey Brandt, LVT', role: 'Lead Technician', photo: img('hc-barton-tech-brandt'), bio: 'Places the hard catheters, calms the hard cats, trains everyone else.' },
        ],
      }),
      b('tour', 'video', {
        provider: 'youtube',
        src: 'Qk8vN2rTf1M',
        title: 'A two-minute walk through the hospital',
        poster: img('hc-barton-tour-poster'),
        caption: 'The cat ward, the treatment floor, and the comfort room — filmed on a normal Tuesday.',
      }),
      b('stories', 'testimonials', {
        title: 'From the neighborhood',
        items: [
          { quote: 'Our terrier used to shake in the parking lot. Now she drags us to the door, because the front desk keeps cheese behind the counter.', author: 'The Alvarez family', role: 'Clients since 2019' },
          { quote: 'Dr. Patel called me at 9pm on a Sunday with lab results that could easily have sat until Monday morning. That is who they are.', author: 'Bree T.', role: 'Oak Hill' },
          { quote: 'They gave us the comfort room for two hours and never once looked at the clock. I will never take an animal anywhere else.', author: 'Jonah M.', role: 'Austin' },
        ],
      }),
      b('faq', 'faq', {
        title: 'Common questions',
        items: [
          { question: 'Do you take walk-ins?', answer: 'For urgent problems, yes, until 11:30 pm. We triage by severity, so a stable itchy ear may wait behind a breathing emergency — call ahead and we will tell you honestly how busy we are.' },
          { question: 'Can I stay with my pet?', answer: 'For exams, always. For sedated procedures we ask you to wait outside the treatment area, but you can come back in for recovery.' },
          { question: 'What does it cost to be seen?', answer: 'The exam fee is $78 and covers the veterinarian’s time. Anything beyond that is estimated in writing and approved by you before we do it.' },
          { question: 'Do you see rabbits, rats and birds?', answer: 'Rabbits, guinea pigs and rats, yes. Birds and reptiles we refer to an exotics practice in North Austin.' },
        ],
      }),
      b('hours', 'hours', {
        title: 'When we are open',
        timezone: 'America/Chicago',
        note: 'Urgent care triage closes 30 minutes before the doors do. Christmas Day is emergency-only.',
        days: [
          { day: 'mon', open: '07:00', close: '23:59' },
          { day: 'tue', open: '07:00', close: '23:59' },
          { day: 'wed', open: '07:00', close: '23:59' },
          { day: 'thu', open: '07:00', close: '23:59' },
          { day: 'fri', open: '07:00', close: '23:59' },
          { day: 'sat', open: '08:00', close: '23:59' },
          { day: 'sun', open: '09:00', close: '23:59' },
        ],
      }),
      b('book', 'cta', {
        headline: 'Get them looked at this week',
        subhead: 'Routine appointments usually open up within three days. Urgent ones, today.',
        background: 'primary',
        button: { label: 'Book a visit', href: '#' },
      }),
      b('footer', 'footer', { brand: 'Barton Creek Animal Hospital', tagline: '4118 Bee Cave Road, Austin TX 78746 · (512) 555-0179', links: [{ label: 'Services', href: '#services' }, { label: 'Team', href: '#team' }, { label: 'Hours', href: '#hours' }], copyright: '© Barton Creek Animal Hospital, PLLC' }),
    ],
  }),

  tpl({
    id: 'healthcare-chiro',
    vertical: 'healthcare',
    label: 'Chiropractor — Landing Page',
    description: 'A single-offer conversion page for a chiropractic clinic: proof, process, one intro offer, one form.',
    tags: ['chiropractor', 'landing', 'one-pager', 'reviews', 'b2c'],
    layout: 'landing',
    preset: 'ocean',
    meta: { title: 'Riverbend Spine & Chiropractic — Toronto', description: 'A $49 assessment for back and neck pain, with direct insurance billing, on Queen West.', lang: 'en', favicon: '🦴' },
    blocks: [
      b('nav', 'nav', { brand: 'Riverbend Spine', sticky: true, links: [{ label: 'How it works', href: '#how' }, { label: 'Reviews', href: '#reviews' }], cta: { label: 'Claim the $49 assessment', href: '#claim' } }),
      b('hero', 'hero', {
        eyebrow: 'Queen West, Toronto · Direct billing to 14 insurers',
        headline: 'Back pain, assessed properly, for $49',
        subhead: 'A full 40-minute assessment, normally $145. Twelve places each week — and we will tell you straight if chiropractic is not the answer.',
        align: 'left',
        minHeight: 'lg',
        image: img('hc-riverbend-hero-adjust'),
        overlay: 'scrim',
        cta: { label: 'Claim the $49 assessment', href: '#claim' },
      }),
      b('trusted', 'logos', {
        title: 'We bill these plans directly — most people pay nothing at the desk',
        items: [
          { src: img('hc-riverbend-insurer-sunlife'), alt: 'Sun Life' },
          { src: img('hc-riverbend-insurer-manulife'), alt: 'Manulife' },
          { src: img('hc-riverbend-insurer-canadalife'), alt: 'Canada Life' },
          { src: img('hc-riverbend-insurer-greenshield'), alt: 'Green Shield Canada' },
          { src: img('hc-riverbend-insurer-bluecross'), alt: 'Blue Cross' },
        ],
      }),
      b('why', 'split', {
        rows: [
          { title: 'We look for the cause, not just the sore spot', text: 'Most low back pain that has hung around for months is a movement problem somewhere else — a stiff hip, a rib that will not rotate, six hours a day in a bad chair. The assessment maps the whole chain before anyone touches your spine.', image: img('hc-riverbend-assessment'), imageAlt: 'A movement assessment in progress' },
          { title: 'Adjustment is a third of the work', text: 'The other two thirds are loaded rehab and changing whatever caused it. You leave with two exercises, filmed on your own phone, and a desk setup you can actually implement on Monday.', image: img('hc-riverbend-rehab-band'), imageAlt: 'Resistance band rehab exercise' },
          { title: 'A finish line, in writing', text: 'At the assessment you get an estimated number of visits and a date to re-test. If you are not measurably better by then, we change the plan or refer you on. No open-ended care plans, no year-long packages.', image: img('hc-riverbend-plan-sheet'), imageAlt: 'A printed care plan on a clipboard' },
        ],
      }),
      b('how', 'steps', {
        title: 'What the $49 hour covers',
        subtitle: 'Forty minutes with the chiropractor, then twenty for questions and the plan.',
        items: [
          { title: 'History that matters', text: 'What you do all day, how you sleep, and what makes it worse at 4pm.' },
          { title: 'Orthopedic and neuro testing', text: 'Reflexes, dermatomes, joint-by-joint mobility — written down and repeated later.' },
          { title: 'Imaging only if indicated', text: 'We refer for X-ray in maybe one case in six. Most people do not need it, and we will say so.' },
          { title: 'A plan with a date on it', text: 'Visit count, expected milestones, re-test date, and what it costs — before you commit.' },
        ],
      }),
      b('reviews', 'reviews', {
        title: 'Six hundred and forty reviews, and counting',
        subtitle: 'Verified through Google and Trustpilot. We do not filter the middling ones out.',
        average: '4.8',
        count: '640',
        source: 'Google',
        items: [
          { rating: 5, quote: 'Two years of sciatica. Eight visits and a set of exercises I still do. They discharged me rather than selling me a maintenance plan, which is why I keep sending people.', author: 'Devon R.', date: 'February 2026', source: 'google' },
          { rating: 5, quote: 'The assessment alone was worth triple the $49. Found the hip restriction three other clinicians had missed.', author: 'Aline C.', date: 'December 2025', source: 'trustpilot' },
          { rating: 4, quote: 'Excellent care, but the 7am slots go fast and the waiting room is tiny. Book ahead.', author: 'Marc-André L.', date: 'January 2026', source: 'google' },
          { rating: 5, quote: 'They told me my shoulder was not a chiropractic problem and sent me to a sports physician. Honest people.', author: 'Sadia H.', date: 'October 2025', source: 'google' },
        ],
      }),
      b('offer', 'pricing', {
        title: 'The offer, and what comes after',
        subtitle: 'One introductory price, then ordinary visit fees. Nothing is bundled and nothing auto-renews.',
        plans: [
          { name: 'Intro assessment', price: '$49', period: 'one hour, once', features: ['40-minute clinical assessment', 'Orthopedic and neurological testing', 'Written care plan with a re-test date', 'First adjustment included if appropriate', 'No obligation to book again'], ctaLabel: 'Claim a place', ctaHref: '#claim', featured: true },
          { name: 'Follow-up visit', price: '$75', period: 'per 20 minutes', features: ['Adjustment and soft-tissue work', 'Rehab progression each visit', 'Direct insurance billing'], ctaLabel: 'Ask about availability', ctaHref: '#claim' },
        ],
      }),
      b('faq', 'faq', {
        title: 'Fair questions before you book',
        items: [
          { question: 'Is there a catch with the $49?', answer: 'No. It is a genuine loss-leader — we would rather you judged us on an assessment than on advertising. You are under no obligation to book anything afterwards, and we will not phone you if you do not.' },
          { question: 'Does the adjustment hurt?', answer: 'It should not. The noise surprises people more than the sensation does. If you would rather not be adjusted at all, say so — mobilisation and soft-tissue work are alternatives.' },
          { question: 'Are you covered by my extended health plan?', answer: 'Chiropractic is covered by most Canadian extended plans. We bill fourteen insurers directly, so in most cases you pay only the portion your plan does not cover.' },
          { question: 'What if I need something else?', answer: 'Then we say so at the assessment and refer you — to a physiotherapist, a sports physician, or your family doctor. About one person in eight who books this offer leaves with a referral instead of a care plan.' },
        ],
      }),
      b('cta', 'cta', {
        headline: 'Twelve places a week. Usually gone by Tuesday.',
        subhead: 'Book the $49 assessment and find out what is actually going on with your back.',
        background: 'accent',
        button: { label: 'Claim the $49 assessment', href: '#claim' },
      }),
      b('claim', 'contact-form', {
        title: 'Claim your assessment',
        intro: 'Tell us when suits and we will confirm by text within a couple of hours. Clinic hours are Mon–Fri 7:00–19:00 and Sat 8:00–13:00.',
        submitLabel: 'Claim my place',
        successMessage: 'Place held. We will text you to confirm the exact time — look out for a Toronto number.',
        fields: [
          { name: 'name', label: 'Full name', type: 'text', placeholder: 'Alex Moreau', required: true },
          { name: 'phone', label: 'Mobile', type: 'tel', placeholder: '(416) 555-0148', required: true },
          { name: 'email', label: 'Email', type: 'email', placeholder: 'you@example.com', required: true },
          { name: 'problem', label: 'Where is the pain?', type: 'select', required: true, options: ['Low back', 'Neck', 'Mid back or ribs', 'Headaches', 'Shoulder or arm', 'Somewhere else'] },
          { name: 'when', label: 'Best time to come in', type: 'select', options: ['Early morning (7–9am)', 'Daytime', 'After work (5–7pm)', 'Saturday morning'] },
          { name: 'insurer', label: 'Extended health provider (optional)', type: 'text', placeholder: 'Sun Life, Manulife…' },
        ],
      }),
      b('footer', 'footer', { brand: 'Riverbend Spine & Chiropractic', tagline: '1042 Queen Street West, Toronto ON M6J 1H8 · (416) 555-0148', links: [{ label: 'How it works', href: '#how' }, { label: 'Reviews', href: '#reviews' }, { label: 'Book', href: '#claim' }], copyright: '© Riverbend Spine & Chiropractic · Registered with the CCO' }),
    ],
  }),

  tpl({
    id: 'healthcare-dietitian',
    vertical: 'healthcare',
    label: 'Dietitian — Practitioner Profile',
    description: 'A solo registered dietitian: credentials, specialisms and writing, built like a professional profile.',
    tags: ['nutrition', 'portfolio', 'remote', 'booking', 'b2c'],
    layout: 'profile',
    preset: 'forest',
    meta: { title: 'Iona Fletcher RD — Dietitian, Bristol', description: 'HCPC-registered dietitian working in gut health, RED-S and eating disorder recovery.', lang: 'en', favicon: '🥗' },
    blocks: [
      b('top', 'profile-header', {
        name: 'Iona Fletcher',
        headline: 'Registered Dietitian (HCPC) · Gut health, RED-S and recovery',
        location: 'Clifton, Bristol · and online across the UK',
        avatar: img('hc-fletcher-portrait'),
        summary: 'Eleven years in the NHS before going independent in 2021. I work with people whose relationship with food has got complicated — through IBS, through sport, or through an eating disorder — and my job is to make eating boring again, in the best possible sense.',
        contacts: [
          { type: 'email', value: 'iona@ionafletcher.co.uk' },
          { type: 'phone', value: '+44 117 456 0021' },
          { type: 'location', value: 'Clifton, Bristol BS8' },
          { type: 'linkedin', value: 'https://www.linkedin.com/in/ionafletcherrd', label: 'LinkedIn' },
        ],
        showDownload: true,
        downloadLabel: 'Download my CV',
        showShare: true,
        shareLabel: 'Share this page',
      }),
      b('about', 'about', {
        eyebrow: 'How I work',
        title: 'No meal plans, no food lists on the fridge',
        body: 'A meal plan works for about three weeks, and then real life arrives — a late meeting, a bad night, a child who will only eat beige. So we do not start there.\n\nWe start with what you actually eat in a normal week, what your body is doing with it, and which single change would make the biggest difference for the least misery. Then we build from there, one thing at a time, with a review every three or four weeks to see whether it held.\n\nI am regulated by the HCPC and a member of the BDA, which means I can interpret bloods, work alongside your GP or consultant, and advise on medication timing around food. It also means there is a real complaints route if I get something wrong.',
        image: img('hc-fletcher-consult-room'),
        imageAlt: 'A consulting room with a kitchen table and two chairs',
        imageSide: 'right',
      }),
      b('work-with-me', 'services-catalogue', {
        title: 'Ways to work together',
        subtitle: 'All appointments are available in Clifton or by video. Sessions are usually claimable on private health insurance.',
        items: [
          { name: 'First consultation', description: '75 minutes: full dietary history, symptom mapping, and a plan for the first fortnight.', price: '£140', ctaLabel: 'Book', ctaHref: '#book' },
          { name: 'Review appointment', description: '30 minutes to look at what stuck, what did not, and what changes next.', price: '£70', ctaLabel: 'Book', ctaHref: '#book' },
          { name: 'Low-FODMAP programme', description: 'Three appointments over twelve weeks: elimination, structured reintroduction, personalisation.', price: '£330', ctaLabel: 'Book', ctaHref: '#book' },
          { name: 'RED-S and sports nutrition', description: 'For endurance athletes with low energy availability — often alongside a coach and a physician.', price: '£160', ctaLabel: 'Book', ctaHref: '#book' },
          { name: 'Recovery support (ED)', description: 'Weekly or fortnightly, coordinated with your therapist and GP. Referral not required.', price: '£110', ctaLabel: 'Enquire', ctaHref: '#book' },
          { name: 'Team or clinic training', description: 'Half-day CPD sessions for sports clubs, GP practices and workplace health teams.', price: 'from £750', ctaLabel: 'Enquire', ctaHref: '#book' },
        ],
      }),
      b('background', 'experience', {
        title: 'Background',
        items: [
          {
            role: 'Independent Dietitian',
            org: 'Iona Fletcher Nutrition',
            period: '2021 — present',
            location: 'Bristol & online',
            summary: 'Private practice split roughly evenly between gut health, sport, and eating disorder recovery.',
            bullets: [
              'Around 400 consultations a year, 60% of them by video across the UK.',
              'Consultant dietitian to two regional triathlon squads on RED-S screening.',
              'Supervise two newly qualified dietitians through their BDA preceptorship.',
            ],
          },
          {
            role: 'Specialist Gastroenterology Dietitian',
            org: 'North Bristol NHS Trust',
            period: '2016 — 2021',
            location: 'Southmead Hospital',
            summary: 'Ran the low-FODMAP and IBD outpatient clinics and rebuilt the referral pathway with gastroenterology.',
            bullets: [
              'Cut the IBS clinic waiting list from 22 weeks to 9 by introducing group first appointments.',
              'Co-authored the trust’s adult coeliac follow-up protocol, still in use.',
            ],
          },
          {
            role: 'Dietitian, rotational',
            org: 'Royal United Hospitals Bath',
            period: '2013 — 2016',
            location: 'Bath',
            summary: 'Rotations across stroke, critical care, oncology and community paediatrics.',
          },
          {
            role: 'BSc (Hons) Dietetics, first class',
            org: 'Cardiff Metropolitan University',
            period: '2009 — 2013',
            location: 'Cardiff',
            summary: 'Dissertation on fibre tolerance in post-surgical bowel patients. HCPC registered since 2013.',
          },
        ],
      }),
      b('specialisms', 'skills', {
        title: 'Specialisms and training',
        display: 'bars',
        groups: [
          { name: 'Clinical areas', items: [
            { label: 'IBS and low-FODMAP', level: 5 },
            { label: 'Coeliac and IBD', level: 4 },
            { label: 'RED-S and endurance sport', level: 4 },
            { label: 'Eating disorder recovery', level: 4 },
            { label: 'Type 2 diabetes remission', level: 3 },
          ] },
          { name: 'Certifications', items: [
            { label: 'Monash low-FODMAP certified', level: 5 },
            { label: 'BDA advanced sports nutrition', level: 4 },
            { label: 'MANTRA-informed practice', level: 3 },
          ] },
          { name: 'Languages', items: [
            { label: 'English', level: 5 },
            { label: 'Welsh', level: 3 },
          ] },
        ],
      }),
      b('writing', 'blog-list', {
        title: 'Writing',
        columns: 3,
        posts: [
          { title: 'Fibre is not one thing, and that is why the advice keeps failing you', excerpt: 'Soluble, insoluble, fermentable, resistant starch — why “eat more fibre” makes some people much worse before it makes anyone better.', href: '#', image: img('hc-fletcher-post-fibre'), date: '12 May 2026', tag: 'Gut health' },
          { title: 'What under-fuelling actually looks like in a club runner', excerpt: 'Not the textbook picture. Usually: a stalled parkrun time, three colds since January, and a stress fracture nobody connected to breakfast.', href: '#', image: img('hc-fletcher-post-reds'), date: '3 April 2026', tag: 'RED-S' },
          { title: 'Reintroduction is the whole point of low-FODMAP', excerpt: 'The elimination phase is six weeks. Too many people stay on it for two years and end up with a smaller diet and a worse microbiome.', href: '#', image: img('hc-fletcher-post-fodmap'), date: '20 February 2026', tag: 'Gut health' },
        ],
      }),
      b('book', 'booking', {
        title: 'Book an appointment',
        intro: 'I answer enquiries myself, usually within a working day. Clinic is Tuesday and Thursday in Clifton; video appointments run Monday, Wednesday and Friday.',
        submitLabel: 'Request appointment',
        successMessage: 'Thank you — I will come back to you within one working day to confirm.',
        serviceLabel: 'Appointment type',
        services: [
          { name: 'First consultation', duration: '75 min', price: '£140' },
          { name: 'Review appointment', duration: '30 min', price: '£70' },
          { name: 'Low-FODMAP programme', duration: '75 min', price: '£330' },
          { name: 'RED-S and sports nutrition', duration: '60 min', price: '£160' },
          { name: 'Free enquiry call', duration: '15 min', price: 'Free' },
        ],
        askDate: true, askTime: true, askPhone: true, askNotes: true,
        notesLabel: 'What would you like to get out of it?',
      }),
      b('elsewhere', 'social-links', {
        title: 'Elsewhere',
        layout: 'row',
        variant: 'labeled',
        align: 'center',
        links: [
          { platform: 'linkedin', href: '#', label: 'LinkedIn' },
          { platform: 'instagram', href: '#', label: '@ionafletcherrd' },
          { platform: 'email', href: '#', label: 'iona@ionafletcher.co.uk' },
          { platform: 'website', href: '#', label: 'BDA member directory' },
        ],
      }),
      b('smallprint', 'copyright', {
        holder: 'Iona Fletcher Nutrition Ltd',
        text: 'HCPC registered dietitian · BDA member · Registered in England 13299104',
        showSymbol: true,
        align: 'center',
      }),
    ],
  }),
];
