/**
 * `hospitality` starter templates — places people sleep: boutique hotels, B&Bs,
 * hostels, self-catering villas, campsites and spa retreats.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const hospitalityTemplates: Template[] = [
  tpl({
    id: 'hospitality-hotel',
    vertical: 'hospitality',
    label: 'Hotel — Boutique',
    description: 'A small harbourside hotel leading with rooms, views and direct booking.',
    tags: ['booking', 'gallery', 'luxury', 'pets', 'local'],
    layout: 'classic',
    preset: 'forest',
    meta: { title: 'The Harbour House Hotel', description: 'A boutique harbourside hotel with sea views and slow mornings.', lang: 'en', favicon: '🏨' },
    blocks: [
      b('nav', 'nav', { brand: 'Harbour House', sticky: true, links: [{ label: 'Rooms', href: '#rooms' }, { label: 'Gallery', href: '#gallery' }, { label: 'Visit', href: '#visit' }], cta: { label: 'Check availability', href: '#book' } }),
      b('hero', 'hero', { eyebrow: 'Harbourside · Cornwall', headline: 'Wake up to the water', subhead: 'Sixteen calm rooms, a sea-view terrace, and breakfast worth getting up for.', align: 'center', minHeight: 'full', image: img('hotel-hero'), overlay: 'scrim', cta: { label: 'Check availability', href: '#book' } }),
      b('gallery', 'gallery', { layout: 'grid', columns: 3, gap: 'md', lightbox: true, items: [{ src: img('hotel-1'), alt: 'Sea-view room' }, { src: img('hotel-2'), alt: 'Terrace' }, { src: img('hotel-3'), alt: 'Breakfast' }, { src: img('hotel-4'), alt: 'Harbour at dusk' }] }),
      b('why', 'features', { title: 'The little things', columns: 3, items: [
        { icon: '🌅', title: 'Sea views', text: 'Most rooms face the harbour.' },
        { icon: '🍳', title: 'Proper breakfast', text: 'Local, cooked to order, included.' },
        { icon: '🐾', title: 'Dogs welcome', text: 'Two paws up — beds and bowls provided.' },
      ] }),
      b('rooms', 'services-catalogue', { title: 'Rooms', subtitle: 'Rates per night, breakfast included.', items: [
        { name: 'Snug double', description: 'Cosy, courtyard-facing.', price: 'from £120' },
        { name: 'Harbour double', description: 'Sea view, king bed.', price: 'from £165' },
        { name: 'Captain’s suite', description: 'Corner room, private balcony.', price: 'from £240' },
      ] }),
      b('reviews', 'testimonials', { title: 'From our guests', items: [
        { quote: 'The view from the Harbour double is unreal. We’ll be back.', author: 'The Nolans', role: 'Stayed in June' },
        { quote: 'Warm, calm, and that breakfast… honestly the best part.', author: 'Grace', role: 'Guest' },
      ] }),
      b('visit', 'contact-details', { title: 'Find us', address: '1 Quay Street, St Ives TR26 1LP', phone: '+44 1736 000 000', email: 'stay@harbourhouse.hotel', hours: 'Reception 7:00–22:00' }),
      b('book', 'cta', { headline: 'Plan a slow weekend', subhead: 'Check dates and book directly for our best rate.', background: 'primary', button: { label: 'Check availability', href: '#' } }),
      b('footer', 'footer', { brand: 'The Harbour House Hotel', tagline: 'Boutique harbourside stays.', links: [{ label: 'Rooms', href: '#rooms' }, { label: 'Book', href: '#book' }], copyright: '© The Harbour House Hotel' }),
    ],
  }),

  tpl({
    id: 'hospitality-bnb',
    vertical: 'hospitality',
    label: 'Bed & Breakfast — Editorial',
    description: 'A five-room farmhouse B&B told in long-form: the house, the breakfast, the valley.',
    tags: ['long-form', 'family', 'local', 'reviews', 'newsletter'],
    layout: 'editorial',
    preset: 'sand',
    meta: { title: 'Willowbank Farmhouse — Bed & Breakfast', description: 'Five rooms, one long breakfast table, and forty acres of Vermont hillside.', lang: 'en', favicon: '🥞' },
    blocks: [
      b('nav', 'nav', { brand: 'Willowbank', sticky: false, links: [{ label: 'The house', href: '#house' }, { label: 'Breakfast', href: '#breakfast' }, { label: 'Rooms', href: '#rooms' }, { label: 'Visit', href: '#visit' }], cta: { label: 'Check dates', href: '#stay' } }),
      b('hero', 'hero', { eyebrow: 'Waitsfield, Vermont', headline: 'Five rooms, one very long breakfast table', subhead: 'A restored 1840s farmhouse above the Mad River, run by two people who genuinely like having guests.', align: 'left', minHeight: 'lg', image: img('willowbank-porch-morning'), overlay: 'light', cta: { label: 'Check dates', href: '#stay' } }),
      b('house', 'about', { eyebrow: 'The house', title: 'It was a dairy farm until 1978', body: 'We bought Willowbank in 2016 with a leaking roof and a wood stove that smoked. Seven winters later there are new windows in every room, a library where the milking parlour used to be, and a porch that catches the last of the light around seven. The floors still slope. We have decided that is character. There are five guest rooms upstairs and one on the ground floor with a step-free entrance and a wet room. No televisions anywhere — but there is a very good radio.', image: img('willowbank-library-corner'), imageAlt: 'Library with a wood stove and full shelves', imageSide: 'right' }),
      b('breakfast', 'rich-text', { blocks: [
        { kind: 'heading', text: 'Breakfast is at eight, and it is not a buffet' },
        { kind: 'paragraph', text: 'Everyone eats together at the long maple table. It is more sociable than it sounds, and if you would rather not talk before nine we will put you at the window end and leave you alone with the coffee.' },
        { kind: 'subheading', text: 'What usually turns up' },
        { kind: 'bullet', text: 'Buttermilk pancakes with syrup from the sugarbush behind the barn.' },
        { kind: 'bullet', text: 'Eggs from the eleven hens, however you like them.' },
        { kind: 'bullet', text: 'Sourdough, cultured butter, and whatever fruit the valley is doing that week.' },
        { kind: 'paragraph', text: 'Vegan, gluten-free and dairy-free breakfasts are cooked to order — tell us when you book and it is genuinely no trouble.' },
        { kind: 'quote', text: 'Guests have been known to move a flight around the pancakes. We are not apologising for that.' },
      ] }),
      b('rooms', 'split', { rows: [
        { title: 'The Sugarhouse — $185 a night', text: 'Front corner room with two windows over the meadow, a queen bed and the deepest bathtub in the house. Sleeps two.', image: img('willowbank-sugarhouse-room'), imageAlt: 'Corner bedroom looking over a meadow' },
        { title: 'The Parlour — $165 a night', text: 'Ground floor, step-free from the drive, wet room with grab rails and a fold-down seat. King bed or twins, your choice when you book.', image: img('willowbank-parlour-room'), imageAlt: 'Ground-floor bedroom with a step-free wet room' },
        { title: 'The Hayloft — $210 a night', text: 'The whole top floor of the barn: sitting room, kitchenette, and a skylight directly over the bed. Sleeps four, so it is the one families ask for.', image: img('willowbank-hayloft-skylight'), imageAlt: 'Barn loft bedroom with a large skylight' },
      ] }),
      b('guests', 'reviews', { title: 'What guests write afterwards', average: '4.9', count: '312', source: 'Verified stays, 2023–2025', items: [
        { rating: 5, quote: 'We came for two nights and stayed four. The room was lovely but it is really the breakfast table that does it — we left with three new friends and a jar of syrup.', author: 'Danielle R.', date: 'October 2025', source: 'tripadvisor' },
        { rating: 5, quote: 'Booked the Parlour for my father, who uses a walker. Step-free from the car to the bed, and nobody made a fuss about it. That is rarer than it should be.', author: 'Marcus T.', date: 'August 2025', source: 'google' },
        { rating: 4, quote: 'Floors creak, the hill is steep, wifi is fine but not fast. Absolutely worth it. Bring boots in mud season.', author: 'Priya S.', date: 'April 2025', source: 'tripadvisor' },
      ] }),
      b('visit', 'contact-details', { title: 'Finding us', address: '412 Mad River Road, Waitsfield, VT 05673', phone: '+1 (802) 555 0148', email: 'hello@willowbankvt.com', hours: 'Check-in 3:00–8:00 pm · Check-out 11:00 am' }),
      b('stay', 'cta', { headline: 'Two nights in the valley', subhead: 'Book direct and the second night is 15% off, November through April.', background: 'surface', button: { label: 'Check dates & book', href: '#' } }),
      b('letter', 'newsletter', { title: 'The Willowbank letter', intro: 'Six emails a year: when the leaves turn, when the sugarhouse fires up, and when we have a last-minute room going spare.', placeholder: 'you@example.com', submitLabel: 'Sign me up', successMessage: 'Lovely — see you in the inbox.' }),
      b('footer', 'footer', { brand: 'Willowbank Farmhouse', tagline: 'Five rooms above the Mad River.', links: [{ label: 'Rooms', href: '#rooms' }, { label: 'Breakfast', href: '#breakfast' }, { label: 'Visit', href: '#visit' }], copyright: '© Willowbank Farmhouse, Waitsfield VT' }),
    ],
  }),

  tpl({
    id: 'hospitality-hostel',
    vertical: 'hospitality',
    label: 'Hostel — Bed rates first',
    description: 'A backpacker hostel where the bed-price list is the whole pitch, plus what happens each week.',
    tags: ['budget', 'pricing', 'social', 'faq', 'mobile-first'],
    layout: 'catalogue',
    preset: 'candy',
    meta: { title: 'Casa Azulejo Hostel — Lisbon', description: 'Beds from €22 in Graça, with a roof terrace, free walking tours and family dinner on Wednesdays.', lang: 'en', favicon: '🛏️' },
    blocks: [
      b('announce', 'announcement-bar', { text: 'Low season: four nights for the price of three, all November.', linkLabel: 'See bed rates', href: '#beds', tone: 'promo', dismissible: true }),
      b('nav', 'nav', { brand: 'Casa Azulejo', sticky: true, links: [{ label: 'Beds', href: '#beds' }, { label: 'Add-ons', href: '#extras' }, { label: 'The week', href: '#week' }, { label: 'FAQ', href: '#faq' }], cta: { label: 'Book a bed', href: '#beds' } }),
      b('hero', 'hero', { eyebrow: 'Graça, Lisbon · four minutes from tram 28', headline: 'Beds from €22. Terrace included.', subhead: 'Sixty-eight beds across six dorms and nine private rooms, in a tiled 1920s townhouse with the best cheap view in the city.', align: 'left', minHeight: 'sm', image: img('azulejo-roof-terrace-sunset'), overlay: 'scrim', cta: { label: 'See tonight’s rates', href: '#beds' } }),
      b('beds', 'pricing', { title: 'Beds & rooms', subtitle: 'Per person per night. Linen, lockers, wifi and breakfast are in the price — no surprise fees at the desk.', plans: [
        { name: '10-bed mixed dorm', price: '€22', period: '/night', features: ['Curtained pod bunk', 'Reading light and two sockets', 'Full-height locker', 'Shared bathroom on the floor'], ctaLabel: 'Book a bunk', ctaHref: '#' },
        { name: '6-bed dorm', price: '€28', period: '/night', features: ['Mixed or women-only', 'Curtained pod bunk', 'En-suite shower room', 'Quieter courtyard side'], ctaLabel: 'Book a bunk', ctaHref: '#', featured: true },
        { name: '4-bed private', price: '€39', period: '/person/night', features: ['Book the whole room', 'En-suite, towels included', 'Fits a family of four', 'Ground-floor option, step-free'], ctaLabel: 'Book the room', ctaHref: '#' },
        { name: 'Double private', price: '€74', period: '/room/night', features: ['Double bed, own key', 'En-suite shower room', 'Street or terrace view', 'Breakfast for two'], ctaLabel: 'Book the room', ctaHref: '#' },
      ] }),
      b('extras', 'services-catalogue', { title: 'Add-ons at the desk', subtitle: 'Pay when you arrive, cash or card, no booking fee.', items: [
        { name: 'Laundry, washed and dried', description: 'Back in your locker the same evening.', price: '€6' },
        { name: 'Bike hire', description: 'City bike with a lock and a hand-drawn map of the flat routes.', price: '€12/day' },
        { name: 'Surf shuttle to Costa da Caparica', description: 'Leaves 8:00, back by 17:00. Board and wetsuit included.', price: '€35' },
        { name: 'Airport transfer', description: 'Shared van, meets you in arrivals with a sign.', price: '€14' },
        { name: 'Luggage storage after checkout', description: 'Locked room, unlimited bags, until 22:00.', price: 'Free' },
      ] }),
      b('perks', 'features', { title: 'What comes as standard', columns: 4, items: [
        { icon: '🌇', title: 'Roof terrace', text: 'Open until 1am, then quiet out of respect for the neighbours.' },
        { icon: '🍳', title: 'Breakfast until 11', text: 'Bread, fruit, eggs, coffee. Included in every rate.' },
        { icon: '🔒', title: 'Big lockers', text: 'A 70-litre pack fits standing up. Bring a padlock or buy one for €3.' },
        { icon: '🧺', title: 'A real kitchen', text: 'Six hobs, two ovens, and a shelf for your leftovers.' },
      ] }),
      b('week', 'tabs', { items: [
        { label: 'Monday', text: 'Free walking tour of Alfama at 10:00 — meet by the reception sofa. Tipping the guide is normal; €5–10 is kind.' },
        { label: 'Wednesday', text: 'Family dinner, 20:00, €7. Whoever is staying cooks together and there is always a vegan pot. Sign up on the whiteboard by lunchtime.' },
        { label: 'Friday', text: 'Fado night at the bar around the corner. We book the back room for 21:30 — no cover charge if you arrive with us.' },
        { label: 'Sunday', text: 'Feira da Ladra flea-market run, leaves 9:30. Bring cash and low expectations, come back with a lamp.' },
      ] }),
      b('faq', 'faq', { title: 'Before you book', items: [
        { question: 'Is there an age limit?', answer: 'Dorms are 18–45. Private rooms have no age limit and we welcome families with children of any age.' },
        { question: 'Is there a lockout or a curfew?', answer: 'Neither. Reception is staffed 24 hours and every guest gets a door code.' },
        { question: 'Can I check in late?', answer: 'Yes, at any hour. Send us your flight number and we will keep an eye on the arrivals board.' },
        { question: 'Is the building step-free?', answer: 'The ground floor — reception, kitchen, one 4-bed private room and an accessible bathroom — is step-free from the street. The dorms and the terrace are up stairs only; the building is listed and we cannot fit a lift.' },
        { question: 'Do you hold luggage before check-in?', answer: 'Free, from 7:00 on your arrival day and until 22:00 on the day you leave.' },
      ] }),
      b('map', 'map', { query: 'Calçada de Santo André, Graça, Lisboa, Portugal', zoom: 15, height: 360, label: 'Casa Azulejo, Graça — four minutes from the 28 tram' }),
      b('social', 'social-links', { title: 'Ask us anything', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'whatsapp', href: '#', label: 'WhatsApp the desk' },
        { platform: 'instagram', href: '#', label: '@casaazulejolisboa' },
        { platform: 'email', href: '#', label: 'ola@casaazulejo.pt' },
      ] }),
      b('footer', 'footer', { brand: 'Casa Azulejo Hostel', tagline: 'Beds, terrace, tram 28.', links: [{ label: 'Beds', href: '#beds' }, { label: 'FAQ', href: '#faq' }, { label: 'Find us', href: '#map' }], copyright: '© Casa Azulejo Lda · RNAL 12345/AL' }),
    ],
  }),

  tpl({
    id: 'hospitality-villa',
    vertical: 'hospitality',
    label: 'Holiday villa — Photo-led',
    description: 'A self-catering villa let where the photography sells the week and the rates sit underneath.',
    tags: ['gallery', 'luxury', 'family', 'booking', 'one-pager'],
    layout: 'showcase',
    preset: 'ocean',
    meta: { title: 'Masseria Fico Nero — Puglia', description: 'A restored trullo farmhouse for eight, with a 14-metre pool and an olive grove to itself.', lang: 'en', favicon: '🫒' },
    blocks: [
      b('nav', 'nav', { brand: 'Masseria Fico Nero', sticky: true, links: [{ label: 'The house', href: '#tour' }, { label: 'Gallery', href: '#gallery' }, { label: 'Rates', href: '#rates' }, { label: 'Getting here', href: '#directions' }], cta: { label: 'Enquire', href: '#enquire' } }),
      b('hero', 'hero', { eyebrow: 'Ostuni, Puglia · sleeps eight', headline: 'A whole farmhouse, an olive grove, and nobody else', subhead: 'Four bedrooms under vaulted stone, a 14-metre pool, and the sea eleven minutes down the hill.', align: 'center', minHeight: 'full', image: img('ficonero-pool-dusk'), overlay: 'scrim', cta: { label: 'Check your week', href: '#enquire' } }),
      b('tour', 'carousel', { title: 'Walk through the house', autoplay: true, items: [
        { src: img('ficonero-vaulted-living'), alt: 'Vaulted stone living room', caption: 'The main room, under the original 1840s vault. Cool even at four in the afternoon.' },
        { src: img('ficonero-kitchen-arch'), alt: 'Kitchen with an arched window', caption: 'Kitchen with a six-ring range, a dishwasher, and a table that seats ten.' },
        { src: img('ficonero-master-bedroom'), alt: 'Master bedroom with shutters', caption: 'Master bedroom: king bed, en-suite, shutters onto the grove.' },
        { src: img('ficonero-shaded-pergola'), alt: 'Dining pergola lit at night', caption: 'Where you will actually eat every night. Lights on a dimmer, no mosquitoes to speak of.' },
        { src: img('ficonero-olive-grove-path'), alt: 'Path between olive trees', caption: 'Six hundred trees, all yours to wander. The oil in the kitchen comes from them.' },
      ] }),
      b('gallery', 'gallery', { layout: 'masonry', columns: 3, gap: 'lg', lightbox: true, items: [
        { src: img('ficonero-pool-morning'), alt: 'Pool at first light', caption: 'The pool at 7am' },
        { src: img('ficonero-twin-room'), alt: 'Twin bedroom with stone walls' },
        { src: img('ficonero-outdoor-shower'), alt: 'Outdoor shower in a stone alcove' },
        { src: img('ficonero-steps-roof-terrace'), alt: 'Stone steps up to the roof terrace' },
        { src: img('ficonero-breakfast-figs'), alt: 'Breakfast of figs, cheese and bread' },
        { src: img('ficonero-lemon-courtyard'), alt: 'Lemon trees in the courtyard' },
        { src: img('ficonero-roof-terrace-sea'), alt: 'Roof terrace with the sea in the distance', caption: 'On a clear day you can see the Adriatic from up here' },
        { src: img('ficonero-hammock-shade'), alt: 'Hammock strung between two olive trees' },
      ] }),
      b('inside', 'features', { title: 'What comes with the week', columns: 4, items: [
        { icon: '🏊', title: '14m private pool', text: 'Salt-filtered, heated from April, with a fenced gate for small children.' },
        { icon: '❄️', title: 'Air conditioning', text: 'In all four bedrooms, plus ceiling fans throughout.' },
        { icon: '🧺', title: 'Changeover clean', text: 'Linen, towels and a mid-week tidy are all in the rate.' },
        { icon: '🚗', title: 'Parking for three', text: 'Gravel yard inside the gate. You will want a car out here.' },
      ] }),
      b('rates', 'services-catalogue', { title: 'Weekly rates', subtitle: 'Saturday to Saturday, whole house, up to eight guests. Final clean and utilities included; tourist tax is €2 per adult per night, paid on arrival.', items: [
        { name: 'April – May', description: 'Wildflowers, empty beaches, 22°C. Our favourite time of year here.', price: '€2,450 / week', ctaLabel: 'Ask about a date', ctaHref: '#enquire' },
        { name: 'June & September', description: 'Warm sea, long evenings, and the grove still green.', price: '€3,200 / week', ctaLabel: 'Ask about a date', ctaHref: '#enquire' },
        { name: 'July – August', description: 'Peak season. Booked a year ahead more often than not.', price: '€4,100 / week', ctaLabel: 'Ask about a date', ctaHref: '#enquire' },
        { name: 'October – March', description: 'Short breaks from three nights, with wood for the fireplace included.', price: '€1,650 / week', ctaLabel: 'Ask about a date', ctaHref: '#enquire' },
      ] }),
      b('directions', 'directions', { title: 'Getting here', place: 'Masseria Fico Nero', address: 'Contrada Lamacesare 44, 72017 Ostuni BR, Italy', lat: '40.7286', lng: '17.5794', mapUrl: '#', directionsLabel: 'Open the route from Brindisi airport', appleMaps: true }),
      b('enquire', 'contact-form', { title: 'Ask about your week', intro: 'Tell us your dates and how many of you there are. Silvia answers within a day, in English or Italian.', submitLabel: 'Send enquiry', successMessage: 'Got it — you will hear from us within 24 hours.', fields: [
        { name: 'name', label: 'Your name', type: 'text', required: true },
        { name: 'email', label: 'Email', type: 'email', required: true },
        { name: 'dates', label: 'Preferred dates', type: 'text', placeholder: 'e.g. 14–21 June', required: true },
        { name: 'guests', label: 'How many guests', type: 'select', options: ['2', '3–4', '5–6', '7–8'], required: true },
        { name: 'notes', label: 'Anything we should know', type: 'textarea', placeholder: 'Travelling with a toddler, need a cot, arriving late…' },
      ] }),
      b('footer', 'footer', { brand: 'Masseria Fico Nero', tagline: 'A trullo farmhouse outside Ostuni.', links: [{ label: 'Gallery', href: '#gallery' }, { label: 'Rates', href: '#rates' }, { label: 'Enquire', href: '#enquire' }], copyright: '© Masseria Fico Nero · CIN IT074012C2000012345' }),
    ],
  }),

  tpl({
    id: 'hospitality-campsite',
    vertical: 'hospitality',
    label: 'Campsite & glamping — Bold',
    description: 'A bush campsite and glamping park selling pitches, bell tents and dark-sky nights.',
    tags: ['booking', 'family', 'pets', 'video', 'dark'],
    layout: 'bold',
    preset: 'midnight',
    meta: { title: 'Blackwood Ridge — Camping & Glamping', description: 'Tent pitches, powered sites and safari tents on 200 hectares of Tasmanian bush.', lang: 'en', favicon: '🏕️' },
    blocks: [
      b('nav', 'nav', { brand: 'Blackwood Ridge', sticky: true, links: [{ label: 'Stays', href: '#stays' }, { label: 'How it works', href: '#how' }, { label: 'Reception', href: '#hours' }], cta: { label: 'Book a site', href: '#book' } }),
      b('hero', 'hero', { eyebrow: 'Derwent Valley, Tasmania', headline: 'No phone signal. That is the product.', subhead: 'Two hundred hectares of bush, a river you can swim in, and a sky dark enough that the Milky Way casts a shadow.', align: 'center', minHeight: 'full', image: img('blackwood-tents-under-stars'), overlay: 'dark', cta: { label: 'Book a site', href: '#book' } }),
      b('numbers', 'stats', { title: 'The site in numbers', columns: 4, items: [
        { value: '200', label: 'Of bush and river frontage', suffix: 'ha' },
        { value: '46', label: 'Pitches and tents' },
        { value: '2', label: 'Bortle dark-sky class' },
        { value: '11', label: 'Years family-run' },
      ] }),
      b('stays', 'product', { title: 'Pick your night', subtitle: 'Prices are per night for two people. Extra adult $18, children under 12 free, dogs free on the unpowered loop.', columns: 3, items: [
        { name: 'Unpowered bush pitch', description: 'Find your own patch on the river loop. Fire drum, firewood, and a composting toilet within 80 metres.', price: '$32', image: img('blackwood-river-pitch'), badge: 'Dogs welcome', ctaLabel: 'Check dates', ctaHref: '#book' },
        { name: 'Powered site', description: 'Level gravel pad for a van or camper, 15A power, drinking tap at the post, 12m drive-through.', price: '$54', image: img('blackwood-powered-van-site'), ctaLabel: 'Check dates', ctaHref: '#book' },
        { name: 'Safari tent', description: 'Canvas on a deck: queen bed, wood heater, gas ring, and a hot shower two minutes away.', price: '$185', was: '$210', image: img('blackwood-safari-tent-deck'), badge: 'Most booked', ctaLabel: 'Check dates', ctaHref: '#book' },
        { name: 'Bell tent, made up', description: 'Turn up with nothing. Bedding, lantern, rug and a firewood bundle are already in there.', price: '$149', image: img('blackwood-bell-tent-interior'), ctaLabel: 'Check dates', ctaHref: '#book' },
        { name: 'Cabin at the treeline', description: 'Solid walls, its own bathroom, a tiny kitchen. The one to book in July when it snows.', price: '$225', image: img('blackwood-timber-cabin-snow'), ctaLabel: 'Check dates', ctaHref: '#book' },
        { name: 'Group clearing', description: 'The whole north clearing for up to 20 people, with its own fire ring and toilet block.', price: '$390', image: img('blackwood-group-clearing-fire'), badge: 'Whole area', ctaLabel: 'Check dates', ctaHref: '#book' },
      ] }),
      b('how', 'steps', { title: 'How a night here goes', subtitle: 'Reception is a shed with a bell on it. It works.', items: [
        { title: 'Book, then drive in', text: 'Turn off the B61 at the Blackwood sign and follow the gravel for 3.4km. Last fuel and groceries are in New Norfolk — stock up there.' },
        { title: 'Collect your wood and your map', text: 'A barrow of split hardwood comes with every site. The map marks the swimming hole, the two walking loops, and where the wombats dig.' },
        { title: 'Lose the day', text: 'Swim, walk to the falls, read. Generators off from 8pm and quiet from 10pm — this is the only rule anyone cares about.' },
        { title: 'Look up', text: 'On a clear moonless night you will see the Magellanic Clouds with the naked eye. We hand out red torches so nobody wrecks it.' },
      ] }),
      b('film', 'video', { provider: 'youtube', src: 'https://www.youtube.com/watch?v=aqz-KE-bpKQ', title: 'A weekend at Blackwood Ridge', poster: img('blackwood-video-poster-river'), caption: 'Four minutes, shot by a guest over one weekend in March. Sound up for the frogs.' }),
      b('voices', 'testimonials', { title: 'What campers say', items: [
        { quote: 'We have been coming since our eldest was in a carrier. She is nine now and knows the river loop better than we do.', author: 'Ash & Tom', role: 'Hobart · eleventh stay' },
        { quote: 'Booked a bell tent as a soft launch into camping for someone who hates camping. They asked to stay a third night.', author: 'Jodie M.', role: 'Melbourne' },
        { quote: 'The dark sky is not marketing. I took my first real Milky Way photograph from the group clearing.', author: 'Ren', role: 'Astrophotography club' },
      ] }),
      b('hours', 'hours', { title: 'Reception & gate', timezone: 'Australia/Hobart', note: 'Arriving late? Ring ahead and we will leave your site number and a torch in the box on the gate.', days: [
        { day: 'mon', open: '09:00', close: '17:00' },
        { day: 'tue', open: '09:00', close: '17:00' },
        { day: 'wed', open: '09:00', close: '17:00' },
        { day: 'thu', open: '09:00', close: '18:00' },
        { day: 'fri', open: '08:00', close: '20:00' },
        { day: 'sat', open: '08:00', close: '20:00' },
        { day: 'sun', open: '08:00', close: '18:00' },
      ] }),
      b('book', 'cta', { headline: 'The good weekends go in August', subhead: 'Summer opens for booking on 1 August, and the river pitches are usually gone by the end of that week.', background: 'accent', button: { label: 'Book a site', href: '#' } }),
      b('footer', 'footer', { brand: 'Blackwood Ridge', tagline: 'Camping & glamping, Derwent Valley.', links: [{ label: 'Stays', href: '#stays' }, { label: 'Reception hours', href: '#hours' }, { label: 'Book', href: '#book' }], copyright: '© Blackwood Ridge Pty Ltd · ABN 00 000 000 000' }),
    ],
  }),

  tpl({
    id: 'hospitality-spa-resort',
    vertical: 'hospitality',
    label: 'Spa resort — Retreat offer',
    description: 'A single-offer landing page for a wellness retreat: packages, proof, and one booking form.',
    tags: ['booking', 'pricing', 'luxury', 'reviews', 'one-pager'],
    layout: 'landing',
    preset: 'mono',
    meta: { title: 'Kanthari Backwater Spa — 7-night Ayurvedic retreat', description: 'A doctor-led seven-night panchakarma retreat on the Kerala backwaters, limited to fourteen guests.', lang: 'en', favicon: '🌿' },
    blocks: [
      b('nav', 'nav', { brand: 'Kanthari', sticky: true, links: [{ label: 'The retreat', href: '#included' }, { label: 'Packages', href: '#packages' }, { label: 'Questions', href: '#questions' }], cta: { label: 'Reserve a place', href: '#book' } }),
      b('hero', 'hero', { eyebrow: 'Alappuzha, Kerala · fourteen guests only', headline: 'Seven nights. One doctor. Fourteen guests.', subhead: 'A structured Ayurvedic retreat on the backwaters — consultation on arrival, a treatment plan written for you, and nothing to decide for a week.', align: 'center', minHeight: 'lg', image: img('kanthari-backwater-pavilion'), overlay: 'scrim', cta: { label: 'Reserve a place', href: '#book' } }),
      b('included', 'features', { title: 'What the seven nights include', columns: 3, items: [
        { icon: '🩺', title: 'Doctor-led plan', text: 'A 90-minute consultation with Dr. Anjali Menon (BAMS, 22 years) on day one, and a written plan you take home.' },
        { icon: '💆', title: 'Fourteen treatments', text: 'Two daily therapies — abhyanga, shirodhara, pizhichil — with the same pair of therapists all week.' },
        { icon: '🍲', title: 'Cooked for your dosha', text: 'Three meals a day from the kitchen garden, adjusted after your consultation. No menu, no decisions.' },
        { icon: '🧘', title: 'Yoga twice daily', text: 'Gentle asana at 6:30, pranayama and yoga nidra at 5:00. Optional, but almost everyone goes.' },
        { icon: '🛶', title: 'Backwater mornings', text: 'A canoe at dawn on days three and six, paddled by someone who grew up on this canal.' },
        { icon: '📵', title: 'A quiet phone', text: 'Wifi in the library only. The pavilions are deliberately without it.' },
      ] }),
      b('packages', 'pricing', { title: 'Three ways to stay', subtitle: 'Rates are per person for seven nights and include full board, all treatments and the airport transfer from Kochi. GST extra.', plans: [
        { name: 'Garden pavilion', price: '₹96,000', period: '/7 nights', features: ['Single occupancy', 'Garden-facing room with a verandah', 'Fourteen treatments', 'All meals and yoga'], ctaLabel: 'Reserve', ctaHref: '#book' },
        { name: 'Backwater pavilion', price: '₹1,24,000', period: '/7 nights', features: ['Single occupancy', 'Canal-facing, with its own jetty steps', 'Fourteen treatments plus two extras', 'All meals and yoga', 'Departure consultation'], ctaLabel: 'Reserve', ctaHref: '#book', featured: true },
        { name: 'Sharing, two guests', price: '₹1,78,000', period: '/7 nights, two people', features: ['Twin or king, canal-facing', 'Twenty-eight treatments between you', 'Separate plans — you are not treated as one patient', 'All meals and yoga'], ctaLabel: 'Reserve', ctaHref: '#book' },
      ] }),
      b('proof', 'testimonials', { title: 'From guests who finished the week', items: [
        { quote: 'I arrived sceptical and spent two days waiting for the sales pitch. It never came. By Thursday I was sleeping through the night for the first time in a year.', author: 'Ritu K.', role: 'Bengaluru · March retreat' },
        { quote: 'The consultation was more thorough than any I have had at home, and the plan came with a paragraph explaining every single item. I still follow half of it.', author: 'Tobias L.', role: 'Hamburg · returned twice' },
        { quote: 'Fourteen guests means the therapists actually remember what you told them on Monday. That is the whole difference.', author: 'Meera D.', role: 'Chennai' },
      ] }),
      b('press', 'logos', { title: 'Written up in', items: [
        { src: img('kanthari-press-travel-monthly'), alt: 'Travel magazine masthead', href: '#' },
        { src: img('kanthari-press-weekend-lounge'), alt: 'Weekend supplement masthead', href: '#' },
        { src: img('kanthari-press-ayur-journal'), alt: 'Ayurveda journal masthead', href: '#' },
        { src: img('kanthari-press-slow-travel'), alt: 'Slow travel publication masthead', href: '#' },
      ] }),
      b('questions', 'accordion', { title: 'The things people email to ask', items: [
        { heading: 'Do I need to be unwell to come?', body: 'No. Roughly half our guests come with something specific — sleep, digestion, joint pain, burnout — and half come because they want a reset. The consultation shapes the week either way.' },
        { heading: 'Is seven nights really the minimum?', body: 'Yes. Panchakarma has preparation, treatment and recovery phases, and a three-night version is a massage holiday with Sanskrit words attached. We would rather you came next season than came for too short a time.' },
        { heading: 'What if I am pregnant, or on medication?', body: 'Send us the details before you pay. Some therapies are not appropriate in pregnancy or alongside certain medication, and Dr. Menon will tell you honestly if the retreat is not right for you now.' },
        { heading: 'Can you cater for allergies and vegan diets?', body: 'Yes to both, and to Jain food. The kitchen is entirely vegetarian already; tell us on the booking form and your diet plan is built around it.' },
        { heading: 'What is the cancellation policy?', body: 'Full refund up to 45 days before arrival, 50% up to 21 days, and we will move your booking once to any date within a year at no charge.' },
        { heading: 'How do I get there?', body: 'Fly to Kochi (COK). The transfer is included and takes about two hours; the driver waits with your name in arrivals.' },
      ] }),
      b('book', 'booking', { title: 'Reserve a place', intro: 'Retreats run from the first Sunday of each month, September through April. We hold a place for five days while you decide.', serviceLabel: 'Which package', services: [
        { name: 'Garden pavilion', duration: '7 nights', price: '₹96,000' },
        { name: 'Backwater pavilion', duration: '7 nights', price: '₹1,24,000' },
        { name: 'Sharing, two guests', duration: '7 nights', price: '₹1,78,000' },
      ], askDate: true, askTime: false, askParty: true, askPhone: true, askNotes: true, notesLabel: 'Health notes, diet, medication — anything the doctor should see first', submitLabel: 'Hold my place', successMessage: 'Thank you — we will confirm by email within two working days, and hold the place for five.' }),
      b('final', 'cta', { headline: 'Fourteen places a month, and that is the whole calendar', subhead: 'The December and January retreats usually close by the end of September.', background: 'primary', button: { label: 'Reserve a place', href: '#book' } }),
      b('terms', 'legal', { title: 'The small print', align: 'center', separator: ' · ', documents: [
        { label: 'Cancellation policy', title: 'Cancellation & transfers', content: 'Full refund up to 45 days before arrival. 50% refund between 44 and 21 days. No refund within 21 days, but one free transfer to any retreat within twelve months. Refunds are made to the original payment method within 14 working days.' },
        { label: 'Medical disclaimer', title: 'Medical disclaimer', content: 'Ayurvedic treatment at Kanthari is complementary care and does not replace medical advice, diagnosis or treatment from your own physician. Do not stop prescribed medication in order to attend. Guests must disclose pregnancy, cardiac conditions, recent surgery and current medication before booking; we may decline a booking on clinical grounds and will refund it in full.' },
        { label: 'Privacy', title: 'Privacy notice', content: 'Health information you give us is seen only by the consulting physician and your assigned therapists, is stored on paper in a locked room, and is destroyed twelve months after your stay unless you ask us to keep it for a return visit.' },
      ] }),
      b('footer', 'footer', { brand: 'Kanthari Backwater Spa', tagline: 'Doctor-led Ayurvedic retreats, Alappuzha.', links: [{ label: 'Packages', href: '#packages' }, { label: 'Questions', href: '#questions' }, { label: 'Small print', href: '#terms' }], copyright: '© Kanthari Wellness Pvt Ltd · Kerala Tourism reg. AY/ALP/0442' }),
    ],
  }),
];
