/**
 * `manufacturing` starter templates — contract engineering, CNC job shops, batch
 * joinery, food co-packing and a print/packaging plant, from spec sheets to shop-floor photography.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const manufacturingTemplates: Template[] = [
  tpl({
    id: 'manufacturing-industrial',
    vertical: 'manufacturing',
    label: 'Manufacturing — Industrial',
    description: 'A contract manufacturer leading with certifications, capability and on-time delivery numbers.',
    tags: ['b2b', 'industrial', 'engineering', 'cnc'],
    layout: 'classic',
    preset: 'ocean',
    meta: { title: 'Vantage Precision — Contract Manufacturing', description: 'CNC machining and precision assembly for demanding industries.', lang: 'en', favicon: '⚙️' },
    blocks: [
      b('nav', 'nav', { brand: 'Vantage Precision', sticky: true, links: [{ label: 'Capabilities', href: '#capabilities' }, { label: 'Sectors', href: '#sectors' }, { label: 'Contact', href: '#contact' }], cta: { label: 'Request a quote', href: '#contact' } }),
      b('hero', 'hero', { eyebrow: 'ISO 9001 certified', headline: 'Precision parts, delivered on time', subhead: 'CNC machining, fabrication, and assembly for aerospace, medical, and automotive.', align: 'left', minHeight: 'md', image: img('factory-hero'), overlay: 'dark', cta: { label: 'Request a quote', href: '#contact' } }),
      b('capabilities', 'features', { title: 'Capabilities', columns: 3, items: [
        { icon: '🛠️', title: '5-axis CNC', text: 'Tolerances to ±0.005 mm.' },
        { icon: '🔩', title: 'Assembly', text: 'Sub-assembly and full build.' },
        { icon: '🧪', title: 'Inspection', text: 'CMM and full material traceability.' },
      ] }),
      b('stats', 'stats', { title: 'By the numbers', columns: 4, items: [
        { value: '35', label: 'Years operating', suffix: '+' },
        { value: '99.2', label: 'On-time delivery', suffix: '%' },
        { value: '24', label: 'CNC centres' },
        { value: '3', label: 'Shifts, 24/5' },
      ] }),
      b('logos', 'logos', { title: 'Trusted by', items: [{ src: img('vantage-client-aero'), alt: 'Meridian Aerostructures' }, { src: img('vantage-client-medical'), alt: 'Halden Medical Devices' }, { src: img('vantage-client-auto'), alt: 'Coventry Driveline Systems' }, { src: img('vantage-client-energy'), alt: 'Northsea Turbine Services' }] }),
      b('sectors', 'services-catalogue', { title: 'Sectors we serve', items: [
        { name: 'Aerospace', description: 'AS9100-aligned processes and traceability.' },
        { name: 'Medical', description: 'Cleanroom assembly and validation support.' },
        { name: 'Automotive', description: 'PPAP and high-volume production runs.' },
      ] }),
      b('contact', 'contact-details', { title: 'Talk to engineering', address: 'Vantage Works, Coventry CV3 4AA', phone: '+44 24 7600 0000', email: 'quotes@vantageprecision.com', hours: 'Mon–Fri 8:00–17:00' }),
      b('footer', 'footer', { brand: 'Vantage Precision', tagline: 'Contract manufacturing.', links: [{ label: 'Capabilities', href: '#capabilities' }, { label: 'Contact', href: '#contact' }], copyright: '© Vantage Precision Ltd' }),
    ],
  }),

  tpl({
    id: 'manufacturing-cnc-shop',
    vertical: 'manufacturing',
    label: 'CNC Machine Shop — Spec sheet',
    description: 'A precision job shop whose page is the capability list: machines, materials, tolerances, then an RFQ form.',
    tags: ['cnc', 'machining', 'b2b', 'prototyping', 'quote'],
    layout: 'catalogue',
    preset: 'mono',
    meta: { title: 'Axis Seven Machine Works — Precision CNC, Grand Rapids MI', description: 'Prototype and low-volume CNC machining in aluminium, stainless and engineering plastics. Quotes back in one business day.', lang: 'en', favicon: '🛠️' },
    blocks: [
      b('nav', 'nav', { brand: 'Axis Seven', sticky: true, links: [{ label: 'Machines', href: '#machines' }, { label: 'Materials', href: '#materials' }, { label: 'Tolerances', href: '#tolerances' }, { label: 'RFQ', href: '#rfq' }], cta: { label: 'Upload a drawing', href: '#rfq' } }),
      b('notice', 'announcement-bar', { text: 'Current lead time: 8 business days on 3-axis work, 12 on 5-axis.', linkLabel: 'Get a quote', href: '#rfq', tone: 'info', dismissible: true }),
      b('hero', 'hero', { eyebrow: 'ITAR registered · AS9100D', headline: 'Send us a STEP file. Get a price by tomorrow.', subhead: 'Prototype and low-volume production machining out of a 14,000 sq ft shop in Grand Rapids, Michigan.', align: 'left', minHeight: 'sm', overlay: 'none', cta: { label: 'Start an RFQ', href: '#rfq' } }),
      b('machines', 'services-catalogue', { title: 'What is on the floor', subtitle: 'Nine machines, all with in-process probing. Pricing shown is our shop rate — most jobs quote below it.', items: [
        { name: 'Haas UMC-750 · 5-axis mill', description: 'Envelope 30 × 20 × 20 in. Single-setup work on complex housings and manifolds.', price: '$95 / hr', ctaLabel: 'Quote a 5-axis part', ctaHref: '#rfq' },
        { name: 'Haas VF-4SS · 3-axis mill (×4)', description: '12,000 rpm, 30-tool changer. Our workhorse for plates, brackets and fixtures.', price: '$72 / hr', ctaLabel: 'Quote a milled part', ctaHref: '#rfq' },
        { name: 'Doosan Puma 2600 · turning centre', description: 'Live tooling and sub-spindle, 10 in chuck, 3 in bar feed for repeat shaft work.', price: '$78 / hr', ctaLabel: 'Quote a turned part', ctaHref: '#rfq' },
        { name: 'Swiss lathe cell · Citizen L20', description: 'Ø20 mm bar, lights-out overnight. Best value on runs of 500 and up.', price: '$0.85 / pc typical', ctaLabel: 'Quote a Swiss run', ctaHref: '#rfq' },
        { name: 'Zeiss Contura CMM', description: 'First-article inspection with a full AS9102 report, included on any order over 25 pieces.', price: 'Included', ctaLabel: 'Ask about FAI', ctaHref: '#rfq' },
      ] }),
      b('materials', 'tabs', { items: [
        { label: 'Aluminium', text: '6061-T6 and 7075-T6 in plate and bar, stocked. 2024 and MIC-6 cast tooling plate on two-day call-off. Anodising (clear, black, red) and chem film come back from our plater in 4 days.' },
        { label: 'Stainless & steel', text: '303, 304 and 316L stainless; 17-4 PH in H900 or solution-annealed. 4140 pre-hard and A36 for fixtures. Passivation to AMS 2700 and black oxide are both sublet with certs returned.' },
        { label: 'Plastics', text: 'Delrin, UHMW, PEEK, Ultem 1000 and cast acrylic. We keep separate tooling and coolant for plastics so there is no metallic pickup on medical and optical parts.' },
        { label: 'Customer-supplied', text: 'Happy to cut your material. Send it with the mill cert and a packing slip referencing the PO; we log heat numbers on receipt and return the drops with the shipment.' },
      ] }),
      b('tolerances', 'accordion', { title: 'The boring details that decide whether we are a fit', items: [
        { heading: 'What tolerances do you hold as standard?', body: 'Unless the drawing says otherwise we work to ±0.005 in (±0.13 mm) on milled features and ±0.002 in on turned diameters. We will hold ±0.0005 in on critical features — call it out on the print and expect it to move the price roughly 15%.' },
        { heading: 'What surface finish should I expect?', body: '125 Ra as-machined on most faces, 63 Ra where a print calls it. Bead blast, tumble and hand-polish to 32 Ra are all available in house.' },
        { heading: 'What file formats do you take?', body: 'STEP or Parasolid for geometry plus a dimensioned PDF for inspection. Native SolidWorks and Fusion files are fine too. Model-based definition with PMI is welcome — we will confirm we can read the annotations before quoting.' },
        { heading: 'Do you do one-offs?', body: 'Yes. Roughly a third of what leaves the shop is a quantity of one. There is a $180 minimum order so a single small bracket rarely makes sense, but a single complex housing usually does.' },
        { heading: 'Who owns the fixturing?', body: 'We build soft jaws and fixtures at cost and keep them on the shelf for two years, so the second order runs cheaper than the first. You are welcome to buy them outright if you ever move the work.' },
      ] }),
      b('numbers', 'stats', { title: 'Last twelve months', columns: 4, items: [
        { value: '1', label: 'Business days to quote', suffix: 'd' },
        { value: '98.6', label: 'On-time shipments', suffix: '%' },
        { value: '0.31', label: 'Parts rejected', suffix: '%' },
        { value: '412', label: 'Jobs run' },
      ] }),
      b('reviews', 'reviews', { title: 'What buyers say', average: '4.9', count: '61 reviews', source: 'Google', items: [
        { rating: 5, quote: 'We sent a manifold that two other shops declined. Axis Seven came back with three DFM notes, quoted it in a day, and shipped early. The FAI package was the cleanest I have seen.', author: 'Renee Alvarado, Supply Chain Lead', date: 'March 2026', source: 'google' },
        { rating: 5, quote: 'Low-volume medical work with real traceability, and they never once made me chase a status update.', author: 'Devin Park', date: 'January 2026', source: 'google' },
        { rating: 4, quote: 'Pricing is not the cheapest we found, but the scrap rate is basically zero, which more than pays for it over a year.', author: 'Hollis Nakamura', date: 'November 2025', source: 'google' },
      ] }),
      b('rfq', 'contact-form', { title: 'Request a quote', intro: 'Tell us the quantity and material and we will come back inside one business day — with DFM notes if we spot something that would make the part cheaper.', submitLabel: 'Send RFQ', successMessage: 'Got it. Expect a quote from an estimator by tomorrow afternoon.', fields: [
        { name: 'name', label: 'Your name', type: 'text', required: true },
        { name: 'company', label: 'Company', type: 'text', required: true },
        { name: 'email', label: 'Work email', type: 'email', placeholder: 'you@company.com', required: true },
        { name: 'process', label: 'Process needed', type: 'select', options: ['3-axis milling', '5-axis milling', 'Turning', 'Swiss turning', 'Not sure — please advise'], required: true },
        { name: 'quantity', label: 'Quantity', type: 'text', placeholder: 'e.g. 1 prototype, then 250', required: true },
        { name: 'material', label: 'Material', type: 'text', placeholder: '6061-T6, 316L, PEEK…' },
        { name: 'notes', label: 'Anything else we should know?', type: 'textarea', placeholder: 'Target date, tolerances, finishing…' },
      ] }),
      b('footer', 'footer', { brand: 'Axis Seven Machine Works', tagline: '2280 Roger B Chaffee Memorial Dr SE, Grand Rapids, MI 49507 · (616) 555-0142', links: [{ label: 'Machines', href: '#machines' }, { label: 'Materials', href: '#materials' }, { label: 'Tolerances', href: '#tolerances' }, { label: 'RFQ', href: '#rfq' }], copyright: '© Axis Seven Machine Works LLC' }),
    ],
  }),

  tpl({
    id: 'manufacturing-joinery',
    vertical: 'manufacturing',
    label: 'Joinery Workshop — Showcase',
    description: 'A batch joinery and shopfitting workshop selling on photography of finished installs and the craft behind them.',
    tags: ['joinery', 'carpentry', 'gallery', 'showcase', 'b2b'],
    layout: 'showcase',
    preset: 'sand',
    meta: { title: 'Blackwattle Joinery — Custom Shopfitting & Cabinetry, Sydney', description: 'A 24-person joinery workshop in Marrickville producing hospitality fitouts, retail joinery and architectural cabinetry.', lang: 'en', favicon: '🪵' },
    blocks: [
      b('nav', 'nav', { brand: 'Blackwattle Joinery', sticky: true, links: [{ label: 'Work', href: '#work' }, { label: 'Process', href: '#process' }, { label: 'Workshop', href: '#workshop' }, { label: 'Visit', href: '#visit' }], cta: { label: 'Start a project', href: '#visit' } }),
      b('hero', 'hero', { eyebrow: 'Marrickville, Sydney · since 2009', headline: 'Drawn by architects. Made by hand and machine.', subhead: 'Hospitality fitouts, retail joinery and architectural cabinetry, batched through a 900 m² workshop.', align: 'center', minHeight: 'full', image: img('joinery-hero-bench'), overlay: 'scrim', cta: { label: 'See recent work', href: '#work' } }),
      b('work', 'gallery', { layout: 'masonry', columns: 3, gap: 'lg', lightbox: true, items: [
        { src: img('joinery-cafe-counter'), alt: 'Curved terrazzo and blackbutt café counter', caption: 'Ombra Coffee, Newtown — blackbutt and terrazzo counter, 2026' },
        { src: img('joinery-library-shelving'), alt: 'Floor-to-ceiling library shelving in a public building', caption: 'Inner West Council library — 62 linear metres of shelving' },
        { src: img('joinery-retail-vitrine'), alt: 'Brass-framed retail display cabinet', caption: 'Aster & Vine, Paddington — brass-framed vitrines' },
        { src: img('joinery-hotel-headboards'), alt: 'Fluted timber headboard in a hotel room', caption: 'The Cleveland Hotel — 84 fluted American oak headboards' },
        { src: img('joinery-kitchen-island'), alt: 'Kitchen island with waterfall stone top', caption: 'Private residence, Balmain — spotted gum and stone' },
        { src: img('joinery-boardroom-table'), alt: 'Long boardroom table in solid timber', caption: '4.2 m single-slab boardroom table, Barangaroo' },
      ] }),
      b('materials-carousel', 'carousel', { title: 'Timbers we keep racked', autoplay: false, items: [
        { src: img('joinery-timber-blackbutt'), alt: 'Blackbutt boards', caption: 'Blackbutt — pale, hard-wearing, our default for hospitality' },
        { src: img('joinery-timber-spotted-gum'), alt: 'Spotted gum boards', caption: 'Spotted gum — warm and figured, beautiful oiled' },
        { src: img('joinery-timber-oak'), alt: 'American oak boards', caption: 'American white oak — quarter-sawn, kiln-dried to 10%' },
        { src: img('joinery-timber-vic-ash'), alt: 'Victorian ash boards', caption: 'Victorian ash — the value option, takes a stain evenly' },
      ] }),
      b('workshop-film', 'video', { provider: 'vimeo', src: 'https://vimeo.com/blackwattle-week-in-the-workshop', title: 'A week in the workshop', poster: img('joinery-workshop-floor'), caption: 'Six minutes on the floor: CNC nesting, edgebanding, hand fitting, and a hotel install at 4am.' }),
      b('process', 'split', { rows: [
        { title: 'We start on the drawings, not the timber', text: 'Every job begins with our detailer marking up your architectural set in shop-drawing form — junctions, tolerances, service penetrations, the lot. You sign off on those before we cut anything, which is why our variation rate sits under 3%.', image: img('joinery-shop-drawings'), imageAlt: 'Shop drawings marked up on a desk' },
        { title: 'Nested, machined, then finished by hand', text: 'Sheet goods go through a Biesse Rover for nesting and a Homag edgebander. Solid timber is still hand-fitted at the bench by a maker who owns the job from first cut to install — no anonymous handoffs.', image: img('joinery-cnc-nesting'), imageAlt: 'CNC router nesting sheet material' },
        { title: 'Installed by the people who built it', text: 'Our own install crews, our own trucks, and we work overnight for retail and hospitality so you trade the next morning. Defect lists are closed within ten working days of handover.', image: img('joinery-install-night'), imageAlt: 'Install crew fitting cabinetry at night' },
      ] }),
      b('workshop', 'timeline', { title: 'How the shop grew', items: [
        { date: '2009', title: 'Two benches in a Tempe lock-up', text: 'Started with residential kitchens and a second-hand panel saw.' },
        { date: '2014', title: 'First hospitality fitout', text: 'A 40-seat café in Enmore. Word of mouth from that one job kept us busy for three years.' },
        { date: '2018', title: 'Moved to Marrickville', text: '900 m² with a spray booth, which let us stop sublet-finishing and control the whole job.' },
        { date: '2022', title: 'CNC and a detailing team', text: 'Two detailers on staff meant we could take architect-led work at volume.' },
        { date: '2025', title: 'Twenty-four people', text: 'Eight apprentices among them — we put two through their Cert III every year.' },
      ] }),
      b('words', 'testimonials', { title: 'From the people who specify us', items: [
        { quote: 'They read a drawing properly, which sounds like a low bar until you have worked with a joiner who does not. The shop drawings came back with three problems we had missed in our own set.', author: 'Priya Raman', role: 'Associate, Halcyon Architects' },
        { quote: 'Eighty-four headboards, delivered in four staged drops, not one damaged. The site manager still talks about it.', author: 'Tom Beaumont', role: 'Project Manager, Rivergate Construction' },
        { quote: 'We opened on the Saturday we said we would open. That was entirely down to their install crew working two nights straight.', author: 'Ilaria Costa', role: 'Owner, Ombra Coffee' },
      ] }),
      b('where', 'map', { query: 'Marrickville NSW 2204, Australia', zoom: 14, height: 380, label: 'The workshop — 12 Sydenham Road, Marrickville' }),
      b('visit', 'contact-details', { title: 'Come and see the shop', address: '12 Sydenham Road, Marrickville NSW 2204', phone: '+61 2 9555 0188', email: 'projects@blackwattlejoinery.com.au', hours: 'Workshop visits Tue–Thu 9:00–15:00, by arrangement' }),
      b('footer', 'footer', { brand: 'Blackwattle Joinery', tagline: 'Custom joinery and shopfitting, made in Sydney.', links: [{ label: 'Work', href: '#work' }, { label: 'Process', href: '#process' }, { label: 'Visit', href: '#visit' }], copyright: '© Blackwattle Joinery Pty Ltd · ABN 41 622 004 118' }),
    ],
  }),

  tpl({
    id: 'manufacturing-copacking',
    vertical: 'manufacturing',
    label: 'Food Production — Co-packing',
    description: 'A contract food manufacturer explaining, at length, how a small brand gets from kitchen recipe to retail-ready pallets.',
    tags: ['food', 'co-packing', 'long-form', 'b2b', 'newsletter'],
    layout: 'editorial',
    preset: 'forest',
    meta: { title: 'Nilgiri Foodworks — Contract Food Manufacturing', description: 'FSSAI-licensed, BRCGS-certified co-packing for sauces, spice blends and ready-to-cook meals. Coimbatore, Tamil Nadu.', lang: 'en', favicon: '🥫' },
    blocks: [
      b('nav', 'nav', { brand: 'Nilgiri Foodworks', sticky: false, links: [{ label: 'About', href: '#about' }, { label: 'How it works', href: '#process' }, { label: 'Notes', href: '#notes' }, { label: 'Enquire', href: '#contact' }], cta: { label: 'Book a discovery call', href: '#contact' } }),
      b('hero', 'hero', { eyebrow: 'Contract manufacturing · Coimbatore', headline: 'You perfected the recipe. We make ten thousand jars of it taste identical.', subhead: 'Co-packing for sauces, chutneys, spice blends and retort meals — from a 2,000-jar pilot run to full national supply.', align: 'left', minHeight: 'md', overlay: 'none' }),
      b('opening', 'rich-text', { blocks: [
        { kind: 'heading', text: 'Most food brands die in the gap between a recipe and a purchase order' },
        { kind: 'paragraph', text: 'The recipe works. Friends love it. A buyer at a retail chain has said the words "send me a sample and your costings". And then the founder discovers that scaling a pot of chutney to a 500-litre kettle is not multiplication — it is a different problem, with different physics, different microbiology and a paperwork trail that nobody warned them about.' },
        { kind: 'paragraph', text: 'That gap is the only thing we do. Nilgiri Foodworks has been a dedicated contract manufacturer since 2011: we own no brands of our own, we compete with none of our customers, and roughly a third of the labels on a modern Indian grocery shelf in the ambient sauces aisle have been through our kettles at some point.' },
        { kind: 'subheading', text: 'What "co-packing" actually covers here' },
        { kind: 'bullet', text: 'Recipe scale-up and bench trials, with a food technologist who will tell you honestly when an ingredient will not survive a hot-fill.' },
        { kind: 'bullet', text: 'Procurement against your spec — or against ours, if you would rather not manage forty vendors.' },
        { kind: 'bullet', text: 'Production, filling, capping, labelling, shrink-wrap and palletising under one roof.' },
        { kind: 'bullet', text: 'Shelf-life validation, nutritional panels, allergen matrices and the FSSAI label artwork check.' },
        { kind: 'quote', text: 'We are boring on purpose. Boring is what a buyer means when they say "consistent supply".' },
        { kind: 'paragraph', text: 'What we do not do is take equity, take your recipe, or lock you into a term you cannot leave. The formulation stays yours in writing, and you can walk with it — including the scaled version we developed with you — on thirty days notice.' },
      ] }),
      b('about', 'about', { eyebrow: 'The plant', title: 'Four lines, one building, 14,000 sq ft', body: 'Two hot-fill lines for sauces and chutneys (500 L and 1,200 L jacketed kettles), a dry blending and packing line for spice and masala, and a retort line for ready-to-cook pouches rated to 121°C. The site is BRCGS AA-graded, FSSAI-licensed, and holds USFDA facility registration and an APEDA organic scope, so a product made here can be exported without a second audit. Allergen segregation is physical, not scheduled: nut and sesame work runs in a separate room with its own air handling and its own staff uniforms.', image: img('copack-plant-floor'), imageAlt: 'Stainless steel jacketed kettles on a production floor', imageSide: 'right' }),
      b('process', 'steps', { title: 'From your kitchen to a retail pallet', subtitle: 'Typically fourteen to eighteen weeks, and we will tell you at week two if it is going to be longer.', items: [
        { title: '1 · Discovery call', text: 'Forty-five minutes on your recipe, target price, pack format and volume. Free, and we will say no here if we are the wrong plant for you.' },
        { title: '2 · Bench trial', text: '₹35,000, refunded against your first production run. You get three formulation variants, a costed BOM and honest notes on what will change at scale.' },
        { title: '3 · Pilot run', text: 'A 2,000-unit batch on the real line, so you have sellable stock and a genuine cost per unit rather than an estimate.' },
        { title: '4 · Shelf-life & compliance', text: 'Accelerated and real-time studies, nutritional analysis from a NABL lab, label artwork checked against FSSAI display rules.' },
        { title: '5 · Scheduled production', text: 'Rolling forecast, twelve-week visibility, minimum 5,000 units per run. Stock ships from our warehouse or straight to your 3PL.' },
      ] }),
      b('capability', 'split', { rows: [
        { title: 'Traceability that survives a recall drill', text: 'Every batch carries a lot code that resolves back to the goods-in docket for each raw material, the operator on the line, the kettle temperature log and the pallet it left on. We run a mock recall every quarter and close it in under three hours — the certification scheme allows four.', image: img('copack-batch-records'), imageAlt: 'Batch record folders and a lot-code label' },
        { title: 'Small runs are welcome, not tolerated', text: 'Plenty of plants quote a small brand politely and then never schedule it. Our minimum is genuinely 5,000 units and about 40% of our runs are at or near it. Changeovers are costed into the shop rate rather than billed as a penalty, so a short run is expensive per unit but never punitive.', image: img('copack-filling-line'), imageAlt: 'Jars moving along a filling line' },
      ] }),
      b('faq', 'faq', { title: 'The questions founders actually ask', items: [
        { question: 'Do you take ownership of my recipe?', answer: 'No. The formulation, including any scaled or reformulated version we develop together, is yours and is assigned to you in the manufacturing agreement. We hold it under NDA, in a locked formulation system that our production staff can read but not export.' },
        { question: 'What does a run actually cost?', answer: 'For a 250 g hot-filled sauce at 5,000 units, expect ₹28–₹42 per unit all-in including glass, cap, label and shrink — the spread is almost entirely ingredient cost. We give you a line-by-line BOM, not a single number, so you can see exactly where the money goes.' },
        { question: 'Can you source packaging?', answer: 'Yes, and we usually should — our glass and closure pricing at volume is better than a young brand can get alone. You are free to nominate your own supplier; we just need the spec sheet and a sample for line trials four weeks ahead.' },
        { question: 'Will you export for me?', answer: 'We manufacture export-compliant and hand over documentation — health certificate, certificate of origin, phytosanitary where needed. We are not a freight forwarder, but we work with three regularly and will introduce you.' },
        { question: 'What if my product fails its shelf-life study?', answer: 'It happens, usually on water activity or on a preservative-free brief that was never going to hold. We reformulate once at no charge. If the brief itself is impossible we will tell you at bench-trial stage rather than take the production booking.' },
      ] }),
      b('notes', 'blog-list', { title: 'Notes from the plant', columns: 3, posts: [
        { title: 'Why your chutney separates at 5,000 jars but never did at five', excerpt: 'Shear rate, pectin behaviour and the unglamorous truth about hydrocolloid stabilisers in a jacketed kettle.', href: '#', image: img('copack-note-chutney'), date: '4 June 2026', tag: 'Formulation' },
        { title: 'Reading an FSSAI label rejection', excerpt: 'The six things that get artwork bounced, ranked by how often we see them. Font size on the nutritional panel is number one, every time.', href: '#', image: img('copack-note-labels'), date: '21 April 2026', tag: 'Compliance' },
        { title: 'What a co-packer wishes you knew before the first call', excerpt: 'Bring a target retail price and a pack format. Bring those two and we can be useful in twenty minutes.', href: '#', image: img('copack-note-firstcall'), date: '9 February 2026', tag: 'Getting started' },
      ] }),
      b('subscribe', 'newsletter', { title: 'The Kettle Notes', intro: 'One email a month for food founders: costing breakdowns, regulation changes, and what is happening to ingredient prices. No sales pitch, unsubscribe in one click.', placeholder: 'you@yourbrand.in', submitLabel: 'Send it to me', successMessage: 'Subscribed. The next issue goes out on the first Tuesday of the month.' }),
      b('contact', 'contact-details', { title: 'Talk to the technical team', address: 'Plot 44, SIDCO Industrial Estate, Kurichi, Coimbatore 641021, Tamil Nadu', phone: '+91 422 400 0188', email: 'newbrands@nilgirifoodworks.in', hours: 'Mon–Sat 9:00–18:00 IST · plant runs two shifts' }),
      b('footer', 'footer', { brand: 'Nilgiri Foodworks', tagline: 'Contract food manufacturing since 2011. FSSAI 10015021000944 · BRCGS AA.', links: [{ label: 'About', href: '#about' }, { label: 'How it works', href: '#process' }, { label: 'Notes', href: '#notes' }, { label: 'Enquire', href: '#contact' }], copyright: '© Nilgiri Foodworks Pvt Ltd' }),
    ],
  }),

  tpl({
    id: 'manufacturing-packaging-print',
    vertical: 'manufacturing',
    label: 'Packaging & Print — Plant',
    description: 'A high-volume packaging and printing plant pitching short lead times, run pricing and sustainable substrates.',
    tags: ['packaging', 'printing', 'pricing', 'b2b', 'dark'],
    layout: 'bold',
    preset: 'midnight',
    meta: { title: 'Kastner Druck & Verpackung — Folding Cartons and Labels', description: 'Offset and digital packaging printing from Leipzig: folding cartons, labels and flexible film, from 500 to 5 million units.', lang: 'en', favicon: '📦' },
    blocks: [
      b('nav', 'nav', { brand: 'KASTNER', sticky: true, links: [{ label: 'Products', href: '#products' }, { label: 'Run pricing', href: '#pricing' }, { label: 'Plant', href: '#plant' }, { label: 'Contact', href: '#contact' }], cta: { label: 'Get run pricing', href: '#pricing' } }),
      b('hero', 'hero', { eyebrow: 'Leipzig · founded 1974 · FSC C118402', headline: 'Print that ships in five days, not five weeks', subhead: 'Folding cartons, pressure-sensitive labels and flexible film, offset and digital, from 500 units to five million.', align: 'center', minHeight: 'full', image: img('kastner-press-hall'), overlay: 'dark', cta: { label: 'See run pricing', href: '#pricing' } }),
      b('clients', 'logos', { title: 'Printing for', items: [
        { src: img('kastner-client-brewery'), alt: 'Craft brewery group' },
        { src: img('kastner-client-cosmetics'), alt: 'Natural cosmetics brand' },
        { src: img('kastner-client-pharma'), alt: 'Generic pharmaceuticals manufacturer' },
        { src: img('kastner-client-confectionery'), alt: 'Confectionery producer' },
        { src: img('kastner-client-coffee'), alt: 'Specialty coffee roaster' },
        { src: img('kastner-client-retail'), alt: 'Retail own-label group' },
      ] }),
      b('why', 'features', { title: 'Why work sits here rather than somewhere cheaper', columns: 4, items: [
        { icon: '⚡', title: 'Five-day standard', text: 'Approved artwork Monday, pallets on your dock Friday. Two-day rush on digital.' },
        { icon: '🎯', title: 'ΔE ≤ 1.5, verified', text: 'Closed-loop spectral control on press. Every delivery ships with its colour report.' },
        { icon: '🌱', title: 'Recyclable by default', text: 'Mono-material film and mineral-oil-free inks unless you specifically ask otherwise.' },
        { icon: '🧾', title: 'Priced per run, publicly', text: 'Our tier pricing is on this page. No discovery call needed to find out roughly what it costs.' },
      ] }),
      b('products', 'product', { title: 'What comes off our presses', subtitle: 'Indicative pricing at 10,000 units on standard substrates, excluding VAT and tooling.', columns: 3, items: [
        { name: 'Folding cartons', description: '300–450 gsm GC1/GC2 board, up to 6 colours plus spot UV and hot foil. Braille embossing for pharma.', price: '€0.14 / unit', image: img('kastner-product-cartons'), badge: 'Best seller', ctaLabel: 'Price a carton', ctaHref: '#contact' },
        { name: 'Pressure-sensitive labels', description: 'Roll-fed on wet-strength paper, PP or clear-on-clear. Cold foil and tactile varnish available.', price: '€0.031 / unit', image: img('kastner-product-labels'), ctaLabel: 'Price a label', ctaHref: '#contact' },
        { name: 'Flexible film & pouches', description: 'Recyclable mono-PE laminate, stand-up pouches with zip and degassing valve for coffee.', price: '€0.19 / unit', image: img('kastner-product-pouches'), badge: 'Recyclable', ctaLabel: 'Price a pouch', ctaHref: '#contact' },
        { name: 'Corrugated shelf-ready', description: 'E and B flute, litho-laminated. Perforated shelf-ready packs and display trays.', price: '€0.42 / unit', image: img('kastner-product-corrugated'), ctaLabel: 'Price corrugated', ctaHref: '#contact' },
        { name: 'Sleeves & wraps', description: 'Shrink sleeves and roll-fed wrap-around labels, seam-checked in line.', price: '€0.048 / unit', image: img('kastner-product-sleeves'), ctaLabel: 'Price a sleeve', ctaHref: '#contact' },
        { name: 'Sample & tooling kit', description: 'Cutting die, mock-ups on your final substrate, and a printed colour draw-down. Credited against orders over 25,000 units.', price: '€480', image: img('kastner-product-samples'), badge: 'Start here', ctaLabel: 'Order a kit', ctaHref: '#contact' },
      ] }),
      b('pricing', 'pricing', { title: 'Run pricing, folding cartons', subtitle: 'Per unit, 350 gsm GC1, 4/0 plus matt dispersion varnish, glued and packed. Tooling quoted separately.', plans: [
        { name: 'Digital short run', price: '€0.61', period: 'per unit · 500–2,500', features: ['No plates, no minimum tooling', '48-hour turnaround available', 'Variable data and versioning included', 'Ideal for launches and market tests'], ctaLabel: 'Quote a short run', ctaHref: '#contact' },
        { name: 'Offset standard', price: '€0.14', period: 'per unit · 10k–100k', features: ['Six-colour offset with in-line varnish', 'Spectral colour report per delivery', 'Five working days from approval', 'Free storage and call-off for 90 days'], ctaLabel: 'Quote a standard run', ctaHref: '#contact', featured: true },
        { name: 'Volume contract', price: '€0.086', period: 'per unit · 500,000+', features: ['Annual price lock with a board-index clause', 'Dedicated scheduling slot each week', 'Consignment stock at your DC', 'Quarterly business review with the plant manager'], ctaLabel: 'Talk contract', ctaHref: '#contact' },
      ] }),
      b('plant', 'video-gallery', { title: 'Inside the plant', layout: 'grid', columns: 3, items: [
        { provider: 'youtube', src: 'https://www.youtube.com/watch?v=kastner-makeready-heidelberg', title: 'Makeready on the six-colour Heidelberg, start to first good sheet', poster: img('kastner-video-makeready') },
        { provider: 'youtube', src: 'https://www.youtube.com/watch?v=kastner-diecut-shelfready', title: 'Die-cutting and gluing a shelf-ready carton', poster: img('kastner-video-diecut') },
        { provider: 'youtube', src: 'https://www.youtube.com/watch?v=kastner-brand-red-three-substrates', title: 'How we hit ΔE 1.5 on a brand red across three substrates', poster: img('kastner-video-colour') },
      ] }),
      b('proof', 'reviews', { title: 'Verified buyer feedback', subtitle: 'Collected by our procurement platform after delivery.', average: '4.7', count: '129 ratings', source: 'Trustpilot', items: [
        { rating: 5, quote: 'We moved eleven SKUs of carton work here after our previous printer missed a Christmas window. Two years later, not one late pallet.', author: 'Katrin Löwe, Head of Packaging', date: 'May 2026', source: 'trustpilot' },
        { rating: 5, quote: 'The mono-material pouch they specced kept our recyclability claim intact and cost less than the laminate it replaced. That is a rare combination.', author: 'Bastien Mercier', date: 'February 2026', source: 'trustpilot' },
        { rating: 4, quote: 'Colour matching on our brand red is genuinely the best we have had. Scheduling in December is tight — book early and it is a non-issue.', author: 'Anneke de Vries', date: 'January 2026', source: 'trustpilot' },
      ] }),
      b('cta', 'cta', { headline: 'Send artwork before noon. Get a printed sample in your hands this week.', subhead: 'Upload a PDF and a pack spec — an estimator comes back with firm pricing and a preflight report within four hours.', background: 'accent', button: { label: 'Get run pricing', href: '#contact' } }),
      b('contact', 'contact-details', { title: 'Sales & estimating', address: 'Kastner Druck & Verpackung GmbH, Torgauer Straße 231, 04347 Leipzig, Germany', phone: '+49 341 2200 640', email: 'kalkulation@kastner-verpackung.de', hours: 'Office Mon–Fri 7:00–18:00 · plant runs three shifts, Mon 06:00 – Sat 06:00' }),
      b('social', 'social-links', { title: 'Follow the plant', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'linkedin', href: 'https://www.linkedin.com/company/kastner-verpackung', label: 'Kastner on LinkedIn' },
        { platform: 'youtube', href: 'https://www.youtube.com/@kastnerverpackung', label: 'Press-hall films' },
        { platform: 'instagram', href: 'https://www.instagram.com/kastner.verpackung', label: '@kastner.verpackung' },
        { platform: 'email', href: 'mailto:kalkulation@kastner-verpackung.de', label: 'Email estimating' },
      ] }),
      b('footer', 'footer', { brand: 'Kastner Druck & Verpackung', tagline: 'Folding cartons, labels and film. Leipzig since 1974.', links: [{ label: 'Products', href: '#products' }, { label: 'Run pricing', href: '#pricing' }, { label: 'Plant', href: '#plant' }, { label: 'Contact', href: '#contact' }], copyright: '© Kastner Druck & Verpackung GmbH · HRB 21440 Leipzig' }),
    ],
  }),
];
