/**
 * `nonprofit` starter templates — charities, appeals and community groups, from a
 * volunteer-led rewilding trust to an animal rescue, a food bank, a youth mentoring
 * programme, an emergency relief appeal and a members-run sports club.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const nonprofitTemplates: Template[] = [
  tpl({
    id: 'nonprofit-community',
    vertical: 'nonprofit',
    label: 'Nonprofit — Community',
    description: 'A volunteer-led environmental charity leading with impact numbers and how to get involved.',
    tags: ['nonprofit', 'local', 'volunteer', 'environment'],
    layout: 'classic',
    preset: 'forest',
    meta: { title: 'GreenRoots — Community Rewilding', description: 'Bringing nature back to our neighbourhoods, one patch at a time.', lang: 'en', favicon: '🌱' },
    blocks: [
      b('nav', 'nav', { brand: 'GreenRoots', sticky: true, links: [{ label: 'About', href: '#about' }, { label: 'Our impact', href: '#impact' }, { label: 'Volunteer', href: '#volunteer' }], cta: { label: 'Donate', href: '#donate' } }),
      b('hero', 'hero', { eyebrow: 'Community rewilding', headline: 'Bring nature back to your street', subhead: 'We turn neglected patches into thriving green spaces — with the people who live there.', align: 'center', minHeight: 'lg', image: img('green-hero'), overlay: 'scrim', cta: { label: 'Get involved', href: '#volunteer' } }),
      b('about', 'about', { eyebrow: 'Who we are', title: 'Small patches, big change', body: 'GreenRoots is a volunteer-led charity helping communities reclaim unused land for wildlife and people. Since 2018 we’ve planted trees, sown meadows, and built raised beds on forgotten corners — always led by the neighbours who use them.', image: img('green-about'), imageAlt: 'Volunteers planting', imageSide: 'right' }),
      b('impact', 'stats', { title: 'Our impact so far', columns: 4, items: [
        { value: '64', label: 'Sites rewilded' },
        { value: '12k', label: 'Trees planted', suffix: '+' },
        { value: '2,300', label: 'Volunteers' },
        { value: '38', label: 'Neighbourhoods' },
      ] }),
      b('volunteer', 'steps', { title: 'How a patch happens', items: [
        { title: 'Nominate a space', text: 'Tell us about a neglected patch near you.' },
        { title: 'Plan together', text: 'We design it with the local community.' },
        { title: 'Plant & tend', text: 'A launch day, then ongoing care.' },
      ] }),
      b('team', 'team', { title: 'The core team', columns: 3, members: [
        { name: 'Ife Adeyemi', role: 'Founder & Director', photo: img('np-1'), bio: 'Ecologist and community organiser.' },
        { name: 'Rob Mackay', role: 'Projects Lead', photo: img('np-2'), bio: 'Coordinates sites and volunteers.' },
        { name: 'Sunita Rao', role: 'Partnerships', photo: img('np-3'), bio: 'Works with councils and funders.' },
      ] }),
      b('voices', 'testimonials', { title: 'Voices from the community', items: [
        { quote: 'Our dead-end alley is now a pollinator garden. Kids help water it.', author: 'Denise', role: 'Volunteer' },
        { quote: 'I’ve met more neighbours planting trees than in ten years living here.', author: 'Omar', role: 'Resident' },
      ] }),
      b('donate', 'cta', { headline: 'Help us plant the next patch', subhead: '£10 plants a tree. £50 sows a meadow. Every bit grows.', background: 'primary', button: { label: 'Donate', href: '#' } }),
      b('footer', 'footer', { brand: 'GreenRoots', tagline: 'Community rewilding charity.', links: [{ label: 'Volunteer', href: '#volunteer' }, { label: 'Donate', href: '#donate' }], copyright: '© GreenRoots · Reg. charity 1188000' }),
    ],
  }),

  tpl({
    id: 'nonprofit-animal-rescue',
    vertical: 'nonprofit',
    label: 'Animal Rescue — Rehoming list',
    description: 'An animal shelter whose front page is the list of pets currently looking for a home.',
    tags: ['nonprofit', 'pets', 'adoption', 'faq'],
    layout: 'catalogue',
    preset: 'sand',
    meta: { title: 'Second Chance Animal Rescue — Adopt in Adelaide', description: 'Dogs, cats and the occasional rabbit, all looking for a home in South Australia.', lang: 'en', favicon: '🐾' },
    blocks: [
      b('announce', 'announcement-bar', { text: 'Kitten season is here — we are 40 foster carers short.', linkLabel: 'Foster a litter', href: '#foster', tone: 'warning', dismissible: true }),
      b('nav', 'nav', { brand: 'Second Chance', sticky: true, links: [{ label: 'Adopt', href: '#adopt' }, { label: 'How it works', href: '#process' }, { label: 'Foster', href: '#foster' }, { label: 'Questions', href: '#faq' }], cta: { label: 'Donate', href: '#donate' } }),
      b('hero', 'hero', { eyebrow: '112 animals rehomed this year', headline: 'Meet the ones still waiting', subhead: 'Every animal below is in foster care right now in and around Adelaide. Scroll, read their story, and send an enquiry — we reply within two days.', align: 'left', minHeight: 'md', image: img('rescue-kennel-morning'), overlay: 'dark', cta: { label: 'See who’s available', href: '#adopt' } }),
      b('adopt', 'feed', { title: 'Looking for a home', layout: 'cards', items: [
        { title: 'Bindi', subtitle: 'Kelpie cross · 3 years · $290 adoption fee', text: 'Bindi came in as a stray from the Riverland and has spent four months learning that indoors is safe. She needs a yard, a daily run, and no cats. Brilliant with older kids.', image: img('rescue-dog-bindi'), badge: 'Ready now', href: '#enquire' },
        { title: 'Otto & Pip', subtitle: 'Domestic shorthair · 1 year · $180 for the pair', text: 'Bonded brothers, surrendered when their person moved into care. They must go together. Otto is the brave one; Pip supervises from under the couch.', image: img('rescue-cats-otto-pip'), badge: 'Bonded pair', href: '#enquire' },
        { title: 'Marlow', subtitle: 'Staffy · 7 years · Fee waived', text: 'A senior gentleman with a grey muzzle and one very loud snore. Marlow is on daily arthritis medication, which we fund for life. He wants a couch and a slow walk.', image: img('rescue-dog-marlow'), badge: 'Senior · fee waived', href: '#enquire' },
        { title: 'Clementine', subtitle: 'Mini lop rabbit · 2 years · $60', text: 'Litter-trained, desexed, and unimpressed by dogs. Needs an indoor pen and a companion rabbit — we can help you match her.', image: img('rescue-rabbit-clementine'), badge: 'Indoor only', href: '#enquire' },
      ] }),
      b('process', 'steps', { title: 'How adoption works', subtitle: 'No queues, no first-in-best-dressed. We match on lifestyle.', items: [
        { title: 'Send an enquiry', text: 'Tell us about your home, your hours and any other animals.' },
        { title: 'Meet in foster care', text: 'You visit the animal where they already live, not in a kennel.' },
        { title: 'Trial fortnight', text: 'Two weeks at your place, with us on the phone the whole time.' },
        { title: 'Make it official', text: 'Microchip transfer, desexing certificate and a lifetime helpline.' },
      ] }),
      b('foster', 'split', { rows: [
        { title: 'Foster carers do the real work', text: 'We have no shelter building. Every animal lives in someone’s spare room until they’re rehomed. We cover food, litter, bedding and all vet costs — you provide the couch and the patience. Most placements run four to eight weeks.', image: img('rescue-foster-lounge'), imageAlt: 'A foster carer sitting with a dog on a rug' },
        { title: 'What we ask of you', text: 'A secure yard or an indoor-only space, a car or a friend with one for vet trips, and honesty about what you can handle. Plenty of our carers work full time — we match animals to schedules, not the other way round.', image: img('rescue-foster-vet-run'), imageAlt: 'A cat carrier in the back of a car' },
      ] }),
      b('faq', 'faq', { title: 'Before you enquire', items: [
        { question: 'Do you rehome outside South Australia?', answer: 'Within reason. We regularly transport to Melbourne and Mildura with volunteer drivers. Interstate flights are at the adopter’s cost and we won’t fly brachycephalic breeds.' },
        { question: 'What does the adoption fee cover?', answer: 'Desexing, microchipping, C5 or F3 vaccination, worming, flea treatment and any dental work done while in our care. It rarely covers what we actually spend — Marlow’s vet bill alone was $2,400.' },
        { question: 'I rent. Can I still adopt?', answer: 'Yes. South Australian tenancy law has allowed pets with reasonable conditions since 2024. We just ask for written confirmation from your agent.' },
        { question: 'Can I return an animal if it doesn’t work out?', answer: 'Always, no time limit and no judgement. It is a condition of the adoption contract that they come back to us rather than being resold or surrendered elsewhere.' },
      ] }),
      b('enquire', 'contact-form', { title: 'Enquire about an animal', intro: 'One form per animal, please — it helps us keep track. We answer every enquiry, including the nos.', submitLabel: 'Send enquiry', successMessage: 'Got it. A rehoming volunteer will be in touch within two days.', fields: [
        { name: 'name', label: 'Your name', type: 'text', required: true },
        { name: 'email', label: 'Email', type: 'email', required: true },
        { name: 'phone', label: 'Mobile', type: 'tel', placeholder: '04XX XXX XXX', required: true },
        { name: 'animal', label: 'Which animal?', type: 'select', required: true, options: ['Bindi', 'Otto & Pip', 'Marlow', 'Clementine', 'Not sure yet'] },
        { name: 'home', label: 'Tell us about your home', type: 'textarea', placeholder: 'Yard, other pets, who’s home during the day…', required: true },
        { name: 'rental', label: 'I rent and have my agent’s permission', type: 'checkbox' },
      ] }),
      b('donate', 'cta', { headline: 'Not ready to adopt? Sponsor the vet bill.', subhead: '$25 covers a desexing. $60 covers a dental. $200 keeps Marlow comfortable for a year.', background: 'accent', button: { label: 'Donate to the vet fund', href: '#' } }),
      b('footer', 'footer', { brand: 'Second Chance Animal Rescue', tagline: 'Foster-based rehoming across South Australia. ABN 44 618 902 117.', links: [{ label: 'Adopt', href: '#adopt' }, { label: 'Foster', href: '#foster' }, { label: 'Enquire', href: '#enquire' }, { label: 'Donate', href: '#donate' }], copyright: '© Second Chance Animal Rescue Inc.' }),
    ],
  }),

  tpl({
    id: 'nonprofit-food-bank',
    vertical: 'nonprofit',
    label: 'Food Bank — Where and when',
    description: 'A stripped-back page for a food bank: who can come, when it opens and how to get there.',
    tags: ['nonprofit', 'local', 'one-pager', 'food-bank', 'light'],
    layout: 'minimal',
    preset: 'mono',
    meta: { title: 'Ladywell Food Bank — Open Tuesdays & Fridays', description: 'Free food parcels in SE13. No referral needed, no questions asked.', lang: 'en', favicon: '🥫' },
    blocks: [
      b('nav', 'nav', { brand: 'Ladywell Food Bank', sticky: false, links: [{ label: 'Opening times', href: '#hours' }, { label: 'Find us', href: '#find' }], cta: { label: 'Give food or money', href: '#give' } }),
      b('hero', 'hero', { headline: 'Come as you are. No referral needed.', subhead: 'We are open Tuesday and Friday afternoons at St Mary’s Hall, Ladywell. Bring a bag if you have one. If you can’t get here, call 020 7946 0311 and we will arrange a delivery.', align: 'center', minHeight: 'md', overlay: 'none', cta: { label: 'See opening times', href: '#hours' } }),
      b('what', 'features', { title: 'What you can take', subtitle: 'A standard parcel feeds two people for three days. Take a second if you need it.', columns: 3, items: [
        { icon: '🥫', title: 'Cupboard parcel', text: 'Tinned beans, soup, tuna, pasta, rice, UHT milk, tea, cereal and a jar of sauce.' },
        { icon: '🥕', title: 'Fresh table', text: 'Whatever the market donates that morning — usually veg, bread and eggs. First come, first served.' },
        { icon: '🧴', title: 'Household shelf', text: 'Nappies, period products, washing powder, toothpaste and shampoo. No one has to ask.' },
      ] }),
      b('hours', 'hours', { title: 'When we’re open', timezone: 'Europe/London', note: 'Last parcel goes out 15 minutes before closing. Closed bank holidays and the week between Christmas and New Year.', days: [
        { day: 'mon', closed: true },
        { day: 'tue', open: '13:00', close: '16:00' },
        { day: 'wed', closed: true },
        { day: 'thu', closed: true },
        { day: 'fri', open: '13:00', close: '18:30' },
        { day: 'sat', closed: true },
        { day: 'sun', closed: true },
      ] }),
      b('find', 'directions', { title: 'Finding us', place: 'St Mary’s Hall', address: 'Slagrove Place, Ladywell, London SE13 7HG', mapUrl: 'https://maps.google.com/?q=Slagrove+Place+London+SE13+7HG', directionsLabel: 'Open in maps', appleMaps: true }),
      b('give', 'cta', { headline: 'We run out most Fridays', subhead: 'Donation bins are in the Co-op on Ladywell Road and inside the hall. £5 buys a full cupboard parcel; we buy at wholesale.', background: 'surface', button: { label: 'Donate £5', href: '#' } }),
      b('footer', 'footer', { brand: 'Ladywell Food Bank', tagline: 'Run by volunteers since 2011. Part of the Lewisham food network.', links: [{ label: 'Opening times', href: '#hours' }, { label: 'Find us', href: '#find' }, { label: 'Donate', href: '#give' }], copyright: '© Ladywell Food Bank · Reg. charity 1149822' }),
    ],
  }),

  tpl({
    id: 'nonprofit-youth-mentoring',
    vertical: 'nonprofit',
    label: 'Youth Mentoring — Long read',
    description: 'A mentoring programme told as a long-form story, from first match to first job offer.',
    tags: ['nonprofit', 'long-form', 'youth', 'mentoring', 'newsletter'],
    layout: 'editorial',
    preset: 'ocean',
    meta: { title: 'Neev Setu — Youth Mentoring, Bengaluru', description: 'Pairing school-leavers in Bengaluru with working mentors, for two years, one hour a week.', lang: 'en', favicon: '🪜' },
    blocks: [
      b('nav', 'nav', { brand: 'Neev Setu', sticky: true, links: [{ label: 'The programme', href: '#story' }, { label: 'Two years', href: '#journey' }, { label: 'Questions', href: '#how' }, { label: 'Dispatches', href: '#notes' }], cta: { label: 'Become a mentor', href: '#signup' } }),
      b('hero', 'hero', { eyebrow: 'Est. 2016 · Bengaluru', headline: 'One hour a week, for two years.', subhead: 'That is the whole ask. We match 17-year-olds finishing PU college with someone already doing the work they are curious about — and then we stay out of the way.', align: 'left', minHeight: 'md', image: img('mentor-bengaluru-rooftop'), overlay: 'scrim', cta: { label: 'Read how it works', href: '#story' } }),
      b('story', 'rich-text', { blocks: [
        { kind: 'heading', text: 'Why two years and not a term' },
        { kind: 'paragraph', text: 'Most mentoring schemes run for twelve weeks because that is how long a grant cycle lasts. We tried it in our first year and watched every single pair fall apart at exactly the point they had stopped being polite with each other. Trust is slow. So we made the commitment inconveniently long, and our drop-out rate fell from 60% to 9%.' },
        { kind: 'quote', text: 'The first six months I mostly asked about their exams. It was month eight when they told me they had no idea what a CV was and had been too embarrassed to say so.' },
        { kind: 'paragraph', text: 'We work with students from twelve government and aided PU colleges across east Bengaluru — Ramamurthy Nagar, KR Puram, Mahadevapura. Most are the first in their family to consider a degree. Almost all of them can name the job they want, and none of them know anyone who does it.' },
        { kind: 'subheading', text: 'What a mentor actually does' },
        { kind: 'bullet', text: 'Turns up for a one-hour call or coffee every week, on a day you both pick.' },
        { kind: 'bullet', text: 'Answers questions no one else in their life can answer — what a probation period is, whether a diploma counts, how much to ask for.' },
        { kind: 'bullet', text: 'Makes exactly two introductions a year. Not more. Networks work best used sparingly.' },
        { kind: 'bullet', text: 'Comes to one group session a quarter, so mentees meet each other and not just you.' },
        { kind: 'paragraph', text: 'What a mentor does not do: pay fees, offer jobs at their own company, or fix things. We run a separate hardship fund and a separate placements team precisely so the relationship never becomes transactional.' },
      ] }),
      b('journey', 'timeline', { title: 'Two years, roughly', items: [
        { date: 'Month 0', title: 'Matching weekend', text: 'Forty pairs meet in a room in Indiranagar. We match on curiosity and temperament, never on caste, gender or college rank.' },
        { date: 'Months 1–6', title: 'The polite phase', text: 'Weekly calls, mostly about exams and cricket. We check in monthly and resist the urge to intervene.' },
        { date: 'Months 7–12', title: 'The honest phase', text: 'CVs, applications, the first rejection. Most breakthroughs happen here.' },
        { date: 'Months 13–18', title: 'Doing the thing', text: 'Internships, entrance exams, a first paid freelance job. Mentors switch from advising to reviewing.' },
        { date: 'Months 19–24', title: 'Handover', text: 'The pair agrees what happens next. About a third stay in touch informally for years.' },
      ] }),
      b('how', 'accordion', { title: 'What mentors ask us before signing up', items: [
        { heading: 'I have never mentored anyone. Am I qualified?', body: 'If you have been doing your job for three years you know more than a 17-year-old does. We run a half-day induction covering safeguarding, boundaries and the four conversations that come up in every match.' },
        { heading: 'What if we simply do not get on?', body: 'Tell us at any point and we rematch, quietly and without blame. It happens in roughly one match in fifteen and nobody is asked to explain themselves.' },
        { heading: 'Can I mentor from outside Bengaluru?', body: 'Yes — about a quarter of our mentors are in Pune, Hyderabad or abroad and meet online. You would need to travel for the matching weekend and one group session a year.' },
        { heading: 'Is there a background check?', body: 'Yes. Every mentor completes police verification and two references before being matched, and we re-verify every two years. Sessions in the first three months take place in public or online.' },
      ] }),
      b('voices', 'testimonials', { title: 'From both sides of the match', items: [
        { quote: 'I wanted to do animation and my father wanted me to do B.Com. My mentor didn’t take a side — they just found me three people doing animation so I could ask them myself. I am in my second year at a studio in Koramangala now.', author: 'Keerthana R.', role: 'Mentee, 2021 cohort' },
        { quote: 'I signed up thinking I would be useful. Mostly I have learned how much of my own career was luck and who I happened to know. That has changed how I hire.', author: 'Vivek Menon', role: 'Mentor, four years' },
        { quote: 'Two years sounded absurd when I read it. It is the only reason it worked.', author: 'Nasreen Baig', role: 'Mentor, two cohorts' },
      ] }),
      b('notes', 'blog-list', { title: 'Dispatches', columns: 3, posts: [
        { title: 'What we got wrong about matching on ambition', excerpt: 'For three cohorts we paired people by career goal. The pairs that lasted were the ones matched on how they argue.', date: '14 May 2026', tag: 'Programme', image: img('mentor-note-matching'), href: '#' },
        { title: 'The hardship fund, one year on', excerpt: 'We spent ₹8.4 lakh on exam fees, bus passes and one laptop. Here is every rupee of it.', date: '2 March 2026', tag: 'Money', image: img('mentor-note-hardship'), href: '#' },
        { title: 'Where the 2022 cohort is now', excerpt: 'Thirty-eight mentees, two years on: eleven in degree courses, nineteen working, four doing both.', date: '11 January 2026', tag: 'Outcomes', image: img('mentor-note-cohort'), href: '#' },
      ] }),
      b('signup', 'newsletter', { title: 'Mentor intake opens twice a year', intro: 'June and December, forty places each time. Leave your email and we will write to you a fortnight before applications open — nothing else, roughly six emails a year.', placeholder: 'you@example.com', submitLabel: 'Tell me when it opens', successMessage: 'You’re on the list. Watch for an email in late May.' }),
      b('footer', 'footer', { brand: 'Neev Setu', tagline: 'Youth mentoring across east Bengaluru. Registered under Section 8, CIN U85300KA2016NPL091447.', links: [{ label: 'The programme', href: '#story' }, { label: 'Mentor FAQ', href: '#how' }, { label: 'Dispatches', href: '#notes' }], copyright: '© Neev Setu Foundation' }),
    ],
  }),

  tpl({
    id: 'nonprofit-relief-appeal',
    vertical: 'nonprofit',
    label: 'Disaster Relief — Emergency appeal',
    description: 'A single-purpose emergency appeal page built around one action: give now.',
    tags: ['nonprofit', 'emergency', 'dark', 'pricing'],
    layout: 'landing',
    preset: 'midnight',
    meta: { title: 'Valley Floods Appeal — Aid Direct', description: 'Emergency shelter, clean water and cash grants for 40,000 people displaced in the Aude valley.', lang: 'en', favicon: '🚨' },
    blocks: [
      b('announce', 'announcement-bar', { text: 'Every euro doubled until 31 August — the Fondation Lacaze is matching all gifts.', linkLabel: 'Give now', href: '#give', tone: 'warning', dismissible: false }),
      b('hero', 'hero', { eyebrow: 'Aude valley floods · Day 11', headline: '40,000 people. Eleven days. No power.', subhead: 'Our teams have been in Limoux since the second night. We are running eight water points and a cash-grant desk, and we are funded through Friday. Not past it.', align: 'center', minHeight: 'full', image: img('relief-aude-floodwater'), overlay: 'dark', cta: { label: 'Give now', href: '#give' } }),
      b('impact', 'stats', { title: 'What has been delivered so far', columns: 4, items: [
        { value: '1.2m', label: 'Litres of clean water' },
        { value: '6,400', label: 'Shelter kits handed out' },
        { value: '2,180', label: 'Families paid a cash grant' },
        { value: '96c', label: 'Of every euro reaches the field' },
      ] }),
      b('give', 'pricing', { title: 'Choose an amount', subtitle: 'Matched two-for-one until 31 August. Every tier is unrestricted — we spend it where it is worst that week.', plans: [
        { name: 'Water', price: '€25', period: 'one-off', features: ['Filters 400 litres at a village tap point', 'Two jerrycans and purification tablets', 'Emailed spend report in September'], ctaLabel: 'Give €25', ctaHref: '#', featured: false },
        { name: 'Shelter', price: '€80', period: 'one-off', features: ['One family shelter kit: tarpaulin, rope, ground mat', 'Solar lantern and phone charger', 'Blankets for four people', 'Emailed spend report in September'], ctaLabel: 'Give €80', ctaHref: '#', featured: true },
        { name: 'Cash grant', price: '€250', period: 'one-off', features: ['A full month’s emergency grant for one household', 'Paid by card, spent locally, no vouchers', 'Keeps village shops trading', 'Named on the appeal wall if you wish'], ctaLabel: 'Give €250', ctaHref: '#', featured: false },
        { name: 'Standby', price: '€15', period: 'per month', features: ['Funds the next response before it makes the news', 'Cancel any time, no phone calls from us', 'Quarterly two-page field letter'], ctaLabel: 'Give monthly', ctaHref: '#', featured: false },
      ] }),
      b('where', 'split', { rows: [
        { title: 'Where the money is going this week', text: 'Two tanker runs a day to Couiza and Alet-les-Bains, where the mains are still contaminated. A cash desk at the Limoux gymnasium paying €250 per household by prepaid card. Sixty shelter kits a day to hamlets the road crews have not reached. Nothing is being warehoused.', image: img('relief-water-tanker-limoux'), imageAlt: 'A water tanker parked in a village square' },
        { title: 'Why cash, not crates', text: 'Ninety per cent of the shops in the valley reopened within a week and they need customers as badly as their customers need supplies. A prepaid card costs us €4 to administer and lets a family buy the specific things they lost. Airlifting tinned food from Lyon would cost six times as much and put the same shops out of business.', image: img('relief-cash-desk-gymnasium'), imageAlt: 'A cash grant desk set up in a sports hall' },
      ] }),
      b('partners', 'logos', { title: 'Coordinating with', items: [
        { src: img('relief-logo-prefecture'), alt: 'Préfecture de l’Aude', href: '#' },
        { src: img('relief-logo-croix-rouge'), alt: 'Croix-Rouge française', href: '#' },
        { src: img('relief-logo-secours-populaire'), alt: 'Secours Populaire', href: '#' },
        { src: img('relief-logo-fondation-lacaze'), alt: 'Fondation Lacaze', href: '#' },
      ] }),
      b('faq', 'faq', { title: 'Fair questions to ask before you give', items: [
        { question: 'How much reaches the valley?', answer: '96 cents in the euro on this appeal. Our overhead is carried by a separate unrestricted core fund, and the audited split is published every February.' },
        { question: 'What happens to money raised after the emergency ends?', answer: 'It stays in the Aude for the recovery phase — rebuilding wells, replacing tools, school equipment. If we raise more than the valley can absorb we will say so publicly and ask donors before moving anything.' },
        { question: 'Is my gift really matched?', answer: 'Yes, up to €1.5 million, until 23:59 CEST on 31 August. The matching pot is held by the Fondation Lacaze and the running total is published daily.' },
        { question: 'Can I give goods instead?', answer: 'Please don’t. Sorting and shipping donated clothing costs more than buying new locally, and the valley has no warehouse space left. Cash is genuinely more useful.' },
      ] }),
      b('close', 'cta', { headline: 'The water points close Friday without more funding', subhead: 'Matched two-for-one. Two minutes. No phone calls afterwards, ever.', background: 'primary', button: { label: 'Give to the Valley Floods Appeal', href: '#give' } }),
      b('footer', 'footer', { brand: 'Aid Direct', tagline: 'Emergency response across southern Europe and the Sahel. SIREN 812 447 903.', links: [{ label: 'Give', href: '#give' }, { label: 'Where it goes', href: '#where' }, { label: 'Questions', href: '#faq' }], copyright: '© Aid Direct · Association loi 1901' }),
    ],
  }),

  tpl({
    id: 'nonprofit-sports-club',
    vertical: 'nonprofit',
    label: 'Sports Club — Season showcase',
    description: 'A member-run community sports club selling the season with photos, film and fixture times.',
    tags: ['nonprofit', 'gallery', 'family', 'sports', 'video', 'local'],
    layout: 'showcase',
    preset: 'candy',
    meta: { title: 'Rockaway United SC — Community Soccer Club', description: 'Youth and adult soccer in Rockaway, Queens. Nobody gets cut, everybody plays.', lang: 'en', favicon: '⚽' },
    blocks: [
      b('nav', 'nav', { brand: 'Rockaway United SC', sticky: true, links: [{ label: 'Season', href: '#season' }, { label: 'Teams', href: '#teams' }, { label: 'Field times', href: '#times' }, { label: 'Find the field', href: '#field' }], cta: { label: 'Register', href: '#join' } }),
      b('hero', 'hero', { eyebrow: 'Founded 1994 · Volunteer-run', headline: 'Nobody gets cut. Everybody plays.', subhead: 'Fourteen teams, one field, $75 a season — and a scholarship for any family who needs it, no paperwork.', align: 'center', minHeight: 'lg', image: img('rusc-floodlit-pitch'), overlay: 'dark', cta: { label: 'See the season', href: '#season' } }),
      b('season', 'gallery', { layout: 'masonry', columns: 3, gap: 'md', lightbox: true, items: [
        { src: img('rusc-u10-huddle'), alt: 'A youth team huddled before kickoff', caption: 'U10 Blues before the Beach Cup semifinal' },
        { src: img('rusc-adult-rec-night'), alt: 'Adults playing on a floodlit field at night', caption: 'Thursday adult rec, 8pm, all abilities' },
        { src: img('rusc-goalkeeper-save'), alt: 'A goalkeeper diving for a save', caption: 'Amara, U14, keeping a clean sheet in the rain' },
        { src: img('rusc-sideline-parents'), alt: 'Parents watching from the sideline in folding chairs', caption: 'The famous folding-chair sideline' },
        { src: img('rusc-trophy-night'), alt: 'A team holding a trophy at an awards evening', caption: 'End-of-season night at the Knights of Columbus hall' },
        { src: img('rusc-field-repaint'), alt: 'Volunteers repainting field lines', caption: 'Line-painting Saturday — everyone shows up' },
      ] }),
      b('film', 'video', { provider: 'youtube', src: 'https://www.youtube.com/watch?v=aqz-KE-bpKQ', title: 'A season at Rockaway United', poster: img('rusc-season-film-poster'), caption: 'Six minutes, shot on a phone by our U16 team. Turn the sound up for the last thirty seconds.' }),
      b('teams', 'tabs', { items: [
        { label: 'Youth (U8–U16)', text: 'Ten teams, coed through U10 then split. Practice twice a week at Beach 108th, games Saturday mornings in the Queens Community League. No tryouts and no cuts at any age — if we get too many players for a roster we add a team and find another coach. Cleats and shin guards required; we keep a swap bin of outgrown gear by the equipment shed.' },
        { label: 'Adult rec', text: 'Thursday nights, 8–10pm, year-round under lights. Coed 7-a-side, rolling substitutions, deliberately unserious. Players range from 18 to 61 and about a third had never touched a ball before joining. $40 for the season covers the field permit and the pinnies.' },
        { label: 'Walking soccer', text: 'Tuesdays at 10am, for players over 55 or anyone coming back from injury. No running, no contact, no scoreline announced. Run by two retired members, coffee afterwards at Sayra’s. Free — the club covers it from the general fund.' },
        { label: 'Coaching & refs', text: 'Every coach is a parent or former player. We pay for your USSF Grassroots license and SafeSport certification, and pair you with an experienced coach for a full season before you take a team alone. Teenage members can train as assistant referees from age 14 and get paid $25 a match.' },
      ] }),
      b('word', 'reviews', { title: 'What families say', subtitle: 'Collected in our end-of-season survey and published unedited.', average: '4.8', count: '214', source: 'Season survey 2026', items: [
        { rating: 5, quote: 'My kid is not a good soccer player. They play every single week anyway, and the coach knows their name and what makes them laugh. That is the whole thing.', author: 'Danielle P.', date: 'June 2026', source: 'other' },
        { rating: 5, quote: 'We moved here in January knowing nobody. Six months later half our contacts list is from that sideline.', author: 'Marcus O.', date: 'June 2026', source: 'other' },
        { rating: 4, quote: 'Registration is chaos every August and the field floods twice a winter. Still the best $75 we spend all year.', author: 'Ines R.', date: 'June 2026', source: 'other' },
      ] }),
      b('times', 'hours', { title: 'Field times at Beach 108th', timezone: 'America/New_York', note: 'The field closes for lightning within ten miles — check the feed before you travel. January to March the schedule moves indoors to the PS 114 gym.', days: [
        { day: 'mon', closed: true },
        { day: 'tue', open: '10:00', close: '11:30' },
        { day: 'wed', open: '17:30', close: '20:00' },
        { day: 'thu', open: '17:30', close: '22:00' },
        { day: 'fri', open: '17:30', close: '20:00' },
        { day: 'sat', open: '08:30', close: '15:00' },
        { day: 'sun', open: '09:00', close: '13:00' },
      ] }),
      b('field', 'map', { query: 'Beach 108th Street Playground, Rockaway Park, NY 11694', zoom: 15, height: 380, label: 'Beach 108th Street Field — free street parking on Rockaway Beach Blvd, A train to Beach 105th' }),
      b('social', 'social-links', { title: 'Cancellations go out here first', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'instagram', href: '#', label: '@rockawayunitedsc' },
        { platform: 'facebook', href: '#', label: 'Rockaway United SC' },
        { platform: 'whatsapp', href: '#', label: 'Parents group' },
        { platform: 'email', href: '#', label: 'club@rockawayunitedsc.org' },
      ] }),
      b('join', 'cta', { headline: 'Fall registration is open until August 22', subhead: '$75 youth · $40 adult rec · walking soccer free. Scholarship places are automatic — check the box and nobody will ask you anything.', background: 'accent', button: { label: 'Register a player', href: '#' } }),
      b('footer', 'footer', { brand: 'Rockaway United SC', tagline: 'A 501(c)(3) community soccer club in Rockaway Park, Queens.', links: [{ label: 'Teams', href: '#teams' }, { label: 'Field times', href: '#times' }, { label: 'Register', href: '#join' }, { label: 'Find the field', href: '#field' }], copyright: '© Rockaway United Soccer Club · EIN 11-3298440' }),
    ],
  }),
];
