/**
 * `personal` starter templates — one person selling their own work: CVs, design and
 * photo portfolios, an illustrator's shop, a band EPK, a writer's hire page, a comp card.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const personalTemplates: Template[] = [
  tpl({
    id: 'personal-resume',
    vertical: 'personal',
    label: 'Personal — Résumé / CV',
    description: 'A hiring-ready one-page CV: profile, experience, skills and references.',
    tags: ['resume', 'cv', 'one-pager', 'portfolio', 'remote'],
    layout: 'profile',
    preset: 'mono',
    meta: { title: 'Maya Okafor — Frontend Engineer', description: 'Frontend engineer specialising in design systems and accessible UI.', lang: 'en', favicon: '👩‍💻' },
    blocks: [
      b('nav', 'nav', { brand: 'Maya Okafor', sticky: true, links: [{ label: 'Experience', href: '#experience' }, { label: 'Skills', href: '#skills' }, { label: 'Contact', href: '#contact' }], cta: { label: 'Download CV', href: '#' } }),
      b('header', 'profile-header', { name: 'Maya Okafor', headline: 'Senior Frontend Engineer', location: 'Lisbon, Portugal', summary: 'I build fast, accessible interfaces and the design systems that keep them consistent. 8 years across startups and product teams.', showDownload: true, downloadLabel: 'Download PDF', showShare: true, contacts: [
        { type: 'email', value: 'maya@okafor.dev' },
        { type: 'website', value: 'https://okafor.dev', label: 'okafor.dev' },
        { type: 'github', value: 'https://github.com/mayao', label: 'github.com/mayao' },
        { type: 'linkedin', value: 'https://linkedin.com/in/mayao', label: 'in/mayao' },
        { type: 'location', value: 'Lisbon, Portugal' },
      ] }),
      b('experience', 'experience', { title: 'Experience', items: [
        { role: 'Senior Frontend Engineer', org: 'Northwind', period: '2022 – Present', location: 'Remote', summary: 'Lead for the web platform and design system used across 6 product teams.', bullets: ['Shipped a token-driven design system adopted by every team, cutting UI bugs ~40%.', 'Drove Core Web Vitals work: LCP 3.1s → 1.4s on the marketing site.', 'Mentored 4 engineers; ran the accessibility guild (WCAG 2.2 AA).'] },
        { role: 'Frontend Engineer', org: 'Belltower', period: '2019 – 2022', location: 'Lisbon', bullets: ['Built the customer dashboard (React, TypeScript) from zero to 50k MAU.', 'Introduced visual regression + component testing, dropping regressions in prod.'] },
      ] }),
      b('skills', 'skills', { title: 'Skills', display: 'tags', groups: [
        { name: 'Languages', items: [{ label: 'TypeScript', level: 5 }, { label: 'JavaScript', level: 5 }, { label: 'HTML', level: 5 }, { label: 'CSS', level: 5 }] },
        { name: 'Frameworks', items: [{ label: 'React', level: 5 }, { label: 'Next.js', level: 4 }, { label: 'Svelte', level: 3 }] },
        { name: 'Craft', items: [{ label: 'Design systems', level: 5 }, { label: 'Accessibility', level: 5 }, { label: 'Web performance', level: 4 }] },
      ] }),
      b('timeline', 'timeline', { title: 'Milestones', items: [
        { date: '2024', title: 'Conf talk: “Tokens all the way down”', text: 'Spoke at a 400-seat frontend conference.' },
        { date: '2021', title: 'Launched a11y-charts', text: 'Open-sourced an accessible charting library (3.2k ★).' },
        { date: '2017', title: 'B.Sc. Computer Science', text: 'University of Porto — focus on HCI.' },
      ] }),
      b('work', 'gallery', { layout: 'grid', columns: 3, gap: 'md', lightbox: true, items: [{ src: img('work-1'), alt: 'Design system docs' }, { src: img('work-2'), alt: 'Dashboard UI' }, { src: img('work-3'), alt: 'Charts library' }] }),
      b('references', 'testimonials', { title: 'References', items: [
        { quote: 'Maya raised the bar for the whole frontend org — and lifted everyone around her.', author: 'D. Almeida', role: 'Eng Director, Northwind' },
        { quote: 'The most reliable engineer I’ve worked with. Ships, documents, mentors.', author: 'R. Costa', role: 'Staff Engineer, Belltower' },
      ] }),
      b('contact', 'contact-details', { title: 'Get in touch', email: 'maya@okafor.dev', address: 'Lisbon, Portugal' }),
      b('footer', 'footer', { brand: 'Maya Okafor', tagline: 'Frontend engineer.', links: [{ label: 'GitHub', href: 'https://github.com/mayao' }, { label: 'LinkedIn', href: 'https://linkedin.com/in/mayao' }], copyright: '© Maya Okafor' }),
    ],
  }),

  tpl({
    id: 'personal-designer',
    vertical: 'personal',
    label: 'Graphic Designer — Editorial',
    description: 'A type-led portfolio for an independent brand and identity designer, case studies first.',
    tags: ['portfolio', 'graphic-design', 'branding', 'long-form', 'b2b'],
    layout: 'editorial',
    preset: 'sand',
    meta: { title: 'Noor Habib — Brand & Identity Design', description: 'Independent identity designer in Amsterdam building brands for food, culture and climate.', lang: 'en', favicon: '✒️' },
    blocks: [
      b('nav', 'nav', { brand: 'Noor Habib', sticky: false, links: [{ label: 'Work', href: '#work' }, { label: 'Studio', href: '#studio' }, { label: 'Services', href: '#services' }], cta: { label: 'Start a project', href: '#enquiry' } }),
      b('intro', 'rich-text', { blocks: [
        { kind: 'heading', text: 'I design identities that still make sense five years later.' },
        { kind: 'paragraph', text: 'I’m Noor — an independent designer in Amsterdam. I work with food producers, cultural institutions and climate startups, usually as the only designer in the room, from naming and marks through to the packaging that ships.' },
        { kind: 'paragraph', text: 'Engagements run four to twelve weeks. I take three a quarter, so there is always time to draw badly for a week before anything is shown to anyone.' },
        { kind: 'quote', text: 'A logo is the smallest part of an identity, and the part clients spend 80% of the meeting on. My job is to make the other 20% just as decided.' },
      ] }),
      b('work', 'split', { rows: [
        { title: 'Kaas & Kruid — cheese counter, Utrecht', text: 'A market stall grown into three shops. We built a hand-lettered wordmark, a rotating stamp system for seasonal wheels, and greaseproof wrap that people kept. Footfall at the Utrecht shop rose 22% in the six months after relaunch.', image: img('pers-des-kaas'), imageAlt: 'Cheese wrap and stamped label system' },
        { title: 'Het Veerhuis — arts venue', text: 'A 300-seat venue that had eleven different logos in circulation. One typeface, one grid, one poster template the box office can fill in themselves — and a season programme that now goes to print in two days instead of two weeks.', image: img('pers-des-veerhuis'), imageAlt: 'Concert poster series pinned in a grid' },
        { title: 'Terrafirm — soil carbon startup', text: 'Naming, mark and the whole Series A deck. The brief was “credible to a farmer and to a fund on the same page”, which mostly meant deleting gradients.', image: img('pers-des-terrafirm'), imageAlt: 'Brand guidelines spread open on a desk' },
      ] }),
      b('studio', 'about', { eyebrow: 'Studio', title: 'One designer, no account layer', body: 'You work with me directly — the person who draws the thing is the person on the call. I bring in trusted collaborators for motion, photography and print production, and you always know who is doing what. Based in Amsterdam-Noord, working across the Netherlands, Germany and the UK. Dutch and English, and I read enough German to proofread a label.', image: img('pers-des-studio'), imageAlt: 'Studio desk with proofs pinned to the wall', imageSide: 'left' }),
      b('clients', 'logos', { title: 'Selected clients', items: [
        { src: img('pers-des-logo-1'), alt: 'Kaas & Kruid' },
        { src: img('pers-des-logo-2'), alt: 'Het Veerhuis' },
        { src: img('pers-des-logo-3'), alt: 'Terrafirm' },
        { src: img('pers-des-logo-4'), alt: 'Bakkerij Loos' },
        { src: img('pers-des-logo-5'), alt: 'Noordlicht Festival' },
      ] }),
      b('services', 'tabs', { items: [
        { label: 'Identity', text: 'Naming, wordmark, type and colour system, and a guidelines document short enough that people actually open it. Four to eight weeks, from €9,500.' },
        { label: 'Packaging', text: 'Structure, artwork and print-ready files, with press checks in person for anything running in the Benelux. Priced per SKU family, typically €3,200–€7,000.' },
        { label: 'Retainer', text: 'Two days a month for teams who have an identity and need someone to defend it. Posters, decks, campaign artwork. €2,400 a month, minimum six months.' },
      ] }),
      b('words', 'testimonials', { title: 'What clients say', items: [
        { quote: 'Noor asked better questions in the first hour than our last agency asked in a month. The wrap paper alone got us into two food magazines.', author: 'Sanne de Vries', role: 'Founder, Kaas & Kruid' },
        { quote: 'We handed over eleven logos and a mess of PDFs. We got back a system our volunteers can run without me.', author: 'Thomas Bakker', role: 'Programme Director, Het Veerhuis' },
      ] }),
      b('enquiry', 'contact-form', { title: 'Start a project', intro: 'Tell me roughly what you’re making and when it has to exist. I reply to everything within two working days.', submitLabel: 'Send enquiry', successMessage: 'Thanks — I’ll come back to you within two working days.', fields: [
        { name: 'name', label: 'Your name', type: 'text', required: true },
        { name: 'email', label: 'Email', type: 'email', required: true },
        { name: 'scope', label: 'What do you need?', type: 'select', options: ['Identity', 'Packaging', 'Retainer', 'Not sure yet'] },
        { name: 'budget', label: 'Rough budget', type: 'select', options: ['Under €5,000', '€5,000 – €15,000', '€15,000+'] },
        { name: 'brief', label: 'The short version', type: 'textarea', placeholder: 'Two or three sentences is plenty.', required: true },
      ] }),
      b('footer', 'footer', { brand: 'Noor Habib', tagline: 'Brand & identity design, Amsterdam.', links: [{ label: 'Work', href: '#work' }, { label: 'Services', href: '#services' }, { label: 'Instagram', href: '#' }], copyright: '© Noor Habib · KvK 84 221 907' }),
    ],
  }),

  tpl({
    id: 'personal-photographer',
    vertical: 'personal',
    label: 'Photographer — Showcase',
    description: 'An image-first portfolio for a wedding and portrait photographer, with packages and enquiries.',
    tags: ['photography', 'gallery', 'portfolio', 'booking', 'dark'],
    layout: 'showcase',
    preset: 'midnight',
    meta: { title: 'Tess Okonkwo — Photography', description: 'Wedding and portrait photography in Melbourne and across Victoria.', lang: 'en', favicon: '📷' },
    blocks: [
      b('notice', 'announcement-bar', { text: '2026 wedding dates are open — eight left for autumn.', linkLabel: 'Check your date', href: '#enquire', tone: 'promo', dismissible: true }),
      b('nav', 'nav', { brand: 'Tess Okonkwo', sticky: true, links: [{ label: 'Weddings', href: '#weddings' }, { label: 'Portraits', href: '#portraits' }, { label: 'Packages', href: '#packages' }], cta: { label: 'Enquire', href: '#enquire' } }),
      b('hero', 'hero', { headline: 'Quiet pictures of loud days', subhead: 'Documentary wedding and portrait photography in Melbourne, and anywhere in Victoria worth the drive.', align: 'left', minHeight: 'full', image: img('pers-pho-hero'), overlay: 'scrim', cta: { label: 'See recent weddings', href: '#weddings' } }),
      b('weddings', 'carousel', { title: 'Recent weddings', autoplay: false, items: [
        { src: img('pers-pho-wed-1'), alt: 'Couple leaving a ceremony under confetti', caption: 'Anisha & Dev — Abbotsford Convent' },
        { src: img('pers-pho-wed-2'), alt: 'Guests dancing in low light', caption: 'Sam & Priya — Mount Macedon' },
        { src: img('pers-pho-wed-3'), alt: 'One of the couple laughing with their grandmother', caption: 'Ella & Jo — Daylesford' },
        { src: img('pers-pho-wed-4'), alt: 'Rain running down the window of a wedding car', caption: 'Marcus & Yiwei — Fitzroy' },
      ] }),
      b('portraits', 'gallery', { layout: 'masonry', columns: 3, gap: 'lg', lightbox: true, items: [
        { src: img('pers-pho-por-1'), alt: 'Studio portrait against grey paper', caption: 'Headshot session' },
        { src: img('pers-pho-por-2'), alt: 'Musician holding a double bass', caption: 'Album press shots' },
        { src: img('pers-pho-por-3'), alt: 'Family on a beach at dusk' },
        { src: img('pers-pho-por-4'), alt: 'Chef standing in a kitchen doorway', caption: 'Restaurant editorial' },
        { src: img('pers-pho-por-5'), alt: 'Dancer mid-turn in a rehearsal room' },
        { src: img('pers-pho-por-6'), alt: 'Newborn asleep on a knitted blanket' },
      ] }),
      b('packages', 'services-catalogue', { title: 'Packages', subtitle: 'All prices in AUD and include travel within 60km of the Melbourne CBD.', items: [
        { name: 'Full day wedding', description: 'Ten hours, two photographers, 600+ edited images in four weeks, plus a sneak-peek gallery within 48 hours.', price: 'A$5,400', ctaLabel: 'Check your date', ctaHref: '#enquire' },
        { name: 'Half day wedding', description: 'Five hours, one photographer. Ceremony through to the first hour of the reception. 300+ edited images.', price: 'A$3,200', ctaLabel: 'Check your date', ctaHref: '#enquire' },
        { name: 'Elopement', description: 'Two hours, anywhere in Victoria. Registry, clifftop or backyard — 80 edited images within a week.', price: 'A$1,450', ctaLabel: 'Enquire', ctaHref: '#enquire' },
        { name: 'Portrait session', description: 'Ninety minutes, studio or location. Headshots, families, press. 25 retouched images.', price: 'A$680', ctaLabel: 'Book a session', ctaHref: '#enquire' },
      ] }),
      b('reviews', 'reviews', { title: 'From couples', average: '5.0', count: '74 reviews', source: 'Google', items: [
        { rating: 5, quote: 'We forgot Tess was there, which was the whole point. Then the gallery arrived and every moment we were worried we had missed was in it.', author: 'Anisha R.', date: 'March 2026', source: 'google' },
        { rating: 5, quote: 'It rained for six hours straight. The photos look deliberate. I still do not understand how.', author: 'Marcus L.', date: 'November 2025', source: 'google' },
        { rating: 5, quote: 'Calm, funny, and extremely good at getting a photo of my grandad before he got tired. Worth every dollar.', author: 'Ella T.', date: 'January 2026', source: 'facebook' },
      ] }),
      b('enquire', 'booking', { title: 'Check your date', intro: 'Send your date and location and I’ll come back within 24 hours with availability and the full pricing guide.', submitLabel: 'Send enquiry', successMessage: 'Got it — you’ll hear from me within 24 hours.', serviceLabel: 'What are you after?', services: [
        { name: 'Full day wedding', duration: '10 hours', price: 'A$5,400' },
        { name: 'Half day wedding', duration: '5 hours', price: 'A$3,200' },
        { name: 'Elopement', duration: '2 hours', price: 'A$1,450' },
        { name: 'Portrait session', duration: '90 min', price: 'A$680' },
      ], askDate: true, askTime: false, askParty: true, askPhone: true, askNotes: true, notesLabel: 'Where is it, and what matters most to you?' }),
      b('contact', 'contact-details', { title: 'Studio', address: '14 Sackville Street, Collingwood VIC 3066', phone: '+61 3 9417 0022', email: 'hello@tessokonkwo.com.au', hours: 'Studio visits by appointment, Tue–Thu' }),
      b('footer', 'footer', { brand: 'Tess Okonkwo', tagline: 'Wedding & portrait photography, Melbourne.', links: [{ label: 'Packages', href: '#packages' }, { label: 'Enquire', href: '#enquire' }, { label: 'Instagram', href: '#' }], copyright: '© Tess Okonkwo Photography · ABN 41 992 118 003' }),
    ],
  }),

  tpl({
    id: 'personal-engineer',
    vertical: 'personal',
    label: 'Software Engineer — Minimal',
    description: 'A stripped-back site for a backend engineer: what they build, proof, and one way to hire them.',
    tags: ['portfolio', 'engineering', 'one-pager', 'remote', 'b2b'],
    layout: 'minimal',
    preset: 'forest',
    meta: { title: 'Devin Ashworth — Backend & Infrastructure', description: 'Backend and infrastructure engineer. Distributed systems, Go, Postgres. Available for contract work.', lang: 'en', favicon: '⌘' },
    blocks: [
      b('nav', 'nav', { brand: 'devinash.dev', sticky: false, links: [{ label: 'Projects', href: '#projects' }, { label: 'How I work', href: '#how' }], cta: { label: 'Hire me', href: '#hire' } }),
      b('hero', 'hero', { eyebrow: 'Available from September, two days a week', headline: 'I make slow backends fast and fragile ones boring.', subhead: 'Nine years on distributed systems in Go and Postgres. Contract and fractional work for teams that have product-market fit and a database starting to complain.', align: 'left', minHeight: 'md', overlay: 'none', cta: { label: 'See what I’ve shipped', href: '#projects' } }),
      b('projects', 'feed', { title: 'Recent work', layout: 'list', items: [
        { title: 'Ledger rewrite — payments startup, Berlin', subtitle: '2025 · 7 months', text: 'Moved double-entry accounting off one Postgres table onto partitioned event storage. p99 write latency 840ms → 46ms; month-end close from 9 hours to 20 minutes.', badge: 'Go / Postgres' },
        { title: 'Multi-region failover — logistics SaaS', subtitle: '2024 · 4 months', text: 'Designed and drilled active-passive failover across eu-west and us-east. Two real incidents since, both inside the 90-second RTO, neither noticed by customers.', badge: 'Terraform / AWS' },
        { title: 'pgqueue', subtitle: 'Open source · 2.1k ★', text: 'A job queue that is just Postgres — no Redis, no broker, exactly-once by default. In production at around 200 teams that bothered to tell me.', href: '#', badge: 'Library' },
        { title: 'Query budget linter', subtitle: '2023 · internal tool', text: 'A CI check that fails a pull request when an endpoint’s query count regresses. Killed N+1 regressions in a 400k-line Rails monolith for good.', badge: 'Ruby' },
      ] }),
      b('numbers', 'stats', { columns: 3, items: [
        { value: '9', label: 'Years on backend systems', suffix: 'yr' },
        { value: '46', label: 'p99 write latency after the ledger rewrite', suffix: 'ms' },
        { value: '2.1k', label: 'GitHub stars on pgqueue', suffix: '★' },
      ] }),
      b('how', 'accordion', { title: 'How I work', items: [
        { heading: 'Engagements start with a two-week paid audit', body: 'I read the code, watch the dashboards, and interview whoever gets paged at night. You get a written findings document with the three things worth fixing, ranked, and an estimate for each. Plenty of clients stop there, and that is a perfectly good outcome.' },
        { heading: 'I write the runbook before I write the code', body: 'Anything I build has to be operable by your on-call at 3am without me on the phone. That means the docs, the alerts and the rollback path ship in the same pull request as the feature.' },
        { heading: 'Two days a week, one client at a time', body: 'I hold Tuesdays and Wednesdays. I am not available for full-time roles, I do not take equity in place of rate, and I will tell you early if the work is a poor fit.' },
        { heading: 'Rate and terms', body: '£950/day, invoiced monthly, 14-day terms, contracting through my own limited company. UK, EU and US East timezones. I will not sign an agreement that assigns my open-source work.' },
      ] }),
      b('links', 'social-links', { title: 'Elsewhere', layout: 'row', variant: 'labeled', align: 'start', links: [
        { platform: 'github', href: 'https://github.com/devinash', label: 'github.com/devinash' },
        { platform: 'linkedin', href: 'https://linkedin.com/in/devinash', label: 'in/devinash' },
        { platform: 'mastodon', href: '#', label: '@devin@hachyderm.io' },
        { platform: 'email', href: 'mailto:devin@devinash.dev', label: 'devin@devinash.dev' },
      ] }),
      b('hire', 'cta', { headline: 'Something in your stack gets slower every month', subhead: 'Two-week audit, written findings, no obligation after it. Email me the symptom and I’ll tell you honestly whether I’m the right person.', background: 'primary', button: { label: 'devin@devinash.dev', href: 'mailto:devin@devinash.dev' } }),
      b('footer', 'footer', { brand: 'Devin Ashworth', tagline: 'Backend & infrastructure, Bristol UK.', links: [{ label: 'Projects', href: '#projects' }, { label: 'How I work', href: '#how' }], copyright: '© Devin Ashworth Ltd · Company 11 442 067' }),
    ],
  }),

  tpl({
    id: 'personal-illustrator',
    vertical: 'personal',
    label: 'Illustrator — Commissions & Shop',
    description: 'A working illustrator’s page where the commission tiers and the print shop do the selling.',
    tags: ['illustration', 'portfolio', 'pricing', 'gallery', 'newsletter'],
    layout: 'catalogue',
    preset: 'candy',
    meta: { title: 'Bex Larkin — Illustration & Prints', description: 'Freelance illustrator taking editorial and book commissions, plus a small print shop.', lang: 'en', favicon: '🖍️' },
    blocks: [
      b('notice', 'announcement-bar', { text: 'Commission books open for Q4 — four slots, closing 30 September.', linkLabel: 'See rates', href: '#commissions', tone: 'info', dismissible: true }),
      b('nav', 'nav', { brand: 'Bex Larkin', sticky: true, links: [{ label: 'Commissions', href: '#commissions' }, { label: 'Shop', href: '#shop' }, { label: 'Portfolio', href: '#portfolio' }, { label: 'FAQ', href: '#faq' }], cta: { label: 'Commission a piece', href: '#commissions' } }),
      b('hero', 'hero', { eyebrow: 'Illustration · Glasgow', headline: 'Ink, gouache, and a great many birds', subhead: 'Editorial illustration, children’s books and album art. Four commission slots a quarter; prints in the shop all year round.', align: 'left', minHeight: 'sm', overlay: 'none' }),
      b('commissions', 'services-catalogue', { title: 'Commissions', subtitle: 'Rates for UK clients, including VAT. Half up front, half on delivery of final files.', items: [
        { name: 'Editorial spot', description: 'A single spot illustration for a magazine, newsletter or article. One round of sketches, two of revisions, ten working days.', price: '£340', ctaLabel: 'Enquire', ctaHref: '#enquire' },
        { name: 'Full page or cover', description: 'Cover or full-page piece with print and web files, licensed for one territory and one edition. Three weeks.', price: '£1,100', ctaLabel: 'Enquire', ctaHref: '#enquire' },
        { name: 'Picture book', description: 'Twelve to sixteen spreads, character sheets, roughs and finals, working directly with your editor. Four to six months.', price: 'From £6,500', ctaLabel: 'Enquire', ctaHref: '#enquire' },
        { name: 'Album & merch art', description: 'Sleeve artwork plus the crops for vinyl, streaming and a T-shirt. Independent labels get a rate I can actually justify.', price: 'From £900', ctaLabel: 'Enquire', ctaHref: '#enquire' },
        { name: 'Pet portrait', description: 'Ink and gouache on 300gsm, A4, worked up from your photos and posted anywhere in the UK. Two weeks. Ferrets count.', price: '£185', ctaLabel: 'Enquire', ctaHref: '#enquire' },
      ] }),
      b('shop', 'product', { title: 'Print shop', subtitle: 'Giclée on Hahnemühle 308gsm, signed, posted in a tube within three working days.', columns: 3, items: [
        { name: 'Wintering Starlings — A2', description: 'Six-colour print of the Gretna murmuration. Edition of 100.', price: '£62', image: img('pers-ill-print-1'), badge: 'Bestseller', ctaLabel: 'Add to basket', ctaHref: '#' },
        { name: 'Kelvingrove Fox — A3', description: 'The one that ended up on the cover of Gutter, issue 31.', price: '£38', image: img('pers-ill-print-2'), ctaLabel: 'Add to basket', ctaHref: '#' },
        { name: 'Herring Gull, Portrait — A3', description: 'Unflattering, accurate, and weirdly popular in Aberdeen.', price: '£38', was: '£45', image: img('pers-ill-print-3'), badge: 'Last 12', ctaLabel: 'Add to basket', ctaHref: '#' },
        { name: 'Riso set of three — A5', description: 'Wren, dipper, long-tailed tit. Two-colour risograph, unsigned.', price: '£24', image: img('pers-ill-print-4'), ctaLabel: 'Add to basket', ctaHref: '#' },
        { name: 'Original — Heron at Bowling', description: 'Ink and gouache, 42 × 59cm, framed in oak. One only.', price: '£640', image: img('pers-ill-print-5'), badge: 'Original', ctaLabel: 'Enquire', ctaHref: '#enquire' },
        { name: 'Sketchbook zine no.4', description: '32 pages of roughs, rejects and marginalia. Risograph, edition of 300.', price: '£11', image: img('pers-ill-print-6'), ctaLabel: 'Add to basket', ctaHref: '#' },
      ] }),
      b('portfolio', 'gallery', { layout: 'grid', columns: 4, gap: 'sm', lightbox: true, items: [
        { src: img('pers-ill-work-1'), alt: 'Ink drawing of a heron', caption: 'Gutter magazine' },
        { src: img('pers-ill-work-2'), alt: 'Gouache spread of a woodland scene', caption: 'The Nightjar Wood, Canongate' },
        { src: img('pers-ill-work-3'), alt: 'Album sleeve artwork with birds' },
        { src: img('pers-ill-work-4'), alt: 'Character sheet of a fox in a coat' },
        { src: img('pers-ill-work-5'), alt: 'Editorial spot illustration of a commuter' },
        { src: img('pers-ill-work-6'), alt: 'Two-colour riso print of a wren' },
        { src: img('pers-ill-work-7'), alt: 'Illustrated map of the River Clyde' },
        { src: img('pers-ill-work-8'), alt: 'Sketchbook page of gull studies' },
      ] }),
      b('faq', 'faq', { title: 'Before you commission', items: [
        { question: 'How do I get on the list?', answer: 'Email bex@bexlarkin.co.uk with what you need, when you need it, and where it will be published. If the quarter is full I’ll offer you the next one rather than rushing yours.' },
        { question: 'What am I actually buying?', answer: 'A licence, not the copyright. Editorial rates cover one edition in one territory for a year; anything wider I quote separately. Originals are sold outright, but I keep reproduction rights.' },
        { question: 'Do you work from AI reference or generated roughs?', answer: 'No. Everything starts as pencil on paper, and I am happy to show you the sketchbook pages to prove it.' },
        { question: 'Do you take rush jobs?', answer: 'Sometimes, at +40%. A newspaper spot in 48 hours is doable. A picture book in a fortnight is not.' },
      ] }),
      b('enquire', 'contact-details', { title: 'Commission enquiries', email: 'bex@bexlarkin.co.uk', address: 'Studio 4, Whisky Bond, 2 Dawson Road, Glasgow G4 9SS', hours: 'Studio open Wed–Fri, 10:00–17:00 · post collected daily' }),
      b('news', 'newsletter', { title: 'Shop restocks & open commission slots', intro: 'One email every six weeks or so: new prints, when the books open, and the occasional page from the sketchbook. No discount-code spam.', placeholder: 'you@example.com', submitLabel: 'Sign me up', successMessage: 'Lovely — check your inbox to confirm.' }),
      b('footer', 'footer', { brand: 'Bex Larkin', tagline: 'Illustration & prints, Glasgow.', links: [{ label: 'Commissions', href: '#commissions' }, { label: 'Shop', href: '#shop' }, { label: 'FAQ', href: '#faq' }], copyright: '© Bex Larkin · All artwork remains the artist’s' }),
    ],
  }),

  tpl({
    id: 'personal-musician',
    vertical: 'personal',
    label: 'Musician — Band EPK',
    description: 'A loud electronic press kit: live video, press quotes, tour dates and a booking contact.',
    tags: ['music', 'epk', 'video', 'social', 'dark'],
    layout: 'bold',
    preset: 'midnight',
    meta: { title: 'HOLLOW COAST — Press Kit', description: 'Four-piece post-punk band from Leeds. Live video, press, tour dates and booking.', lang: 'en', favicon: '🎸' },
    blocks: [
      b('nav', 'nav', { brand: 'HOLLOW COAST', sticky: true, links: [{ label: 'Live', href: '#live' }, { label: 'Dates', href: '#dates' }, { label: 'Press', href: '#press' }], cta: { label: 'Booking', href: '#booking' } }),
      b('hero', 'hero', { eyebrow: 'Leeds · Post-punk · Est. 2021', headline: 'HOLLOW COAST', subhead: 'Second album ‘Marine Layer’ out 14 August on Tidal Fault. Thirty-four dates across the UK and EU this autumn.', align: 'center', minHeight: 'full', image: img('pers-mus-hero'), overlay: 'dark', cta: { label: 'Watch the Brudenell set', href: '#live' } }),
      b('numbers', 'stats', { columns: 4, items: [
        { value: '186k', label: 'Monthly listeners' },
        { value: '34', label: 'Dates this autumn' },
        { value: '1,800', label: 'Capacity, biggest headline' },
        { value: '2nd', label: 'Album, out in August' },
      ] }),
      b('live', 'video-gallery', { title: 'Live & video', layout: 'grid', columns: 3, items: [
        { provider: 'youtube', src: 'https://www.youtube.com/watch?v=hollowcoast-brudenell', title: 'Full set — Brudenell Social Club, Leeds', poster: img('pers-mus-vid-1') },
        { provider: 'youtube', src: 'https://www.youtube.com/watch?v=hollowcoast-marinelayer', title: '‘Marine Layer’ — official video', poster: img('pers-mus-vid-2') },
        { provider: 'vimeo', src: 'https://vimeo.com/hollowcoast-session', title: 'Two-song session for Tidal Fault', poster: img('pers-mus-vid-3') },
      ] }),
      b('dates', 'feed', { title: 'Autumn tour', layout: 'cards', items: [
        { title: 'Manchester — YES (Pink Room)', subtitle: 'Fri 12 Sep', text: 'With Sunk Cost. Doors 7:30pm, 14+.', href: '#', badge: 'Low tickets' },
        { title: 'Glasgow — Stereo', subtitle: 'Sat 13 Sep', text: 'With Cold Harbour. Doors 7pm.', href: '#', badge: 'On sale' },
        { title: 'London — Moth Club', subtitle: 'Thu 18 Sep', text: 'Album launch show. Doors 7:30pm, 18+.', href: '#', badge: 'Sold out' },
        { title: 'Amsterdam — Paradiso Upstairs', subtitle: 'Wed 1 Oct', text: 'First EU headline show. Doors 20:00.', href: '#', badge: 'On sale' },
        { title: 'Berlin — Badehaus', subtitle: 'Fri 3 Oct', text: 'With Nachtmahr Kollektiv. Doors 20:00.', href: '#', badge: 'On sale' },
      ] }),
      b('press', 'testimonials', { title: 'Press', items: [
        { quote: 'The most physical band in the North right now — forty minutes that feel like being argued with by someone you agree with.', author: 'The Quietus', role: 'Live review, March 2026' },
        { quote: '‘Marine Layer’ is the rare second record that gets quieter and hits harder.', author: 'DIY Magazine', role: '8/10' },
        { quote: 'A rhythm section that could pull a ferry off a sandbank.', author: 'Loud And Quiet', role: 'Track of the week' },
      ] }),
      b('shots', 'gallery', { layout: 'grid', columns: 2, gap: 'lg', lightbox: true, items: [
        { src: img('pers-mus-press-1'), alt: 'Band standing on a sea wall in grey light', caption: 'Press shot 1 — credit Ola Hennessy' },
        { src: img('pers-mus-press-2'), alt: 'Guitarist mid-set under red light', caption: 'Live at the Brudenell — credit J. Farrow' },
        { src: img('pers-mus-press-3'), alt: 'Album artwork for Marine Layer', caption: '‘Marine Layer’ artwork' },
        { src: img('pers-mus-press-4'), alt: 'Drummer photographed from behind the kit', caption: 'Live at YES, Manchester' },
      ] }),
      b('links', 'social-links', { title: 'Listen & follow', layout: 'grid', variant: 'labeled', align: 'center', links: [
        { platform: 'instagram', href: '#', label: '@hollowcoastband' },
        { platform: 'youtube', href: '#', label: 'YouTube' },
        { platform: 'tiktok', href: '#', label: 'TikTok' },
        { platform: 'website', href: '#', label: 'Bandcamp' },
        { platform: 'custom', href: '#', label: 'Spotify', icon: '🎧' },
      ] }),
      b('booking', 'cta', { headline: 'Booking, press and guest list', subhead: 'UK & EU booking: Priya Raval at Northline. Press requests and the full asset pack: management@hollowcoast.band', background: 'accent', button: { label: 'Email management', href: 'mailto:management@hollowcoast.band' } }),
      b('footer', 'footer', { brand: 'HOLLOW COAST', tagline: 'Post-punk, Leeds. Marine Layer out 14 August.', links: [{ label: 'Dates', href: '#dates' }, { label: 'Press', href: '#press' }, { label: 'Booking', href: '#booking' }], copyright: '© Hollow Coast · Tidal Fault Records' }),
    ],
  }),

  tpl({
    id: 'personal-writer',
    vertical: 'personal',
    label: 'Freelance Writer — Hire Page',
    description: 'A single-purpose page for a freelance writer: bylines, clips, rates and one clear ask.',
    tags: ['writing', 'freelance', 'pricing', 'newsletter', 'b2b'],
    layout: 'landing',
    preset: 'ocean',
    meta: { title: 'Rafael Duarte — Freelance Writer', description: 'Freelance journalist and B2B writer covering climate tech, energy and industry.', lang: 'en', favicon: '✍️' },
    blocks: [
      b('nav', 'nav', { brand: 'Rafael Duarte', sticky: true, links: [{ label: 'Clips', href: '#clips' }, { label: 'Rates', href: '#rates' }], cta: { label: 'Commission me', href: '#hire' } }),
      b('hero', 'hero', { eyebrow: 'Climate tech · Energy · Industry', headline: 'I write the piece your team keeps meaning to write', subhead: 'Freelance journalist and B2B writer. Twelve years of bylines, six of them on the energy transition. Currently taking two commissions a month.', align: 'center', minHeight: 'lg', image: img('pers-wri-hero'), overlay: 'scrim', cta: { label: 'Commission a piece', href: '#hire' } }),
      b('bylines', 'logos', { title: 'Bylines', items: [
        { src: img('pers-wri-byl-1'), alt: 'Canary Media' },
        { src: img('pers-wri-byl-2'), alt: 'Heatmap' },
        { src: img('pers-wri-byl-3'), alt: 'The Verge' },
        { src: img('pers-wri-byl-4'), alt: 'Wired' },
        { src: img('pers-wri-byl-5'), alt: 'MIT Technology Review' },
      ] }),
      b('how', 'steps', { title: 'How commissioning works', subtitle: 'No discovery calls, no proposal theatre.', items: [
        { title: 'Send the brief', text: 'A paragraph is enough: the reader, the angle, the word count, the deadline. I reply the same day with yes, no, or a better idea.' },
        { title: 'Get an outline in 48 hours', text: 'Before I write a word you see the structure, the sources I plan to call, and what I think the piece actually argues. Kill it at this stage for free.' },
        { title: 'Draft, then one real revision', text: 'Full draft on the agreed date, one substantive revision round included, line edits after that are on the house. Fact-check notes travel with every draft.' },
      ] }),
      b('clips', 'blog-list', { title: 'Recent clips', columns: 3, posts: [
        { title: 'The interconnection queue that is quietly killing Midwest solar', excerpt: 'Nine gigawatts of permitted projects, a MISO queue measured in years, and the two tariff changes that could unblock most of it.', href: '#', image: img('pers-wri-clip-1'), date: 'May 2026', tag: 'Reported feature' },
        { title: 'What happens to a heat pump installer in year three', excerpt: 'I followed four installers through a full winter. Only one is still in business, and not for the reason anyone predicted.', href: '#', image: img('pers-wri-clip-2'), date: 'February 2026', tag: 'Longread' },
        { title: 'Nobody knows what a green steel premium is worth', excerpt: 'Buyers say they will pay more. Contracts say otherwise. A look at the twelve deals that actually got signed.', href: '#', image: img('pers-wri-clip-3'), date: 'November 2025', tag: 'Analysis' },
      ] }),
      b('rates', 'pricing', { title: 'Rates', subtitle: 'USD, invoiced on delivery, net 30. Publications on their own rate cards — just ask.', plans: [
        { name: 'Explainer', price: '$1,200', period: '/ 1,200 words', features: ['One outline round', 'Two interviews', 'One revision', 'Ten working days'], ctaLabel: 'Commission this', ctaHref: '#hire' },
        { name: 'Reported feature', price: '$3,400', period: '/ 2,500 words', features: ['Six to ten interviews', 'Data and FOIA work', 'Fact-check notes', 'One revision', 'Four weeks'], ctaLabel: 'Commission this', ctaHref: '#hire', featured: true },
        { name: 'Monthly retainer', price: '$4,800', period: '/ month', features: ['Two long pieces or four short', 'Editorial calendar input', 'A standing Slack channel', 'Three months minimum'], ctaLabel: 'Talk it through', ctaHref: '#hire' },
      ] }),
      b('words', 'testimonials', { title: 'Editors and clients', items: [
        { quote: 'Rafael files clean, on time, and with the fact-check already done. In this job that is close to a miracle.', author: 'Hannah Weiss', role: 'Commissioning Editor, Heatmap' },
        { quote: 'We asked for a product explainer. Rafael came back and told us the interesting story was the supply chain. That call was right, and the piece got picked up twice.', author: 'Deepak Menon', role: 'Head of Content, Voltiq' },
      ] }),
      b('news', 'newsletter', { title: 'Dispatch — every other Thursday', intro: 'What I’m reporting on, the numbers that did not fit in the piece, and one chart. About 4,000 subscribers, most of them in energy.', placeholder: 'you@company.com', submitLabel: 'Subscribe', successMessage: 'You’re on the list — the first issue lands Thursday.' }),
      b('hire', 'cta', { headline: 'Two commissions a month. One is open.', subhead: 'Send the brief to rafael@duarte.press — a paragraph is plenty, and you will have an answer today.', background: 'primary', button: { label: 'rafael@duarte.press', href: 'mailto:rafael@duarte.press' } }),
      b('footer', 'footer', { brand: 'Rafael Duarte', tagline: 'Freelance writer, Chicago IL. Member, Society of Environmental Journalists.', links: [{ label: 'Clips', href: '#clips' }, { label: 'Rates', href: '#rates' }, { label: 'Commission me', href: '#hire' }], copyright: '© Rafael Duarte' }),
    ],
  }),

  tpl({
    id: 'personal-compcard',
    vertical: 'personal',
    label: 'Model / Actor — Digital Comp Card',
    description: 'A phone-shaped digital comp card a casting director can open, scroll and keep.',
    tags: ['acting', 'modelling', 'mobile-first', 'portfolio', 'social'],
    layout: 'app',
    preset: 'mono',
    meta: { title: 'Jules Amara — Comp Card', description: 'Actor and commercial model, London. Stats, shots, credits and agency contact.', lang: 'en', favicon: '🎭' },
    blocks: [
      b('shell', 'app-shell', { brand: 'Jules Amara', tabs: [
        { label: 'Shots', href: '#shots', icon: '📸' },
        { label: 'Stats', href: '#stats', icon: '📐' },
        { label: 'Credits', href: '#credits', icon: '🎬' },
        { label: 'Reel', href: '#reel', icon: '▶️' },
        { label: 'Contact', href: '#contact', icon: '✉️' },
      ] }),
      b('header', 'profile-header', { name: 'Jules Amara', headline: 'Actor · Commercial & editorial model', location: 'London, UK — travels for work', avatar: img('pers-cmp-avatar'), summary: 'Non-binary performer, they/them. RADA-trained, seven years on stage and camera and four in commercial and editorial. Fluent English and Portuguese, working French. Full clean driving licence, stage combat and horse riding.', contacts: [
        { type: 'custom', value: 'Kite & Warren Management', label: 'Agency' },
        { type: 'phone', value: '+44 20 7946 0311', label: 'Agency desk' },
        { type: 'email', value: 'casting@kitewarren.co.uk', label: 'Casting enquiries' },
        { type: 'website', value: 'https://spotlight.com/julesamara', label: 'Spotlight 4821-9930' },
      ], showDownload: true, downloadLabel: 'Download PDF card', showShare: true, shareLabel: 'Send to a colleague' }),
      b('shots', 'gallery', { layout: 'grid', columns: 2, gap: 'sm', lightbox: true, items: [
        { src: img('pers-cmp-shot-1'), alt: 'Headshot in natural light against a neutral background', caption: 'Headshot — commercial' },
        { src: img('pers-cmp-shot-2'), alt: 'Headshot in profile with dramatic lighting', caption: 'Headshot — theatrical' },
        { src: img('pers-cmp-shot-3'), alt: 'Full length in tailoring against a studio wall', caption: 'Full length' },
        { src: img('pers-cmp-shot-4'), alt: 'Editorial shot in knitwear on a rooftop', caption: 'Editorial — Grazia UK' },
        { src: img('pers-cmp-shot-5'), alt: 'Three-quarter shot smiling in a denim jacket', caption: 'Commercial — lifestyle' },
        { src: img('pers-cmp-shot-6'), alt: 'Character shot in period costume', caption: 'Character — period' },
      ] }),
      b('stats', 'stats', { title: 'Stats', columns: 4, items: [
        { value: '178', label: 'Height', suffix: 'cm' },
        { value: '86', label: 'Chest', suffix: 'cm' },
        { value: '73', label: 'Waist', suffix: 'cm' },
        { value: '42', label: 'Shoe', prefix: 'EU ' },
        { value: 'Dark brown', label: 'Hair' },
        { value: 'Hazel', label: 'Eyes' },
        { value: '20–32', label: 'Playing age' },
        { value: '3', label: 'Accents: RP, Estuary, Lisbon' },
      ] }),
      b('credits', 'experience', { title: 'Selected credits', items: [
        { role: 'Bea (supporting)', org: 'Salt Line — BBC Three', period: '2026', location: 'Cardiff', summary: 'Six-part drama, dir. Aisha Kowalski.' },
        { role: 'Viola', org: 'Twelfth Night — Bristol Old Vic', period: '2025', location: 'Bristol', bullets: ['Ten-week run, dir. Nadia Fell.', 'Nominated, Stage Debut Award for Best Performer.'] },
        { role: 'Principal', org: 'Lloyds Bank — “Every Other Tuesday”', period: '2025', location: 'London', summary: 'National TV and VOD campaign, dir. Sam Ortega.' },
        { role: 'Ensemble', org: 'The Winter’s Tale — Sam Wanamaker Playhouse', period: '2024', location: 'London' },
        { role: 'Editorial model', org: 'Grazia UK, Wonderland, Nike Running', period: '2023 – 2026', location: 'London / Lisbon' },
      ] }),
      b('reel', 'video', { provider: 'vimeo', src: 'https://vimeo.com/julesamara-showreel-2026', title: 'Showreel 2026 — 2 min 40', poster: img('pers-cmp-reel'), caption: 'Full reel and recent self-tapes available from the agency on request.' }),
      b('links', 'social-links', { title: 'Profiles', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'instagram', href: '#', label: '@julesamara' },
        { platform: 'website', href: '#', label: 'Spotlight' },
        { platform: 'custom', href: '#', label: 'Backstage', icon: '🎟️' },
      ] }),
      b('contact', 'contact-details', { title: 'Agency contact', address: 'Kite & Warren Management, 3rd Floor, 22 Rivington Street, London EC2A 3DU', phone: '+44 20 7946 0311', email: 'casting@kitewarren.co.uk', hours: 'Casting desk Mon–Fri 9:00–18:00' }),
      b('install', 'install-prompt', { title: 'Keep this card on your phone', body: 'Add it to your home screen — stats, shots and agency contact, even offline.', actionLabel: 'How?', position: 'bottom', tone: 'info', delayMs: 4000, dismissible: true, rememberDismiss: true, platforms: ['ios-safari', 'android', 'desktop-chrome'] }),
      b('footer', 'footer', { brand: 'Jules Amara', tagline: 'Actor & model · they/them · represented by Kite & Warren.', links: [{ label: 'Credits', href: '#credits' }, { label: 'Contact', href: '#contact' }], copyright: '© Jules Amara · Photos credited on request' }),
    ],
  }),
];
