/**
 * `professional` starter templates — regulated and advisory practices (medicine,
 * engineering, law, accountancy, architecture, finance, HR, languages, strategy),
 * each leaning on the credentials / case-study / experience / stats vocabulary.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const professionalTemplates: Template[] = [
  // ── private doctor / consultant physician ──────────────────────────────────
  tpl({
    id: 'professional-consultant-physician',
    vertical: 'professional',
    label: 'Consultant Physician — Private Clinic',
    description: 'A private consultant physician leading with credentials, clinic times and self-referral.',
    tags: ['doctor', 'healthcare', 'booking', 'faq', 'local'],
    layout: 'classic',
    preset: 'ocean',
    meta: {
      title: 'Dr Anwen Pryce — Consultant Physician, London',
      description: 'Private general medicine and cardiology clinics in central London. Self-referral welcome.',
      lang: 'en',
      favicon: '🩺',
    },
    blocks: [
      b('notice', 'announcement-bar', { text: 'New Thursday evening clinic — appointments now open to 8pm.', linkLabel: 'See times', href: '#hours', tone: 'info', dismissible: true }),
      b('nav', 'nav', { brand: 'Dr Anwen Pryce', sticky: true, links: [{ label: 'Clinics & fees', href: '#clinics' }, { label: 'About', href: '#about' }, { label: 'Training', href: '#credentials' }, { label: 'FAQ', href: '#faq' }], cta: { label: 'Book a consultation', href: '#book' } }),
      b('hero', 'hero', { eyebrow: 'MBBS, MRCP(UK), FRCP · GMC 6142880', headline: 'Unhurried general medicine, when you need answers sooner', subhead: 'Forty-five minute first consultations, same-week echocardiography, and a written summary to your GP within 48 hours.', align: 'left', minHeight: 'md', image: img('physician-consulting-room'), overlay: 'light', cta: { label: 'Request an appointment', href: '#book' } }),
      b('stats', 'stats', { title: 'The practice in numbers', columns: 4, items: [
        { value: '19', label: 'Years in practice' },
        { value: '4,200', label: 'Patients seen privately' },
        { value: '48', label: 'Until your GP has the letter', suffix: 'h' },
        { value: '98', label: 'Would recommend', suffix: '%' },
      ] }),
      b('clinics', 'services-catalogue', { title: 'Clinics and investigations', subtitle: 'All fees are quoted before booking and recognised by the major UK insurers.', items: [
        { name: 'New patient consultation', description: '45 minutes, full history and examination, plan letter to your GP.', price: '£290' },
        { name: 'Follow-up consultation', description: '20 minutes, review of results and adjustment of treatment.', price: '£180' },
        { name: 'Echocardiogram with report', description: 'Performed and reported in clinic on the same visit.', price: '£420' },
        { name: '24-hour ambulatory BP monitoring', description: 'Fitted in clinic, posted results and interpretation.', price: '£240' },
        { name: 'Executive health review', description: 'Bloods, ECG, spirometry and a two-part consultation.', price: '£950' },
      ] }),
      b('about', 'about', { eyebrow: 'About', title: 'Trained at Bart’s, still on the NHS rota', body: 'Dr Pryce read medicine at Queen Mary and trained in general internal medicine and cardiology across the North East Thames rotation. They hold a substantive consultant post at a central London teaching hospital and keep private clinics to two afternoons and one evening a week — deliberately, so appointments stay long and follow-up stays personal. Special interests are unexplained breathlessness, palpitations, hypertension that has not settled on two drugs, and second opinions on complex medication lists.', image: img('physician-portrait-desk'), imageAlt: 'Consultant physician at a clinic desk', imageSide: 'left' }),
      b('credentials', 'timeline', { title: 'Training and appointments', items: [
        { date: '2006', title: 'MBBS, Queen Mary University of London', text: 'Distinction in clinical practice; intercalated BSc in cardiovascular medicine.' },
        { date: '2010', title: 'MRCP (UK)', text: 'Completed core medical training at the Royal London Hospital.' },
        { date: '2016', title: 'CCT in general internal medicine and cardiology', text: 'North East Thames higher specialist training.' },
        { date: '2017', title: 'Consultant appointment', text: 'Substantive consultant physician, central London teaching hospital.' },
        { date: '2021', title: 'FRCP', text: 'Elected Fellow of the Royal College of Physicians.' },
      ] }),
      b('reviews', 'reviews', { title: 'Patient feedback', subtitle: 'Collected after every appointment by an independent feedback provider.', average: '4.9', count: '212', source: 'verified patient surveys', items: [
        { rating: 5, quote: 'I had been told for two years that it was “just anxiety”. Dr Pryce listened for forty minutes, ordered one test, and I had a diagnosis the same week.', author: 'S. Okonkwo', date: 'March 2026' },
        { rating: 5, quote: 'Explained my mother’s eleven medications to her in plain English and stopped four of them safely. She is a different person.', author: 'Ruth D.', date: 'January 2026' },
        { rating: 4, quote: 'The consultation was excellent and the report to my GP was genuinely useful. Parking near the clinic is the only hard part.', author: 'M. Haldar', date: 'December 2025' },
      ] }),
      b('faq', 'faq', { title: 'Before you book', items: [
        { question: 'Do I need a GP referral?', answer: 'No. Self-referral is welcome for consultations. Some insurers require a referral letter before they will authorise a claim, so check your policy first if you intend to claim.' },
        { question: 'Which insurers are recognised?', answer: 'Bupa, AXA Health, Aviva, Vitality and WPA are all recognised at fee-assured rates. Please bring your membership number and pre-authorisation code to the first appointment.' },
        { question: 'What should I bring?', answer: 'A list of your current medicines including doses, any recent blood results or scan reports, and your reading glasses — there is usually a form or two.' },
        { question: 'Can you see me urgently?', answer: 'Urgent slots are usually available within three working days. If you have chest pain, sudden breathlessness or symptoms of a stroke, call 999 rather than the clinic.' },
      ] }),
      b('hours', 'hours', { title: 'Clinic times', timezone: 'Europe/London', note: 'Secretarial line answered 9am–5pm weekdays; messages returned the same day.', days: [
        { day: 'mon', closed: true },
        { day: 'tue', open: '14:00', close: '18:30' },
        { day: 'wed', closed: true },
        { day: 'thu', open: '14:00', close: '20:00' },
        { day: 'fri', open: '09:00', close: '13:00' },
        { day: 'sat', closed: true },
        { day: 'sun', closed: true },
      ] }),
      b('book', 'booking', { title: 'Request an appointment', intro: 'Tell us a little about what is troubling you and the secretary will call back with the first suitable slot.', serviceLabel: 'Type of appointment', services: [
        { name: 'New patient consultation', duration: '45 min', price: '£290' },
        { name: 'Follow-up consultation', duration: '20 min', price: '£180' },
        { name: 'Echocardiogram with report', duration: '40 min', price: '£420' },
      ], askDate: true, askTime: true, askPhone: true, askNotes: true, notesLabel: 'Main symptom or reason for referral', submitLabel: 'Request appointment', successMessage: 'Thank you — the secretary will call you within one working day.' }),
      b('contact', 'contact-details', { title: 'The clinic', address: '18 Devonshire Place, Marylebone, London W1G 6HP', phone: '+44 20 7946 0182', email: 'secretary@pryceclinic.co.uk', hours: 'Tue & Thu afternoons · Fri mornings' }),
      b('footer', 'footer', { brand: 'Dr Anwen Pryce', tagline: 'Consultant physician and cardiologist, London.', links: [{ label: 'Fees', href: '#clinics' }, { label: 'FAQ', href: '#faq' }, { label: 'Book', href: '#book' }], copyright: '© Pryce Medical Ltd · Registered in England 09182734' }),
    ],
  }),

  // ── chartered engineer consultancy ─────────────────────────────────────────
  tpl({
    id: 'professional-chartered-engineer',
    vertical: 'professional',
    label: 'Chartered Engineer — Consultancy',
    description: 'A structural engineering consultancy whose service list and fee bands are the whole page.',
    tags: ['engineering', 'b2b', 'pricing', 'case-studies', 'construction'],
    layout: 'catalogue',
    preset: 'forest',
    meta: {
      title: 'Kestrel Structural — Chartered Structural Engineers, Melbourne',
      description: 'Residential and light commercial structural design, inspections and certification across Victoria.',
      lang: 'en',
      favicon: '📐',
    },
    blocks: [
      b('nav', 'nav', { brand: 'Kestrel Structural', sticky: true, links: [{ label: 'Services', href: '#services' }, { label: 'Fees', href: '#fees' }, { label: 'Projects', href: '#projects' }, { label: 'Process', href: '#process' }], cta: { label: 'Request a fee proposal', href: '#enquiry' } }),
      b('hero', 'hero', { eyebrow: 'CPEng · NER · RPEV PE0004512', headline: 'Structural design and certification, priced before we start', subhead: 'Kestrel works with owner-builders, architects and small commercial developers across greater Melbourne. Fixed fees, drawings in ten working days.', align: 'left', minHeight: 'sm', overlay: 'none', cta: { label: 'See the fee bands', href: '#fees' } }),
      b('services', 'services-catalogue', { title: 'What we are engaged for', subtitle: 'Every engagement is signed off by a Registered Professional Engineer of Victoria.', items: [
        { name: 'Residential extension design', description: 'Beams, lintels, footings and connections for a single or double-storey addition, with computations.', price: 'from A$2,400', ctaLabel: 'Enquire', ctaHref: '#enquiry' },
        { name: 'Removal of a load-bearing wall', description: 'Site measure, temporary propping scheme and a certified beam design for your building surveyor.', price: 'from A$980', ctaLabel: 'Enquire', ctaHref: '#enquiry' },
        { name: 'Pre-purchase structural inspection', description: 'Two-hour walkover, defect photography and a written opinion on movement, moisture and framing.', price: 'A$1,150', ctaLabel: 'Enquire', ctaHref: '#enquiry' },
        { name: 'Retaining wall design', description: 'Geotechnical review, wall design to AS 4678 and council-ready documentation.', price: 'from A$1,800', ctaLabel: 'Enquire', ctaHref: '#enquiry' },
        { name: 'Steel frame and portal shed design', description: 'Light commercial portal frames, wind loading to AS/NZS 1170, fabrication drawings.', price: 'from A$4,200', ctaLabel: 'Enquire', ctaHref: '#enquiry' },
        { name: 'Expert witness and dispute reports', description: 'Independent structural opinion for VCAT and insurer matters, prepared to the expert code of conduct.', price: 'A$420/hr', ctaLabel: 'Enquire', ctaHref: '#enquiry' },
      ] }),
      b('fees', 'pricing', { title: 'How we package fees', subtitle: 'Pick the band that fits the job; anything unusual gets a bespoke proposal within two days.', plans: [
        { name: 'Single element', price: 'A$980', period: 'fixed', features: ['One beam, lintel or footing', 'Site measure included', 'Certified computations', 'Ten working day turnaround'], ctaLabel: 'Start here', ctaHref: '#enquiry' },
        { name: 'Whole project', price: 'A$2,400', period: 'from', features: ['Full structural package', 'Coordination with your architect', 'Two rounds of revisions', 'Council RFI responses included', 'Site inspection at frame stage'], ctaLabel: 'Most engagements', ctaHref: '#enquiry', featured: true },
        { name: 'Retained', price: 'A$1,600', period: 'per month', features: ['For builders with steady volume', 'Priority ten-day queue', 'Unlimited short-form advice', 'Quarterly detailing review', 'Discounted site attendances'], ctaLabel: 'Talk to us', ctaHref: '#enquiry' },
      ] }),
      b('projects', 'split', { rows: [
        { title: 'Brunswick — 1920s weatherboard, rear opening of 6.4m', text: 'The owners wanted the back wall gone without a post in the middle of the kitchen. We used a 460UB steel with a concealed flitch to keep the ceiling line flat, and designed a temporary propping sequence the builder could put up in a single morning. Council approved without an RFI.', image: img('engineer-brunswick-extension'), imageAlt: 'Steel beam installed in a rear extension' },
        { title: 'Geelong — 640m² portal frame workshop', text: 'A fabricator outgrew their shed and needed 8m clear internal height with a 5-tonne gantry. We designed the portals, crane runway beams and slab thickenings, and worked the wind bracing around three roller doors on the exposed western elevation. Erected in nine days.', image: img('engineer-geelong-portal-shed'), imageAlt: 'Steel portal frame workshop under construction' },
        { title: 'Fitzroy North — underpinning after slab heave', text: 'Reactive clay and a leaking stormwater line had lifted the rear of a slab by 34mm. We instrumented the floor for six weeks before designing anything, then specified screw piles only where the movement was live. Half the underpinning the original report called for.', image: img('engineer-fitzroy-underpinning'), imageAlt: 'Level survey markers on a cracked concrete slab' },
      ] }),
      b('process', 'steps', { title: 'How an engagement runs', subtitle: 'No surprises, and no invoice you have not already seen the number for.', items: [
        { title: 'Send us what you have', text: 'Sketches, a survey, an architect’s set or three photos on your phone — all fine. We will tell you what is missing.' },
        { title: 'Fixed fee proposal in 48 hours', text: 'Scope, exclusions, deliverables and a date. If we cannot fix the fee we say why and quote a capped rate.' },
        { title: 'Site measure', text: 'We attend, measure, and open up enough to be sure what is holding the building up before we draw anything.' },
        { title: 'Design and certification', text: 'Drawings, computations and the RPEV certificate, issued as a single signed PDF set.' },
        { title: 'Through to approval', text: 'We answer the building surveyor’s questions directly. RFI responses are included, not extra.' },
      ] }),
      b('credentials', 'features', { title: 'Registrations and insurance', columns: 3, items: [
        { icon: '🏛️', title: 'RPEV registered', text: 'Registered Professional Engineer of Victoria, structural area of engineering, PE0004512.' },
        { icon: '🎓', title: 'CPEng and NER', text: 'Chartered status with Engineers Australia and listed on the National Engineering Register.' },
        { icon: '🛡️', title: 'A$10m PI cover', text: 'Professional indemnity to A$10m and public liability to A$20m, with certificates of currency issued alongside every proposal.' },
      ] }),
      b('enquiry', 'contact-form', { title: 'Request a fee proposal', intro: 'Two days for a written fee, most of the time same day. Attachments can follow by email.', fields: [
        { name: 'name', label: 'Your name', type: 'text', required: true },
        { name: 'email', label: 'Email', type: 'email', required: true },
        { name: 'phone', label: 'Phone', type: 'tel' },
        { name: 'suburb', label: 'Site suburb', type: 'text', required: true },
        { name: 'kind', label: 'Type of work', type: 'select', options: ['Extension or alteration', 'Wall removal', 'Retaining wall', 'Shed or portal frame', 'Inspection or report', 'Something else'] },
        { name: 'detail', label: 'Tell us about the job', type: 'textarea', placeholder: 'What are you building, and when do you need documentation?' },
      ], submitLabel: 'Send enquiry', successMessage: 'Received. You will have a written fee proposal within two working days.' }),
      b('footer', 'footer', { brand: 'Kestrel Structural', tagline: 'Chartered structural engineers · Level 1, 88 Wellington Street, Collingwood VIC 3066 · +61 3 9016 4482', links: [{ label: 'Services', href: '#services' }, { label: 'Fees', href: '#fees' }, { label: 'Enquiry', href: '#enquiry' }], copyright: '© Kestrel Structural Pty Ltd · ABN 41 622 118 903' }),
    ],
  }),

  // ── solicitor / law firm ───────────────────────────────────────────────────
  tpl({
    id: 'professional-law-firm',
    vertical: 'professional',
    label: 'Solicitors — Editorial',
    description: 'A boutique law firm using long-form writing to explain how it works and what it costs.',
    tags: ['legal', 'long-form', 'b2b', 'faq', 'dark'],
    layout: 'editorial',
    preset: 'midnight',
    meta: {
      title: 'Ó Braonáin & Kelly — Solicitors, Dublin',
      description: 'Employment, commercial and dispute resolution advice for Irish businesses and their people.',
      lang: 'en',
      favicon: '⚖️',
    },
    blocks: [
      b('nav', 'nav', { brand: 'Ó Braonáin & Kelly', sticky: false, links: [{ label: 'Approach', href: '#approach' }, { label: 'Practice areas', href: '#areas' }, { label: 'People', href: '#people' }, { label: 'Costs', href: '#costs' }], cta: { label: 'Speak to a solicitor', href: '#contact' } }),
      b('hero', 'hero', { eyebrow: 'Established 2011 · Dublin 2', headline: 'The advice you would want if it were happening to you', subhead: 'A twelve-person firm acting for employers, employees and owner-managed businesses across Ireland — in plain language, on agreed fees.', align: 'center', minHeight: 'md', overlay: 'none' }),
      b('approach', 'rich-text', { blocks: [
        { kind: 'heading', text: 'We are deliberately small, and that is the point' },
        { kind: 'paragraph', text: 'Most firms our size are a stepping stone to somewhere larger. We set this one up because we wanted to do the work ourselves rather than supervise other people doing it. When you instruct Ó Braonáin & Kelly, the solicitor you meet at the first consultation is the one who drafts your pleadings, attends your WRC hearing and picks up the phone at half past six when the other side has just filed something.' },
        { kind: 'paragraph', text: 'That imposes a discipline. We can only take on work we can actually service, so we turn matters away — usually with a recommendation to someone who does that work better than we do. It also means we are unusually direct about the merits. If a case is weak, you will hear that at the first meeting rather than after eight months of correspondence.' },
        { kind: 'quote', text: 'Litigation is expensive, slow and stressful, and it is the right answer far less often than television suggests. Our job is to tell you which of those times you are in.' },
        { kind: 'subheading', text: 'What that looks like in practice' },
        { kind: 'bullet', text: 'A written scope and fee estimate before any substantive work begins, updated whenever the scope moves.' },
        { kind: 'bullet', text: 'A named solicitor and a named point of contact, both reachable directly, never through a switchboard.' },
        { kind: 'bullet', text: 'Advice in the language you would use to explain it to your board, with the legal citation in a footnote where you need it.' },
        { kind: 'bullet', text: 'A view on commercial outcome, not only legal entitlement — including when settling early is simply cheaper.' },
      ] }),
      b('areas', 'accordion', { title: 'Practice areas', items: [
        { heading: 'Employment law — employers', body: 'Contracts and handbooks, restructuring and collective redundancy consultation, TUPE on business transfers, disciplinary and grievance process design, investigations, and defence of WRC and Labour Court claims. We act for employers from eight people to eight hundred, most often in technology, hospitality and professional services.' },
        { heading: 'Employment law — employees', body: 'Exit negotiations and settlement agreements, unfair dismissal and discrimination claims, protected disclosures, and post-termination restrictions. We take a limited number of employee matters and never act for both sides of the same industry cluster in the same period.' },
        { heading: 'Commercial contracts', body: 'Supply, distribution and reseller agreements, SaaS and data processing terms, shareholders’ agreements, and the sale or purchase of small owner-managed businesses. Fixed fees for standard-form work, capped fees for negotiated deals.' },
        { heading: 'Dispute resolution', body: 'Contractual and shareholder disputes in the Circuit and High Court, debt recovery for regular commercial clients, mediation advocacy, and injunctions where speed genuinely matters. We are candid about costs exposure before proceedings issue, not after.' },
        { heading: 'Data protection', body: 'GDPR compliance reviews, DPIAs, breach response and DPC correspondence. Practical rather than performative — a register nobody maintains is worse than no register at all.' },
      ] }),
      b('people', 'team', { title: 'The people who will do the work', subtitle: 'Every matter is led by a partner or a senior associate. Nothing is delegated out of sight.', columns: 3, members: [
        { name: 'Síle Ó Braonáin', role: 'Partner — Employment', photo: img('law-partner-employment'), bio: 'Fifteen years in employment law, seven of them in-house at a listed retailer. Chairs the firm’s WRC advocacy practice.', socials: [{ label: 'LinkedIn', href: '#' }] },
        { name: 'Darragh Kelly', role: 'Partner — Commercial', photo: img('law-partner-commercial'), bio: 'Formerly of a Dublin commercial practice. Acts on shareholder disputes and the sale of owner-managed businesses.', socials: [{ label: 'LinkedIn', href: '#' }] },
        { name: 'Aoife Nwosu', role: 'Senior Associate — Data', photo: img('law-associate-data'), bio: 'Certified data protection practitioner. Writes the firm’s widely-forwarded quarterly note on DPC decisions.', socials: [{ label: 'LinkedIn', href: '#' }] },
      ] }),
      b('outcomes', 'stats', { title: 'Last twelve months', columns: 4, items: [
        { value: '164', label: 'Matters opened' },
        { value: '81', label: 'Settled before hearing', suffix: '%' },
        { value: '11', label: 'Days to first substantive advice' },
        { value: '0', label: 'Fee disputes' },
      ] }),
      b('costs', 'faq', { title: 'Costs, candidly', items: [
        { question: 'How do you charge?', answer: 'Fixed fee wherever the scope allows it — contracts, handbooks, settlement agreements, most advisory work. Hourly with a written cap for litigation and negotiated transactions. Our section 150 letter of engagement sets it all out before we start.' },
        { question: 'What are your hourly rates?', answer: 'Partners €395, senior associates €285, solicitors €215, all excluding VAT at 23%. Trainee and administrative time is not charged to clients.' },
        { question: 'Do you take employment cases on a no-win-no-fee basis?', answer: 'No. Irish law restricts contingency arrangements, and in employment matters we think they distort advice. We do offer staged fees for individual employee claims so the cost lands with the milestones.' },
        { question: 'What happens at the first meeting?', answer: 'Forty-five minutes, charged at €150 plus VAT and credited against your first invoice if you instruct us. You leave with a view on merits, a rough timeline and a fee estimate in writing within two days.' },
      ] }),
      b('notes', 'blog-list', { title: 'The quarterly note', columns: 3, posts: [
        { title: 'What the WRC actually does with a badly-run investigation', excerpt: 'Three 2026 decisions where the process, not the conduct, decided the case — and the paragraph employers keep leaving out of their terms of reference.', href: '#', image: img('law-note-wrc-investigation'), date: '4 June 2026', tag: 'Employment' },
        { title: 'Restrictive covenants after the 2025 Court of Appeal decisions', excerpt: 'Twelve months is no longer a safe default. What is enforceable now, and how to draft a clause a court will read down rather than strike out.', href: '#', image: img('law-note-restrictive-covenants'), date: '12 March 2026', tag: 'Employment' },
        { title: 'Shareholders’ agreements for two-person companies', excerpt: 'The four clauses that decide whether a fallout costs €4,000 or €400,000, written for founders rather than for lawyers.', href: '#', image: img('law-note-shareholders'), date: '28 January 2026', tag: 'Commercial' },
      ] }),
      b('contact', 'contact-details', { title: 'Speak to a solicitor', address: '31 Fitzwilliam Square South, Dublin 2, D02 XY45', phone: '+353 1 903 4410', email: 'hello@obkelly.ie', hours: 'Mon–Fri 9:00–17:30 · consultations by appointment' }),
      b('regulatory', 'legal', { title: 'Regulatory information', align: 'start', separator: '·', documents: [
        { label: 'Regulation', title: 'Regulatory status', content: 'Ó Braonáin & Kelly Solicitors LLP is regulated by the Law Society of Ireland. A list of partners is available at the registered office. Firm number 8842. Professional indemnity insurance is maintained in accordance with the Solicitors Acts.' },
        { label: 'Complaints', title: 'Complaints procedure', content: 'If you are unhappy with our service, please write to the managing partner, who will respond within ten working days. If the matter is not resolved you may refer it to the Legal Services Regulatory Authority.' },
        { label: 'Privacy', title: 'Privacy notice', content: 'We process personal data to provide legal services and to meet our anti-money-laundering obligations. Client files are retained for seven years from closure. Contact the data protection lead at the address above to exercise your rights.' },
      ] }),
      b('footer', 'footer', { brand: 'Ó Braonáin & Kelly', tagline: 'Solicitors · Dublin 2.', links: [{ label: 'Practice areas', href: '#areas' }, { label: 'Costs', href: '#costs' }, { label: 'Contact', href: '#contact' }], copyright: '© Ó Braonáin & Kelly Solicitors LLP' }),
    ],
  }),

  // ── accountant & bookkeeper ────────────────────────────────────────────────
  tpl({
    id: 'professional-accountant',
    vertical: 'professional',
    label: 'Accountant & Bookkeeper — Landing',
    description: 'A one-offer conversion page for a monthly bookkeeping and compliance package.',
    tags: ['accounting', 'pricing', 'one-pager', 'b2b', 'reviews'],
    layout: 'landing',
    preset: 'sand',
    meta: {
      title: 'Ledgerleaf — Accountants & Bookkeepers, Bengaluru',
      description: 'Monthly bookkeeping, GST returns and statutory filings for Indian founders and small businesses.',
      lang: 'en',
      favicon: '📒',
    },
    blocks: [
      b('offer', 'announcement-bar', { text: 'Onboarding before 31 July includes last year’s books cleaned up at no charge.', linkLabel: 'Claim it', href: '#start', tone: 'promo', dismissible: false }),
      b('nav', 'nav', { brand: 'Ledgerleaf', sticky: true, links: [{ label: 'What you get', href: '#included' }, { label: 'Pricing', href: '#pricing' }, { label: 'Clients', href: '#proof' }], cta: { label: 'Book a 20-min call', href: '#start' } }),
      b('hero', 'hero', { eyebrow: 'For founders who dread the 20th of the month', headline: 'Books closed by the 7th. GST filed by the 11th. Every month.', subhead: 'Ledgerleaf runs bookkeeping, GST, TDS and ROC compliance for 140 Indian startups and small businesses on one flat monthly fee.', align: 'center', minHeight: 'lg', image: img('accountant-desk-ledgers'), overlay: 'scrim', cta: { label: 'Book a 20-minute call', href: '#start' } }),
      b('proofbar', 'stats', { columns: 4, items: [
        { value: '140', label: 'Businesses on monthly retainer' },
        { value: '480', label: 'Crore of turnover administered', prefix: '₹' },
        { value: '7th', label: 'Working day close' },
        { value: '0', label: 'Late-filing penalties in 3 years' },
      ] }),
      b('included', 'features', { title: 'Everything in one monthly fee', subtitle: 'No per-return invoices, no surprise charges in March.', columns: 3, items: [
        { icon: '📥', title: 'Bookkeeping', text: 'Bank feeds reconciled weekly in Zoho Books or Tally. You forward bills to one email address; we do the rest.' },
        { icon: '🧾', title: 'GST returns', text: 'GSTR-1 and 3B prepared, reconciled against 2B, and filed with your sign-off every month.' },
        { icon: '💸', title: 'TDS & payroll', text: 'Monthly TDS deposits, quarterly returns, Form 16s, and payslips for teams up to 25.' },
        { icon: '📊', title: 'Monthly MIS', text: 'P&L, cash position and runway in a two-page PDF on the 8th, plus a 20-minute call if you want it walked through.' },
        { icon: '🏛️', title: 'ROC & annual filings', text: 'AOC-4, MGT-7, DIR-3 KYC and board minute templates, tracked so nothing lapses.' },
        { icon: '🔍', title: 'Notices handled', text: 'Departmental notices drafted and responded to by a chartered accountant, included up to two per year.' },
      ] }),
      b('pricing', 'pricing', { title: 'Flat monthly pricing', subtitle: 'Priced on transaction volume, not on how many questions you ask. GST extra at 18%.', plans: [
        { name: 'Solo', price: '₹6,000', period: 'per month', features: ['Up to 75 transactions a month', 'GST returns for one GSTIN', 'ITR for the business', 'Email support, 1 working day'], ctaLabel: 'Start with Solo', ctaHref: '#start' },
        { name: 'Growing', price: '₹14,500', period: 'per month', features: ['Up to 300 transactions a month', 'Two GSTINs', 'Payroll and TDS for up to 15 staff', 'Monthly MIS and review call', 'WhatsApp support, same day'], ctaLabel: 'Start with Growing', ctaHref: '#start', featured: true },
        { name: 'Funded', price: '₹32,000', period: 'per month', features: ['Unlimited transactions', 'Multi-state GST', 'Payroll to 25 staff with Form 16s', 'Investor-ready monthly reporting', 'Audit coordination and schedules', 'Named CA on your Slack'], ctaLabel: 'Talk to us', ctaHref: '#start' },
      ] }),
      b('how', 'steps', { title: 'Switching takes about a week', items: [
        { title: 'Twenty minute call', text: 'We look at your current books, your GSTINs and your headcount, and quote a band on the call.' },
        { title: 'We collect the history', text: 'Bank statements, last filed returns and your existing ledger. We do the chasing, including from your old accountant.' },
        { title: 'Clean-up month', text: 'Opening balances reconciled, mismatches in 2B chased down, and anything unfiled brought current.' },
        { title: 'Steady state', text: 'From month two you get books by the 7th, GST by the 11th, MIS by the 8th. You mostly stop thinking about it.' },
      ] }),
      b('proof', 'testimonials', { title: 'Founders who stopped doing this at midnight', items: [
        { quote: 'We had three years of half-reconciled Tally and a notice we did not understand. Ledgerleaf cleaned it up in six weeks and answered the notice for us. I have not opened Tally since.', author: 'Rhea Menon', role: 'Co-founder, Kettle & Co' },
        { quote: 'Our previous CA was cheaper and cost us ₹1.4 lakh in interest on a missed TDS deposit. The flat fee here is the least stressful line item we have.', author: 'Vikram Raghunathan', role: 'Director, Northline Logistics' },
        { quote: 'The monthly MIS is genuinely useful — it is the first thing I send our investors. It took our old firm four weeks to produce the same numbers.', author: 'Aditi Shah', role: 'Founder, Tallow Studio' },
      ] }),
      b('objections', 'faq', { title: 'The questions everyone asks', items: [
        { question: 'Do I have to change accounting software?', answer: 'No. We work in Zoho Books, Tally and QuickBooks. If you are on spreadsheets we will move you to Zoho Books during the clean-up month and the licence is on us for the first year.' },
        { question: 'Who actually does my work?', answer: 'A named bookkeeper does the daily entries and a chartered accountant reviews and signs off every filing. You get both names and both phone numbers on day one.' },
        { question: 'What if I want to leave?', answer: 'Thirty days’ notice, no exit fee. We hand over the complete ledger, all filed returns and the software login. It is your data.' },
        { question: 'Are you a virtual firm?', answer: 'Our office is in Indiranagar and you are welcome in it. In practice most clients meet us twice a year and do everything else over WhatsApp.' },
      ] }),
      b('start', 'cta', { headline: 'Get your last close done by someone else', subhead: 'Twenty minutes, a quote on the call, and no obligation. Weekday slots from 9am to 7pm IST.', background: 'primary', button: { label: 'Book a 20-minute call', href: '#' } }),
      b('footer', 'footer', { brand: 'Ledgerleaf', tagline: 'Indiranagar, Bengaluru 560038 · +91 80 4718 2200', links: [{ label: 'Pricing', href: '#pricing' }, { label: 'FAQ', href: '#objections' }], copyright: '© Ledgerleaf Advisory LLP · ICAI firm reg. 018842S' }),
    ],
  }),

  // ── architect practice ─────────────────────────────────────────────────────
  tpl({
    id: 'professional-architect',
    vertical: 'professional',
    label: 'Architecture Practice — Showcase',
    description: 'An architecture studio where the project photography carries the whole argument.',
    tags: ['architecture', 'portfolio', 'gallery', 'showcase', 'luxury'],
    layout: 'showcase',
    preset: 'mono',
    meta: {
      title: 'Rowan Vale Architecture — Portland, Oregon',
      description: 'A ten-person studio designing houses, small civic buildings and adaptive reuse in the Pacific Northwest.',
      lang: 'en',
      favicon: '🏛️',
    },
    blocks: [
      b('nav', 'nav', { brand: 'Rowan Vale', sticky: true, links: [{ label: 'Work', href: '#work' }, { label: 'Selected', href: '#selected' }, { label: 'Studio', href: '#studio' }, { label: 'Awards', href: '#awards' }], cta: { label: 'Start a project', href: '#enquire' } }),
      b('hero', 'hero', { eyebrow: 'AIA · Portland, Oregon', headline: 'Buildings that get quieter the longer you live in them', subhead: 'Rowan Vale designs houses, small civic work and adaptive reuse across Oregon and southwest Washington.', align: 'left', minHeight: 'full', image: img('architect-hero-timber-house'), overlay: 'dark', cta: { label: 'See selected work', href: '#work' } }),
      b('work', 'gallery', { layout: 'masonry', columns: 3, gap: 'lg', lightbox: true, items: [
        { src: img('architect-alder-house-exterior'), alt: 'Cedar-clad house among Douglas firs', caption: 'Alder House, Corbett — 2,180 sq ft on a sloped forest lot' },
        { src: img('architect-alder-house-interior'), alt: 'Double-height living room with clerestory glazing', caption: 'Alder House — clerestory light, no south-facing glare' },
        { src: img('architect-kilnworks-reuse'), alt: 'Converted brick kiln building with steel insertions', caption: 'Kilnworks, Sellwood — 1912 brick kiln to eleven workspaces' },
        { src: img('architect-columbia-library'), alt: 'Small public library with a deep timber porch', caption: 'Columbia Branch Library — 6,400 sq ft, mass timber' },
        { src: img('architect-hood-cabin'), alt: 'Small black cabin in snow', caption: 'Hood Cabin — 720 sq ft, off-grid, built in eleven weeks' },
        { src: img('architect-ravenscourt-adu'), alt: 'Backyard accessory dwelling with a green roof', caption: 'Ravenscourt ADU — a two-bedroom unit on a 34ft lot' },
      ] }),
      b('selected', 'split', { rows: [
        { title: 'Alder House — Corbett, Oregon', text: 'A retired couple wanted one level, no thresholds, and a view of the Sandy River gorge that did not cook the room in August. We buried the house half a story into the slope, put the glazing high and north, and used the roof overhang as the only shading device. Passive House certified, and heated by a single mini-split.', image: img('architect-alder-detail-eave'), imageAlt: 'Detail of a deep timber eave' },
        { title: 'Kilnworks — Sellwood, Portland', text: 'A 1912 brick kiln building that the city had listed and nobody could figure out how to occupy. We inserted eleven independent steel-framed workspaces that touch the historic masonry in only fourteen places, so the whole intervention is reversible. Full occupancy within four months of completion.', image: img('architect-kilnworks-interior'), imageAlt: 'Steel mezzanine inside a brick industrial shell' },
        { title: 'Columbia Branch Library — Vancouver, Washington', text: 'Our first public commission, won in open competition. Mass timber structure, a deep porch that doubles the usable program in summer, and a children’s room sized around the way kids actually sit on the floor. Delivered $180,000 under a $4.1m budget.', image: img('architect-library-porch'), imageAlt: 'Timber porch of a small public library' },
      ] }),
      b('studio', 'about', { eyebrow: 'The studio', title: 'Ten people, one office, no satellite branches', body: 'Rowan Vale was founded in 2014 and has stayed deliberately at ten people. A principal is on every project from the first site walk to the last punch item — we do not hand work down to a production team once the pretty drawings are done. We build physical models for every project, including the small ones, because clients read them and renderings flatter everything equally. Roughly a third of our work is residential, a third adaptive reuse, and a third small civic and cultural buildings won in competition.', image: img('architect-studio-model-shop'), imageAlt: 'Architecture studio model-making bench', imageSide: 'right' }),
      b('numbers', 'stats', { title: 'Since 2014', columns: 4, items: [
        { value: '62', label: 'Projects completed' },
        { value: '10', label: 'People in the studio' },
        { value: '7', label: 'Passive House certifications' },
        { value: '94', label: 'Delivered on or under budget', suffix: '%' },
      ] }),
      b('awards', 'timeline', { title: 'Recognition', items: [
        { date: '2025', title: 'AIA Oregon — Honor Award, Institutional', text: 'Columbia Branch Library, Vancouver, Washington.' },
        { date: '2024', title: 'Architectural Record — Record Houses', text: 'Alder House, Corbett.' },
        { date: '2023', title: 'Portland Historic Landmarks Commission — Preservation Award', text: 'Kilnworks adaptive reuse.' },
        { date: '2021', title: 'AIA Portland — Small Project Award', text: 'Hood Cabin.' },
        { date: '2019', title: 'Passive House Northwest — Project of the Year', text: 'Ravenscourt ADU.' },
      ] }),
      b('clients', 'testimonials', { title: 'From the people who live and work in them', items: [
        { quote: 'They talked us out of the third bedroom we thought we wanted and spent the money on the roof instead. Two winters in, that was obviously the right call.', author: 'Dana & Marcus Whitfield', role: 'Alder House' },
        { quote: 'We interviewed five firms about the kiln. Rowan Vale was the only one who came back and said the building should be touched as little as possible.', author: 'Elena Ruiz', role: 'Developer, Kilnworks' },
        { quote: 'Under budget, on schedule, and our circulation is up thirty percent. The porch is where half the town now waits for the bus.', author: 'T. Nakashima', role: 'Library District Director' },
      ] }),
      b('enquire', 'contact-form', { title: 'Start a project', intro: 'We take on roughly eight new projects a year and typically book six to nine months ahead. Tell us what you are thinking about.', fields: [
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'email', label: 'Email', type: 'email', required: true },
        { name: 'location', label: 'Project location', type: 'text', required: true },
        { name: 'type', label: 'Project type', type: 'select', options: ['New house', 'Renovation or addition', 'ADU', 'Adaptive reuse', 'Civic or cultural', 'Not sure yet'] },
        { name: 'budget', label: 'Construction budget', type: 'select', options: ['Under $400k', '$400k–$900k', '$900k–$2m', 'Over $2m', 'Undecided'] },
        { name: 'brief', label: 'What are you hoping to build?', type: 'textarea' },
      ], submitLabel: 'Send', successMessage: 'Thanks — a principal will reply within a week, and we mean a principal.' }),
      b('footer', 'footer', { brand: 'Rowan Vale Architecture', tagline: '2211 SE Water Ave, Portland, OR 97214 · (503) 555-0146', links: [{ label: 'Work', href: '#work' }, { label: 'Studio', href: '#studio' }, { label: 'Enquire', href: '#enquire' }], copyright: '© Rowan Vale Architecture LLC · Licensed by the Oregon Board of Architect Examiners, reg. 6702' }),
    ],
  }),

  // ── financial adviser ──────────────────────────────────────────────────────
  tpl({
    id: 'professional-financial-adviser',
    vertical: 'professional',
    label: 'Financial Adviser — Minimal',
    description: 'A fee-only independent financial adviser with one page, one promise and one call to action.',
    tags: ['finance', 'minimal', 'one-pager', 'faq', 'light'],
    layout: 'minimal',
    preset: 'ocean',
    meta: {
      title: 'Bramble Financial Planning — Edinburgh',
      description: 'Independent, fee-only financial planning for people approaching and in retirement.',
      lang: 'en',
      favicon: '🌿',
    },
    blocks: [
      b('nav', 'nav', { brand: 'Bramble', sticky: false, links: [{ label: 'How it works', href: '#how' }, { label: 'Fees', href: '#fees' }], cta: { label: 'Arrange a first meeting', href: '#meet' } }),
      b('hero', 'hero', { eyebrow: 'Chartered Financial Planner · Fee-only', headline: 'Will the money last?', subhead: 'That is the only question most people actually want answered. Bramble is a two-planner practice in Edinburgh that answers it properly, for a fee you agree in advance.', align: 'center', minHeight: 'lg', overlay: 'none', cta: { label: 'Arrange a first meeting', href: '#meet' } }),
      b('how', 'steps', { title: 'How it works', subtitle: 'Four meetings over about ten weeks, then an annual rhythm.', items: [
        { title: 'A conversation, at our cost', text: 'Ninety minutes about what you want the money to do. No products, no forms, no charge, and no obligation to go further.' },
        { title: 'The financial plan', text: 'A cash-flow model of the rest of your life, stress-tested against a 2008 and a 1974. You see the assumptions and can argue with them.' },
        { title: 'Implementation', text: 'If — and only if — the plan says something needs to change, we recommend it in writing, with the alternatives we rejected and why.' },
        { title: 'An annual review that earns its fee', text: 'Rebalancing, tax-year housekeeping, and re-running the model against what actually happened rather than what we assumed.' },
      ] }),
      b('independence', 'features', { title: 'What fee-only and independent means here', columns: 2, items: [
        { icon: '🪙', title: 'We are paid by you, only', text: 'No commission, no platform kickbacks, no introducer fees from anyone. If we recommend something we do not profit from the choice.' },
        { icon: '🧭', title: 'Whole of market', text: 'Genuinely independent under FCA rules — no restricted panel, no in-house fund, no parent company with products to shift.' },
        { icon: '📉', title: 'Low-cost, evidence-based', text: 'Globally diversified index funds, average total portfolio cost 0.21% a year. We do not think we can pick next year’s winners.' },
        { icon: '🔒', title: 'You keep control', text: 'Assets sit in your name on a platform you can log into. We hold discretion over nothing without your written instruction.' },
      ] }),
      b('fees', 'pricing', { title: 'Fees', subtitle: 'Published, in pounds, not as a percentage you have to compute yourself.', plans: [
        { name: 'Financial plan', price: '£3,200', period: 'one-off', features: ['Four meetings over ten weeks', 'Full lifetime cash-flow model', 'Written plan and recommendations', 'No obligation to implement with us'], ctaLabel: 'Start here', ctaHref: '#meet' },
        { name: 'Ongoing planning', price: '£3,900', period: 'per year', features: ['Annual plan refresh and review', 'All rebalancing and tax-year work', 'Unlimited contact between reviews', 'Capped regardless of portfolio size'], ctaLabel: 'Most clients', ctaHref: '#meet', featured: true },
        { name: 'One-off advice', price: '£290', period: 'per hour', features: ['Single questions — a pension consolidation, an inheritance', 'Written answer within ten working days', 'Estimate agreed before we begin'], ctaLabel: 'Ask us', ctaHref: '#meet' },
      ] }),
      b('faq', 'faq', { title: 'Fair questions', items: [
        { question: 'Is there a minimum portfolio?', answer: 'No minimum, but our flat fee makes us poor value below roughly £250,000 of investable assets. We will say so on the first call rather than take the money.' },
        { question: 'Do you advise on defined benefit transfers?', answer: 'We will give you an independent view on whether to seek a transfer analysis, but we do not hold the pension transfer specialist permission and do not carry out the analysis ourselves.' },
        { question: 'What happens to my money if Bramble stops trading?', answer: 'Your assets are held in your own name with your platform provider, not by us. We hold no client money. FSCS protection of up to £85,000 applies to the advice itself.' },
        { question: 'Who regulates you?', answer: 'Bramble Financial Planning Ltd is authorised and regulated by the Financial Conduct Authority, firm reference 812744. You can check that on the FCA register.' },
      ] }),
      b('meet', 'cta', { headline: 'The first meeting costs nothing and commits you to nothing', subhead: 'Ninety minutes in our Stockbridge office or over video, whichever suits. Weekday daytime appointments, plus Tuesday evenings.', background: 'primary', button: { label: 'Arrange a first meeting', href: '#' } }),
      b('footer', 'footer', { brand: 'Bramble Financial Planning', tagline: '14 Deanhaugh Street, Edinburgh EH4 1LY · +44 131 496 0173', links: [{ label: 'Fees', href: '#fees' }, { label: 'FAQ', href: '#faq' }], copyright: '© Bramble Financial Planning Ltd · FCA 812744 · SC612844' }),
    ],
  }),

  // ── HR & recruitment consultant ────────────────────────────────────────────
  tpl({
    id: 'professional-hr-recruitment',
    vertical: 'professional',
    label: 'HR & Recruitment — Bold',
    description: 'An HR and talent consultancy with a loud hero, hard numbers and client logos.',
    tags: ['hr', 'recruitment', 'b2b', 'newsletter', 'remote'],
    layout: 'bold',
    preset: 'candy',
    meta: {
      title: 'Northlight People — HR & Talent Consultancy, Berlin',
      description: 'Fractional HR leadership and hiring for scale-ups across the DACH region.',
      lang: 'en',
      favicon: '🧭',
    },
    blocks: [
      b('nav', 'nav', { brand: 'Northlight People', sticky: true, links: [{ label: 'Services', href: '#services' }, { label: 'Results', href: '#results' }, { label: 'Clients', href: '#clients' }, { label: 'Notes', href: '#notes' }], cta: { label: 'Book a diagnostic', href: '#book' } }),
      b('hero', 'hero', { eyebrow: 'Fractional HR & talent · Berlin, remote across DACH', headline: 'Hiring is not the hard part. Keeping the ones you hired is.', subhead: 'Northlight embeds a senior HR operator into scale-ups from 30 to 300 people — building the hiring engine, the comp bands and the manager layer that stops the leavers.', align: 'center', minHeight: 'full', image: img('hr-team-workshop-berlin'), overlay: 'dark', cta: { label: 'Book a 45-min diagnostic', href: '#book' } }),
      b('results', 'stats', { title: 'What the last two years looked like', columns: 4, items: [
        { value: '41', label: 'Scale-ups supported' },
        { value: '31', label: 'Average days to hire' },
        { value: '11', label: 'Regretted attrition, from 24%', suffix: '%' },
        { value: '9', label: 'Countries hired into' },
      ] }),
      b('services', 'tabs', { items: [
        { label: 'Fractional HR lead', text: 'Two or three days a week of a senior people operator inside your business, for six to twelve months. They own the whole function: contracts and compliance across DACH, comp banding, performance cycles, the manager training that nobody has time to write, and the awkward conversations. Typically €7,400–€11,200 a month depending on days. Most engagements end with us hiring our own replacement into your team, which is the point.' },
        { label: 'Embedded hiring', text: 'A recruiter of ours sits in your standups and works only your roles, on a monthly retainer rather than a percentage of salary. That removes the incentive to push you towards expensive candidates. €6,800 a month for a recruiter running six to eight open roles, sourcing included, with your ATS and your employer brand rather than ours.' },
        { label: 'Compensation review', text: 'A four-week project: market data for every role you have, a levelling framework that survives contact with a promotion round, banded ranges, and a costed plan to fix the people who are underpaid before they notice. Delivered as a spreadsheet your CFO can actually run scenarios in, plus a manager briefing pack. €18,000 fixed.' },
        { label: 'Manager enablement', text: 'Six 90-minute sessions for first-time managers on feedback, one-to-ones, performance conversations and hiring. Run live, in cohorts of eight to twelve, in English or German. €9,600 per cohort. Follow-up coaching hours available at €260.' },
      ] }),
      b('offer', 'services-catalogue', { title: 'Also available as one-off work', subtitle: 'Sometimes you do not need a retainer, you need one specific problem gone.', items: [
        { name: 'Interview process teardown', description: 'We sit in on four of your interview loops and rewrite the scorecards, the take-home and the debrief.', price: '€4,200' },
        { name: 'Handbook and policy set', description: 'German-law-compliant handbook, remote policy, leave and expenses, in DE and EN.', price: '€6,500' },
        { name: 'Restructure support', description: 'Process design, works council preparation, manager scripts and outplacement coordination.', price: 'from €8,000' },
        { name: 'Engagement survey and readout', description: 'Run, analysed and presented to the leadership team with a prioritised action list.', price: '€5,400' },
      ] }),
      b('clients', 'logos', { title: 'Recent clients', items: [
        { src: img('hr-client-logo-fintech'), alt: 'Berlin fintech client', href: '#' },
        { src: img('hr-client-logo-logistics'), alt: 'Logistics software client', href: '#' },
        { src: img('hr-client-logo-healthtech'), alt: 'Munich health technology client', href: '#' },
        { src: img('hr-client-logo-marketplace'), alt: 'Marketplace client', href: '#' },
        { src: img('hr-client-logo-climate'), alt: 'Climate technology client', href: '#' },
      ] }),
      b('voices', 'testimonials', { title: 'What clients say when the engagement ends', items: [
        { quote: 'We had lost four engineers in a quarter and told ourselves it was the market. Northlight found it was one manager and one broken promotion promise. Both fixed within eight weeks.', author: 'Jonas Weber', role: 'CTO, logistics platform' },
        { quote: 'The comp review was uncomfortable reading and exactly what we needed before our Series B. Our investors asked who did it.', author: 'Priya Balan', role: 'CFO, Berlin fintech' },
        { quote: 'They hired their own replacement, briefed that person properly, and left. I have never had a consultancy work themselves out of a job so deliberately.', author: 'Miriam Achterberg', role: 'CEO, healthtech, Munich' },
      ] }),
      b('notes', 'blog-list', { title: 'Notes from inside other people’s companies', columns: 2, posts: [
        { title: 'Your attrition problem is four managers wide', excerpt: 'What we find almost every time we cut exit data by reporting line rather than by department, and the two questions that surface it in a week.', href: '#', image: img('hr-note-attrition-managers'), date: '2 July 2026', tag: 'Retention' },
        { title: 'Stop paying recruiters a percentage of salary', excerpt: 'The incentive maths, worked through honestly — including the cases where contingency search is still the right call.', href: '#', image: img('hr-note-recruiter-fees'), date: '19 May 2026', tag: 'Hiring' },
      ] }),
      b('subscribe', 'newsletter', { title: 'One useful email a month', intro: 'Comp benchmarks for the DACH region, one thing we got wrong, and a template you can steal. No case studies dressed as insight.', placeholder: 'you@company.com', submitLabel: 'Subscribe', successMessage: 'You are in. First issue lands on the first Tuesday of the month.' }),
      b('book', 'cta', { headline: 'Forty-five minutes, and three things to do whether or not you hire us', subhead: 'We only take four new engagements a quarter, so the diagnostic is also how we decide if we can help.', background: 'accent', button: { label: 'Book a diagnostic', href: '#' } }),
      b('social', 'social-links', { title: 'Elsewhere', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'linkedin', href: '#', label: 'Northlight People' },
        { platform: 'email', href: '#', label: 'hallo@northlightpeople.de' },
        { platform: 'website', href: '#', label: 'Case studies' },
      ] }),
      b('footer', 'footer', { brand: 'Northlight People', tagline: 'Prinzessinnenstraße 20, 10969 Berlin · +49 30 5557 4180', links: [{ label: 'Services', href: '#services' }, { label: 'Notes', href: '#notes' }, { label: 'Book', href: '#book' }], copyright: '© Northlight People GmbH · HRB 249118 B' }),
    ],
  }),

  // ── translator & interpreter ───────────────────────────────────────────────
  tpl({
    id: 'professional-translator',
    vertical: 'professional',
    label: 'Translator & Interpreter — Profile',
    description: 'A certified translator’s personal practice page built around credentials and experience.',
    tags: ['translation', 'portfolio', 'freelance', 'b2b', 'remote'],
    layout: 'profile',
    preset: 'sand',
    meta: {
      title: 'Camille Beauchamp — Certified Translator & Conference Interpreter',
      description: 'FR to EN certified translation and conference interpreting, based in Montréal.',
      lang: 'en',
      favicon: '🗣️',
    },
    blocks: [
      b('profile', 'profile-header', {
        name: 'Camille Beauchamp',
        headline: 'Certified translator (OTTIAQ) & conference interpreter — FR ⇄ EN, ES → EN',
        location: 'Montréal, Québec',
        avatar: img('translator-portrait-booth'),
        summary: 'Fourteen years turning legal, medical and technical French into English that reads as though it was written that way — and back again. Certified for court and immigration use, and in the booth for roughly forty conference days a year.',
        contacts: [
          { type: 'email', value: 'camille@beauchamptraduction.ca', label: 'Email' },
          { type: 'phone', value: '+1 514 555 0198', label: 'Direct' },
          { type: 'location', value: 'Mile End, Montréal (UTC−5)' },
          { type: 'linkedin', value: '#', label: 'LinkedIn' },
        ],
        showDownload: true,
        downloadLabel: 'Download CV',
        showShare: true,
        shareLabel: 'Share',
      }),
      b('nav', 'nav', { brand: 'C. Beauchamp', sticky: true, links: [{ label: 'Services', href: '#services' }, { label: 'Experience', href: '#experience' }, { label: 'Languages', href: '#languages' }, { label: 'Clients', href: '#clients' }], cta: { label: 'Request a quote', href: '#quote' } }),
      b('services', 'services-catalogue', { title: 'Services and rates', subtitle: 'Rates in Canadian dollars. Certified work carries a per-document attestation fee.', items: [
        { name: 'Certified translation', description: 'Birth and marriage certificates, diplomas, court filings and corporate records, sealed for IRCC, courts and professional orders.', price: 'C$0.42/word' },
        { name: 'Legal and financial translation', description: 'Contracts, pleadings, expert reports, prospectuses and annual reports. NDA signed before any file is opened.', price: 'C$0.38/word' },
        { name: 'Medical and life sciences', description: 'Protocols, informed consent forms, regulatory submissions and patient-facing material. Back-translation available.', price: 'C$0.44/word' },
        { name: 'Simultaneous interpreting', description: 'Conference, board and arbitration work, in booth or remote. Two-interpreter teams over 90 minutes.', price: 'C$1,150/day' },
        { name: 'Consecutive & liaison interpreting', description: 'Depositions, medical appointments, factory audits and site visits across Greater Montréal.', price: 'C$180/hr' },
        { name: 'Revision of others’ work', description: 'Bilingual revision against source, with tracked changes and a quality note.', price: 'C$95/hr' },
      ] }),
      b('experience', 'experience', { title: 'Selected experience', items: [
        {
          role: 'Independent certified translator & interpreter',
          org: 'Beauchamp Traduction',
          period: '2016 — present',
          location: 'Montréal, QC',
          summary: 'Direct practice serving law firms, hospital research units and federal agencies.',
          bullets: [
            'Roughly 480,000 words a year of legal, medical and technical translation, FR ⇄ EN.',
            'Standing translator for two Montréal litigation boutiques and a CRO running bilingual trials.',
            'Around 40 conference days a year in the booth, including three annual medical congresses.',
            'Build and maintain client-specific termbases in memoQ; deliver bilingual TMX on request.',
          ],
        },
        {
          role: 'Staff translator, then senior translator',
          org: 'Translation Bureau, Government of Canada',
          period: '2012 — 2016',
          location: 'Gatineau, QC',
          summary: 'Parliamentary and departmental translation under statutory deadlines.',
          bullets: [
            'Translated committee evidence and departmental reports to same-day turnaround.',
            'Revised the work of four junior translators and ran the unit’s terminology reviews.',
          ],
        },
        {
          role: 'Interpreter, refugee protection hearings',
          org: 'Immigration and Refugee Board of Canada',
          period: '2014 — present',
          location: 'Montréal, QC',
          summary: 'Consecutive interpreting in protection and appeal hearings, FR/EN/ES.',
          bullets: [
            'Over 600 hearings interpreted; accredited at the Board’s highest reliability tier.',
            'Regularly briefed counsel on register and cultural-context issues before hearings.',
          ],
        },
      ] }),
      b('languages', 'skills', { title: 'Languages, tools and fields', display: 'bars', groups: [
        { name: 'Languages', items: [
          { label: 'French (native, Québec & France)', level: 5 },
          { label: 'English (native-level, CA & UK)', level: 5 },
          { label: 'Spanish (source only, DELE C1)', level: 4 },
        ] },
        { name: 'Fields', items: [
          { label: 'Legal & judicial', level: 5 },
          { label: 'Medical & clinical trials', level: 5 },
          { label: 'Financial reporting', level: 4 },
          { label: 'Engineering & manufacturing', level: 3 },
        ] },
        { name: 'Tools', items: [
          { label: 'memoQ', level: 5 },
          { label: 'Trados Studio', level: 4 },
          { label: 'Interprefy / Zoom RSI', level: 4 },
          { label: 'Antidote & termbase management', level: 5 },
        ] },
      ] }),
      b('credentials', 'features', { title: 'Certifications', columns: 3, items: [
        { icon: '🏅', title: 'OTTIAQ certified', text: 'Certified translator (trad. a.) with the Ordre des traducteurs, terminologues et interprètes agréés du Québec, member 8841.' },
        { icon: '🎧', title: 'AIIC candidate member', text: 'International Association of Conference Interpreters, FR/EN booth.' },
        { icon: '🎓', title: 'MA Translation, Concordia', text: 'Plus the Université de Genève certificate in medical translation, 2019.' },
      ] }),
      b('clients', 'testimonials', { title: 'What clients say', items: [
        { quote: 'Camille caught an inconsistency between the French and English versions of a clause that four lawyers had read. It would have cost our client the argument.', author: 'Étienne Larivière', role: 'Partner, litigation boutique' },
        { quote: 'Consent forms translated on a Friday, ethics submission on the Monday, no queries back. That has happened eleven times now.', author: 'Dr Hana Öztürk', role: 'Clinical trials manager' },
        { quote: 'The best booth partner I have worked with in this city — prepared, generous with the mic, and unflappable when the speaker went off-script for twenty minutes.', author: 'Jean-Paul Mercier', role: 'Conference interpreter' },
      ] }),
      b('quote', 'contact-form', { title: 'Request a quote', intro: 'Send the document or the event details and you will have a firm price and a delivery date, usually within four working hours.', fields: [
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'email', label: 'Email', type: 'email', required: true },
        { name: 'service', label: 'What do you need?', type: 'select', options: ['Certified translation', 'Legal or financial translation', 'Medical translation', 'Simultaneous interpreting', 'Consecutive interpreting', 'Revision'] },
        { name: 'pair', label: 'Language direction', type: 'select', options: ['FR → EN', 'EN → FR', 'ES → EN', 'Not sure'] },
        { name: 'deadline', label: 'Deadline or event date', type: 'text' },
        { name: 'detail', label: 'Word count, subject matter, anything else', type: 'textarea' },
      ], submitLabel: 'Request a quote', successMessage: 'Merci — you will have a firm quote within four working hours.' }),
      b('footer', 'footer', { brand: 'Camille Beauchamp', tagline: 'Certified translator & conference interpreter · Montréal.', links: [{ label: 'Services', href: '#services' }, { label: 'Experience', href: '#experience' }, { label: 'Quote', href: '#quote' }], copyright: '© Beauchamp Traduction · OTTIAQ 8841 · GST/QST registered' }),
    ],
  }),

  // ── management consultant ──────────────────────────────────────────────────
  tpl({
    id: 'professional-management-consultant',
    vertical: 'professional',
    label: 'Management Consultant — Conversational',
    description: 'An independent strategy consultant who shows a real discovery conversation instead of describing one.',
    tags: ['consulting', 'strategy', 'b2b', 'case-studies', 'dark'],
    layout: 'conversational',
    preset: 'midnight',
    meta: {
      title: 'Aster & Vale — Independent Management Consulting, Singapore',
      description: 'Operating-model and margin work for mid-market companies across Southeast Asia.',
      lang: 'en',
      favicon: '🧩',
    },
    blocks: [
      b('nav', 'nav', { brand: 'Aster & Vale', sticky: true, links: [{ label: 'How we start', href: '#thread' }, { label: 'Work', href: '#work' }, { label: 'Track record', href: '#record' }, { label: 'Who we are', href: '#bios' }], cta: { label: 'Start a conversation', href: '#start' } }),
      b('hero', 'hero', { eyebrow: 'Two partners · Singapore · Mid-market Southeast Asia', headline: 'No deck until we understand the business', subhead: 'Aster & Vale does operating-model, pricing and margin work for companies between S$20m and S$400m in revenue. Here is exactly how a first conversation goes.', align: 'left', minHeight: 'md', overlay: 'none', cta: { label: 'Read the conversation', href: '#thread' } }),
      b('thread', 'chat-thread', {
        title: 'A first conversation, more or less verbatim',
        subtitle: 'Reconstructed from a real engagement with the client’s permission. Names changed.',
        participants: [
          { id: 'client', name: 'Wei Lin — COO, distribution', role: 'user' },
          { id: 'av', name: 'Nadia — Aster & Vale', role: 'agent' },
        ],
        messages: [
          { from: 'client', time: '09:04', body: [{ kind: 'text', text: 'We turned over S$118m last year and made almost nothing. The board wants a cost programme. Can you run one?' }] },
          { from: 'av', time: '09:11', body: [{ kind: 'text', text: 'Probably — but before we agree to that, can I ask three things? What was gross margin five years ago, what is it now, and has your customer mix changed in between?' }] },
          { from: 'client', time: '09:26', body: [{ kind: 'text', text: '31% then, 22% now. Mix has moved a lot — we went hard after the big supermarket accounts in 2022.' }] },
          { from: 'av', time: '09:31', body: [
            { kind: 'text', text: 'Then a cost programme is likely to be the wrong project. Nine points of gross margin over a mix shift that size is usually a pricing and channel problem, not an overhead problem. Cutting cost will make the P&L look better for two quarters and leave the cause running.' },
            { kind: 'text', text: 'Here is what I would propose instead as a first step:' },
            { kind: 'list', ordered: true, items: [
              { label: 'Four weeks, two of us, fixed fee. No junior team.' },
              { label: 'Rebuild profitability by customer and by SKU from your raw invoice lines — not from the management accounts.' },
              { label: 'Cost-to-serve model including delivery frequency, returns and credit terms.' },
              { label: 'One session with your board on what to stop selling, and to whom.' },
            ] },
          ] },
          { from: 'client', time: '09:40', body: [{ kind: 'text', text: 'Our finance team will say the data is not clean enough for that.' }] },
          { from: 'av', time: '09:44', body: [{ kind: 'text', text: 'It never is, and it does not need to be. We work from invoice lines and delivery manifests, which are messy but true. If your top forty customers are 80% of revenue, we only need those forty to be right, and we can check them by hand in a day.' }] },
          { from: 'client', time: '09:52', body: [{ kind: 'text', text: 'And if you get four weeks in and find it really is overhead?' }] },
          { from: 'av', time: '09:55', body: [
            { kind: 'text', text: 'Then we say so, hand over the model, and you are free to run the cost programme with anyone you like. We would rather be wrong in week four than in month nine.' },
            { kind: 'buttons', items: [{ label: 'See what this engagement found', href: '#work' }, { label: 'Start a conversation', href: '#start' }] },
          ] },
        ],
      }),
      b('work', 'feed', { title: 'What came of it, and three others', layout: 'cards', items: [
        { title: 'Distribution — S$118m revenue, Singapore & Johor', subtitle: 'Margin & channel mix', text: 'Eleven of the forty largest accounts were loss-making after cost-to-serve. Repricing and two exits took gross margin from 22% to 27.4% in three quarters.', badge: '4 weeks', image: img('consulting-case-distribution'), href: '#' },
        { title: 'Contract manufacturer — 1,400 staff, Batam & Penang', subtitle: 'Operating model', text: 'Plant managers had accountability for output but not material cost. We redrew the P&L to plant level and rebuilt the weekly operating review. Scrap down 31%.', badge: '9 weeks', image: img('consulting-case-manufacturing'), href: '#' },
        { title: 'B2B services roll-up — six acquired agencies', subtitle: 'Post-merger integration', text: 'Stopped a shared-services consolidation that would have broken client relationships, and integrated pricing and utilisation reporting instead. EBITDA +4.1 points.', badge: '12 weeks', image: img('consulting-case-rollup'), href: '#' },
        { title: 'Regional retailer — 62 stores, Malaysia', subtitle: 'Pricing', text: 'Built a zone pricing model and a rule for when a store may discount. Like-for-like gross profit up 9% with no change to footfall.', badge: '6 weeks', image: img('consulting-case-retail'), href: '#' },
      ] }),
      b('record', 'stats', { title: 'Since we left the big firms in 2018', columns: 4, items: [
        { value: '47', label: 'Engagements delivered' },
        { value: '2', label: 'Partners on every project' },
        { value: '6.2', label: 'Average EBITDA points added' },
        { value: '68', label: 'Repeat or referred work', suffix: '%' },
      ] }),
      b('terms', 'accordion', { title: 'How we work, and what it costs', items: [
        { heading: 'Fixed fee, agreed before we start', body: 'A four-week diagnostic is S$68,000. Longer implementation work runs S$52,000 a month for both partners at roughly 60% time. We do not bill expenses beyond travel outside Singapore, and we do not have a rate card with eleven levels on it because there are two of us.' },
        { heading: 'No juniors, no pyramid', body: 'The people you meet are the people who do the work. We take on four to five engagements a year, which is the honest capacity of two partners. If we are full we will say so and suggest someone else.' },
        { heading: 'We will decline work', body: 'If your question is really a decision the leadership team has already made and wants validated, we are the wrong firm and expensive cover. We turn down roughly a third of enquiries on that basis.' },
        { heading: 'You keep the models', body: 'Every spreadsheet, model and data pipeline we build is handed over live, documented, and yours. Nothing sits on a server we control after the engagement closes.' },
      ] }),
      b('bios', 'team', { title: 'Who we are', subtitle: 'Two partners. That is the whole firm.', columns: 2, members: [
        { name: 'Nadia Rahim', role: 'Partner — Commercial', photo: img('consulting-partner-nadia'), bio: 'Twelve years in strategy consulting across Singapore and Jakarta, then two as commercial director of a S$200m distributor. Does the customer economics.', socials: [{ label: 'LinkedIn', href: '#' }] },
        { name: 'Gerald Vale', role: 'Partner — Operations', photo: img('consulting-partner-gerald'), bio: 'Former plant director in contract electronics, then operations practice at a global firm. Does the plants, the org design and the operating reviews.', socials: [{ label: 'LinkedIn', href: '#' }] },
      ] }),
      b('start', 'contact-form', { title: 'Start a conversation', intro: 'One of the two of us replies personally, usually within a day. The first conversation is an hour and costs nothing.', fields: [
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'company', label: 'Company', type: 'text', required: true },
        { name: 'email', label: 'Work email', type: 'email', required: true },
        { name: 'revenue', label: 'Approximate revenue', type: 'select', options: ['Under S$20m', 'S$20m–S$80m', 'S$80m–S$200m', 'S$200m–S$400m', 'Over S$400m'] },
        { name: 'problem', label: 'What is the question you cannot answer?', type: 'textarea', placeholder: 'The messier the description, the better.' },
      ], submitLabel: 'Send', successMessage: 'Thank you — Nadia or Gerald will reply personally within one working day.' }),
      b('footer', 'footer', { brand: 'Aster & Vale', tagline: '9 Straits View, Marina One, Singapore 018937 · +65 6100 4482', links: [{ label: 'Work', href: '#work' }, { label: 'How we work', href: '#terms' }, { label: 'Start', href: '#start' }], copyright: '© Aster & Vale Advisory Pte Ltd · UEN 201834911K' }),
    ],
  }),
];
