/**
 * `realestate` starter templates — high-street agency, a single luxury listing,
 * a new-build launch, a lettings catalogue, commercial brokerage and a mortgage broker.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const realestateTemplates: Template[] = [
  tpl({
    id: 'realestate-agency',
    vertical: 'realestate',
    label: 'Real Estate — Agency',
    description: 'A local sales-and-lettings estate agency leading with listings, track record and the people behind them.',
    tags: ['estate-agency', 'local', 'gallery', 'reviews', 'one-pager'],
    layout: 'classic',
    preset: 'ocean',
    meta: { title: 'Meridian Estates', description: 'A local estate agency that actually answers the phone.', lang: 'en', favicon: '🏡' },
    blocks: [
      b('nav', 'nav', { brand: 'Meridian', sticky: true, links: [{ label: 'Listings', href: '#listings' }, { label: 'Sell', href: '#sell' }, { label: 'Team', href: '#team' }], cta: { label: 'Book a valuation', href: '#contact' } }),
      b('hero', 'hero', { eyebrow: 'Sales & lettings', headline: 'Move with people who know the area', subhead: 'Honest advice, sharp photography, and a valuation that’s actually realistic.', align: 'left', minHeight: 'md', image: img('estate-hero'), overlay: 'light', cta: { label: 'Book a free valuation', href: '#contact' } }),
      b('listings', 'gallery', { layout: 'grid', columns: 3, gap: 'md', lightbox: true, items: [{ src: img('home-1'), alt: 'Terraced house' }, { src: img('home-2'), alt: 'Garden flat' }, { src: img('home-3'), alt: 'New-build' }, { src: img('home-4'), alt: 'Cottage' }, { src: img('home-5'), alt: 'Townhouse' }, { src: img('home-6'), alt: 'Apartment' }] }),
      b('sell', 'features', { title: 'Why sell with us', columns: 3, items: [
        { icon: '📸', title: 'Photography that sells', text: 'Pro photos, floorplans, and video.' },
        { icon: '📞', title: 'We answer', text: 'A named agent, reachable seven days.' },
        { icon: '💷', title: 'Fair fees', text: 'Simple percentage, no tie-ins.' },
      ] }),
      b('stats', 'stats', { title: 'Our track record', columns: 4, items: [
        { value: '98', label: 'Of asking price', suffix: '%' },
        { value: '28', label: 'Avg. days to offer' },
        { value: '450', label: 'Homes sold', suffix: '+' },
        { value: '4.9', label: 'Google rating', suffix: '★' },
      ] }),
      b('team', 'team', { title: 'Your local team', columns: 3, members: [
        { name: 'Olivia Grant', role: 'Branch Manager', photo: img('agent-1'), bio: '15 years selling in the area.' },
        { name: 'Daniel Cross', role: 'Senior Negotiator', photo: img('agent-2'), bio: 'Sales and chain management.' },
        { name: 'Priya Nair', role: 'Lettings Manager', photo: img('agent-3'), bio: 'Landlords and tenants alike.' },
      ] }),
      b('reviews', 'testimonials', { title: 'From movers', items: [
        { quote: 'Sold above asking in ten days. Communication was brilliant.', author: 'The Wrights', role: 'Sellers' },
        { quote: 'They found us the flat before it hit the portals. Legends.', author: 'Sam', role: 'Buyer' },
      ] }),
      b('contact', 'contact-details', { title: 'Book a valuation', address: '12 Market Place, Nottingham NG1 6HY', phone: '+44 115 000 0000', email: 'hello@meridianestates.co.uk', hours: 'Mon–Sat 9:00–18:00' }),
      b('cta', 'cta', { headline: 'Thinking of moving?', subhead: 'Start with a free, no-obligation valuation.', background: 'primary', button: { label: 'Book a valuation', href: '#contact' } }),
      b('footer', 'footer', { brand: 'Meridian Estates', tagline: 'Sales & lettings.', links: [{ label: 'Listings', href: '#listings' }, { label: 'Valuation', href: '#contact' }], copyright: '© Meridian Estates' }),
    ],
  }),

  tpl({
    id: 'realestate-luxury',
    vertical: 'realestate',
    label: 'Property — Single luxury listing',
    description: 'One trophy home, sold on imagery: full-bleed hero, walkthrough film and a private viewing request.',
    tags: ['luxury', 'gallery', 'video', 'showcase', 'single-listing'],
    layout: 'showcase',
    preset: 'midnight',
    meta: { title: 'The Aldridge Residence — 1180 Skyline Ridge Road', description: 'A 6,240 sq ft contemporary residence above Lake Austin, offered at $4,750,000.', lang: 'en', favicon: '🏛️' },
    blocks: [
      b('notice', 'announcement-bar', { text: 'Private viewings by appointment — open house Saturday 23 May, 1–4pm.', linkLabel: 'Request a slot', href: '#enquire', tone: 'promo', dismissible: true }),
      b('nav', 'nav', { brand: 'Skyline Ridge', sticky: true, links: [{ label: 'Gallery', href: '#gallery' }, { label: 'The residence', href: '#residence' }, { label: 'Film', href: '#film' }, { label: 'Location', href: '#location' }], cta: { label: 'Arrange a viewing', href: '#enquire' } }),
      b('hero', 'hero', { eyebrow: 'Offered at $4,750,000', headline: 'The Aldridge Residence', subhead: 'Five bedrooms, an infinity edge pool and 180° hill country views, ten minutes from downtown Austin.', align: 'left', minHeight: 'full', image: img('luxury-aldridge-hero'), overlay: 'dark', cta: { label: 'View the gallery', href: '#gallery' } }),
      b('facts', 'stats', { title: 'At a glance', columns: 4, items: [
        { value: '5', label: 'Bedrooms' },
        { value: '4.5', label: 'Bathrooms' },
        { value: '6,240', label: 'Interior', suffix: ' sq ft' },
        { value: '1.2', label: 'Acre lot' },
      ] }),
      b('gallery', 'gallery', { layout: 'masonry', columns: 3, gap: 'lg', lightbox: true, items: [
        { src: img('luxury-aldridge-facade'), alt: 'Cantilevered limestone and glass façade at dusk', caption: 'Approach from Skyline Ridge Road' },
        { src: img('luxury-aldridge-living'), alt: 'Double-height living room with a stone fireplace', caption: 'Living room, 22ft ceilings' },
        { src: img('luxury-aldridge-kitchen'), alt: 'Kitchen with a walnut island and integrated appliances', caption: 'Kitchen by Bulthaup' },
        { src: img('luxury-aldridge-primary'), alt: 'Primary bedroom opening onto a terrace', caption: 'Primary suite' },
        { src: img('luxury-aldridge-bath'), alt: 'Marble bathroom with a freestanding tub', caption: 'Primary bath' },
        { src: img('luxury-aldridge-pool'), alt: 'Infinity pool overlooking the hills', caption: '60ft infinity edge pool' },
        { src: img('luxury-aldridge-terrace'), alt: 'Covered terrace with an outdoor kitchen', caption: 'Evening terrace' },
        { src: img('luxury-aldridge-study'), alt: 'Book-lined study with a glass wall', caption: 'Study / fifth bedroom' },
      ] }),
      b('residence', 'split', { rows: [
        { title: 'Built to catch the light', text: 'Completed in 2021 by Halbert Ward Architects, the house is arranged as three linked pavilions so every principal room takes the western view. Floor-to-ceiling glazing is shaded by a 9ft limestone overhang, keeping the interiors cool through an Austin August.', image: img('luxury-aldridge-architecture'), imageAlt: 'Three linked pavilions seen from the garden' },
        { title: 'A kitchen for people who cook', text: 'Bulthaup cabinetry, a 4.2m walnut island, twin Gaggenau ovens and a scullery behind. The dining terrace is eight steps away, with a built-in grill and a fig tree that was on the plot long before the house was.', image: img('luxury-aldridge-dining'), imageAlt: 'Dining terrace under a fig tree' },
        { title: 'Grounds and guest house', text: 'Just over an acre of oak and native grasses, xeriscaped so it needs almost no irrigation. A detached 640 sq ft guest house sits at the north edge with its own kitchenette, currently let as a studio.', image: img('luxury-aldridge-grounds'), imageAlt: 'Oak trees and native planting around the guest house' },
      ] }),
      b('film', 'video', { provider: 'youtube', src: 'https://www.youtube.com/watch?v=BHACKCNDMW8', title: 'Walkthrough film — The Aldridge Residence', poster: img('luxury-aldridge-film-poster'), caption: 'Four-minute walkthrough, filmed March 2026.' }),
      b('location', 'map', { query: '1180 Skyline Ridge Road, Austin, TX 78746', zoom: 14, height: 400, label: 'Skyline Ridge — Eanes ISD, 12 min to downtown' }),
      b('enquire', 'contact-form', { title: 'Arrange a private viewing', intro: 'Viewings are accompanied and take about an hour. Rowan Alvarez, the listing agent, will confirm within the day.', submitLabel: 'Request a viewing', successMessage: 'Thank you — Rowan will call you to confirm a time.', fields: [
        { name: 'name', label: 'Your name', type: 'text', placeholder: 'Jordan Whitfield', required: true },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'you@example.com', required: true },
        { name: 'phone', label: 'Phone', type: 'tel', placeholder: '(512) 555-0142' },
        { name: 'when', label: 'Preferred day', type: 'select', options: ['Weekday morning', 'Weekday afternoon', 'Saturday', 'Sunday'] },
        { name: 'position', label: 'Your position', type: 'select', options: ['Cash buyer', 'Financed, pre-approved', 'Financed, not yet approved', 'Representing a buyer'] },
        { name: 'notes', label: 'Anything we should know?', type: 'textarea', placeholder: 'Timescale, questions about the guest house…' },
      ] }),
      b('footer', 'footer', { brand: 'Skyline Ridge', tagline: 'Listed by Rowan Alvarez · Marchetti & Fine, Austin · TREC #0592184', links: [{ label: 'Gallery', href: '#gallery' }, { label: 'Film', href: '#film' }, { label: 'Arrange a viewing', href: '#enquire' }], copyright: '© Marchetti & Fine. Information deemed reliable but not guaranteed.' }),
    ],
  }),

  tpl({
    id: 'realestate-newbuild',
    vertical: 'realestate',
    label: 'Development — New-build launch',
    description: 'A single-purpose launch page for a new-build scheme: release pricing, reservation steps and a waiting list.',
    tags: ['new-build', 'pricing', 'landing', 'newsletter', 'b2c'],
    layout: 'landing',
    preset: 'sand',
    meta: { title: 'Marlowe Quarter — Brunswick', description: 'Forty-two apartments and eight terraces on the old Marlowe brickworks site, Brunswick VIC. Stage two now released.', lang: 'en', favicon: '🏗️' },
    blocks: [
      b('nav', 'nav', { brand: 'Marlowe Quarter', sticky: true, links: [{ label: 'The homes', href: '#homes' }, { label: 'Reserving', href: '#reserving' }, { label: 'Programme', href: '#programme' }], cta: { label: 'Join the list', href: '#register' } }),
      b('hero', 'hero', { eyebrow: 'Stage two released · Brunswick VIC', headline: 'Fifty homes on the old brickworks', subhead: 'One, two and three-bedroom apartments plus eight terraces, a shared courtyard, and Anstey station four minutes on foot. Completing winter 2027.', align: 'center', minHeight: 'lg', image: img('newbuild-marlowe-hero'), overlay: 'scrim', cta: { label: 'See the release prices', href: '#homes' } }),
      b('highlights', 'features', { title: 'Designed for the way Brunswick actually lives', subtitle: 'Built by Corliss Group with Ottoway Architects — their fourth project in the inner north.', columns: 4, items: [
        { icon: '☀️', title: '7.4-star average', text: 'Double glazing, heat-pump hot water, no gas connection anywhere on site.' },
        { icon: '🌿', title: 'Courtyard, not carpark', text: 'Parking is under the deck; the middle of the block is 900m² of garden.' },
        { icon: '🚲', title: '96 bike spaces', text: 'Secure basement storage and a workshop bench, plus two car-share bays.' },
        { icon: '🔑', title: '5% deposit', text: 'Deposit bonds accepted. Balance on settlement, not before.' },
      ] }),
      b('homes', 'pricing', { title: 'Stage two release', subtitle: 'Prices as at 1 May 2026. Eleven of the twenty-six released homes remain.', plans: [
        { name: 'One bedroom', price: '$549,000', period: 'from', features: ['52–58m² internal', '8m² balcony', 'Study nook to every plan', 'Six remaining'], ctaLabel: 'Request the plan', ctaHref: '#register' },
        { name: 'Two bedroom', price: '$729,000', period: 'from', features: ['78–86m² internal', 'Two bathrooms', 'One secure car space', 'Four remaining'], ctaLabel: 'Request the plan', ctaHref: '#register', featured: true },
        { name: 'Terrace', price: '$1,145,000', period: 'from', features: ['Three bedrooms over two levels', 'Private 40m² garden', 'Double garage with EV charger', 'One remaining'], ctaLabel: 'Request the plan', ctaHref: '#register' },
      ] }),
      b('reserving', 'steps', { title: 'How reserving works', subtitle: 'No ballots, no expressions-of-interest theatre. First in, first served.', items: [
        { title: 'Pick a plan', text: 'We send the floor plan, the finishes schedule and the body corporate estimate for your specific home — not a generic brochure.' },
        { title: 'Hold it for seven days', text: 'A $2,000 refundable holding deposit takes the home off the list while your solicitor reads the contract.' },
        { title: 'Exchange', text: 'Sign, pay the 5% balance of deposit into the trust account, and you are done until completion.' },
        { title: 'Choose your finishes', text: 'Around twelve months out you pick one of three palettes and, if you want, upgrade the joinery.' },
      ] }),
      b('programme', 'timeline', { title: 'Build programme', items: [
        { date: 'Complete', title: 'Site remediation', text: 'Brickworks slab removed, soil validated and signed off by the EPA-appointed auditor in November 2025.' },
        { date: 'Now', title: 'Structure', text: 'Basement poured; level three slab pours through July 2026.' },
        { date: 'Q1 2027', title: 'Façade and fit-out', text: 'Brick and anodised aluminium façade, then internal fit-out floor by floor.' },
        { date: 'Winter 2027', title: 'Settlement', text: 'Occupancy permit expected June 2027, with settlements over the following six weeks.' },
      ] }),
      b('faq', 'faq', { title: 'The questions buyers actually ask', items: [
        { question: 'What are the body corporate fees?', answer: 'Estimated at $3,100 a year for a two-bedroom, including building insurance, the lift, gardens and the sinking fund. The full estimate is in the contract disclosure.' },
        { question: 'Is it eligible for the Victorian off-the-plan duty concession?', answer: 'Most one and two-bedroom homes are, which on a $729,000 apartment is worth roughly $28,000. Your conveyancer will confirm against your own circumstances.' },
        { question: 'Can I get a rental appraisal?', answer: 'Yes. Three local agents have appraised stage one two-bedrooms at $640–$700 a week. We will send all three, not just the highest.' },
        { question: 'What if the build runs late?', answer: 'The contract has a sunset date of 31 December 2027. If we pass it, you can rescind and take your deposit back with interest.' },
      ] }),
      b('register', 'newsletter', { title: 'Join the stage three list', intro: 'Stage three — sixteen homes facing the courtyard — releases in spring. List members get plans and prices a fortnight before the public launch.', placeholder: 'you@example.com', submitLabel: 'Add me to the list', successMessage: 'You are on the list. We will email before the public release, and not otherwise.' }),
      b('visit', 'cta', { headline: 'The display suite is open Thursday to Sunday', subhead: '14 Weston Street, Brunswick VIC 3056 · 11am–4pm · No appointment needed.', background: 'accent', button: { label: 'Get the release prices', href: '#homes' } }),
      b('footer', 'footer', { brand: 'Marlowe Quarter', tagline: 'A Corliss Group development · Sales by Halloran Property, licence 084112L', links: [{ label: 'The homes', href: '#homes' }, { label: 'Build programme', href: '#programme' }, { label: 'Join the list', href: '#register' }], copyright: '© Corliss Group. Renders are indicative; landscaping shown at maturity.' }),
    ],
  }),

  tpl({
    id: 'realestate-lettings',
    vertical: 'realestate',
    label: 'Lettings — Rentals catalogue',
    description: 'A letting agent whose available rentals are the page itself, with landlord fees and tenant guides underneath.',
    tags: ['rentals', 'catalogue', 'pricing', 'faq', 'local'],
    layout: 'catalogue',
    preset: 'forest',
    meta: { title: 'Kastanien Wohnen — Rentals in Prenzlauer Berg', description: 'Long-let apartments in Prenzlauer Berg and Pankow, managed by a five-person team that answers in German and English.', lang: 'en', favicon: '🔑' },
    blocks: [
      b('nav', 'nav', { brand: 'Kastanien Wohnen', sticky: true, links: [{ label: 'Available now', href: '#available' }, { label: 'Landlords', href: '#landlords' }, { label: 'Tenant guides', href: '#guides' }, { label: 'Fees', href: '#fees' }], cta: { label: 'Book a viewing', href: '#contact' } }),
      b('find', 'search', { layout: 'bar', placeholder: 'Kiez, rooms or budget — try “Pankow 2 rooms”', label: 'Find a rental', buttonLabel: 'Search', name: 'q', align: 'center' }),
      b('available', 'product', { title: 'Available now', subtitle: 'Six apartments free this month, updated every morning. Cold rent shown; Nebenkosten listed on each listing.', columns: 3, items: [
        { name: 'Stargarder Straße 44 · 2 rooms', description: '61m², second floor, Altbau with original parquet and a courtyard-facing balcony. Free from 1 July.', price: '€1,290 / mo', image: img('lettings-kastanien-stargarder'), badge: 'New', ctaLabel: 'Book a viewing', ctaHref: '#contact' },
        { name: 'Dunckerstraße 9 · 1.5 rooms', description: '44m², top floor, renovated 2024, lift, no through traffic. Suits one person or a couple.', price: '€895 / mo', image: img('lettings-kastanien-duncker'), ctaLabel: 'Book a viewing', ctaHref: '#contact' },
        { name: 'Wisbyer Straße 118 · 3 rooms', description: '84m², first floor, two bedrooms plus a study, fitted kitchen included, Kita on the same block.', price: '€1,640 / mo', image: img('lettings-kastanien-wisbyer'), badge: 'Family', ctaLabel: 'Book a viewing', ctaHref: '#contact' },
        { name: 'Greifenhagener Str. 22 · 2 rooms', description: '58m², rear building, quiet, gas heating replaced with a heat pump in 2025. Pets discussed case by case.', price: '€1,150 / mo', image: img('lettings-kastanien-greifenhagener'), ctaLabel: 'Book a viewing', ctaHref: '#contact' },
        { name: 'Florastraße 61 · 4 rooms', description: '112m² maisonette in Pankow with a roof terrace and two bathrooms. Twelve-month minimum term.', price: '€2,240 / mo', image: img('lettings-kastanien-flora'), ctaLabel: 'Book a viewing', ctaHref: '#contact' },
        { name: 'Schönhauser Allee 178 · Studio', description: '32m² furnished studio, three-month minimum, all bills and internet included. Good for a relocation.', price: '€1,050 / mo', image: img('lettings-kastanien-schoenhauser'), badge: 'Furnished', ctaLabel: 'Book a viewing', ctaHref: '#contact' },
      ] }),
      b('landlords', 'services-catalogue', { title: 'For landlords', subtitle: 'Three levels of service. Percentages are of collected cold rent, billed monthly, cancellable on three months’ notice.', items: [
        { name: 'Tenant find', description: 'Photography, floor plan, portal listing, accompanied viewings, SCHUFA and income checks, and the signed contract handed to you.', price: '1.5 months’ cold rent', ctaLabel: 'Enquire', ctaHref: '#contact' },
        { name: 'Rent collection', description: 'Everything in tenant find, plus rent collection, arrears chasing and an annual statement your Steuerberater will accept without complaint.', price: '4.5% / month', ctaLabel: 'Enquire', ctaHref: '#contact' },
        { name: 'Full management', description: 'Rent collection plus repairs, contractor coordination, annual inspections, Nebenkostenabrechnung and all tenant contact. You hear from us twice a year.', price: '7.5% / month', ctaLabel: 'Enquire', ctaHref: '#contact' },
        { name: 'Handover only', description: 'For self-managing owners: a professional check-in or check-out with a photographic protocol and meter readings.', price: '€240 flat', ctaLabel: 'Enquire', ctaHref: '#contact' },
      ] }),
      b('guides', 'tabs', { items: [
        { label: 'Viewing', text: 'Viewings are individual, not the fifty-people-on-a-staircase kind. Bring photo ID and, if you have them, your last three payslips and a SCHUFA extract — it means we can hold the apartment for you the same day. If you cannot make the times listed, ask: we keep two evening slots a week for people who work shifts.' },
        { label: 'Applying', text: 'We need proof of income covering roughly three times the cold rent, a SCHUFA-Bonitätsauskunft less than three months old, ID, and a Mietschuldenfreiheitsbescheinigung from your current landlord if you have one. Freelancers can substitute the last two tax assessments. We charge tenants nothing — under the Bestellerprinzip the landlord pays.' },
        { label: 'Moving in', text: 'You get the keys at the check-in appointment, where we photograph every room and read the meters together. The protocol is signed by both sides and emailed to you within a day. Your Wohnungsgeberbestätigung — the document you need for your Anmeldung — is handed over at the same appointment.' },
        { label: 'Living there', text: 'Repairs go through the tenant portal or WhatsApp; anything without heating or hot water is treated as urgent and we aim to have someone out the same day. The Nebenkostenabrechnung is issued each November for the previous calendar year, with the receipts available to inspect at our office.' },
      ] }),
      b('fees', 'accordion', { title: 'Fees and the small print', items: [
        { heading: 'What do tenants pay?', body: 'Nothing to us. Under the Bestellerprinzip the party who instructs the agent pays the agent, and that is always the landlord. Any agent asking you for commission on a normal long let is breaking the law — report them.' },
        { heading: 'What is the deposit?', body: 'Three months’ cold rent, the legal maximum. You may pay it in three monthly instalments and it sits in a separate interest-bearing Mietkautionskonto in your name. We return it, with interest, within six weeks of a clean check-out.' },
        { heading: 'How are rent increases handled?', body: 'Prenzlauer Berg is a Milieuschutz area and everything we manage sits inside the Mietspiegel. Increases follow §558 BGB: capped, no more than once every fifteen months, and always with the Mietspiegel comparison attached so you can check the arithmetic yourself.' },
        { heading: 'Can I keep a pet?', body: 'Small animals need no permission at all. For a dog or a cat we ask the landlord, and roughly four in five say yes. A blanket ban in a contract is not enforceable in Germany, and we do not write one.' },
        { heading: 'Do you let to shared households?', body: 'Yes, on about half our stock. Everyone goes on the contract jointly, and swapping a flatmate later is a short amendment rather than a whole new tenancy.' },
      ] }),
      b('hours', 'hours', { title: 'Office hours', timezone: 'Europe/Berlin', note: 'Viewings run until 19:00 on Tuesdays and Thursdays. Emergency repairs: call any time.', days: [
        { day: 'mon', open: '09:00', close: '17:00' },
        { day: 'tue', open: '09:00', close: '19:00' },
        { day: 'wed', open: '09:00', close: '17:00' },
        { day: 'thu', open: '09:00', close: '19:00' },
        { day: 'fri', open: '09:00', close: '15:00' },
        { day: 'sat', open: '10:00', close: '13:00' },
        { day: 'sun', closed: true },
      ] }),
      b('findus', 'directions', { title: 'Finding the office', place: 'Kastanien Wohnen', address: 'Kastanienallee 71, 10435 Berlin', lat: '52.5387', lng: '13.4103', mapUrl: 'https://maps.google.com/?q=Kastanienallee+71,+10435+Berlin', directionsLabel: 'Open in maps', appleMaps: true }),
      b('contact', 'contact-details', { title: 'Talk to us', address: 'Kastanienallee 71, 10435 Berlin', phone: '+49 30 5555 0180', email: 'buero@kastanienwohnen.de', hours: 'Mon–Thu 9:00–17:00, Fri to 15:00, Sat 10:00–13:00' }),
      b('footer', 'footer', { brand: 'Kastanien Wohnen', tagline: 'Vermietung und Hausverwaltung · IVD member · Erlaubnis nach §34c GewO', links: [{ label: 'Available now', href: '#available' }, { label: 'Landlords', href: '#landlords' }, { label: 'Fees', href: '#fees' }], copyright: '© Kastanien Wohnen GmbH, Berlin' }),
    ],
  }),

  tpl({
    id: 'realestate-commercial',
    vertical: 'realestate',
    label: 'Commercial — Brokerage & advisory',
    description: 'A type-led commercial brokerage page: market view first, then deals done, the desk, and research notes.',
    tags: ['b2b', 'commercial', 'long-form', 'editorial', 'advisory'],
    layout: 'editorial',
    preset: 'mono',
    meta: { title: 'Kestrel Commercial Advisors — Mumbai', description: 'Office, industrial and retail brokerage across the MMR. Leasing, capital markets and occupier advisory.', lang: 'en', favicon: '🏢' },
    blocks: [
      b('nav', 'nav', { brand: 'Kestrel', sticky: false, links: [{ label: 'View', href: '#view' }, { label: 'Deals', href: '#deals' }, { label: 'Desk', href: '#desk' }, { label: 'Research', href: '#research' }], cta: { label: 'Speak to the desk', href: '#contact' } }),
      b('hero', 'hero', { eyebrow: 'Office · Industrial · Retail · MMR', headline: 'We only advise on buildings we would take space in ourselves', subhead: 'Kestrel is a fourteen-person brokerage in BKC. We lease, we sell, and we tell occupiers when the right answer is to stay exactly where they are.', align: 'left', minHeight: 'sm', overlay: 'none', cta: { label: 'Read this quarter’s view', href: '#view' } }),
      b('view', 'rich-text', { blocks: [
        { kind: 'heading', text: 'The Mumbai market as we actually see it' },
        { kind: 'paragraph', text: 'Grade A vacancy across the MMR closed the quarter at 11.4%, but that single number hides two different markets. In BKC and Lower Parel, genuinely institutional stock is tight and headline rents held at ₹310–₹360 per sq ft per month. Push out to the Thane–Belapur belt and the picture inverts: eleven million square feet under construction into a market absorbing roughly two million a year.' },
        { kind: 'subheading', text: 'What that means if you are leasing' },
        { kind: 'paragraph', text: 'Landlords in the central submarkets have stopped discounting and started competing on fit-out contribution instead. We are seeing ₹1,800–₹2,600 per sq ft of capex offered on a nine-year term with a three-year lock-in — worth more than the two months rent-free most occupiers ask for first, and easier for a landlord to say yes to.' },
        { kind: 'bullet', text: 'Take the capex, not the rent-free, if you are fitting out anyway.' },
        { kind: 'bullet', text: 'Negotiate the escalation clause hardest — 15% every three years is now genuinely movable to 12%.' },
        { kind: 'bullet', text: 'In the periphery, do not sign anything longer than five years this year.' },
        { kind: 'subheading', text: 'What that means if you own' },
        { kind: 'paragraph', text: 'Cap rates on leased BKC office have compressed about 40 basis points over twelve months as domestic institutional money has come back. If you hold a single-tenant asset with more than six years of term certain, this is a better exit window than most of us expected in January.' },
        { kind: 'quote', text: 'The buildings that let in a soft market are the ones whose landlord answered the phone during the last one.' },
      ] }),
      b('clients', 'logos', { title: 'Occupiers and owners we have acted for', items: [
        { src: img('commercial-kestrel-client-1'), alt: 'Sarvatra Financial' },
        { src: img('commercial-kestrel-client-2'), alt: 'Halcyon Logistics' },
        { src: img('commercial-kestrel-client-3'), alt: 'Nadkarni & Rao' },
        { src: img('commercial-kestrel-client-4'), alt: 'Bluewick Retail' },
        { src: img('commercial-kestrel-client-5'), alt: 'Tarrant Pharma' },
        { src: img('commercial-kestrel-client-6'), alt: 'Ashwath Capital' },
      ] }),
      b('deals', 'timeline', { title: 'Recently concluded', items: [
        { date: 'Apr 2026', title: '84,000 sq ft · One Trellis, BKC', text: 'Acted for a global payments occupier on a nine-year lease with a three-year lock-in. Secured ₹2,400 per sq ft of fit-out contribution and a 12% triennial escalation.' },
        { date: 'Feb 2026', title: '₹412 crore · Industrial portfolio, Bhiwandi', text: 'Sale of four warehouse assets totalling 1.1m sq ft for a family office. Six bidders; closed 7% above the guide.' },
        { date: 'Nov 2025', title: '26,500 sq ft · Peninsula Corporate Park', text: 'Occupier advisory for a law firm that ultimately renewed rather than moved. Restructured the existing lease and saved an estimated ₹9 crore over the term.' },
        { date: 'Aug 2025', title: '160,000 sq ft · Powai campus letting', text: 'Landlord letting mandate on a repositioned IT campus, taken from 38% let to fully let in eleven months across five tenants.' },
      ] }),
      b('figures', 'stats', { title: 'The desk in numbers', columns: 4, items: [
        { value: '4.2', label: 'Sq ft transacted, 2025', suffix: 'm' },
        { value: '1,180', label: 'Concluded value, 2025', prefix: '₹', suffix: ' cr' },
        { value: '14', label: 'Advisors on the desk' },
        { value: '68', label: 'Repeat instructions', suffix: '%' },
      ] }),
      b('desk', 'team', { title: 'The desk', subtitle: 'Four practice heads. You deal with one of them, not with an account manager.', columns: 2, members: [
        { name: 'Ishaan Bhatt', role: 'Managing Partner · Capital Markets', photo: img('commercial-kestrel-ishaan'), bio: 'Nineteen years in Mumbai investment sales, previously at a global agency. Runs the institutional relationships.' },
        { name: 'Meera Sundaram', role: 'Head of Industrial & Logistics', photo: img('commercial-kestrel-meera'), bio: 'Bhiwandi, Panvel and the JNPT corridor. Started out as a warehouse operations manager, which shows.' },
        { name: 'Farhan Qureshi', role: 'Head of Office Leasing', photo: img('commercial-kestrel-farhan'), bio: 'Leases BKC, Worli and Lower Parel. Has represented both sides of the same building — never at the same time.' },
        { name: 'Aditi Raval', role: 'Head of Occupier Advisory', photo: img('commercial-kestrel-aditi'), bio: 'Portfolio strategy, lease restructuring, and the unglamorous work of getting out of a bad lease early.' },
      ] }),
      b('research', 'blog-list', { title: 'Research notes', columns: 3, posts: [
        { title: 'MMR Office Snapshot — Q1 2026', excerpt: 'Submarket-by-submarket vacancy, net absorption and the gap between headline and effective rents. Twelve pages, no filler.', href: '#', image: img('commercial-kestrel-research-office'), date: '14 April 2026', tag: 'Office' },
        { title: 'Warehousing beyond Bhiwandi', excerpt: 'Why the next four million square feet of grade A logistics goes to Panvel and Palghar, and what the land is trading at today.', href: '#', image: img('commercial-kestrel-research-logistics'), date: '3 March 2026', tag: 'Industrial' },
        { title: 'Reading an escalation clause properly', excerpt: 'A short guide for occupier finance teams: compounding, resets, and the three clauses that quietly cost you a year of rent.', href: '#', image: img('commercial-kestrel-research-leases'), date: '19 January 2026', tag: 'Occupier' },
      ] }),
      b('contact', 'contact-details', { title: 'Speak to the desk', address: '9th floor, Trellis Tower, G Block, Bandra Kurla Complex, Mumbai 400051', phone: '+91 22 6555 0100', email: 'desk@kestreladvisors.in', hours: 'Mon–Fri 9:30–18:30 IST' }),
      b('terms', 'legal', { title: 'Regulatory', align: 'start', separator: '·', documents: [
        { label: 'RERA', title: 'RERA registration', content: 'Kestrel Commercial Advisors LLP is registered as a real estate agent with MahaRERA under registration number A519900041286, valid to 31 March 2029. The registration certificate is available for inspection at the BKC office on request.' },
        { label: 'Disclaimer', title: 'Particulars disclaimer', content: 'All areas, rents and capital values published on this site are indicative and given without responsibility. Nothing here constitutes an offer or a contract. Intending purchasers and lessees must satisfy themselves by inspection and independent enquiry as to the correctness of each statement.' },
        { label: 'Fees', title: 'How we are paid', content: 'Brokerage on leasing mandates is charged at one month of rent per year of lock-in, capped at two months, payable by the instructing party. Capital markets fees are agreed case by case and disclosed in writing before any marketing begins. We do not take a fee from both sides of a transaction.' },
      ] }),
      b('footer', 'footer', { brand: 'Kestrel Commercial Advisors', tagline: 'Office, industrial and retail across the Mumbai Metropolitan Region.', links: [{ label: 'Research', href: '#research' }, { label: 'The desk', href: '#desk' }, { label: 'Contact', href: '#contact' }], copyright: '© Kestrel Commercial Advisors LLP · MahaRERA A519900041286' }),
    ],
  }),

  tpl({
    id: 'realestate-mortgage',
    vertical: 'realestate',
    label: 'Mortgage broker — Chat-led',
    description: 'A mortgage broker who explains things in plain language, framed as a real conversation with a first-time buyer.',
    tags: ['mortgage', 'conversational', 'reviews', 'faq', 'first-time-buyer'],
    layout: 'conversational',
    preset: 'candy',
    meta: { title: 'Northline Mortgage — Toronto', description: 'An independent Toronto mortgage brokerage for first-time buyers, renewals and self-employed applicants.', lang: 'en', favicon: '💬' },
    blocks: [
      b('nav', 'nav', { brand: 'Northline', sticky: true, links: [{ label: 'How it goes', href: '#thread' }, { label: 'Process', href: '#process' }, { label: 'Reviews', href: '#reviews' }, { label: 'Questions', href: '#faq' }], cta: { label: 'Start a conversation', href: '#apply' } }),
      b('hero', 'hero', { eyebrow: 'Independent · 40+ lenders · Toronto', headline: 'Ask us the question you think is too basic', subhead: 'We are brokers, not a bank branch. Nobody here earns more for steering you to one particular lender, and no question about how any of this works is too small.', align: 'left', minHeight: 'sm', overlay: 'none', cta: { label: 'See a real conversation', href: '#thread' } }),
      b('thread', 'chat-thread', { title: 'A first conversation, more or less verbatim', subtitle: 'Shared with permission. Names changed, numbers not.', participants: [
        { id: 'dev', name: 'Devon', role: 'user', avatar: img('mortgage-northline-devon') },
        { id: 'sam', name: 'Sam Oyelaran, broker', role: 'agent', avatar: img('mortgage-northline-sam') },
      ], messages: [
        { from: 'dev', time: '10:02', body: [{ kind: 'text', text: 'Hi — we have about $70k saved and a combined income of $148k. Is that anywhere near enough for a place in the east end? It feels like it isn’t.' }] },
        { from: 'sam', time: '10:09', body: [{ kind: 'text', text: 'It is closer than you think. On $148k, with no car loans and a clean file, most lenders will land you around $610k–$650k depending on the stress-test rate and the property taxes. Do you have any other monthly debt?' }] },
        { from: 'dev', time: '10:11', body: [{ kind: 'text', text: 'A student line of credit, about $180 a month. And we are both salaried, no bonuses.' }] },
        { from: 'sam', time: '10:20', body: [
          { kind: 'text', text: 'Salaried is the easy case — two paystubs and a letter of employment and we are basically done. That $180 knocks roughly $34k off the maximum, so realistically:' },
          { kind: 'list', ordered: false, items: [{ label: 'Purchase price around $615,000' }, { label: 'Minimum down payment on that: $36,500' }, { label: 'Your $70k covers it, plus land transfer tax and closing costs' }] },
          { kind: 'text', text: 'Toronto charges a municipal land transfer tax on top of the provincial one, but as first-time buyers you get a rebate on both — about $8,475 back in total. That is the number most people forget to count.' },
        ] },
        { from: 'dev', time: '10:24', body: [{ kind: 'text', text: 'Wait — we would still be under 20% down. Doesn’t that make everything much worse?' }] },
        { from: 'sam', time: '10:33', body: [{ kind: 'text', text: 'It means CMHC insurance, about $23,200 on that purchase, added to the mortgage rather than paid upfront. It stings on paper. But insured mortgages usually get a lower rate than uninsured ones, so putting exactly 20% down is often worse over five years than putting 10% down. I will run both side by side so you can see it rather than take my word for it.' }] },
        { from: 'dev', time: '10:35', body: [{ kind: 'text', text: 'Okay, that is genuinely not what I expected. What do you need from us?' }] },
        { from: 'sam', time: '10:41', body: [
          { kind: 'text', text: 'Very little to start. Two recent paystubs each, last year’s T4s, and a screenshot of the savings balance. I can have a pre-approval with a 120-day rate hold back to you tomorrow.' },
          { kind: 'buttons', items: [{ label: 'Send the documents', href: '#apply' }, { label: 'Read the full process', href: '#process' }] },
        ] },
      ] }),
      b('process', 'steps', { title: 'What actually happens, start to keys', subtitle: 'Typically five to seven weeks from first message to closing, most of it spent waiting on other people.', items: [
        { title: 'A conversation', text: 'Twenty minutes on the phone or over chat. No credit pull yet, no documents, no commitment. We give you the honest number.' },
        { title: 'Pre-approval', text: 'One credit check, a handful of documents, and a rate hold of 90–120 days. Now you can make an offer without a financing condition scaring the seller off.' },
        { title: 'Shop the lenders', text: 'We take your file to the lenders whose rules actually fit it — not all forty, the six that will say yes at the best rate.' },
        { title: 'Firm approval', text: 'Once you have an accepted offer we submit the property details, order the appraisal if the lender wants one, and get the commitment in writing.' },
        { title: 'Closing', text: 'Instructions go to your real estate lawyer, the funds move on closing day, and we call you a week later to check the first payment came out correctly.' },
      ] }),
      b('reviews', 'reviews', { title: 'What clients say', subtitle: 'Verified reviews from clients who closed with us in the last eighteen months.', average: '4.9', count: '212 reviews', source: 'Google', items: [
        { rating: 5, quote: 'Sam talked me out of the mortgage I wanted and into a cheaper one. Who does that? Saved us about $6,000 over the five-year term and explained exactly why.', author: 'Priya M.', date: 'March 2026', source: 'google' },
        { rating: 5, quote: 'I am self-employed and two banks had already told me no. Northline found a lender who understood how a corporation pays its owner. Closed in four weeks.', author: 'Marc-André L.', date: 'January 2026', source: 'google' },
        { rating: 5, quote: 'Answered a text at 9pm on a Sunday during a bidding war so we could raise our offer with confidence. Never once made us feel stupid for asking something obvious.', author: 'The Osei family', date: 'November 2025', source: 'google' },
        { rating: 4, quote: 'Great advice and a genuinely good rate. The lender they placed us with was slow with paperwork, though Northline chased them constantly on our behalf.', author: 'Hana T.', date: 'September 2025', source: 'google' },
      ] }),
      b('faq', 'faq', { title: 'Questions people are embarrassed to ask', items: [
        { question: 'Do you charge me anything?', answer: 'No. On standard residential deals the lender pays our commission on closing, and it does not change your rate. If your file needs an alternative or private lender we will tell you the fee in writing before any application goes anywhere.' },
        { question: 'Will shopping around wreck my credit score?', answer: 'No. We pull your credit once and use that single report with every lender we approach. Multiple mortgage enquiries inside a short window are also treated as one by the credit bureaus.' },
        { question: 'Fixed or variable?', answer: 'There is no universal answer, only one for your situation. If a 1.5% rate rise would genuinely hurt your monthly budget, take fixed and sleep at night. If you have room and you might move or refinance early, variable usually carries the cheaper break penalty — and that penalty is where most people actually lose money.' },
        { question: 'I am self-employed. Is this going to be painful?', answer: 'More paperwork, not more rejection. We will want two years of T1 Generals and Notices of Assessment, and if you pay yourself in dividends we will find a lender that counts them properly. Roughly a third of our clients are self-employed.' },
        { question: 'My renewal letter arrived. Should I just sign it?', answer: 'Please do not sign it first. Renewal offers from an existing lender are on average 0.2–0.4% above what the same lender will offer a switching client. Send it to us and we will tell you honestly if it is already competitive.' },
      ] }),
      b('apply', 'contact-form', { title: 'Start a conversation', intro: 'No credit check at this stage, and nothing you send here obliges you to anything. We reply within one business day, usually much sooner.', submitLabel: 'Send it over', successMessage: 'Got it — one of our brokers will be in touch within a business day.', fields: [
        { name: 'name', label: 'Your name', type: 'text', placeholder: 'Devon Okonkwo', required: true },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'you@example.com', required: true },
        { name: 'phone', label: 'Phone', type: 'tel', placeholder: '(416) 555-0173' },
        { name: 'stage', label: 'Where are you?', type: 'select', options: ['Just curious about the numbers', 'Looking to get pre-approved', 'Offer accepted, need financing', 'Renewal or refinance', 'Buying an investment property'] },
        { name: 'employment', label: 'How are you paid?', type: 'select', options: ['Salaried', 'Hourly', 'Commission', 'Self-employed / incorporated', 'A mix'] },
        { name: 'question', label: 'What do you want to know?', type: 'textarea', placeholder: 'Ask the basic question. Genuinely.' },
        { name: 'consent', label: 'You may contact me about my enquiry', type: 'checkbox', required: true },
      ] }),
      b('social', 'social-links', { title: 'Or find us elsewhere', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'whatsapp', href: 'https://wa.me/14165550173', label: 'WhatsApp us' },
        { platform: 'instagram', href: 'https://instagram.com/northlinemortgage', label: '@northlinemortgage' },
        { platform: 'linkedin', href: 'https://linkedin.com/company/northline-mortgage', label: 'Northline Mortgage' },
        { platform: 'phone', href: 'tel:+14165550173', label: '(416) 555-0173' },
      ] }),
      b('footer', 'footer', { brand: 'Northline Mortgage', tagline: 'Independent brokerage · FSRA licence 13842 · 250 University Ave, Toronto ON M5H 3E5', links: [{ label: 'How it goes', href: '#thread' }, { label: 'Questions', href: '#faq' }, { label: 'Start a conversation', href: '#apply' }], copyright: '© Northline Mortgage Inc. Rates quoted are illustrative and subject to lender approval.' }),
    ],
  }),
];
