/**
 * `retail` starter templates — independent shops, from a high-street gift boutique
 * to a bookshop, florist, jewellery atelier, bike workshop, interiors studio and
 * a vintage shop that sells through conversation.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const retailTemplates: Template[] = [
  tpl({
    id: 'retail-boutique',
    vertical: 'retail',
    label: 'Shop — Boutique',
    description: 'A high-street gift and homeware boutique leading with photography and a stock edit.',
    tags: ['local', 'gallery', 'gifts', 'homeware', 'one-pager'],
    layout: 'classic',
    preset: 'sand',
    meta: { title: 'Fern & Oak — Homeware & Gifts', description: 'A little shop of well-made homeware, plants, and local gifts.', lang: 'en', favicon: '🪴' },
    blocks: [
      b('nav', 'nav', { brand: 'Fern & Oak', sticky: true, links: [{ label: 'Shop', href: '#shop' }, { label: 'Gallery', href: '#gallery' }, { label: 'Visit', href: '#visit' }], cta: { label: 'Visit the shop', href: '#visit' } }),
      b('hero', 'hero', { eyebrow: 'On the high street', headline: 'Well-made things for a home you love', subhead: 'Ceramics, candles, houseplants, and cards — hand-picked from local makers.', align: 'left', minHeight: 'md', image: img('shop-hero'), overlay: 'light', cta: { label: 'What we stock', href: '#shop' } }),
      b('gallery', 'gallery', { layout: 'masonry', columns: 3, gap: 'md', lightbox: true, items: [{ src: img('shop-1'), alt: 'Shelf of ceramics' }, { src: img('shop-2'), alt: 'Candles' }, { src: img('shop-3'), alt: 'Plants by the window' }, { src: img('shop-4'), alt: 'Greeting cards' }] }),
      b('shop', 'services-catalogue', { title: 'What we stock', subtitle: 'A rotating edit — pop in to see this week’s finds.', items: [
        { name: 'Stoneware mugs', description: 'Hand-thrown, dishwasher-safe.', price: 'from £16' },
        { name: 'Soy candles', description: 'Small-batch, 40-hour burn.', price: '£22' },
        { name: 'Houseplants', description: 'Potted and ready to gift.', price: 'from £9' },
        { name: 'Local art cards', description: 'Blank inside, recycled stock.', price: '£3.50' },
      ] }),
      b('reviews', 'testimonials', { title: 'Loved by locals', items: [
        { quote: 'My go-to for a thoughtful gift. Always something lovely.', author: 'Hannah', role: 'Customer' },
        { quote: 'Beautifully curated and the staff really know their makers.', author: 'Dev', role: 'Regular' },
      ] }),
      b('visit', 'contact-details', { title: 'Come say hello', address: '5 Church Street, York YO1 8BE', phone: '+44 1904 000 000', email: 'hello@fernandoak.shop', hours: 'Tue–Sat 9:30–17:30 · Sun 11:00–16:00' }),
      b('footer', 'footer', { brand: 'Fern & Oak', tagline: 'Well-made homeware & gifts.', links: [{ label: 'Shop', href: '#shop' }, { label: 'Instagram', href: '#' }], copyright: '© Fern & Oak' }),
    ],
  }),

  tpl({
    id: 'retail-bookshop',
    vertical: 'retail',
    label: 'Bookshop — Independent',
    description: 'A neighborhood bookstore that sells through staff picks, a reading journal and an events calendar.',
    tags: ['books', 'long-form', 'newsletter', 'local', 'light'],
    layout: 'editorial',
    preset: 'forest',
    meta: { title: 'Odd Volumes — Portland, OR', description: 'An independent bookshop on SE Belmont: staff picks, readings, and a very opinionated new-fiction table.', lang: 'en', favicon: '📚' },
    blocks: [
      b('nav', 'nav', { brand: 'Odd Volumes', sticky: false, links: [{ label: 'Staff picks', href: '#product' }, { label: 'Journal', href: '#blog' }, { label: 'Events', href: '#feed' }, { label: 'Visit', href: '#contact' }], cta: { label: 'Join the list', href: '#newsletter' } }),
      b('hero', 'hero', { eyebrow: 'SE Belmont · since 2011', headline: 'A bookshop that argues back', subhead: 'Eleven hundred square feet, four booksellers, and a new-fiction table we will happily defend for twenty minutes.', align: 'left', minHeight: 'sm', overlay: 'none', cta: { label: 'This month’s picks', href: '#product' } }),
      b('story', 'rich-text', { blocks: [
        { kind: 'heading', text: 'We read everything we sell' },
        { kind: 'paragraph', text: 'Odd Volumes opened in a former hardware store in 2011 with about four hundred titles, most of them ours. Fifteen years later the shelves hold roughly nine thousand, and the rule has not changed: nothing goes on the front table unless a bookseller here has read it and can tell you exactly who it is for.' },
        { kind: 'paragraph', text: 'That makes us slow at bestsellers and unusually good at the book you did not know existed. If you tell us the last three things you loved, we will find the fourth — in the shop, by phone, or by email if you would rather not talk to anyone, which is a completely reasonable thing to want from a bookshop.' },
        { kind: 'quote', text: 'The point of a small shop is not selection. It is judgment.' },
        { kind: 'subheading', text: 'What we are good at' },
        { kind: 'bullet', text: 'Translated fiction, especially from small presses' },
        { kind: 'bullet', text: 'Poetry that people actually finish' },
        { kind: 'bullet', text: 'Children’s picture books chosen for the adult reading them aloud' },
        { kind: 'bullet', text: 'Special orders — usually two to four days' },
      ] }),
      b('search', 'search', { layout: 'bar', label: 'Search the shelves', placeholder: 'Author, title, or “something like Elena Ferrante”', buttonLabel: 'Look it up', name: 'q', align: 'start' }),
      b('product', 'product', { title: 'On the front table', subtitle: 'Hand-sold this month, with the bookseller’s name on the shelf-talker.', columns: 3, items: [
        { name: 'The Long Field', description: 'Essays on grief and Welsh weather. Ana keeps buying copies for other people.', price: '$18.00', image: img('bookshop-pick-field'), badge: 'Ana’s pick', ctaLabel: 'Reserve a copy', ctaHref: '#' },
        { name: 'Cold Enough for Snow', description: 'A hundred quiet pages about a mother, a daughter, and Tokyo in the rain.', price: '$16.95', image: img('bookshop-pick-snow'), ctaLabel: 'Reserve a copy', ctaHref: '#' },
        { name: 'Wandering Souls', description: 'Debut novel, translated from the French. Our most-recommended book of the spring.', price: '$17.00', was: '$22.00', image: img('bookshop-pick-souls'), badge: 'Paperback out', ctaLabel: 'Reserve a copy', ctaHref: '#' },
        { name: 'Bluets', description: 'Two hundred and forty numbered fragments about the color blue. Sells itself, once opened.', price: '$16.00', image: img('bookshop-pick-bluets'), ctaLabel: 'Reserve a copy', ctaHref: '#' },
        { name: 'The Hare with Amber Eyes', description: 'A family, a war, and two hundred and sixty-four netsuke. Our perennial gift book.', price: '$19.99', image: img('bookshop-pick-hare'), ctaLabel: 'Reserve a copy', ctaHref: '#' },
        { name: 'Small Things Like These', description: 'Ninety pages, one week before Christmas 1985, and no wasted sentences.', price: '$15.00', image: img('bookshop-pick-small'), badge: 'Staff favorite', ctaLabel: 'Reserve a copy', ctaHref: '#' },
      ] }),
      b('blog', 'blog-list', { title: 'From the shop journal', columns: 3, posts: [
        { title: 'Twelve novels under 150 pages', excerpt: 'For the reader who says they have no time, and for the one who simply likes finishing things.', href: '#', image: img('bookshop-journal-short'), date: 'June 2, 2026', tag: 'Lists' },
        { title: 'What our booksellers read on vacation', excerpt: 'Four people, three weeks off, one unexpected agreement about a 900-page Hungarian novel.', href: '#', image: img('bookshop-journal-holiday'), date: 'May 19, 2026', tag: 'Staff' },
        { title: 'How a special order actually works', excerpt: 'Where the book comes from, why it takes three days, and what happens when a title is out of print.', href: '#', image: img('bookshop-journal-orders'), date: 'April 30, 2026', tag: 'Shop' },
      ] }),
      b('feed', 'feed', { title: 'What’s on', layout: 'list', items: [
        { title: 'Reading & conversation: Ilse Nordqvist', subtitle: 'Thursday, June 18, 7pm', text: 'The translator joins us for a bilingual reading of “Winter Quarters”. Free, but the room holds forty.', href: '#', badge: 'Free' },
        { title: 'Second Tuesday Book Club', subtitle: 'Tuesday, June 9, 6:30pm', text: 'This month: “Cold Enough for Snow”. Copies 20% off for members at the register.', href: '#', badge: 'Monthly' },
        { title: 'Kids’ storytime', subtitle: 'Every Saturday, 10:30am', text: 'Thirty minutes of picture books on the rug at the back. Ages 2–6, no booking needed.', href: '#', badge: 'Weekly' },
        { title: 'Poetry open mic', subtitle: 'Last Friday of the month, 8pm', text: 'Five minutes each, sign-up sheet by the register from 7:30. Bring your own or read someone else’s.', href: '#', badge: 'Monthly' },
      ] }),
      b('newsletter', 'newsletter', { title: 'The Monday List', intro: 'One email a week: three books we sold a lot of, one we wish we had, and what’s on this Thursday. Written by a person, on a Monday.', placeholder: 'you@example.com', submitLabel: 'Send me the list', successMessage: 'You’re on the list — the first one lands Monday morning.' }),
      b('hours', 'hours', { title: 'Opening hours', timezone: 'America/Los_Angeles', note: 'Closed Thanksgiving and December 25. Storytime is Saturdays at 10:30.', days: [
        { day: 'mon', open: '11:00', close: '19:00' },
        { day: 'tue', open: '11:00', close: '19:00' },
        { day: 'wed', open: '11:00', close: '19:00' },
        { day: 'thu', open: '11:00', close: '21:00' },
        { day: 'fri', open: '10:00', close: '21:00' },
        { day: 'sat', open: '10:00', close: '21:00' },
        { day: 'sun', open: '11:00', close: '17:00' },
      ] }),
      b('contact', 'contact-details', { title: 'Find us', address: '3418 SE Belmont St, Portland, OR 97214', phone: '(503) 555 0142', email: 'hello@oddvolumes.com', hours: 'Open seven days · late Thu–Sat' }),
      b('footer', 'footer', { brand: 'Odd Volumes', tagline: 'Independent since 2011.', links: [{ label: 'Staff picks', href: '#product' }, { label: 'Events', href: '#feed' }, { label: 'Journal', href: '#blog' }, { label: 'Bookshop.org', href: '#' }], copyright: '© Odd Volumes LLC' }),
    ],
  }),

  tpl({
    id: 'retail-florist',
    vertical: 'retail',
    label: 'Florist — Studio & delivery',
    description: 'A florist selling seasonal bouquets and weekly subscriptions, carried almost entirely by photography.',
    tags: ['gallery', 'florist', 'local', 'reviews', 'b2c'],
    layout: 'showcase',
    preset: 'candy',
    meta: { title: 'Petal & Stem — Flowers, Dublin 8', description: 'Seasonal, Irish-grown bouquets, same-day delivery across Dublin, and a weekly flower subscription.', lang: 'en', favicon: '💐' },
    blocks: [
      b('nav', 'nav', { brand: 'Petal & Stem', sticky: true, links: [{ label: 'Bouquets', href: '#product' }, { label: 'Lookbook', href: '#carousel' }, { label: 'How it works', href: '#steps' }, { label: 'Find us', href: '#map' }], cta: { label: 'Order flowers', href: '#product' } }),
      b('hero', 'hero', { eyebrow: 'Same-day delivery across Dublin', headline: 'Flowers cut this morning, in a vase by six', subhead: 'Seasonal bouquets built from Irish-grown stems — no dyed carnations, no cellophane, and no filler you did not choose.', align: 'center', minHeight: 'lg', image: img('florist-hero-bench'), overlay: 'scrim', cta: { label: 'See this week’s flowers', href: '#product' } }),
      b('carousel', 'carousel', { title: 'This week on the bench', autoplay: false, items: [
        { src: img('florist-look-ranunculus'), alt: 'Ranunculus and hellebore in a shallow bowl', caption: 'Ranunculus, hellebore, and a little smoke bush' },
        { src: img('florist-look-market'), alt: 'Buckets of cut flowers at the studio door', caption: 'Wednesday delivery from a grower in Meath' },
        { src: img('florist-look-wedding'), alt: 'Loose garden-style wedding bouquet', caption: 'A June wedding in Rathmines' },
        { src: img('florist-look-desk'), alt: 'Small posy on a café counter', caption: 'Weekly posy for a café on Francis Street' },
        { src: img('florist-look-wreath'), alt: 'Dried autumn wreath on a blue door', caption: 'Autumn wreath workshop, October' },
      ] }),
      b('product', 'product', { title: 'Order a bouquet', subtitle: 'Order before 1pm for same-day delivery inside the M50. €6 delivery, free over €70.', columns: 3, items: [
        { name: 'The Wednesday', description: 'Our smallest bunch — six or seven stems of whatever came in best that morning.', price: '€28', image: img('florist-buy-wednesday'), ctaLabel: 'Order', ctaHref: '#' },
        { name: 'Studio Choice', description: 'Let us build it. Generous, loose, seasonal. The one we send most.', price: '€55', image: img('florist-buy-studio'), badge: 'Most ordered', ctaLabel: 'Order', ctaHref: '#' },
        { name: 'The Big One', description: 'Twice the stems, wrapped in kraft and ribbon. For apologies and 40th birthdays.', price: '€90', image: img('florist-buy-big'), ctaLabel: 'Order', ctaHref: '#' },
        { name: 'Dried arrangement', description: 'Lasts a year in a dry room. Grasses, strawflower, and honesty.', price: '€42', image: img('florist-buy-dried'), ctaLabel: 'Order', ctaHref: '#' },
        { name: 'Weekly subscription', description: 'A fresh bunch every Thursday. Pause any week, cancel whenever.', price: '€32/week', image: img('florist-buy-sub'), badge: 'Subscription', ctaLabel: 'Start', ctaHref: '#' },
        { name: 'Wedding consultation', description: 'An hour in the studio, a mood board, and a costed proposal within a week.', price: 'from €650', image: img('florist-buy-wedding'), ctaLabel: 'Enquire', ctaHref: '#map' },
      ] }),
      b('steps', 'steps', { title: 'How ordering works', subtitle: 'No account, no app. Four steps and a text message when it lands.', items: [
        { title: 'Pick a size, not a photo', text: 'Flowers change weekly, so you choose a budget and we choose the best stems in the bucket that day.' },
        { title: 'Tell us the tone', text: 'Celebration, apology, sympathy, or “they like orange”. One line is plenty — it genuinely changes what we cut.' },
        { title: 'We build it that morning', text: 'Everything is made the day it goes out, conditioned overnight, and wrapped in water.' },
        { title: 'Hand-delivered by 6pm', text: 'Our own driver, not a courier. You get a photo of the finished bouquet before it leaves.' },
      ] }),
      b('reviews', 'reviews', { title: 'What people say', subtitle: 'Collected from Google over the last two years.', average: '4.9', count: '327 reviews', source: 'Google', items: [
        { rating: 5, quote: 'Ordered at 11am from London for my sister in Portobello and it was on her table by five, with a photo sent to me first. Genuinely lovely flowers, not the usual supermarket-in-a-box thing.', author: 'Ríona M.', date: 'March 2026', source: 'google' },
        { rating: 5, quote: 'We used them for a small wedding in June. They talked us out of the expensive thing we asked for and the room looked better for it.', author: 'Tom & Andreas', date: 'July 2025', source: 'google' },
        { rating: 4, quote: 'Subscription is great value and the flowers last well over a week. Only note is that Thursday delivery can be late in the evening in December.', author: 'Sinéad K.', date: 'January 2026', source: 'google' },
        { rating: 5, quote: 'They made a sympathy arrangement for my father’s funeral at two days’ notice and were incredibly kind about it. I won’t forget that.', author: 'Peter D.', date: 'November 2025', source: 'google' },
      ] }),
      b('map', 'map', { query: '14 Francis Street, The Liberties, Dublin 8, Ireland', zoom: 16, height: 380, label: 'The studio — 14 Francis Street, Dublin 8' }),
      b('order', 'cta', { headline: 'Order before 1pm for flowers today', subhead: 'Same-day inside the M50, next-day nationwide by An Post.', background: 'primary', button: { label: 'Order a bouquet', href: '#product' } }),
      b('footer', 'footer', { brand: 'Petal & Stem', tagline: 'Seasonal flowers, Dublin 8.', links: [{ label: 'Bouquets', href: '#product' }, { label: 'How it works', href: '#steps' }, { label: 'Find us', href: '#map' }, { label: 'Instagram', href: '#' }], copyright: '© Petal & Stem Ltd · 14 Francis Street, Dublin 8' }),
    ],
  }),

  tpl({
    id: 'retail-jewellery',
    vertical: 'retail',
    label: 'Jewellery — Atelier',
    description: 'A bench jeweller selling finished pieces and bespoke commissions, in a dark, high-contrast showroom register.',
    tags: ['luxury', 'dark', 'booking', 'jewellery', 'reviews'],
    layout: 'bold',
    preset: 'midnight',
    meta: { title: 'Aurelia — Fine Jewellery Atelier, Sydney', description: 'Hand-made fine jewellery and bespoke commissions from a working bench in Surry Hills.', lang: 'en', favicon: '💍' },
    blocks: [
      b('notice', 'announcement-bar', { text: 'Commissions for December delivery close on 3 October. Consultation slots are released each Monday.', linkLabel: 'Book a consultation', href: '#booking', tone: 'promo', dismissible: true }),
      b('nav', 'nav', { brand: 'AURELIA', sticky: true, links: [{ label: 'Collection', href: '#product' }, { label: 'Bespoke', href: '#split' }, { label: 'Visit', href: '#contact' }], cta: { label: 'Book a consultation', href: '#booking' } }),
      b('hero', 'hero', { eyebrow: 'Surry Hills · by appointment', headline: 'Made at the bench. Worn for fifty years.', subhead: 'Solid gold, ethically sourced stones, and one pair of hands from wax to polish. Nothing here was cast in a factory.', align: 'center', minHeight: 'full', image: img('jewel-hero-bench'), overlay: 'dark', cta: { label: 'See the collection', href: '#product' } }),
      b('product', 'product', { title: 'The collection', subtitle: 'Ready to wear, in 9ct and 18ct. Every piece can be re-sized once, free, within a year.', columns: 4, items: [
        { name: 'Signet, plain', description: '18ct yellow gold, 12mm face, engraved to order.', price: 'A$1,890', image: img('jewel-piece-signet'), ctaLabel: 'Enquire', ctaHref: '#booking' },
        { name: 'Salt-and-pepper solitaire', description: '1.2ct Australian-cut diamond on a tapered band.', price: 'A$4,450', image: img('jewel-piece-solitaire'), badge: 'One only', ctaLabel: 'Enquire', ctaHref: '#booking' },
        { name: 'Hammered wedding band', description: '3mm, 18ct, finished by hand. Made in pairs.', price: 'A$1,180', image: img('jewel-piece-band'), ctaLabel: 'Enquire', ctaHref: '#booking' },
        { name: 'Opal drop earrings', description: 'Lightning Ridge opal on 9ct gold hooks.', price: 'A$980', image: img('jewel-piece-opal'), ctaLabel: 'Enquire', ctaHref: '#booking' },
        { name: 'Chain, heavy curb', description: '45cm, 18ct, hand-linked and soldered.', price: 'A$3,200', image: img('jewel-piece-chain'), ctaLabel: 'Enquire', ctaHref: '#booking' },
        { name: 'Sapphire cluster', description: 'Six Queensland sapphires, no two the same.', price: 'A$2,640', image: img('jewel-piece-sapphire'), badge: 'New', ctaLabel: 'Enquire', ctaHref: '#booking' },
        { name: 'Seal ring, carved', description: 'Bespoke intaglio, cut in-house over three weeks.', price: 'from A$5,400', image: img('jewel-piece-seal'), ctaLabel: 'Enquire', ctaHref: '#booking' },
        { name: 'Remodelling service', description: 'We melt down inherited gold and build something you will wear.', price: 'from A$1,400', image: img('jewel-piece-remodel'), ctaLabel: 'Enquire', ctaHref: '#booking' },
      ] }),
      b('split', 'split', { rows: [
        { title: 'One bench, no outsourcing', text: 'Everything is made at 3 Bourke Lane — wax carved by hand, cast in a small furnace out the back, then filed, set and polished in the same room. If you commission a ring you will meet the person who makes it, and you will probably see it half-finished.', image: img('jewel-split-hands'), imageAlt: 'A jeweller filing a ring at the bench' },
        { title: 'Where the metal and stones come from', text: 'Gold is 100% recycled, refined in Melbourne, with a certificate for every pour. Coloured stones are bought direct from cutters in Queensland and Sri Lanka whom we have visited. Diamonds are either Australian, lab-grown, or reclaimed from a piece you already own — your choice, and priced honestly either way.', image: img('jewel-split-stones'), imageAlt: 'Loose sapphires on a paper parcel' },
        { title: 'How a commission runs', text: 'Consultation, then a costed drawing within a week. On approval we take 50%, carve the wax, and send you a photograph before casting. Six to eight weeks from deposit to collection — sooner if you tell us the date and we can make it work.', image: img('jewel-split-wax'), imageAlt: 'A carved wax ring model beside carving tools' },
      ] }),
      b('numbers', 'stats', { title: 'Since 2009', columns: 4, items: [
        { value: '2,400', label: 'Pieces made at this bench', suffix: '+' },
        { value: '100', label: 'Recycled gold', suffix: '%' },
        { value: '6', label: 'Weeks, typical commission' },
        { value: '50', label: 'Year guarantee on our settings' },
      ] }),
      b('voices', 'testimonials', { title: 'From the people wearing them', items: [
        { quote: 'I brought in my grandmother’s ring, which nobody had worn since 1998, and left with two bands made from the same gold. Watching it melt was surprisingly emotional.', author: 'Priya', role: 'Remodelling commission' },
        { quote: 'They quoted a third less than the arcade jeweller and then talked me down further, because the stone I wanted was daft for someone who rock-climbs. Six years on it looks new.', author: 'Callum', role: 'Engagement ring, 2020' },
        { quote: 'Our bands were finished four days before the wedding because we were late, not because they were. No fuss made about it at all.', author: 'Jess & Marlo', role: 'Wedding bands' },
      ] }),
      b('booking', 'booking', { title: 'Book a consultation', intro: 'An hour at the bench, no obligation and no charge. Bring photos, old jewellery, or nothing at all. Saturdays book out about a month ahead.', serviceLabel: 'What would you like to talk about?', submitLabel: 'Request a slot', successMessage: 'Thanks — we’ll confirm by email within a working day, usually sooner.', services: [
        { name: 'Engagement ring commission', duration: '60 min', price: 'Free' },
        { name: 'Wedding bands (pair)', duration: '45 min', price: 'Free' },
        { name: 'Remodelling inherited gold', duration: '60 min', price: 'Free' },
        { name: 'Repair or re-sizing', duration: '20 min', price: 'from A$95' },
        { name: 'Try on the collection', duration: '30 min', price: 'Free' },
      ], askDate: true, askTime: true, askParty: false, askPhone: true, askNotes: true, notesLabel: 'Budget, timing, or anything you already have in mind' }),
      b('contact', 'contact-details', { title: 'The atelier', address: '3 Bourke Lane, Surry Hills NSW 2010', phone: '+61 2 8000 4417', email: 'bench@aurelia.jewelry', hours: 'Wed–Fri 10:00–18:00 · Sat 10:00–16:00 · by appointment' }),
      b('terms', 'legal', { align: 'center', separator: '·', documents: [
        { label: 'Care & guarantee', title: 'Care and guarantee', content: 'Everything below applies to any piece made or remodelled at our bench, whoever owns it now.\n\n**What we guarantee.** Every setting we make is guaranteed for fifty years against stone loss caused by our workmanship. Bring the piece in and we will re-set it at no charge.\n\n**What is not covered.** Impact damage, wear on the underside of a band from daily use, and stones knocked out by a fall are not defects. We will always quote to repair them, usually for less than you expect.\n\n**Free for life.** Cleaning, polishing and re-rhodium of white gold are free for life on anything made here, plus one free re-size in the first twelve months.' },
        { label: 'Sourcing policy', title: 'Where our materials come from', content: 'We will name the source of any material in a piece you are considering, in writing, before you pay a deposit.\n\n**Gold.** All gold is 100% recycled and refined in Melbourne. We keep the refiner’s certificate for every pour and will show it to you on request.\n\n**Diamonds.** We offer Australian-mined, laboratory-grown, and reclaimed diamonds. We do not buy stones without a verifiable chain of custody, and we will tell you plainly which category a stone falls into and what that means for its price.\n\n**Coloured stones.** Sapphires come from cutters in central Queensland; spinel and some sapphire from a family workshop in Ratnapura, Sri Lanka, which we visit roughly every two years.' },
      ] }),
      b('footer', 'footer', { brand: 'AURELIA', tagline: 'Fine jewellery, made at the bench in Surry Hills.', links: [{ label: 'Collection', href: '#product' }, { label: 'Bespoke', href: '#split' }, { label: 'Book', href: '#booking' }, { label: 'Instagram', href: '#' }], copyright: '© Aurelia Fine Jewellery Pty Ltd · ABN 00 000 000 000' }),
    ],
  }),

  tpl({
    id: 'retail-bike',
    vertical: 'retail',
    label: 'Bike shop — Sales & workshop',
    description: 'A bike shop where the repair workshop is the main event: service menu, bikes in stock, and a booking form.',
    tags: ['cycling', 'pricing', 'faq', 'local', 'mobile-first'],
    layout: 'catalogue',
    preset: 'ocean',
    meta: { title: 'Cogset Cycles — Sales & Workshop, Bengaluru', description: 'Bicycle sales, servicing and wheel building in Indiranagar. Same-week workshop slots.', lang: 'en', favicon: '🚲' },
    blocks: [
      b('nav', 'nav', { brand: 'Cogset Cycles', sticky: true, links: [{ label: 'Workshop', href: '#services' }, { label: 'Bikes', href: '#product' }, { label: 'Service plans', href: '#plans' }, { label: 'Book', href: '#contact' }], cta: { label: 'Book a service', href: '#contact' } }),
      b('hero', 'hero', { eyebrow: 'Indiranagar · 12th Main', headline: 'The workshop is the shop', subhead: 'Three mechanics with nineteen years between them, a proper truing jig, and a same-week slot for almost everything. We sell bikes too — after you have ridden them.', align: 'left', minHeight: 'sm', image: img('bike-hero-workshop'), overlay: 'scrim', cta: { label: 'See the service menu', href: '#services' } }),
      b('services', 'services-catalogue', { title: 'Workshop menu', subtitle: 'Prices are labour only; parts quoted before we touch anything. Drop off before 10am for same-day on the first three.', items: [
        { name: 'Safety check', description: 'Brakes, gears, bolt torques, tyre pressure. Twenty minutes while you wait.', price: '₹300', ctaLabel: 'Book', ctaHref: '#contact' },
        { name: 'Standard service', description: 'Full drivetrain clean, gear and brake set-up, wheel true, bearings checked.', price: '₹1,400', ctaLabel: 'Book', ctaHref: '#contact' },
        { name: 'Major service', description: 'Everything above plus stripped bearings, fresh cables, and a degreased chain and cassette.', price: '₹3,200', ctaLabel: 'Book', ctaHref: '#contact' },
        { name: 'Puncture / tyre fit', description: 'Tube, tubeless plug, or a full tubeless conversion.', price: 'from ₹150', ctaLabel: 'Book', ctaHref: '#contact' },
        { name: 'Hand-built wheel', description: 'Your hub and rim or ours, laced and tensioned by hand, stress-relieved twice.', price: '₹2,500 per wheel', ctaLabel: 'Book', ctaHref: '#contact' },
        { name: 'Hydraulic brake bleed', description: 'Shimano, SRAM or TRP. Includes fresh fluid and pad alignment.', price: '₹700 per brake', ctaLabel: 'Book', ctaHref: '#contact' },
        { name: 'Suspension lower-leg service', description: 'Seals, oil and a wipe-down. Full damper rebuilds sent out, two weeks.', price: '₹2,800', ctaLabel: 'Book', ctaHref: '#contact' },
        { name: 'Bike fit', description: 'Ninety minutes on the jig with saddle, cleat and bar adjustment. Free with any new bike.', price: '₹4,000', ctaLabel: 'Book', ctaHref: '#contact' },
      ] }),
      b('product', 'product', { title: 'In stock this week', subtitle: 'Test rides from the door, no deposit. Every new bike includes a free first service at six weeks.', columns: 3, items: [
        { name: 'Marin Nail Trail 6', description: 'Hardtail, 29in, 12-speed. The one we sell to people riding Turahalli at the weekend.', price: '₹1,24,000', image: img('bike-stock-hardtail'), ctaLabel: 'Book a test ride', ctaHref: '#contact' },
        { name: 'Polygon Strattos S5', description: 'Alloy road bike, 105 hydraulic. Fast enough for Nandi Hills, calm enough for the commute.', price: '₹98,500', was: '₹1,09,000', image: img('bike-stock-road'), badge: 'Last year’s colour', ctaLabel: 'Book a test ride', ctaHref: '#contact' },
        { name: 'Firefox Rapide Steel', description: 'Steel city bike with rack mounts and full guards. Built for potholes and rain.', price: '₹42,000', image: img('bike-stock-city'), ctaLabel: 'Book a test ride', ctaHref: '#contact' },
        { name: 'Tern Link D8 (folding)', description: 'Folds for the metro in about fifteen seconds, once you have done it twice.', price: '₹58,000', image: img('bike-stock-folding'), ctaLabel: 'Book a test ride', ctaHref: '#contact' },
        { name: 'Refurbished Trek FX 2', description: 'Traded in, fully serviced here, new chain and cassette. Six-month workshop warranty.', price: '₹27,500', image: img('bike-stock-used'), badge: 'Used', ctaLabel: 'Ask about it', ctaHref: '#contact' },
        { name: 'Btwin Rockrider 500 (20in)', description: 'For roughly ages 6–9. We size it with the child standing over it, not from a chart.', price: '₹18,900', image: img('bike-stock-kids'), ctaLabel: 'Book a test ride', ctaHref: '#contact' },
      ] }),
      b('plans', 'pricing', { title: 'Service plans', subtitle: 'Pay once, ride all year. Plans cover labour; parts are 10% off for members.', plans: [
        { name: 'Commuter', price: '₹2,400', period: '/year', features: ['Two standard services', 'Unlimited safety checks', 'Free puncture repairs', '10% off parts'], ctaLabel: 'Join', ctaHref: '#contact' },
        { name: 'Enthusiast', price: '₹5,900', period: '/year', features: ['Two standard, one major service', 'Unlimited safety checks', 'Free punctures and bleeds', 'Free wheel truing', '10% off parts', 'Priority slot within 48 hours'], ctaLabel: 'Join', ctaHref: '#contact', featured: true },
        { name: 'Shop family', price: '₹8,500', period: '/year', features: ['Covers up to four bikes', 'One standard service each', 'Unlimited safety checks', 'Free punctures', '10% off parts'], ctaLabel: 'Join', ctaHref: '#contact' },
      ] }),
      b('advice', 'tabs', { items: [
        { label: 'Before you drop off', text: 'Give the bike a rinse if it has been anywhere muddy — we will still work on it if you do not, but a clean bike gets diagnosed faster and you get the stand time you paid for. Take off panniers, lights, phone mounts and anything you would be upset to lose, and bring the key if you have a locking axle. If something is making a noise, try to describe when it happens: pedalling under load, coasting, braking, or only over bumps. That one sentence saves us half an hour.' },
        { label: 'What we can do same day', text: 'Safety checks, punctures and tyre fitting, gear and brake adjustment, chain and cassette replacement, and most bleeds are same-day if the bike is with us before 10am. Standard services booked in advance are usually back the same evening. Major services need the bike overnight. Hand-built wheels take two to three days, because we let the spokes settle and re-tension the next morning — which is the whole point of paying a person to build them.' },
        { label: 'Parts we stock', text: 'Chains, cassettes, cables, pads, tubes and tyres for everything common — Shimano up to 12-speed, SRAM mechanical and AXS, plus the usual 26in, 27.5in, 29in and 700c sizes. Tubeless sealant, valves and rim tape always on the shelf. Anything exotic we can normally get from our distributor in Bengaluru within two to four working days; from abroad, allow three weeks and we will take a deposit.' },
        { label: 'Bikes we will not touch', text: 'We do not service throttle-controlled e-scooters, petrol conversions, or e-bikes with unbranded battery packs — the fire risk in a shared building is not ours to take. Branded e-bikes with certified batteries are fine, and we service plenty of them. If you are not sure what you have, send us a photo of the battery label on WhatsApp before you ride over.' },
      ] }),
      b('faq', 'faq', { title: 'Before you come in', items: [
        { question: 'Do I need to book, or can I just turn up?', answer: 'Turn up for punctures, safety checks and quick adjustments — there is nearly always a free stand before 11am. Book for anything bigger; we hold a couple of slots each day for emergencies.' },
        { question: 'Will you service a bike I bought somewhere else?', answer: 'Of course. Roughly seven in ten bikes on our stands were bought elsewhere, including online. We do not charge more for it and we will not lecture you about it.' },
        { question: 'Do you take trade-ins?', answer: 'Yes, against any new bike. Bring it in for a five-minute look and we will give you a number the same day. We only take bikes we would be happy to refurbish and resell.' },
        { question: 'Can you help me choose a size?', answer: 'Come in and ride two. Frame charts are a starting point, not an answer — we would rather spend twenty minutes on the road outside than sell you a bike that never feels right.' },
        { question: 'Do you sell parts to home mechanics?', answer: 'Yes, at the same price we charge on a job, and we will happily tell you how to fit them. If you get stuck halfway, bring the bits in a bag.' },
      ] }),
      b('hours', 'hours', { title: 'Workshop hours', timezone: 'Asia/Kolkata', note: 'Drop-offs from 9:30. Closed on public holidays and the second Sunday of each month.', days: [
        { day: 'mon', closed: true },
        { day: 'tue', open: '09:30', close: '19:00' },
        { day: 'wed', open: '09:30', close: '19:00' },
        { day: 'thu', open: '09:30', close: '19:00' },
        { day: 'fri', open: '09:30', close: '19:00' },
        { day: 'sat', open: '08:00', close: '19:00' },
        { day: 'sun', open: '08:00', close: '14:00' },
      ] }),
      b('directions', 'directions', { title: 'Getting here', place: 'Cogset Cycles', address: '418, 12th Main Road, HAL 2nd Stage, Indiranagar, Bengaluru 560038', lat: '12.9719', lng: '77.6412', directionsLabel: 'Open in maps', appleMaps: true }),
      b('contact', 'contact-form', { title: 'Book the workshop', intro: 'Tell us what the bike is doing and when you can drop it in. We reply on WhatsApp or by email, usually within a couple of hours during shop hours.', submitLabel: 'Request a slot', successMessage: 'Got it — we’ll confirm your slot shortly, and quote before we start any work.', fields: [
        { name: 'name', label: 'Your name', type: 'text', placeholder: 'Name', required: true },
        { name: 'phone', label: 'Mobile (WhatsApp)', type: 'tel', placeholder: '+91', required: true },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'you@example.com', required: false },
        { name: 'job', label: 'What do you need?', type: 'select', required: true, options: ['Safety check', 'Standard service', 'Major service', 'Puncture or tyre', 'Wheel build or true', 'Brake bleed', 'Suspension service', 'Bike fit', 'Something is making a noise'] },
        { name: 'bike', label: 'Bike make and model', type: 'text', placeholder: 'e.g. Marin Nail Trail, 2022', required: false },
        { name: 'when', label: 'When could you drop it in?', type: 'text', placeholder: 'e.g. Saturday morning', required: false },
        { name: 'notes', label: 'Describe the problem', type: 'textarea', placeholder: 'When does it happen — pedalling, braking, over bumps?', required: false },
        { name: 'wait', label: 'I can wait in the shop if it’s quick', type: 'checkbox', required: false },
      ] }),
      b('footer', 'footer', { brand: 'Cogset Cycles', tagline: 'Sales and workshop, Indiranagar.', links: [{ label: 'Workshop', href: '#services' }, { label: 'Bikes', href: '#product' }, { label: 'Plans', href: '#plans' }, { label: 'Directions', href: '#directions' }], copyright: '© Cogset Cycles LLP · GSTIN 29AAAAA0000A1Z5' }),
    ],
  }),

  tpl({
    id: 'retail-homeware',
    vertical: 'retail',
    label: 'Homeware — Interiors studio',
    description: 'A quiet, nearly wordless interiors showroom: one statement, one room set, one way to get in touch.',
    tags: ['interiors', 'minimal', 'gallery', 'luxury', 'one-pager'],
    layout: 'minimal',
    preset: 'mono',
    meta: { title: 'Slate & Linen — Interiors, Copenhagen', description: 'A small interiors showroom on Værnedamsvej: furniture, textiles, and a two-hour styling consultation.', lang: 'en', favicon: '🕯️' },
    blocks: [
      b('nav', 'nav', { brand: 'Slate & Linen', sticky: false, links: [{ label: 'Rooms', href: '#gallery' }, { label: 'Studio', href: '#about' }, { label: 'Visit', href: '#contact' }], cta: { label: 'Book a consultation', href: '#contact' } }),
      b('hero', 'hero', { eyebrow: 'Værnedamsvej 12, København V', headline: 'Fewer things, chosen slowly', subhead: 'A showroom of about forty pieces at a time — oak, linen, stoneware, wool. If it is on the floor, we would live with it.', align: 'left', minHeight: 'md', overlay: 'none', cta: { label: 'See the rooms', href: '#gallery' } }),
      b('gallery', 'gallery', { layout: 'grid', columns: 2, gap: 'lg', lightbox: true, items: [
        { src: img('homeware-room-living'), alt: 'Living room with an oak bench and a linen sofa', caption: 'Oak bench, 180cm — 9.400 kr' },
        { src: img('homeware-room-table'), alt: 'Dining table set with stoneware plates', caption: 'Stoneware, thrown on Bornholm — from 220 kr' },
        { src: img('homeware-room-bed'), alt: 'Bed made with washed linen bedding', caption: 'Washed linen bedding, six colours — from 1.850 kr' },
        { src: img('homeware-room-light'), alt: 'Paper pendant lamp over a hallway console', caption: 'Paper pendant, made in Odense — 2.100 kr' },
      ] }),
      b('rule', 'divider', { style: 'line' }),
      b('about', 'about', { eyebrow: 'The studio', title: 'We will happily talk you out of buying something', body: 'Slate & Linen has been on Værnedamsvej since 2016. We keep the showroom deliberately small — about forty pieces — because the alternative is a warehouse, and nobody has ever chosen a sofa well in a warehouse.\n\nMost of what we sell is made within a day’s drive: oak from a joinery outside Aarhus, stoneware from a two-person studio on Bornholm, paper shades in Odense, and linen woven in Lithuania then washed in Denmark. Lead times are honest — six to ten weeks for furniture, told to you before you pay rather than after.\n\nIf you would like help, book two hours of styling. We come to your flat, look at your light, measure the awkward wall, and leave you with a plan. It costs 1.800 kr, which comes off anything you order in the following month, and it is entirely fine to spend it and order nothing.', image: img('homeware-studio-shopfront'), imageAlt: 'The Slate & Linen shopfront on Værnedamsvej', imageSide: 'left' }),
      b('contact', 'contact-details', { title: 'Visit or book', address: 'Værnedamsvej 12, 1619 København V, Denmark', phone: '+45 33 00 41 20', email: 'studio@slateandlinen.dk', hours: 'Wed–Fri 11:00–17:30 · Sat 10:00–16:00 · Mon–Tue by appointment' }),
      b('rights', 'copyright', { holder: 'Slate & Linen ApS', text: 'CVR 38 42 11 07. All rights reserved.', showSymbol: true, align: 'center' }),
    ],
  }),

  tpl({
    id: 'retail-vintage',
    vertical: 'retail',
    label: 'Vintage — Drops & DMs',
    description: 'A thrift and vintage shop that sells through weekly drops and a running conversation with its regulars.',
    tags: ['vintage', 'social', 'budget', 'newsletter', 'gallery'],
    layout: 'conversational',
    preset: 'candy',
    meta: { title: 'Second Spin — Vintage & Thrift, Manchester', description: 'Sorted-by-hand vintage in the Northern Quarter. Weekly drops, sizes 6–26, and someone who actually replies.', lang: 'en', favicon: '🧥' },
    blocks: [
      b('nav', 'nav', { brand: 'Second Spin', sticky: true, links: [{ label: 'Ask us', href: '#chat' }, { label: 'This week’s drop', href: '#gallery' }, { label: 'Selling to us', href: '#accordion' }], cta: { label: 'Get drop alerts', href: '#newsletter' } }),
      b('hero', 'hero', { eyebrow: 'Oldham Street · drops Thursdays at 7pm', headline: 'Message us. We’ll go and look.', subhead: 'Four rails, sizes 6–26, nothing over £45. Tell us what you are after and someone here will actually go through the back for you.', align: 'left', minHeight: 'sm', image: img('vintage-hero-rails'), overlay: 'scrim', cta: { label: 'See how it works', href: '#chat' } }),
      b('chat', 'chat-thread', { title: 'How it usually goes', subtitle: 'A real exchange from our Instagram DMs, posted with permission.', participants: [
        { id: 'jo', name: 'Jo', role: 'user' },
        { id: 'shop', name: 'Second Spin', role: 'agent', avatar: img('vintage-avatar-shop') },
      ], messages: [
        { from: 'jo', time: '18:42', body: [{ kind: 'text', text: 'hiya! looking for a proper 90s leather jacket, size 18ish, under £60. do you ever get them in that size or am I dreaming' }] },
        { from: 'shop', time: '18:51', body: [
          { kind: 'text', text: 'Not dreaming — we get two or three a month in 16–20, they just go fast because we only put them out on the Thursday drop. Two in the back right now:' },
          { kind: 'image', src: img('vintage-chat-jacket-brown'), alt: 'Brown leather bomber jacket on a hanger' },
          { kind: 'image', src: img('vintage-chat-jacket-black'), alt: 'Black leather biker jacket on a hanger' },
        ] },
        { from: 'shop', time: '18:52', body: [{ kind: 'list', ordered: false, items: [
          { label: 'Brown bomber, marked 18, roomy — £48' },
          { label: 'Black biker, marked 16 but cut large — £55' },
          { label: 'Both need a wax, which we do for you free' },
        ] }] },
        { from: 'jo', time: '19:03', body: [{ kind: 'text', text: 'the brown one!! can you hold it til Saturday? and does it smell. be honest' }] },
        { from: 'shop', time: '19:05', body: [
          { kind: 'text', text: 'Held under your name til Saturday close, no deposit needed. And honestly: faint charity-shop smell, gone after a wax and a day on the line. We would not put it out otherwise.' },
          { kind: 'buttons', items: [{ label: 'See the rest of the drop', href: '#gallery' }, { label: 'Get Thursday alerts', href: '#newsletter' }] },
        ] },
        { from: 'jo', time: '19:06', body: [{ kind: 'text', text: 'amazing, see you sat' }] },
      ] }),
      b('gallery', 'gallery', { layout: 'masonry', columns: 3, gap: 'sm', lightbox: true, items: [
        { src: img('vintage-drop-levis'), alt: 'Stack of vintage Levi’s jeans', caption: '501s, 26"–38" — £38' },
        { src: img('vintage-drop-knit'), alt: 'Hand-knitted wool jumpers on a rail', caption: 'Hand-knit jumpers — £24' },
        { src: img('vintage-drop-dresses'), alt: 'Floral tea dresses hanging in a window', caption: '70s tea dresses — £32' },
        { src: img('vintage-drop-sports'), alt: 'Vintage football and college sweatshirts', caption: 'Sports sweats — £28' },
        { src: img('vintage-drop-bags'), alt: 'Leather bags and belts on a shelf', caption: 'Leather bags — from £18' },
        { src: img('vintage-drop-coats'), alt: 'Wool overcoats on a wooden rail', caption: 'Wool overcoats — £45' },
      ] }),
      b('accordion', 'accordion', { title: 'Selling, swapping, and the boring bits', items: [
        { heading: 'Can I sell you my clothes?', body: 'Yes — bring anything up to two bin bags, no appointment, Tuesday to Friday before 5pm. We sort it while you wait if it is quiet, or you can leave it and we will message you a figure within a day.\n\nWe pay 30% of what we would price it at in cash, or 45% as shop credit. Nothing we say no to is a judgement on your taste; it usually just means we already have nine of them.' },
        { heading: 'What do you not take?', body: 'Fast fashion from the last five years, anything with a broken zip we cannot replace, underwear, and shoes worn past the point of repair. School uniform and workwear we pass to a project on Tib Street rather than sell, if you are happy for us to.' },
        { heading: 'How does the Thursday drop work?', body: 'Everything new goes out at 7pm on Thursday, both in the shop and on the Instagram grid — roughly two hundred pieces. We hold items for 48 hours for anyone who asks, in person or by message, and we do not take payment to hold. If you change your mind, just tell us.' },
        { heading: 'Do you post?', body: 'Yes: £4.20 anywhere in the UK, free over £60, sent within two working days. Returns accepted for 14 days on anything posted. You pay the return postage unless we got the measurements wrong, which does happen, and which we always refund.' },
        { heading: 'Are the sizes real?', body: 'Rarely. A 1970s 14 is a modern 10, and a 1990s 18 can be anything at all. Every tag we write has the actual chest, waist and length in inches on it, and we will measure anything you ask about before you travel in.' },
      ] }),
      b('follow', 'social-links', { title: 'Where the drops go up', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'instagram', href: 'https://instagram.com/secondspin.mcr', label: 'secondspin.mcr' },
        { platform: 'tiktok', href: 'https://tiktok.com/@secondspin.mcr', label: 'Fitting-room videos' },
        { platform: 'whatsapp', href: 'https://wa.me/441610000000', label: 'Message the shop' },
        { platform: 'email', href: 'mailto:hello@secondspin.uk', label: 'hello@secondspin.uk' },
      ] }),
      b('newsletter', 'newsletter', { title: 'Thursday, 6pm, one email', intro: 'A dozen photos from that night’s drop an hour before it goes live, plus anything unusual in your size if you tell us what that is. No sales, no discount codes, no “hi babe”.', placeholder: 'you@example.com', submitLabel: 'Send me the drop', successMessage: 'Done — the first one lands Thursday at six.' }),
      b('footer', 'footer', { brand: 'Second Spin', tagline: 'Vintage & thrift, Oldham Street, Manchester.', links: [{ label: 'This week’s drop', href: '#gallery' }, { label: 'Selling to us', href: '#accordion' }, { label: 'Alerts', href: '#newsletter' }], copyright: '© Second Spin · 61 Oldham Street, Manchester M4 1LW · Wed–Sun 11:00–18:00' }),
    ],
  }),
];
