/**
 * `salon` starter templates — hair, barbering, nails, massage, ink, lashes and
 * aesthetics: seven appointment-led businesses that each sell a very different feeling.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const salonTemplates: Template[] = [
  tpl({
    id: 'salon-spa',
    vertical: 'salon',
    label: 'Salon & Spa — Classic',
    description: 'A hair, skin and nails studio that sells an unhurried hour and books it online.',
    tags: ['booking', 'gallery', 'local', 'luxury', 'one-pager'],
    layout: 'classic',
    preset: 'candy',
    meta: { title: 'Lumière — Salon & Spa', description: 'Hair, skin, and nails in a calm, unhurried studio.', lang: 'en', favicon: '💇' },
    blocks: [
      b('nav', 'nav', { brand: 'Lumière', sticky: true, links: [{ label: 'Services', href: '#services' }, { label: 'Gallery', href: '#gallery' }, { label: 'Visit', href: '#visit' }], cta: { label: 'Book now', href: '#book' } }),
      b('hero', 'hero', { eyebrow: 'By appointment', headline: 'An hour that’s all about you', subhead: 'Expert cuts, colour, facials, and nails — in an unhurried, calming studio.', align: 'center', minHeight: 'lg', image: img('salon-hero'), overlay: 'scrim', cta: { label: 'Book an appointment', href: '#book' } }),
      b('services', 'services-catalogue', { title: 'Services', subtitle: 'Every visit starts with a proper consultation.', items: [
        { name: 'Cut & finish', description: 'Consultation, cut, wash, style.', price: 'from £45' },
        { name: 'Colour', description: 'Gloss, balayage, or full colour.', price: 'from £70' },
        { name: 'Signature facial', description: '60 minutes, tailored to your skin.', price: '£65' },
        { name: 'Gel manicure', description: 'Shape, cuticle care, long-wear gel.', price: '£30' },
      ] }),
      b('gallery', 'gallery', { layout: 'grid', columns: 3, gap: 'md', lightbox: true, items: [{ src: img('salon-1'), alt: 'Styling chair' }, { src: img('salon-2'), alt: 'Colour work' }, { src: img('salon-3'), alt: 'Treatment room' }] }),
      b('reviews', 'testimonials', { title: 'From the chair', items: [
        { quote: 'Best colour I’ve had in years — and it grew out beautifully.', author: 'Sofia', role: 'Client' },
        { quote: 'Genuinely relaxing. I book my next one before I leave.', author: 'Amara', role: 'Regular' },
      ] }),
      b('visit', 'contact-details', { title: 'Find the studio', address: '22 Wellington Row, Bath BA1 2QP', phone: '+44 1225 000 000', email: 'hello@lumiere.salon', hours: 'Tue–Sat 9:00–18:00' }),
      b('book', 'cta', { headline: 'Ready for a little time out?', subhead: 'Book online in under a minute, or message us.', background: 'primary', button: { label: 'Book an appointment', href: '#' } }),
      b('footer', 'footer', { brand: 'Lumière', tagline: 'Salon & spa.', links: [{ label: 'Services', href: '#services' }, { label: 'Book', href: '#book' }], copyright: '© Lumière' }),
    ],
  }),

  tpl({
    id: 'salon-barbershop',
    vertical: 'salon',
    label: 'Barbershop — Bold',
    description: 'A walk-in-friendly neighbourhood barbershop that leads with chair count, hours and reviews.',
    tags: ['barber', 'dark', 'reviews', 'local', 'one-pager'],
    layout: 'bold',
    preset: 'midnight',
    meta: { title: 'Nostrand & Co. — Brooklyn Barbershop', description: 'Skin fades, beard work and hot-towel shaves on Nostrand Ave. Walk in or book ahead.', lang: 'en', favicon: '💈' },
    blocks: [
      b('notice', 'announcement-bar', { text: 'Six chairs open Saturdays — walk-ins taken until 5pm.', linkLabel: 'See hours', href: '#hours', tone: 'promo', dismissible: true }),
      b('nav', 'nav', { brand: 'Nostrand & Co.', sticky: true, links: [{ label: 'Cuts', href: '#cuts' }, { label: 'Hours', href: '#hours' }, { label: 'Reviews', href: '#reviews' }, { label: 'Find us', href: '#find' }], cta: { label: 'Grab a chair', href: '#chair' } }),
      b('hero', 'hero', { eyebrow: 'Est. 2011 · Bed-Stuy', headline: 'Sharp cut. Twenty minutes. No fuss.', subhead: 'Six barbers, six chairs, and a clipper line you can set your watch by.', align: 'left', minHeight: 'full', image: img('barber-shopfront-night'), overlay: 'dark', cta: { label: 'Grab a chair', href: '#chair' } }),
      b('numbers', 'stats', { title: 'The shop, in numbers', columns: 4, items: [
        { value: '6', label: 'Barbers on the floor' },
        { value: '14', label: 'Years on Nostrand' },
        { value: '22', label: 'Average cut', suffix: ' min' },
        { value: '4.9', label: 'Google rating', suffix: '★' },
      ] }),
      b('cuts', 'services-catalogue', { title: 'What it costs', subtitle: 'Cash and card. Tips go straight to your barber.', items: [
        { name: 'Skin fade', description: 'Taper or bald fade, lined up sharp.', price: '$40' },
        { name: 'Cut & beard', description: 'Full cut plus beard shape and oil.', price: '$55' },
        { name: 'Hot-towel shave', description: 'Straight razor, two towels, balm.', price: '$45' },
        { name: 'Kids under 12', description: 'Same cut, shorter wait, cartoons on.', price: '$25' },
        { name: 'Line-up only', description: 'Edge-up between cuts, in and out.', price: '$20' },
      ] }),
      b('hours', 'hours', { title: 'When we’re open', timezone: 'America/New_York', note: 'Last walk-in taken 30 minutes before close.', days: [
        { day: 'mon', closed: true },
        { day: 'tue', open: '10:00', close: '19:00' },
        { day: 'wed', open: '10:00', close: '19:00' },
        { day: 'thu', open: '10:00', close: '20:00' },
        { day: 'fri', open: '09:00', close: '20:00' },
        { day: 'sat', open: '08:00', close: '18:00' },
        { day: 'sun', open: '11:00', close: '16:00' },
      ] }),
      b('reviews', 'reviews', { title: 'What the block says', subtitle: 'Pulled from Google and Yelp.', average: '4.9', count: '812', source: 'Google', items: [
        { rating: 5, quote: 'Walked in at 8:15 on a Saturday, out by 8:40, cleanest fade I’ve had in Brooklyn.', author: 'Dev R.', date: 'March 2026', source: 'google' },
        { rating: 5, quote: 'They cut my kid’s hair for the first time and nobody cried, including me.', author: 'Priya M.', date: 'February 2026', source: 'google' },
        { rating: 4, quote: 'Busy on Fridays, but they text you when your chair is close. Worth the wait.', author: 'Tomás L.', date: 'January 2026', source: 'yelp' },
      ] }),
      b('find', 'directions', { title: 'Come by', place: 'Nostrand & Co. Barbershop', address: '241 Nostrand Ave, Brooklyn, NY 11205', lat: '40.6902', lng: '-73.9506', directionsLabel: 'Open in maps', appleMaps: true }),
      b('chair', 'cta', { headline: 'Skip the wait — put your name down', subhead: 'Join the list from your phone and we’ll text you when your chair is up.', background: 'accent', button: { label: 'Join the list', href: '#' } }),
      b('footer', 'footer', { brand: 'Nostrand & Co.', tagline: 'Barbering since 2011.', links: [{ label: 'Cuts', href: '#cuts' }, { label: 'Hours', href: '#hours' }, { label: 'Find us', href: '#find' }], copyright: '© Nostrand & Co. Barbershop' }),
    ],
  }),

  tpl({
    id: 'salon-nail-bar',
    vertical: 'salon',
    label: 'Nail Bar — Showcase',
    description: 'A nail studio where the work sells itself: a carousel, a masonry grid and a small retail shelf.',
    tags: ['nails', 'gallery', 'showcase', 'booking', 'b2c'],
    layout: 'showcase',
    preset: 'sand',
    meta: { title: 'Gertrude Nail Bar — Fitzroy', description: 'Hand-painted nail art, structured gel and pedicures in Fitzroy, Melbourne.', lang: 'en', favicon: '💅' },
    blocks: [
      b('nav', 'nav', { brand: 'Gertrude Nail Bar', sticky: true, links: [{ label: 'Work', href: '#work' }, { label: 'Sets', href: '#sets' }, { label: 'Prices', href: '#menu' }, { label: 'Shop', href: '#shop' }], cta: { label: 'Book a seat', href: '#book' } }),
      b('hero', 'hero', { eyebrow: 'Fitzroy, Melbourne', headline: 'Nails worth photographing', subhead: 'Hand-painted art, structured gel that actually lasts, and a chair by the window.', align: 'center', minHeight: 'lg', image: img('nailbar-window-seat'), overlay: 'light', cta: { label: 'See the work', href: '#work' } }),
      b('work', 'carousel', { title: 'This season’s sets', autoplay: true, items: [
        { src: img('nailbar-chrome-french'), alt: 'Chrome french tips on short almond nails', caption: 'Chrome french · 90 min' },
        { src: img('nailbar-ochre-marble'), alt: 'Ochre and cream marbled nails', caption: 'Ochre marble · hand-painted' },
        { src: img('nailbar-micro-florals'), alt: 'Tiny painted florals on a milky base', caption: 'Micro florals · our most-booked' },
        { src: img('nailbar-jelly-red'), alt: 'Sheer jelly red gel on long square nails', caption: 'Jelly red · summer 2026' },
      ] }),
      b('sets', 'gallery', { layout: 'masonry', columns: 3, gap: 'lg', lightbox: true, items: [
        { src: img('nailbar-grid-1'), alt: 'Matte olive set with gold foil detail', caption: 'Olive & foil' },
        { src: img('nailbar-grid-2'), alt: 'Short natural nails with a clear builder gel overlay', caption: 'Builder gel overlay' },
        { src: img('nailbar-grid-3'), alt: 'Pearl aura nails under lamp light', caption: 'Pearl aura' },
        { src: img('nailbar-grid-4'), alt: 'Toes finished with a deep plum pedicure', caption: 'Deluxe pedicure' },
        { src: img('nailbar-grid-5'), alt: 'Hand-painted checkerboard tips', caption: 'Checkerboard tips' },
        { src: img('nailbar-grid-6'), alt: 'Bridal set in sheer pink with tiny crystals', caption: 'Bridal, 2026' },
      ] }),
      b('menu', 'services-catalogue', { title: 'Price list', subtitle: 'Soak-off included when you rebook within six weeks.', items: [
        { name: 'Structured gel manicure', description: 'Shape, cuticle work, builder gel, colour.', price: 'A$85', ctaLabel: 'Book', ctaHref: '#book' },
        { name: 'Nail art, per nail', description: 'Hand-painted, from simple lines to full scenes.', price: 'from A$6', ctaLabel: 'Book', ctaHref: '#book' },
        { name: 'Deluxe pedicure', description: 'Soak, scrub, ten-minute massage, gel colour.', price: 'A$95', ctaLabel: 'Book', ctaHref: '#book' },
        { name: 'Soak-off & treat', description: 'Gentle removal plus a keratin nail treatment.', price: 'A$40', ctaLabel: 'Book', ctaHref: '#book' },
      ] }),
      b('shop', 'product', { title: 'Take it home', subtitle: 'The three things that keep a set alive between visits.', columns: 3, items: [
        { name: 'Cuticle oil, 15ml', description: 'Jojoba and vitamin E. Twice a day, no excuses.', price: 'A$24', image: img('nailbar-shop-oil'), ctaLabel: 'Add', ctaHref: '#' },
        { name: 'Glass file', description: 'Lasts years, never shreds a free edge.', price: 'A$18', was: 'A$22', badge: 'Restocked', image: img('nailbar-shop-file'), ctaLabel: 'Add', ctaHref: '#' },
        { name: 'Hand balm, 50ml', description: 'Unscented, absorbs before you touch your keys.', price: 'A$29', image: img('nailbar-shop-balm'), ctaLabel: 'Add', ctaHref: '#' },
      ] }),
      b('words', 'testimonials', { title: 'Regulars', items: [
        { quote: 'Three weeks in and not one lift. I have never got that anywhere else.', author: 'Bec', role: 'Every six weeks' },
        { quote: 'I brought in a photo of a painting and they freehanded it onto ten nails.', author: 'Ngoc', role: 'Client' },
        { quote: 'Quiet, unrushed, and they never make you feel silly for asking questions.', author: 'Harriet', role: 'First visit' },
      ] }),
      b('map', 'map', { query: '188 Gertrude Street, Fitzroy VIC 3065, Australia', zoom: 16, height: 320, label: 'Studio 3, upstairs — buzzer marked Nail Bar' }),
      b('book', 'cta', { headline: 'Chairs open two weeks out', subhead: 'Pick your artist, your set and your slot. A deposit holds the seat.', background: 'surface', button: { label: 'Book a seat', href: '#' } }),
      b('footer', 'footer', { brand: 'Gertrude Nail Bar', tagline: '3/188 Gertrude Street, Fitzroy VIC 3065 · +61 3 9000 0000', links: [{ label: 'Price list', href: '#menu' }, { label: 'Shop', href: '#shop' }, { label: 'Book', href: '#book' }], copyright: '© Gertrude Nail Bar' }),
    ],
  }),

  tpl({
    id: 'salon-day-spa',
    vertical: 'salon',
    label: 'Day Spa — Editorial',
    description: 'A long-form, type-led page for a massage and treatment house that sells slowness.',
    tags: ['massage', 'long-form', 'wellness', 'newsletter', 'luxury'],
    layout: 'editorial',
    preset: 'forest',
    meta: { title: 'Casa Vagar — Day Spa, Lisboa', description: 'Massage, hydrotherapy and quiet in a restored townhouse in Lisbon.', lang: 'en', favicon: '🌿' },
    blocks: [
      b('nav', 'nav', { brand: 'Casa Vagar', sticky: false, links: [{ label: 'The house', href: '#house' }, { label: 'Treatments', href: '#treatments' }, { label: 'Journal', href: '#journal' }, { label: 'Visit', href: '#visit' }], cta: { label: 'Reserve a day', href: '#book' } }),
      b('opening', 'rich-text', { blocks: [
        { kind: 'heading', text: 'Nothing here happens quickly' },
        { kind: 'paragraph', text: 'Casa Vagar occupies three floors of an 1870s townhouse on Rua das Flores. The lift is slow, the corridors are narrow, and the whole building smells faintly of eucalyptus and old plaster. None of that is an accident.' },
        { kind: 'paragraph', text: 'We take four guests at a time. There is no music in the treatment rooms, no upsell at the end, and no clock where you can see it. You arrive an hour before your treatment, you sit in the courtyard, and you leave when you are ready.' },
        { kind: 'quote', text: 'A massage is ninety minutes. A visit is half a day. We priced the second one.' },
        { kind: 'subheading', text: 'How a visit is shaped' },
        { kind: 'numbered', text: 'Arrive, change, and spend an unhurried hour in the water rooms.' },
        { kind: 'numbered', text: 'Meet your therapist, who will ask more questions than you expect.' },
        { kind: 'numbered', text: 'Your treatment, then tea in the courtyard for as long as you like.' },
      ] }),
      b('house', 'about', { eyebrow: 'Since 2016', title: 'The house', body: 'Ana and Rui bought the building as a shell and spent two years putting it back together with the original azulejo intact. The ground floor holds the water rooms — a cold plunge, a steam room lined in Estremoz marble, and a shallow warm pool that seats six. The two floors above are treatment rooms, one per floor per guest, each with a window onto the street or the courtyard.', image: img('dayspa-townhouse-courtyard'), imageAlt: 'Sunlit tiled courtyard with a single stone bench', imageSide: 'left' }),
      b('treatments', 'split', { rows: [
        { title: 'Deep tissue, 90 minutes — €120', text: 'Slow, firm and specific. Your therapist works one or two areas properly rather than covering the whole body lightly. Most people book this for a shoulder or a lower back that has been complaining for months.', image: img('dayspa-deep-tissue-room'), imageAlt: 'Treatment table beside a tall shuttered window' },
        { title: 'Hydrotherapy circuit, 2 hours — €65', text: 'Steam, plunge, warm pool, repeat, with a rest between each. Bring nothing; robes, slippers and towels are set out for you. Best booked on a weekday morning when the house is at its quietest.', image: img('dayspa-steam-marble'), imageAlt: 'Marble-lined steam room with a low bench' },
        { title: 'The full day — €240', text: 'The circuit, a 90-minute treatment, lunch in the courtyard, and the afternoon to yourself. Four of these are available each day and they go about six weeks ahead.', image: img('dayspa-courtyard-lunch'), imageAlt: 'Small lunch table laid under a fig tree' },
      ] }),
      b('story', 'timeline', { title: 'Ten years, slowly', items: [
        { date: '2016', title: 'A shell on Rua das Flores', text: 'Ana and Rui buy a building with no roof and very good bones.' },
        { date: '2018', title: 'The water rooms open', text: 'Hydrotherapy only, three days a week, entirely by word of mouth.' },
        { date: '2021', title: 'Four treatment rooms', text: 'The upper floors are finished and the first therapists join.' },
        { date: '2024', title: 'The full day', text: 'Lunch service starts in the courtyard and the day package is born.' },
        { date: '2026', title: 'Still four guests at a time', text: 'We have had ten years of chances to grow and have politely declined.' },
      ] }),
      b('journal', 'blog-list', { title: 'From the journal', columns: 3, posts: [
        { title: 'Why we took the music out', excerpt: 'Ninety minutes of whale song is a decision made for you. Silence is not.', href: '#', image: img('dayspa-journal-silence'), date: '18 May 2026', tag: 'The house' },
        { title: 'Cold plunge, honestly', excerpt: 'What the research actually supports, and what it very much does not.', href: '#', image: img('dayspa-journal-plunge'), date: '2 April 2026', tag: 'Water' },
        { title: 'A short defence of the nap', excerpt: 'The courtyard bench exists for exactly one purpose and you should use it.', href: '#', image: img('dayspa-journal-nap'), date: '11 February 2026', tag: 'Slowness' },
      ] }),
      b('questions', 'accordion', { title: 'Before you come', items: [
        { heading: 'What should I bring?', body: 'Yourself. Robes, slippers, towels and toiletries are laid out. Leave jewellery at home — there is a locker, but the fewer things to think about, the better.' },
        { heading: 'Can I book for two people?', body: 'Yes, and you can share the water rooms, but treatments are one guest per room. Couples’ rooms would mean a bigger building and a louder one.' },
        { heading: 'Is there parking?', body: 'No, and there is no realistic prospect of any. The 28 tram stops two streets up and there is a car park on Rua do Alecrim, six minutes on foot.' },
        { heading: 'What if I need to cancel?', body: 'Forty-eight hours and we refund in full. Inside that we will move you if we can fill the slot, which on a weekday we usually can.' },
      ] }),
      b('book', 'cta', { headline: 'Four visits a day, and they go about six weeks ahead', subhead: 'Tell us the date you want. We hold it for 24 hours while you decide what to book into it.', background: 'surface', button: { label: 'Reserve a day', href: '#' } }),
      b('letter', 'newsletter', { title: 'The quiet letter', intro: 'One email a month: what is open, what has changed, and the occasional cancellation slot before it goes public.', placeholder: 'you@example.com', submitLabel: 'Send it to me', successMessage: 'Done. The next one goes out on the first of the month.' }),
      b('visit', 'contact-details', { title: 'Visiting', address: 'Rua das Flores 41, 1200-194 Lisboa, Portugal', phone: '+351 21 000 0000', email: 'bomdia@casavagar.pt', hours: 'Wed–Sun 10:00–20:00 · closed Mon & Tue' }),
      b('footer', 'footer', { brand: 'Casa Vagar', tagline: 'Day spa, Lisboa. Four guests at a time.', links: [{ label: 'Treatments', href: '#treatments' }, { label: 'Journal', href: '#journal' }, { label: 'Visit', href: '#visit' }], copyright: '© Casa Vagar, Lda.' }),
    ],
  }),

  tpl({
    id: 'salon-tattoo-studio',
    vertical: 'salon',
    label: 'Tattoo Studio — Artist Profile',
    description: 'One tattoo artist’s page: a portfolio reel, the styles they take on, a résumé and an enquiry form.',
    tags: ['tattoo', 'portfolio', 'profile', 'video', 'dark'],
    layout: 'profile',
    preset: 'mono',
    meta: { title: 'Wren Kessler — Tattoo, Berlin', description: 'Fine-line and blackwork tattooing at a private studio in Kreuzberg, Berlin.', lang: 'en', favicon: '🖤' },
    blocks: [
      b('nav', 'nav', { brand: 'Wren Kessler', sticky: true, links: [{ label: 'Work', href: '#reel' }, { label: 'Styles', href: '#styles' }, { label: 'Background', href: '#background' }, { label: 'Enquire', href: '#enquire' }] }),
      b('who', 'profile-header', {
        name: 'Wren Kessler',
        headline: 'Fine-line & blackwork tattoo artist · private studio, Kreuzberg',
        location: 'Berlin, Germany',
        avatar: img('tattoo-wren-portrait'),
        summary: 'Twelve years in, mostly large-scale blackwork and botanical fine line. I take four clients a week, draw everything by hand, and only tattoo designs made for the person in the chair. Books open on the first Monday of each quarter.',
        contacts: [
          { type: 'email', value: 'studio@wrenkessler.ink', label: 'Email' },
          { type: 'location', value: 'Oranienstraße 58, 10969 Berlin', label: 'Studio' },
          { type: 'website', value: 'wrenkessler.ink', label: 'Portfolio' },
        ],
        showDownload: true,
        downloadLabel: 'Download portfolio PDF',
        showShare: true,
        shareLabel: 'Share this page',
      }),
      b('styles', 'skills', { title: 'What I actually do', display: 'bars', groups: [
        { name: 'Tattooing', items: [
          { label: 'Blackwork & ornamental', level: 5 },
          { label: 'Botanical fine line', level: 5 },
          { label: 'Lettering & script', level: 4 },
          { label: 'Scar & stretch-mark cover', level: 3 },
        ] },
        { name: 'Placement I take on', items: [
          { label: 'Full and half sleeves', level: 5 },
          { label: 'Spine and back pieces', level: 4 },
          { label: 'Hands, neck and face', level: 2 },
        ] },
        { name: 'Languages', items: [
          { label: 'German', level: 5 },
          { label: 'English', level: 5 },
          { label: 'Polish', level: 3 },
        ] },
      ] }),
      b('reel', 'video-gallery', { title: 'Recent work, in motion', layout: 'grid', columns: 3, items: [
        { provider: 'vimeo', src: '918420031', title: 'Botanical half sleeve — three sittings', poster: img('tattoo-reel-botanical') },
        { provider: 'vimeo', src: '918420052', title: 'Ornamental spine piece — timelapse', poster: img('tattoo-reel-spine') },
        { provider: 'vimeo', src: '918420078', title: 'Blackout cover-up, before and after', poster: img('tattoo-reel-coverup') },
      ] }),
      b('background', 'experience', { title: 'Background', items: [
        { role: 'Resident artist & owner', org: 'Studio Kessler', period: '2019 — now', location: 'Kreuzberg, Berlin', summary: 'A two-chair private studio, appointment only.', bullets: ['Four clients a week, one project each, drawn from scratch', 'Mentored three apprentices through to resident', 'Ran the 2024 Kreuzberg scar-cover clinic — 40 pieces at cost'] },
        { role: 'Artist', org: 'Eisen & Tinte', period: '2015 — 2019', location: 'Leipzig', summary: 'Walk-in shop, high volume, every style going.', bullets: ['Roughly 1,800 pieces, which is where the line work got fast', 'Wrote the shop’s aftercare protocol, still in use today'] },
        { role: 'Apprentice', org: 'Nadel Neun', period: '2013 — 2015', location: 'Leipzig', bullets: ['Two years of setup, sterilisation and drawing before touching skin'] },
      ] }),
      b('faq', 'faq', { title: 'The practical bits', items: [
        { question: 'How do I get on the books?', answer: 'Send the enquiry form below with a rough idea, a placement and a size in centimetres. Books open the first Monday of January, April, July and October, and I answer everything within that week.' },
        { question: 'What does it cost?', answer: '€140 an hour, or a flat day rate of €900 for anything over six hours. A €150 deposit holds the date and comes off the final sitting.' },
        { question: 'Do you tattoo other artists’ designs?', answer: 'No. I draw for the person in the chair and I will not copy another artist’s piece. Bring references, moods and photographs — not a screenshot to reproduce.' },
        { question: 'I have a scar or stretch marks — can they be tattooed?', answer: 'Usually, once the tissue is at least a year old and fully settled. Send a photo in daylight and I will tell you honestly whether it will hold ink.' },
        { question: 'Under 18?', answer: 'No, and not with a parent’s consent either. German law and my own preference agree here.' },
      ] }),
      b('enquire', 'contact-form', { title: 'Project enquiry', intro: 'The more specific you are, the faster I can say yes or point you to someone better suited.', submitLabel: 'Send enquiry', successMessage: 'Got it. I answer enquiries in a block on Fridays — you will hear from me within a week.', fields: [
        { name: 'name', label: 'Your name', type: 'text', required: true, placeholder: 'How should I address you?' },
        { name: 'email', label: 'Email', type: 'email', required: true, placeholder: 'you@example.com' },
        { name: 'placement', label: 'Placement', type: 'select', required: true, options: ['Forearm', 'Upper arm or sleeve', 'Back or spine', 'Thigh or calf', 'Ribs or sternum', 'Somewhere else'] },
        { name: 'size', label: 'Rough size in cm', type: 'text', placeholder: 'e.g. 20cm tall' },
        { name: 'idea', label: 'The idea', type: 'textarea', required: true, placeholder: 'What it is, what it is for, and anything you definitely do not want.' },
        { name: 'firsttime', label: 'This would be my first tattoo', type: 'checkbox' },
      ] }),
      b('elsewhere', 'social-links', { title: 'Elsewhere', layout: 'row', variant: 'icon', align: 'center', links: [
        { platform: 'instagram', href: '#', label: 'Instagram' },
        { platform: 'email', href: '#', label: 'Email the studio' },
        { platform: 'whatsapp', href: '#', label: 'WhatsApp' },
      ] }),
      b('rights', 'copyright', { holder: 'Wren Kessler', text: 'All designs remain the artist’s work. Please do not reproduce them.', showSymbol: true, align: 'center' }),
    ],
  }),

  tpl({
    id: 'salon-lash-brow-bar',
    vertical: 'salon',
    label: 'Lash & Brow Bar — App',
    description: 'An install-to-home-screen booking page for a lash and brow bar, built around a tab bar.',
    tags: ['lashes', 'brows', 'booking', 'mobile-first', 'b2c'],
    layout: 'app',
    preset: 'candy',
    meta: { title: 'Kohl Lash & Brow Bar — Bengaluru', description: 'Lash extensions, lifts and brow lamination on Lavelle Road. Book from your phone.', lang: 'en', favicon: '👁️' },
    blocks: [
      b('shell', 'app-shell', { brand: 'Kohl', tabs: [
        { label: 'Home', href: '#top', icon: '🏠' },
        { label: 'Menu', href: '#services', icon: '📋' },
        { label: 'Looks', href: '#looks', icon: '✨' },
        { label: 'Book', href: '#book', icon: '📅' },
        { label: 'Help', href: '#help', icon: '💬' },
      ] }),
      b('top', 'hero-app', {
        headline: 'Your lashes, booked in four taps',
        subhead: 'Kohl Lash & Brow Bar, Lavelle Road. Add us to your home screen and rebook in seconds.',
        installLabel: 'Book a chair',
        installHref: '#book',
        screenshots: [
          { src: img('kohl-app-shot-slots'), alt: 'Slot picker showing this week’s available lash appointments' },
          { src: img('kohl-app-shot-fills'), alt: 'Fill reminder screen counting down to the next appointment' },
          { src: img('kohl-app-shot-looks'), alt: 'Saved looks screen with three previous lash sets' },
        ],
      }),
      b('why', 'features', { title: 'Why regulars keep the tab open', columns: 3, items: [
        { icon: '⏱️', title: 'Fills in 45 minutes', text: 'Book a fill on the way over; we hold the chair for ten minutes.' },
        { icon: '🔔', title: 'Fill reminders', text: 'A nudge at week two, while a refill still costs half a full set.' },
        { icon: '💾', title: 'Your look, saved', text: 'Curl, length and map stored — no re-explaining it every visit.' },
      ] }),
      b('services', 'services-catalogue', { title: 'The menu', subtitle: 'Prices include GST. Patch test is free, 24 hours ahead.', items: [
        { name: 'Classic lash set', description: 'One extension per natural lash. The softest, most natural finish.', price: '₹3,200', ctaLabel: 'Book', ctaHref: '#book' },
        { name: 'Hybrid set', description: 'Classic and volume mixed for texture and a fuller line.', price: '₹4,000', ctaLabel: 'Book', ctaHref: '#book' },
        { name: 'Volume set', description: 'Handmade fans, 3D–6D. The full, dark, editorial look.', price: '₹4,800', ctaLabel: 'Book', ctaHref: '#book' },
        { name: 'Fill, within 3 weeks', description: 'Top-up on any set originally done with us.', price: '₹1,800', ctaLabel: 'Book', ctaHref: '#book' },
        { name: 'Lash lift & tint', description: 'No extensions — your own lashes curled and darkened, 6–8 weeks.', price: '₹2,600', ctaLabel: 'Book', ctaHref: '#book' },
        { name: 'Brow lamination & shape', description: 'Laminate, tint, thread and trim.', price: '₹2,400', ctaLabel: 'Book', ctaHref: '#book' },
      ] }),
      b('looks', 'gallery', { layout: 'grid', columns: 2, gap: 'sm', lightbox: true, items: [
        { src: img('kohl-look-classic'), alt: 'Classic lash set, close up on an open eye', caption: 'Classic · C curl · 10mm' },
        { src: img('kohl-look-hybrid'), alt: 'Hybrid lash set with a textured, wispy line', caption: 'Hybrid · wispy map' },
        { src: img('kohl-look-volume'), alt: 'Volume lash set with dense handmade fans', caption: 'Volume · 4D' },
        { src: img('kohl-look-brows'), alt: 'Laminated and tinted brows brushed upward', caption: 'Brow lamination + tint' },
      ] }),
      b('aftercare', 'steps', { title: 'The first 48 hours', subtitle: 'Do these three things and a set lasts a full cycle.', items: [
        { title: 'Keep them dry for 24 hours', text: 'No steam, no swimming, no hot yoga. The adhesive is still curing.' },
        { title: 'Brush every morning', text: 'Ten seconds with the spoolie in your kit, from the middle outward.' },
        { title: 'Sleep on your back if you can', text: 'A silk pillowcase does most of the work if you cannot.' },
      ] }),
      b('book', 'booking', {
        title: 'Book a chair',
        intro: 'Pick a service and a slot. We confirm on WhatsApp within the hour, 10am–8pm.',
        submitLabel: 'Request this slot',
        successMessage: 'Sent. Watch for a WhatsApp from +91 80 4000 0000 to confirm.',
        serviceLabel: 'What are you booking?',
        services: [
          { name: 'Classic lash set', duration: '2 hr', price: '₹3,200' },
          { name: 'Hybrid set', duration: '2 hr 15 min', price: '₹4,000' },
          { name: 'Volume set', duration: '2 hr 30 min', price: '₹4,800' },
          { name: 'Fill', duration: '45 min', price: '₹1,800' },
          { name: 'Lash lift & tint', duration: '1 hr', price: '₹2,600' },
          { name: 'Brow lamination & shape', duration: '1 hr', price: '₹2,400' },
        ],
        askDate: true,
        askTime: true,
        askParty: false,
        askPhone: true,
        askNotes: true,
        notesLabel: 'Allergies, sensitivities, or a look you want to show us?',
      }),
      b('help', 'faq', { title: 'Quick answers', items: [
        { question: 'How long does a set last?', answer: 'Six to eight weeks, but you will want a fill at two to three weeks, because your natural lashes shed on their own cycle.' },
        { question: 'Do I need a patch test?', answer: 'For your first set with us, yes — a free five-minute visit at least 24 hours ahead. Regulars are re-tested once a year.' },
        { question: 'Can I wear mascara?', answer: 'On extensions, no. On a lash lift, yes, and it looks excellent.' },
        { question: 'What if I am late?', answer: 'We hold the chair ten minutes. After that we fit in what we can in the time left, at full price.' },
      ] }),
      b('install', 'install-prompt', { title: 'Add Kohl to your home screen', body: 'Rebook in four taps and get your fill reminder as a notification instead of an email you miss.', actionLabel: 'Show me how', position: 'bottom', tone: 'promo', delayMs: 6000, dismissible: true, rememberDismiss: true, platforms: ['ios-safari', 'android', 'desktop-chrome'] }),
      b('footer', 'footer', { brand: 'Kohl Lash & Brow Bar', tagline: '2nd floor, 14 Lavelle Road, Bengaluru 560001 · Tue–Sun 10:00–20:00', links: [{ label: 'Menu', href: '#services' }, { label: 'Book', href: '#book' }, { label: 'Help', href: '#help' }], copyright: '© Kohl Lash & Brow Bar' }),
    ],
  }),

  tpl({
    id: 'salon-med-spa',
    vertical: 'salon',
    label: 'Med-Spa — Treatment Catalogue',
    description: 'A nurse-led aesthetics clinic leading with its full treatment list, course pricing and consent detail.',
    tags: ['aesthetics', 'pricing', 'catalogue', 'faq', 'b2c'],
    layout: 'catalogue',
    preset: 'ocean',
    meta: { title: 'Marylebone Aesthetics — Nurse-led med-spa', description: 'Injectables, skin resurfacing and laser, prescribed and delivered by registered nurses in London W1.', lang: 'en', favicon: '💠' },
    blocks: [
      b('nav', 'nav', { brand: 'Marylebone Aesthetics', sticky: true, links: [{ label: 'Treatments', href: '#treatments' }, { label: 'Courses', href: '#courses' }, { label: 'Your visit', href: '#visit' }, { label: 'Team', href: '#team' }], cta: { label: 'Book a consultation', href: '#book' } }),
      b('hero', 'hero', { eyebrow: 'CQC registered · nurse-led', headline: 'Every treatment starts with a consultation, and some of them end there', subhead: 'If a treatment will not do what you are hoping for, we tell you before you pay for it.', align: 'left', minHeight: 'md', image: img('medspa-consult-room'), overlay: 'light', cta: { label: 'Book a consultation — £50, redeemable', href: '#book' } }),
      b('treatments', 'services-catalogue', { title: 'Treatment list', subtitle: 'Prices are per session and include your two-week review.', items: [
        { name: 'Anti-wrinkle injections, 1 area', description: 'Prescription-only medicine, prescribed on the day after assessment.', price: '£185' },
        { name: 'Anti-wrinkle injections, 3 areas', description: 'Forehead, glabella and crow’s feet.', price: '£345' },
        { name: 'Dermal filler, 1ml', description: 'Cheeks, chin, jaw or lips. Hyaluronic acid, reversible.', price: '£320' },
        { name: 'Polynucleotide skin booster', description: 'Course of three, two weeks apart. Under-eye or full face.', price: '£240' },
        { name: 'Medical microneedling', description: 'SkinPen with a growth-factor mask. Scarring and texture.', price: '£195' },
        { name: 'Laser hair removal, small area', description: 'Alexandrite and Nd:YAG — safe on all skin types.', price: '£95' },
        { name: 'Chemical peel, medium depth', description: 'Pigmentation and sun damage. Four days of visible peeling.', price: '£160' },
        { name: 'Prescription skincare review', description: 'Tretinoin, azelaic acid and hydroquinone where indicated.', price: '£75' },
      ] }),
      b('courses', 'pricing', { title: 'Courses & membership', subtitle: 'Courses are paid up front and refundable pro rata if the plan changes.', plans: [
        { name: 'Skin course', price: '£520', period: '/ 3 sessions', features: ['Three medical microneedling sessions', 'Six weeks apart', 'Home prescription included', 'A two-week review after each'], ctaLabel: 'Enquire', ctaHref: '#book' },
        { name: 'Membership', price: '£95', period: '/ month', features: ['One treatment credit a month, rolls over 3 months', '15% off everything else', 'Priority cancellation list', 'Annual skin-health review'], ctaLabel: 'Join', ctaHref: '#book', featured: true },
        { name: 'Laser course', price: '£480', period: '/ 6 sessions', features: ['Six sessions, one small area', 'Patch test and settings recorded', 'Top-up session at 12 months', 'Interest-free over 6 months'], ctaLabel: 'Enquire', ctaHref: '#book' },
      ] }),
      b('visit', 'tabs', { items: [
        { label: 'Before', text: 'Your consultation is 45 minutes and costs £50, which comes off your first treatment. We take a full medical history, photograph the area in standardised lighting, and talk through what the treatment can and cannot change. Nothing is injected on a first visit unless you have had the same treatment with us before — you go away with a written plan and a quote, and you decide in your own time.' },
        { label: 'On the day', text: 'Come with a clean face and no make-up on the treatment area. Avoid alcohol for 24 hours, and stop fish oil, high-dose vitamin E and ibuprofen for three days if your own doctor is happy for you to do so. Injectable appointments run 30 to 45 minutes including numbing time. You will be asked to sign a consent form that we go through line by line.' },
        { label: 'Afterwards', text: 'Expect small raised bumps for an hour and possible bruising for up to a week. No exercise, saunas or facials for 48 hours, and sleep propped up on the first night. Filler settles over two weeks. We see you at the two-week mark to review and adjust — that appointment is included, and about one in five people needs it.' },
        { label: 'Safety', text: 'Every prescriber here is an NMC-registered nurse independent prescriber with an indemnified aesthetics scope. We hold hyaluronidase on site for filler reversal, keep an anaphylaxis kit and a trained responder in the building throughout clinic hours, and record batch numbers for every product used on you.' },
      ] }),
      b('team', 'team', { title: 'Who will treat you', subtitle: 'Three prescribers, one clinic manager, no sales staff.', columns: 3, members: [
        { name: 'Iman Farooq', role: 'Clinical Lead · RN, Independent Prescriber', photo: img('medspa-team-iman'), bio: '16 years in NHS dermatology before aesthetics. Runs the complications clinic other London practices refer into.' },
        { name: 'Danny Okonkwo', role: 'Aesthetic Nurse · RN, Independent Prescriber', photo: img('medspa-team-danny'), bio: 'Laser and pigmentation lead. Particular interest in safe settings for Fitzpatrick IV–VI skin.' },
        { name: 'Marta Reis', role: 'Aesthetic Nurse · RN', photo: img('medspa-team-marta'), bio: 'Skin health, peels and polynucleotides. Speaks Portuguese and Spanish.' },
      ] }),
      b('ask', 'chat-thread', {
        title: 'How a consultation actually goes',
        subtitle: 'A real enquiry, lightly edited and shared with permission.',
        participants: [
          { id: 'client', name: 'Rachel', role: 'user' },
          { id: 'nurse', name: 'Iman Farooq', role: 'agent', avatar: img('medspa-chat-iman') },
        ],
        messages: [
          { from: 'client', time: '09:12', body: [{ kind: 'text', text: 'Hi — I have quite deep lines between my brows and I have been told filler would sort it. Can I book that?' }] },
          { from: 'nurse', time: '09:31', body: [{ kind: 'text', text: 'Possibly, but filler between the brows is one of the higher-risk placements and it is rarely the right first answer. Can I ask one thing: are the lines there when your face is relaxed, or only when you frown?' }] },
          { from: 'client', time: '09:34', body: [{ kind: 'text', text: 'Mostly when I frown. There is a faint one at rest.' }] },
          { from: 'nurse', time: '09:40', body: [
            { kind: 'text', text: 'Then I would start with anti-wrinkle injections rather than filler. The usual path for that pattern:' },
            { kind: 'list', ordered: true, items: [{ label: 'One area treated, £185, reviewed at two weeks' }, { label: 'Repeat at 3–4 months so the muscle softens' }, { label: 'Only then consider anything for the residual static line' }] },
            { kind: 'text', text: 'That is cheaper and safer than where you were heading. Shall I book you a consultation so I can see it in person?' },
          ] },
          { from: 'client', time: '09:41', body: [{ kind: 'text', text: 'Yes please. Honestly did not expect to be talked out of the expensive one.' }] },
          { from: 'nurse', time: '09:45', body: [
            { kind: 'text', text: 'It happens most weeks. Here are the next few slots:' },
            { kind: 'buttons', items: [{ label: 'Thu 09:30', href: '#' }, { label: 'Thu 16:00', href: '#' }, { label: 'Sat 11:15', href: '#' }] },
          ] },
        ],
      }),
      b('book', 'contact-form', { title: 'Book a consultation', intro: 'Forty-five minutes, £50, redeemable against your first treatment. A prescriber reads every enquiry — nobody here works on commission.', submitLabel: 'Request a consultation', successMessage: 'Thank you. A prescriber will reply within one working day with two or three times.', fields: [
        { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'What we should call you' },
        { name: 'email', label: 'Email', type: 'email', required: true, placeholder: 'you@example.com' },
        { name: 'phone', label: 'Mobile', type: 'tel', required: true, placeholder: 'For the appointment reminder' },
        { name: 'interest', label: 'What are you thinking about?', type: 'select', required: true, options: ['Anti-wrinkle injections', 'Dermal filler', 'Skin boosters or microneedling', 'Laser hair removal', 'Peels or prescription skincare', 'Not sure — I would like advice'] },
        { name: 'history', label: 'Anything medical we should know now?', type: 'textarea', placeholder: 'Medication, pregnancy, allergies, previous treatments.' },
        { name: 'firstvisit', label: 'This would be my first aesthetic treatment', type: 'checkbox' },
      ] }),
      b('faq', 'faq', { title: 'Questions we get asked most', items: [
        { question: 'Will I look done?', answer: 'Not if we are doing our job. We work conservatively and review at two weeks, because adding a little more is easy and taking it away is not.' },
        { question: 'Who prescribes the medicine?', answer: 'The nurse treating you. All three are NMC-registered independent prescribers, so nobody here injects a prescription-only medicine that a remote prescriber signed off without seeing you.' },
        { question: 'Can I have treatment while pregnant or breastfeeding?', answer: 'No injectables, no peels and no laser. Skincare and facials, yes — tell us at booking and we will adjust the plan.' },
        { question: 'Do you treat under-25s?', answer: 'For skin health and laser, yes. For injectables we start at 25, and we decline anyone under 18 outright, as the law requires.' },
        { question: 'What happens if something goes wrong?', answer: 'You call the clinic mobile, which is answered by a prescriber out of hours. Review, reversal and management of any complication from a treatment we performed is free, and always will be.' },
      ] }),
      b('policies', 'legal', { title: 'The paperwork', align: 'center', separator: '·', documents: [
        { label: 'Consent', title: 'Consent to treatment', content: 'Before any treatment you will be asked to read and sign a consent form specific to that procedure.\n\nIt sets out the intended effect, the expected recovery, the common side effects (bruising, swelling, tenderness) and the rare but serious ones, including vascular occlusion for dermal filler. We go through it with you out loud, and you are welcome to take it home and come back another day.\n\nYou may withdraw consent at any point, including after treatment has begun.' },
        { label: 'Cancellations', title: 'Cancellation policy', content: 'Consultations and treatments can be moved or cancelled free of charge with **48 hours** notice.\n\nInside 48 hours we retain the £50 consultation fee or 50% of a treatment deposit, because the slot rarely refills at short notice. We waive this without argument for illness, bereavement, and anything that is obviously life happening.\n\nCourses are refundable pro rata at any point if the clinical plan changes.' },
        { label: 'Privacy', title: 'Privacy & clinical records', content: 'We hold a clinical record for every patient, including medical history, consent forms, batch numbers and standardised photographs.\n\nRecords are kept for **eight years** as required for healthcare records, stored encrypted in the UK, and never used for marketing. Photographs are never published without separate, specific, written consent that you can withdraw at any time.\n\nYou can request a copy of your record by emailing the clinic; we respond within 30 days.' },
        { label: 'Complaints', title: 'Complaints', content: 'Tell the clinic manager first — most things are fixed the same week.\n\nIf you would rather not, or you are unhappy with the outcome, write to the registered manager at the clinic address. We acknowledge within 3 working days and respond fully within 20.\n\nYou can also escalate to the Care Quality Commission or, for a concern about an individual nurse, to the Nursing and Midwifery Council.' },
      ] }),
      b('where', 'contact-details', { title: 'The clinic', address: '9 Marylebone Lane, London W1U 2NF', phone: '+44 20 7000 0000', email: 'clinic@maryleboneaesthetics.co.uk', hours: 'Mon–Wed 9:00–18:00 · Thu 9:00–20:00 · Sat 10:00–16:00' }),
      b('footer', 'footer', { brand: 'Marylebone Aesthetics', tagline: 'Nurse-led aesthetics, London W1. CQC registered.', links: [{ label: 'Treatments', href: '#treatments' }, { label: 'Courses', href: '#courses' }, { label: 'Policies', href: '#policies' }], copyright: '© Marylebone Aesthetics Ltd' }),
    ],
  }),
];
