/**
 * `service` starter templates — home and business services sold by the visit:
 * trades, cleaning, grounds, laundry, IT support, locksmithing and clearance.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const serviceTemplates: Template[] = [
  tpl({
    id: 'service-local',
    vertical: 'service',
    label: 'Local Trade — Classic',
    description: 'A local plumbing and heating firm selling on turning up, fixed prices and no call-out fee.',
    tags: ['plumbing', 'local', 'emergency', 'faq', 'one-pager'],
    layout: 'classic',
    preset: 'forest',
    meta: { title: 'Reliant Plumbing & Heating', description: 'Local, reliable plumbers — no call-out fee, upfront prices.', lang: 'en', favicon: '🔧' },
    blocks: [
      b('nav', 'nav', { brand: 'Reliant', sticky: true, links: [{ label: 'Services', href: '#services' }, { label: 'How it works', href: '#how' }, { label: 'Contact', href: '#contact' }], cta: { label: 'Get a quote', href: '#contact' } }),
      b('hero', 'hero', { eyebrow: 'Gas Safe registered', headline: 'A plumber who turns up when they say', subhead: 'Repairs, boilers, and bathrooms — upfront prices and no call-out fee.', align: 'left', minHeight: 'md', image: img('plumb-hero'), overlay: 'scrim', cta: { label: 'Get a free quote', href: '#contact' } }),
      b('services', 'features', { title: 'What we do', columns: 3, items: [
        { icon: '🚿', title: 'Repairs', text: 'Leaks, taps, toilets, and drains.' },
        { icon: '🔥', title: 'Boilers & heating', text: 'Servicing, repairs, and new installs.' },
        { icon: '🛁', title: 'Bathrooms', text: 'Full fits, project managed.' },
      ] }),
      b('how', 'steps', { title: 'How it works', items: [
        { title: 'Tell us the job', text: 'Call or send a photo — we’ll advise.' },
        { title: 'Fixed quote', text: 'Upfront price before we start.' },
        { title: 'Sorted', text: 'Tidy work, guaranteed for 12 months.' },
      ] }),
      b('chat', 'chat-thread', {
        title: 'Booking a job, start to finish',
        subtitle: 'A real enquiry from last week, lightly trimmed.',
        participants: [
          { id: 'c', name: 'Dan Whitfield', role: 'user' },
          { id: 'r', name: 'Reliant', role: 'agent' },
        ],
        messages: [
          { from: 'c', time: '08:02', body: [{ kind: 'text', text: 'Boiler is making a banging noise and the radiators are cold upstairs. Can someone come today?' }] },
          { from: 'r', time: '08:09', body: [
            { kind: 'text', text: 'Sounds like trapped air or a failing pump. We keep two morning slots free for emergencies — both still open:' },
            { kind: 'list', ordered: false, items: [{ label: '11:00 – 12:00' }, { label: '14:30 – 15:30' }] },
            { kind: 'buttons', items: [{ label: 'Book 11:00', href: '#contact' }, { label: 'Book 14:30', href: '#contact' }] },
          ] },
          { from: 'c', time: '08:11', body: [{ kind: 'text', text: 'Morning one please. What will it cost?' }] },
          { from: 'r', time: '08:12', body: [
            { kind: 'text', text: '£85 for the visit and first hour, parts quoted before we fit anything. No call-out fee on top.' },
            { kind: 'buttons', items: [{ label: 'Confirmed — see you at 11' }] },
          ] },
        ],
      }),
      b('reviews', 'testimonials', { title: 'What neighbours say', items: [
        { quote: 'Fixed our boiler same day and left the kitchen spotless.', author: 'Karen', role: 'Sheffield' },
        { quote: 'Honest, on time, fair price. Booked them for the bathroom next.', author: 'Paul', role: 'Rotherham' },
      ] }),
      b('faq', 'faq', { title: 'Good to know', items: [
        { question: 'Do you charge a call-out fee?', answer: 'No — you only pay for the work, quoted upfront.' },
        { question: 'Are you insured?', answer: 'Fully insured and Gas Safe registered.' },
      ] }),
      b('cta', 'cta', { headline: 'Got a job that needs doing?', subhead: 'Send a message and we’ll come back with a fixed price.', background: 'primary', button: { label: 'Get a quote', href: '#contact' } }),
      b('contact', 'contact-details', { title: 'Get in touch', address: 'Covering Sheffield & Rotherham', phone: '+44 114 000 0000', email: 'jobs@reliantplumbing.co.uk', hours: 'Mon–Sat 7:00–19:00 · 24/7 emergencies' }),
      b('footer', 'footer', { brand: 'Reliant Plumbing & Heating', tagline: 'Local & reliable.', links: [{ label: 'Services', href: '#services' }, { label: 'Contact', href: '#contact' }], copyright: '© Reliant Plumbing & Heating' }),
    ],
  }),

  tpl({
    id: 'service-cleaning',
    vertical: 'service',
    label: 'Domestic Cleaning — Catalogue',
    description: 'A residential cleaning company where the price list and the booking form do all the selling.',
    tags: ['cleaning', 'pricing', 'booking', 'reviews', 'b2c'],
    layout: 'catalogue',
    preset: 'candy',
    meta: { title: 'Brightwell Home Cleaning — Melbourne', description: 'Police-checked home cleaners across inner-north Melbourne. Flat prices, same cleaner every time.', lang: 'en', favicon: '🧼' },
    blocks: [
      b('promo', 'announcement-bar', { text: 'Now covering Brunswick, Coburg and Northcote — 20% off your first clean.', linkLabel: 'Book a clean', href: '#book', tone: 'promo', dismissible: true }),
      b('nav', 'nav', { brand: 'Brightwell', sticky: true, links: [{ label: 'Cleans', href: '#cleans' }, { label: 'Prices', href: '#prices' }, { label: 'Reviews', href: '#reviews' }, { label: 'FAQ', href: '#faq' }], cta: { label: 'Book a clean', href: '#book' } }),
      b('hero', 'hero', { eyebrow: 'Melbourne · Police-checked cleaners', headline: 'The same cleaner, the same day, every fortnight', subhead: 'No agency roulette. You meet your cleaner once and they stay with your home.', align: 'left', minHeight: 'sm', image: img('brightwell-kitchen-light'), overlay: 'light', cta: { label: 'See prices', href: '#prices' } }),
      b('cleans', 'services-catalogue', { title: 'What we clean', subtitle: 'Every visit includes products, cloths and a checklist you can edit.', items: [
        { name: 'Regular home clean', description: 'Kitchen, bathrooms, floors, dusting and bins. Weekly or fortnightly.', price: 'from A$38/hr', ctaLabel: 'Book regular', ctaHref: '#book' },
        { name: 'Spring clean', description: 'Inside cupboards, skirting, window tracks, oven front, behind furniture.', price: 'from A$310', ctaLabel: 'Book a spring clean', ctaHref: '#book' },
        { name: 'End of lease', description: 'Bond-back checklist, oven and range hood degreased, marks off walls.', price: 'from A$465', ctaLabel: 'Get a bond quote', ctaHref: '#book' },
        { name: 'Oven deep clean', description: 'Dip-tank treatment for racks and trays, glass split and polished.', price: 'A$145', ctaLabel: 'Add to a booking', ctaHref: '#book' },
        { name: 'Inside fridge & pantry', description: 'Emptied, wiped, restocked in order. Good before or after a long trip.', price: 'A$60', ctaLabel: 'Add to a booking', ctaHref: '#book' },
      ] }),
      b('prices', 'pricing', { title: 'Plans', subtitle: 'Skip or cancel any visit with 24 hours notice — no fee, no explanation.', plans: [
        { name: 'Fortnightly', price: 'A$152', period: 'per visit', features: ['4 hours, 2 cleaners', 'Same team every visit', 'Products included', 'Skip any visit free'], ctaLabel: 'Book fortnightly', ctaHref: '#book' },
        { name: 'Weekly', price: 'A$118', period: 'per visit', features: ['3 hours, 2 cleaners', 'Same team every visit', 'Products included', 'Priority reschedules'], ctaLabel: 'Book weekly', ctaHref: '#book', featured: true },
        { name: 'One-off', price: 'A$44', period: 'per hour', features: ['Minimum 3 hours', 'Weekend slots available', 'Products included'], ctaLabel: 'Book a one-off', ctaHref: '#book' },
      ] }),
      b('included', 'features', { title: 'What you get either way', columns: 4, items: [
        { icon: '🪪', title: 'Police checked', text: 'Every cleaner, checked again each year.' },
        { icon: '🛡️', title: 'A$20m insured', text: 'Public liability and accidental damage cover.' },
        { icon: '🌱', title: 'Low-tox products', text: 'Fragrance-free by default, pet and kid safe.' },
        { icon: '🔁', title: 'Re-clean promise', text: 'Tell us within 48 hours and we come back free.' },
      ] }),
      b('reviews', 'reviews', { title: 'What clients say', subtitle: 'Collected after the third visit, not the first.', average: '4.9', count: '312 reviews', source: 'Google & Facebook', items: [
        { rating: 5, quote: 'Priya and Marcus have cleaned our place for two years. They know where everything lives, which is honestly the whole point.', author: 'Hannah T.', date: 'March 2026', source: 'google' },
        { rating: 5, quote: 'Bond back in full after the end-of-lease clean. The agent actually commented on the oven.', author: 'Deb K.', date: 'January 2026', source: 'google' },
        { rating: 4, quote: 'Great clean, and they text the night before. Only knocked a star because the first booking ran late.', author: 'Sam O.', date: 'November 2025', source: 'facebook' },
      ] }),
      b('faq', 'faq', { title: 'Before you book', items: [
        { question: 'Do I need to be home?', answer: 'No. Most clients leave a key or a lockbox code, and we log every entry and exit.' },
        { question: 'What if I have pets?', answer: 'Tell us in the notes. All our products are pet safe and we shut doors behind us.' },
        { question: 'Can I change my cleaner?', answer: 'Yes, no explanation needed. Message us and we reassign for the next visit.' },
        { question: 'How do I pay?', answer: 'Card on file, charged the evening after each clean. Invoices available for tax purposes.' },
      ] }),
      b('book', 'booking', {
        title: 'Book a clean',
        intro: 'Pick a service and a time. We confirm by text within two hours on business days.',
        serviceLabel: 'Which clean?',
        services: [
          { name: 'Regular home clean', duration: '3–4 hrs', price: 'from A$118' },
          { name: 'Spring clean', duration: '6 hrs', price: 'from A$310' },
          { name: 'End of lease', duration: '7–8 hrs', price: 'from A$465' },
          { name: 'Oven deep clean', duration: '2 hrs', price: 'A$145' },
        ],
        askDate: true,
        askTime: true,
        askPhone: true,
        askNotes: true,
        notesLabel: 'Parking, pets, keys — anything we should know',
        submitLabel: 'Request this time',
        successMessage: 'Booked in provisionally. We’ll text to confirm your cleaner.',
      }),
      b('contact', 'contact-details', { title: 'Brightwell Home Cleaning', address: '14 Wilson Ave, Brunswick VIC 3056, Australia', phone: '+61 3 5550 1274', email: 'hello@brightwellclean.com.au', hours: 'Office Mon–Fri 8:00–17:00 · Cleans Mon–Sat' }),
      b('footer', 'footer', { brand: 'Brightwell Home Cleaning', tagline: 'Inner-north Melbourne, fortnightly.', links: [{ label: 'Prices', href: '#prices' }, { label: 'Book', href: '#book' }, { label: 'FAQ', href: '#faq' }], copyright: '© Brightwell Home Cleaning Pty Ltd' }),
    ],
  }),

  tpl({
    id: 'service-garden',
    vertical: 'service',
    label: 'Garden & Landscaping — Showcase',
    description: 'A design-and-build landscaping studio that persuades with finished-garden photography and a build film.',
    tags: ['landscaping', 'gallery', 'video', 'portfolio', 'local'],
    layout: 'showcase',
    preset: 'forest',
    meta: { title: 'Fernhill Gardens & Landscapes', description: 'Garden design and build in Portland, Oregon — native planting, stonework and decks.', lang: 'en', favicon: '🌿' },
    blocks: [
      b('nav', 'nav', { brand: 'Fernhill', sticky: true, links: [{ label: 'Work', href: '#work' }, { label: 'Process', href: '#process' }, { label: 'Film', href: '#film' }, { label: 'Contact', href: '#contact' }], cta: { label: 'Start a project', href: '#contact' } }),
      b('hero', 'hero', { eyebrow: 'Portland, Oregon · Since 2011', headline: 'Gardens that look like they were always there', subhead: 'Design, build and planting for city lots, slopes and awkward side yards.', align: 'center', minHeight: 'full', image: img('fernhill-terrace-hero'), overlay: 'scrim', cta: { label: 'See recent work', href: '#work' } }),
      b('work', 'gallery', { layout: 'grid', columns: 3, gap: 'md', lightbox: true, items: [
        { src: img('fernhill-basalt-steps'), alt: 'Basalt steps cut into a sloped back yard', caption: 'Mount Tabor — basalt terrace, 2025' },
        { src: img('fernhill-fern-shade-bed'), alt: 'Shade bed of sword ferns under a maple', caption: 'Irvington — shade planting' },
        { src: img('fernhill-cedar-deck'), alt: 'Low cedar deck with built-in bench seating', caption: 'Sellwood — cedar deck and bench' },
        { src: img('fernhill-gravel-courtyard'), alt: 'Gravel courtyard with raised steel planters', caption: 'Kenton — gravel courtyard' },
        { src: img('fernhill-rain-garden'), alt: 'Rain garden planted with rushes and sedges', caption: 'Alberta — rain garden' },
        { src: img('fernhill-kitchen-garden'), alt: 'Raised vegetable beds in cedar frames', caption: 'Woodstock — kitchen garden' },
      ] }),
      b('process', 'split', { rows: [
        { title: 'We start with the survey, not the mood board', text: 'Two hours on site with a level and a soil auger. Drainage, shade, roots and access decide most of the design before anyone draws anything.', image: img('fernhill-site-survey'), imageAlt: 'A landscaper measuring levels across a sloped yard' },
        { title: 'One drawing, priced line by line', text: 'You get a plan, a planting schedule and a build quote broken into stages you can take this year or next. Nothing is a mystery number.', image: img('fernhill-plan-drawing'), imageAlt: 'A hand-drawn garden plan spread out on a workbench' },
        { title: 'Our own crew, not a phone number', text: 'The four people who build your garden are on our payroll, and the same lead is on site from the first dig to the last plant.', image: img('fernhill-crew-planting'), imageAlt: 'Two landscapers setting plants into a prepared bed' },
      ] }),
      b('film', 'video', { provider: 'youtube', src: 'fN7hK2sBv9Q', title: 'A sloped Mount Tabor yard, start to finish', poster: img('fernhill-film-poster'), caption: 'Eleven weeks of basalt, cedar and 340 native plants, in six minutes.' }),
      b('planting', 'carousel', { title: 'Through the seasons', autoplay: true, items: [
        { src: img('fernhill-season-spring'), alt: 'Trillium and bleeding heart in early spring', caption: 'April — trillium and bleeding heart' },
        { src: img('fernhill-season-summer'), alt: 'Grasses and echinacea at midsummer', caption: 'July — grasses hold the beds together' },
        { src: img('fernhill-season-autumn'), alt: 'Vine maple turning red in autumn', caption: 'October — vine maple earns its keep' },
        { src: img('fernhill-season-winter'), alt: 'Frosted seed heads and evergreen structure', caption: 'January — seed heads left standing for the birds' },
      ] }),
      b('voices', 'testimonials', { title: 'From the owners', items: [
        { quote: 'We had a slope nobody would touch. They spent a whole morning working out where the water went, and three years on it has never washed out once.', author: 'Marisol Vega', role: 'Mount Tabor' },
        { quote: 'They talked us out of the water feature and into better soil. Best money we never spent.', author: 'Theo Brandt', role: 'Sellwood' },
      ] }),
      b('cta', 'cta', { headline: 'Thinking about next spring?', subhead: 'Design slots for the spring build season fill by November.', background: 'primary', button: { label: 'Start a project', href: '#contact' } }),
      b('contact', 'contact-details', { title: 'Fernhill Gardens & Landscapes', address: '2210 SE Ankeny St, Portland, OR 97214', phone: '(503) 555-0148', email: 'studio@fernhillgardens.com', hours: 'Studio Mon–Thu 9:00–16:00 · Site visits Fridays' }),
      b('footer', 'footer', { brand: 'Fernhill Gardens & Landscapes', tagline: 'Design, build, planting.', links: [{ label: 'Work', href: '#work' }, { label: 'Film', href: '#film' }, { label: 'Contact', href: '#contact' }], copyright: '© Fernhill Gardens LLC · OR LCB #9921' }),
    ],
  }),

  tpl({
    id: 'service-laundry',
    vertical: 'service',
    label: 'Laundry & Dry Cleaning — App',
    description: 'A pickup-and-delivery laundry service presented as an installable app with live order tracking.',
    tags: ['laundry', 'mobile-first', 'pricing', 'delivery', 'b2c'],
    layout: 'app',
    preset: 'sand',
    meta: { title: 'WashLoop — Laundry, picked up tonight', description: 'Doorstep laundry and dry cleaning across Bengaluru. Picked up by 9pm, back in 24 hours.', lang: 'en', favicon: '🧺' },
    blocks: [
      b('shell', 'app-shell', { brand: 'WashLoop', tabs: [
        { label: 'Home', href: '#home', icon: '🏠' },
        { label: 'Rates', href: '#rates', icon: '💰' },
        { label: 'Track', href: '#track', icon: '📍' },
        { label: 'Help', href: '#help', icon: '💬' },
      ] }),
      b('home', 'hero-app', {
        headline: 'Leave the bag outside by 9pm',
        subhead: 'A rider collects, we wash and press, and it is back on your doorstep within 24 hours. Bengaluru only, for now.',
        installLabel: 'Install WashLoop',
        installHref: '#install',
        screenshots: [
          { src: img('washloop-screen-order'), alt: 'Order screen showing a scheduled 9pm pickup' },
          { src: img('washloop-screen-track'), alt: 'Live tracking screen with the rider on a map' },
          { src: img('washloop-screen-receipt'), alt: 'Itemised receipt for a wash-and-fold order' },
        ],
      }),
      b('how', 'steps', { title: 'Three taps, one bag', subtitle: 'No counting and no forms — we weigh and itemise at the plant.', items: [
        { title: 'Schedule', text: 'Pick a 30-minute pickup window between 6pm and 10pm.' },
        { title: 'Leave it out', text: 'Any bag. The rider scans the QR sticker we posted you.' },
        { title: 'Back by tomorrow', text: 'Folded, or on hangers if you chose press-only.' },
      ] }),
      b('rates', 'pricing', { title: 'Rates', subtitle: 'GST included. No delivery fee on orders above ₹399.', plans: [
        { name: 'Wash & fold', price: '₹79', period: 'per kg', features: ['Minimum 3 kg', 'Sorted by colour', 'Folded, not pressed', 'Back in 24 hours'], ctaLabel: 'Schedule a pickup', ctaHref: '#home' },
        { name: 'Wash & press', price: '₹129', period: 'per kg', features: ['Minimum 3 kg', 'Steam pressed', 'On hangers, bagged', 'Back in 24 hours'], ctaLabel: 'Schedule a pickup', ctaHref: '#home', featured: true },
        { name: 'Dry clean', price: '₹249', period: 'per piece', features: ['Suits, sarees, silks', 'Stain treatment included', 'Hand finished', 'Back in 48 hours'], ctaLabel: 'Schedule a pickup', ctaHref: '#home' },
      ] }),
      b('track', 'feed', { title: 'Order #4471', layout: 'list', items: [
        { title: 'Picked up', subtitle: 'Yesterday, 9:14pm', text: 'Rider Anitha collected one bag from HSR Layout, Sector 2.', badge: 'Done' },
        { title: 'Weighed & sorted', subtitle: 'Yesterday, 10:40pm', text: '4.2 kg. Two items pulled for a separate wash — a linen kurta and a red towel.', badge: 'Done' },
        { title: 'Washed', subtitle: 'Today, 6:05am', text: 'Fragrance-free detergent at 40°C, as saved in your preferences.', badge: 'Done' },
        { title: 'Pressing', subtitle: 'Today, 11:20am', text: 'Six shirts on the finishing line. Everything else is folded and bagged.', badge: 'In progress' },
        { title: 'Out for delivery', subtitle: 'Expected today, 7:30pm', text: 'You’ll get a call two minutes before the rider arrives.', badge: 'Next' },
      ] }),
      b('install', 'install-prompt', {
        title: 'Add WashLoop to your home screen',
        body: 'Schedule a pickup in two taps and get delivery alerts without another login.',
        actionLabel: 'Add to home screen',
        position: 'bottom',
        tone: 'promo',
        delayMs: 6000,
        dismissible: true,
        rememberDismiss: true,
        platforms: ['ios-safari', 'android', 'desktop-chrome'],
      }),
      b('help', 'faq', { title: 'Help', items: [
        { question: 'What if it rains on my bag?', answer: 'Riders carry lined waterproof sacks and re-bag at the door. If anything arrives damp we rewash it free.' },
        { question: 'Do you separate my clothes from other households?', answer: 'Yes. Every order runs in its own machine drum, tagged to your QR sticker end to end.' },
        { question: 'Something is missing.', answer: 'Message us in the app within seven days. We photograph every order at intake, so most cases resolve the same day.' },
        { question: 'Which areas do you cover?', answer: 'HSR Layout, Koramangala, Indiranagar, BTM and Sarjapur Road. Whitefield opens in September.' },
      ] }),
      b('contact', 'contact-details', { title: 'WashLoop', address: 'Plant 2, 27th Main, HSR Layout, Bengaluru 560102', phone: '+91 80 4718 2200', email: 'care@washloop.in', hours: 'Pickups 18:00–22:00 daily · Support 9:00–21:00' }),
      b('footer', 'footer', { brand: 'WashLoop', tagline: 'Doorstep laundry, Bengaluru.', links: [{ label: 'Rates', href: '#rates' }, { label: 'Track', href: '#track' }, { label: 'Help', href: '#help' }], copyright: '© WashLoop Services Pvt Ltd' }),
    ],
  }),

  tpl({
    id: 'service-it-managed',
    vertical: 'service',
    label: 'Managed IT — Bold',
    description: 'A managed IT provider pitching small businesses on response times, named engineers and per-seat pricing.',
    tags: ['b2b', 'it-support', 'pricing', 'dark', 'long-form'],
    layout: 'bold',
    preset: 'midnight',
    meta: { title: 'Kernline — Managed IT for Berlin SMEs', description: 'Helpdesk, security and infrastructure for 10–200 seat companies. Twelve-minute median response.', lang: 'en', favicon: '🛰️' },
    blocks: [
      b('nav', 'nav', { brand: 'Kernline', sticky: true, links: [{ label: 'Service', href: '#service' }, { label: 'Pricing', href: '#pricing' }, { label: 'SLA', href: '#sla' }, { label: 'Clients', href: '#clients' }], cta: { label: 'Book a review', href: '#contact' } }),
      b('hero', 'hero', { eyebrow: 'Managed IT · Berlin & Brandenburg', headline: 'Your ticket is answered by someone who knows your network', subhead: 'No offshore tier one, no ticket ping-pong. A named engineer pair per client and a twelve-minute median first response.', align: 'center', minHeight: 'full', image: img('kernline-noc-dark'), overlay: 'dark', cta: { label: 'Book an IT review', href: '#contact' } }),
      b('numbers', 'stats', { title: 'Last twelve months, audited', columns: 4, items: [
        { value: '12', label: 'Median first response', suffix: ' min' },
        { value: '94', label: 'Resolved without escalation', suffix: '%' },
        { value: '0', label: 'Ransomware incidents' },
        { value: '61', label: 'Client companies' },
      ] }),
      b('clients', 'logos', { title: 'Trusted by teams of 10 to 200', items: [
        { src: img('kernline-logo-atlas'), alt: 'Atlas Verpackung', href: '#' },
        { src: img('kernline-logo-nordlicht'), alt: 'Nordlicht Media', href: '#' },
        { src: img('kernline-logo-krause'), alt: 'Krause Rechtsanwälte', href: '#' },
        { src: img('kernline-logo-tempelhof'), alt: 'Tempelhof Labs', href: '#' },
        { src: img('kernline-logo-brandt'), alt: 'Brandt Logistik', href: '#' },
      ] }),
      b('service', 'tabs', { items: [
        { label: 'Helpdesk', text: 'Unlimited tickets by mail, phone or Teams. Two named engineers per client plus a documented standby pair, so holidays are invisible to you. Remote fix first; on site within four working hours anywhere inside the Ring.' },
        { label: 'Security', text: 'Managed EDR on every endpoint, conditional access and MFA enforcement, quarterly phishing simulations, and a written incident runbook we rehearse with your team once a year rather than filing away.' },
        { label: 'Infrastructure', text: 'Microsoft 365 and Entra tenant management, Intune device enrolment, firewall and VPN, plus backup with monthly restore tests. You get the restore test report whether or not you read it.' },
        { label: 'Onboarding', text: 'Starters and leavers handled inside one business day from a single form. Hardware sourced, imaged, shipped and asset-tagged; leavers offboarded with an access report you can hand to an auditor.' },
      ] }),
      b('pricing', 'pricing', { title: 'Per seat, per month', subtitle: 'Twelve-month terms. All prices exclude VAT.', plans: [
        { name: 'Core', price: '€39', period: 'per seat / month', features: ['Unlimited helpdesk 8:00–18:00', 'Patch and endpoint management', 'Microsoft 365 administration', 'Backup with monthly restore test'], ctaLabel: 'Book a review', ctaHref: '#contact' },
        { name: 'Secure', price: '€57', period: 'per seat / month', features: ['Everything in Core', 'Managed EDR and 24/7 monitoring', 'Conditional access and MFA rollout', 'Quarterly phishing simulation', 'Named engineer pair'], ctaLabel: 'Book a review', ctaHref: '#contact', featured: true },
        { name: 'Regulated', price: '€84', period: 'per seat / month', features: ['Everything in Secure', 'ISO 27001 evidence pack', 'Annual penetration test', 'Four-hour on-site SLA', 'Quarterly board reporting'], ctaLabel: 'Talk to us', ctaHref: '#contact' },
      ] }),
      b('sla', 'accordion', { title: 'The SLA, in plain language', items: [
        { heading: 'What counts as a P1?', body: 'Anything that stops the whole company working: mail down, site offline, file server unreachable, suspected breach. P1s are acknowledged in fifteen minutes and worked continuously until resolved or downgraded, including out of hours on Secure and above.' },
        { heading: 'What happens out of hours?', body: 'Core clients get next-business-day handling. Secure and Regulated route P1s to a rostered engineer by phone, around the clock, including public holidays in Berlin and Brandenburg.' },
        { heading: 'Do you charge for projects?', body: 'Migrations, office moves and new site builds are quoted separately at €120 per hour or a fixed price. Day-to-day change requests under two hours sit inside the seat fee.' },
        { heading: 'How do we leave?', body: 'Ninety days notice and we hand over documentation, admin credentials and the asset register as a structured export. No exit fee and no hostage tenant. We have done it four times and will give you those references.' },
      ] }),
      b('voices', 'testimonials', { title: 'From the people who are not IT people', items: [
        { quote: 'Our office manager used to spend a day a week on laptops. Now they file a ticket and get on with their actual job.', author: 'Judith Ahrens', role: 'COO, Nordlicht Media' },
        { quote: 'During the last Exchange scare they had our tenant hardened before we had finished reading the news article.', author: 'Sami Ould', role: 'Managing Director, Tempelhof Labs' },
      ] }),
      b('contact', 'contact-form', {
        title: 'Book a 45-minute IT review',
        intro: 'We look at your tenant, your backups and your last three months of tickets, then tell you what we would change — whether or not you hire us.',
        submitLabel: 'Request the review',
        successMessage: 'Thanks. We reply within one business day with two proposed slots.',
        fields: [
          { name: 'name', label: 'Your name', type: 'text', required: true },
          { name: 'company', label: 'Company', type: 'text', required: true },
          { name: 'email', label: 'Work email', type: 'email', required: true },
          { name: 'seats', label: 'How many people?', type: 'select', required: true, options: ['Under 10', '10–25', '26–60', '61–120', '120+'] },
          { name: 'current', label: 'Who supports you today?', type: 'select', options: ['Nobody in particular', 'An internal admin', 'Another provider', 'Not sure'] },
          { name: 'notes', label: 'What is currently annoying you?', type: 'textarea', placeholder: 'Tickets vanish, laptops take a week, the backup has never been tested…' },
        ],
      }),
      b('footer', 'footer', { brand: 'Kernline GmbH', tagline: 'Managed IT, Berlin.', links: [{ label: 'Pricing', href: '#pricing' }, { label: 'SLA', href: '#sla' }, { label: 'Book a review', href: '#contact' }], copyright: '© Kernline GmbH · Ritterstraße 12, 10969 Berlin' }),
    ],
  }),

  tpl({
    id: 'service-window',
    vertical: 'service',
    label: 'Window Cleaning — Minimal',
    description: 'A two-van window and pressure-washing round with one price list, one form and nothing else.',
    tags: ['window-cleaning', 'light', 'one-pager', 'local', 'budget'],
    layout: 'minimal',
    preset: 'ocean',
    meta: { title: 'Clearview — Window Cleaning & Pressure Washing', description: 'Four-weekly window rounds and pressure washing across south Bristol.', lang: 'en', favicon: '🪟' },
    blocks: [
      b('nav', 'nav', { brand: 'Clearview', sticky: false, links: [{ label: 'Prices', href: '#services' }, { label: 'Rounds', href: '#rounds' }], cta: { label: 'Get a price', href: '#quote' } }),
      b('hero', 'hero', { eyebrow: 'South Bristol · BS3, BS4, BS14', headline: 'Windows, four-weekly. Text the night before.', subhead: 'Pure water pole up to three storeys. Pay by card link after we’ve been — never before.', align: 'left', minHeight: 'sm', overlay: 'none', cta: { label: 'Get a price', href: '#quote' } }),
      b('services', 'services-catalogue', { title: 'Prices', subtitle: 'Standard terraced or semi. Larger houses are quoted on the day, always before we start.', items: [
        { name: 'Windows — four-weekly', description: 'Frames and sills included, front and back.', price: '£14' },
        { name: 'Windows — eight-weekly', description: 'Same job, less often. Most popular over winter.', price: '£18' },
        { name: 'Conservatory roof', description: 'Panels, gutters and finials, usually once a year.', price: 'from £45' },
        { name: 'Gutter clear & flush', description: 'Vacuumed out, downpipes flushed, before-and-after photos.', price: 'from £60' },
        { name: 'Driveway pressure wash', description: 'Rotary head, weeds treated, sand re-brushed if block paved.', price: 'from £120' },
        { name: 'Patio & decking wash', description: 'Softer pressure on decking, algae treated afterwards.', price: 'from £90' },
      ] }),
      b('rounds', 'hours', { title: 'When we are out on the round', timezone: 'Europe/London', note: 'Rain days roll to the next dry day, and you get a text either way.', days: [
        { day: 'mon', open: '08:00', close: '16:00' },
        { day: 'tue', open: '08:00', close: '16:00' },
        { day: 'wed', open: '08:00', close: '16:00' },
        { day: 'thu', open: '08:00', close: '16:00' },
        { day: 'fri', open: '08:00', close: '13:00' },
        { day: 'sat', closed: true },
        { day: 'sun', closed: true },
      ] }),
      b('quote', 'contact-form', {
        title: 'Get a price',
        intro: 'A postcode and the house type is enough. We reply the same evening.',
        submitLabel: 'Send it over',
        successMessage: 'Got it — we’ll text you a price tonight.',
        fields: [
          { name: 'name', label: 'Name', type: 'text', required: true },
          { name: 'phone', label: 'Mobile', type: 'tel', required: true },
          { name: 'postcode', label: 'Postcode', type: 'text', required: true, placeholder: 'BS3 4…' },
          { name: 'job', label: 'What do you need?', type: 'select', required: true, options: ['Windows, four-weekly', 'Windows, eight-weekly', 'Conservatory roof', 'Gutters', 'Driveway or patio'] },
        ],
      }),
      b('footer', 'footer', { brand: 'Clearview', tagline: 'Bristol · 07700 900123 · hello@clearviewbristol.co.uk', links: [{ label: 'Prices', href: '#services' }], copyright: '© Clearview Window Cleaning' }),
    ],
  }),

  tpl({
    id: 'service-locksmith',
    vertical: 'service',
    label: 'Locksmith — 24h Landing',
    description: 'A 24-hour emergency locksmith landing page built around one phone-call action and honest arrival times.',
    tags: ['locksmith', 'emergency', 'reviews', 'faq', 'one-pager'],
    layout: 'landing',
    preset: 'mono',
    meta: { title: 'Bolt & Key — 24 Hour Locksmith, Austin TX', description: 'Locked out in Austin? Licensed locksmiths, 25-minute average arrival, price quoted before we roll.', lang: 'en', favicon: '🔑' },
    blocks: [
      b('alert', 'announcement-bar', { text: 'Locked out right now? We answer the phone in person, day or night — (512) 555-0177.', linkLabel: 'Call now', href: 'tel:+15125550177', tone: 'warning', dismissible: false }),
      b('nav', 'nav', { brand: 'Bolt & Key', sticky: true, links: [{ label: 'Services', href: '#services' }, { label: 'Coverage', href: '#coverage' }, { label: 'Reviews', href: '#reviews' }], cta: { label: 'Call now', href: '#call' } }),
      b('hero', 'hero', { eyebrow: 'Licensed TX B-Level · Insured', headline: 'Locked out? Someone is 25 minutes away.', subhead: 'Real vans, real license numbers, and a firm price on the phone before anyone drives to you.', align: 'center', minHeight: 'lg', image: img('boltkey-night-door'), overlay: 'dark', cta: { label: 'Call (512) 555-0177', href: 'tel:+15125550177' } }),
      b('numbers', 'stats', { title: 'Last 90 days', columns: 3, items: [
        { value: '25', label: 'Average arrival', suffix: ' min' },
        { value: '100', label: 'Calls answered by a person', suffix: '%' },
        { value: '2,940', label: 'Jobs completed' },
      ] }),
      b('how', 'steps', { title: 'What happens when you call', items: [
        { title: 'You describe the lock', text: 'Front door, car, safe, or a broken key in the cylinder. Photos help but are not needed.' },
        { title: 'We quote before dispatch', text: 'A firm number including the trip charge. If it changes on site we stop and re-agree first.' },
        { title: 'We open it, then secure it', text: 'Non-destructive entry wherever possible. If a cylinder has to go, the replacement is fitted the same visit.' },
      ] }),
      b('services', 'features', { title: 'What we handle', columns: 3, items: [
        { icon: '🏠', title: 'Home lockouts', text: 'Non-destructive entry on nine of ten residential doors.' },
        { icon: '🚗', title: 'Car lockouts', text: 'Most 2005-onward models. Keys cut and programmed on site.' },
        { icon: '🏢', title: 'Commercial', text: 'Storefront mortise, panic bars, master key systems.' },
        { icon: '🔐', title: 'Rekeys', text: 'New tenant, ex-roommate, lost key — rekeyed in under an hour.' },
        { icon: '🧰', title: 'Safes', text: 'Combination resets and non-destructive safe opening.' },
        { icon: '🚪', title: 'Break-in repair', text: 'Frame, strike plate and cylinder made secure tonight.' },
      ] }),
      b('reviews', 'reviews', { title: 'Reviews written at 2am', average: '4.8', count: '1,204 reviews', source: 'Google & Yelp', items: [
        { rating: 5, quote: 'Key snapped in the deadbolt at midnight. Quoted $95 on the phone, charged $95, and drilled nothing.', author: 'Renee W.', date: 'June 2026', source: 'google' },
        { rating: 5, quote: 'Second time I have called them, and both times a human answered on the second ring. That is the whole business right there.', author: 'Marcus D.', date: 'April 2026', source: 'google' },
        { rating: 4, quote: 'Took forty minutes rather than twenty-five because a game was letting out downtown, but they warned me it would.', author: 'Priya S.', date: 'February 2026', source: 'yelp' },
      ] }),
      b('faq', 'faq', { title: 'Straight answers', items: [
        { question: 'How much is a house lockout?', answer: '$95 for a standard residential lockout between 8am and 8pm, $135 overnight. That includes the trip charge — it is not added afterwards.' },
        { question: 'Will you damage my door?', answer: 'Nine of ten residential doors open non-destructively. If yours needs drilling we tell you the replacement cost first and you decide.' },
        { question: 'Can you prove you are legitimate?', answer: 'Every tech carries a Texas DPS locksmith license and a company ID. Ask for both at the door — we would rather you did.' },
        { question: 'Do I need to prove it is my home?', answer: 'Yes. A lease, photo ID with the address, or addressed mail. It protects you as much as it protects us.' },
      ] }),
      b('coverage', 'map', { query: 'Austin, Texas', zoom: 11, height: 340, label: 'Downtown, East Austin, Hyde Park, South Congress, Mueller, Round Rock and Pflugerville' }),
      b('call', 'cta', { headline: 'Still standing outside?', subhead: 'Call (512) 555-0177 — answered in person, day or night.', background: 'primary', button: { label: 'Call (512) 555-0177', href: 'tel:+15125550177' } }),
      b('footer', 'footer', { brand: 'Bolt & Key Locksmiths', tagline: 'Twenty-four hours, all of Austin.', links: [{ label: 'Services', href: '#services' }, { label: 'Coverage', href: '#coverage' }, { label: 'Reviews', href: '#reviews' }], copyright: '© Bolt & Key LLC · TX DPS B-Level #B14722' }),
    ],
  }),

  tpl({
    id: 'service-waste',
    vertical: 'service',
    label: 'Waste Clearance & Skip Hire — Editorial',
    description: 'A licensed clearance and skip hire firm arguing its case on recycling rates and paperwork you can defend.',
    tags: ['waste', 'long-form', 'b2b', 'local', 'pricing'],
    layout: 'editorial',
    preset: 'sand',
    meta: { title: 'Kettleworth Waste & Skip Hire', description: 'Skips, wait-and-load and full house clearance across Leeds. 92% recycled or reprocessed, nothing to landfill, and the transfer notes to prove it.', lang: 'en', favicon: '♻️' },
    blocks: [
      b('nav', 'nav', { brand: 'Kettleworth', sticky: true, links: [{ label: 'Skips & clearance', href: '#skips' }, { label: 'Where it goes', href: '#journey' }, { label: 'Our story', href: '#story' }, { label: 'Licences', href: '#licences' }], cta: { label: 'Book a skip', href: '#contact' } }),
      b('hero', 'hero', { eyebrow: 'Leeds & Wakefield · Registered carrier CBDU8842', headline: 'Anyone can take it away. Ask them where it goes.', subhead: 'Fly-tipping fines follow the waste back to whoever produced it, not the van that took it. Here is exactly what happens to yours.', align: 'left', minHeight: 'md', image: img('kettleworth-yard-morning'), overlay: 'light', cta: { label: 'Read the sorting process', href: '#journey' } }),
      b('argument', 'rich-text', { blocks: [
        { kind: 'heading', text: 'Your duty of care does not end at the kerb' },
        { kind: 'paragraph', text: 'Under the Environmental Protection Act, the household or business that produced the waste stays legally responsible for it until it reaches a licensed facility. If a cheap van tips your old kitchen units in a lay-by on the A61, the enforcement letter comes to you — not to them.' },
        { kind: 'paragraph', text: 'That is why every Kettleworth job, from a two-yard mini skip to a four-tonne office strip-out, leaves with a waste transfer note showing our carrier registration, the destination site and the tonnage. It is emailed before the van is back in the yard.' },
        { kind: 'quote', text: 'The paperwork is not admin. It is the thing you hold up when somebody asks.' },
        { kind: 'subheading', text: 'What that means in practice' },
        { kind: 'bullet', text: 'Ask any waste carrier for their CBDU number and check it free on the Environment Agency register before they load.' },
        { kind: 'bullet', text: 'Never accept a cash job with no paperwork, however good the price looks on the day.' },
        { kind: 'bullet', text: 'Keep transfer notes for two years, or three for hazardous waste such as asbestos sheeting and fluorescent tubes.' },
      ] }),
      b('skips', 'services-catalogue', { title: 'Skips and clearance', subtitle: 'Prices include delivery, collection, tipping and the transfer note. Road permits are £42 extra and we arrange them with Leeds City Council.', items: [
        { name: '2-yard mini skip', description: 'Roughly 25 bin bags. Fits on most single driveways.', price: '£145 · 7 days' },
        { name: '4-yard midi skip', description: 'The bathroom-refit skip. Soil and rubble friendly.', price: '£195 · 7 days' },
        { name: '8-yard builders skip', description: 'Full house refurbishment. No soil above half fill.', price: '£265 · 14 days' },
        { name: 'Wait & load', description: 'We arrive, you point, we load, we leave. No permit needed.', price: 'from £220 · 1 hour' },
        { name: 'Full house clearance', description: 'Probate and end of tenancy, photographed room by room before and after.', price: 'from £480' },
        { name: 'Office strip-out', description: 'Desks, chairs and partitions. Out of hours at no premium.', price: 'quoted per floor' },
      ] }),
      b('journey', 'timeline', { title: 'Where your skip actually goes', items: [
        { date: 'Hour 0', title: 'Collected and weighed', text: 'A weighbridge ticket is raised at the Hunslet yard. Overweight loads are billed on that tonnage, and you get the ticket.' },
        { date: 'Hour 1', title: 'Tipped on the picking floor', text: 'Nothing goes straight to landfill. Every load is tipped and spread before anyone decides anything about it.' },
        { date: 'Hour 2', title: 'Hand-picked, then screened', text: 'Timber, metal, plasterboard and clean hardcore come off by hand. The rest goes over a trommel and a magnet.' },
        { date: 'Day 1', title: 'Sent to reprocessors', text: 'Metal to a Sheffield merchant, timber chipped for biomass, hardcore crushed to 6F2 and sold back to groundworkers.' },
        { date: 'Day 2', title: 'Residual to energy recovery', text: 'What genuinely cannot be recycled — about 8% by weight — goes to the Cross Green energy-from-waste plant. None of it goes to landfill.' },
        { date: 'Day 3', title: 'Your paperwork lands', text: 'Transfer note and recycling percentage emailed for your specific job, not a generic annual company figure.' },
      ] }),
      b('numbers', 'stats', { title: 'Independently audited, 2025–26', columns: 3, items: [
        { value: '92', label: 'Recycled or reprocessed', suffix: '%' },
        { value: '11,400', label: 'Tonnes handled' },
        { value: '0', label: 'Enforcement notices since 2009' },
      ] }),
      b('story', 'about', { eyebrow: 'Since 2009', title: 'Two siblings, one tipper, a great deal of paperwork', body: 'Kettleworth started with a single tipper truck and a rule that has not changed: if we cannot say where a load ended up, we do not take it. Seventeen years later we run nine vehicles and a permitted transfer station in Hunslet, and that rule is why the council, three housing associations and most of the letting agents in south Leeds send us their difficult jobs. We are not the cheapest quote you will get this week. We are the one that still stands up if somebody audits it in two years.', image: img('kettleworth-tipper-crew'), imageAlt: 'A clearance crew loading a tipper truck outside a terraced house', imageSide: 'right' }),
      b('faq', 'faq', { title: 'The questions we actually get', items: [
        { question: 'Can I put a mattress or a fridge in the skip?', answer: 'Mattresses yes, at £18 each on top, because they need separate processing. Fridges and freezers no — gas removal is regulated, but we collect them separately for £30.' },
        { question: 'What about plasterboard?', answer: 'It cannot legally be mixed with general waste. Put it in the tonne bags we drop off free with any skip and it costs nothing extra.' },
        { question: 'Do I need a permit?', answer: 'Only if the skip sits on a public road. We apply on your behalf — allow three working days, or choose wait-and-load instead.' },
        { question: 'How fast can you come?', answer: 'Next working day on skips ordered before 3pm. Wait-and-load and clearances are usually within 48 hours.' },
      ] }),
      b('licences', 'legal', { title: 'Licences and terms', align: 'start', separator: '·', documents: [
        { label: 'Waste carrier licence', title: 'Upper tier waste carrier, broker and dealer — CBDU8842', content: 'Kettleworth Waste Ltd is registered with the Environment Agency as an upper tier carrier, broker and dealer of controlled waste, registration CBDU8842, valid to 31 March 2028. The registration can be verified free on the public register at gov.uk. Our Hunslet transfer station operates under environmental permit EPR/QB3992ZC.' },
        { label: 'Duty of care', title: 'Waste transfer notes and your duty of care', content: 'A waste transfer note is issued for every job and emailed within 24 hours of collection. It records the producer, our carrier registration, the EWC codes, the destination site and the tonnage. Retain it for two years, or three years for hazardous waste. We keep our own copies for seven.' },
        { label: 'Terms of hire', title: 'Skip hire terms', content: 'Hire periods run from delivery, and overstays are charged at £9 per day beyond the included period. Skips must not be loaded above the fill line and must not contain fridges, tyres, asbestos, batteries, paint or gas bottles — tell us in advance and we collect those separately. Overweight loads are charged at the weighbridge rate of £128 per tonne above the included tonnage.' },
      ] }),
      b('contact', 'contact-details', { title: 'Book or ask', address: 'Kettleworth Transfer Station, Bridge Mill Road, Hunslet, Leeds LS10 1RT', phone: '+44 113 496 0184', email: 'yard@kettleworthwaste.co.uk', hours: 'Yard Mon–Fri 6:30–17:00 · Sat 7:00–12:00 · Phones from 6:00' }),
      b('footer', 'footer', { brand: 'Kettleworth Waste & Skip Hire', tagline: 'Licensed, weighed, accounted for.', links: [{ label: 'Skips', href: '#skips' }, { label: 'Where it goes', href: '#journey' }, { label: 'Licences', href: '#licences' }], copyright: '© Kettleworth Waste Ltd · CBDU8842' }),
    ],
  }),
];
