/**
 * `tech` starter templates — SaaS launch, mobile app, developer API, AI product,
 * digital agency, pre-launch startup teaser, and an open-source project homepage.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const techTemplates: Template[] = [
  tpl({
    id: 'tech-saas',
    vertical: 'tech',
    label: 'SaaS — Product launch',
    description: 'A product-led SaaS launch page: screenshots, proof, and a pricing table that closes.',
    tags: ['saas', 'pricing', 'b2b', 'dark', 'one-pager'],
    layout: 'landing',
    preset: 'midnight',
    meta: { title: 'Flowdeck — Ship faster', description: 'The workspace that turns scattered work into one clear flow.', lang: 'en', favicon: '🚀' },
    blocks: [
      b('nav', 'nav', { brand: 'Flowdeck', sticky: true, links: [{ label: 'Features', href: '#features' }, { label: 'Pricing', href: '#pricing' }, { label: 'FAQ', href: '#faq' }], cta: { label: 'Start free', href: '#pricing' } }),
      b('hero', 'hero-app', { headline: 'Turn scattered work into one clear flow', subhead: 'Docs, tasks, and reviews in a single fast workspace your team will actually use.', installLabel: 'Start free', installHref: '#pricing', screenshots: [{ src: img('app-1'), alt: 'Board view' }, { src: img('app-2'), alt: 'Doc editor' }, { src: img('app-3'), alt: 'Timeline' }] }),
      b('features', 'features', { title: 'Everything in one place', columns: 3, items: [
        { icon: '⚡', title: 'Fast by default', text: 'Keyboard-first, instant sync, offline-ready.' },
        { icon: '🧩', title: 'Docs + tasks', text: 'Write a doc, turn a line into a task.' },
        { icon: '🔗', title: 'Integrates', text: 'GitHub, Slack, and 40+ tools.' },
      ] }),
      b('stats', 'stats', { title: 'Teams move faster', columns: 3, items: [
        { value: '12k', label: 'Teams' },
        { value: '30', label: 'Less status-chasing', suffix: '%' },
        { value: '4.8', label: 'G2 rating', suffix: '★' },
      ] }),
      b('pricing', 'pricing', { title: 'Simple pricing', subtitle: 'Start free. Upgrade when you grow.', plans: [
        { name: 'Free', price: '£0', period: '/mo', features: ['Up to 5 members', 'Unlimited docs', 'Core integrations'], ctaLabel: 'Start free', ctaHref: '#' },
        { name: 'Team', price: '£8', period: '/user/mo', features: ['Unlimited members', 'Timeline & goals', 'Priority support'], ctaLabel: 'Start trial', ctaHref: '#', featured: true },
        { name: 'Enterprise', price: 'Custom', features: ['SSO & SCIM', 'Audit log', 'Dedicated CSM'], ctaLabel: 'Contact sales', ctaHref: '#' },
      ] }),
      b('logos', 'logos', { title: 'Trusted by fast teams', items: [{ src: img('tlogo-1'), alt: 'Company one' }, { src: img('tlogo-2'), alt: 'Company two' }, { src: img('tlogo-3'), alt: 'Company three' }, { src: img('tlogo-4'), alt: 'Company four' }] }),
      b('faq', 'faq', { title: 'Questions', items: [
        { question: 'Is there a free plan?', answer: 'Yes — free forever for up to 5 members.' },
        { question: 'Can we import our data?', answer: 'One-click import from Notion, Jira, and Asana.' },
      ] }),
      b('cta', 'cta', { headline: 'Get your team in flow', subhead: 'Free for small teams. No credit card required.', background: 'primary', button: { label: 'Start free', href: '#pricing' } }),
      b('footer', 'footer', { brand: 'Flowdeck', tagline: 'Ship faster, together.', links: [{ label: 'Features', href: '#features' }, { label: 'Pricing', href: '#pricing' }], copyright: '© Flowdeck, Inc.' }),
    ],
  }),

  tpl({
    id: 'tech-app',
    vertical: 'tech',
    label: 'Mobile app — Install page',
    description: 'An app-store style landing page for a consumer mobile app, built around screenshots and ratings.',
    tags: ['mobile-first', 'app', 'reviews', 'video', 'b2c'],
    layout: 'app',
    preset: 'candy',
    meta: { title: 'Tempo — the calm habit tracker', description: 'Build three habits at a time, without the streak guilt. Free on iOS and Android.', lang: 'en', favicon: '🌀' },
    blocks: [
      b('shell', 'app-shell', { brand: 'Tempo', tabs: [
        { label: 'Home', href: '#hero', icon: '🏠' },
        { label: 'Features', href: '#features', icon: '✨' },
        { label: 'Reviews', href: '#reviews', icon: '⭐' },
        { label: 'Get it', href: '#get', icon: '⬇️' },
      ] }),
      b('hero', 'hero-app', {
        headline: 'Three habits. No streak guilt.',
        subhead: 'Tempo tracks the handful of things you actually want to keep doing, and quietly forgives the days you miss.',
        installLabel: 'Get Tempo — free',
        installHref: '#get',
        screenshots: [
          { src: img('tempo-screen-today'), alt: 'Today view with three habit rings' },
          { src: img('tempo-screen-week'), alt: 'Weekly rhythm chart' },
          { src: img('tempo-screen-nudge'), alt: 'A gentle evening reminder' },
          { src: img('tempo-screen-widget'), alt: 'Home screen widget' },
        ],
      }),
      b('features', 'features', { title: 'Small on purpose', subtitle: 'Everything Tempo does, it does in under five seconds.', columns: 2, items: [
        { icon: '🕯️', title: 'Three at a time', text: 'A hard cap of three active habits. Finish one before you add another.' },
        { icon: '🌙', title: 'Rest days built in', text: 'Set two rest days a week and Tempo simply skips them — no broken streak, no red X.' },
        { icon: '📵', title: 'Works offline', text: 'Everything is stored on device. Sync is optional and end-to-end encrypted.' },
        { icon: '⌚', title: 'Watch + widget', text: 'Tick a habit from your wrist or your home screen without opening the app.' },
      ] }),
      b('tour', 'video', { provider: 'youtube', src: 'M7lc1UVf-VE', title: 'A 90-second tour of Tempo', poster: img('tempo-tour-poster'), caption: 'Ninety seconds, start to finish — recorded on an iPhone 15.' }),
      b('reviews', 'reviews', {
        title: 'What people are saying',
        subtitle: 'Ratings from the App Store and Google Play.',
        average: '4.8',
        count: '12,400 ratings',
        source: 'App Store',
        items: [
          { rating: 5, quote: 'I have deleted six habit apps for making me feel bad on a Tuesday. This one just says "see you tomorrow" and I keep opening it.', author: 'Priya M.', date: 'March 2026', source: 'app-store' },
          { rating: 5, quote: 'The three-habit limit sounded gimmicky until I realised it is the whole product. I finally finished one instead of half-doing nine.', author: 'Dev Okonkwo', date: 'February 2026', source: 'app-store' },
          { rating: 4, quote: 'Widget is excellent. I would love a shared view for my partner and me, but the core loop is spot on.', author: 'Hannah R.', date: 'January 2026', source: 'google' },
        ],
      }),
      b('faq', 'faq', { title: 'Before you download', items: [
        { question: 'Is it really free?', answer: 'The full habit tracker is free forever. Tempo Plus ($2.99/mo) adds cross-device sync, unlimited history, and the shared household view.' },
        { question: 'Do you sell my data?', answer: 'No. There is no analytics SDK and no ad network in the app. Habit data never leaves your device unless you turn on sync.' },
        { question: 'Which devices are supported?', answer: 'iOS 16 and later, Android 11 and later, plus Apple Watch and Wear OS companions.' },
      ] }),
      b('get', 'cta', { headline: 'Start with one habit tonight', subhead: 'Free on iOS and Android. No account needed to begin.', background: 'accent', button: { label: 'Download Tempo', href: '#' } }),
      b('social', 'social-links', { title: 'Follow along', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'instagram', href: 'https://instagram.com/tempoapp', label: '@tempoapp' },
        { platform: 'tiktok', href: 'https://tiktok.com/@tempoapp', label: 'Tempo on TikTok' },
        { platform: 'email', href: 'mailto:hello@tempo.app', label: 'hello@tempo.app' },
      ] }),
      b('install', 'install-prompt', { title: 'Add Tempo to your home screen', body: 'The web app works offline too — one tap and it lives next to your other apps.', actionLabel: 'Show me how', position: 'bottom-right', tone: 'promo', delayMs: 6000, dismissible: true, rememberDismiss: true, platforms: ['ios-safari', 'android', 'desktop-chrome'] }),
      b('footer', 'footer', { brand: 'Tempo', tagline: 'A calmer way to keep going.', links: [{ label: 'Features', href: '#features' }, { label: 'Reviews', href: '#reviews' }, { label: 'Download', href: '#get' }], copyright: '© Tempo Labs · Portland, OR' }),
    ],
  }),

  tpl({
    id: 'tech-devtool',
    vertical: 'tech',
    label: 'Developer API — Docs-first',
    description: 'A stripped-back developer landing page where the code sample is the hero and pricing is per request.',
    tags: ['api', 'developers', 'b2b', 'pricing', 'light'],
    layout: 'minimal',
    preset: 'mono',
    meta: { title: 'Relayd — webhooks that never drop', description: 'A hosted webhook gateway with retries, replay, and signature verification. One endpoint, one line of code.', lang: 'en', favicon: '🛰️' },
    blocks: [
      b('nav', 'nav', { brand: 'relayd', sticky: true, links: [
        { label: 'Quickstart', href: '#quickstart' },
        { label: 'Why relayd', href: '#why' },
        { label: 'Pricing', href: '#pricing' },
      ], cta: { label: 'Get an API key', href: '#pricing' } }),
      b('hero', 'hero', {
        eyebrow: 'Webhook infrastructure',
        headline: 'Webhooks that never drop',
        subhead: 'Point your producers at one relayd endpoint. We handle signing, retries with exponential backoff, replay, and a searchable delivery log — so your consumers can be down and nobody notices.',
        align: 'left',
        minHeight: 'md',
        overlay: 'none',
        cta: { label: 'Read the quickstart', href: '#quickstart' },
      }),
      b('quickstart', 'tabs', { items: [
        { label: 'cURL', text: 'curl https://api.relayd.eu/v1/events \\\n  -H "Authorization: Bearer $RELAYD_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"topic":"invoice.paid","payload":{"id":"in_8812","total":4900}}\'\n\n# → 202 Accepted\n# { "id": "ev_01HQ8", "attempts": 0, "status": "queued" }' },
        { label: 'Node', text: 'import { Relayd } from "@relayd/node";\n\nconst relayd = new Relayd(process.env.RELAYD_KEY);\n\nawait relayd.events.publish({\n  topic: "invoice.paid",\n  payload: { id: "in_8812", total: 4900 },\n});\n\n// Verify on the receiving side:\nconst event = relayd.verify(req.rawBody, req.headers["relayd-signature"]);' },
        { label: 'Python', text: 'from relayd import Relayd\n\nrelayd = Relayd(os.environ["RELAYD_KEY"])\n\nrelayd.events.publish(\n    topic="invoice.paid",\n    payload={"id": "in_8812", "total": 4900},\n)\n\n# Verify on the receiving side:\nevent = relayd.verify(request.data, request.headers["Relayd-Signature"])' },
        { label: 'Go', text: 'client := relayd.New(os.Getenv("RELAYD_KEY"))\n\n_, err := client.Events.Publish(ctx, relayd.Event{\n    Topic:   "invoice.paid",\n    Payload: map[string]any{"id": "in_8812", "total": 4900},\n})\n\n// Verify on the receiving side:\nevent, err := client.Verify(body, r.Header.Get("Relayd-Signature"))' },
      ] }),
      b('why', 'features', { title: 'What you stop building', columns: 3, items: [
        { icon: '↩︎', title: 'Retries with backoff', text: 'Twelve attempts over 24 hours, jittered. Consumers can be down for a working day and lose nothing.' },
        { icon: '🔏', title: 'Signed payloads', text: 'HMAC-SHA256 signatures with key rotation, plus a five-minute replay window to stop replay attacks.' },
        { icon: '🔎', title: 'Delivery log', text: 'Every request and response body kept for 30 days, searchable by topic, status, or consumer.' },
      ] }),
      b('numbers', 'stats', { columns: 4, items: [
        { value: '99.99', label: 'Delivery SLA', suffix: '%' },
        { value: '41', label: 'Median publish latency', suffix: 'ms' },
        { value: '2.4', label: 'Events last month', suffix: 'B' },
        { value: '3', label: 'EU regions' },
      ] }),
      b('pricing', 'pricing', { title: 'Pay per event, not per seat', subtitle: 'Every plan includes all regions, all features, and the full 30-day log.', plans: [
        { name: 'Hobby', price: '€0', period: '/mo', features: ['100k events/month', '7-day delivery log', 'Community Discord'], ctaLabel: 'Get a key', ctaHref: '#' },
        { name: 'Growth', price: '€49', period: '/mo', features: ['5M events/month, then €4 per million', '30-day log with replay', 'Custom retry policies', 'Email support, 1 business day'], ctaLabel: 'Start building', ctaHref: '#', featured: true },
        { name: 'Scale', price: '€490', period: '/mo', features: ['100M events/month', 'Dedicated queues + static egress IPs', '99.99% SLA with credits', 'Shared Slack channel'], ctaLabel: 'Talk to an engineer', ctaHref: '#' },
      ] }),
      b('footer', 'footer', { brand: 'relayd', tagline: 'Webhook infrastructure, hosted in the EU.', links: [{ label: 'Quickstart', href: '#quickstart' }, { label: 'Pricing', href: '#pricing' }, { label: 'Status', href: '#' }], copyright: '© Relayd GmbH · Prinzessinnenstraße 20, 10969 Berlin' }),
    ],
  }),

  tpl({
    id: 'tech-ai',
    vertical: 'tech',
    label: 'AI product — Copilot',
    description: 'An AI assistant page that sells by showing a real transcript instead of describing the model.',
    tags: ['ai', 'b2b', 'saas', 'newsletter', 'dark'],
    layout: 'conversational',
    preset: 'ocean',
    meta: { title: 'Sightline — the support copilot that cites its sources', description: 'Drafts replies from your own docs and tickets, with a citation on every sentence.', lang: 'en', favicon: '🔭' },
    blocks: [
      b('nav', 'nav', { brand: 'Sightline', sticky: true, links: [
        { label: 'See it work', href: '#thread' },
        { label: 'How it works', href: '#how' },
        { label: 'Security', href: '#security' },
      ], cta: { label: 'Book a walkthrough', href: '#cta' } }),
      b('hero', 'hero', {
        eyebrow: 'Support copilot',
        headline: 'It drafts the reply. It shows you where every line came from.',
        subhead: 'Sightline reads your help centre, past tickets, and release notes, then writes the answer your team would have written — with a citation on each claim, so an agent can approve in seconds.',
        align: 'left',
        minHeight: 'md',
        overlay: 'none',
        cta: { label: 'Watch a real thread', href: '#thread' },
      }),
      b('thread', 'chat-thread', {
        title: 'A live ticket, unedited',
        subtitle: 'Tuesday 09:14 — a billing question that would normally take an agent eleven minutes.',
        participants: [
          { id: 'customer', name: 'Marisol Vega', role: 'user', avatar: img('sightline-avatar-customer') },
          { id: 'copilot', name: 'Sightline', role: 'bot' },
          { id: 'agent', name: 'Theo (support)', role: 'agent', avatar: img('sightline-avatar-agent') },
        ],
        messages: [
          { from: 'customer', time: '09:14', body: [
            { kind: 'text', text: 'We were charged twice on the annual plan this morning — invoice 44119 and 44120, same amount. Can you refund one and tell me why it happened?' },
          ] },
          { from: 'copilot', time: '09:14', body: [
            { kind: 'text', text: 'Draft reply, 3 sources found:' },
            { kind: 'text', text: 'Hi Marisol — you were charged twice because the annual renewal ran while a card-update retry was still in flight. Invoice 44120 is the duplicate; I have refunded it in full and you should see it back on the card within 5–10 business days. Nothing else about your plan has changed.' },
            { kind: 'list', ordered: false, items: [
              { label: 'Billing runbook §4 — duplicate charge on retry overlap' },
              { label: 'Ticket #21884 — same pattern, resolved by refunding the later invoice' },
              { label: 'Release note 2026.03 — retry window shortened to 60s' },
            ] },
            { kind: 'buttons', items: [
              { label: 'Approve & send', href: '#' },
              { label: 'Edit draft', href: '#' },
              { label: 'Show the runbook', href: '#' },
            ] },
          ] },
          { from: 'agent', time: '09:15', body: [
            { kind: 'text', text: 'Approved. Adding the refund reference so they can match it on their statement.' },
            { kind: 'code', lang: 'json', text: '{\n  "refund": "re_9K21B",\n  "invoice": "44120",\n  "amount": 1188.00,\n  "currency": "USD"\n}' },
          ] },
          { from: 'customer', time: '09:31', body: [
            { kind: 'text', text: 'That was fast, thank you — and thanks for explaining the cause rather than just refunding it.' },
          ] },
        ],
      }),
      b('how', 'steps', { title: 'How it gets that good', subtitle: 'Two weeks from kickoff to agents trusting the drafts.', items: [
        { title: 'Connect your sources', text: 'Help centre, Zendesk or Intercom history, Notion runbooks, and your changelog. Read-only, scoped tokens.' },
        { title: 'Sightline learns your voice', text: 'It grounds every sentence in a retrieved passage and matches the tone of your highest-rated past replies.' },
        { title: 'Agents stay in the loop', text: 'Nothing sends itself. Every draft arrives with its sources so a human approves, edits, or rejects in one click.' },
      ] }),
      b('security', 'accordion', { title: 'Security, in plain terms', items: [
        { heading: 'Do you train on our data?', body: 'No. Your content is used only to retrieve context for your own workspace. It is never used to train a shared model, and it is never pooled with another customer.' },
        { heading: 'Where does the data live?', body: 'US-East by default, EU-West on request. Encrypted at rest with AES-256 and in transit with TLS 1.3. You can pin a workspace to a single region at creation time.' },
        { heading: 'What happens when we leave?', body: 'Export everything as JSON at any time. On cancellation we delete embeddings and raw source copies within 30 days and send you written confirmation.' },
        { heading: 'Compliance', body: 'SOC 2 Type II since 2025, annual penetration test, and a signed DPA with standard contractual clauses for EU customers. Sub-processor list is public and versioned.' },
      ] }),
      b('logos', 'logos', { title: 'Answering tickets at', items: [
        { src: img('sightline-logo-alpine'), alt: 'Alpine Fintech' },
        { src: img('sightline-logo-parcelo'), alt: 'Parcelo' },
        { src: img('sightline-logo-northmark'), alt: 'Northmark Health' },
        { src: img('sightline-logo-bindle'), alt: 'Bindle Commerce' },
        { src: img('sightline-logo-quarry'), alt: 'Quarry Analytics' },
      ] }),
      b('digest', 'newsletter', { title: 'The Grounded Reply', intro: 'A short monthly note on evaluating support AI — refusal rates, citation accuracy, and what we got wrong. No product news.', placeholder: 'you@company.com', submitLabel: 'Send me the digest', successMessage: 'Subscribed — the next issue goes out on the first Tuesday.' }),
      b('cta', 'cta', { headline: 'See it read your own help centre', subhead: 'A 30-minute walkthrough on your real tickets. No sandbox demo data.', background: 'primary', button: { label: 'Book a walkthrough', href: '#' } }),
      b('footer', 'footer', { brand: 'Sightline', tagline: 'Support drafts you can actually check.', links: [{ label: 'See it work', href: '#thread' }, { label: 'Security', href: '#security' }, { label: 'Digest', href: '#digest' }], copyright: '© Sightline AI, Inc. · Boston, MA' }),
    ],
  }),

  tpl({
    id: 'tech-agency',
    vertical: 'tech',
    label: 'Digital agency — Studio',
    description: 'A work-first studio site where case study images carry the pitch and the brief form closes it.',
    tags: ['agency', 'portfolio', 'gallery', 'b2b', 'design'],
    layout: 'showcase',
    preset: 'sand',
    meta: { title: 'Northlight Studio — product design & build', description: 'A Melbourne studio that designs and ships digital products for teams without an in-house design function.', lang: 'en', favicon: '◧' },
    blocks: [
      b('nav', 'nav', { brand: 'Northlight', sticky: true, links: [
        { label: 'Work', href: '#work' },
        { label: 'Services', href: '#services' },
        { label: 'Studio', href: '#team' },
      ], cta: { label: 'Start a project', href: '#brief' } }),
      b('hero', 'hero', {
        eyebrow: 'Product design & build · Melbourne',
        headline: 'We design the thing, then we ship the thing',
        subhead: 'A studio of eight. Research, interface design, and front-end engineering under one roof, so nothing gets lost in a handover that never happens.',
        align: 'center',
        minHeight: 'full',
        image: img('northlight-studio-hero'),
        overlay: 'scrim',
        cta: { label: 'See recent work', href: '#work' },
      }),
      b('work', 'carousel', { title: 'Recent work', autoplay: false, items: [
        { src: img('northlight-case-ferry'), alt: 'Ferry booking app on a phone', caption: 'SeaLink — rebuilt ticketing flow, 31% fewer abandoned bookings' },
        { src: img('northlight-case-clinic'), alt: 'Clinic scheduling dashboard', caption: 'Carevale — scheduling tool for 40 allied health clinics' },
        { src: img('northlight-case-grain'), alt: 'Agricultural data platform on a laptop', caption: 'Grainline — grain contract platform, design system and build' },
        { src: img('northlight-case-museum'), alt: 'Museum wayfinding kiosk', caption: 'Melbourne Museum — wayfinding kiosks and companion web app' },
        { src: img('northlight-case-lender'), alt: 'Loan origination interface', caption: 'Kestrel Lending — broker portal, 9 weeks brief to launch' },
      ] }),
      b('services', 'services-catalogue', { title: 'How we work with you', subtitle: 'Fixed-scope engagements. We quote in weeks, not day rates.', items: [
        { name: 'Discovery sprint', description: 'Two weeks: user interviews, a service map, and a clickable prototype you can put in front of customers.', price: 'from A$18,000', ctaLabel: 'Enquire', ctaHref: '#brief' },
        { name: 'Design & build', description: 'Eight to sixteen weeks, a squad of three, shipping to your repo every Friday. Design system included.', price: 'from A$85,000', ctaLabel: 'Enquire', ctaHref: '#brief' },
        { name: 'Design system', description: 'An audit, a token set, and a documented component library in your framework, handed over with a workshop.', price: 'from A$32,000', ctaLabel: 'Enquire', ctaHref: '#brief' },
        { name: 'Embedded designer', description: 'One of our designers inside your team, three days a week, minimum three months.', price: 'A$9,600 / month', ctaLabel: 'Enquire', ctaHref: '#brief' },
      ] }),
      b('numbers', 'stats', { columns: 3, items: [
        { value: '46', label: 'Products shipped since 2017' },
        { value: '8', label: 'People, on purpose' },
        { value: '74', label: 'Work from repeat clients', suffix: '%' },
      ] }),
      b('words', 'testimonials', { title: 'What clients say afterwards', items: [
        { quote: 'They interviewed eleven of our brokers before drawing a single screen. The portal launched with almost no change requests because the hard thinking happened first.', author: 'Alina Petrov', role: 'COO, Kestrel Lending' },
        { quote: 'We had been quoted six months by two other studios. Northlight scoped it to nine weeks, told us what to cut, and hit the date.', author: 'James Whitfield', role: 'Head of Product, SeaLink' },
        { quote: 'The design system they left behind is the reason our two in-house developers can now ship UI without us.', author: 'Ngozi Bello', role: 'CTO, Grainline' },
      ] }),
      b('team', 'team', { title: 'The studio', subtitle: 'You work with the people you meet in the pitch. Every time.', columns: 4, members: [
        { name: 'Hana Sato', role: 'Founder & principal designer', photo: img('northlight-person-hana'), bio: 'Fifteen years in product design, half of it in regulated industries.' },
        { name: 'Marcus Ellery', role: 'Engineering lead', photo: img('northlight-person-marcus'), bio: 'Front-end architecture, design systems, and stubborn accessibility opinions.' },
        { name: 'Divya Raman', role: 'Research lead', photo: img('northlight-person-divya'), bio: 'Runs every discovery sprint. Has interviewed more farmers than most agencies have clients.' },
        { name: 'Tom Ferreira', role: 'Studio manager', photo: img('northlight-person-tom'), bio: 'Scoping, scheduling, and the reason projects land on the date we said.' },
      ] }),
      b('brief', 'contact-form', {
        title: 'Tell us about the project',
        intro: 'A few lines is plenty. We reply within two business days, and we will tell you honestly if we are the wrong studio for it.',
        submitLabel: 'Send the brief',
        successMessage: 'Got it — we will come back to you within two business days.',
        fields: [
          { name: 'name', label: 'Your name', type: 'text', placeholder: 'Alex Nguyen', required: true },
          { name: 'email', label: 'Work email', type: 'email', placeholder: 'alex@company.com.au', required: true },
          { name: 'company', label: 'Company', type: 'text', placeholder: 'Company or product name' },
          { name: 'engagement', label: 'What are you after?', type: 'select', options: ['Discovery sprint', 'Design & build', 'Design system', 'Embedded designer', 'Not sure yet'], required: true },
          { name: 'budget', label: 'Rough budget', type: 'select', options: ['Under A$25,000', 'A$25,000 – A$80,000', 'A$80,000 – A$200,000', 'Over A$200,000'] },
          { name: 'brief', label: 'The brief', type: 'textarea', placeholder: 'What are you building, who is it for, and what is the deadline?', required: true },
          { name: 'nda', label: 'We need an NDA before talking', type: 'checkbox' },
        ],
      }),
      b('footer', 'footer', { brand: 'Northlight Studio', tagline: 'Product design & build · Melbourne, Australia', links: [{ label: 'Work', href: '#work' }, { label: 'Services', href: '#services' }, { label: 'Start a project', href: '#brief' }], copyright: '© Northlight Studio Pty Ltd · Level 2, 118 Gertrude St, Fitzroy VIC 3065' }),
    ],
  }),

  tpl({
    id: 'tech-teaser',
    vertical: 'tech',
    label: 'Startup — Pre-launch teaser',
    description: 'A one-screen teaser for a startup still in private beta: a promise, a roadmap, and a waitlist.',
    tags: ['startup', 'newsletter', 'one-pager', 'dark', 'launch'],
    layout: 'bold',
    preset: 'midnight',
    meta: { title: 'Kestrel — freight paperwork, gone', description: 'Private beta: Kestrel turns port and customs paperwork into a single automated flow for Indian exporters.', lang: 'en', favicon: '🪶' },
    blocks: [
      b('banner', 'announcement-bar', { text: 'Private beta — 40 of 60 pilot places taken.', linkLabel: 'Join the waitlist', href: '#waitlist', tone: 'promo', dismissible: false }),
      b('hero', 'hero', {
        eyebrow: 'Private beta · Bengaluru',
        headline: 'Freight paperwork, gone',
        subhead: 'Exporters lose four working days a shipment to forms that already contain the same forty fields. Kestrel fills them once, files them everywhere, and tells you the moment something is rejected.',
        align: 'center',
        minHeight: 'full',
        image: img('kestrel-port-hero'),
        overlay: 'dark',
        cta: { label: 'Request a pilot place', href: '#waitlist' },
      }),
      b('manifesto', 'rich-text', { blocks: [
        { kind: 'heading', text: 'Why we are building this' },
        { kind: 'paragraph', text: 'We spent 2024 inside three freight forwarders in Chennai and Mundra, watching operations teams retype the same shipment details into a shipping bill, an e-invoice, a certificate of origin, and two portals that reject silently at 6pm on a Friday.' },
        { kind: 'quote', text: 'Nobody in this building has ever been paid to type. We get paid when a container moves.' },
        { kind: 'paragraph', text: 'Kestrel takes the commercial invoice and packing list you already have, derives every downstream document, and files them against ICEGATE and your CHA. When a filing bounces, you get a message that says which field and why — not a status code.' },
        { kind: 'subheading', text: 'What the pilot includes' },
        { kind: 'bullet', text: 'Automated shipping bill and e-invoice generation from your existing exports data.' },
        { kind: 'bullet', text: 'Rejection alerts on WhatsApp with the offending field highlighted.' },
        { kind: 'bullet', text: 'A weekly call with a founder, and free use through to general availability.' },
      ] }),
      b('roadmap', 'timeline', { title: 'Where we are', items: [
        { date: 'Oct 2025', title: 'Founded', text: 'Two founders out of Freightwala and Razorpay, funded by a pre-seed from Blume.' },
        { date: 'Mar 2026', title: 'First filing', text: 'A shipping bill generated and accepted end to end, with no human retyping. Twelve minutes, down from two days.' },
        { date: 'Now', title: 'Private beta', text: 'Sixty pilot exporters across Chennai, Mundra, and Nhava Sheva. Free, hands-on, and noisy in the best way.' },
        { date: 'Q4 2026', title: 'General availability', text: 'Self-serve onboarding, CHA marketplace, and per-shipment pricing.' },
      ] }),
      b('rule', 'divider', { style: 'gradient' }),
      b('waitlist', 'newsletter', {
        title: 'Ask for a pilot place',
        intro: 'Tell us your email and we will send the two questions we need answered to see if your shipment volume fits the beta. Twenty places left.',
        placeholder: 'you@exportco.in',
        submitLabel: 'Request a place',
        successMessage: 'Received — watch for a note from Anjali within a day or two.',
      }),
      b('social', 'social-links', { layout: 'row', variant: 'icon', align: 'center', links: [
        { platform: 'linkedin', href: 'https://linkedin.com/company/kestrelfreight', label: 'Kestrel on LinkedIn' },
        { platform: 'x', href: 'https://x.com/kestrelfreight', label: '@kestrelfreight' },
        { platform: 'email', href: 'mailto:founders@kestrel.in', label: 'founders@kestrel.in' },
      ] }),
      b('rights', 'copyright', { holder: 'Kestrel Logistics Technologies Pvt Ltd', text: 'Bengaluru · Private beta, everything subject to change.', showSymbol: true, align: 'center' }),
    ],
  }),

  tpl({
    id: 'tech-oss',
    vertical: 'tech',
    label: 'Open source — Project home',
    description: 'A maintainer-run project homepage: packages, quick start, contributor stats, and release notes.',
    tags: ['open-source', 'developers', 'community', 'long-form', 'light'],
    layout: 'catalogue',
    preset: 'forest',
    meta: { title: 'Halyard — composable data pipelines for Python', description: 'An MIT-licensed toolkit for building, testing, and scheduling data pipelines that fit in your head.', lang: 'en', favicon: '⛵' },
    blocks: [
      b('nav', 'nav', { brand: 'Halyard', sticky: true, links: [
        { label: 'Packages', href: '#packages' },
        { label: 'Quick start', href: '#start' },
        { label: 'Community', href: '#community' },
        { label: 'Releases', href: '#releases' },
      ], cta: { label: 'GitHub', href: '#' } }),
      b('hero', 'hero', {
        eyebrow: 'MIT licensed · v3.2 · Python 3.10+',
        headline: 'Composable data pipelines that fit in your head',
        subhead: 'Halyard is a small set of packages for defining, testing, and scheduling pipelines as plain Python functions. No DSL, no scheduler lock-in, no YAML pyramid.',
        align: 'left',
        minHeight: 'sm',
        overlay: 'none',
        cta: { label: 'Install in 30 seconds', href: '#start' },
      }),
      b('packages', 'feed', { title: 'The packages', layout: 'cards', items: [
        { title: 'halyard-core', subtitle: 'v3.2.1 · 1.2 MB', text: 'Task graph, typed inputs and outputs, retries, and the local runner. The only package most projects need.', href: '#', badge: 'stable', image: img('halyard-pkg-core') },
        { title: 'halyard-io', subtitle: 'v3.2.1 · 640 kB', text: 'Readers and writers for Parquet, Postgres, S3, BigQuery, and Delta, all sharing one connection abstraction.', href: '#', badge: 'stable', image: img('halyard-pkg-io') },
        { title: 'halyard-test', subtitle: 'v3.1.4 · 210 kB', text: 'Golden-file fixtures and a fake clock so a pipeline test runs in milliseconds without touching a warehouse.', href: '#', badge: 'stable', image: img('halyard-pkg-test') },
        { title: 'halyard-scheduler', subtitle: 'v0.9.0 · 780 kB', text: 'A single-binary scheduler with cron and event triggers. Optional — Airflow and Dagster adapters ship too.', href: '#', badge: 'beta', image: img('halyard-pkg-scheduler') },
        { title: 'halyard-viz', subtitle: 'v0.4.2 · 1.8 MB', text: 'Renders a pipeline graph to SVG or a local web view, with run history overlaid on each node.', href: '#', badge: 'experimental', image: img('halyard-pkg-viz') },
      ] }),
      b('start', 'steps', { title: 'Quick start', subtitle: 'From an empty directory to a running pipeline.', items: [
        { title: 'Install', text: 'pip install halyard-core halyard-io — no compiler, no system dependencies, wheels for Linux, macOS, and Windows.' },
        { title: 'Write a task', text: 'Decorate a plain function with @task. Type hints become the contract; Halyard checks them before anything runs.' },
        { title: 'Compose a pipeline', text: 'Call tasks from a @pipeline function. The graph is inferred from the calls — there is nothing else to declare.' },
        { title: 'Run and test it', text: 'halyard run daily_sales runs it locally; pytest with halyard-test runs the same graph against fixtures in under a second.' },
      ] }),
      b('community', 'stats', { title: 'The project, in numbers', columns: 4, items: [
        { value: '18.4k', label: 'GitHub stars' },
        { value: '312', label: 'Contributors' },
        { value: '1.1M', label: 'Monthly downloads' },
        { value: '6', label: 'Median days to first review' },
      ] }),
      b('maintainers', 'team', { title: 'Maintainers', subtitle: 'Halyard is volunteer-run. Three of us are funded part-time by the Open Data Fund.', columns: 3, members: [
        { name: 'Sanne de Vries', role: 'Lead maintainer · Utrecht', photo: img('halyard-maintainer-sanne'), bio: 'Wrote the original task graph in 2021. Reviews most core PRs.', socials: [{ label: 'GitHub', href: 'https://github.com/sannedv' }] },
        { name: 'Lucas Amorim', role: 'halyard-io · São Paulo', photo: img('halyard-maintainer-lucas'), bio: 'Owns the connector layer and the compatibility matrix.', socials: [{ label: 'GitHub', href: 'https://github.com/lamorim' }] },
        { name: 'Wei Tan', role: 'Docs & scheduler · Singapore', photo: img('halyard-maintainer-wei'), bio: 'Writes the guides and is slowly getting the scheduler to 1.0.', socials: [{ label: 'GitHub', href: 'https://github.com/weitan' }] },
      ] }),
      b('releases', 'blog-list', { title: 'Release notes', columns: 3, posts: [
        { title: '3.2 — Incremental runs', excerpt: 'Tasks can now declare a watermark, so a rerun only processes what changed. Plus a 40% faster graph resolver.', href: '#', date: '2 June 2026', tag: 'minor', image: img('halyard-release-32') },
        { title: '3.1 — Typed connection pools', excerpt: 'halyard-io connections are now typed and pooled per pipeline run, which fixes the long-standing Postgres leak on retries.', href: '#', date: '14 April 2026', tag: 'minor', image: img('halyard-release-31') },
        { title: '3.0 — Goodbye YAML', excerpt: 'The declarative config layer is gone. Pipelines are Python functions and nothing else. Migration guide included.', href: '#', date: '3 February 2026', tag: 'major', image: img('halyard-release-30') },
      ] }),
      b('contribute', 'faq', { title: 'Contributing', items: [
        { question: 'Where do I start?', answer: 'Issues tagged "good first issue" are kept stocked and each one names a maintainer who will review it. Say hello in the issue before you start so nobody duplicates work.' },
        { question: 'What is the review turnaround?', answer: 'Median six days. If a pull request has had no reply after two weeks, ping the weekly triage thread and we will pick it up.' },
        { question: 'Do you accept new connectors?', answer: 'Yes, into halyard-io, provided the connector has an integration test that runs against a container and a named person willing to maintain it.' },
        { question: 'How is the project funded?', answer: 'Open Data Fund grants and GitHub Sponsors. Nobody is employed by a company that sells a hosted Halyard, and we intend to keep it that way.' },
      ] }),
      b('cta', 'cta', { headline: 'Star it, or better, break it', subhead: 'Bug reports from real pipelines are worth more to us than stars.', background: 'surface', button: { label: 'Open an issue', href: '#' } }),
      b('footer', 'footer', { brand: 'Halyard', tagline: 'MIT licensed. Maintained by volunteers.', links: [{ label: 'Packages', href: '#packages' }, { label: 'Quick start', href: '#start' }, { label: 'Releases', href: '#releases' }, { label: 'Contributing', href: '#contribute' }], copyright: '© Halyard contributors · Docs and code under the MIT licence' }),
    ],
  }),
];
