/**
 * `trades` starter templates — nine skilled-trade businesses, from a one-person
 * tiler's profile page to a metal fabricator's B2B catalogue, each leaning on the
 * proof trades actually sell on: before/after work, certifications, service areas
 * and a fast route to a free quote.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const tradesTemplates: Template[] = [
  // ── Carpenter / joiner — showcase: the work carries the argument ────────────
  tpl({
    id: 'trades-carpenter',
    vertical: 'trades',
    label: 'Carpenter & Joiner — Showcase',
    description: 'A bespoke joinery workshop selling on photographs of finished built-ins.',
    tags: ['carpentry', 'gallery', 'portfolio', 'local', 'light'],
    layout: 'showcase',
    preset: 'sand',
    meta: { title: 'Hollis & Fern — Bespoke Joinery', description: 'Hand-made alcove units, staircases and fitted wardrobes across Bristol and Bath.', lang: 'en', favicon: '🪵' },
    blocks: [
      b('nav', 'nav', { brand: 'Hollis & Fern', sticky: true, links: [{ label: 'Work', href: '#work' }, { label: 'What we make', href: '#make' }, { label: 'Workshop', href: '#workshop' }, { label: 'Quote', href: '#quote' }], cta: { label: 'Free quote', href: '#quote' } }),
      b('hero', 'hero', { eyebrow: 'Workshop-made in Bedminster since 2009', headline: 'Furniture that grows out of your walls', subhead: 'Alcove libraries, window seats, staircases and wardrobes — drawn, made and fitted by the same two people.', align: 'left', minHeight: 'lg', image: img('trd-carpenter-hero'), overlay: 'scrim', cta: { label: 'See recent work', href: '#work' } }),
      b('work', 'gallery', { layout: 'masonry', columns: 3, gap: 'lg', lightbox: true, items: [
        { src: img('trd-carp-alcove'), alt: 'Painted alcove shelving either side of a Victorian chimney breast', caption: 'Twin alcove libraries, Totterdown — tulipwood, hand-painted' },
        { src: img('trd-carp-stairs'), alt: 'Oak staircase with a curved handrail', caption: 'Replacement oak stair, Clifton — 11 weeks from survey to fit' },
        { src: img('trd-carp-wardrobe'), alt: 'Floor-to-ceiling fitted wardrobe with shaker doors', caption: 'Shaker wardrobe run under a sloped ceiling, Bath' },
        { src: img('trd-carp-seat'), alt: 'Window seat with a lift-up storage lid', caption: 'Bay window seat with felt-lined toy storage' },
        { src: img('trd-carp-kitchen'), alt: 'Freestanding kitchen dresser in ash', caption: 'Ash dresser, finished in hardwax oil' },
        { src: img('trd-carp-desk'), alt: 'Home office desk built into a loft eaves space', caption: 'Loft desk cut to the rafter line, Southville' },
      ] }),
      b('before-after', 'split', { rows: [
        { title: 'Before: a dead corner and a radiator', text: 'The client had two shallow alcoves nobody had touched since the 1970s, a boxed-in meter and nowhere to put books. We surveyed on a Tuesday and had a drawing back by the Friday.', image: img('trd-carp-before'), imageAlt: 'Bare plaster alcoves before joinery work' },
        { title: 'After: 14 linear metres of shelving', text: 'Painted MDF carcasses with solid tulipwood face frames, scribed to a floor that drops 18mm across the room. The meter hides behind a magnetic-catch panel.', image: img('trd-carp-after'), imageAlt: 'Finished painted alcove shelving full of books' },
      ] }),
      b('make', 'services-catalogue', { title: 'What we make', subtitle: 'Every job is drawn to your room, not picked from a catalogue.', items: [
        { name: 'Alcove & media units', description: 'Shelving, cupboards and cable-managed TV walls, scribed to uneven walls.', price: 'from £1,450' },
        { name: 'Fitted wardrobes', description: 'Full-height runs, sloped-ceiling and eaves solutions, painted or veneered.', price: 'from £2,900' },
        { name: 'Staircases & handrails', description: 'Replacement flights, closed-string conversions, spindle and newel work.', price: 'quoted per flight' },
        { name: 'Doors & sash windows', description: 'Hanging, easing, draught-proofing and like-for-like heritage repairs.', price: 'from £180' },
        { name: 'Freestanding pieces', description: 'Dressers, benches, desks and dining tables in ash, oak or walnut.', price: 'from £900' },
      ] }),
      b('workshop', 'about', { eyebrow: 'Who you get', title: 'Two people, one workbench', body: 'Hollis & Fern is Dani Hollis and Ade Fernandes. Dani draws and machines, Ade fits — and whoever answers the phone is the person who will be in your house. We keep three jobs on the board at a time, which is why the diary runs about six weeks out and why nothing gets abandoned half-finished. Everything is made 15 minutes away in a railway arch in Bedminster, so a wrong-sized panel is a morning to fix rather than a fortnight.', image: img('trd-carp-workshop'), imageAlt: 'Two joiners marking out a panel on a workbench', imageSide: 'left' }),
      b('proof', 'testimonials', { title: 'What clients said afterwards', items: [
        { quote: 'They spotted that our floor sloped before we did, and built the whole run to hide it. Six months on there is not a single gap.', author: 'Rachel', role: 'Totterdown' },
        { quote: 'Quoted in writing, started on the day they said, and hoovered up every night. The staircase is the best thing in the house now.', author: 'Tom & Priya', role: 'Clifton' },
        { quote: 'I sent them a bad phone photo of an eaves cupboard and got a proper drawing back. That is when I knew.', author: 'Marianne', role: 'Bath' },
      ] }),
      b('quote', 'contact-form', { title: 'Get a free quote', intro: 'Send a photo of the space and rough dimensions — we come back with a fixed written price, usually within three working days.', submitLabel: 'Send my enquiry', successMessage: 'Got it. Dani or Ade will reply within three working days.', fields: [
        { name: 'name', label: 'Your name', type: 'text', required: true },
        { name: 'email', label: 'Email', type: 'email', required: true },
        { name: 'phone', label: 'Phone', type: 'tel', placeholder: '07700 900000' },
        { name: 'job', label: 'What are you after?', type: 'select', required: true, options: ['Alcove or media unit', 'Fitted wardrobe', 'Staircase or handrail', 'Doors or sash windows', 'Freestanding furniture', 'Something else'] },
        { name: 'detail', label: 'Tell us about the space', type: 'textarea', placeholder: 'Room, rough sizes, and when you would like it done.', required: true },
      ] }),
      b('contact', 'contact-details', { title: 'The workshop', address: 'Arch 12, Mead Street, Bristol BS3 4NF', phone: '+44 117 496 0142', email: 'hello@hollisandfern.co.uk', hours: 'Workshop Mon–Fri 8:00–17:00 · site visits Sat mornings' }),
      b('footer', 'footer', { brand: 'Hollis & Fern', tagline: 'Bespoke joinery, Bristol & Bath.', links: [{ label: 'Work', href: '#work' }, { label: 'What we make', href: '#make' }, { label: 'Free quote', href: '#quote' }], copyright: '© Hollis & Fern Joinery Ltd · Reg. 09184422' }),
    ],
  }),

  // ── General builder & extensions — editorial: long-form trust building ──────
  tpl({
    id: 'trades-builder',
    vertical: 'trades',
    label: 'Builder & Extensions — Editorial',
    description: 'A main contractor explaining, at length, how an extension actually runs.',
    tags: ['building', 'extensions', 'long-form', 'local', 'b2c'],
    layout: 'editorial',
    preset: 'mono',
    meta: { title: 'Ardenwood Construction — Extensions & Renovations', description: 'Single-storey extensions, loft conversions and whole-house renovations in North London.', lang: 'en', favicon: '🏗️' },
    blocks: [
      b('nav', 'nav', { brand: 'Ardenwood', sticky: false, links: [{ label: 'How a build runs', href: '#process' }, { label: 'Programme', href: '#programme' }, { label: 'Team', href: '#team' }, { label: 'Notes', href: '#notes' }, { label: 'Enquire', href: '#enquire' }], cta: { label: 'Request a quote', href: '#enquire' } }),
      b('hero', 'hero', { eyebrow: 'Main contractor · North London · est. 2004', headline: 'Nobody wants an extension. They want the room at the end of it.', subhead: 'So we spend the first three weeks on drawings, dates and a fixed price — and the rest of it out of your way.', align: 'left', minHeight: 'md', overlay: 'none' }),
      b('essay', 'rich-text', { blocks: [
        { kind: 'heading', text: 'Why most builds go wrong before anyone lifts a shovel' },
        { kind: 'paragraph', text: 'In twenty years of rear extensions we have never seen a job overrun because someone laid bricks slowly. It overruns because a steel was ordered late, because the structural calculations came back needing a bigger pad foundation, or because nobody asked where the boiler flue was going until week six.' },
        { kind: 'paragraph', text: 'That is the whole of our method. We do the boring, unglamorous sequencing work up front, in writing, and we charge for it as a separate pre-construction stage so you are not paying for guesses.' },
        { kind: 'subheading', text: 'What a fixed price from us actually includes' },
        { kind: 'bullet', text: 'Building control fees, structural engineer’s calculations and the party wall surveyor’s time.' },
        { kind: 'bullet', text: 'Every steel, pad and lintel priced off the engineer’s drawing, not off a rule of thumb.' },
        { kind: 'bullet', text: 'Skip hire, scaffolding, protection to your existing floors, and a weekly clean.' },
        { kind: 'bullet', text: 'A named site manager who is on your job and no more than one other.' },
        { kind: 'quote', text: 'If it is not on the schedule of works, it is not in the price — and we would rather argue about that in week zero than week twelve.' },
        { kind: 'subheading', text: 'What it does not include, honestly' },
        { kind: 'paragraph', text: 'Kitchens, bathroom sanitaryware, flooring and decoration are carried as provisional sums against a budget you set. You buy what you like; we fit it. If you underspend, you get the difference back on the final account.' },
      ] }),
      b('rule', 'divider', { style: 'line' }),
      b('process', 'steps', { title: 'How a build runs', subtitle: 'Five stages, and you always know which one you are in.', items: [
        { title: 'Site visit and budget range', text: 'Ninety minutes, free, and you get an honest range on the day. If your budget and the job do not meet, we say so then.' },
        { title: 'Pre-construction, 3–4 weeks', text: 'Engineer’s calcs, building control submission, party wall notices, and a schedule of works line by line. Charged at £1,850, credited back if you proceed.' },
        { title: 'Fixed price and dates', text: 'One number, one start date, one completion date, and a payment schedule tied to stages rather than the calendar.' },
        { title: 'On site', text: 'Site manager on your job daily, a photo update every Friday, and a fortnightly 20-minute call whether or not anything is wrong.' },
        { title: 'Snagging and handover', text: 'You write the snag list, not us. Ten-year structural warranty and all certificates handed over in one folder.' },
      ] }),
      b('programme', 'timeline', { title: 'A typical 4m rear extension, week by week', items: [
        { date: 'Weeks 1–2', title: 'Groundworks', text: 'Site set-up, protection, dig and inspect foundations with building control.' },
        { date: 'Week 3', title: 'Concrete and drainage', text: 'Foundations poured, existing drain runs diverted and re-inspected.' },
        { date: 'Weeks 4–6', title: 'Brick and block to plate', text: 'Cavity walls up, insulation in, wall plate levelled.' },
        { date: 'Week 7', title: 'Steels and structural opening', text: 'The noisy week. Steels craned in, the existing rear wall opened up, props out.' },
        { date: 'Weeks 8–9', title: 'Roof and watertight', text: 'Joists, warm-deck insulation, single-ply membrane, rooflights in. You get your garden back.' },
        { date: 'Weeks 10–12', title: 'First fix and plaster', text: 'Electrics, plumbing, underfloor heating, then plasterboard and skim.' },
        { date: 'Weeks 13–14', title: 'Second fix and snagging', text: 'Doors, sockets, screed finish, decoration, and your snag list.' },
      ] }),
      b('numbers', 'stats', { title: 'Where we stand', columns: 4, items: [
        { value: '148', label: 'Extensions completed' },
        { value: '96', label: 'Finished on the contract date', suffix: '%' },
        { value: '10', label: 'Structural warranty', suffix: ' yr' },
        { value: '2', label: 'Concurrent jobs per manager' },
      ] }),
      b('team', 'team', { title: 'Who runs your job', columns: 3, members: [
        { name: 'Nadia Oyelaran', role: 'Director & estimator', photo: img('trd-build-nadia'), bio: 'Prices every job personally. Ex-quantity surveyor, so the schedule of works is unusually specific.' },
        { name: 'Frank Ilyich', role: 'Site manager', photo: img('trd-build-frank'), bio: 'Twenty-two years on the tools. Runs two jobs at a time and no more, deliberately.' },
        { name: 'Sam Whitcombe', role: 'Site manager', photo: img('trd-build-sam'), bio: 'Loft conversions and structural openings. Sends the Friday photo update at 4pm sharp.' },
      ] }),
      b('notes', 'blog-list', { title: 'Notes from site', columns: 3, posts: [
        { title: 'Party wall notices: the six weeks nobody budgets for', excerpt: 'If your neighbour dissents you need a surveyor, and a surveyor needs time. Serve early and it costs you nothing.', href: '#', image: img('trd-build-note-party'), date: '4 March', tag: 'Planning' },
        { title: 'Why your engineer wants a bigger foundation than your builder guessed', excerpt: 'Clay shrinkage, tree roots and NHBC depth tables, explained without the jargon.', href: '#', image: img('trd-build-note-found'), date: '19 February', tag: 'Groundworks' },
        { title: 'Rooflights: the one spec decision worth spending on', excerpt: 'Thermal break, not glass area, is what stops the condensation you will otherwise live with.', href: '#', image: img('trd-build-note-roof'), date: '30 January', tag: 'Spec' },
      ] }),
      b('breath', 'spacer', { size: 'lg' }),
      b('faq', 'faq', { title: 'The questions we get every week', items: [
        { question: 'Do we have to move out?', answer: 'For a rear extension, usually not — the disruptive part is the week the steels go in and the rear wall opens up. For a whole-house renovation, yes, and we will tell you that at the first visit rather than the fourth.' },
        { question: 'What happens if you find something unexpected?', answer: 'We stop, photograph it, price the variation and get it signed before we carry on. Nothing lands on the final account that you have not agreed in writing first.' },
        { question: 'Are you insured and accredited?', answer: '£10m public liability, FMB members since 2011, and every electrician and gas engineer on site is NICEIC or Gas Safe registered in their own right. Certificates go in the handover folder.' },
        { question: 'How far do you travel?', answer: 'Barnet, Haringey, Enfield and Camden. Outside that we would be sending vans through the North Circular twice a day and charging you for it.' },
      ] }),
      b('enquire', 'contact-form', { title: 'Request a quote', intro: 'The first site visit is free and takes about ninety minutes. Bring your drawings if you have them, and your budget if you have one.', submitLabel: 'Request a site visit', successMessage: 'Thanks — Nadia will call within two working days to book a visit.', fields: [
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'email', label: 'Email', type: 'email', required: true },
        { name: 'phone', label: 'Phone', type: 'tel', required: true },
        { name: 'postcode', label: 'Postcode', type: 'text', placeholder: 'N8 9DR', required: true },
        { name: 'scope', label: 'What are you planning?', type: 'select', required: true, options: ['Single-storey rear extension', 'Side return', 'Loft conversion', 'Two-storey extension', 'Whole-house renovation', 'Not sure yet'] },
        { name: 'drawings', label: 'I already have architect’s drawings', type: 'checkbox' },
        { name: 'detail', label: 'Anything else', type: 'textarea', placeholder: 'Rough size, timescale, and planning status.' },
      ] }),
      b('footer', 'footer', { brand: 'Ardenwood Construction', tagline: 'Extensions, lofts and renovations across North London.', links: [{ label: 'How a build runs', href: '#process' }, { label: 'Notes from site', href: '#notes' }, { label: 'Enquire', href: '#enquire' }], copyright: '© Ardenwood Construction Ltd · FMB member 41902' }),
    ],
  }),

  // ── Electrician — landing: one offer, proof, repeated CTA ───────────────────
  tpl({
    id: 'trades-electrician',
    vertical: 'trades',
    label: 'Electrician — Emergency Landing',
    description: 'A 24-hour electrical callout page built around one number and one promise.',
    tags: ['electrician', 'emergency', 'one-pager', 'reviews', 'dark'],
    layout: 'landing',
    preset: 'midnight',
    meta: { title: 'Voltaic Electrical — 24hr Emergency Electrician, Melbourne', description: 'Licensed emergency electricians across inner Melbourne. On site in 60 minutes or the callout is free.', lang: 'en', favicon: '⚡' },
    blocks: [
      b('alert', 'announcement-bar', { text: 'Power out right now? We answer the phone 24/7 — 1300 864 220.', linkLabel: 'Book a callout', href: '#book', tone: 'warning', dismissible: false }),
      b('nav', 'nav', { brand: 'Voltaic Electrical', sticky: true, links: [{ label: 'Callout', href: '#promise' }, { label: 'Prices', href: '#prices' }, { label: 'Reviews', href: '#reviews' }], cta: { label: 'Call now', href: '#book' } }),
      b('hero', 'hero', { eyebrow: 'REC 24817 · A-Grade licensed · 24/7', headline: 'On site within 60 minutes, or the callout fee is on us', subhead: 'Dead circuits, tripping safety switches, burning smells and switchboard failures — across Fitzroy, Carlton, Richmond and the CBD.', align: 'center', minHeight: 'full', image: img('trd-elec-hero'), overlay: 'dark', cta: { label: 'Book an emergency callout', href: '#book' } }),
      b('promise', 'features', { title: 'What the 60-minute promise means', subtitle: 'Not a marketing line — it is on the invoice.', columns: 3, items: [
        { icon: '⏱️', title: 'Sixty minutes, timed', text: 'The clock starts when you hang up. Late and the $99 callout is waived, no argument.' },
        { icon: '💳', title: 'Price before we start', text: 'The electrician quotes the fix on your doorstep. You approve it before a tool comes out of the van.' },
        { icon: '📋', title: 'Certificate every time', text: 'A Certificate of Electrical Safety is emailed the same day, whatever the job size.' },
      ] }),
      b('numbers', 'stats', { title: 'Last twelve months', columns: 4, items: [
        { value: '41', label: 'Average response', suffix: ' min' },
        { value: '3,190', label: 'Emergency callouts' },
        { value: '4.9', label: 'Google rating', suffix: '★' },
        { value: '0', label: 'Callout fee if we are late', prefix: '$' },
      ] }),
      b('prices', 'pricing', { title: 'What it costs', subtitle: 'Flat rates, published. Nights and weekends are the same price as Tuesday morning.', plans: [
        { name: 'Emergency callout', price: '$99', period: 'callout', features: ['Attendance within 60 minutes', 'Full fault diagnosis', 'Written quote before any work', 'Waived if we arrive late'], ctaLabel: 'Book now', ctaHref: '#book' },
        { name: 'Callout + first hour', price: '$245', period: 'most jobs', features: ['Everything in Emergency callout', 'First hour of labour', 'Common parts carried on the van', 'Certificate of Electrical Safety'], ctaLabel: 'Book now', ctaHref: '#book', featured: true },
        { name: 'Switchboard upgrade', price: '$1,290', period: 'from', features: ['Full RCBO switchboard replacement', 'Safety switches on every circuit', 'Compliance testing and tagging', 'Booked ahead, not at emergency rates'], ctaLabel: 'Get a quote', ctaHref: '#book' },
      ] }),
      b('reviews', 'reviews', { title: 'What Melbourne says', subtitle: 'Pulled from our Google profile, unedited.', average: '4.9', count: '612 reviews', source: 'Google', items: [
        { rating: 5, quote: 'Half the house went dark at 11pm with a newborn asleep. Someone was at the door at 11:34 and had found a cooked neutral in the switchboard by midnight.', author: 'Hien N.', date: '12 May', source: 'google' },
        { rating: 5, quote: 'Quoted $245 on the doorstep, charged $245. I have never had that happen with a trade before.', author: 'Bec T.', date: '2 May', source: 'google' },
        { rating: 4, quote: 'Took 70 minutes, not 60, so they took the callout off without me having to ask. Fixed the safety switch that had been tripping for a month.', author: 'Marcus D.', date: '28 April', source: 'google' },
        { rating: 5, quote: 'Burning smell from a downlight. They came out, found a failed transformer in the ceiling and checked every other fitting in the house before leaving.', author: 'Priya S.', date: '15 April', source: 'google' },
      ] }),
      b('areas', 'accordion', { title: 'Where we cover, and how fast', items: [
        { heading: 'Inner north — Fitzroy, Carlton, Brunswick, Northcote', body: 'Two vans on shift overnight. Typical arrival 25–40 minutes. This is our home patch.' },
        { heading: 'Inner east — Richmond, Hawthorn, Kew, Camberwell', body: 'Typical arrival 35–50 minutes, longer over the Punt Road bridge at peak. The 60-minute promise still applies.' },
        { heading: 'CBD, Docklands and Southbank', body: 'Apartment and strata work included. Have your building manager’s number ready — most towers need a fob for the riser cupboards.' },
        { heading: 'Outer suburbs beyond 15km', body: 'We will still come, but we quote the response time honestly on the phone rather than promising 60 minutes we cannot hit.' },
      ] }),
      b('cta', 'cta', { headline: 'Still without power?', subhead: 'One call, a real person, and a van already on shift.', background: 'accent', button: { label: 'Book an emergency callout', href: '#book' } }),
      b('book', 'contact-form', { title: 'Book a callout', intro: 'Faster to ring 1300 864 220 if it is urgent — this form is for anything that can wait until business hours.', submitLabel: 'Request a callout', successMessage: 'Received. If this is an emergency, call 1300 864 220 now — we answer 24/7.', fields: [
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'phone', label: 'Mobile', type: 'tel', required: true },
        { name: 'suburb', label: 'Suburb', type: 'text', placeholder: 'Fitzroy North', required: true },
        { name: 'urgency', label: 'How urgent?', type: 'select', required: true, options: ['Emergency — no power now', 'Today if possible', 'This week', 'Booked job, no rush'] },
        { name: 'fault', label: 'What is happening?', type: 'textarea', placeholder: 'Which circuits, and when it started.', required: true },
      ] }),
      b('contact', 'contact-details', { title: 'Voltaic Electrical', address: '3/44 Alexandra Parade, Fitzroy North VIC 3068', phone: '1300 864 220', email: 'jobs@voltaicelectrical.com.au', hours: 'Emergency line 24/7 · office Mon–Fri 7:30–17:00 AEST' }),
      b('footer', 'footer', { brand: 'Voltaic Electrical', tagline: 'Licensed emergency electricians, inner Melbourne.', links: [{ label: 'Prices', href: '#prices' }, { label: 'Coverage', href: '#areas' }, { label: 'Book', href: '#book' }], copyright: '© Voltaic Electrical Pty Ltd · REC 24817 · ABN 61 004 118 622' }),
    ],
  }),

  // ── Plumber & heating engineer — app: a service you keep on your phone ──────
  tpl({
    id: 'trades-plumber',
    vertical: 'trades',
    label: 'Plumber & Heating — App',
    description: 'A plumbing service packaged as an installable app for repeat customers.',
    tags: ['plumbing', 'booking', 'mobile-first', 'emergency', 'local'],
    layout: 'app',
    preset: 'ocean',
    meta: { title: 'Nalke Plumbing — Book a Plumber, Pune', description: 'Book a licensed plumber or geyser engineer in Pune. Track the job, pay after.', lang: 'en', favicon: '🚰' },
    blocks: [
      b('shell', 'app-shell', { brand: 'Nalke', tabs: [
        { label: 'Book', href: '#book', icon: '📅' },
        { label: 'Jobs', href: '#jobs', icon: '🧰' },
        { label: 'Rates', href: '#rates', icon: '₹' },
        { label: 'Hours', href: '#hours', icon: '🕗' },
        { label: 'Help', href: '#help', icon: '💬' },
      ] }),
      b('lead', 'hero-app', { headline: 'A plumber, booked in four taps', subhead: 'Pick a slot, get a name and a photo, watch the van move, pay after the job. Across Kothrud, Baner, Aundh and Viman Nagar.', installLabel: 'Add to home screen', installHref: '#install', screenshots: [
        { src: img('trd-plumb-shot-book'), alt: 'Booking screen showing three available time slots' },
        { src: img('trd-plumb-shot-track'), alt: 'Live tracking screen with the engineer twelve minutes away' },
        { src: img('trd-plumb-shot-quote'), alt: 'In-app quote screen listing parts and labour' },
        { src: img('trd-plumb-shot-history'), alt: 'Job history screen with past service records' },
      ] }),
      b('install', 'install-prompt', { title: 'Keep Nalke on your home screen', body: 'Next leak, you are two taps from an engineer instead of ten minutes of searching.', actionLabel: 'Show me how', position: 'bottom', tone: 'promo', delayMs: 6000, dismissible: true, rememberDismiss: true, platforms: ['ios-safari', 'android', 'desktop-chrome'] }),
      b('jobs', 'feed', { title: 'What we get called out for', layout: 'cards', items: [
        { title: 'Geyser not heating', subtitle: 'Most common winter job', text: 'Element, thermostat or scale. Diagnosed in 20 minutes; most fixes are same-visit.', badge: 'Same day', image: img('trd-plumb-geyser'), href: '#book' },
        { title: 'Overhead tank overflow', subtitle: 'Float valve failure', text: 'Wasting water down the outside wall since the last monsoon? Usually a ₹450 part.', badge: 'From ₹650', image: img('trd-plumb-tank'), href: '#book' },
        { title: 'Blocked kitchen line', subtitle: 'Slow drain, bad smell', text: 'Motorised auger, then a camera check so you know whether it will come back.', badge: 'From ₹900', image: img('trd-plumb-drain'), href: '#book' },
        { title: 'Bathroom leak below', subtitle: 'Neighbour complaining', text: 'Leak detection without breaking tiles first. We find it, then we agree what to open up.', badge: 'Detection ₹1,200', image: img('trd-plumb-leak'), href: '#book' },
        { title: 'Full bathroom re-plumb', subtitle: 'Renovation work', text: 'CPVC re-run, concealed cistern, mixer sets. Quoted on site, fixed price.', badge: 'Quoted', image: img('trd-plumb-bathroom'), href: '#book' },
        { title: 'Annual society contract', subtitle: 'For housing societies', text: 'Scheduled pump servicing, tank cleaning and a named engineer on call.', badge: 'B2B', image: img('trd-plumb-society'), href: '#help' },
      ] }),
      b('rates', 'services-catalogue', { title: 'Rate card', subtitle: 'Shown before you confirm. Parts at cost plus 10%, receipts attached in the app.', items: [
        { name: 'Visit and diagnosis', description: 'Waived if you go ahead with the repair on the same visit.', price: '₹350' },
        { name: 'Standard repair, first hour', description: 'Taps, traps, flush valves, angle cocks, shower mixers.', price: '₹650' },
        { name: 'Geyser service or element swap', description: 'Descale, element and thermostat test, safety valve check.', price: '₹1,100' },
        { name: 'Drain clearing, motorised', description: 'Kitchen, basin or floor trap, including a camera check.', price: '₹900' },
        { name: 'Leak detection', description: 'Acoustic and moisture-meter survey before anything is opened up.', price: '₹1,200' },
        { name: 'Night or Sunday surcharge', description: 'Added to the above between 21:00 and 07:00 and all day Sunday.', price: '+₹400' },
      ] }),
      b('book', 'booking', { title: 'Book a slot', intro: 'Two-hour windows. You get the engineer’s name, photo and mobile number as soon as it is assigned.', submitLabel: 'Request this slot', successMessage: 'Slot held. You will get an SMS with your engineer’s name within 15 minutes.', serviceLabel: 'What do you need?', services: [
        { name: 'Emergency — water everywhere', duration: '90 min window', price: '₹350 visit' },
        { name: 'Geyser or water heater', duration: '1–2 hrs', price: '₹1,100' },
        { name: 'Tap, trap or flush repair', duration: '1 hr', price: '₹650' },
        { name: 'Blocked drain', duration: '1–2 hrs', price: '₹900' },
        { name: 'Leak detection survey', duration: '2 hrs', price: '₹1,200' },
        { name: 'Quote for renovation work', duration: '30 min visit', price: 'Free' },
      ], askDate: true, askTime: true, askParty: false, askPhone: true, askNotes: true, notesLabel: 'Flat number, landmark, and what is happening' }),
      b('hours', 'hours', { title: 'When we are on', timezone: 'Asia/Kolkata', note: 'Emergency line runs 24/7 on +91 20 4860 3311 — night surcharge applies after 21:00.', days: [
        { day: 'mon', open: '07:30', close: '21:00' },
        { day: 'tue', open: '07:30', close: '21:00' },
        { day: 'wed', open: '07:30', close: '21:00' },
        { day: 'thu', open: '07:30', close: '21:00' },
        { day: 'fri', open: '07:30', close: '21:00' },
        { day: 'sat', open: '07:30', close: '19:00' },
        { day: 'sun', open: '09:00', close: '14:00' },
      ] }),
      b('help', 'faq', { title: 'Help', items: [
        { question: 'How do I pay?', answer: 'UPI, card or cash after the job is signed off in the app. Nothing is taken up front, and the invoice lands in your email the same evening.' },
        { question: 'Do you cover housing societies?', answer: 'Yes — annual contracts cover pump servicing, tank cleaning and a named engineer on call. Ask for the society rate card on +91 20 4860 3311.' },
        { question: 'What if the fix does not hold?', answer: 'Every repair carries a 90-day guarantee on our labour. Re-book in the app and the return visit is free.' },
        { question: 'Are your engineers police-verified?', answer: 'All 14 engineers are police-verified and carry photo ID. The app shows you their face before they knock.' },
      ] }),
      b('contact', 'contact-details', { title: 'Nalke Plumbing', address: 'Shop 4, Sanewadi, Aundh, Pune 411007', phone: '+91 20 4860 3311', email: 'help@nalkeplumbing.in', hours: 'Bookings 07:30–21:00 · emergency line 24/7' }),
      b('footer', 'footer', { brand: 'Nalke Plumbing', tagline: 'Plumbing and heating, booked from your phone.', links: [{ label: 'Book', href: '#book' }, { label: 'Rates', href: '#rates' }, { label: 'Help', href: '#help' }], copyright: '© Nalke Services Pvt Ltd · GSTIN 27AAGCN4410P1ZQ' }),
    ],
  }),

  // ── Painter & decorator — minimal: six blocks, one action ───────────────────
  tpl({
    id: 'trades-painter',
    vertical: 'trades',
    label: 'Painter & Decorator — Minimal',
    description: 'A two-person decorating firm with a deliberately short, calm one-pager.',
    tags: ['decorating', 'one-pager', 'gallery', 'light', 'local'],
    layout: 'minimal',
    preset: 'candy',
    meta: { title: 'Rowan & Sage — Painters and Decorators, Dublin', description: 'Careful interior decorating, heritage woodwork and wallpapering across Dublin.', lang: 'en', favicon: '🎨' },
    blocks: [
      b('nav', 'nav', { brand: 'Rowan & Sage', sticky: false, links: [{ label: 'Work', href: '#work' }, { label: 'How it goes', href: '#how' }, { label: 'Quote', href: '#quote' }] }),
      b('hero', 'hero', { eyebrow: 'Dublin 2, 4, 6 and 8', headline: 'Two coats, straight lines, and your house back by Friday', subhead: 'Interior decorating and heritage woodwork by Éabha Rowan and Cillian Sage. No subcontractors, no surprises on the invoice.', align: 'center', minHeight: 'md', overlay: 'none', cta: { label: 'Get a free quote', href: '#quote' } }),
      b('work', 'gallery', { layout: 'grid', columns: 2, gap: 'lg', lightbox: true, items: [
        { src: img('trd-paint-hall'), alt: 'Georgian hallway painted in deep green with white cornicing', caption: 'Ranelagh — hall, stairs and landing, three days' },
        { src: img('trd-paint-sash'), alt: 'Restored sash window with freshly painted glazing bars', caption: 'Portobello — eight sash windows stripped and rebuilt' },
        { src: img('trd-paint-paper'), alt: 'Feature wall in a patterned botanical wallpaper', caption: 'Rathmines — hand-trimmed paper, one wall, one day' },
        { src: img('trd-paint-kitchen'), alt: 'Hand-painted kitchen cabinets in soft blue', caption: 'Stoneybatter — kitchen re-sprayed in situ over a weekend' },
      ] }),
      b('how', 'steps', { title: 'How it goes', items: [
        { title: 'We come and look', text: 'Twenty minutes, free, evenings fine. We measure and take colour notes.' },
        { title: 'A written price', text: 'By email within 48 hours, itemised by room, including paint. It does not move.' },
        { title: 'Prep, which is most of it', text: 'Filling, sanding, caulking and masking take longer than painting and are why it lasts.' },
        { title: 'Two coats and a walk-round', text: 'You point at anything you are not happy with while we are still there, not after.' },
      ] }),
      b('quote', 'contact-form', { title: 'Get a free quote', intro: 'Tell us the rooms and we will come and look. Evening viewings are fine — most of ours are.', submitLabel: 'Ask for a price', successMessage: 'Thanks — Éabha or Cillian will text you today to arrange a look.', fields: [
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'phone', label: 'Phone', type: 'tel', required: true },
        { name: 'email', label: 'Email', type: 'email' },
        { name: 'rooms', label: 'What needs doing?', type: 'textarea', placeholder: 'e.g. hall, stairs and landing plus two bedrooms.', required: true },
      ] }),
      b('footer', 'footer', { brand: 'Rowan & Sage', tagline: 'Painters and decorators · Dublin · 087 419 2260 · hello@rowanandsage.ie', links: [{ label: 'Work', href: '#work' }, { label: 'Quote', href: '#quote' }], copyright: '© Rowan & Sage Decorating' }),
    ],
  }),

  // ── Roofer — bold: full-bleed, heavy type, storm-damage urgency ─────────────
  tpl({
    id: 'trades-roofer',
    vertical: 'trades',
    label: 'Roofer — Bold',
    description: 'A storm-damage roofing contractor leading with scale, speed and insurance help.',
    tags: ['roofing', 'emergency', 'dark', 'video', 'reviews'],
    layout: 'bold',
    preset: 'midnight',
    meta: { title: 'Ironline Roofing — Denver Storm Damage Specialists', description: 'Hail and wind damage roof replacement across the Front Range. Free inspection, insurance handled.', lang: 'en', favicon: '🏠' },
    blocks: [
      b('nav', 'nav', { brand: 'IRONLINE ROOFING', sticky: true, links: [{ label: 'Storm damage', href: '#damage' }, { label: 'Process', href: '#process' }, { label: 'Reviews', href: '#reviews' }, { label: 'Service area', href: '#area' }], cta: { label: 'Free inspection', href: '#inspect' } }),
      b('hero', 'hero', { eyebrow: 'Licensed & insured · Colorado since 1998', headline: 'Hail hit. We handle the roof and the insurance company.', subhead: 'Free 45-minute inspection, a photo-documented damage report, and a claim your adjuster cannot wave away. Most Front Range roofs replaced in one day.', align: 'center', minHeight: 'full', image: img('trd-roof-hero'), overlay: 'dark', cta: { label: 'Book a free inspection', href: '#inspect' } }),
      b('numbers', 'stats', { title: 'Since 1998', columns: 4, items: [
        { value: '11,400', label: 'Roofs replaced', suffix: '+' },
        { value: '1', label: 'Day for most tear-offs' },
        { value: '50', label: 'Workmanship warranty', suffix: ' yr' },
        { value: '0', label: 'Owed beyond your deductible', prefix: '$' },
      ] }),
      b('damage', 'features', { title: 'What hail actually does', subtitle: 'Most of it is invisible from the driveway — which is why claims get denied.', columns: 2, items: [
        { icon: '🧊', title: 'Bruised shingles', text: 'Granule loss exposes the asphalt mat. The roof looks fine and fails in 18 months.' },
        { icon: '💨', title: 'Wind-lifted seals', text: '70mph gusts break the adhesive strip. The shingle stays put until the next storm takes it.' },
        { icon: '🔩', title: 'Split ridge caps', text: 'The first thing an adjuster checks and the first thing homeowners never climb up to see.' },
        { icon: '🌧️', title: 'Flashing and boot cracks', text: 'Pipe boots go brittle at altitude. A $19 part is behind most Denver ceiling stains.' },
      ] }),
      b('film', 'video', { provider: 'youtube', src: 'aQ1mP9Xr7Kc', title: 'A full tear-off in one day, filmed in Aurora', poster: img('trd-roof-video-poster'), caption: 'Sixteen crew, 6:40am to 4:15pm, 34 squares of impact-resistant shingle.' }),
      b('process', 'steps', { title: 'From hailstorm to new roof', subtitle: 'You make two phone calls. We make the rest.', items: [
        { title: 'Free inspection, 45 minutes', text: 'We photograph every slope, the gutters, the screens and the AC fins — the collateral evidence adjusters look for.' },
        { title: 'You file the claim', text: 'We hand you a report with the storm date, hail size from NOAA data, and a Xactimate estimate. You call your carrier.' },
        { title: 'We meet your adjuster on the roof', text: 'Every time. Claims where the contractor is present get approved at a materially higher rate, and we will not send you up there alone.' },
        { title: 'Tear-off and replacement', text: 'One day for most homes. Magnetic sweep of the yard twice before we leave.' },
        { title: 'Final inspection and warranty', text: 'City inspection scheduled by us, 50-year workmanship warranty registered in your name.' },
      ] }),
      b('reviews', 'reviews', { title: 'Front Range homeowners', average: '4.8', count: '1,043 reviews', source: 'Google', items: [
        { rating: 5, quote: 'Our carrier denied us flat. Ironline came back out, met the second adjuster on the roof with their photos, and the claim was approved that afternoon. Full replacement.', author: 'Denise R.', date: 'Sep 14', source: 'google' },
        { rating: 5, quote: 'Crew showed at 6:40am, done by 4pm, and I found exactly one nail in the yard afterward. My neighbor hired them the next week.', author: 'Anthony V.', date: 'Aug 2', source: 'google' },
        { rating: 5, quote: 'They told me my roof did NOT have claimable damage and to wait. A roofer who talks you out of a job is a roofer I called back two years later.', author: 'Kim H.', date: 'Jul 21', source: 'google' },
      ] }),
      b('insurance', 'accordion', { title: 'The insurance questions', items: [
        { heading: 'Will my premium go up if I file?', body: 'Hail is classed as an act of God in Colorado, so a single storm claim does not rate against you the way an at-fault liability claim does. Multiple claims across a short window can affect renewal, which is worth a conversation with your agent before you file.' },
        { heading: 'What is a deductible and what will I actually pay?', body: 'Your policy has either a flat deductible or a percentage of the dwelling coverage — on a $600,000 home a 1% wind/hail deductible is $6,000. You pay that. We invoice the carrier for the rest. Anyone offering to "eat your deductible" is committing insurance fraud in this state and will not be around to honor the warranty.' },
        { heading: 'How long do I have to file after a storm?', body: 'Colorado gives you one year from the date of loss for hail and wind. Do not wait — the longer you leave it, the harder it is to tie the damage to a specific dated storm.' },
        { heading: 'Do I have to use the contractor my insurer suggests?', body: 'No. Preferred-vendor lists exist for the carrier’s convenience, not yours. You choose who works on your house.' },
      ] }),
      b('area', 'map', { query: 'Denver, Colorado', zoom: 9, height: 420, label: 'Denver metro, Aurora, Lakewood, Arvada, Boulder, Castle Rock and Longmont' }),
      b('yard', 'directions', { title: 'Yard and office', place: 'Ironline Roofing', address: '4820 Fox Street, Denver, CO 80216', lat: '39.7860', lng: '-104.9930', directionsLabel: 'Open in Maps', appleMaps: true }),
      b('cta', 'cta', { headline: 'Storm came through your block?', subhead: 'The inspection is free and takes 45 minutes. There is no obligation and no sales pitch on the ladder.', background: 'primary', button: { label: 'Book a free inspection', href: '#inspect' } }),
      b('inspect', 'contact-form', { title: 'Book a free inspection', intro: 'We will come out within two business days — sooner if there is active water coming in.', submitLabel: 'Book my inspection', successMessage: 'Booked. Someone from the Denver office will call you within one business day.', fields: [
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'phone', label: 'Phone', type: 'tel', required: true },
        { name: 'address', label: 'Property address', type: 'text', required: true },
        { name: 'issue', label: 'What are you seeing?', type: 'select', required: true, options: ['Hail damage after a storm', 'Wind damage or missing shingles', 'Active leak into the house', 'Claim already denied — second opinion', 'Roof is just old', 'Gutters or siding'] },
        { name: 'notes', label: 'Anything else', type: 'textarea', placeholder: 'Storm date, and whether you have already filed.' },
      ] }),
      b('contact', 'contact-details', { title: 'Ironline Roofing', address: '4820 Fox Street, Denver, CO 80216', phone: '(303) 555-0184', email: 'inspect@ironlineroofing.com', hours: 'Mon–Fri 7:00–18:00 MT · Sat 8:00–13:00 · storm response 24/7' }),
      b('footer', 'footer', { brand: 'Ironline Roofing', tagline: 'Storm damage specialists, Front Range Colorado.', links: [{ label: 'Storm damage', href: '#damage' }, { label: 'Insurance FAQ', href: '#insurance' }, { label: 'Free inspection', href: '#inspect' }], copyright: '© Ironline Roofing LLC · CO License RC-118422' }),
    ],
  }),

  // ── Welder / metal fabricator — catalogue: the list is the page ─────────────
  tpl({
    id: 'trades-welder',
    vertical: 'trades',
    label: 'Metal Fabricator — Catalogue',
    description: 'A structural welding shop selling stock products and bespoke fabrication to trade.',
    tags: ['welding', 'fabrication', 'b2b', 'pricing', 'catalogue'],
    layout: 'catalogue',
    preset: 'mono',
    meta: { title: 'Staalwerk Rotterdam — Structural Welding & Fabrication', description: 'Certified structural steel, balustrades and bespoke metalwork from a Rotterdam workshop.', lang: 'en', favicon: '🔥' },
    blocks: [
      b('nav', 'nav', { brand: 'STAALWERK', sticky: true, links: [{ label: 'Stock', href: '#stock' }, { label: 'Fabrication', href: '#fabrication' }, { label: 'Certification', href: '#certification' }, { label: 'Quote', href: '#quote' }], cta: { label: 'Send a drawing', href: '#quote' } }),
      b('find', 'search', { layout: 'bar', placeholder: 'Search stock: balustrade, beam, gate frame…', label: 'Find a part', buttonLabel: 'Search', name: 'q', align: 'center' }),
      b('stock', 'product', { title: 'Stock items, made to order', subtitle: 'Priced ex-works, excl. 21% BTW. Lead time 5–10 working days unless marked.', columns: 3, items: [
        { name: 'Steel balustrade panel, 1000×900mm', description: 'Hot-rolled flat bar infill, welded frame, hot-dip galvanised. Building-decree compliant.', price: '€310', image: img('trd-weld-balustrade'), badge: 'In stock', ctaLabel: 'Add to quote', ctaHref: '#quote' },
        { name: 'Universal beam, cut and drilled', description: 'IPE or HEA to your schedule, cut to length, holes drilled, primed. Certificates supplied.', price: 'from €95/m', image: img('trd-weld-beam'), ctaLabel: 'Add to quote', ctaHref: '#quote' },
        { name: 'Industrial staircase, straight flight', description: '13-riser open-tread flight, checker plate treads, welded stringers, galvanised.', price: '€2,140', image: img('trd-weld-stair'), badge: '3 week lead', ctaLabel: 'Add to quote', ctaHref: '#quote' },
        { name: 'Driveway gate frame, 3.0m', description: 'Box-section frame, welded hinges, ready for timber or composite infill.', price: '€680', image: img('trd-weld-gate'), ctaLabel: 'Add to quote', ctaHref: '#quote' },
        { name: 'Mezzanine edge protection, per metre', description: 'Two-rail system with kickplate, bolt-down base, powder-coated safety yellow.', price: '€88/m', image: img('trd-weld-edge'), badge: 'In stock', ctaLabel: 'Add to quote', ctaHref: '#quote' },
        { name: 'Stainless handrail, 42.4mm', description: '316-grade for marine and exterior use, satin polished, brackets included.', price: '€64/m', was: '€79/m', image: img('trd-weld-handrail'), badge: 'Clearance', ctaLabel: 'Add to quote', ctaHref: '#quote' },
      ] }),
      b('fabrication', 'services-catalogue', { title: 'Bespoke fabrication', subtitle: 'Send a DXF, a STEP file or a sketch on the back of a delivery note. All three work.', items: [
        { name: 'Structural steelwork', description: 'Beams, columns, portal frames and connections to EN 1090 EXC2, with CE marking and a declaration of performance.', price: 'quoted per tonne', ctaLabel: 'Send drawings', ctaHref: '#quote' },
        { name: 'MIG, TIG and stick welding', description: 'Mild steel, stainless and aluminium. Coded welders for pressure and structural work.', price: '€72/hr', ctaLabel: 'Book shop time', ctaHref: '#quote' },
        { name: 'Site welding and repair', description: 'Mobile rigs across Zuid-Holland — plant repair, structural remedials, emergency call-outs.', price: '€95/hr + travel', ctaLabel: 'Call us out', ctaHref: '#quote' },
        { name: 'Laser cutting and folding', description: 'Up to 20mm mild steel, 3m bed, 100-tonne press brake. Nesting done for you.', price: 'from €45 setup', ctaLabel: 'Upload a DXF', ctaHref: '#quote' },
        { name: 'Galvanising and powder coating', description: 'Managed through our finishers — one delivery, one invoice, RAL to your spec.', price: 'at cost + 12%', ctaLabel: 'Add to quote', ctaHref: '#quote' },
        { name: 'Architectural metalwork', description: 'Staircases, canopies, screens and balustrades with the welds dressed to an exposed finish.', price: 'quoted per project', ctaLabel: 'Discuss a project', ctaHref: '#quote' },
      ] }),
      b('capacity', 'tabs', { items: [
        { label: 'Workshop', text: '1,400m² under crane in Rotterdam-Waalhaven. Two 5-tonne overhead cranes, a 3m × 1.5m fibre laser, a 100-tonne 3m press brake, plate rolls to 8mm, and eight welding bays. Two shifts, 06:00–22:00.' },
        { label: 'Materials', text: 'S235 and S355 mild steel, 304 and 316 stainless, 5083 and 6082 aluminium held in stock. Mill certificates supplied with every structural order and archived for ten years.' },
        { label: 'Tolerances', text: 'Cut length ±0.5mm, hole position ±1.0mm, fabricated assembly to EN 1090-2 class 1 unless your drawing specifies tighter. Weld inspection to EN ISO 5817 level B on request.' },
        { label: 'Logistics', text: 'Own 7.5t crane lorry for Randstad deliveries, hiab off-load included within 40km. Pallet freight elsewhere in the Benelux, typically next day.' },
      ] }),
      b('certification', 'experience', { title: 'Certification and approvals', items: [
        { role: 'EN 1090-1 Factory Production Control, EXC2', org: 'Kiwa Nederland', period: 'Certified 2016 · renewed 2024', summary: 'Covers CE marking of structural steel components up to execution class 2.', bullets: ['Annual surveillance audit', 'Welding coordinator to EN ISO 14731 on staff'] },
        { role: 'EN ISO 3834-2 — comprehensive quality requirements for fusion welding', org: 'Lloyd’s Register', period: 'Certified 2018 · renewed 2023', bullets: ['Qualified procedures for MAG, TIG and MMA', 'Six welders coded to EN ISO 9606-1'] },
        { role: 'VCA** safety certification', org: 'SSVV', period: 'Certified 2012 · renewed 2025', summary: 'Required for site work at refinery, port and utility clients across the Rotterdam basin.' },
        { role: 'ISO 9001:2015 quality management', org: 'DEKRA', period: 'Certified 2019 · renewed 2025' },
      ] }),
      b('clients', 'logos', { title: 'Working for', items: [
        { src: img('trd-weld-client-port'), alt: 'Port logistics contractor' },
        { src: img('trd-weld-client-arch'), alt: 'Rotterdam architecture practice' },
        { src: img('trd-weld-client-plant'), alt: 'Process plant operator' },
        { src: img('trd-weld-client-build'), alt: 'Regional main contractor' },
        { src: img('trd-weld-client-rail'), alt: 'Rail infrastructure supplier' },
      ] }),
      b('quote', 'contact-form', { title: 'Send a drawing, get a price', intro: 'Trade and self-build both welcome. DXF, STEP, PDF or a photo of a sketch — we quote from all of them inside two working days.', submitLabel: 'Request a quotation', successMessage: 'Received. Our estimator will come back within two working days.', fields: [
        { name: 'company', label: 'Company (leave blank if private)', type: 'text' },
        { name: 'name', label: 'Contact name', type: 'text', required: true },
        { name: 'email', label: 'Email', type: 'email', required: true },
        { name: 'phone', label: 'Telephone', type: 'tel' },
        { name: 'work', label: 'Type of work', type: 'select', required: true, options: ['Structural steelwork (EN 1090)', 'Balustrade or staircase', 'Laser cutting / folding only', 'Site welding or repair', 'Stock item from the catalogue', 'Something else'] },
        { name: 'spec', label: 'Specification', type: 'textarea', placeholder: 'Quantities, material grade, finish, delivery date.', required: true },
      ] }),
      b('terms', 'legal', { title: 'Trading documents', align: 'start', separator: '·', documents: [
        { label: 'Terms of supply', title: 'General terms of supply', content: '**1. Scope.** These terms apply to all quotations, orders and deliveries by Staalwerk Rotterdam B.V. unless varied in writing.\n\n**2. Quotations.** Quotations are valid for 30 days. Material surcharges may be applied where the European steel index moves more than 5% between quotation and order.\n\n**3. Payment.** Net 30 days for approved trade accounts. Private customers pay 50% on order and the balance before collection or dispatch.\n\n**4. Title.** Title passes on full payment. Risk passes on delivery or collection.' },
        { label: 'Warranty', title: 'Workmanship warranty', content: '**Cover.** Fabrication and welding are warranted against defective workmanship for 24 months from delivery.\n\n**Coatings.** Hot-dip galvanising is warranted by the finisher, typically 15 years in inland atmospheric conditions. Powder coating carries a 10-year colour and adhesion warranty when applied over galvanising.\n\n**Exclusions.** Mechanical damage, unauthorised modification, and corrosion arising from site cutting or drilling that has not been re-protected.' },
        { label: 'Site safety', title: 'Site working and VCA', content: '**Certification.** Staalwerk holds VCA two-star certification. All site operatives carry VCA Basisveiligheid at minimum, and supervisors hold VOL-VCA.\n\n**Hot work.** We issue our own hot-work permits and provide fire watch as standard on site welding. Client permit systems take precedence where they exist.\n\n**Insurance.** 5,000,000 EUR public and products liability. Certificate available on request.' },
      ] }),
      b('contact', 'contact-details', { title: 'Workshop', address: 'Reeweg 118, 3089 KP Rotterdam, Netherlands', phone: '+31 10 486 2270', email: 'werk@staalwerk-rotterdam.nl', hours: 'Mon–Fri 06:00–22:00 (two shifts) · Sat 07:00–13:00 collections' }),
      b('rights', 'copyright', { holder: 'Staalwerk Rotterdam B.V.', text: 'KvK 24418822 · BTW NL8140.62.111.B01 · All rights reserved.', showSymbol: true, align: 'start' }),
    ],
  }),

  // ── Tiler — profile: one named craftsperson ─────────────────────────────────
  tpl({
    id: 'trades-tiler',
    vertical: 'trades',
    label: 'Tiler — Craftsperson Profile',
    description: 'A sole-trader tile setter presented as a portfolio and credentials page.',
    tags: ['tiling', 'portfolio', 'profile', 'gallery', 'light'],
    layout: 'profile',
    preset: 'sand',
    meta: { title: 'Marisol Vega — Tile Setter, Austin TX', description: 'Large-format porcelain, natural stone and waterproofed wet rooms across Austin.', lang: 'en', favicon: '🧱' },
    blocks: [
      b('header', 'profile-header', { name: 'Marisol Vega', headline: 'Tile setter — large-format porcelain, stone and waterproofed wet areas', location: 'Austin, Texas', avatar: img('trd-tile-marisol'), summary: 'Twenty years setting tile, the last twelve on my own. I take one job at a time, I do my own waterproofing, and I do not leave a bathroom half-finished to start another. Most of my work comes from three builders and the people they built for.', contacts: [
        { type: 'phone', value: '(512) 555-0147', label: 'Call or text' },
        { type: 'email', value: 'marisol@vegatile.com' },
        { type: 'location', value: 'Austin, Round Rock, Dripping Springs' },
        { type: 'website', value: 'vegatile.com' },
      ], showDownload: true, downloadLabel: 'Download credentials', showShare: true, shareLabel: 'Share this page' }),
      b('portfolio', 'gallery', { layout: 'masonry', columns: 3, gap: 'md', lightbox: true, items: [
        { src: img('trd-tile-wetroom'), alt: 'Curbless wet room in large-format grey porcelain', caption: 'Curbless wet room, Travis Heights — linear drain, fall built in mud' },
        { src: img('trd-tile-herringbone'), alt: 'Herringbone marble floor in an entryway', caption: 'Carrara herringbone entry, Tarrytown — 2mm grout joints throughout' },
        { src: img('trd-tile-slab'), alt: 'Bookmatched porcelain slab shower wall', caption: 'Bookmatched 3m slab shower, Barton Creek' },
        { src: img('trd-tile-pool'), alt: 'Glass mosaic waterline tile on a swimming pool', caption: 'Glass mosaic waterline and spa spillway, Westlake' },
        { src: img('trd-tile-kitchen'), alt: 'Handmade zellige backsplash behind a range', caption: 'Zellige backsplash, Hyde Park — every tile hand-sorted for tone' },
        { src: img('trd-tile-heat'), alt: 'Electric underfloor heating mat before tiling', caption: 'Heated bathroom floor, Mueller — tested at four separate stages' },
      ] }),
      b('walkthroughs', 'video-gallery', { title: 'How the wet rooms are actually built', layout: 'grid', columns: 3, items: [
        { provider: 'youtube', src: 'kQ8vN2ZbT4w', title: 'Building a shower fall in a traditional mud bed', poster: img('trd-tile-vid-fall') },
        { provider: 'youtube', src: 'rM5tY7Wc1Ld', title: 'Flood-testing a wet room before a single tile goes down', poster: img('trd-tile-vid-flood') },
        { provider: 'youtube', src: 'pB3xJ9Qe6Nf', title: 'Setting a 1.6m porcelain slab without cracking it', poster: img('trd-tile-vid-slab') },
      ] }),
      b('credentials', 'experience', { title: 'Training and certification', items: [
        { role: 'Certified Tile Installer #2214', org: 'Ceramic Tile Education Foundation (CTEF)', period: 'Since 2014', summary: 'The hands-on certification, not a weekend card. Re-tested on large-format and shower assemblies.' },
        { role: 'Advanced Certification — shower receptors and membranes', org: 'CTEF / NTCA', period: '2017 and 2022', bullets: ['Bonded and traditional waterproofing assemblies', 'Curbless and linear-drain construction'] },
        { role: 'Certified installer, bonded membrane systems', org: 'Schluter-Systems', period: 'Since 2013', summary: 'Membrane and heated-floor assemblies, which is what carries the manufacturer warranty on my wet rooms.' },
        { role: 'Owner', org: 'Vega Tile', period: '2014 — present', location: 'Austin, TX', bullets: ['One job at a time, no subcontracted labour', '$2m general liability, workers comp carried', '380+ bathrooms, kitchens and floors completed'] },
        { role: 'Lead setter', org: 'Barrow & Kline Custom Homes', period: '2006 — 2014', location: 'Austin, TX', summary: 'Ran the tile crew on high-end custom builds, which is where the slab and stone work came from.' },
      ] }),
      b('materials', 'skills', { title: 'What I work in', display: 'bars', groups: [
        { name: 'Materials', items: [
          { label: 'Large-format porcelain', level: 5 },
          { label: 'Natural stone — marble, limestone', level: 5 },
          { label: 'Gauged porcelain slab', level: 4 },
          { label: 'Glass and zellige mosaic', level: 4 },
          { label: 'Terrazzo and encaustic cement', level: 3 },
        ] },
        { name: 'Assemblies', items: [
          { label: 'Bonded waterproof membrane', level: 5 },
          { label: 'Traditional mud beds', level: 5 },
          { label: 'Curbless / linear drain', level: 5 },
          { label: 'Electric underfloor heating', level: 4 },
          { label: 'Exterior and pool tile', level: 3 },
        ] },
      ] }),
      b('words', 'testimonials', { title: 'From builders and homeowners', items: [
        { quote: 'Marisol flood-tested our shower for 48 hours before setting a single tile and made us come look at the water line. Nobody else has ever shown us that.', author: 'Alicia & Dev', role: 'Travis Heights' },
        { quote: 'I have used her on eleven custom homes. She calls me when something in my design will not work rather than building it wrong and letting me find out.', author: 'Ray Kline', role: 'Barrow & Kline Custom Homes' },
        { quote: 'The zellige took three extra days because she hand-sorted every tile for tone. Worth every hour of it.', author: 'Sunni P.', role: 'Hyde Park' },
      ] }),
      b('socials', 'social-links', { title: 'Elsewhere', layout: 'row', variant: 'labeled', align: 'center', links: [
        { platform: 'instagram', href: '#', label: '@vegatile — daily progress shots' },
        { platform: 'youtube', href: '#', label: 'Wet room walkthroughs' },
        { platform: 'phone', href: '#', label: '(512) 555-0147' },
        { platform: 'email', href: '#', label: 'marisol@vegatile.com' },
      ] }),
      b('quote', 'contact-form', { title: 'Ask about your job', intro: 'I quote from photos and rough measurements, then confirm on site. Booking is usually four to seven weeks out — one job at a time is the whole point.', submitLabel: 'Send it over', successMessage: 'Thanks — a text to (512) 555-0147 will always reach me faster than email.', fields: [
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'phone', label: 'Cell', type: 'tel', required: true },
        { name: 'email', label: 'Email', type: 'email' },
        { name: 'scope', label: 'What is the job?', type: 'select', required: true, options: ['Bathroom or wet room', 'Kitchen backsplash', 'Floor — porcelain or stone', 'Pool or exterior', 'Repair or re-grout', 'Trade / builder enquiry'] },
        { name: 'detail', label: 'Details', type: 'textarea', placeholder: 'Rough square footage, tile chosen, timing.', required: true },
      ] }),
      b('footer', 'footer', { brand: 'Vega Tile', tagline: 'Marisol Vega · CTI #2214 · Austin, Texas', links: [{ label: 'Portfolio', href: '#portfolio' }, { label: 'Credentials', href: '#credentials' }, { label: 'Get a quote', href: '#quote' }], copyright: '© Vega Tile · Licensed and insured in the State of Texas' }),
    ],
  }),

  // ── Flooring & carpet fitter — conversational: the enquiry is the page ──────
  tpl({
    id: 'trades-flooring',
    vertical: 'trades',
    label: 'Flooring & Carpet Fitter — Conversational',
    description: 'A flooring fitter showing a whole customer enquiry as the main content.',
    tags: ['flooring', 'carpets', 'faq', 'reviews', 'local'],
    layout: 'conversational',
    preset: 'forest',
    meta: { title: 'Underfoot — Flooring & Carpet Fitting, Glasgow', description: 'Carpet, LVT, engineered wood and vinyl supplied and fitted across Glasgow and Lanarkshire.', lang: 'en', favicon: '🧵' },
    blocks: [
      b('nav', 'nav', { brand: 'Underfoot', sticky: true, links: [{ label: 'How it works', href: '#thread' }, { label: 'Prices', href: '#prices' }, { label: 'Reviews', href: '#reviews' }, { label: 'Measure', href: '#measure' }], cta: { label: 'Free measure', href: '#measure' } }),
      b('hero', 'hero', { eyebrow: 'Glasgow, Paisley & Lanarkshire · fitting since 2011', headline: 'Ask us anything before you commit to a floor', subhead: 'Most people message us a photo and a rough size. Here is what one of those conversations actually looks like, start to finish.', align: 'left', minHeight: 'sm', overlay: 'none', cta: { label: 'Start yours', href: '#measure' } }),
      b('thread', 'chat-thread', { title: 'A real enquiry, from photo to fitted', subtitle: 'Sent over last month. Name changed, nothing else.', participants: [
        { id: 'cust', name: 'Ishbel', role: 'user' },
        { id: 'uf', name: 'Underfoot', role: 'agent' },
      ], messages: [
        { from: 'cust', time: 'Mon 19:41', body: [
          { kind: 'text', text: 'Hi — we’ve pulled up the old carpet in the living room and there are floorboards underneath with big gaps. Can you fit LVT straight over that or does something have to go down first?' },
          { kind: 'image', src: img('trd-floor-boards'), alt: 'Bare floorboards with visible gaps between them' },
        ] },
        { from: 'uf', time: 'Mon 19:58', body: [
          { kind: 'text', text: 'Not straight over, no — LVT is only 5mm and it telegraphs every gap and every board edge within about six months. Those boards need ply first.' },
          { kind: 'list', ordered: true, items: [
            { label: '6mm plywood screwed at 150mm centres, joints staggered' },
            { label: 'Sanded flush at the sheet joins' },
            { label: 'Then LVT bonded down over the top' },
          ] },
          { kind: 'text', text: 'Adds about £14/m² and half a day. Worth it — the two failed LVT floors we get called to lift every month are both this.' },
        ] },
        { from: 'cust', time: 'Mon 20:03', body: [{ kind: 'text', text: 'That’s honest, thanks. Room is roughly 4.2m × 3.8m. Ballpark for the whole thing?' }] },
        { from: 'uf', time: 'Mon 20:14', body: [
          { kind: 'text', text: '16m² plus 10% waste, so 18m² ordered. Three options at that size, supplied and fitted, ply included:' },
          { kind: 'list', ordered: false, items: [
            { label: 'Budget LVT, 2.5mm — £760' },
            { label: 'Mid-range LVT, 4.5mm — £1,040' },
            { label: 'Premium LVT, herringbone — £1,690' },
          ] },
          { kind: 'text', text: 'All three include lifting and tipping the old underlay, the ply, beading, and the trim to the hall. No VAT surprise — the prices above are what you pay.' },
        ] },
        { from: 'cust', time: 'Mon 20:19', body: [{ kind: 'text', text: 'Middle one. How soon, and do we need to move out?' }] },
        { from: 'uf', time: 'Mon 20:26', body: [
          { kind: 'text', text: 'One day on site, and you can be in the house — just not that room. Next free slot is a week on Thursday. Want us to come and measure properly first? It is free and takes 20 minutes, and the price only moves if our tape disagrees with yours.' },
          { kind: 'buttons', items: [
            { label: 'Book a free measure', href: '#measure' },
            { label: 'See the full price list', href: '#prices' },
          ] },
        ] },
        { from: 'cust', time: 'Mon 20:27', body: [{ kind: 'text', text: 'Thursday next week works. Booked.' }] },
      ] }),
      b('prices', 'pricing', { title: 'Supplied and fitted, per square metre', subtitle: 'Includes underlay or ply, gripper, beading, door bars, and taking the old floor away.', plans: [
        { name: 'Carpet', price: '£22', period: 'per m² fitted', features: ['80/20 wool twist or polypropylene', '10mm PU underlay included', 'Grippers and door bars', 'Old carpet lifted and tipped'], ctaLabel: 'Book a measure', ctaHref: '#measure' },
        { name: 'LVT', price: 'from £42', period: 'per m² fitted', features: ['Budget 2.5mm through to 4.5mm mid-range at £58/m²', 'Ply or latex subfloor prep included', 'Herringbone and borders from £94/m²', '20-year residential wear warranty'], ctaLabel: 'Book a measure', ctaHref: '#measure', featured: true },
        { name: 'Engineered wood', price: '£72', period: 'per m² fitted', features: ['14/3mm and 20/6mm boards', 'Floated or fully bonded', 'Acoustic underlay for flats', 'Scotia or square-edge beading'], ctaLabel: 'Book a measure', ctaHref: '#measure' },
        { name: 'Sheet vinyl', price: '£31', period: 'per m² fitted', features: ['Kitchens, bathrooms and utility', 'Welded seams where needed', 'Coved skirting available', 'Slip-rated options for wet areas'], ctaLabel: 'Book a measure', ctaHref: '#measure' },
      ] }),
      b('reviews', 'reviews', { title: 'Recent jobs', average: '4.9', count: '287 reviews', source: 'Trustpilot', items: [
        { rating: 5, quote: 'Talked me out of the expensive one because the room gets almost no traffic. Fitted the cheaper floor beautifully and I have sent them to two neighbours since.', author: 'Fiona D., Shawlands', date: '11 June', source: 'trustpilot' },
        { rating: 5, quote: 'Three flights of stairs, awkward turn at the top, and the carpet joins are invisible. They were finished and gone by two o’clock.', author: 'Gordon R., Bearsden', date: '29 May', source: 'trustpilot' },
        { rating: 5, quote: 'Quoted £1,240, charged £1,240, and swept up so thoroughly I could not tell they had been in.', author: 'Nadia K., Paisley', date: '3 May', source: 'trustpilot' },
      ] }),
      b('faq', 'faq', { title: 'Before you book', items: [
        { question: 'Do I have to move the furniture?', answer: 'Small stuff yes, big stuff no — we move sofas, beds and wardrobes as part of the fit. Empty the wardrobes and disconnect anything plumbed in and we will handle the rest.' },
        { question: 'Can you fit over underfloor heating?', answer: 'Yes for LVT and most engineered wood, with a maximum surface temperature of 27°C. Solid wood and thick wool carpet are the two we would talk you out of.' },
        { question: 'What is the waste allowance about?', answer: 'Rooms are never exactly rectangular and patterned floors need matching, so we order about 10% over. You keep the offcuts — they are the repair kit for the day something gets dropped.' },
        { question: 'Do you do commercial work?', answer: 'Offices, nurseries and small retail, yes. Contract carpet tile and safety vinyl are quoted per project — email work@underfootglasgow.co.uk.' },
      ] }),
      b('cta', 'cta', { headline: 'Send us a photo and a rough size', subhead: 'You will get a real answer from a fitter, not a form response — usually the same evening.', background: 'primary', button: { label: 'Book a free measure', href: '#measure' } }),
      b('measure', 'booking', { title: 'Book a free measure', intro: 'Twenty minutes, no obligation, evenings and Saturdays available. We bring samples for whatever you are leaning towards.', submitLabel: 'Book my measure', successMessage: 'Booked — we will text to confirm the window the day before.', serviceLabel: 'What are you thinking of?', services: [
        { name: 'Carpet', duration: '20 min', price: 'from £22/m²' },
        { name: 'LVT', duration: '20 min', price: 'from £42/m²' },
        { name: 'Engineered wood', duration: '20 min', price: 'from £72/m²' },
        { name: 'Sheet vinyl', duration: '20 min', price: 'from £31/m²' },
        { name: 'Not sure — bring samples', duration: '30 min', price: 'Free' },
      ], askDate: true, askTime: true, askParty: false, askPhone: true, askNotes: true, notesLabel: 'Rooms, rough sizes, and what is down at the moment' }),
      b('contact', 'contact-details', { title: 'Underfoot', address: 'Unit 6, Nithsdale Works, Glasgow G41 2AN', phone: '+44 141 496 0088', email: 'work@underfootglasgow.co.uk', hours: 'Mon–Fri 8:00–18:00 · Sat 9:00–14:00 · measures by arrangement' }),
      b('footer', 'footer', { brand: 'Underfoot', tagline: 'Flooring and carpet fitting, Glasgow & Lanarkshire.', links: [{ label: 'Prices', href: '#prices' }, { label: 'Before you book', href: '#faq' }, { label: 'Free measure', href: '#measure' }], copyright: '© Underfoot Flooring Ltd · SC488210' }),
    ],
  }),
];
