/**
 * `transport` starter templates — people and freight on the move: executive
 * chauffeurs, airport minicabs, same-day couriers, house removals, a one-van
 * operator, and long-haul road freight.
 */
import { tpl, img, b, type Template } from './_helpers.js';

export const transportTemplates: Template[] = [
  // ── Private chauffeur / executive driver ──────────────────────────────────
  tpl({
    id: 'transport-chauffeur',
    vertical: 'transport',
    label: 'Private Chauffeur — Editorial',
    description: 'A discreet executive car service selling on quiet professionalism, fleet detail and punctuality.',
    tags: ['chauffeur', 'luxury', 'b2b', 'long-form', 'reviews'],
    layout: 'editorial',
    preset: 'mono',
    meta: {
      title: 'Meridian Private Chauffeurs — London',
      description: 'Executive chauffeur hire across London and the South East. Vetted drivers, marque saloons, fixed hourly rates.',
      lang: 'en',
      favicon: '🎩',
    },
    blocks: [
      b('nav', 'nav', {
        brand: 'Meridian',
        sticky: true,
        links: [
          { label: 'The service', href: '#story' },
          { label: 'Fleet', href: '#fleet' },
          { label: 'Rates', href: '#rates' },
          { label: 'Enquire', href: '#enquire' },
        ],
        cta: { label: 'Request a quote', href: '#enquire' },
      }),
      b('hero', 'hero', {
        eyebrow: 'Established 2011 · London & the South East',
        headline: 'The car is already outside.',
        subhead: 'A chauffeur service for people whose day has no slack in it. One vetted driver, assigned to you, who learns how you like to travel.',
        align: 'left',
        minHeight: 'md',
        overlay: 'none',
        cta: { label: 'Request a quote', href: '#enquire' },
      }),
      b('story', 'rich-text', {
        blocks: [
          { kind: 'heading', text: 'We measure ourselves in minutes, not miles' },
          { kind: 'paragraph', text: 'Meridian was started by two former close-protection drivers who were tired of being sent to the wrong terminal. Fourteen years later we still run the business the same way: a small fleet, a smaller roster of drivers, and a dispatcher who knows exactly what the M4 does at 07:20 on a Thursday.' },
          { kind: 'paragraph', text: 'Every driver on the roster holds a TfL private hire licence, an enhanced DBS check and a clean licence going back five years. They arrive twenty minutes early, they do not make conversation unless you start it, and they carry a phone charger for every connector still in production.' },
          { kind: 'quote', text: 'In 2025 we completed 4,180 journeys. Eleven of them were late. We wrote to every one of those eleven clients.' },
          { kind: 'subheading', text: 'How an account works' },
          { kind: 'bullet', text: 'A named account manager and one primary driver, with a briefed second for cover.' },
          { kind: 'bullet', text: 'Flight numbers tracked automatically — we rebook the pickup, you do not have to call.' },
          { kind: 'bullet', text: 'Monthly consolidated invoicing on 30-day terms for company accounts.' },
          { kind: 'bullet', text: 'No surge pricing, ever. The rate quoted in January is the rate on New Year’s Eve.' },
        ],
      }),
      b('fleet', 'split', {
        rows: [
          {
            title: 'Mercedes-Benz E-Class saloon',
            text: 'The default for airport runs and single-passenger city work. Rear climate control, bottled water, and a boot that genuinely takes two large cases plus a suit carrier.',
            image: img('transport-chauffeur-eclass'),
            imageAlt: 'Black executive saloon waiting at a kerb',
          },
          {
            title: 'Mercedes-Benz S-Class',
            text: 'For longer legs and client-facing journeys. Reclining rear seats, privacy glass, and a partition on request. Booked most often for board days and investor roadshows.',
            image: img('transport-chauffeur-sclass'),
            imageAlt: 'Interior of a long-wheelbase executive saloon',
          },
          {
            title: 'Mercedes-Benz V-Class · up to six',
            text: 'Conference seating or forward-facing, with room for six passengers and their luggage. The one to book when a whole team lands together.',
            image: img('transport-chauffeur-vclass'),
            imageAlt: 'Executive people carrier with conference seating',
          },
        ],
      }),
      b('rates', 'services-catalogue', {
        title: 'Rates',
        subtitle: 'All rates include waiting time, parking, tolls and the congestion charge. Quoted per vehicle, not per passenger.',
        items: [
          { name: 'Hourly — as directed', description: 'Three-hour minimum inside the M25. The driver stays with you throughout.', price: '£65/hr' },
          { name: 'Heathrow transfer', description: 'Central London to any terminal, meet-and-greet included, 60 minutes free waiting.', price: '£140' },
          { name: 'Gatwick transfer', description: 'Central London to North or South Terminal, inbound flight tracked.', price: '£165' },
          { name: 'Full day · 10 hours', description: 'One driver, one car, from your first pickup. Built for roadshows and site visits.', price: '£560' },
          { name: 'Long distance', description: 'Anywhere in mainland Britain, quoted per journey with no return-leg charge.', price: 'from £2.40/mile' },
          { name: 'Corporate account', description: 'Consolidated monthly invoicing, cost centres, 30-day terms.', price: 'By agreement' },
        ],
      }),
      b('proof', 'reviews', {
        title: 'What clients say',
        subtitle: 'Collected from account holders over the past two years.',
        average: '4.9',
        count: '212 reviews',
        source: 'Google',
        items: [
          { rating: 5, quote: 'My flight from Zurich landed 90 minutes early and the car was already there. I have no idea how. Three years on the account and I have never once had to look for the driver.', author: 'Adaeze O.', date: 'March 2026', source: 'google' },
          { rating: 5, quote: 'They quoted a flat rate for a Friday-evening run to Oxford and honoured it when the A40 turned into a car park. That is the whole reason we moved the account.', author: 'Reuben Marsh', date: 'January 2026', source: 'google' },
          { rating: 4, quote: 'Faultless driving and immaculate cars. The booking form could be quicker on a phone, which is the only reason this is not five stars.', author: 'H. Lindqvist', date: 'November 2025', source: 'trustpilot' },
        ],
      }),
      b('questions', 'faq', {
        title: 'Before you book',
        items: [
          { question: 'How far ahead do I need to book?', answer: 'For a saloon inside London, four hours is usually enough. For the S-Class or V-Class, or anything before 06:00, give us the day before. Account holders can call the dispatcher directly and we will find a way.' },
          { question: 'What happens if my flight is delayed?', answer: 'We track the inbound flight number from the moment you give it to us and move the pickup automatically. There is no charge for the delay — the free waiting period starts when the aircraft lands, not when you booked.' },
          { question: 'Do you carry child seats?', answer: 'Yes, at no extra cost. Tell us the age and weight of each child when you book and the correct seat will be fitted and checked before the driver sets off.' },
          { question: 'Can I request the same driver each time?', answer: 'That is the default on an account. You get a primary driver and a briefed second who covers leave and sickness, so someone who already knows your preferences is always available.' },
          { question: 'Are you insured for corporate passengers?', answer: 'Fully — £10m public liability and hire-and-reward insurance on every vehicle. Certificates are sent with the first invoice and reissued annually without being asked.' },
        ],
      }),
      b('enquire', 'contact-details', {
        title: 'Speak to the dispatcher',
        address: 'Meridian Private Chauffeurs, 4 Hanway Place, London W1T 1HB',
        phone: '+44 20 7946 0812',
        email: 'dispatch@meridianchauffeurs.co.uk',
        hours: 'Dispatch answered 24 hours · Accounts Mon–Fri 09:00–17:30',
      }),
      b('policies', 'legal', {
        title: 'Terms of carriage',
        align: 'center',
        documents: [
          { label: 'Cancellation policy', title: 'Cancellation policy', content: '**Cancellation**\n\nJourneys cancelled more than **4 hours** before the booked pickup are refunded in full.\n\nInside 4 hours we charge 50% of the quoted fare, which covers the driver already allocated to your job.\n\nAirport pickups are never charged when the inbound flight is cancelled by the airline.' },
          { label: 'Privacy', title: 'Privacy notice', content: '**What we hold**\n\nWe keep your name, contact details, and the pickup and drop-off points of journeys you have booked.\n\nJourney records are retained for **six years** to satisfy HMRC, then deleted.\n\nWe do not sell or share passenger data with third parties, and our drivers are contractually bound to confidentiality about who they carry and where.' },
        ],
      }),
      b('footer', 'footer', {
        brand: 'Meridian Private Chauffeurs',
        tagline: 'Executive car hire across London and the South East since 2011.',
        links: [
          { label: 'Fleet', href: '#fleet' },
          { label: 'Rates', href: '#rates' },
          { label: 'Enquire', href: '#enquire' },
        ],
        copyright: '© Meridian Private Chauffeurs Ltd · TfL PHV operator licence 00912345',
      }),
    ],
  }),

  // ── Airport taxi & minicab ────────────────────────────────────────────────
  tpl({
    id: 'transport-airport-taxi',
    vertical: 'transport',
    label: 'Airport Taxi — App',
    description: 'An airport transfer and minicab firm whose site behaves like the booking app, with fixed fares up front.',
    tags: ['taxi', 'airport', 'mobile-first', 'pricing', 'b2c'],
    layout: 'app',
    preset: 'midnight',
    meta: {
      title: 'Kerbside Cabs — Sydney Airport Transfers',
      description: 'Fixed-fare airport transfers and minicabs across Sydney. Book in the app, track your driver, pay in the car.',
      lang: 'en',
      favicon: '🚕',
    },
    blocks: [
      b('shell', 'app-shell', {
        brand: 'Kerbside',
        tabs: [
          { label: 'Book', href: '#book', icon: '🚕' },
          { label: 'Fares', href: '#fares', icon: '💲' },
          { label: 'Areas', href: '#areas', icon: '📍' },
          { label: 'Help', href: '#help', icon: '💬' },
        ],
      }),
      b('book', 'hero-app', {
        headline: 'Your fare, before you get in.',
        subhead: 'Fixed-price airport runs and around-town minicabs across Sydney. Quote in ten seconds, driver tracked door to door, no surge on New Year’s Eve.',
        installLabel: 'Get the app',
        installHref: '#',
        screenshots: [
          { src: img('transport-taxi-app-quote'), alt: 'Quote screen showing a fixed fare to Sydney Airport' },
          { src: img('transport-taxi-app-track'), alt: 'Live driver tracking on a map' },
          { src: img('transport-taxi-app-receipt'), alt: 'Emailed tax receipt with the fare broken down' },
        ],
      }),
      b('install', 'install-prompt', {
        title: 'Add Kerbside to your home screen',
        body: 'One tap to rebook your usual airport run — and it opens in the arrivals hall when the wifi will not.',
        actionLabel: 'Show me how',
        position: 'bottom',
        tone: 'promo',
        delayMs: 6000,
        platforms: ['ios-safari', 'android', 'desktop-chrome'],
      }),
      b('why', 'features', {
        title: 'Why people rebook',
        columns: 4,
        items: [
          { icon: '💲', title: 'Fixed fares', text: 'Quoted before you book and honoured in traffic. No meter, no surge multiplier.' },
          { icon: '✈️', title: 'Flight tracked', text: 'Give us the flight number and the pickup moves itself when you are delayed.' },
          { icon: '🅿️', title: '45 min free wait', text: 'From wheels-down on international arrivals, 20 minutes on domestic.' },
          { icon: '🧒', title: 'Seats on request', text: 'Baby capsules and boosters fitted free — just say so when you book.' },
        ],
      }),
      b('fares', 'pricing', {
        title: 'Fixed airport fares',
        subtitle: 'To or from Sydney Airport (SYD), any terminal. Tolls and the airport gate fee are inside the price.',
        plans: [
          {
            name: 'Sedan',
            price: '$59',
            period: 'CBD ↔ SYD',
            features: ['Up to 4 passengers', '2 large cases', '45 min free airport wait', 'Tolls and gate fee included'],
            ctaLabel: 'Book a sedan',
            ctaHref: '#book',
          },
          {
            name: 'Wagon',
            price: '$74',
            period: 'CBD ↔ SYD',
            features: ['Up to 4 passengers', '4 large cases, or golf clubs', '45 min free airport wait', 'Tolls and gate fee included', 'Our most-booked vehicle'],
            ctaLabel: 'Book a wagon',
            ctaHref: '#book',
            featured: true,
          },
          {
            name: 'Van · 7 seats',
            price: '$110',
            period: 'CBD ↔ SYD',
            features: ['Up to 7 passengers', '7 cases', '45 min free airport wait', 'Tolls and gate fee included', 'Surfboards and bikes carried'],
            ctaLabel: 'Book a van',
            ctaHref: '#book',
          },
        ],
      }),
      b('areas', 'feed', {
        title: 'Suburbs we cover, and what they cost to the airport',
        layout: 'list',
        items: [
          { title: 'Sydney CBD & The Rocks', subtitle: '20–30 min', text: 'Our busiest run. Cars staged at Circular Quay from 04:00.', badge: '$59' },
          { title: 'Bondi, Bronte & Coogee', subtitle: '25–35 min', text: 'Early flights out of the east need a 04:30 pickup — book the night before.', badge: '$72' },
          { title: 'Newtown, Marrickville & the Inner West', subtitle: '15–25 min', text: 'Closest suburbs to SYD. Same-hour bookings are almost always accepted.', badge: '$49' },
          { title: 'North Sydney, Neutral Bay & Mosman', subtitle: '35–50 min', text: 'Harbour Bridge and tunnel tolls sit inside the quoted fare.', badge: '$89' },
          { title: 'Parramatta & the Hills', subtitle: '45–60 min', text: 'Fixed fare regardless of which motorway your driver ends up taking.', badge: '$119' },
          { title: 'Cronulla & the Shire', subtitle: '30–40 min', text: 'Wagons preferred out here — most bookings are families with boards.', badge: '$79' },
        ],
      }),
      b('ontime', 'stats', {
        title: 'Last twelve months',
        columns: 4,
        items: [
          { value: '99.2', suffix: '%', label: 'Pickups on time or early' },
          { value: '186', suffix: 'k', label: 'Airport transfers completed' },
          { value: '3', suffix: ' min', label: 'Median wait after you land' },
          { value: '0', label: 'Surge-priced fares, ever' },
        ],
      }),
      b('help', 'faq', {
        title: 'Help',
        items: [
          { question: 'Where do I meet the driver at Sydney Airport?', answer: 'International (T1): the driver waits at the arrivals café opposite gate B, holding a sign with your name. Domestic (T2 and T3): kerbside priority pickup, and they text you the bay number while you are still taxiing in.' },
          { question: 'What if my bags take an hour to come out?', answer: 'International bookings include 45 minutes of free waiting from wheels-down, domestic 20. After that it is $1 per minute, capped at $30. Message the driver in the app and they will hold the car.' },
          { question: 'How do I pay?', answer: 'Card in the app, or tap in the car. Cash is fine too. A tax invoice is emailed within a minute of drop-off, which is what most people need for the expense claim.' },
          { question: 'Do you do trips that are not airport runs?', answer: 'Yes — point to point anywhere in greater Sydney, metered or fixed-quoted, whichever comes out cheaper for you. Hourly hire is $95/hr with a two-hour minimum.' },
          { question: 'Can I book the return leg now?', answer: 'Book both directions in one go and the return is 10% off. We hold the return driver even if your outbound flight changes.' },
        ],
      }),
      b('contact', 'contact-details', {
        title: 'Kerbside Cabs',
        address: 'Unit 12, 40 Bourke Road, Alexandria NSW 2015, Australia',
        phone: '+61 2 8123 4400',
        email: 'bookings@kerbsidecabs.com.au',
        hours: 'Phones answered 24/7 · Office Mon–Fri 08:00–18:00 AEST',
      }),
      b('footer', 'footer', {
        brand: 'Kerbside Cabs',
        tagline: 'Fixed-fare Sydney airport transfers since 2016.',
        links: [
          { label: 'Fares', href: '#fares' },
          { label: 'Areas', href: '#areas' },
          { label: 'Help', href: '#help' },
        ],
        copyright: '© Kerbside Cabs Pty Ltd · NSW Point to Point authorisation 41822',
      }),
    ],
  }),

  // ── Same-day courier ──────────────────────────────────────────────────────
  tpl({
    id: 'transport-courier-sameday',
    vertical: 'transport',
    label: 'Same-Day Courier — Landing',
    description: 'A single-purpose conversion page for an urgent same-day courier, built around one quote form.',
    tags: ['courier', 'same-day', 'b2b', 'emergency', 'one-pager'],
    layout: 'landing',
    preset: 'candy',
    meta: {
      title: 'Relay Same-Day — Dublin Courier',
      description: 'Dedicated same-day courier across Dublin and all 32 counties. Collected within the hour, driven direct, proof of delivery in your inbox.',
      lang: 'en',
      favicon: '⚡',
    },
    blocks: [
      b('alert', 'announcement-bar', {
        text: 'Booking before 15:00? Dublin city collections are averaging 38 minutes today.',
        linkLabel: 'Get a quote',
        href: '#quote',
        tone: 'promo',
        dismissible: true,
      }),
      b('nav', 'nav', {
        brand: 'Relay Same-Day',
        sticky: true,
        links: [
          { label: 'How it works', href: '#how' },
          { label: 'Prices', href: '#prices' },
          { label: 'Quote', href: '#quote' },
        ],
        cta: { label: 'Book a collection', href: '#quote' },
      }),
      b('hero', 'hero', {
        eyebrow: 'Dublin · nationwide · seven days',
        headline: 'It leaves within the hour and nobody else touches it.',
        subhead: 'Dedicated same-day courier. One driver, your consignment only, straight from your door to theirs — with a photo and a signature the moment it lands.',
        align: 'center',
        minHeight: 'lg',
        image: img('transport-courier-hero'),
        overlay: 'dark',
        cta: { label: 'Get a price in 30 seconds', href: '#quote' },
      }),
      b('numbers', 'stats', {
        title: 'Why urgent freight ends up with us',
        columns: 4,
        items: [
          { value: '38', suffix: ' min', label: 'Average Dublin collection time' },
          { value: '99.6', suffix: '%', label: 'Delivered same day, on promise' },
          { value: '32', label: 'Counties covered direct' },
          { value: '24', suffix: '/7', label: 'Controllers on the phone' },
        ],
      }),
      b('how', 'steps', {
        title: 'Four steps, one driver',
        subtitle: 'No depot, no sorting hub, no overnight in a cage. Your item never leaves the vehicle it was collected in.',
        items: [
          { title: 'Tell us the two addresses', text: 'Eircodes, rough weight, and how big it is. Thirty seconds on the form below, or one phone call.' },
          { title: 'Price confirmed in writing', text: 'A fixed euro figure by email or SMS before we move. It does not change because of traffic, tolls or a diversion.' },
          { title: 'Driver assigned and moving', text: 'You get their name, mobile and a live tracking link. Ring them directly if the plan changes mid-journey.' },
          { title: 'Proof of delivery, instantly', text: 'A photo at the door, the recipient’s name and signature, and a timestamp — emailed the second it is handed over.' },
        ],
      }),
      b('prices', 'services-catalogue', {
        title: 'Indicative prices',
        subtitle: 'Dedicated vehicle, one job at a time. Excludes VAT; includes fuel, tolls and 20 minutes of waiting at each end.',
        items: [
          { name: 'Dublin city centre', description: 'Inside the M50, anything up to 25kg, by car or motorbike.', price: '€38' },
          { name: 'Dublin metro & county', description: 'Swords, Tallaght, Blanchardstown, Bray and everywhere between.', price: '€55' },
          { name: 'Dublin → Cork', description: 'Direct drive, roughly three hours door to door, small van.', price: '€310' },
          { name: 'Dublin → Belfast', description: 'Cross-border paperwork handled, customs-ready documentation supplied.', price: '€245' },
          { name: 'Dedicated large van', description: 'Up to 1,200kg or eight pallet spaces, anywhere on the island.', price: '€1.35/km' },
          { name: 'Overnight scheduled run', description: 'Recurring nightly collection on contract, invoiced monthly.', price: 'from €190/night' },
        ],
      }),
      b('trust', 'reviews', {
        title: 'Sent by people who could not afford it to be late',
        average: '4.8',
        count: '340 reviews',
        source: 'Google',
        items: [
          { rating: 5, quote: 'A production line in Athlone was down waiting on a bearing. Collected in Sandyford at 11:40, on the bench by 14:05. They saved us a full shift.', author: 'Órla Byrne', date: 'April 2026', source: 'google' },
          { rating: 5, quote: 'We move legal documents that cannot be scanned. Six years, several hundred jobs, a signature every single time. That is the whole review.', author: 'D. Nwachukwu', date: 'February 2026', source: 'google' },
          { rating: 5, quote: 'Rang at 21:10 on a Sunday expecting an answering machine. A human picked up and the driver was outside in 50 minutes.', author: 'Cian Fitzgerald', date: 'December 2025', source: 'trustpilot' },
        ],
      }),
      b('quote', 'contact-form', {
        title: 'Get a fixed price',
        intro: 'Fill this in and a controller replies with a firm euro figure — usually inside five minutes in working hours. Urgent right now? Ring +353 1 526 8800.',
        submitLabel: 'Send for a price',
        successMessage: 'Got it. A controller is pricing your job now and will reply within five minutes.',
        fields: [
          { name: 'name', label: 'Your name', type: 'text', placeholder: 'Órla Byrne', required: true },
          { name: 'company', label: 'Company', type: 'text', placeholder: 'Optional' },
          { name: 'phone', label: 'Mobile', type: 'tel', placeholder: '+353 87 000 0000', required: true },
          { name: 'email', label: 'Email', type: 'email', placeholder: 'you@company.ie', required: true },
          { name: 'collection', label: 'Collection address or Eircode', type: 'text', placeholder: 'D02 XY45', required: true },
          { name: 'delivery', label: 'Delivery address or Eircode', type: 'text', placeholder: 'T12 AB34', required: true },
          { name: 'vehicle', label: 'Size of the job', type: 'select', options: ['Envelope or small parcel', 'Up to 25kg', 'Van load, up to 1 pallet', 'Van load, 2–8 pallets', 'Not sure — advise me'], required: true },
          { name: 'when', label: 'When does it need to land?', type: 'select', options: ['Immediately', 'Before noon', 'Before close of business', 'Tonight', 'Tomorrow morning'], required: true },
          { name: 'notes', label: 'Anything fragile, hazardous or awkward?', type: 'textarea', placeholder: 'Two-person lift, 2.4m long, glass' },
        ],
      }),
      b('cta', 'cta', {
        headline: 'Nothing on that form beats a phone call',
        subhead: 'Controllers answer around the clock, including Sundays and bank holidays — +353 1 526 8800.',
        background: 'accent',
        button: { label: 'Or send the form', href: '#quote' },
      }),
      b('footer', 'footer', {
        brand: 'Relay Same-Day',
        tagline: 'Dedicated same-day courier · Dublin and all 32 counties.',
        links: [
          { label: 'How it works', href: '#how' },
          { label: 'Prices', href: '#prices' },
          { label: 'Get a quote', href: '#quote' },
        ],
        copyright: '© Relay Same-Day Ltd · Broomhill Business Park, Dublin 24',
      }),
    ],
  }),

  // ── House removals / movers ───────────────────────────────────────────────
  tpl({
    id: 'transport-removals',
    vertical: 'transport',
    label: 'House Removals — Catalogue',
    description: 'A full-service removals firm led by its service list, packing packages and a free video-survey booking.',
    tags: ['removals', 'moving', 'booking', 'family', 'pricing'],
    layout: 'catalogue',
    preset: 'sand',
    meta: {
      title: 'Northgate Removals — Melbourne',
      description: 'Local and interstate house removals from Melbourne. Packing, storage, and a fixed quote after a free video survey.',
      lang: 'en',
      favicon: '📦',
    },
    blocks: [
      b('nav', 'nav', {
        brand: 'Northgate Removals',
        sticky: true,
        links: [
          { label: 'Services', href: '#services' },
          { label: 'Packages', href: '#packages' },
          { label: 'Included', href: '#included' },
          { label: 'Book a survey', href: '#survey' },
        ],
        cta: { label: 'Free video survey', href: '#survey' },
      }),
      b('hero', 'hero', {
        eyebrow: 'Melbourne · Victoria · interstate',
        headline: 'Everything you own, arriving in the condition it left.',
        subhead: 'Third-generation removalists. A free video survey, a fixed quote, and a crew that has done this five thousand times.',
        align: 'left',
        minHeight: 'sm',
        overlay: 'none',
        cta: { label: 'Book a free survey', href: '#survey' },
      }),
      b('services', 'services-catalogue', {
        title: 'What we do',
        subtitle: 'Pick the pieces you want. Most people take the move and the packing, and do their own unpacking.',
        items: [
          { name: 'Local house move', description: 'Anywhere within 60km of the Melbourne CBD. Two or three movers plus a truck, hourly after the first four hours.', price: 'from $480', ctaLabel: 'Get a quote', ctaHref: '#survey' },
          { name: 'Interstate move', description: 'Melbourne to Sydney, Brisbane, Adelaide or Perth. Fixed price, dedicated truck, no shared load unless you ask.', price: 'from $2,850', ctaLabel: 'Get a quote', ctaHref: '#survey' },
          { name: 'Full packing service', description: 'We arrive the day before with materials and pack the whole house, room by room, labelled to the destination room.', price: 'from $640' },
          { name: 'Fragile-only packing', description: 'Crockery, glassware, mirrors, artwork and the television. You do the books and the clothes.', price: 'from $260' },
          { name: 'Piano & safe moving', description: 'Uprights, grands and gun safes. Specialist crew, skates and a stair-crawler, fully insured.', price: 'from $390' },
          { name: 'Storage', description: 'Clean, alarmed, palletised storage in Coburg. Priced per week with a four-week minimum.', price: '$38/week' },
          { name: 'Dismantle & reassemble', description: 'Beds, wardrobes, trampolines, flat-pack. Fittings bagged and taped to the frame so nothing goes missing.', price: '$95/hr' },
          { name: 'Rubbish & donation run', description: 'Everything you decided not to take, dropped at a charity or the tip on the way back.', price: 'from $180' },
        ],
      }),
      b('packages', 'pricing', {
        title: 'Three ways to move',
        subtitle: 'Based on a typical three-bedroom house moving within metropolitan Melbourne. Your survey returns an exact figure.',
        plans: [
          {
            name: 'Truck & crew',
            price: '$980',
            period: 'from',
            features: ['Two movers and a 6-tonne truck', 'Blankets, straps and trolleys', 'You pack, we carry', 'Transit cover to $10,000'],
            ctaLabel: 'Book a survey',
            ctaHref: '#survey',
          },
          {
            name: 'Packed & moved',
            price: '$1,690',
            period: 'from',
            features: ['Three movers and a 10-tonne truck', 'Full packing the day before', 'All cartons and materials supplied', 'Beds dismantled and remade', 'Transit cover to $30,000'],
            ctaLabel: 'Book a survey',
            ctaHref: '#survey',
            featured: true,
          },
          {
            name: 'Door to door',
            price: '$2,450',
            period: 'from',
            features: ['Everything in Packed & moved', 'Unpacking and carton removal', 'Wardrobes hung, art rehung', 'Two weeks of storage if dates slip', 'Transit cover to $60,000'],
            ctaLabel: 'Book a survey',
            ctaHref: '#survey',
          },
        ],
      }),
      b('included', 'accordion', {
        title: 'What is included, and what is not',
        items: [
          { heading: 'Included in every quote, at no extra charge', body: 'Furniture blankets and shrink wrap. Wardrobe cartons on the day for hanging clothes. Floor and door-frame protection at both ends. Trolleys, skates and lifting straps. Fuel, tolls and travel time inside 60km. GST.' },
          { heading: 'Charged separately if you need them', body: 'Cartons you keep, from $2.80 each. Stairs above the second floor, at $45 per flight for items over 40kg. Waiting time if keys are not released, at $60 per 15 minutes. Long carries of more than 50 metres from truck to door.' },
          { heading: 'Things we cannot legally carry', body: 'Petrol, gas bottles, paint, fireworks, ammunition, pool chlorine and aerosols in quantity. Live plants across state borders — Western Australia and Tasmania quarantine them. Pets. Cash, jewellery and passports: please carry those yourself.' },
          { heading: 'Insurance, in plain words', body: 'Every job carries transit cover for accidental damage while your goods are in our care, up to the limit shown on your package. Owner-packed cartons are covered for loss, and for damage caused by an accident, but not for breakage inside a box we did not pack. If you want full replacement cover we will quote it — usually 1.4% of the declared value.' },
        ],
      }),
      b('crew', 'gallery', {
        layout: 'masonry',
        columns: 3,
        gap: 'md',
        lightbox: true,
        items: [
          { src: img('transport-removals-truck'), alt: 'Removals truck with its tailgate down outside a weatherboard house', caption: 'The 10-tonne, loaded and blanketed' },
          { src: img('transport-removals-packing'), alt: 'Cartons labelled by destination room stacked in a hallway', caption: 'Every carton labelled to the room it lands in' },
          { src: img('transport-removals-piano'), alt: 'Movers walking an upright piano down front steps on skates', caption: 'Piano crew, Fitzroy North' },
          { src: img('transport-removals-storage'), alt: 'Palletised household storage racked in a warehouse', caption: 'Coburg storage — alarmed, racked, dry' },
        ],
      }),
      b('voices', 'testimonials', {
        title: 'From the last hundred moves',
        items: [
          { quote: 'Four bedrooms, two cats, and a settlement date that moved twice. They rebooked us without a word about it and did not charge for the change.', author: 'Meera & Josh', role: 'Brunswick to Ocean Grove' },
          { quote: 'The quote after the video survey was $1,740. The invoice was $1,740. I have moved six times and that has never once happened before.', author: 'Toby Ellery', role: 'Richmond to Carlton' },
          { quote: 'They wrapped my grandmother’s dresser like it was going to the moon. Not a mark on it after 900 kilometres.', author: 'Sandra V.', role: 'Melbourne to Adelaide' },
        ],
      }),
      b('survey', 'booking', {
        title: 'Book a free video survey',
        intro: 'Twenty minutes on a video call walking us through the house. You get a fixed written quote the same day — no doorstep sales, no obligation.',
        submitLabel: 'Request my survey',
        successMessage: 'Thanks — a surveyor will text you within a business hour to lock in a time.',
        serviceLabel: 'What are you moving?',
        services: [
          { name: 'Apartment, 1–2 bedrooms', duration: '15 min survey', price: 'from $480' },
          { name: 'House, 3 bedrooms', duration: '20 min survey', price: 'from $980' },
          { name: 'House, 4+ bedrooms', duration: '30 min survey', price: 'from $1,450' },
          { name: 'Interstate move', duration: '30 min survey', price: 'from $2,850' },
          { name: 'Office or commercial', duration: '30 min survey', price: 'Quoted' },
          { name: 'Storage only', duration: '10 min survey', price: '$38/week' },
        ],
        askDate: true,
        askTime: true,
        askParty: false,
        askPhone: true,
        askNotes: true,
        notesLabel: 'Stairs, narrow access, a piano — anything we should plan for?',
      }),
      b('contact', 'contact-details', {
        title: 'Northgate Removals',
        address: '31 Sydney Road, Coburg VIC 3058, Australia',
        phone: '+61 3 9388 7100',
        email: 'move@northgateremovals.com.au',
        hours: 'Mon–Fri 07:00–18:00 · Sat 08:00–14:00 · Sun by arrangement',
      }),
      b('footer', 'footer', {
        brand: 'Northgate Removals',
        tagline: 'Melbourne removalists, three generations in.',
        links: [
          { label: 'Services', href: '#services' },
          { label: 'Packages', href: '#packages' },
          { label: 'Book a survey', href: '#survey' },
        ],
        copyright: '© Northgate Removals Pty Ltd · AFRA member 08841',
      }),
    ],
  }),

  // ── Van & driver (single-operator) ────────────────────────────────────────
  tpl({
    id: 'transport-van-and-driver',
    vertical: 'transport',
    label: 'Van & Driver — Minimal',
    description: 'A one-person van operator with a short, honest page: the rate, what fits, and how to get hold of them.',
    tags: ['van-and-driver', 'local', 'budget', 'mobile-first', 'one-pager'],
    layout: 'minimal',
    preset: 'forest',
    meta: {
      title: 'Row’s Van — Bristol',
      description: 'One person, one Luton van, all of Bristol. Single items, small moves and tip runs, seven days a week.',
      lang: 'en',
      favicon: '🚐',
    },
    blocks: [
      b('nav', 'nav', {
        brand: 'Row’s Van',
        sticky: false,
        links: [
          { label: 'Prices', href: '#prices' },
          { label: 'Reviews', href: '#reviews' },
          { label: 'Contact', href: '#contact' },
        ],
        cta: { label: 'Text me', href: '#contact' },
      }),
      b('hero', 'hero', {
        eyebrow: 'Bristol & 20 miles around · seven days',
        headline: 'One van. One person. £35 an hour.',
        subhead: 'I am Row. I run a long-wheelbase Luton with a tail lift, and I move the things that are too big for your car and too small for a removals firm. Text me a photo and I will tell you if it fits.',
        align: 'center',
        minHeight: 'md',
        image: img('transport-vanman-hero'),
        overlay: 'scrim',
        cta: { label: 'Text a photo to 07700 900412', href: '#contact' },
      }),
      b('prices', 'services-catalogue', {
        title: 'What it costs',
        subtitle: 'One hour minimum, then billed in fifteen-minute blocks. Fuel is in the rate. Cash, bank transfer or card in the van.',
        items: [
          { name: 'Just me and the van', description: 'You help load and unload. The cheapest way to do it, and what most people choose.', price: '£35/hr' },
          { name: 'Me plus a hand', description: 'I bring a second pair of hands for anything heavy, awkward, or up more than one flight of stairs.', price: '£55/hr' },
          { name: 'Single item collection', description: 'A sofa off Marketplace, a bed from IKEA at Cribbs, a fridge from your parents.', price: 'from £45' },
          { name: 'Tip run', description: 'Loaded, driven to the Avonmouth recycling centre and disposed of properly. Tip fees at cost.', price: 'from £60' },
          { name: 'Student move', description: 'One room to another across the city, term-time weekends included. Bring your own bags.', price: '£70 flat' },
          { name: 'Outside Bristol', description: 'Bath, Gloucester, Cardiff, Exeter — anywhere, really. Quoted per job, one way only.', price: '£1.10/mile' },
        ],
      }),
      b('reviews', 'reviews', {
        title: 'What people say afterwards',
        average: '5.0',
        count: '96 reviews',
        source: 'Google',
        items: [
          { rating: 5, quote: 'Texted Row a photo of a wardrobe at 9am, it was in my flat by 1pm, and they carried it up three floors without a single complaint. £70 all in.', author: 'Kwame A.', date: 'May 2026', source: 'google' },
          { rating: 5, quote: 'Turned up when they said, charged what they said, and helped me flat-pack a bed frame that was never going to fit otherwise. Genuinely lovely.', author: 'Lucy Trent', date: 'March 2026', source: 'google' },
          { rating: 5, quote: 'Cleared my late dad’s garage over two trips. Row was patient, careful with the bits I wanted to keep, and did not rush me once.', author: 'Peter M.', date: 'February 2026', source: 'facebook' },
        ],
      }),
      b('when', 'hours', {
        title: 'When I am on the road',
        timezone: 'Europe/London',
        note: 'Text any time — I read them between jobs and reply at the next stop. Sunday is single items and tip runs only, no full moves.',
        days: [
          { day: 'mon', open: '07:00', close: '20:00' },
          { day: 'tue', open: '07:00', close: '20:00' },
          { day: 'wed', open: '07:00', close: '20:00' },
          { day: 'thu', open: '07:00', close: '20:00' },
          { day: 'fri', open: '07:00', close: '20:00' },
          { day: 'sat', open: '08:00', close: '18:00' },
          { day: 'sun', open: '10:00', close: '16:00' },
        ],
      }),
      b('contact', 'contact-details', {
        title: 'Get hold of me',
        address: 'Based in Bedminster, BS3 — covering every Bristol postcode and 20 miles around',
        phone: '07700 900412',
        email: 'row@rowsvan.co.uk',
        hours: 'Text any time · Calls 07:00–20:00, seven days',
      }),
      b('social', 'social-links', {
        title: 'Or find me where you already are',
        layout: 'row',
        variant: 'labeled',
        align: 'center',
        links: [
          { platform: 'whatsapp', href: '#', label: 'WhatsApp a photo' },
          { platform: 'facebook', href: '#', label: 'Bristol Buy & Sell regular' },
          { platform: 'instagram', href: '#', label: '@rowsvan' },
          { platform: 'phone', href: '#', label: '07700 900412' },
        ],
      }),
      b('footer', 'footer', {
        brand: 'Row’s Van',
        tagline: 'One van, one driver, all of Bristol. Fully insured, goods in transit to £10,000.',
        links: [
          { label: 'Prices', href: '#prices' },
          { label: 'Hours', href: '#when' },
          { label: 'Contact', href: '#contact' },
        ],
        copyright: '© Row’s Van, Bristol',
      }),
    ],
  }),

  // ── Freight & haulage ─────────────────────────────────────────────────────
  tpl({
    id: 'transport-freight-haulage',
    vertical: 'transport',
    label: 'Freight & Haulage — Bold',
    description: 'A road freight operator pitching fleet capacity, compliance and on-time performance to shippers.',
    tags: ['freight', 'haulage', 'logistics', 'b2b', 'dark'],
    layout: 'bold',
    preset: 'ocean',
    meta: {
      title: 'Vanguard Freight Lines — Regional Road Freight',
      description: 'Full-truckload and LTL road freight across the Midwest and Great Lakes. 140 power units, 99.4% on-time, real-time visibility.',
      lang: 'en',
      favicon: '🚚',
    },
    blocks: [
      b('nav', 'nav', {
        brand: 'Vanguard Freight Lines',
        sticky: true,
        links: [
          { label: 'Capacity', href: '#capacity' },
          { label: 'Lanes', href: '#lanes' },
          { label: 'Performance', href: '#performance' },
          { label: 'History', href: '#history' },
        ],
        cta: { label: 'Request capacity', href: '#rfp' },
      }),
      b('hero', 'hero', {
        eyebrow: 'DOT 2214087 · MC 771540 · SmartWay carrier',
        headline: 'Freight that shows up in the hour it said it would.',
        subhead: '140 power units and 420 trailers running the Midwest and Great Lakes. Dry van, reefer and flatbed, dispatched from four terminals, tracked to the minute.',
        align: 'center',
        minHeight: 'full',
        image: img('transport-freight-hero'),
        overlay: 'dark',
        cta: { label: 'Request capacity', href: '#rfp' },
      }),
      b('performance', 'stats', {
        title: 'Trailing twelve months',
        columns: 4,
        items: [
          { value: '99.4', suffix: '%', label: 'On-time delivery, shipper-confirmed' },
          { value: '140', label: 'Company power units' },
          { value: '0.61', label: 'DOT recordable rate per million miles' },
          { value: '18', label: 'Average driver tenure, months' },
        ],
      }),
      b('shippers', 'logos', {
        title: 'Moving freight for',
        items: [
          { src: img('transport-freight-logo-mill'), alt: 'Harrow Mills', href: '#' },
          { src: img('transport-freight-logo-cold'), alt: 'Bluewater Cold Storage', href: '#' },
          { src: img('transport-freight-logo-steel'), alt: 'Calumet Steel Products', href: '#' },
          { src: img('transport-freight-logo-grocer'), alt: 'Fairfield Grocery Group', href: '#' },
          { src: img('transport-freight-logo-parts'), alt: 'Meridian Auto Parts', href: '#' },
        ],
      }),
      b('capacity', 'tabs', {
        items: [
          { label: 'Dry van', text: '96 units of 53-foot dry van: air-ride, swing and roll doors, e-track throughout, load locks and 24 straps on every trailer. Drop-and-hook at the Chicago, Columbus and Milwaukee terminals with a standing trailer pool — we currently hold 140 spotted trailers for contract customers. Typical full-truckload lane cost runs $2.35 to $2.90 per mile all-in depending on lane balance, quoted firm for the length of the contract.' },
          { label: 'Refrigerated', text: '28 units of 53-foot multi-temp reefer on Carrier Vector units with two-way telematics. Continuous temperature logging every five minutes, downloadable as a PDF or pushed straight into your TMS over the API. Full FSMA Sanitary Transport compliance, washout records retained twelve months, and pre-cool verification photographed at every pickup. Frozen, chilled and produce protocols run separately — we do not co-load them.' },
          { label: 'Flatbed & step deck', text: '16 units split between 48-foot flatbed and 53-foot step deck, all with Conestoga rolling-tarp options. Coil racks, pipe stakes, chains and twelve straps as standard. Drivers are certified on securement to FMCSA 393 subpart I, and every load is photographed after securement before the truck rolls. Oversize permitting is handled in-house for Illinois, Indiana, Ohio, Michigan and Wisconsin.' },
          { label: 'LTL & partials', text: 'Consolidated partials from 6 to 24 linear feet on scheduled lanes, moving overnight between our four terminals. No hub-and-spoke re-handling beyond a single cross-dock, which is why our LTL damage rate sits at 0.08%. Pallet-level scanning at every touch, with a shipper portal showing position and ETA. Best value on Chicago–Columbus and Milwaukee–Indianapolis.' },
        ],
      }),
      b('lanes', 'feed', {
        title: 'Core lanes and current transit',
        layout: 'cards',
        items: [
          { title: 'Chicago, IL → Columbus, OH', subtitle: '355 miles · solo driver', text: 'Two departures nightly, 19:00 and 23:00. Delivery windows from 06:00.', badge: 'Next day' },
          { title: 'Milwaukee, WI → Indianapolis, IN', subtitle: '280 miles · solo driver', text: 'Nightly departure at 20:30, drop-and-hook at both ends.', badge: 'Next day' },
          { title: 'Detroit, MI → St. Louis, MO', subtitle: '530 miles · solo driver', text: 'Departs 16:00, delivers next morning. Reefer capacity available on this lane.', badge: 'Next day' },
          { title: 'Chicago, IL → Dallas, TX', subtitle: '925 miles · teams available', text: 'Solo runs deliver in two days; teams cover it in 22 hours for time-critical freight.', badge: '2 day' },
          { title: 'Cleveland, OH → Atlanta, GA', subtitle: '715 miles · solo driver', text: 'Departs 14:00 Mon, Wed and Fri, with flatbed and dry van both scheduled.', badge: '2 day' },
          { title: 'Great Lakes regional', subtitle: 'Under 250 miles', text: 'Same-day and next-morning inside the five-state footprint, dispatched hourly.', badge: 'Same day' },
        ],
      }),
      b('walkthrough', 'video', {
        provider: 'youtube',
        src: 'kXYiU_JCYtU',
        title: 'Inside the Chicago cross-dock',
        poster: img('transport-freight-terminal'),
        caption: 'Six minutes through the Chicago terminal: gate-in, scan, cross-dock, seal and gate-out.',
      }),
      b('history', 'timeline', {
        title: 'How we got here',
        items: [
          { date: '1998', title: 'Two trucks and a gravel yard', text: 'Started hauling steel out of Calumet with a pair of secondhand Freightliners and exactly one customer.' },
          { date: '2006', title: 'First terminal', text: 'Bought the Chicago cross-dock on 88th Street. The fleet reached 30 power units and the first refrigerated trailers arrived.' },
          { date: '2013', title: 'SmartWay certification', text: 'Joined the EPA SmartWay program and specced the whole fleet to 65mph with auxiliary power units, cutting fuel burn 11%.' },
          { date: '2018', title: 'ELD and full visibility', text: 'Deployed electronic logging and two-way trailer telematics ahead of the federal mandate. Shippers got live tracking the same year.' },
          { date: '2022', title: 'Four terminals', text: 'Opened Columbus and Milwaukee, added Detroit through acquisition, and launched scheduled LTL lanes between all four.' },
          { date: '2026', title: 'Electric drayage pilot', text: 'Twelve battery-electric tractors running short-haul drayage out of Chicago, with the terminal on a 2MW charging yard.' },
        ],
      }),
      b('where', 'map', {
        query: 'S 88th St & Stony Island Ave, Chicago, IL 60617',
        zoom: 12,
        height: 380,
        label: 'Vanguard Freight Lines — Chicago terminal and cross-dock',
      }),
      b('rfp', 'contact-form', {
        title: 'Request capacity or submit an RFP',
        intro: 'Tell us the lanes and the volume. Pricing comes back within two business days, and bid packets go to a named account team, not a portal.',
        submitLabel: 'Send to pricing',
        successMessage: 'Received. A pricing analyst will be in touch within two business days.',
        fields: [
          { name: 'name', label: 'Name', type: 'text', placeholder: 'Dana Whitfield', required: true },
          { name: 'company', label: 'Company', type: 'text', placeholder: 'Fairfield Grocery Group', required: true },
          { name: 'email', label: 'Work email', type: 'email', placeholder: 'you@company.com', required: true },
          { name: 'phone', label: 'Phone', type: 'tel', placeholder: '(312) 555-0142' },
          { name: 'equipment', label: 'Equipment needed', type: 'select', options: ['Dry van', 'Refrigerated', 'Flatbed or step deck', 'LTL / partial', 'Mixed'], required: true },
          { name: 'volume', label: 'Weekly volume', type: 'select', options: ['Under 5 loads', '5–20 loads', '20–75 loads', '75+ loads'], required: true },
          { name: 'lanes', label: 'Origin and destination lanes', type: 'textarea', placeholder: 'Chicago, IL 60617 → Columbus, OH 43004, 12 loads/wk', required: true },
          { name: 'rfp', label: 'This is a formal RFP with a bid deadline', type: 'checkbox' },
        ],
      }),
      b('contact', 'contact-details', {
        title: 'Vanguard Freight Lines',
        address: '2400 E 88th Street, Chicago, IL 60617, United States',
        phone: '(312) 555-0180',
        email: 'pricing@vanguardfreightlines.com',
        hours: 'Dispatch 24/7/365 · Pricing and accounts Mon–Fri 07:00–18:00 CT',
      }),
      b('footer', 'footer', {
        brand: 'Vanguard Freight Lines',
        tagline: 'Regional road freight across the Midwest and Great Lakes since 1998.',
        links: [
          { label: 'Capacity', href: '#capacity' },
          { label: 'Lanes', href: '#lanes' },
          { label: 'Request capacity', href: '#rfp' },
        ],
        copyright: '© Vanguard Freight Lines, Inc. · DOT 2214087 · MC 771540',
      }),
    ],
  }),
];
