/**
 * PWA layer (§7) — derive an installable app shell from the `SiteManifest`.
 *
 * Two emitted artifacts sit alongside the rendered HTML:
 *   - `manifest.webmanifest` — name/icons/colors/display, defaulted from meta +
 *     design tokens so a bare `pwa: {}` already produces a valid, installable
 *     manifest;
 *   - `sw.js` — a tiny precache + offline-fallback service worker.
 *
 * Both are total (never throw) and host-neutral: the host serves the returned
 * files at `/manifest.webmanifest` and `/sw.js`. `emitPwa` returns null when the
 * manifest does not opt into PWA, so callers can `if (files) writeAll(files)`.
 */
import { normalizeTokens } from './tokens.js';
import type { PwaConfig, SiteManifest } from './types.js';

export interface WebAppManifest {
  name: string;
  short_name: string;
  description?: string;
  start_url: string;
  scope: string;
  display: string;
  theme_color: string;
  background_color: string;
  icons: Array<{ src: string; sizes: string; type?: string; purpose?: string }>;
}

const DEFAULT_ICONS = [
  { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
  { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
  { src: '/icons/icon-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
];

/** Build the Web App Manifest object from meta + design tokens + `pwa` opts. */
export function buildWebManifest(manifest: SiteManifest): WebAppManifest {
  const pwa: PwaConfig = manifest?.pwa ?? {};
  const tokens = normalizeTokens(manifest?.design);
  const name = pwa.name || manifest?.meta?.title || 'App';
  return {
    name,
    short_name: pwa.shortName || name.slice(0, 12),
    ...(pwa.description || manifest?.meta?.description
      ? { description: pwa.description || manifest!.meta.description }
      : {}),
    start_url: pwa.startUrl || '/',
    scope: pwa.scope || '/',
    display: pwa.display || 'standalone',
    theme_color: pwa.themeColor || tokens.palette.primary,
    background_color: pwa.backgroundColor || tokens.palette.bg,
    icons: pwa.icons && pwa.icons.length ? pwa.icons : DEFAULT_ICONS,
  };
}

/** Serialized `manifest.webmanifest` content. */
export function buildWebManifestJson(manifest: SiteManifest): string {
  return JSON.stringify(buildWebManifest(manifest), null, 2) + '\n';
}

/**
 * A minimal, dependency-free service worker: precache the app shell, serve
 * cache-first for same-origin GETs, and fall back to the cached shell offline.
 * The cache name is derived from the manifest `version` so a new publish
 * invalidates the old cache deterministically (no timestamps — reproducible).
 */
export function buildServiceWorker(manifest: SiteManifest): string {
  const version = typeof manifest?.version === 'number' ? manifest.version : 1;
  const cache = `weblocks-v${version}`;
  const shell = JSON.stringify(['/', '/manifest.webmanifest']);
  return `// Auto-generated by @bytesbrains/weblocks (PWA layer). Do not edit by hand.
const CACHE='${cache}';
const SHELL=${shell};
self.addEventListener('install',function(e){e.waitUntil(caches.open(CACHE).then(function(c){return c.addAll(SHELL)}).then(function(){return self.skipWaiting()}))});
self.addEventListener('activate',function(e){e.waitUntil(caches.keys().then(function(keys){return Promise.all(keys.filter(function(k){return k!==CACHE}).map(function(k){return caches.delete(k)}))}).then(function(){return self.clients.claim()}))});
self.addEventListener('fetch',function(e){
  var req=e.request;
  if(req.method!=='GET'||new URL(req.url).origin!==self.location.origin)return;
  e.respondWith(caches.match(req).then(function(hit){
    return hit||fetch(req).then(function(res){
      var copy=res.clone();caches.open(CACHE).then(function(c){c.put(req,copy)});return res;
    }).catch(function(){return caches.match('/')});
  }));
});
`;
}

/** Files to serve for an installable PWA, or null when not opted in. */
export function emitPwa(manifest: SiteManifest): Record<string, string> | null {
  if (!manifest?.pwa) return null;
  const files: Record<string, string> = {
    'manifest.webmanifest': buildWebManifestJson(manifest),
  };
  if (manifest.pwa.offline !== false) files['sw.js'] = buildServiceWorker(manifest);
  return files;
}
